-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 19 de 31 | filas 7201-7600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('13542','COLEGIO IRMA SALAS SILVA','Coquimbo','PUNITAQUI','Part. Subvencionado'),
('13543','ESCUELA ESPECIAL KIMELTU','Coquimbo','OVALLE','Part. Subvencionado'),
('13544','JARDIN INFANTIL CASCANUECES','Coquimbo','COQUIMBO','Part. Pagado'),
('13545','ESCUELA BASICA SAN FRANCISCO DE BORJA','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('13551','COLEGIO MANANTIAL','Coquimbo','OVALLE','Part. Subvencionado'),
('13552','COLEGIO CRISTIANO LA SERENA','Coquimbo','LA SERENA','Part. Subvencionado'),
('13553','COLEGIO SANTA HELENA COLLEGE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13554','ESCUELA ESPECIAL KREATIVITAS','Coquimbo','LA SERENA','Part. Subvencionado'),
('13557','ESCUELA BASICA REPUBLICA DE ITALIA','Coquimbo','COQUIMBO','Servicio Local'),
('13558','INSTITUTO DE ADM. Y COMERCIO ESTADO DE ISRAEL','Coquimbo','COQUIMBO','Servicio Local'),
('13559','ESCUELA REPUBLICA DE GRECIA','Coquimbo','COQUIMBO','Servicio Local'),
('13560','ESCUELA PADRE ALBERTO HURTADO CRUCHAGA','Coquimbo','COQUIMBO','Servicio Local'),
('13561','LIC.DE CIENC.Y HUM.SAN JOSEMARIA ESCRIVA','Coquimbo','COQUIMBO','Servicio Local'),
('13562','ESCUELA JUAN PABLO II','Coquimbo','COQUIMBO','Servicio Local'),
('13563','COLEGIO NUESTRA SEÑORA DEL ROSARIO','Coquimbo','ANDACOLLO','Servicio Local'),
('13565','COLEGIO MANANTIALES DE ELQUI','Coquimbo','LA SERENA','Part. Subvencionado'),
('13566','ESCUELA SAN LORENZO','Coquimbo','ANDACOLLO','Part. Subvencionado'),
('13567','ESC.ESP.DE TRAS.ESPEC. DEL LENGUAJE RINCON DE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13568','ESC.ESP.DE TRAST.ESPEC.DE LENGUAJE AMANKAY','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13569','ESCUELA ESPECIAL RAYEN','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13570','ESCUELA MUNICIPAL VILLA SANTA ROSA','Coquimbo','SALAMANCA','Corp. Municipal'),
('13572','JARDIN INFANTIL EL MUNDO DE LOS PELUSITAS','Coquimbo','OVALLE','Part. Pagado'),
('13573','COLEGIO TAMELCURA','Coquimbo','OVALLE','Part. Subvencionado'),
('13574','COLEGIO CERVANTES','Coquimbo','LA SERENA','Part. Pagado'),
('13575','ESCUELA ESPECIAL Y DE LENGUAJE PADRE ALBERTO HURTADO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13576','LICEO TECNICO PROFESIONAL EDUCADOR JUAN BAUTISTA DE LA SALLE','Coquimbo','LA SERENA','Servicio Local'),
('13577','ESCUELA ESPECIAL CONDEMARIN','Coquimbo','LA SERENA','Part. Subvencionado'),
('13579','COLEGIO SAN ISIDRO','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('13580','COLEGIO PAULO FREIRE','Coquimbo','LA SERENA','Part. Subvencionado'),
('13582','COLEGIO TECNICO PROFESIONAL FLORENCIA NIGHTIN','Coquimbo','LA SERENA','Part. Subvencionado'),
('13584','ESCUELA PARA ADULTOS AMIGOS DEL PADRE HURTADO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13586','COLEGIO CHRIST SCHOOL','Coquimbo','LA SERENA','Part. Subvencionado'),
('13590','COLEGIO DE ADMINISTRACION Y COMERCIO EL INGENIO','Coquimbo','OVALLE','Corp. Municipal'),
('13591','CENTRO INTEGRAL DE ADULTOS LIMARI','Coquimbo','OVALLE','Corp. Municipal'),
('13592','LICEO TECNICO PROF. ADULTOS CORESOL DE LA SER','Coquimbo','LA SERENA','Part. Subvencionado'),
('13593','COLEGIO EUSEBIO LILLO PUNTA MIRA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13597','ESCUELA ESP DE TRASTORNO DEL LENGUAJE VALLE D','Coquimbo','OVALLE','Part. Subvencionado'),
('13598','ESCUELA ESPECIAL DEL ARTE DE HABLAR','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13601','ESCUELA ESPECIAL DEL LENGUAJE BORDEMAR','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13604','COLEGIO RAKIDUAM','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13606','COLEGIO LEONARDO DA VINCI - VICUÑA','Coquimbo','VICUÑA','Part. Subvencionado'),
('13607','ESC. ESPECIAL DE LENGUAJE ALTO DEL MIRAMAR','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13608','COLEGIO GOLDEN HIND SCHOOL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13609','ESCUELA ESP. DE LENGUAJE CORDILLERA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13610','COLEGIO INTERCULTURAL','Coquimbo','LA SERENA','Part. Subvencionado'),
('13611','CENTRO DE EDUC. INTEGRAL DE ADULTOS ANDACOLLO','Coquimbo','ANDACOLLO','Servicio Local'),
('13612','COLEGIO JOSE MARTI PEREZ','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13613','ESC. ESP. DE LENGUAJE HISPANOAMERICANA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13617','JARDIN INFANTIL RUISEÑOR','Coquimbo','LA SERENA','Part. Pagado'),
('13620','JARDIN INFANTIL MI PEQUEÑO GENIO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13621','COLEGIO DISCOVERY','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13622','JARDIN INFANTIL ANDALUE','Coquimbo','LA SERENA','Part. Pagado'),
('13623','ESC.ESP. DE LENGUAJE SAN CARLOS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13625','ESCUELA DE LENGUAJE PAN DE AZUCAR','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13626','COLEGIO SAN LUIS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13627','COLEGIO SAN SEBASTIÁN','Coquimbo','SALAMANCA','Part. Subvencionado'),
('13629','JARDIN INFANTIL MELODIA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13630','ESCUELA ESPECIAL DESPERTARES','Coquimbo','OVALLE','Part. Subvencionado'),
('13632','COLEGIO HORIZONTES','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13633','ESCUELA SAN MARINO COLLEGE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13636','ESC.ESP.DE LENG.HORIZONTES DE PALABRAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13637','COLEGIO HELLEN KELLER PEÑUELAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('14201','LICEO MIXTO LOS ANDES','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14202','LICEO BICENTENARIO COLEGIO PANQUEHUE','Valparaíso','PANQUEHUE','Corp. Municipal'),
('14206','LICEO AGRICOLA DE QUILLOTA','Valparaíso','QUILLOTA','Corp. Municipal'),
('14208','CENTRO INTEGRAL DE EDUCACION DE ADULTOS','Valparaíso','QUILLOTA','Corp. Municipal'),
('14209','ESCUELA ESPECIAL HELLEN KELLER','Valparaíso','OLMUÉ','Corp. Municipal'),
('14210','COLEGIO BECARB II','Valparaíso','CALERA','Part. Subvencionado'),
('14211','AMERICAN COLLEGE','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14212','SAINT MARY SCHOOL','Valparaíso','CALERA','Part. Subvencionado'),
('14213','COLEGIO VALLE DE NARAU','Valparaíso','QUINTERO','Servicio Local'),
('14217','SUN VALLEY COLLEGE','Valparaíso','CALLE LARGA','Part. Pagado'),
('14219','ESCUELA DE PARVULOS BUGS BUNNY','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14224','ESC  PART  KORC SCHOOL','Valparaíso','CONCÓN','Part. Pagado'),
('14225','INSTITUTO DE CAPACITACION TEC.PROF.ITPSA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14232','COLEGIO BORDEMAR','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14233','COLEGIO SANTA TERESA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14234','ESCUELA PART. LORENZO LUZURIAGA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14237','COL.NUESTRA SRA.DE LAS MERCEDES','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14247','COLLEGE SAINT ANDRE','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14249','COLEGIO ALBAMAR','Valparaíso','CONCÓN','Part. Pagado'),
('14250','INSTITUTO CULTURAL Y DE EDUC  PERMANENTE','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14251','ESCUELA DE PARVULOS GIRASOL','Valparaíso','SAN FELIPE','Part. Pagado'),
('14254','ESCUELA DE PARVULOS KINTU','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14255','ESCUELA DE PARVULOS LOBITO MARINO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14256','ESCUELA DE PARVULOS CARACOLITO DE MAR','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14257','ESCUELA DE PARVULOS LOS DELFINES','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14258','ESCUELA DE PARVULOS N   478','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14260','COLEGIO LORD COCHRANE ANEXO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14263','ESC. DE PARVULOS PECESITOS DE COLORES','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14265','ESCUELA SAINT BENEDICT COLLEGE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14266','COLEGIO NAZCA BELEN','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14268','ESCUELA DE PARVULOS MIGUEL FENOLLERA','Valparaíso','CALERA','Part. Subvencionado'),
('14269','ESCUELA DE PARVULOS PELUSITAS','Valparaíso','CALERA','Part. Pagado'),
('14270','COLEGIO GOBERNADOR CONCHA Y SALVATIERRA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14271','ESCUELA ESPECIAL HUMBERTO MOATH','Valparaíso','CASABLANCA','Corp. Municipal'),
('14280','COLEGIO SAGRADA FAMILIA','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14283','COLEGIO ESPECIAL BRILLO DE LUNA','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14284','LICEO RENE DESCARTES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14288','COLEGIO NUEVA PROVIDENCIA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14289','COLEGIO ADVENTISTA','Valparaíso','CALERA','Part. Subvencionado'),
('14292','COLEGIO  LOUIS LE GRAND','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14299','COLEGIO ADVENTISTA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14300','CENTRO DE CAPACITACION LABORAL','Valparaíso','VALPARAÍSO','Servicio Local'),
('14305','CENTRO ASPAUT VIÑA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14307','COLEGIO LATINO AMERICANO','Valparaíso','LIMACHE','Part. Subvencionado'),
('14308','COLEGIO ITALIANO SAN PEDRO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14310','CENTRO INTEGRAL EDUCACIONAL LINDA CORREA','Valparaíso','LIMACHE','Part. Subvencionado'),
('14313','COLEGIO NUEVA ESPERANZA','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14314','COLEGIO THOMAS ALVA EDISON','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14315','COLEGIO VICTOR ANTONIO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14316','COLEGIO EMANUEL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14318','ESCUELA DE PARVULOS CRISPA KA','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('14323','COLEGIO JOSEFINA MAGASICH ARZE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14324','COLEGIO WILLIAM JAMES','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14330','ESCUELA BASICA ARTURO PRAT','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14332','COLEGIO PEHUEN','Valparaíso','CABILDO','Part. Subvencionado'),
('14334','COLEGIO CAPELLAN PASCAL','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14336','LICEO TECN. PROF. OBISPO RAFAEL LIRA INFANTE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14338','INSTITUTO ITEP','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14347','INST.DEL DISCAP.VISUAL ANTONIO MOSQUETE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('14348','COLEGIO ESPIRITU SANTO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14351','COLEGIO SAINT GREGORY COLLEGE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14353','ESCUELA DE PARVULOS PALOMA','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14354','ESCUELA DE PARVULOS LILIPUT','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14355','ESCUELA DE PARVULOS MC DONALD GARDEN','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14359','COLEGIO LOS REYES','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14362','ESCUELA ESPECIAL ARCO IRIS BAJO EL SOL ANEXO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14363','COLEGIO HISPANO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14364','COLEGIO JORGE WILLIAMS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14365','COLEGIO CHARLES DICKENS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14371','INSTITUTO BALDOR','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14372','KING EDWARD´S SCHOOL 1','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14373','COLEGIO JOSE LUIS NORRIS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14375','COLEGIO DIVINA MAESTRA','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14376','COLEGIO SAN CARLOS','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14379','COLEGIO INTERNACIONAL SEK DEL PACIFICO','Valparaíso','CONCÓN','Part. Pagado'),
('14380','CAERNARFON COLLEGE','Valparaíso','CASABLANCA','Part. Pagado'),
('14381','COLEGIO EL VALLE DE CASABLANCA','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14383','ESCUELA DE PARVULOS L`ARC EN CIEL','Valparaíso','QUILPUÉ','Part. Pagado'),
('14386','ESCUELA DE PARVULOS TIRITAS DE PAPEL II','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14387','COLEGIO SAN NICOLAS EL OLIVAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14389','COLEGIO JUAN LUIS VIVES','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14392','CTRO INTEGRAL EDUCAC LINDA CORREA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14394','ESCUELA DE PARVULOS SAN LUIS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14395','COLEGIO EDUPAC','Valparaíso','CABILDO','Part. Subvencionado'),
('14396','COLEGIO MEDIOAMBIENTAL LAS AMAPOLAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14397','COLEGIO CRISTIANO DE QUILLOTA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14398','CENTRO DE ATENCION ANDALUE','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14402','COLEGIO MONTESSORI YERPUN','Valparaíso','QUILPUÉ','Part. Pagado'),
('14409','ESCUELA PARV  ESTRELLITAS DE BELEN','Valparaíso','LOS ANDES','Part. Pagado'),
('14411','ESCUELA DE PARVULOS ANNY SCHOOL','Valparaíso','CALERA','Part. Subvencionado'),
('14412','COLEGIO SAN PABLO','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14413','COLEGIO SANTA CLARA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14414','COLEGIO EDUCENTER','Valparaíso','CALLE LARGA','Part. Subvencionado'),
('14416','COLEGIO DOMINGO ORTIZ DE ROZAS','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14417','COLEGIO PAIDOS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14418','COLEGIO PANAL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14420','COLEGIO EL ALBA','Valparaíso','EL QUISCO','Part. Subvencionado'),
('14421','CENTRO DE EDUCACION DE ADULTOS CEAVI','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14423','ESCUELA DE PARVULOS BAMBI','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14428','VINA DEL MAR COLLEGE','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14439','INSTITUTO BALDOR','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14446','ESCUELA DE PARVULOS   BAMBI','Valparaíso','LA LIGUA','Part. Pagado'),
('14452','COLEGIO LUTERANO CONCORDIA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14453','COLEGIO LOS LIBERTADORES','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14454','LICEO EDUCACIONAL DE ADULTOS JUAN F. GONZALEZ R.','Valparaíso','SAN FELIPE','Corp. Municipal'),
('14457','ESCUELA DE PARVULOS LOS CLAVELES','Valparaíso','ALGARROBO','Corp. Municipal'),
('14459','ESCUELA DE PARVULOS CAMPANITA','Valparaíso','LIMACHE','Part. Pagado'),
('14460','ESCUELA PARVULOS PIECECITOS DE NINO','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14462','CENTRO DE ESTUDIOS SAN IGNACIO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14463','CTRO.INTEGRAL DE EDUCACION ALBORADA','Valparaíso','CONCÓN','Part. Subvencionado'),
('14466','COLEGIO ALBORADA DE CURAUMA','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14467','LICEO DE ADULTOS JACQUES COUSTEAU','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14470','LICEO POLITÉCNICO MARGA MARGA','Valparaíso','QUILPUÉ','Municipal'),
('14476','COLEGIO VALLE DEL ACONCAGUA','Valparaíso','QUILLOTA','Part. Pagado'),
('14479','ESCUELA BASICA MUNICIPAL ARAUCARIA','Valparaíso','CABILDO','Corp. Municipal'),
('14482','COLEGIO NUEVO HORIZONTE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14487','COLEGIO MAESE DA VINCI','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14490','COLEGIO MANANTIAL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14492','CENTRO EDUCACIÓN ADULTOS PEDRO DE VALDIVIA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14493','ESC. ESPECIAL SAN JUAN DE DIOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14494','COLEGIO EVANGELICO LABRANZA DE DIOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14498','COLEGIO MONTEMAR','Valparaíso','CONCÓN','Part. Pagado'),
('14499','ESCUELA DE PARVULOS SOL Y LUNA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14500','ESC. DE LENGUAJE PIPAN VINA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14502','COLEGIO CURIMON','Valparaíso','SAN FELIPE','Part. Pagado'),
('14503','ESCUELA DE PARVULOS KORCITO','Valparaíso','CONCÓN','Part. Pagado'),
('14504','COLEGIO CRISTIANO CON-CON','Valparaíso','CONCÓN','Part. Subvencionado'),
('14506','COLEGIO APUMANQUE','Valparaíso','CALERA','Part. Subvencionado'),
('14507','COLEGIO NUESTRO TIEMPO','Valparaíso','ALGARROBO','Part. Subvencionado'),
('14508','COLEGIO COEDUC','Valparaíso','QUILPUÉ','Part. Pagado'),
('14509','ESCUELA DE PARVULOS TIA PATRICIA N_ 2','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14510','COLEGIO NACIONAL','Valparaíso','LIMACHE','Part. Subvencionado'),
('14511','COLEGIO SANTA BARBARA DE LA REINA','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14512','ESCUELA DE PARVULOS FANTASIA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14513','ESCUELA DE PARVULOS NIDO DE LUNA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14514','COLEGIO EL ARRAYAN','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14515','COLEGIO GABRIELA MISTRAL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14516','ESCUELA ESPECIAL CANEC','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14517','ESCUELA ESPECIAL DE LENGUAJE EMANUEL','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14518','COLEGIO BUENAVENTURA JOGLAR AMANDI','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14521','ESC. SAINT PATRICK SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14523','LIONS SCHOOL','Valparaíso','CARTAGENA','Part. Subvencionado'),
('14525','CTRO.EDUC.Y CAPAC.AD.FCO.BILBAO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14526','COLEGIO ALONSO DE QUINTERO','Valparaíso','QUINTERO','Part. Subvencionado'),
('14527','KING EDWARD´S SCHOOL 2','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14531','ESC.ESPEC.LENG. MIS NUEVAS PALABRAS','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14533','COLEGIO CRISTIANO LOS PINOS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14534','COLEGIO AMANCAY LIMACHE','Valparaíso','LIMACHE','Part. Subvencionado'),
('14537','COLEGIO ADONAY PUKALAN','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14538','COL.SANTO DOMINGO DE GUZMAN','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14539','ESCUELA SANTA INÉS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14541','COLEGIO PATRICIO LYNCH','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14542','CENTR.ESC.TRAT.DEL LENGUAJE PAIHUEN','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14543','ESCUELA DE PARVULOS ITALITO','Valparaíso','LIMACHE','Part. Subvencionado'),
('14545','COLEGIO MERCEDES LEMUS ZAMORA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14546','ESCUELA RUBEN DARIO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14547','CENTRO DE ESTUDIOS DALBADIE','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14550','ESCUELA DE PARVULOS TIA XIMENA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14551','ESCUELA DE LENGUAJE LOS ALMENDRALES','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14552','COLEGIO SAN NICOLAS DE CANAL CHACAO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14556','COLEGIO AEQUALIS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14557','CTRO DE ESTIMULACION TEMPRANA LAS ROSAS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14559','ESCUELA ESPECIAL LOURDES','Valparaíso','QUINTERO','Part. Subvencionado'),
('14565','VERDOYHAM SCHOOL','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14568','COLEGIO CRISTO REY SALVADOR','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14569','ESCUELA DEL LENGUAJE NACAREL','Valparaíso','EL TABO','Part. Subvencionado'),
('14572','ESC.ESPECIAL DE LENGUAJE PALABRITAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14573','ESCUELA CAROLA REYES PIZARRO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14577','CTRO.EDUC.Y ATENC INTEG A LA DIVERSIDAD','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14578','ESC.TRAST.DE LA COM. Y LENG. LAS VIOLETAS','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14580','COLEGIO BOSTON','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14581','ESCUELA DE PARVULOS SABER ES CRECER','Valparaíso','LIMACHE','Part. Pagado'),
('14583','ESCUELA DE PARVULOS CLARITO DE SOL','Valparaíso','NOGALES','Part. Subvencionado'),
('14587','COLEGIO CUMBRES DE LLAY LLAY','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14588','ESCUELA DE TRAST. DE LENGUAJE CELAN PAICAVÝ','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14589','COLEGIO TRAST.DE LA COMUNIC MATICES','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14592','COLEGIO DE ADULTOS FRITZ ENCALADA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14593','COLEGIO VALLE DE ARAUCO','Valparaíso','CALERA','Part. Subvencionado'),
('14594','COLEGIO QUILLOTA TERRANOVA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14599','COLEGIO POETA DANIEL DE LA VEGA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14602','COLEGIO SIGLO XXI','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14605','COLEGIO VILLA ACONCAGUA','Valparaíso','CONCÓN','Part. Subvencionado'),
('14606','COLEGIO PUERTO PAZ','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14608','COLEGIO JUANITA FERNANDEZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14609','COLEGIO CARDENAL OVIEDO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14614','COLEGIO VEDRUNA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14616','COLEGIO LOS PRINCIPES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14622','COLEGIO SAN AGUSTIN','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14625','CENTRO DE ESTUDIOS IGNACIO DOMEYKO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14626','COLEGIO ARAUCARIAS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14628','CENTRO DE ESTUDIOS IBERO CHILE','Valparaíso','QUILLOTA','Part. Pagado'),
('14629','COLEGIO CASTELIANO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14631','ESCUELA DE PARVULOS SANTA TERESITA','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14636','COLEGIO DE LENGUAJE EVERITO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14637','COLEGIO HYATT','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14638','ESC.DE TRAST.DE LA COMUNIC.YAMANKI','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14639','COLEGIO GHERARDELLI','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14641','COLEGIO PAULA VIVANCO','Valparaíso','LIMACHE','Part. Subvencionado'),
('14642','COLEGIO CRISTIANO EMBAJADORES DEL REY','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14643','CASABLANCA BILINGUAL SCHOOL','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14645','ESCUELA SANTA MARIA DE LA ESPERANZA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14649','COLEGIO SAN FRANCISCO DE ASIS','Valparaíso','CALERA','Part. Subvencionado'),
('14654','NUEVO COLEGIO CAMBRIDGE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14655','ESCUELA ESPECIAL AMOR Y ESPERANZA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14656','CENTRO DE APOYO A JOV. Y ADUL. CON SINDROME','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14657','COL EXPERIM.NINOS CANTORES DE VINA D','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14658','CTRO.ESTIMULAC.DEL LENGUAJE ANTIYAL','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14659','COLEGIO NAHUEN DE QUILPUÉ','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14662','C E D I P','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14663','ESCUELA ESPECIAL ARAMDA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14664','ESCUELA PARVULOS MUNDO FELIZ','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14666','COLEGIO ESPECIAL DE LENGUAJE LOS CAPULLITOS','Valparaíso','CALERA','Part. Subvencionado'),
('14669','ESCUELA DE PARVULOS GOTITA DE LUNA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14670','COLEGIO SAN SEBASTIAN','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14671','COLEGIO TIERRA DEL FUEGO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14672','COLEGIO BLAISE PASCAL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14673','COLEGIO NUEVA ERA SIGLO XXI QUILLOTA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14674','COLEGIO NUEVO MILENIO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14675','COLEGIO SAN SEBASTIAN DE AKIVI','Valparaíso','ISLA DE PASCUA','Part. Subvencionado'),
('14676','COLEGIO CANEC VALPARAISO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14677','COLEGIO CAPITAN ARTURO PRAT CHACON','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14678','ESCUELA JUAN DE SAAVEDRA','Valparaíso','VALPARAÍSO','Servicio Local'),
('14681','ESCUELA DE PARVULOS PEQUEGENIOS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14685','COLEGIO CENTILEN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14687','COLEGIO GEA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14690','ESC DE PARVULOS MI PEQUENO CLUB','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14692','ESC.ESPEC.DE LENGUAJE NOGALES','Valparaíso','NOGALES','Part. Subvencionado'),
('14693','ESCUELA DE LENGUAJE AMANKAY','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14695','ESCUELA DE PARVULOS PINIPON','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14697','LICEO BICENTENARIO CORDILLERA DE SAN FELIPE','Valparaíso','SAN FELIPE','Corp. Municipal'),
('14699','COLEGIO FENIX','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14702','ESCUELA DE LENGUAJE OTE MOANA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14703','THE KINGSTOWN SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14705','ESC.DE LENG. SEMBRANDO PALABRAS','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14706','COLEGIO SAN FRANCISCO','Valparaíso','LIMACHE','Part. Subvencionado'),
('14707','COLEGIO PORTALIANO','Valparaíso','SAN FELIPE','Part. Pagado'),
('14708','ESC ESTER DE LA TORRE VILLARROEL','Valparaíso','LIMACHE','Part. Subvencionado'),
('14709','ESCUELA DE LENGUAJE Y PÁRVULOS MARÍA MADRE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14711','CTRO DE ESTUDIOS ALONSO DE ERCILLA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14716','PAN AMERICAN COLLEGE VINA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14717','COLEGIO LAS AMERICAS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14718','COLEGIO PRINCIPE DE ASTURIAS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14719','MATURANA SCHOOL','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14720','LICEO GASTRONOMIA Y TURISMO','Valparaíso','QUILPUÉ','Municipal'),
('14721','ESC.DE LENGUAJE NUEVO AMANECER','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14723','ESCUELA DE PARVULOS SOLRIE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14726','ESCUELA DE LENGUAJE ARTYLEN','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14728','JARDIN INFANTIL  ANDALUE','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('14730','ESC. DE LENGUAJE ARINGA POKI','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14731','CENTRO INTEGRAL EDUCACIONAL NUESTRA SEÑORA DEL ENCUENTRO','Valparaíso','HIJUELAS','Part. Subvencionado'),
('14733','ESCUELA DE LENGUAJE SAN BENITO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14734','JARDIN INFANTIL DAPANGAM','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14735','ESCUELA DE PARVULOS TIA LUZ','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14737','CTRO EDUCAT INTEGRAL RAYEN','Valparaíso','HIJUELAS','Part. Subvencionado'),
('14738','JARDIN INFANTIL TRES OSITOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14739','ESCUELA DE LENGUAJE TRIGAL','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14742','ESCUELA DE LENGUAJE PALABRITAS','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14744','JARDIN INFANTIL MIS COLORES','Valparaíso','QUILPUÉ','Part. Pagado'),
('14747','JARDIN INFANTIL MI PEQUENO MUNDO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14748','JARDIN INFANTIL ABRACADABRA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14750','COLEGIO GREENLAND SAN FELIPE','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14751','COLEGIO EL ROBLE DE SANTO DOMINGO','Valparaíso','SANTO DOMINGO','Part. Subvencionado'),
('14753','COLEGIO MONTEALEGRE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14755','ESCUELA DE LENGUAJE MIS VIOLETAS','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14756','JARDIN INFANTIL TERRALEGRE','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('14758','JARDIN INFANTIL ANDALICAN','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14759','COLEGIO ADULTOS ALICIA MONCKEBERG','Valparaíso','CARTAGENA','Part. Subvencionado'),
('14760','COLEGIO PADRE ZANANDREA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14762','COLEGIO PARTICULAR ANDES-CHILE','Valparaíso','LOS ANDES','Part. Pagado'),
('14764','COLEGIO UMBRAL DE CURAUMA','Valparaíso','VALPARAÍSO','Part. Pagado'),
('14765','ESCUELA DE LENGUAJE RAYEN','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14766','ESC. DE LENGUAJE TERRANOVA','Valparaíso','PUTAENDO','Part. Subvencionado'),
('14767','ESCUELA DE LENGUAJE PAIDEIA','Valparaíso','SANTA MARÍA','Part. Subvencionado'),
('14770','COL.PRECURSOR FRANCISCO DE MIRANDA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14771','COLEGIO CARLOMAGNO','Valparaíso','QUILPUÉ','Part. Pagado'),
('14772','JARDIN INFANTIL MASEJITOS','Valparaíso','LOS ANDES','Part. Pagado'),
('14773','COLEGIO GUARDIAMARINA RIQUELME','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14774','ESCUELA DE LENGUAJE SAN FRANCISCO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14775','COLEGIO MONTESOL 2','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14778','COLEGIO SAN NICOLAS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14779','COLEGIO MAR ABIERTO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14782','COLEGIO ANTUMAPU','Valparaíso','CALERA','Part. Subvencionado'),
('14783','COLEGIO NUEVA ERA SIGLO XXI','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14785','CENTRO CAID LTDA. CABILDO','Valparaíso','CABILDO','Part. Subvencionado'),
('14787','ESC.TRAST. LENGUAJE RAYITO DE SOL','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14788','COLEGIO PAPA JUAN PABLO II','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14789','ESC. ESPECIAL VIDA NUEVA ELIM','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14790','COLEGIO SAINT-LAWRENCE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14791','COL.DE ADULTOS ELEUTERIO RAMIREZ','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14793','ESCUELA DE LENGUAJE ALONQUEO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14796','COLEGIO SOL DE AMERICA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14798','ESCUELA DE LENGUAJE CAICURA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14799','CTRO. DE RECURSOS ALTAVIDA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14800','COLEGIO ESPECIAL ARMONIA','Valparaíso','CALERA','Part. Subvencionado'),
('14801','COLEGIO LAS PALMAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14802','ESCUELA DE LENGUAJE ARCOIRIS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14803','ESC. ESP. DE LENGUAJE Y PARVULOS SONRISAS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14804','COLEGIO SAN BLAS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14805','COLEGIO EL QUISCO','Valparaíso','EL QUISCO','Corp. Municipal'),
('14806','ESC.DE PARVULOS ARBOL DE LA VIDA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14808','CTRO.EDUC.INTEG.ALGUIEN DENTRO DE MI','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14809','ESCUELA DE LENGUAJE SAN RAFAEL','Valparaíso','LIMACHE','Part. Subvencionado'),
('14810','COLEGIO DE LENGUAJE AYELEN','Valparaíso','CALERA','Part. Subvencionado'),
('14811','ESCUELA DE LENGUAJE PAICAVI','Valparaíso','SAN ESTEBAN','Part. Subvencionado'),
('14814','JARDIN INFANTIL CHARLIE BROWN','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14818','COLEGIO NUMANCIA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14819','COLEGIO CERVANTINO','Valparaíso','PUTAENDO','Part. Subvencionado'),
('14820','COLEGIO SANTA MARIA COLLEGE','Valparaíso','SANTA MARÍA','Part. Subvencionado'),
('14822','COLEGIO ALBORADA DEL MAR','Valparaíso','CONCÓN','Part. Subvencionado'),
('14823','COLEGIO ANTONIO ZANOLETTI','Valparaíso','PAPUDO','Part. Subvencionado'),
('14824','COLEGIO EVEREST CENTRAL','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14825','NUEVO COLEGIO PART. DE CARTAGENA','Valparaíso','CARTAGENA','Part. Subvencionado'),
('14828','ESC.ESTIMUL.LENG. PEQUENAS VOCES','Valparaíso','NOGALES','Part. Subvencionado'),
('14829','ESCUELA MULTIDEFICIT AMANECER','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('14832','ESC.ESP.DE LENGUAJE DIVINA MISERICORDIA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14833','ESC. ESPEC.DE LENGUAJE PRINCIPITO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14834','JARDIN INFANTIL GOLONRISAS','Valparaíso','QUILLOTA','Part. Pagado'),
('14836','ESCUELA ESP. DE LENGUAJE YIREH','Valparaíso','LIMACHE','Part. Subvencionado'),
('14837','JARDIN INFANTIL BURBUJITAS','Valparaíso','CALERA','Part. Subvencionado'),
('14838','PARVULARIO EL OLIVITO','Valparaíso','HIJUELAS','Part. Subvencionado'),
('14839','ESC. ESP. DE LENG. Y JARDIN INFANTIL NUBELUZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14845','ESC.ESPEC. DE LENGUAJE ANTU','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14846','CENTRO EDUCACIONAL CEVAL LTDA.','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14847','JARDIN INFANTIL PIECECITOS DE NIÑOS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14848','ESCUELA PART. ANNY SCHOOL','Valparaíso','LA CRUZ','Part. Subvencionado'),
('14850','ESCUELA ESPECIAL QUILLAGUA','Valparaíso','CONCÓN','Part. Subvencionado'),
('14851','JARDIN INFANTIL TIA MONONA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14854','ESC. ESPEC. DE LENGUAJE PEQUENINO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14856','SUNNYLAND SCHOOL','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14859','ESC. ESPECIAL DE LENGUAJE EDUCATEL','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14860','COLEGIO HERMANO EUGENIO EYRAUD','Valparaíso','ISLA DE PASCUA','Part. Subvencionado'),
('14862','COLEGIO NAZAREO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14863','ESC.ESPEC DE LENGUAJE SAN GABRIEL','Valparaíso','QUINTERO','Part. Subvencionado'),
('14865','COLEGIO TECNICO ALIANZA EDUCACIONAL','Valparaíso','LIMACHE','Part. Subvencionado'),
('14866','COLEGIO ALTAZOR','Valparaíso','CONCÓN','Part. Subvencionado'),
('14868','LICEO TECNICO AGRICOLA OBISPO RAFAEL LIRA INF','Valparaíso','LA CRUZ','Part. Subvencionado'),
('14869','JARDIN INFANTIL MINILANDIA','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('14870','COLEGIO ENTRE VALLES','Valparaíso','VILLA ALEMANA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
