-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 13 de 31 | filas 4801-5200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('8071','ESCUELA RURAL NAL','Los Lagos','ANCUD','Servicio Local'),
('8075','ESCUELA RURAL QUILAR','Los Lagos','ANCUD','Servicio Local'),
('8080','ESCUELA RURAL COGOMO','Los Lagos','ANCUD','Servicio Local'),
('8085','ESCUELA RURAL SAN MIGUEL DE COÑIMO','Los Lagos','ANCUD','Servicio Local'),
('8092','ESCUELA RURAL LUIS ALBERTO SEGOVIA ROSS','Los Lagos','ANCUD','Servicio Local'),
('8094','ESCUELA RURAL CAIPULLI','Los Lagos','ANCUD','Servicio Local'),
('8095','ESCUELA RURAL AGUAS BUENAS','Los Lagos','ANCUD','Servicio Local'),
('8096','ESCUELA RURAL PUGUEÑUN','Los Lagos','ANCUD','Servicio Local'),
('8099','ESCUELA RURAL COCOTUE','Los Lagos','ANCUD','Servicio Local'),
('8100','ESCUELA RURAL SOL DEL PACIFICO','Los Lagos','ANCUD','Servicio Local'),
('8102','ESCUELA RURAL HUELDEN','Los Lagos','ANCUD','Servicio Local'),
('8103','ESCUELA RURAL BAHIA LINAO','Los Lagos','ANCUD','Servicio Local'),
('8104','ESCUELA RURAL PUENTE PUNTRA','Los Lagos','ANCUD','Servicio Local'),
('8105','LICEO BICENTENARIO DE ANCUD','Los Lagos','ANCUD','Servicio Local'),
('8107','ESCUELA DIFERENCIAL `SAN CARLOS DE ANCUD`','Los Lagos','ANCUD','Servicio Local'),
('8108','SEMINARIO CONCILIAR DE ANCUD','Los Lagos','ANCUD','Part. Subvencionado'),
('8109','LICEO COMERCIAL EL PILAR','Los Lagos','ANCUD','Part. Subvencionado'),
('8111','LICEO BICENTENARIO QUEMCHI','Los Lagos','QUEMCHI','Servicio Local'),
('8112','ESCUELA RURAL JUAN VICTORINO TANGOL','Los Lagos','DALCAHUE','Servicio Local'),
('8113','ESCUELA RURAL AQUELARRE','Los Lagos','QUEMCHI','Servicio Local'),
('8114','ESCUELA RURAL LLIUCO','Los Lagos','QUEMCHI','Servicio Local'),
('8115','ESCUELA RURAL MORRO LOBOS ALTO','Los Lagos','QUEMCHI','Servicio Local'),
('8116','ESCUELA RURAL HUITE','Los Lagos','QUEMCHI','Servicio Local'),
('8117','ESCUELA RURAL MONTEMAR','Los Lagos','QUEMCHI','Servicio Local'),
('8120','ESCUELA RURAL QUINTERQUEN','Los Lagos','QUEMCHI','Servicio Local'),
('8121','ESCUELA RURAL SANTA ROSA','Los Lagos','QUEMCHI','Servicio Local'),
('8122','ESCUELA RURAL PIDO','Los Lagos','QUEMCHI','Servicio Local'),
('8124','ESCUELA RURAL CAUCAHUE','Los Lagos','QUEMCHI','Servicio Local'),
('8126','ESCUELA RURAL AUCAR','Los Lagos','QUEMCHI','Servicio Local'),
('8127','ESCUELA RURAL QUELER','Los Lagos','QUEMCHI','Servicio Local'),
('8131','ESCUELA RURAL MALUCO','Los Lagos','QUEMCHI','Servicio Local'),
('8132','ESCUELA DE AULIN','Los Lagos','QUEMCHI','Servicio Local'),
('8133','ESCUELA RURAL LINDA VISTA','Los Lagos','QUEMCHI','Servicio Local'),
('8134','ESCUELA RURAL CONEB','Los Lagos','QUEMCHI','Servicio Local'),
('8135','ESCUELA RURAL TAC','Los Lagos','QUEMCHI','Servicio Local'),
('8136','ESCUELA RURAL ARCHIPIELAGO','Los Lagos','QUEMCHI','Servicio Local'),
('8139','ESCUELA RURAL CHENIAO','Los Lagos','QUEMCHI','Servicio Local'),
('8141','ESCUELA RURAL SAN JOSE','Los Lagos','QUEMCHI','Servicio Local'),
('8142','ESCUELA RURAL BORDEMAR VILLA MECHUQUE','Los Lagos','QUEMCHI','Servicio Local'),
('8143','ESCUELA RURAL NAYAHUE','Los Lagos','QUEMCHI','Servicio Local'),
('8144','ESCUELA RURAL CESAR GOMEZ GARCIA','Los Lagos','DALCAHUE','Servicio Local'),
('8147','ESCUELA RURAL MALLINLEMU','Los Lagos','DALCAHUE','Servicio Local'),
('8149','ESCUELA RURAL CARIHUEICO','Los Lagos','DALCAHUE','Servicio Local'),
('8150','ESCUELA RURAL EL PRADO','Los Lagos','DALCAHUE','Servicio Local'),
('8157','ESCUELA RURAL JOSE MARIA ULLOA SALDIVIA','Los Lagos','DALCAHUE','Servicio Local'),
('8158','ESCUELA RURAL CALEN','Los Lagos','DALCAHUE','Servicio Local'),
('8159','ESCUELA RURAL JOSE DANIEL BAHAMONDE BAHAMONDE','Los Lagos','DALCAHUE','Servicio Local'),
('8160','ESCUELA RURAL CULDEO','Los Lagos','DALCAHUE','Servicio Local'),
('8161','ESCUELA BASICA DALCAHUE','Los Lagos','DALCAHUE','Servicio Local'),
('8162','LICEO ALFREDO DEL CARMEN BARRIA OYARZUN','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8163','ESCUELA RURAL CHULLEC','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8164','ESCUELA RURAL TOLQUIEN','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8165','ESCUELA RURAL EDUARDO FREI MONTALVA','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8166','ESCUELA RURAL VISTA HERMOSA','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8167','ESCUELA RURAL HUYAR BAJO','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8169','ESCUELA RURAL HUYAR ALTO','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8170','ESCUELA RURAL SAN JAVIER','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8173','ESCUELA RURAL HUENAO','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('8174','LICEO BICENTENARIO INSULAR','Los Lagos','QUINCHAO','Servicio Local'),
('8176','ESCUELA RURAL LA CAPILLA','Los Lagos','QUINCHAO','Servicio Local'),
('8177','ESCUELA RURAL OSTRICULTURA','Los Lagos','QUINCHAO','Servicio Local'),
('8179','ESCUELA RURAL FRANCISCO DE VILLAGRA','Los Lagos','QUINCHAO','Servicio Local'),
('8180','ESCUELA RURAL ALAO','Los Lagos','QUINCHAO','Servicio Local'),
('8181','ESCUELA RURAL METAHUE','Los Lagos','QUINCHAO','Servicio Local'),
('8182','ESCUELA RURAL LA VILLA','Los Lagos','QUINCHAO','Servicio Local'),
('8183','ESCUELA RURAL AMANECER 2000','Los Lagos','QUINCHAO','Servicio Local'),
('8184','ESCUELA RURAL LLINGUA','Los Lagos','QUINCHAO','Servicio Local'),
('8186','ESCUELA RURAL LOS PINOS','Los Lagos','QUINCHAO','Servicio Local'),
('8188','ESCUELA RURAL LA CAPILLA','Los Lagos','QUINCHAO','Servicio Local'),
('8189','ESCUELA RURAL TERESA CARDENAS DE PAREDES','Los Lagos','QUINCHAO','Servicio Local'),
('8191','ESCUELA RURAL SAN FRANCISCO','Los Lagos','QUINCHAO','Servicio Local'),
('8194','LICEO PARTICULAR RAMON FREIRE','Los Lagos','QUINCHAO','Part. Subvencionado'),
('8195','ESCUELA PUQUELDON','Los Lagos','PUQUELDÓN','Servicio Local'),
('8197','ESCUELA RURAL LAS LAGUNAS','Los Lagos','PUQUELDÓN','Servicio Local'),
('8198','ESCUELA RURAL SAN JUAN DE LINCAY','Los Lagos','PUQUELDÓN','Servicio Local'),
('8200','ESCUELA RURAL SAN AGUSTIN','Los Lagos','PUQUELDÓN','Servicio Local'),
('8201','ESCUELA RURAL LAS CAMPANAS','Los Lagos','PUQUELDÓN','Servicio Local'),
('8202','ESCUELA RURAL DETIF','Los Lagos','PUQUELDÓN','Servicio Local'),
('8203','ESCUELA RURAL SANTA ROSA','Los Lagos','PUQUELDÓN','Servicio Local'),
('8205','ESCUELA RURAL ICHUAC','Los Lagos','PUQUELDÓN','Servicio Local'),
('8206','LICEO BICENTENARIO MANUEL JESUS ANDRADE BORQUEZ','Los Lagos','CHONCHI','Servicio Local'),
('8207','ESCUELA RURAL NOTUCO','Los Lagos','CHONCHI','Servicio Local'),
('8208','ESCUELA RURAL CURACO DE VILUPULLI','Los Lagos','CHONCHI','Servicio Local'),
('8210','ESCUELA RURAL QUITRIPULLI','Los Lagos','CHONCHI','Servicio Local'),
('8211','ESCUELA RURAL HUILLINCO','Los Lagos','CHONCHI','Servicio Local'),
('8213','ESCUELA RURAL EL PULPITO','Los Lagos','CHONCHI','Servicio Local'),
('8216','ESCUELA RURAL PUCATUE','Los Lagos','CHONCHI','Servicio Local'),
('8217','ESCUELA RURAL TEUPA','Los Lagos','CHONCHI','Servicio Local'),
('8220','ESCUELA RURAL CUCAO','Los Lagos','CHONCHI','Servicio Local'),
('8225','ESCUELA RURAL CANAN','Los Lagos','CHONCHI','Servicio Local'),
('8226','ESCUELA RURAL QUINCHED','Los Lagos','CHONCHI','Servicio Local'),
('8227','ESCUELA RURAL CHANQUIN','Los Lagos','CHONCHI','Servicio Local'),
('8228','ESCUELA RURAL VILUPULLI','Los Lagos','CHONCHI','Servicio Local'),
('8230','ESCUELA RURAL RAUCO','Los Lagos','CHONCHI','Servicio Local'),
('8231','ESCUELA RURAL TERAO','Los Lagos','CHONCHI','Servicio Local'),
('8234','ESCUELA RURAL MIRAFLORES','Los Lagos','CHONCHI','Servicio Local'),
('8236','ESCUELA CHILHUE','Los Lagos','QUEILÉN','Servicio Local'),
('8237','ESCUELA RURAL PAILDAD','Los Lagos','QUEILÉN','Servicio Local'),
('8238','ESCUELA RURAL ALQUI','Los Lagos','QUEILÉN','Servicio Local'),
('8239','ESCUELA RURAL INSTITUTO CORFO-PUREO','Los Lagos','QUEILÉN','Servicio Local'),
('8241','ESCUELA RURAL ALVARO VARGAS MIRANDA','Los Lagos','QUEILÉN','Servicio Local'),
('8243','ESCUELA RURAL JUAN BAUTISTA CHIGUAY','Los Lagos','QUEILÉN','Servicio Local'),
('8244','ESCUELA RURAL DIAZ-LIRA','Los Lagos','QUEILÉN','Servicio Local'),
('8246','ESCUELA RURAL NEPUE','Los Lagos','QUEILÉN','Servicio Local'),
('8247','ESCUELA RURAL JUAN ANTONIO VERA DIAZ','Los Lagos','QUEILÉN','Servicio Local'),
('8251','ESCUELA RURAL SAN JOSE DE TRANQUI','Los Lagos','QUEILÉN','Servicio Local'),
('8254','ESCUELA RURAL DETICO','Los Lagos','QUEILÉN','Servicio Local'),
('8255','LICEO RAYEN MAPU','Los Lagos','QUELLÓN','Servicio Local'),
('8256','ESCUELA EDUCADORA EULOGIA BORQUEZ PEREZ','Los Lagos','QUELLÓN','Servicio Local'),
('8257','ESCUELA RURAL SAN ANTONIO DE CHADMO','Los Lagos','QUELLÓN','Servicio Local'),
('8258','ESCUELA RURAL RIO MAULE','Los Lagos','QUELLÓN','Servicio Local'),
('8260','ESCUELA RURAL QUILEN','Los Lagos','QUELLÓN','Servicio Local'),
('8261','ESCUELA RURAL CHADMO CENTRAL','Los Lagos','QUELLÓN','Servicio Local'),
('8262','ESCUELA RURAL COLCAO','Los Lagos','QUELLÓN','Servicio Local'),
('8263','ESCUELA RURAL JOSE SANTOS LINCOMAN INAICHEO','Los Lagos','QUELLÓN','Servicio Local'),
('8264','ESCUELA RURAL ADELA GARCIA GARCIA','Los Lagos','QUELLÓN','Servicio Local'),
('8265','ESCUELA RURAL COCAUQUE','Los Lagos','QUELLÓN','Servicio Local'),
('8267','ESCUELA RURAL HUELPUN','Los Lagos','QUELLÓN','Servicio Local'),
('8268','ESCUELA RURAL OQUELDAN','Los Lagos','QUELLÓN','Servicio Local'),
('8269','ESCUELA RURAL LASTENIA OYARZUN ANDRADE','Los Lagos','QUELLÓN','Servicio Local'),
('8270','ESCUELA RURAL PELU','Los Lagos','QUELLÓN','Servicio Local'),
('8271','ESCUELA RURAL PUNTA PAULA','Los Lagos','QUELLÓN','Servicio Local'),
('8273','ESCUELA RURAL COINCO ALTO','Los Lagos','QUELLÓN','Municipal'),
('8274','ESCUELA RURAL CANDELARIA','Los Lagos','QUELLÓN','Servicio Local'),
('8275','ESCUELA RURAL TRINCAO','Los Lagos','QUELLÓN','Servicio Local'),
('8276','ESCUELA RURAL PIEDRA BLANCA','Los Lagos','QUELLÓN','Servicio Local'),
('8278','ESCUELA RURAL YELCHO','Los Lagos','QUELLÓN','Servicio Local'),
('8281','ESCUELA RURAL CHAIGUAO','Los Lagos','QUELLÓN','Servicio Local'),
('8284','ESCUELA RURAL COINCO','Los Lagos','QUELLÓN','Servicio Local'),
('8285','ESCUELA RURAL AGUA FRESCA','Los Lagos','QUELLÓN','Servicio Local'),
('8286','ESCUELA RURAL SAN ANTONIO','Los Lagos','QUELLÓN','Servicio Local'),
('8287','ESCUELA RURAL AUCHAC','Los Lagos','QUELLÓN','Servicio Local'),
('8288','ESCUELA RURAL YALDAD','Los Lagos','QUELLÓN','Servicio Local'),
('8289','ESCUELA RURAL ARTISTICA ALUMNO MARCELO GUENTEO SOLIS','Los Lagos','QUELLÓN','Servicio Local'),
('8290','ESCUELA RURAL KUME RUKA WEKETRUMAO','Los Lagos','QUELLÓN','Servicio Local'),
('8293','ESCUELA RURAL NAYAHUE','Los Lagos','CHAITÉN','Corp. Municipal'),
('8294','ESCUELA RURAL AUTENI','Los Lagos','CHAITÉN','Corp. Municipal'),
('8295','ESCUELA RURAL CHUIT','Los Lagos','CHAITÉN','Corp. Municipal'),
('8296','ESCUELA RURAL NUEVA ESPERANZA','Los Lagos','CHAITÉN','Corp. Municipal'),
('8299','ESCUELA RURAL CASA DE PESCA','Los Lagos','CHAITÉN','Corp. Municipal'),
('8300','ESCUELA RURAL LOYOLA','Los Lagos','CHAITÉN','Corp. Municipal'),
('8301','ESCUELA RURAL BUILL','Los Lagos','CHAITÉN','Corp. Municipal'),
('8303','ESCUELA RURAL CHUMELDEN','Los Lagos','CHAITÉN','Corp. Municipal'),
('8304','ESCUELA RURAL RIO AMARILLO','Los Lagos','CHAITÉN','Corp. Municipal'),
('8305','ESCUELA RURAL CHANA','Los Lagos','CHAITÉN','Corp. Municipal'),
('8306','ESCUELA RURAL VALLE EL FRIO','Los Lagos','CHAITÉN','Corp. Municipal'),
('8307','ESCUELA RURAL HUEQUE','Los Lagos','CHAITÉN','Corp. Municipal'),
('8308','ESCUELA RURAL POYO','Los Lagos','CHAITÉN','Corp. Municipal'),
('8309','LICEO PENINSULAR AYACARA','Los Lagos','CHAITÉN','Corp. Municipal'),
('8310','COLEGIO MAURICIO HITCHCOCK','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8311','ESCUELA RURAL AULEN','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8312','ESCUELA RURAL PICHICOLO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8313','ESCUELA RURAL CATARATAS DEL ALERCE','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8314','ESCUELA RURAL CANDELARIA','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8315','ESCUELA RURAL SAN PEDRO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8317','ESCUELA RURAL LA POZA CONTAO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8318','ESCUELA RURAL QUILDACO BAJO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8319','ESCUELA RURAL VALLE HERMOSO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8320','ESCUELA RURAL MANIHUEICO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8321','ESCUELA RURAL CALETA EL MANZANO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8322','ESCUELA RURAL HUINAY','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8323','ESCUELA RURAL N.745 SEMILLERO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8324','ESCUELA RURAL QUETEN','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8325','ESCUELA ANTUPIREN','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8326','ESCUELA RURAL SAN FRANCISCO','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8327','ESCUELA RURAL QUIACA','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8328','ESCUELA RURAL JUAN FRANCISCO MALDONADO BARRÍA','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8329','ESCUELA RURAL CORDILLERA NEVADA','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('8331','LICEO BICENTENARIO FUTALEUFU','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8334','ESCUELA RURAL EL ESPOLON','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8335','ESCUELA RURAL RIO AZUL','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8336','ESCUELA RURAL EL LIMITE','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8337','ESCUELA RURAL LAS ESCALAS','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8338','ESCUELA RURAL LONCONAO','Los Lagos','FUTALEUFÚ','Corp. Municipal'),
('8339','COLEGIO ROBERTO WHITE GESELL','Los Lagos','PALENA','Corp. Municipal'),
('8340','ESCUELA RURAL RIO MALITO','Los Lagos','PALENA','Corp. Municipal'),
('8341','ESCUELA RURAL FRONTERIZA','Los Lagos','PALENA','Corp. Municipal'),
('8342','ESCUELA RURAL PUERTO RAMIREZ','Los Lagos','PALENA','Corp. Municipal'),
('8344','ESCUELA RURAL LA CASCADA','Los Lagos','PALENA','Corp. Municipal'),
('8345','LICEO JOSEFINA AGUIRRE MONTENEGRO','Aysén','COYHAIQUE','Servicio Local'),
('8346','ESCUELA VICTOR DOMINGO SILVA','Aysén','COYHAIQUE','Servicio Local'),
('8348','ESCUELA BAQUEDANO','Aysén','COYHAIQUE','Servicio Local'),
('8349','ESCUELA PEDRO QUINTANA MANSILLA','Aysén','COYHAIQUE','Servicio Local'),
('8351','ESCUELA DIFERENCIAL ESPANA','Aysén','COYHAIQUE','Servicio Local'),
('8352','LICEO TECNICO PROFESIONAL PROFESOR RICARDO NAVARRETE BARRIA','Aysén','COYHAIQUE','Servicio Local'),
('8353','ESCUELA NIEVES DEL SUR','Aysén','COYHAIQUE','Servicio Local'),
('8354','ESCUELA RURAL PABLO CEA VASQUEZ','Aysén','COYHAIQUE','Servicio Local'),
('8355','ESCUELA RURAL PABLO NERUDA','Aysén','COYHAIQUE','Servicio Local'),
('8356','ESCUELA RURAL RIO BLANCO','Aysén','COYHAIQUE','Servicio Local'),
('8357','ESCUELA RURAL VALLE SIMPSON','Aysén','COYHAIQUE','Servicio Local'),
('8358','ESCUELA JOSE ANTOLIN SILVA ORMENO','Aysén','COYHAIQUE','Servicio Local'),
('8361','ESCUELA RURAL VALLE DE LA LUNA','Aysén','COYHAIQUE','Servicio Local'),
('8362','ESCUELA RURAL ARROYO EL GATO','Aysén','COYHAIQUE','Servicio Local'),
('8365','LICEO SAN FELIPE BENICIO DE COYHAIQUE','Aysén','COYHAIQUE','Part. Subvencionado'),
('8366','COLEGIO LYON COLLEGE','Aysén','COYHAIQUE','Part. Subvencionado'),
('8367','COLEGIO MATER DEI DE COYHAIQUE','Aysén','COYHAIQUE','Part. Subvencionado'),
('8368','ESCUELA PARTICULAR SAN JOSE OBRERO','Aysén','COYHAIQUE','Part. Subvencionado'),
('8369','LICEO BICENTENARIO AGRICOLA E INDUSTRIAL DE LA PATAGONIA','Aysén','COYHAIQUE','Adm. Delegada'),
('8370','ESCUELA MUNICIPAL VILLA AMENGUAL','Aysén','LAGO VERDE','Servicio Local'),
('8371','ESC.CON INTERNADO JOSE MIGUEL CARRERA','Aysén','LAGO VERDE','Servicio Local'),
('8372','ESCUELA RURAL CON INTERNADO LA TAPERA','Aysén','LAGO VERDE','Servicio Local'),
('8374','ESCUELA DESPERTAR','Aysén','AYSÉN','Servicio Local'),
('8375','LICEO POLITECNICO DE AYSEN','Aysén','AYSÉN','Servicio Local'),
('8376','ESCUELA BASICA MUNICIPAL POETISA GABRIELA MISTRAL','Aysén','AYSÉN','Servicio Local'),
('8377','ESCUELA AYSEN','Aysén','AYSÉN','Servicio Local'),
('8379','ESCUELA PEDRO AGUIRRE CERDA','Aysén','AYSÉN','Servicio Local'),
('8380','LICEO MANIHUALES','Aysén','AYSÉN','Servicio Local'),
('8382','ESCUELA CARLOS CONDELL','Aysén','AYSÉN','Servicio Local'),
('8384','ESCUELA ALMIRANTE SIMPSON','Aysén','AYSÉN','Servicio Local'),
('8388','ESCUELA GUIDO GOMEZ MUNOZ','Aysén','CISNES','Servicio Local'),
('8389','ESCUELA AMANDA LABARCA HUBERSTONE','Aysén','CISNES','Servicio Local'),
('8390','ESCUELA HAMBURGO','Aysén','CISNES','Servicio Local'),
('8391','ESCUELA EUSEBIO IBAR SCHEPELER','Aysén','CISNES','Servicio Local'),
('8392','LICEO MELINKA','Aysén','GUAITECAS','Servicio Local'),
('8393','ESCUELA DE REPOLLAL','Aysén','GUAITECAS','Servicio Local'),
('8394','LICEO BICENTENARIO LUISA RABANAL PALMA','Aysén','CHILE CHICO','Servicio Local'),
('8397','ESCUELA TULIO BURGOS RIVERA','Aysén','CHILE CHICO','Servicio Local'),
('8398','ESC. LIBERTADOR BERNARDO O´HIGGINS RIQUELME','Aysén','CHILE CHICO','Servicio Local'),
('8399','ESCUELA PÚBLICA NACIMIENTO DEL BAKER','Aysén','CHILE CHICO','Servicio Local'),
('8401','ESCUELA GABRIELA MISTRAL','Aysén','RÍO IBÁÑEZ','Servicio Local'),
('8403','LICEO BICENTENARIO RURAL CERRO CASTILLO','Aysén','RÍO IBÁÑEZ','Servicio Local'),
('8404','ESCUELA AONIKENK','Aysén','RÍO IBÁÑEZ','Servicio Local'),
('8405','ESCUELA RURAL CARRETERA AUSTRAL','Aysén','RÍO IBÁÑEZ','Servicio Local'),
('8407','ESCUELA MARIA ANTONIETA PARRA MONSALVE','Aysén','RÍO IBÁÑEZ','Servicio Local'),
('8408','ESC. BASICA HERNAN MERINO CORREA','Aysén','COCHRANE','Servicio Local'),
('8409','LICEO PIONEROS DEL SUR','Aysén','O''HIGGINS','Servicio Local'),
('8410','ESCUELA MUNICIPAL CDTE LUIS BRAVO BRAVO','Aysén','TORTEL','Servicio Local'),
('8411','LICEO BICENTENARIO POLITECNICO LUIS CRUZ MARTINEZ','Magallanes','NATALES','Servicio Local'),
('8412','ESCUELA LIB. BERNARDO O´HIGGINS R.','Magallanes','NATALES','Servicio Local'),
('8413','ESCUELA CORONEL SANTIAGO BUERAS','Magallanes','NATALES','Servicio Local'),
('8415','ESCUELA CAPITAN JUAN LADRILLERO','Magallanes','NATALES','Servicio Local'),
('8416','ESC. DIF. NICOLAS MLADINIC DOBRONIC','Magallanes','NATALES','Servicio Local'),
('8417','ESCUELA BAUDILIA AVENDANO DE YOUSSUF','Magallanes','NATALES','Servicio Local'),
('8419','ESC. PROF. MIGUEL S. MONTECINOS C.','Magallanes','NATALES','Servicio Local'),
('8420','ESC. DE CONCENTRACION FRONTERIZA DOROTEA','Magallanes','NATALES','Servicio Local'),
('8421','LICEO SALESIANO MONSEÑOR FAGNANO','Magallanes','NATALES','Part. Subvencionado'),
('8422','LICEO BICENTENARIO MARIA MAZZARELLO','Magallanes','NATALES','Part. Subvencionado'),
('8423','ESC.HOGAR MUN.FRONTERIZA RAMON SERRANO M','Magallanes','TORRES DEL PAINE','Servicio Local'),
('8424','INSTITUTO SUPERIOR DE COMERCIO LICEO BICENTENARIO','Magallanes','PUNTA ARENAS','Servicio Local'),
('8425','LICEO POLIVALENTE MARIA BEHETY DE MENENDEZ','Magallanes','PUNTA ARENAS','Servicio Local'),
('8426','COLEGIO ANDINO','Magallanes','PUNTA ARENAS','Servicio Local'),
('8427','LICEO INDUSTRIAL ARMANDO QUEZADA ACHARAN','Magallanes','PUNTA ARENAS','Servicio Local'),
('8429','LICEO LUIS ALBERTO BARRERA','Magallanes','PUNTA ARENAS','Servicio Local'),
('8430','LICEO POLIVALENTE SARA BRAUN','Magallanes','PUNTA ARENAS','Servicio Local'),
('8432','CENTRO DE EDUC.INTEGRAL DE ADULTOS CEIA.','Magallanes','PUNTA ARENAS','Servicio Local'),
('8433','ESCUELA LIBERTADOR CAP GRAL BDO OHIGGINS','Magallanes','PUNTA ARENAS','Servicio Local'),
('8434','ESCUELA ESPANA','Magallanes','PUNTA ARENAS','Servicio Local'),
('8435','ESCUELA DIECIOCHO DE SEPTIEMBRE','Magallanes','PUNTA ARENAS','Servicio Local'),
('8436','ESCUELA PORTUGAL','Magallanes','PUNTA ARENAS','Servicio Local'),
('8437','ESC. CAPITAN ARTURO PRAT CHACON','Magallanes','PUNTA ARENAS','Servicio Local'),
('8438','ESCUELA REPUBLICA DE CROACIA','Magallanes','PUNTA ARENAS','Servicio Local'),
('8439','ESCUELA JUAN WILLIAMS','Magallanes','PUNTA ARENAS','Servicio Local'),
('8441','ESCUELA HERNANDO DE MAGALLANES','Magallanes','PUNTA ARENAS','Servicio Local'),
('8442','ESCUELA PEDRO PABLO LEMAITRE','Magallanes','PUNTA ARENAS','Servicio Local'),
('8443','ESCUELA ESPECIAL ROTARIO PAUL HARRIS','Magallanes','PUNTA ARENAS','Servicio Local'),
('8444','ESCUELA PATAGONIA','Magallanes','PUNTA ARENAS','Servicio Local'),
('8448','ESCUELA PEDRO SARMIENTO DE GAMBOA','Magallanes','PUNTA ARENAS','Servicio Local'),
('8449','ESCUELA ELBA OJEDA GOMEZ','Magallanes','PUNTA ARENAS','Servicio Local'),
('8450','ESCUELA DELLAMIRA REBECA AGUILAR','Magallanes','PUNTA ARENAS','Servicio Local'),
('8452','ESCUELA DE PUERTO HARRIS','Magallanes','PUNTA ARENAS','Servicio Local'),
('8454','INSTITUTO DON BOSCO','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('8455','LICEO MARIA AUXILIADORA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('8457','INSTITUTO SAGRADA FAMILIA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('8458','ESCUELA PARTICULAR LA MILAGROSA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('8463','THE BRITISH SCHOOL','Magallanes','PUNTA ARENAS','Part. Pagado'),
('8464','COLEGIO ALEMAN','Magallanes','PUNTA ARENAS','Part. Pagado'),
('8467','BERNARDO DE BRUYNE','Magallanes','RÍO VERDE','Servicio Local'),
('8468','ESCUELA DIEGO PORTALES','Magallanes','LAGUNA BLANCA','Servicio Local'),
('8470','ESCUELA PUNTA DELGADA','Magallanes','SAN GREGORIO','Servicio Local'),
('8474','LICEO BICENTENARIO HERNANDO DE MAGALLANES','Magallanes','PORVENIR','Servicio Local'),
('8475','ESCUELA LIBERTADOR BDO. O´HIGGINS R.','Magallanes','PORVENIR','Servicio Local'),
('8479','ESCUELA CERRO SOMBRERO','Magallanes','PRIMAVERA','Servicio Local'),
('8482','ESCUELA IGNACIO CARRERA PINTO','Magallanes','TIMAUKEL','Servicio Local'),
('8483','LICEO BICENTENARIO DONALD MC-INTYRE GRIFFITHS','Magallanes','CABO DE HORNOS','Servicio Local'),
('8484','ESCUELA PUERTO TORO','Magallanes','CABO DE HORNOS','Servicio Local'),
('8485','LICEO INSTITUTO NACIONAL','Metropolitana','SANTIAGO','Corp. Municipal'),
('8486','ESCUELA VILLA LAS ESTRELLAS','Magallanes','ANTÁRTICA','Corp. Municipal'),
('8487','LICEO JAVIERA CARRERA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8488','LICEO N° 4 BICENTENARIO ISAURA DINATOR','Metropolitana','SANTIAGO','Corp. Municipal'),
('8489','LICEO 6 BICENTENARIO TERESA PRATS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8490','LICEO NRO 2 MIGUEL LUIS AMUNATEGUI','Metropolitana','SANTIAGO','Corp. Municipal'),
('8491','LICEO DE APLICACION RECTOR JORGE E SCHNE','Metropolitana','SANTIAGO','Corp. Municipal'),
('8492','LICEO MANUEL BARROS BORGONO','Metropolitana','SANTIAGO','Corp. Municipal'),
('8494','LICEO A-1 VALENTIN LETELIER','Metropolitana','RECOLETA','Corp. Municipal'),
('8495','LICEO CONFEDERACION SUIZA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8496','LICEO JOSÉ DE SAN MARTIN','Metropolitana','SANTIAGO','Corp. Municipal'),
('8497','LICEO GABRIELA MISTRAL','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8498','LICEO DARIO SALAS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8499','INTERNADO NACIONAL BARROS ARANA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8500','LICEO INDUSTRIAL ELIODORO GARCIA ZEGERS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8501','LICEO POLITEC. PDTE. GABRIEL GONZALEZ VIDELA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8502','LICEO COMERCIAL LUIS CORREA PRIETO','Metropolitana','RECOLETA','Adm. Delegada'),
('8503','INST.SUP.DE COMERCIO EDUARDO FREI M.','Metropolitana','SANTIAGO','Corp. Municipal'),
('8504','LICEO TECNICO A N° 27 CLELIA CLAVEL DINAT','Metropolitana','SANTIAGO','Adm. Delegada'),
('8505','LICEO POLIVALENTE A-28 EMILIA TORO DE BAL','Metropolitana','SANTIAGO','Adm. Delegada'),
('8506','INSTITUTO COMERCIAL ELIODORO DOMINGUEZ DOMINGUEZ','Metropolitana','SANTIAGO','Adm. Delegada'),
('8507','LICEO COMERCIAL JOAQUIN VERA MORALES','Metropolitana','SANTIAGO','Adm. Delegada'),
('8508','LICEO POLIVALENTE JUAN A.RIOS','Metropolitana','QUINTA NORMAL','Corp. Municipal'),
('8510','LICEO PAULA JARAQUEMADA','Metropolitana','RECOLETA','Corp. Municipal'),
('8511','LICEO EXPERIMENTAL ARTISTICO B-65','Metropolitana','MAIPÚ','Adm. Delegada'),
('8513','ESC. BAS. REPUBLICA ORIENTAL DE URUGUAY','Metropolitana','SANTIAGO','Corp. Municipal'),
('8514','LICEO MULTIGENERO DOCTORA ELOISA DIAZ INZUNZA','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8515','ESCUELA BASICA CORNELIA OLIVARES','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8518','LICEO ESTACION CENTRAL','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8519','ESCUELA BASICA PEDRO AGUIRRE CERDA','Metropolitana','CERRILLOS','Servicio Local'),
('8520','ESCUELA BASICA PROVINCIA DE CHILOE','Metropolitana','SANTIAGO','Corp. Municipal'),
('8521','ESCUELA CARLOS CONDELL DE LA HAZA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8522','ESCUELA BASICA REPUBLICA DE COLOMBIA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8523','ESCUELA BASICA REPUBLICA DE PANAMA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8529','ESCUELA DE PARVULOS ANTU-HUILEN','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8530','ESCUELA CADETE ARTURO PRAT CHACON','Metropolitana','SANTIAGO','Corp. Municipal'),
('8531','ESCUELA BASICA IRENE FREI DE CID','Metropolitana','SANTIAGO','Corp. Municipal'),
('8532','ESCUELA BASICA LIBERTADORES DE CHILE','Metropolitana','SANTIAGO','Corp. Municipal'),
('8533','ESCUELA BASICA BENJAMIN VICUNA MACKENNA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8535','LICEO REPUBLICA DE BRASIL','Metropolitana','SANTIAGO','Corp. Municipal'),
('8536','ESCUELA REPUBLICA DE ISRAEL','Metropolitana','SANTIAGO','Corp. Municipal'),
('8537','ESCUELA ARNALDO FALABELLA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8540','ESCUELA BASICA REPUBLICA DE HAITI','Metropolitana','SANTIAGO','Corp. Municipal'),
('8541','LICEO DE ADULTOS HERBERT VARGAS WALLIS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8542','LICEO SAN FRANCISCO DE QUITO','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8544','ESCUELA BÁSICA ARTURO ALESSANDRI PALMA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8546','ESC.BAS.BILINGUE REPUBLICA DEL PARAGUAY','Metropolitana','RECOLETA','Corp. Municipal'),
('8547','ESCUELA NUEVA ZELANDIA','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8548','ESCUELA BASICA DR LUIS CALVO MACKENNA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8549','ESCUELA FERNANDO ALESSANDRI RODRIGUEZ','Metropolitana','SANTIAGO','Corp. Municipal'),
('8552','ESCUELA BAS SALVADOR SANFUENTES REP EEUU','Metropolitana','SANTIAGO','Corp. Municipal'),
('8553','ESCUELA DE ADULTOS  JORGE ALESSANDRI R.','Metropolitana','RECOLETA','Corp. Municipal'),
('8554','LICEO MUNICIPAL METROPOLITANO DE ADULTOS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8555','ESCUELA REPUBLICA EL LIBANO','Metropolitana','SANTIAGO','Corp. Municipal'),
('8556','ESCUELA REPUBLICA DE AUSTRIA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8558','ESCUELA BÁSICA VICTOR JARA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8561','ESCUELA REPUBLICA DE ALEMANIA','Metropolitana','SANTIAGO','Corp. Municipal'),
('8562','CIUDAD SANTIAGO DE CHILE','Metropolitana','SANTIAGO','Corp. Municipal'),
('8563','ESCUELA BASICA REPUBLICA DE MEXICO','Metropolitana','SANTIAGO','Corp. Municipal'),
('8564','ESCUELA BASICA REINO DE NORUEGA','Metropolitana','QUINTA NORMAL','Corp. Municipal'),
('8569','ESCUELA BASICA REPUBLICA DEL ECUADOR','Metropolitana','SANTIAGO','Corp. Municipal'),
('8571','LICEO DR HUMBERTO MATURANA ROMESIN','Metropolitana','SANTIAGO','Corp. Municipal'),
('8572','ESCUELA BASICA CAMILO MORI','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('8576','ESCUELA BASICA REYES CATOLICOS','Metropolitana','SANTIAGO','Corp. Municipal'),
('8579','ESCUELA BASICA LATINOAMERICANA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8581','ESCUELA BÁSICA F Nº 64','Metropolitana','SANTIAGO','Corp. Municipal'),
('8585','ESC. CENTRO DE CAPACITACION LABORAL SANTIAGO','Metropolitana','SANTIAGO','Corp. Municipal'),
('8586','ESCUELA DIFERENCIAL JUAN SANDOVAL C','Metropolitana','SANTIAGO','Corp. Municipal'),
('8587','LICEO DE ADULTOS MUNICIPALIZADO LUIS GOMEZ CATALAN','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('8589','LICEO MIGUEL RAFAEL PRADO','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8592','LICEO JOSE MIGUEL INFANTE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8598','COLEGIO ALTO PALENA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8601','COLEGIO WUNMAN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8603','CENTRO EDUCATIVO SALESIANOS ALAMEDA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8604','COLEGIO SANTA CRUZ','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8609','COLEGIO SAN IGNACIO','Metropolitana','SANTIAGO','Part. Pagado'),
('8611','COLEGIO NUESTRA SENORA DE ANDACOLLO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8613','COLEGIO FRANCISCANO MARIA REINA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8614','COLEGIO MARIA TERESA CANCINO AGUILAR','Metropolitana','RECOLETA','Part. Subvencionado'),
('8616','COLEGIO POLIVALENTE PLUS ULTRA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8617','LICEO POLIT. SARA BLINDER DARGOLTZ','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8620','COLEGIO SAN SEBASTIAN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8621','ESCUELA TECNICA L.BDO.O´HIGGINS-DIURNA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8623','ESC. BAS. PART. TERESIANA DE SAN GABRIEL','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8625','CENTRO EDUC. CASA TALLERES SAN VICENTE DE PAU','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8627','COLEGIO SANTA MARIA DE SANTIAGO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8629','COLEGIO POLITÉCNICO SANTA ANA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('8631','COLEGIO ECHAURREN','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8632','LICEO POLIVALENTE SANTA JULIANA','Metropolitana','RECOLETA','Part. Subvencionado'),
('8634','LICEO RUIZ TAGLE','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8636','LICEO LEONARDO MURIALDO','Metropolitana','RECOLETA','Part. Subvencionado'),
('8639','LICEO Y COLEGIO NUEVO HISPANO CHILENO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8643','INSTITUTO COMERCIAL BLAS CANAS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8644','COLEGIO INDUSTRIAL VASCO NUNEZ DE BALBOA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8645','LICEO JOSE DOMINGO CANAS','Metropolitana','QUILICURA','Part. Subvencionado'),
('8649','COLEGIO LORENZO SAZIE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8650','COLEGIO SAN BENILDO','Metropolitana','RECOLETA','Part. Subvencionado'),
('8652','COLEGIO SAN ANTONIO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8654','COLEGIO POLITECNICO AVDA. INDEPENDENCIA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8657','COLEGIO SAN ALBERTO','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8658','COLEGIO FRANCISCO ARRIARAN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8659','ESCUELA PARTICULAR FRANCISCO ANDRES OLEA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8661','ESCUELA PARTICULAR GUILLERMO MATTA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8663','INSTITUTO HERMANOS MATTE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8665','ESCUELA BASICA N°43 PATRONATO SAN ANTONIO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8666','COLEGIO SANTA ISABEL','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8671','COLEGIO BICENTENARIO VICTORIA PRIETO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8674','ESCUELA PARTICULAR SAN LAZARO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8675','COLEGIO SANTA TERESITA DEL NINO JESUS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8676','ESCUELA MANUEL JOSE IRARRAZAVAL','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8678','ESC.SILVIA SALAS EDWARDS','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8680','COLEGIO ADVENTISTA PORVENIR','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8681','COLEGIO ANGLO MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('8682','COLEGIO RAFAEL SANHUEZA LIZARDI','Metropolitana','RECOLETA','Part. Subvencionado'),
('8684','COLEGIO JEAN JACQUES','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8685','ESCUELA BASICA PARTICULAR CLUB HIPICO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('8690','ESCUELA PARTICULAR AMOR DE DIOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('8697','COLEGIO ORATORIO DON BOSCO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8699','ESCUELA PARTICULAR EL PEQUENO ESTUDIANTE','Metropolitana','RECOLETA','Part. Subvencionado'),
('8703','ESCUELA BASICA N°728 MARYLAND COLLEGE','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8706','ESCUELA SAN BENILDO','Metropolitana','RECOLETA','Part. Subvencionado'),
('8712','ESCUELA BASICA N°1319 DAVID MATARASSO 2','Metropolitana','SANTIAGO','Part. Pagado'),
('8714','ESCUELA PARTICULAR RAMON FREIRE','Metropolitana','RECOLETA','Part. Subvencionado'),
('8715','COLEGIO SAO PAULO','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('8717','ESCUELA PARTICULAR SAINT HENRY SCHOOL','Metropolitana','SANTIAGO','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
