-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 1 de 31 | filas 1-400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('1','LICEO POLITECNICO ARICA','Arica y Parinacota','ARICA','Servicio Local'),
('2','PARVULARIO LAS ESPIGUITAS','Arica y Parinacota','ARICA','Servicio Local'),
('3','ESC. PEDRO VICENTE GUTIERREZ TORRES','Arica y Parinacota','ARICA','Servicio Local'),
('4','LICEO OCTAVIO PALMA PEREZ','Arica y Parinacota','ARICA','Servicio Local'),
('5','JOVINA NARANJO FERNANDEZ','Arica y Parinacota','ARICA','Servicio Local'),
('7','L. POLI. BICENTENARIO DE EXCELENCIA ANTONIO VARAS DE LA BARRA','Arica y Parinacota','ARICA','Servicio Local'),
('8','COLEGIO EDUARDO FREI MONTALVA','Arica y Parinacota','ARICA','Servicio Local'),
('9','ESCUELA REPUBLICA DE ISRAEL','Arica y Parinacota','ARICA','Servicio Local'),
('10','ESCUELA REPUBLICA DE FRANCIA','Arica y Parinacota','ARICA','Servicio Local'),
('11','ESC. GRAL. PEDRO LAGOS MARCHANT','Arica y Parinacota','ARICA','Servicio Local'),
('12','ESCUELA GRAL JOSE MIGUEL CARRERA','Arica y Parinacota','ARICA','Servicio Local'),
('13','ESCUELA MANUEL RODRIGUEZ ERDOYZA','Arica y Parinacota','ARICA','Servicio Local'),
('14','ESCUELA ROMULO J. PENA MATURANA','Arica y Parinacota','ARICA','Servicio Local'),
('15','LICEO BICENTENARIO ARTISTICO DR. JUAN NOE CREVANI','Arica y Parinacota','ARICA','Servicio Local'),
('16','ESCUELA REGIMIENTO RANCAGUA','Arica y Parinacota','ARICA','Servicio Local'),
('17','ESCUELA SUBTTE. LUIS CRUZ MARTINEZ','Arica y Parinacota','ARICA','Servicio Local'),
('18','ESC. COMTE. JUAN JOSE SAN MARTIN','Arica y Parinacota','ARICA','Servicio Local'),
('19','ESC. HUMBERTO VALENZUELA GARCIA','Arica y Parinacota','ARICA','Servicio Local'),
('20','ESCUELA TUCAPEL','Arica y Parinacota','ARICA','Servicio Local'),
('22','ESCUELA GABRIELA MISTRAL','Arica y Parinacota','ARICA','Servicio Local'),
('25','COLEGIO CENTENARIO DE ARICA','Arica y Parinacota','ARICA','Servicio Local'),
('26','ESCUELA REPUBLICA DE ARGENTINA','Arica y Parinacota','ARICA','Servicio Local'),
('27','ESCUELA ESMERALDA','Arica y Parinacota','ARICA','Servicio Local'),
('28','ESCUELA RICARDO SILVA ARRIAGADA','Arica y Parinacota','ARICA','Servicio Local'),
('29','ESCUELA AMERICA','Arica y Parinacota','ARICA','Servicio Local'),
('30','ESCUELA DR. RICARDO OLEA GUERRA','Arica y Parinacota','ARICA','Servicio Local'),
('31','ESCUELA DARIO SALAS DIAZ','Arica y Parinacota','ARICA','Servicio Local'),
('32','LICEO AGRICOLA JOSE ABELARDO NUNEZ M.','Arica y Parinacota','ARICA','Servicio Local'),
('33','ESCUELA CARLOS CONDELL DE LA HAZA','Arica y Parinacota','ARICA','Servicio Local'),
('35','ESCUELA GRAL. MANUEL BAQUEDANO','Arica y Parinacota','ARICA','Servicio Local'),
('36','ESCUELA IGNACIO CARRERA PINTO','Arica y Parinacota','ARICA','Servicio Local'),
('38','ESCUELA ESPAÑA','Arica y Parinacota','ARICA','Servicio Local'),
('39','ESCUELA PAMPA ALGODONAL','Arica y Parinacota','ARICA','Servicio Local'),
('41','ESCUELA VALLE DE CHACA','Arica y Parinacota','ARICA','Servicio Local'),
('42','ESCUELA MOLINOS LLUTA','Arica y Parinacota','ARICA','Servicio Local'),
('43','JARDIN INFANTIL CEPILLIN','Arica y Parinacota','ARICA','Part. Subvencionado'),
('45','COLEGIO ITALIANO SANTA ANA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('47','J.  I. KURUMI','Arica y Parinacota','ARICA','Part. Pagado'),
('49','JARDIN INFANTIL PADRE LUIS GALLARDO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('50','COLEGIO ADVENTISTA DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('52','LICEO BICENTENARIO DOMINGO SANTA MARIA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('56','COLEGIO SAN MARCOS DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('59','COLEGIO SAN JORGE','Arica y Parinacota','ARICA','Part. Pagado'),
('60','COLEGIO ALEMAN DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('66','JARDIN INFANTIL PLUTO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('67','ABRAHAM LINCOLN SCHOOL','Arica y Parinacota','ARICA','Part. Subvencionado'),
('69','JUNIOR COLLEGE','Arica y Parinacota','ARICA','Part. Pagado'),
('70','ESCUELA VALLE DE ESQUINA','Arica y Parinacota','CAMARONES','Servicio Local'),
('72','LICEO VALLE DE CODPA','Arica y Parinacota','CAMARONES','Servicio Local'),
('73','ESCUELA VALLE DE COBIJA','Arica y Parinacota','CAMARONES','Servicio Local'),
('74','ESCUELA VALLE DE CAMARONES','Arica y Parinacota','CAMARONES','Servicio Local'),
('75','ESCUELA VALLE DE GUANACAGUA','Arica y Parinacota','CAMARONES','Servicio Local'),
('76','ESCUELA VALLE DE CUYA','Arica y Parinacota','CAMARONES','Servicio Local'),
('78','LICEO GRANADEROS','Arica y Parinacota','PUTRE','Servicio Local'),
('79','ESCUELA EL MARQUEZ','Arica y Parinacota','PUTRE','Servicio Local'),
('81','ESCUELA PAYACHATAS','Arica y Parinacota','PUTRE','Servicio Local'),
('82','ESCUELA SAN FRANCISCO DE ASIS','Arica y Parinacota','PUTRE','Servicio Local'),
('83','ESCUELA COTA COTANI','Arica y Parinacota','PUTRE','Servicio Local'),
('84','ESCUELA LOS ALAMOS','Arica y Parinacota','PUTRE','Servicio Local'),
('86','ESCUELA SAN SANTIAGO DE BELEN','Arica y Parinacota','PUTRE','Servicio Local'),
('87','ESCUELA ANCOLACANE','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('88','ESCUELA ALCERRECA','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('89','ESCUELA HUMAPALCA','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('90','ESCUELA INTERNADO VISVIRI','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('91','ESCUELA COSAPILLA','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('92','ESCUELA CHISLLUMA','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('93','ESCUELA CHUJLLUTA','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('94','ESCUELA GUACOYO','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('95','ESCUELA COLPITAS','Arica y Parinacota','GENERAL LAGOS','Servicio Local'),
('97','INST. COM. DE IQUIQUE BALDOMERO WOLNITZKY','Tarapacá','IQUIQUE','Servicio Local'),
('102','ESC.EDUC.ESPECIAL FLOR DEL INCA','Tarapacá','IQUIQUE','Servicio Local'),
('103','ESC.EDUC.GRAL.BAS.Y DES.ART.VIOLETA PARRA','Tarapacá','IQUIQUE','Servicio Local'),
('105','CENTRO DE CAPACITACION LABORAL','Tarapacá','IQUIQUE','Servicio Local'),
('106','INSTITUTO DEL MAR ALMIRANTE CARLOS CONDEL','Tarapacá','IQUIQUE','Adm. Delegada'),
('107','LICEO LIBERT. GRAL.BERNARDO O´HIGGINS','Tarapacá','IQUIQUE','Servicio Local'),
('108','LICEO POLITEC. JOSE GUTIERREZ DE LA FUEN','Tarapacá','IQUIQUE','Servicio Local'),
('109','COLEGIO DEPORTIVO TEC. PROF. ELENA DUVAUCHELLE CABEZON','Tarapacá','IQUIQUE','Servicio Local'),
('110','LICEO BICENTENARIO DOMINGO SANTA MARIA DE IQQ.','Tarapacá','IQUIQUE','Servicio Local'),
('111','ESCUELA GABRIELA MISTRAL','Tarapacá','IQUIQUE','Servicio Local'),
('112','ESCUELA EDUARDO LLANOS','Tarapacá','IQUIQUE','Servicio Local'),
('113','ESCUELA ALMIRANTE PATRICIO LYNCH','Tarapacá','IQUIQUE','Servicio Local'),
('114','ESCUELA PLACIDO VILLARROEL','Tarapacá','IQUIQUE','Servicio Local'),
('116','COLEGIO REPUBLICA DE CROACIA','Tarapacá','IQUIQUE','Servicio Local'),
('117','ESCUELA PAULA JARAQUEMADA ALQUIZAR','Tarapacá','IQUIQUE','Servicio Local'),
('119','ESCUELA CENTENARIO','Tarapacá','IQUIQUE','Servicio Local'),
('122','ESCUELA THILDA PORTILLO OLIVARES','Tarapacá','IQUIQUE','Servicio Local'),
('123','COLEGIO ESPANA','Tarapacá','IQUIQUE','Servicio Local'),
('124','LICEO LUIS CRUZ MARTINEZ','Tarapacá','IQUIQUE','Servicio Local'),
('125','ESCUELA PROFESOR MANUEL CASTRO RAMOS','Tarapacá','IQUIQUE','Servicio Local'),
('126','COLEGIO REPUBLICA DE ITALIA','Tarapacá','IQUIQUE','Servicio Local'),
('127','LICEO MARIA AUXILIADORA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('129','LICEO SUPERIOR GABRIELA MISTRAL','Tarapacá','IQUIQUE','Part. Subvencionado'),
('130','COLEGIO NORTH COLLEGE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('131','COLEGIO ESCASCE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('132','COLEGIO BAJO MOLLE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('133','COLEGIO ADVENTISTA DE IQUIQUE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('134','LICEO ATENEA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('136','J.  I.  CAPULLITO','Tarapacá','IQUIQUE','Part. Pagado'),
('139','JARDIN INFANTIL CONEJITO','Tarapacá','IQUIQUE','Part. Pagado'),
('144','COLEGIO IQUIQUE YOUNG SCHOOL','Tarapacá','IQUIQUE','Part. Subvencionado'),
('154','ESCUELA BASICA FRONTERIZA','Tarapacá','HUARA','Corp. Municipal'),
('156','ESCUELA PISAGUA','Tarapacá','HUARA','Corp. Municipal'),
('158','ESCUELA CHIAPA','Tarapacá','HUARA','Corp. Municipal'),
('159','ESCUELA JAINA','Tarapacá','HUARA','Corp. Municipal'),
('160','ESCUELA PACHICA','Tarapacá','HUARA','Corp. Municipal'),
('161','LICEO DE HUARA','Tarapacá','HUARA','Corp. Municipal'),
('162','ESCUELA SIBAYA','Tarapacá','HUARA','Corp. Municipal'),
('165','ESCUELA CHUSMIZA','Tarapacá','HUARA','Corp. Municipal'),
('167','ESCUELA CAMINA','Tarapacá','CAMIÑA','Corp. Municipal'),
('168','ESCUELA CUISAMA','Tarapacá','CAMIÑA','Corp. Municipal'),
('169','ESCUELA QUISTAGAMA','Tarapacá','CAMIÑA','Corp. Municipal'),
('170','ESCUELA NAMA','Tarapacá','CAMIÑA','Corp. Municipal'),
('171','ESCUELA APAMILCA','Tarapacá','CAMIÑA','Corp. Municipal'),
('172','ESCUELA CHAPIQUILTA','Tarapacá','CAMIÑA','Corp. Municipal'),
('173','ESCUELA MOQUELLA','Tarapacá','CAMIÑA','Corp. Municipal'),
('174','ESCUELA FRANCIA','Tarapacá','CAMIÑA','Corp. Municipal'),
('175','ESCUELA YALA YALA','Tarapacá','CAMIÑA','Corp. Municipal'),
('177','ESCUELA BASICA CARIQUIMA','Tarapacá','COLCHANE','Corp. Municipal'),
('178','LICEO TECNICO PROFESIONAL COLCHANE','Tarapacá','COLCHANE','Corp. Municipal'),
('179','ESCUELA BASICA MAUQUE','Tarapacá','COLCHANE','Corp. Municipal'),
('185','ESCUELA BASICA PISIGA-CHOQUE','Tarapacá','COLCHANE','Corp. Municipal'),
('186','ESCUELA BASICA ENQUELGA','Tarapacá','COLCHANE','Corp. Municipal'),
('187','ESCUELA VERTIENTE DEL SABER','Tarapacá','PICA','Corp. Municipal'),
('188','ESC. MATILLA DE NUEVA EXTREMADURA','Tarapacá','PICA','Corp. Municipal'),
('191','LIC. ALCDE.SERGIO GONZALEZ GUTIERREZ','Tarapacá','POZO ALMONTE','Municipal'),
('192','ESCUELA BASICA MAMINA','Tarapacá','POZO ALMONTE','Municipal'),
('193','ESCUELA BASICA POZO ALMONTE','Tarapacá','POZO ALMONTE','Municipal'),
('195','ESCUELA BASICA LA TIRANA','Tarapacá','POZO ALMONTE','Municipal'),
('196','ESCUELA BASICA HUATACONDO','Tarapacá','POZO ALMONTE','Municipal'),
('198','ESCUELA BASICA LA HUAYCA','Tarapacá','POZO ALMONTE','Municipal'),
('199','LICEO DOMINGO LATRILLE LASTAUNOU','Antofagasta','TOCOPILLA','Servicio Local'),
('200','LICEO POLITÉCNICO BICENTENARIO DE EXCELENCIA DIEGO PORTALES PALAZUELOS','Antofagasta','TOCOPILLA','Servicio Local'),
('201','ESCUELA CARLOS CONDELL DE LA HAZA','Antofagasta','TOCOPILLA','Servicio Local'),
('203','ESCUELA PABLO NERUDA','Antofagasta','TOCOPILLA','Servicio Local'),
('204','ESCUELA L.GRAL.BERNARDO O´HIGGINS R.','Antofagasta','TOCOPILLA','Servicio Local'),
('205','ESCUELA ARTURO PRAT CHACON','Antofagasta','TOCOPILLA','Servicio Local'),
('206','ESCUELA ESTADOS UNIDOS DE NORTEAMERICA','Antofagasta','TOCOPILLA','Servicio Local'),
('207','ESC. ESPECIAL PEDRO AGUIRRE CERDA','Antofagasta','TOCOPILLA','Servicio Local'),
('208','COLEGIO BICENTENARIO SAGRADA FAMILIA','Antofagasta','TOCOPILLA','Part. Subvencionado'),
('210','ESCUELA ARTURO PEREZ CANTO','Antofagasta','MARÍA ELENA','Servicio Local'),
('211','LICEO H.C. T.P. MARIA ELENA','Antofagasta','MARÍA ELENA','Servicio Local'),
('214','ESCUELA IGNACIO CARRERA PINTO','Antofagasta','MARÍA ELENA','Servicio Local'),
('217','LICEO BICENTENARIO LUIS CRUZ MARTINEZ','Antofagasta','CALAMA','Servicio Local'),
('218','LICEO FRANCISCO DE AGUIRRE','Antofagasta','CALAMA','Servicio Local'),
('219','LICEO BICENTENARIO POLITECNICO CESAREO AGUIRRE GOYENECHEA','Antofagasta','CALAMA','Servicio Local'),
('220','LICEO MINERO AMÉRICA','Antofagasta','CALAMA','Servicio Local'),
('222','CENTRO EDUC.INTEGRAL DE ADULTOS C.E.I.A','Antofagasta','CALAMA','Servicio Local'),
('223','ESCUELA CLAUDIO ARRAU','Antofagasta','CALAMA','Servicio Local'),
('224','ESCUELA GRECIA','Antofagasta','CALAMA','Servicio Local'),
('225','ESCUELA REPUBLICA DE BOLIVIA','Antofagasta','CALAMA','Servicio Local'),
('226','ESCUELA BASICA EMILIO SOTOMAYOR','Antofagasta','CALAMA','Servicio Local'),
('227','ESCUELA BASICA PRESIDENTE BALMACEDA','Antofagasta','CALAMA','Servicio Local'),
('228','ESCUELA BASICA VADO DE TOPATER','Antofagasta','CALAMA','Servicio Local'),
('229','ESCUELA REPUBLICA DE CHILE','Antofagasta','CALAMA','Servicio Local'),
('230','ESCUELA BASICA ANDRES BELLO','Antofagasta','CALAMA','Servicio Local'),
('231','ESCUELA BASICA JOHN FITZGERALD KENNEDY','Antofagasta','CALAMA','Servicio Local'),
('232','ESCUELA BASICA PEDRO VERGARA KELLER','Antofagasta','CALAMA','Servicio Local'),
('236','ESCUELA DE PARVULOS LAS ABEJITAS','Antofagasta','CALAMA','Servicio Local'),
('237','ESCUELA DE PARVULOS LLAMITO BLANCO','Antofagasta','CALAMA','Servicio Local'),
('238','ESCUELA DIFERENCIAL LOA','Antofagasta','CALAMA','Servicio Local'),
('239','ESCUELA BASICA 21 DE MAYO','Antofagasta','CALAMA','Servicio Local'),
('240','ESCUELA BASICA REPUBLICA DE FRANCIA','Antofagasta','CALAMA','Servicio Local'),
('241','ESCUELA PARVULARIA LAS ARDILLAS','Antofagasta','CALAMA','Servicio Local'),
('243','ESCUELA BASICA PUKARA','Antofagasta','CALAMA','Servicio Local'),
('244','ESCUELA DE PARVULOS LOS ENANITOS','Antofagasta','CALAMA','Servicio Local'),
('245','ESCUELA DE PARVULOS PAPELUCHO','Antofagasta','CALAMA','Servicio Local'),
('246','ESCUELA BASICA SENORA DE LA CANDELARIA','Antofagasta','CALAMA','Servicio Local'),
('248','ESCUELA BASICA SAN JOSE','Antofagasta','CALAMA','Servicio Local'),
('252','ESCUELA BASICA SAN FRANCISCO','Antofagasta','CALAMA','Servicio Local'),
('253','COLEGIO ADVENTISTA DE CALAMA','Antofagasta','CALAMA','Part. Subvencionado'),
('254','FUNDACION EDUCACIONAL COLEGIO NUESTRA SEÑORA DE AYQUINA','Antofagasta','CALAMA','Part. Subvencionado'),
('255','COLEGIO EJERCITO DE SALVACION','Antofagasta','CALAMA','Part. Subvencionado'),
('256','INSTITUTO OBISPO SILVA LEZAETA','Antofagasta','CALAMA','Part. Subvencionado'),
('257','COLEGIO CHUQUICAMATA','Antofagasta','CALAMA','Part. Pagado'),
('259','ESC. PARV. JESUS DE NAZARETH','Antofagasta','CALAMA','Part. Pagado'),
('262','ESCUELA DE PARVULOS MICKEY MOUSE','Antofagasta','CALAMA','Part. Subvencionado'),
('265','ESCUELA DE PARVULOS LOS CONEJITOS','Antofagasta','CALAMA','Servicio Local'),
('268','ESC. BASICA RURAL SAN ANTONIO DE PADUA','Antofagasta','OLLAGÜE','Servicio Local'),
('269','ESCUELA BASICA SAN PEDRO DE ATACAMA','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('270','COMPLEJO EDUCACIONAL TOCONAO','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('271','ESCUELA BASICA CAMAR','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('273','ESCUELA BASICA SOLOR','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('274','ESCUELA BASICA SAN ROQUE','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('275','ESCUELA BASICA ANDINA','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('276','ESCUELA BASICA TALABRE','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('277','ESCUELA BASICA SAN BARTOLOME','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('279','LICEO INDUSTRIAL EULOGIO GORDO MONEO','Antofagasta','ANTOFAGASTA','Municipal'),
('280','LICEO COMERCIAL JERARDO MUNOZ CAMPOS','Antofagasta','ANTOFAGASTA','Municipal'),
('282','LICEO A. RENDIC I. ANEXO C. REHABILIT. SOCIAL','Antofagasta','ANTOFAGASTA','Municipal'),
('283','LICEO TECNICO ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Municipal'),
('284','LICEO DE HOMBRES DE ANTOFAGASTA MARIO BAHAMONDE SILVA','Antofagasta','ANTOFAGASTA','Municipal'),
('285','LICEO BICENTENARIO MARTA NAREA DIAZ','Antofagasta','ANTOFAGASTA','Municipal'),
('286','LICEO LA PORTADA','Antofagasta','ANTOFAGASTA','Municipal'),
('287','LICEO DOMINGO HERRERA RIVERA','Antofagasta','ANTOFAGASTA','Municipal'),
('288','ESCUELA JAPON','Antofagasta','ANTOFAGASTA','Municipal'),
('289','ESCUELA ESPANA','Antofagasta','ANTOFAGASTA','Municipal'),
('291','ESCUELA PADRE GUSTAVO LE PAIGE DE WALQUE','Antofagasta','ANTOFAGASTA','Municipal'),
('292','ESCUELA REPUBLICA DE ITALIA','Antofagasta','ANTOFAGASTA','Municipal'),
('293','ESCUELA JOSE PAPIC RADNIC','Antofagasta','ANTOFAGASTA','Municipal'),
('294','ESCUELA PROFESORA LJUBICA DOMIC WUTH','Antofagasta','ANTOFAGASTA','Municipal'),
('296','ESCUELA REPUBLICA DE ESTADOS UNIDOS','Antofagasta','ANTOFAGASTA','Municipal'),
('297','ESCUELA ALCALDE MAXIMILIANO POBLETE','Antofagasta','ANTOFAGASTA','Municipal'),
('298','ESCUELA DARIO SALAS DIAZ','Antofagasta','ANTOFAGASTA','Municipal'),
('301','ESCUELA ROMULO J. PENA MATURANA','Antofagasta','ANTOFAGASTA','Municipal'),
('302','ESCUELA JUAN LOPEZ','Antofagasta','ANTOFAGASTA','Municipal'),
('303','ESCUELA REPUBLICA ARGENTINA','Antofagasta','ANTOFAGASTA','Municipal'),
('304','LICEO BICENTENARIO ANDRÉS SABELLA','Antofagasta','ANTOFAGASTA','Municipal'),
('305','ESCUELA HUMBERTO GONZALEZ ECHEGOYEN','Antofagasta','ANTOFAGASTA','Municipal'),
('306','ESCUELA HUANCHACA','Antofagasta','ANTOFAGASTA','Municipal'),
('307','ESCUELA DE PARVULOS MARCELA PAZ','Antofagasta','ANTOFAGASTA','Municipal'),
('310','ESCUELA CLAUDIO MATTE PEREZ','Antofagasta','ANTOFAGASTA','Municipal'),
('311','ESC DIFERENCIAL JUAN SANDOVAL CARRASCO','Antofagasta','ANTOFAGASTA','Municipal'),
('312','ESCUELA ECUADOR','Antofagasta','ANTOFAGASTA','Municipal'),
('313','ESCUELA ARTURO PRAT','Antofagasta','ANTOFAGASTA','Municipal'),
('315','ESCUELA HEROES DE LA CONCEPCION','Antofagasta','ANTOFAGASTA','Municipal'),
('316','ESCUELA LAS AMERICAS PROFESOR JUSTO VALLADARES ORELLANA','Antofagasta','ANTOFAGASTA','Municipal'),
('317','ESCUELA LAS ROCAS','Antofagasta','ANTOFAGASTA','Municipal'),
('318','ESCUELA EDDA CUNEO DONNAGIO','Antofagasta','ANTOFAGASTA','Municipal'),
('319','ESCUELA LA BANDERA','Antofagasta','ANTOFAGASTA','Municipal'),
('320','LICEO ARTISTICO DE ANTOFAGASTA `ARMANDO CARRERA GONZALEZ`','Antofagasta','ANTOFAGASTA','Municipal'),
('322','ESCUELA GENERAL MANUEL BAQUEDANO','Antofagasta','ANTOFAGASTA','Municipal'),
('324','ESCUELA FUNDACION MINERA ESCONDIDA','Antofagasta','ANTOFAGASTA','Municipal'),
('326','ESCUELA SANTIAGO AMENGUAL B.','Antofagasta','ANTOFAGASTA','Municipal'),
('329','LICEO BICENTENARIO INSTITUTO JOSÉ MAZA SANCHO','Antofagasta','ANTOFAGASTA','Municipal'),
('330','ESCUELA DE PARVULOS LOS PINGUINITOS','Antofagasta','ANTOFAGASTA','Municipal'),
('332','ESCUELA GABRIELA MISTRAL','Antofagasta','ANTOFAGASTA','Municipal'),
('333','ESCUELA DE PARVULOS BLANCA NIEVES','Antofagasta','ANTOFAGASTA','Municipal'),
('335','COLEGIO MISIONERO JOSE LANCASTER','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('336','LICEO EXPERIMENTAL ARTISTICO-APLICACION','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('337','COLEGIO SANTA TERESITA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('340','CENTRO TRATAMIEN.INTEGRAL RAYITO DE SOL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('341','COLEGIO ADVENTISTA DE ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('342','COLEGIO INGLES SAN JOSE','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('343','ESCUELA PRESBITERIANA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('344','COLEGIO SANTA EMILIA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('349','ESC. PARV. LAS ARDILLITAS 1','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('350','COLEGIO LIDIA MORENO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('352','ESC. PARV. PAPELUCHO','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('354','COL. KID''S SCHOOL','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('356','COLEGIO CORAZON DE MARIA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('357','COL. SAN LUIS','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('358','INS. SANTA MARIA','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('361','COL. THE ANTOFAGASTA BRITISH SCHOOL','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('364','COL. ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('365','COLEGIO EAGLE SCHOOL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('366','HRVATSKA SKOLA S. ESTEBAN (EX-J. SKOLA)','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('367','COMPLEJO EDUCATIVO JUAN JOSE LATORRE BENAVENT','Antofagasta','MEJILLONES','Corp. Municipal'),
('368','ESCUELA BASICA JULIA HERRERA VARAS','Antofagasta','MEJILLONES','Corp. Municipal'),
('369','ESCUELA LUCILA GODOY ALCAYAGA','Antofagasta','MEJILLONES','Corp. Municipal'),
('370','ESCUELA ESTACION BAQUEDANO','Antofagasta','SIERRA GORDA','Corp. Municipal'),
('371','COMPLEJO EDUCATIVO CARACOLES','Antofagasta','SIERRA GORDA','Corp. Municipal'),
('372','LICEO POLITECNICO JOSE MIGUEL QUIROZ','Antofagasta','TALTAL','Corp. Municipal'),
('373','LICEO JUAN CORTES-MONROY CORTES','Antofagasta','TALTAL','Corp. Municipal'),
('374','ESCUELA HOGAR VICTORIANO QUINTEROS SOTO','Antofagasta','TALTAL','Corp. Municipal'),
('375','ESCUELA VICTOR CARVAJAL MEZA','Antofagasta','TALTAL','Corp. Municipal'),
('377','ESCUELA PARANAL','Antofagasta','TALTAL','Corp. Municipal'),
('379','LICEO FEDERICO VARELA','Atacama','CHAÑARAL','Servicio Local'),
('380','ESCUELA BÁSICA DIEGO PORTALES PALAZUELOS','Atacama','CHAÑARAL','Servicio Local'),
('381','ESCUELA BÁSICA PEDRO LUJAN','Atacama','CHAÑARAL','Servicio Local'),
('382','ESCUELA GASPAR CABRALES, ARTÍSTICA Y DEPORTIVA','Atacama','CHAÑARAL','Servicio Local'),
('383','ESCUELA BÁSICA DIFERENCIAL JOSÉ LUIS OLIVARES ARANCIBIA','Atacama','CHAÑARAL','Servicio Local'),
('384','LICEO BICENTENARIO  MANUEL MAGALHAES MEDLING','Atacama','DIEGO DE ALMAGRO','Servicio Local'),
('386','ESCUELA ALIRO LAMAS CASTILLO','Atacama','DIEGO DE ALMAGRO','Servicio Local'),
('387','ESCUELA BÁSICA EMPERATRIZ SEPÚLVEDA LANDEROS','Atacama','DIEGO DE ALMAGRO','Servicio Local'),
('390','ESCUELA COEDUCACIONAL PARTICULAR','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('392','LICEO DIEGO DE ALMEIDA','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('396','INSTITUTO COMERCIAL ALEJANDRO RIVERA DÍAZ','Atacama','COPIAPÓ','Servicio Local'),
('397','LICEO TÉCNICO PROFESIONAL EDWIN LATORRE RIVERO','Atacama','COPIAPÓ','Servicio Local'),
('399','LICEO JOSÉ ANTONIO CARVAJAL','Atacama','COPIAPÓ','Servicio Local'),
('400','LICEO BICENTENARIO MERCEDES FRITIS MACKENNEY','Atacama','COPIAPÓ','Servicio Local'),
('401','ESCUELA BERNARDO O HIGGINS','Atacama','COPIAPÓ','Servicio Local'),
('403','ESCUELA LAURA ROBLES SILVA','Atacama','COPIAPÓ','Servicio Local'),
('404','ESCUELA EDUCACIÓN DIFERENCIAL MARÍA LUZ LANZA PIZARRO','Atacama','COPIAPÓ','Servicio Local'),
('405','ESCUELA LOS ESTANDARTES','Atacama','COPIAPÓ','Servicio Local'),
('406','ESCUELA VICENTE SEPÚLVEDA ROJO','Atacama','COPIAPÓ','Servicio Local'),
('407','ESCUELA JESÚS FERNÁNDEZ HIDALGO','Atacama','COPIAPÓ','Servicio Local'),
('408','ESCUELA PEDRO LEÓN GALLO','Atacama','COPIAPÓ','Servicio Local'),
('410','ESCUELA JOSÉ MANSO DE VELASCO','Atacama','COPIAPÓ','Servicio Local'),
('411','ESCUELA LAS CANTERAS','Atacama','COPIAPÓ','Servicio Local'),
('413','ESCUELA LAS BRISAS','Atacama','COPIAPÓ','Servicio Local'),
('415','LICEO DE MÚSICA DE COPIAPÓ HUGO GARRIDO GAETE','Atacama','COPIAPÓ','Servicio Local'),
('416','ESCUELA ABRAHAM SEPÚLVEDA PIZARRO','Atacama','COPIAPÓ','Servicio Local'),
('417','COLEGIO BUEN PASTOR','Atacama','COPIAPÓ','Servicio Local'),
('418','ESCUELA ISABEL PEÑA MORALES','Atacama','COPIAPÓ','Servicio Local'),
('419','ESCUELA HERNÁN MÁRQUEZ HUERTA','Atacama','COPIAPÓ','Servicio Local'),
('420','LICEO FERNANDO ARIZTÍA RUIZ','Atacama','COPIAPÓ','Servicio Local'),
('421','ESCUELA BRUNO ZAVALA FREDES','Atacama','COPIAPÓ','Servicio Local'),
('423','ESCUELA SAN PEDRO','Atacama','COPIAPÓ','Servicio Local'),
('427','ESCUELA LUIS CRUZ MARTÍNEZ','Atacama','COPIAPÓ','Servicio Local'),
('429','LICEO CATÓLICO ATACAMA','Atacama','COPIAPÓ','Part. Subvencionado'),
('430','LICEO POLITÉCNICO BELÉN','Atacama','COPIAPÓ','Part. Subvencionado'),
('431','LICEO SAGRADO CORAZÓN','Atacama','COPIAPÓ','Part. Subvencionado'),
('433','COLEGIO ADVENTISTA DE COPIAPÓ','Atacama','COPIAPÓ','Part. Subvencionado'),
('434','ESCUELA SAN VICENTE DE PAUL','Atacama','COPIAPÓ','Part. Subvencionado'),
('437','ESCUELA TÉCNICO PROFESIONAL','Atacama','COPIAPÓ','Part. Subvencionado'),
('438','LICEO MANUEL BLANCO ENCALADA','Atacama','CALDERA','Servicio Local'),
('439','ESCUELA TOTORAL','Atacama','COPIAPÓ','Servicio Local'),
('440','COLEGIO PARROQUIAL PADRE NEGRO','Atacama','CALDERA','Part. Subvencionado'),
('441','ESCUELA DE CONCENTRACIÓN','Atacama','TIERRA AMARILLA','Servicio Local'),
('442','ESCUELA VICTOR MANUEL SÁNCHEZ CABAÑAS','Atacama','TIERRA AMARILLA','Servicio Local'),
('444','ESCUELA LUIS URIBE ORREGO','Atacama','TIERRA AMARILLA','Servicio Local'),
('445','ESCUELA PAUL HARRIS','Atacama','TIERRA AMARILLA','Servicio Local'),
('446','ESCUELA AMOLANAS','Atacama','TIERRA AMARILLA','Servicio Local'),
('447','ESCUELA SAN ANTONIO','Atacama','TIERRA AMARILLA','Servicio Local'),
('448','LICEO PEDRO TRONCOSO MACHUCA','Atacama','VALLENAR','Servicio Local'),
('449','LICEO JOSÉ SANTOS OSSA','Atacama','VALLENAR','Servicio Local'),
('450','ESCUELA HERMANOS CARRERA','Atacama','VALLENAR','Servicio Local'),
('452','ESCUELA GABRIELA MISTRAL','Atacama','VALLENAR','Servicio Local'),
('453','ESCUELA IGNACIO CARRERA PINTO','Atacama','VALLENAR','Servicio Local'),
('454','ESCUELA GREGORIO CASTILLO MARÍN','Atacama','VALLENAR','Servicio Local'),
('455','ESCUELA REPÚBLICA DE LOS ESTADOS UNIDOS','Atacama','VALLENAR','Servicio Local'),
('456','ESCUELA EDUCACIÓN DIFERENCIAL LUIS IRIARTE IRIARTE','Atacama','VALLENAR','Servicio Local'),
('458','ESCUELA ARTURO PÉREZ CANTO','Atacama','VALLENAR','Servicio Local'),
('459','ESCUELA BÁSICA ESPAÑA','Atacama','VALLENAR','Servicio Local'),
('461','ESCUELA LUIS CRUZ MARTÍNEZ','Atacama','VALLENAR','Servicio Local'),
('462','ESCUELA JOSÉ CAROCA LAFLOR','Atacama','VALLENAR','Servicio Local'),
('463','ESCUELA BÁSICA ROBERTO CUADRA ALQUINTA','Atacama','VALLENAR','Servicio Local'),
('464','ESCUELA BÁSICA GUALBERTO KONG FERNÁNDEZ','Atacama','VALLENAR','Servicio Local'),
('467','ESCUELA HERNÁN ARAVENA CONTRERAS','Atacama','VALLENAR','Servicio Local'),
('468','ESCUELA BÁSICA IGNACIO FRANCO GALLO','Atacama','VALLENAR','Servicio Local'),
('469','ESCUELA BÁSICA JUSTINO LEIVA AMOR','Atacama','VALLENAR','Servicio Local'),
('471','ESCUELA BÁSICA SARA BEMBOW VILLEGAS','Atacama','VALLENAR','Servicio Local'),
('476','ESCUELA BÁSICA SOR TERESA DE LOS ANDES','Atacama','VALLENAR','Servicio Local'),
('478','LICEO SANTA MARTA','Atacama','VALLENAR','Part. Subvencionado'),
('479','LICEO SAN FRANCISCO','Atacama','VALLENAR','Part. Subvencionado'),
('481','ESCUELA BÁSICA ALEJANDRO NOEMI HUERTA','Atacama','FREIRINA','Servicio Local'),
('482','ESCUELA FORTUNATO SOZA RODRÍGUEZ','Atacama','FREIRINA','Servicio Local'),
('483','ESCUELA SAMUEL E. CASTILLO LOPEZ','Atacama','FREIRINA','Servicio Local'),
('484','ESCUELA DE MAITENCILLO','Atacama','FREIRINA','Servicio Local'),
('485','ESCUELA BÁSICA YERBAS BUENAS','Atacama','VALLENAR','Servicio Local'),
('486','LICEO JAPÓN','Atacama','HUASCO','Servicio Local'),
('487','ESCUELA BÁSICA JOSÉ MIGUEL CARRERA','Atacama','HUASCO','Servicio Local'),
('489','ESCUELA EL OLIVAR','Atacama','HUASCO','Servicio Local'),
('490','ESCUELA PABLO NERUDA','Atacama','HUASCO','Servicio Local'),
('492','COLEGIO PARTICULAR ENGLISH COLLEGE','Atacama','HUASCO','Part. Subvencionado'),
('493','ESCUELA EDUCADOR ARTURO ALVEAR RAMOS','Atacama','ALTO DEL CARMEN','Servicio Local'),
('495','ESCUELA AGLADE MARÍN VARGAS','Atacama','ALTO DEL CARMEN','Servicio Local'),
('496','ESCUELA DE CHOLLAY','Atacama','ALTO DEL CARMEN','Servicio Local'),
('497','ESCUELA DE LA PAMPA','Atacama','ALTO DEL CARMEN','Servicio Local'),
('498','ESCUELA ALGARROBILLA','Atacama','ALTO DEL CARMEN','Servicio Local'),
('499','ESCUELA RICARDO CAMPILLAY CONTRERAS','Atacama','ALTO DEL CARMEN','Servicio Local'),
('500','ESCUELA BÁSICA RURAL EL TAMBO','Atacama','ALTO DEL CARMEN','Servicio Local'),
('502','ESCUELA DE LAS MARQUESAS','Atacama','ALTO DEL CARMEN','Servicio Local'),
('503','ESCUELA DE LAS BREAS','Atacama','ALTO DEL CARMEN','Servicio Local'),
('504','ESCUELA GABRIELA MISTRAL','Atacama','ALTO DEL CARMEN','Servicio Local'),
('508','ESCUELA DE CHIGUINTO','Atacama','ALTO DEL CARMEN','Servicio Local'),
('514','ESCUELA DE EL CORRAL','Atacama','ALTO DEL CARMEN','Servicio Local'),
('516','LICEO GABRIELA MISTRAL DE LA SERENA','Coquimbo','LA SERENA','Servicio Local'),
('517','LICEO GREGORIO CORDOVEZ','Coquimbo','LA SERENA','Servicio Local'),
('518','LICEO TECNICO MARTA BRUNET','Coquimbo','LA SERENA','Servicio Local'),
('519','COLEGIO ARTURO PRAT CHACON','Coquimbo','LA SERENA','Servicio Local'),
('521','COLEGIO VICTOR DOMINGO SILVA','Coquimbo','LA SERENA','Servicio Local'),
('522','COLEGIO JAVIERA CARRERA','Coquimbo','LA SERENA','Servicio Local'),
('523','ESCUELA ALONSO DE ERCILLA','Coquimbo','LA SERENA','Servicio Local'),
('525','COLEGIO JAPON','Coquimbo','LA SERENA','Servicio Local'),
('526','COLEGIO JOSE MANUEL BALMACEDA','Coquimbo','LA SERENA','Servicio Local'),
('527','COLEGIO HEROES DE LA CONCEPCION','Coquimbo','LA SERENA','Servicio Local'),
('528','ESCUELA GERMAN RIESCO','Coquimbo','LA SERENA','Servicio Local'),
('529','COLEGIO MANUEL RODRIGUEZ','Coquimbo','LA SERENA','Servicio Local'),
('530','COLEGIO GABRIEL GONZALEZ VIDELA','Coquimbo','LA SERENA','Servicio Local'),
('531','COLEGIO PEDRO AGUIRRE CERDA','Coquimbo','LA SERENA','Servicio Local'),
('532','CEN.ED.INT.DE ADUL.ESTER VILLARREAL CASTILLO','Coquimbo','LA SERENA','Servicio Local'),
('533','COLEGIO DARIO SALAS','Coquimbo','LA SERENA','Servicio Local'),
('534','COLEGIO VILLA SAN BARTOLOME','Coquimbo','LA SERENA','Servicio Local'),
('535','COLEGIO JOSE MIGUEL CARRERA','Coquimbo','LA SERENA','Servicio Local'),
('536','COLEGIO DEPORTIVO OLIMPICO','Coquimbo','LA SERENA','Servicio Local'),
('537','COLEGIO LUIS BRAILLE','Coquimbo','LA SERENA','Servicio Local'),
('539','COLEGIO DE ALGARROBITO','Coquimbo','LA SERENA','Servicio Local'),
('540','ESCUELA DE ISLON','Coquimbo','LA SERENA','Servicio Local'),
('542','ESCUELA DE LAMBERT','Coquimbo','LA SERENA','Servicio Local'),
('543','COLEGIO ALTOVALSOL','Coquimbo','LA SERENA','Servicio Local'),
('544','ESCUELA DE EL MILAGRO','Coquimbo','LA SERENA','Servicio Local'),
('546','COLEGIO COQUIMBITO','Coquimbo','LA SERENA','Servicio Local'),
('548','ESCUELA DE COLONIA ALFALFARES','Coquimbo','LA SERENA','Servicio Local'),
('550','ESCUELA DE ALMIRANTE LATORRE','Coquimbo','LA SERENA','Servicio Local'),
('551','ESCUELA DE LAS ROJAS','Coquimbo','LA SERENA','Servicio Local'),
('552','ESCUELA DE CHACAY ALTO','Coquimbo','LA SERENA','Servicio Local'),
('554','ESCUELA DE PELICANA','Coquimbo','LA SERENA','Servicio Local'),
('556','ESCUELA DE ROMERO','Coquimbo','LA SERENA','Servicio Local'),
('557','ESCUELA DE SATURNO','Coquimbo','LA SERENA','Servicio Local'),
('558','COLEGIO PUNTA DE TEATINOS','Coquimbo','LA SERENA','Servicio Local'),
('560','COLEGIO QUEBRADA DE TALCA','Coquimbo','LA SERENA','Servicio Local'),
('561','COLEGIO EL ROMERAL','Coquimbo','LA SERENA','Servicio Local'),
('562','COLEGIO CALETA SAN PEDRO','Coquimbo','LA SERENA','Servicio Local'),
('564','COLEGIO LA ESTRELLA','Coquimbo','LA SERENA','Servicio Local'),
('565','COLEGIO ADVENTISTA LA SERENA','Coquimbo','LA SERENA','Part. Subvencionado'),
('566','COLEGIO ISABEL RIQUELME','Coquimbo','LA SERENA','Part. Subvencionado'),
('567','COLEGIO SAN FRANCISCO COLL','Coquimbo','LA SERENA','Part. Subvencionado'),
('568','COLEGIO SAN ANTONIO','Coquimbo','LA SERENA','Part. Subvencionado'),
('570','COLEGIO ELENA BETTINI','Coquimbo','LA SERENA','Part. Subvencionado'),
('571','ESC.ESPEC.LOS PENSAMIENTOS DE JUAN XXIII','Coquimbo','LA SERENA','Part. Subvencionado'),
('573','ESCUELA PARTICULAR TERESA VIDELA DE G','Coquimbo','LA SERENA','Part. Subvencionado'),
('574','ESCUELA INDUSTRIAL SALESIANA SAN RAMON','Coquimbo','LA SERENA','Part. Subvencionado'),
('575','COLEGIO PROVIDENCIA','Coquimbo','LA SERENA','Part. Subvencionado'),
('578','LICEO BICENTENARIO DE EXCELENCIA IGNACIO CARRERA PINTO','Coquimbo','LA SERENA','Servicio Local'),
('579','COLEGIO SEMINARIO CONCILIAR','Coquimbo','LA SERENA','Part. Subvencionado'),
('580','COLEGIO GERONIMO RENDIC','Coquimbo','LA SERENA','Part. Pagado'),
('581','ESCUELA EXPERIMENTAL DE MUSICA JORGE PEÑA HEN','Coquimbo','LA SERENA','Part. Subvencionado'),
('582','COLEGIO ANDRES BELLO','Coquimbo','LA SERENA','Part. Pagado'),
('583','COLEGIO SAGRADOS CORAZONES','Coquimbo','LA SERENA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
