-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 9 de 31 | filas 3201-3600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('5068','ESCUELA DUIDICO','Biobío','ARAUCO','Corp. Municipal'),
('5069','ESCUELA BASICA ALTO YANI','Biobío','ARAUCO','Corp. Municipal'),
('5070','ESCUELA BASICA VALLE VERDE','Biobío','ARAUCO','Corp. Municipal'),
('5072','ESCUELA VALLE ARAUCO','Biobío','ARAUCO','Corp. Municipal'),
('5073','ESCUELA BASICA BRISAS DEL MAR','Biobío','ARAUCO','Corp. Municipal'),
('5074','ESCUELA BASICA CESAR MONSALVE FLORES','Biobío','ARAUCO','Corp. Municipal'),
('5078','ESCUELA CERRO COLORADO','Biobío','ARAUCO','Corp. Municipal'),
('5080','ESCUELA BASICA PEMEREHUE','Biobío','ARAUCO','Corp. Municipal'),
('5081','ESCUELA ALTO RAQUI','Biobío','ARAUCO','Corp. Municipal'),
('5082','LICEO SAN FRANCISCO DE ASIS','Biobío','ARAUCO','Part. Subvencionado'),
('5083','COLEGIO ARAUCO','Biobío','ARAUCO','Part. Pagado'),
('5084','LICEO POLIVALENTE MARIANO LATORRE','Biobío','CURANILAHUE','Corp. Municipal'),
('5085','ESCUELA RAMIRO ROA GONZALEZ','Biobío','CURANILAHUE','Corp. Municipal'),
('5086','ESCUELA CUATRO DE OCTUBRE','Biobío','CURANILAHUE','Corp. Municipal'),
('5087','ESCUELA COLICO SUR','Biobío','CURANILAHUE','Corp. Municipal'),
('5088','ESCUELA PABLO NERUDA','Biobío','CURANILAHUE','Corp. Municipal'),
('5090','ESCUELA BUENA ESPERANZA','Biobío','CURANILAHUE','Corp. Municipal'),
('5091','ESCUELA GABRIELA MISTRAL','Biobío','CURANILAHUE','Corp. Municipal'),
('5093','ESCUELA INDEPENDENCIA','Biobío','CURANILAHUE','Corp. Municipal'),
('5094','ESCUELA SANTA TERESA DE LOS ANDES','Biobío','CURANILAHUE','Corp. Municipal'),
('5095','ESCUELA LOS CRUCEROS','Biobío','CURANILAHUE','Corp. Municipal'),
('5097','ESCUELA BAJO LOS RIOS','Biobío','CURANILAHUE','Corp. Municipal'),
('5099','ESCUELA TRONGOL ALTO','Biobío','CURANILAHUE','Corp. Municipal'),
('5100','ESCUELA PLEGARIAS','Biobío','CURANILAHUE','Corp. Municipal'),
('5101','ESCUELA SAN JOSE DE COLICO','Biobío','CURANILAHUE','Corp. Municipal'),
('5103','ESCUELA COLICO NORTE','Biobío','CURANILAHUE','Corp. Municipal'),
('5104','COLEGIO ALONSO DE ERCILLA','Biobío','CURANILAHUE','Part. Subvencionado'),
('5105','LICEO BICENTENARIO POLITECNICO CAUPOLICAN','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5106','ESCUELA FELIX EYHERAMENDY','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5109','LICEO CLAUDIO FLORES SOTO','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5110','ESCUELA PILPILCO','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5112','ESCUELA ZAIDA ARANEDA VIGUERAS','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5113','LICEO ORLANDO DELGADO ZÚNIGA','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5114','ESCUELA TEGUALDA DE RANQUILCO','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5115','ESCUELA TRONGOL BAJO','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5116','ESCUELA JOSE M.CAMPOS MENCHACA','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5117','ESCUELA LOS GUALLES','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5119','ESCUELA LAS DUNAS','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5120','ESCUELA INDEPENDENCIA','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5121','ESCUELA JOSE ULLOA FIERRO','Biobío','LOS ÁLAMOS','Corp. Municipal'),
('5122','LICEO CRISTO REDENTOR','Biobío','LOS ÁLAMOS','Part. Subvencionado'),
('5123','ESCUELA BASICA CACIQUE FRANCISCO MELIN','Biobío','CAÑETE','Corp. Municipal'),
('5126','LICEO HUMANISTA CIENTÍFICO JOSÉ DE LA CRUZ MIRANDA CORREA','Biobío','CAÑETE','Corp. Municipal'),
('5127','ESCUELA LEONCIO ARANEDA FIGUEROA','Biobío','CAÑETE','Corp. Municipal'),
('5128','ESCUELA ARTURO PRAT CHACON','Biobío','CAÑETE','Corp. Municipal'),
('5129','ESCUELA BASICA RENE ANDRADES TOLEDO','Biobío','CAÑETE','Corp. Municipal'),
('5130','ESCUELA BASICA RUBI NELSON SILVA SALAS','Biobío','CAÑETE','Corp. Municipal'),
('5131','LICEO HOMERO VIGUERAS','Biobío','CAÑETE','Corp. Municipal'),
('5132','ESCUELA RICARDO COLOMA DIAZ','Biobío','CAÑETE','Corp. Municipal'),
('5133','ESCUELA BASICA LLONCAO','Biobío','CAÑETE','Corp. Municipal'),
('5134','ESCUELA BASICA LA GRANJA','Biobío','CAÑETE','Corp. Municipal'),
('5135','ESCUELA BASICA PAICAVI','Biobío','CAÑETE','Corp. Municipal'),
('5140','ESCUELA BASICA FEDERICO GANA','Biobío','CAÑETE','Corp. Municipal'),
('5143','ESCUELA BASICA SALTO DEL HUILLINCO','Biobío','CAÑETE','Corp. Municipal'),
('5145','ESCUELA BASICA GARCIA HURTADO DE MENDOZA','Biobío','CAÑETE','Corp. Municipal'),
('5147','ESCUELA BASICA TRES SAUCES','Biobío','CAÑETE','Corp. Municipal'),
('5150','LICEO GABRIELA MISTRAL','Biobío','CAÑETE','Part. Subvencionado'),
('5151','ESCUELA PARTICULAR LUIS CRUZ MARTINEZ','Biobío','CAÑETE','Part. Subvencionado'),
('5152','ESCUELA PARTICULAR EL RIO','Biobío','CAÑETE','Part. Subvencionado'),
('5153','COLEGIO INSTITUTO SAN JOSE','Biobío','CAÑETE','Part. Subvencionado'),
('5154','ESCUELA SAN LUIS DE CONTULMO','Biobío','CONTULMO','Corp. Municipal'),
('5155','LICEO POLIVALENTE NAHUELBUTA','Biobío','CONTULMO','Corp. Municipal'),
('5157','ESCUELA BASICA GALVARINO','Biobío','CAÑETE','Corp. Municipal'),
('5158','ESCUELA BASICA JUAN AGUILERA JEREZ','Biobío','CAÑETE','Corp. Municipal'),
('5159','ESCUELA HUALLEPEN BAJO','Biobío','CONTULMO','Corp. Municipal'),
('5160','ESCUELA BASICA IRMA RAMIREZ SEPULVEDA','Biobío','CAÑETE','Corp. Municipal'),
('5162','ESCUELA HUIDE','Biobío','CONTULMO','Corp. Municipal'),
('5163','ESCUELA GRANO DE TRIGO','Biobío','CONTULMO','Corp. Municipal'),
('5165','ESCUELA HUALLEPEN ALTO','Biobío','CONTULMO','Corp. Municipal'),
('5166','ESCUELA CALEBU','Biobío','CONTULMO','Corp. Municipal'),
('5167','ESCUELA NAHUELBUTA ALTO','Biobío','CONTULMO','Corp. Municipal'),
('5168','ESCUELA VILLA RIVAS','Biobío','CONTULMO','Corp. Municipal'),
('5169','ESCUELA PICHIHUILLINCO','Biobío','CONTULMO','Corp. Municipal'),
('5170','ESCUELA HUILLINCO','Biobío','CONTULMO','Corp. Municipal'),
('5172','ESCUELA BASICA JUAN LAVIN ALVEAR','Biobío','CAÑETE','Corp. Municipal'),
('5174','ESCUELA EL ALAMO','Biobío','CONTULMO','Corp. Municipal'),
('5175','ESCUELA VILLA ELICURA','Biobío','CONTULMO','Corp. Municipal'),
('5176','ESCUELA MAHUILQUE','Biobío','CONTULMO','Corp. Municipal'),
('5178','ESCUELA BASICA PEDRO ETCHEPARE BORDA','Biobío','CAÑETE','Corp. Municipal'),
('5180','ESCUELA PARTICULAR NUEVA AURORA','Biobío','CAÑETE','Part. Subvencionado'),
('5181','ESCUELA PARTICULAR HUILLINCO ALTO','Biobío','CONTULMO','Part. Subvencionado'),
('5182','ESCUELA PARTICULAR COLLICO','Biobío','CAÑETE','Part. Subvencionado'),
('5183','ESCUELA PARTICULAR LLEU-LLEU BAJO','Biobío','CAÑETE','Part. Subvencionado'),
('5186','ESCUELA PARTICULAR VILLA HERMOSA','Biobío','CONTULMO','Part. Subvencionado'),
('5188','ESCUELA PARTICULAR BUCHOCO','Biobío','CONTULMO','Part. Subvencionado'),
('5189','ESCUELA PARTICULAR LICAUQUEN','Biobío','CONTULMO','Part. Subvencionado'),
('5192','ESCUELA ANA MOLINA','Biobío','TIRÚA','Corp. Municipal'),
('5193','ESCUELA HECTOR ISAAC CARRASCO HELDT','Biobío','TIRÚA','Corp. Municipal'),
('5194','ESCUELA ELOISA GONZALEZ','Biobío','TIRÚA','Corp. Municipal'),
('5195','ESCUELA CERRO NEGRO','Biobío','TIRÚA','Corp. Municipal'),
('5196','ESCUELA PRIMER AGUA','Biobío','TIRÚA','Corp. Municipal'),
('5197','ESCUELA CASA DE PIEDRA','Biobío','TIRÚA','Corp. Municipal'),
('5198','ESCUELA ALTO QUILANTAHUE','Biobío','TIRÚA','Corp. Municipal'),
('5200','ESCUELA ULTIMA ESPERANZA','Biobío','TIRÚA','Corp. Municipal'),
('5201','ESCUELA PUERTO PALLACO','Biobío','TIRÚA','Corp. Municipal'),
('5202','ESCUELA MAPUDUNGUN','Biobío','TIRÚA','Corp. Municipal'),
('5203','ESCUELA AGUA DE MOLINO','Biobío','TIRÚA','Corp. Municipal'),
('5204','ESCUELA LOS MAQUIS','Biobío','TIRÚA','Corp. Municipal'),
('5205','ESCUELA CHILLIMAPU','Biobío','TIRÚA','Corp. Municipal'),
('5207','ESCUELA PONOTRO HENCHI AMULEI','Biobío','TIRÚA','Corp. Municipal'),
('5208','ESCUELA PARTICULAR LOS LINGUES','Biobío','TIRÚA','Part. Subvencionado'),
('5210','ESCUELA PARTICULAR SANTOS CHÁVEZ DE CANIHUAL','Biobío','TIRÚA','Part. Subvencionado'),
('5211','ESCUELA PARTICULAR RANQUILHUE','Biobío','TIRÚA','Part. Subvencionado'),
('5212','ESCUELA PARTICULAR NUEVA LAS HUELLAS','Biobío','TIRÚA','Part. Subvencionado'),
('5213','ESCUELA PARTICULAR LAS MISIONES','Biobío','TIRÚA','Part. Subvencionado'),
('5214','ESCUELA PARTICULAR AILLINCO','Biobío','TIRÚA','Part. Subvencionado'),
('5215','LICEO INDUSTRIAL B-5 ANGOL','La Araucanía','ANGOL','Adm. Delegada'),
('5216','LICEO COMERCIAL ARMANDO BRAVO BRAVO','La Araucanía','ANGOL','Corp. Municipal'),
('5218','LICEO ENRIQUE BALLACEY COTTEREAU','La Araucanía','ANGOL','Corp. Municipal'),
('5219','LICEO BICENTENARIO POLITECNICO JUANITA FERNANDEZ','La Araucanía','ANGOL','Corp. Municipal'),
('5220','ESCUELA HERMANOS CARRERA','La Araucanía','ANGOL','Corp. Municipal'),
('5221','ESCUELA BASICA NAHUELBUTA','La Araucanía','ANGOL','Corp. Municipal'),
('5224','ESCUELA REPUBLICA FEDERAL ALEMANA','La Araucanía','ANGOL','Corp. Municipal'),
('5225','COLEGIO MARÍA SYLVESTER RASCH','La Araucanía','ANGOL','Corp. Municipal'),
('5226','ESCUELA DIEGO DUBLE URRUTIA','La Araucanía','ANGOL','Corp. Municipal'),
('5227','ESCUELA JOSÉ ELÍAS BOLIVAR HERRERA','La Araucanía','ANGOL','Corp. Municipal'),
('5228','ESCUELA VILLA HUEQUEN','La Araucanía','ANGOL','Corp. Municipal'),
('5229','ESCUELA BASICA ARAGON','La Araucanía','ANGOL','Corp. Municipal'),
('5230','CENTRO DE DESARROLLO INTEGRAL ESPAÑA','La Araucanía','ANGOL','Corp. Municipal'),
('5232','ESCUELA BASICA MIGUEL LUIS AMUNATEGUI','La Araucanía','ANGOL','Corp. Municipal'),
('5233','ESCUELA BASICA JUAN M. FERRIERE CAIRE','La Araucanía','ANGOL','Corp. Municipal'),
('5248','ESCUELA REPUBLICA DE AUSTRIA','La Araucanía','ANGOL','Corp. Municipal'),
('5249','ESC. BASICA MANUEL RODRIGUEZ','La Araucanía','ANGOL','Corp. Municipal'),
('5250','ESCUELA REGIMIENTO HUSARES','La Araucanía','ANGOL','Corp. Municipal'),
('5258','ESCUELA BASICA CHACAICO','La Araucanía','ANGOL','Corp. Municipal'),
('5264','COLEGIO SAN FRANCISCO DE ASIS DE ANGOL','La Araucanía','ANGOL','Part. Subvencionado'),
('5265','COLEGIO ADVENTISTA DE ANGOL','La Araucanía','ANGOL','Part. Subvencionado'),
('5266','COLEGIO SAN JOSE','La Araucanía','ANGOL','Part. Pagado'),
('5267','ESCUELA AGRICOLA EL VERGEL','La Araucanía','ANGOL','Part. Subvencionado'),
('5270','LICEO POLITECNICO DOMINGO STA MARIA','La Araucanía','RENAICO','Corp. Municipal'),
('5272','ESCUELA BASICA LOS NOGALES','La Araucanía','RENAICO','Corp. Municipal'),
('5273','ESCUELA MUNICIP. LA NOBEL GABRIELA','La Araucanía','RENAICO','Corp. Municipal'),
('5274','LICEO AGRICOLA FORESTAL MANZANARES','La Araucanía','RENAICO','Corp. Municipal'),
('5275','ESC. BASICA JULIO MONTT SALAMANCA','La Araucanía','RENAICO','Corp. Municipal'),
('5276','ESCUELA BASICA TOLPAN','La Araucanía','RENAICO','Corp. Municipal'),
('5280','SAN FRANCISCO DE ASIS - RENAICO','La Araucanía','RENAICO','Part. Subvencionado'),
('5282','COMPLEJO EDUCACIONAL COLLIPULLI','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5283','ESCUELA THOMAS ALVA EDISON','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5284','ESCUELA BENJAMIN FRANKLIN','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5286','ESCUELA BASICA VICTOR DURAN PEREZ','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5288','ESCUELA MICHIGAN EL AMANECER','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5289','ESCUELA F-90 RAÚL CASTRO MÁRQUEZ','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5290','ESCUELA NICOLAS PEREZ CARDENAS','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5292','ESCUELA BASICA MIGUEL HUENTELEN','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5294','ESCUELA MUNICIPAL JOEL COLLÍO MORALES','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5307','ESCUELA BASICA SAN ANDRES','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5309','ESCUELA BASICA RIO AMARGO','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5310','ESCUELA BASICA MAPUDANCO','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5314','ESCUELA CHIGUAIHUE','La Araucanía','COLLIPULLI','Corp. Municipal'),
('5315','COLEGIO PARTIC. WOLFGANG AMADEUS MOZART','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('5322','ESCUELA PARTICULAR SN.JUAN DE LA AMERICA','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('5323','LICEO BICENTENARIO POLIVALENTE LONQUIMAY','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5324','ESCUELA MUNICIPAL FRONTERIZA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5326','ESCUELA BASICA MALALMAHUIDA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5327','ESCUELA DE LIUCURA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5328','ESCUELA BASICA MITRAUQUEN','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5329','ESCUELA BASICA CRUZACO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5331','ESCUELA BASICA MARIMENUCO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5332','ESCUELA BASICA LA ANGOSTURA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5333','ESCUELA DE ICALMA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5336','ESCUELA BASICA PEHUENCO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5337','ESCUELA DE SIERRA NEVADA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5338','ESC. BASICA JUSTO SCHWEITZER M.','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5339','ESCUELA DE TROYO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5340','ESC. BASICA LEONTINA VASQUEZ RIVERA','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5341','ESCUELA BASICA DOMINGO CAMARGO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5342','ESCUELA PARTICULAR LONQUIMAY','La Araucanía','LONQUIMAY','Part. Subvencionado'),
('5343','LICEO POLITECNICO C-12 CURACAUTIN','La Araucanía','CURACAUTÍN','Adm. Delegada'),
('5344','LICEO LAS ARAUCARIAS','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5345','ESCUELA LUIS CRUZ MARTINEZ','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5346','ESCUELA OSVALDO FUENTES BARRERA','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5347','ESCUELA PATRICIO CHAVEZ SOTO','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5348','RAMON EDUARDO RAMIREZ HENRIQUEZ','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5350','ESCUELA ESPECIAL LOS VOLCANES','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5351','COLEGIO MANUEL BULNES PRIETO','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5353','ESCUELA BASICA REPUBLICA DE MEXICO','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5357','ESCUELA LOS PRADOS','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5360','ESCUELA BASICA LEFUCO','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5362','ESCUELA RIO BLANCO','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5363','ESCUELA BASICA ALEJO TASCON','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5364','ESCUELA MANCHURIA','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5365','ESCUELA JOSE CHANIN SILHY','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5368','ESC. BASICA SAN ARTURO, RADALCO ESTE.','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5371','ESCUELA DE SANTA JULIA','La Araucanía','CURACAUTÍN','Corp. Municipal'),
('5372','ESCUELA PARTICULAR SANTA ELENA','La Araucanía','CURACAUTÍN','Part. Subvencionado'),
('5373','ESCUELA PARTICULAR SANTA EMMA','La Araucanía','CURACAUTÍN','Part. Subvencionado'),
('5374','LICEO ALONSO DE ERCILLA Y ZUÑIGA','La Araucanía','ERCILLA','Corp. Municipal'),
('5375','ESCUELA BASICA SALVADOR ALLENDE','La Araucanía','ERCILLA','Corp. Municipal'),
('5376','ESCUELA BASICA SAN RAMON','La Araucanía','ERCILLA','Corp. Municipal'),
('5378','ESCUELA BASICA TEODOCIO URRUTIA','La Araucanía','ERCILLA','Corp. Municipal'),
('5379','ESCUELA TRICAUCO','La Araucanía','ERCILLA','Corp. Municipal'),
('5381','ESC. ASENTAMIENTO PABLO NERUDA','La Araucanía','ERCILLA','Corp. Municipal'),
('5382','ESCUELA MILLALEVIA','La Araucanía','ERCILLA','Corp. Municipal'),
('5385','ESCUELA CHACAIMAPU','La Araucanía','ERCILLA','Corp. Municipal'),
('5386','ESCUELA BASICA TEMOCUICUI','La Araucanía','ERCILLA','Corp. Municipal'),
('5387','ESC.PAR.SAN FRANCISCO DE ASIS DE ERCILLA','La Araucanía','ERCILLA','Part. Subvencionado'),
('5391','ESCUELA PARTICULAR SANTA ROSA','La Araucanía','ERCILLA','Part. Subvencionado'),
('5392','ESCUELA PARTICULAR EL PROGRESO','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('5393','LICEO BICENTENARIO POLITECNICO MANUEL MONTT','La Araucanía','VICTORIA','Corp. Municipal'),
('5394','LICEO JORGE ALESSANDRI RODRIGUEZ','La Araucanía','VICTORIA','Corp. Municipal'),
('5395','ESCUELA MARCELA PAZ','La Araucanía','VICTORIA','Corp. Municipal'),
('5396','COLEGIO IGNACIO CARRERA PINTO','La Araucanía','VICTORIA','Corp. Municipal'),
('5398','ESCUELA HEROES DE IQUIQUE','La Araucanía','VICTORIA','Corp. Municipal'),
('5401','ESCUELA ESPECIAL CONFEDERACION SUIZA','La Araucanía','VICTORIA','Corp. Municipal'),
('5403','ESCUELA CLAUDIO MATTE','La Araucanía','VICTORIA','Corp. Municipal'),
('5404','ESCUELA HERNAN TRIZANO AVEZZANA','La Araucanía','VICTORIA','Corp. Municipal'),
('5406','ESCUELA SELVA OSCURA','La Araucanía','VICTORIA','Corp. Municipal'),
('5407','ESCUELA BASICA PATRICIO LINCH','La Araucanía','VICTORIA','Corp. Municipal'),
('5408','ESCUELA PAILAHUEQUE','La Araucanía','VICTORIA','Corp. Municipal'),
('5410','ESCUELA PEHUENCO','La Araucanía','VICTORIA','Corp. Municipal'),
('5411','ESCUELA MUNICIPAL MONICA GEBERT MEIER','La Araucanía','VICTORIA','Corp. Municipal'),
('5414','ESCUELA BASICA TOQUIHUE','La Araucanía','VICTORIA','Corp. Municipal'),
('5415','ESCUELA BASICA EL PORVENIR','La Araucanía','VICTORIA','Corp. Municipal'),
('5422','ESCUELA BASICA LAS CARDAS','La Araucanía','VICTORIA','Corp. Municipal'),
('5423','ESCUELA BASICA TRANGOL','La Araucanía','VICTORIA','Corp. Municipal'),
('5424','ESCUELA BASICA SAN LUIS','La Araucanía','VICTORIA','Corp. Municipal'),
('5425','ESCUELA BASICA SANTA ELENA','La Araucanía','VICTORIA','Corp. Municipal'),
('5430','ESCUELA BASICA COLO','La Araucanía','VICTORIA','Corp. Municipal'),
('5431','ESCUELA BASICA SAN PEDRO','La Araucanía','VICTORIA','Corp. Municipal'),
('5434','COLEGIO INSTITUTO VICTORIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('5435','COLEGIO SANTA CRUZ DE VICTORIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('5437','ESCUELA PARTICULAR BOLLILCO','La Araucanía','VICTORIA','Part. Subvencionado'),
('5439','COMPLEJO EDUCACIONAL LUIS DURAND DURAND','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5440','LICEO LUCILA GODOY ALCAYAGA','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5441','ESCUELA REPUBLICA DE ISRAEL','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5442','ESCUELA BASICA EMILIA ROMAGNA','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5444','ESCUELA PROFESOR JUAN DE LA CRUZ MUNOZ M.','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5446','ESCUELA GUACOLDA','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5449','ESC. BASICA ANIDIR','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5455','ESC.BASICA QUILQUEN','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5459','ESC. BASICA FUNDO QUINO','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5462','ESC. BASICA REDUCCION TEMULEMU','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5463','ESC. BASICA DIDAICO','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('5465','COLEGIO BICENTENARIO LOUIS PASTEUR','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('5466','ESCUELA PARTICULAR SANTA ROSA','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('5467','LICEO AGRICOLA Y FORESTAL SUIZO LA PROVI','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('5469','ESCUELA PARTICULAR LORENZO COLIPI','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('5470','ESCUELA BASICA REPUBLICA DE ITALIA','La Araucanía','LUMACO','Corp. Municipal'),
('5471','ESCUELA F-174 VALLE DE LUMACO','La Araucanía','LUMACO','Corp. Municipal'),
('5472','ESC. MUNICIPAL PICHIPELLAHUEN','La Araucanía','LUMACO','Corp. Municipal'),
('5473','ESC. BASICA QUETRAHUE','La Araucanía','LUMACO','Corp. Municipal'),
('5474','ESC. BASICA RALUN','La Araucanía','LUMACO','Corp. Municipal'),
('5479','ESC. BASICA CHANCO','La Araucanía','LUMACO','Corp. Municipal'),
('5480','ESCUELA RUCATRARO ALTO','La Araucanía','GALVARINO','Corp. Municipal'),
('5482','ESC. BASICA RUCAYECO','La Araucanía','LUMACO','Corp. Municipal'),
('5485','ESC. BASICA BUTA RINCON','La Araucanía','LUMACO','Corp. Municipal'),
('5487','ESCUELA MUNICIPAL G-180 MARIA RIQUELME MENA','La Araucanía','LUMACO','Corp. Municipal'),
('5490','ESC. BASICA COMUDE','La Araucanía','LUMACO','Corp. Municipal'),
('5492','ESC. BASICA REDUCCION CALBUDIR','La Araucanía','LUMACO','Corp. Municipal'),
('5493','ESCUELA PARTICULAR LAS COLINAS','La Araucanía','LUMACO','Part. Subvencionado'),
('5494','ESCUELA PARTICULAR PICHI-LONCOYAN','La Araucanía','PURÉN','Part. Subvencionado'),
('5496','ESCUELA PARTICULAR QUILLUCO','La Araucanía','LUMACO','Part. Subvencionado'),
('5499','ESCUELA PARTICULAR GABRIELA MISTRAL','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('5503','ESCUELA PARTICULAR EL EDEN','La Araucanía','PURÉN','Part. Subvencionado'),
('5504','ESCUELA PARTICULAR CALBUCO','La Araucanía','LUMACO','Part. Subvencionado'),
('5506','ESCUELA GENERAL LAGOS','La Araucanía','LUMACO','Part. Subvencionado'),
('5507','LICEO MARIA AURORA GUINEZ RAMIREZ','La Araucanía','PURÉN','Corp. Municipal'),
('5508','ESCUELA PEDRO DE ONA','La Araucanía','PURÉN','Corp. Municipal'),
('5509','LICEO BICENTENARIO INDÓMITO DE PURÉN','La Araucanía','PURÉN','Corp. Municipal'),
('5510','ESCUELA ENZO FERRARI','La Araucanía','PURÉN','Corp. Municipal'),
('5512','ESC.BASICA PINGUIDAHUE','La Araucanía','PURÉN','Corp. Municipal'),
('5513','ESC. BASICA TRANAMAN','La Araucanía','PURÉN','Corp. Municipal'),
('5520','ESC. BASICA IPINCO ALTO','La Araucanía','PURÉN','Corp. Municipal'),
('5521','ESC. BASICA QUILACO','La Araucanía','PURÉN','Corp. Municipal'),
('5522','ESC. BASICA HUITRANLEBU','La Araucanía','PURÉN','Corp. Municipal'),
('5523','ESCUELA PELLAHUENCO','La Araucanía','PURÉN','Corp. Municipal'),
('5524','ESC. BASICA EL LINGUE','La Araucanía','PURÉN','Corp. Municipal'),
('5525','ESC. BASICA CAUPOLICAN','La Araucanía','PURÉN','Corp. Municipal'),
('5532','ESCUELA PARTICULAR TRULAUQUEN','La Araucanía','PURÉN','Part. Subvencionado'),
('5533','ESCUELA PARTICULAR SAN BERNARDO','La Araucanía','PURÉN','Part. Subvencionado'),
('5535','ESCUELA PARTICULAR LOS DERRAMES','La Araucanía','PURÉN','Part. Subvencionado'),
('5536','ESCUELA PARTICULAR PICHIHUENOCOLLE','La Araucanía','PURÉN','Part. Subvencionado'),
('5537','ESCUELA PARTICULAR REMEHUEICO','La Araucanía','PURÉN','Part. Subvencionado'),
('5538','ESCUELA GUSTAVO VASQUEZ DIAZ','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5539','ESCUELA DE LOS SAUCES','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5541','ESC. BASICA ELENA MULLER M.','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5542','ESC. BASICA LINO BARBIERI CANTERGIANI','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5544','ESC. BASICA SAN RAMON ALTO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5546','ESC. BASICA OSCAR CASTRO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5548','ESC. BASICA PIVADENCO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5550','ESCUELA BASICA VILLA TRINTE','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5551','ESC. BASICA GUINDO GRANDE','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5552','ESC. BASICA NAPADIR','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5554','ESC. BASICA HUITRANLEBU','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5557','ESCUELA VICENTE PEREZ ROSALES','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5558','ESC. BASICA NININCO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5561','ESCUELA DE CENTENARIO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5563','ESC. BASICA PETRONA PAILLALEO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('5565','INSTITUTO SUPERIOR DE COMERCIO','La Araucanía','TEMUCO','Corp. Municipal'),
('5566','LICEO INDUSTRIAL A-27 TEMUCO','La Araucanía','TEMUCO','Adm. Delegada'),
('5567','LICEO BICENTENARIO TECNOLOGICO PEDRO AGUIRRE CERDA','La Araucanía','TEMUCO','Corp. Municipal'),
('5568','INSTITUTO SUPERIOR DE ESPECIALIDADES TECNICAS DE TEMUCO','La Araucanía','TEMUCO','Corp. Municipal'),
('5569','LICEO GABRIELA MISTRAL DE TEMUCO','La Araucanía','TEMUCO','Corp. Municipal'),
('5570','LICEO PABLO NERUDA','La Araucanía','TEMUCO','Corp. Municipal'),
('5571','LICEO ANIBAL PINTO','La Araucanía','TEMUCO','Corp. Municipal'),
('5574','COMPLEJO EDUCACIONAL PADRE LAS CASAS','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5575','ESCUELA ARTURO PRAT','La Araucanía','TEMUCO','Corp. Municipal'),
('5578','ESCUELA LLAIMA','La Araucanía','TEMUCO','Corp. Municipal'),
('5580','ESCUELA CAMPOS DEPORTIVOS','La Araucanía','TEMUCO','Corp. Municipal'),
('5582','ESCUELA STANDAR','La Araucanía','TEMUCO','Corp. Municipal'),
('5583','ESCUELA SANTA ROSA','La Araucanía','TEMUCO','Corp. Municipal'),
('5585','ESCUELA VILLA ALEGRE','La Araucanía','TEMUCO','Corp. Municipal'),
('5588','ESCUELA MANUEL RECABARREN','La Araucanía','TEMUCO','Corp. Municipal'),
('5589','ESCUELA MILLARAY','La Araucanía','TEMUCO','Corp. Municipal'),
('5590','COMPLEJO EDUC. UN AMANECER EN LA ARAUCANIA','La Araucanía','TEMUCO','Corp. Municipal'),
('5592','ESCUELA ANDRES BELLO','La Araucanía','TEMUCO','Corp. Municipal'),
('5596','COLEGIO MUNDO MAGICO','La Araucanía','TEMUCO','Corp. Municipal'),
('5597','COLEGIO ALONSO DE ERCILLA','La Araucanía','TEMUCO','Corp. Municipal'),
('5598','ESCUELA ESPECIAL NIELOL','La Araucanía','TEMUCO','Corp. Municipal'),
('5599','ESCUELA DARIO SALAS','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5600','ESCUELA DE ADULTOS MANUEL ROJAS','La Araucanía','TEMUCO','Corp. Municipal'),
('5601','ESCUELA MUNICIPAL EL TRENCITO','La Araucanía','TEMUCO','Corp. Municipal'),
('5603','JARDIN INFANTIL MONTE VERDE','La Araucanía','TEMUCO','Corp. Municipal'),
('5604','ESCUELA PEDRO DE VALDIVIA','La Araucanía','TEMUCO','Corp. Municipal'),
('5606','ESCUELA VILLA CAROLINA','La Araucanía','TEMUCO','Corp. Municipal'),
('5608','ESCUELA LOS AVELLANOS','La Araucanía','TEMUCO','Corp. Municipal'),
('5611','ESCUELA LOS TRIGALES','La Araucanía','TEMUCO','Corp. Municipal'),
('5613','COMPLEJO EDUCACIONAL LA GRANJA','La Araucanía','VILCÚN','Corp. Municipal'),
('5614','ESCUELA LABRANZA','La Araucanía','TEMUCO','Corp. Municipal'),
('5617','ESCUELA DE PARVULOS CAMPANITA','La Araucanía','TEMUCO','Corp. Municipal'),
('5619','ESCUELA DE PARVULOS SEMILLITA','La Araucanía','TEMUCO','Corp. Municipal'),
('5620','LICEO POLIVALENTE DE ADULTOS SELVA SAAVEDRA','La Araucanía','TEMUCO','Corp. Municipal'),
('5622','ESCUELA BÁSICA BERNARDO ÑANKO','La Araucanía','LONQUIMAY','Corp. Municipal'),
('5623','ESCUELA TRUMPULO CHICO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5624','ESCUELA METRENCO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5625','ESCUELA TRUF-TRUF.','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5627','ESCUELA LAUREL HUACHO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5629','ESCUELA REDUCCION RALUNCOLLAN','La Araucanía','TEMUCO','Corp. Municipal'),
('5630','ESCUELA MANIO CHICO','La Araucanía','TEMUCO','Corp. Municipal'),
('5631','ESCUELA LICANCO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5632','ESCUELA REDUCCION MONTE VERDE','La Araucanía','TEMUCO','Corp. Municipal'),
('5633','ESCUELA CONOCO CHICO','La Araucanía','TEMUCO','Corp. Municipal'),
('5634','ESCUELA NIRRIMAPU','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5635','ESCUELA TROMEN','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5636','ESCUELA BOTROLHUE','La Araucanía','TEMUCO','Corp. Municipal'),
('5637','ESCUELA TROMEN BAJO','La Araucanía','TEMUCO','Corp. Municipal'),
('5638','ESCUELA COLPANAO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5639','ESCUELA LIRCAY','La Araucanía','TEMUCO','Corp. Municipal'),
('5640','ESCUELA MOLLULCO','La Araucanía','TEMUCO','Corp. Municipal'),
('5644','ESCUELA TROMEN ALTO','La Araucanía','TEMUCO','Corp. Municipal'),
('5645','ESCUELA BOYECO','La Araucanía','TEMUCO','Corp. Municipal'),
('5646','ESCUELA CHOMIO','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5647','ESCUELA COLLIMALLIN','La Araucanía','TEMUCO','Corp. Municipal'),
('5648','ESCUELA CHAPOD','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5649','ESCUELA FUNDO MAQUEHUE','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('5651','ESCUELA PARTICULAR COLLIN','La Araucanía','LAUTARO','Part. Subvencionado'),
('5652','COLEGIO PROVIDENCIA DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5653','LICEO CARLOS CONDELL DE LA HAZA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5654','INSTITUTO CLARET','La Araucanía','TEMUCO','Part. Subvencionado'),
('5655','LICEO COMERCIAL TEMUCO BICENTENARIO DE EXCELENCIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5656','LICEO POLITECNICO PUEBLO NUEVO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5658','COMPLEJO EDUCACIONAL JAVIERA CARRERA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5659','ESCUELA Y LICEO MONTESSORI','La Araucanía','TEMUCO','Part. Subvencionado'),
('5661','LICEO ADVENTISTA DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5662','LICEO ESPANA DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5663','LICEO BICENTENARIO DE EXCELENCIA  PADRE OSCAR MOSER','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5664','COLEGIO AUGUSTO WINTER','La Araucanía','TEMUCO','Part. Subvencionado'),
('5666','LICEO CAMILO HENRIQUEZ DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5667','ESC.PARTIC. MONS.GUIDO DE RAMBERGA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5668','ESCUELA BASICA VISTA VERDE','La Araucanía','TEMUCO','Part. Subvencionado'),
('5669','COLEGIO MADRE ADMIRABLE DE SCHOENSTATT','La Araucanía','TEMUCO','Part. Subvencionado'),
('5670','COLEGIO SAN FRANCISCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5675','ESCUELA PARTICULAR ARTURO ARRIAGADA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5677','ESC. ESP.RETARDO MENTAL LAS ARAUCARIAS','La Araucanía','TEMUCO','Part. Subvencionado'),
('5678','ESCUELA PARTICULAR NTRA.SRA.DEL CARMEN','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5680','ESC.PART.SAN FRANCISCO DE ASIS DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5682','ESCUELA PARTICULAR FRANCIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5683','ESCUELA PARTICULAR PADRE VENANCIO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5684','ESCUELA PART. WENCESLAO VALDIVIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5690','ESCUELA PARTICULAR LA ESPIGA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5693','ESCUELA PARTICULAR ESTRELLA DE BELEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('5694','ESCUELA PARTICULAR ALIANZA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5695','ESCUELA PARTICULAR SAN RAFAEL ARCANGEL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5697','ESCUELA PARTICULAR LAS AMERICAS','La Araucanía','TEMUCO','Part. Subvencionado'),
('5703','LICEO BICENTENARIO DE EXCELENCIA TECNICO PROFESIONAL CENTENARIO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5706','ESCUELA PARTICULAR SAN JUAN','La Araucanía','TEMUCO','Part. Subvencionado'),
('5709','ESCUELA PARTICULAR LOS TRIGALES','La Araucanía','TEMUCO','Part. Subvencionado'),
('5713','COLEGIO PARTICULAR I. CULTURA BRITANICA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5714','ESCUELA PART.SANTA MARIA DE LA RIBERA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5716','PADRE BARTOLOME DE LAS CASAS','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5717','ESCUELA PARTICULAR CLAUDIO MATTE','La Araucanía','TEMUCO','Part. Subvencionado'),
('5719','ESCUELA PARTICULAR ARAUCANIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5720','COLEGIO ÑIELOL CHE KIMUN','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5725','ESCUELA PARTICULAR SAN BERNARDO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5726','COLEGIO MANUEL MONTT','La Araucanía','TEMUCO','Part. Subvencionado'),
('5729','LICEO TÉCNICO FEMENINO SANTA CRUZ ÑIELOL','La Araucanía','TEMUCO','Part. Subvencionado'),
('5730','ESCUELA PARTICULAR ROBLE HUACHO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5731','ESCUELA PARTICULAR MILLAHUECO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5732','ESCUELA PARTICULAR MAQUEHUE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5734','ESCUELA PARTICULAR BOTRONHUE','La Araucanía','TEMUCO','Part. Subvencionado'),
('5737','ESCUELA PARTICULAR HERMANO PASCUAL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5740','ESCUELA PARTICULAR SAN MANUEL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5745','ESCUELA PARTICULAR MILLANTU','La Araucanía','TEMUCO','Part. Subvencionado'),
('5746','ESCUELA PARTICULAR MONO PAINE','La Araucanía','TEMUCO','Part. Subvencionado'),
('5748','ESCUELA PARTICULAR LAS LOMAS','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5750','ESCUELA PARTICULAR CRUZ DE MAYO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5751','ESCUELA SAN ANTONIO DE NIENOCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5752','ESCUELA PARTICULAR SAN PEDRO RAPA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5753','ESCUELA PARTICULAR SAN MIGUEL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5754','ESCUELA PARTICULAR NUEVA MEMBRILLAR','La Araucanía','PADRE LAS CASAS','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
