-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 16 de 31 | filas 6001-6400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('10321','LICEO LAS AMERICAS MODERNAS','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10324','ESCUELA JOSE ABELARDO NUÑEZ Nº 3','Metropolitana','HUECHURABA','Part. Subvencionado'),
('10326','ESCUELA PARTICULAR SAN JOSE','Metropolitana','RECOLETA','Part. Subvencionado'),
('10327','ESCUELA PARTICULAR SANTA TERESITA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10329','COLEGIO LIBERTADOR SAN MARTIN','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10331','COLEGIO ISABEL RIQUELME','Metropolitana','RECOLETA','Part. Subvencionado'),
('10332','ESCUELA PARTICULAR EL CARMEN','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10333','ESCUELA PARTICULAR N.SRA.DE GUADALUPE','Metropolitana','RECOLETA','Part. Subvencionado'),
('10334','ESCUELA PATROCINIO EL SEMBRADOR N 2','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10335','ESCUELA SAN JORGE','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10336','ESCUELA PARTICULAR SAN DIEGO','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10337','COLEGIO MATER DOLOROSA','Metropolitana','HUECHURABA','Part. Subvencionado'),
('10338','ESCUELA BASICA SANTO DOMINGO','Metropolitana','RECOLETA','Part. Subvencionado'),
('10341','ESCUELA BASICA PART. THE LITTLE SCHOOL','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10344','COLEGIO HELLEN´S COLLEGE','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10345','ESCUELA PARTICULAR FRANCISCO BILBAO','Metropolitana','RECOLETA','Part. Subvencionado'),
('10346','ESCUELA BASICA INES DE SUAREZ','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10348','ESCUELA BASICA PART.MARY ANNE SCHOOL','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10350','COLEGIO ELENA BETTINI','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10351','ESCUELA PARTICULAR PARQUE ASUNCION','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10352','LICEO BICENTENARIO NUEVA AURORA DE CHILE','Metropolitana','RECOLETA','Part. Subvencionado'),
('10353','ESCUELA ESPECIAL PARTICULAR LA PIRAMIDE','Metropolitana','RECOLETA','Part. Subvencionado'),
('10355','COLEGIO PARTICULAR JUAN PABLO','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10359','ESCUELA PART. SANTA LUISA DE MARILLAC','Metropolitana','HUECHURABA','Part. Subvencionado'),
('10361','ESCUELA PARTICULAR ZOLTAN DIENES','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10362','ESCUELA PARTICULAR HNAS.AGAZZI','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10363','ESCUELA PARTICULAR JAIME EYZAGUIRRE','Metropolitana','RECOLETA','Part. Subvencionado'),
('10364','ESCUELA BÁSICA Nº 953 JOSE ARTIGA','Metropolitana','RECOLETA','Part. Subvencionado'),
('10365','ESCUELA BAS. ISABEL GONZALEZ CARES','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10372','ESCUELA PARTICULAR ISLA DE PASCUA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10375','ESCUELA PARTICULAR RUTH','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10376','ESCUELA BÀSICA Nº 1090 UNIÒN LATINOAMERICANA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10377','LICEO POLIVALENTE SAINT ANDREWS','Metropolitana','LAMPA','Part. Subvencionado'),
('10384','ESCUELA BASICA PART.BRIGIDA WALKER','Metropolitana','RECOLETA','Part. Subvencionado'),
('10385','ESCUELA PART. ADVENTISTA SANTIAGO NORTE','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10386','ESCUELA ESPECIAL BELLA ESPERANZA','Metropolitana','QUILICURA','Part. Subvencionado'),
('10396','LICEO POLIVALENTE RAFAEL DONOSO CARRASCO','Metropolitana','RECOLETA','Adm. Delegada'),
('10397','LICEO INDUSTRIAL DE RECOLETA','Metropolitana','RECOLETA','Adm. Delegada'),
('10398','LICEO REBECA OLIVARES BENITEZ','Metropolitana','COLINA','Municipal'),
('10399','LICEO POLIVALENTE RIGOBERTO FONTT I.','Metropolitana','COLINA','Municipal'),
('10400','ESCUELA BASICA MARCOS GOOYCOLEA CORTES','Metropolitana','COLINA','Municipal'),
('10401','ESCUELA BASICA SANTA TERESA DEL CARMELO','Metropolitana','COLINA','Municipal'),
('10402','ESCUELA ESPECIAL ERNESTO SOTO NEGRETE','Metropolitana','COLINA','Municipal'),
('10403','ESCUELA PREMIO NOBEL PABLO NERUDA','Metropolitana','COLINA','Municipal'),
('10404','ANDALIEN DE COLINA','Metropolitana','COLINA','Municipal'),
('10405','LICEO ESMERALDA','Metropolitana','COLINA','Municipal'),
('10407','ESCUELA BASICA ALGARROBAL','Metropolitana','COLINA','Municipal'),
('10408','LICEO PELDEHUE','Metropolitana','COLINA','Municipal'),
('10409','ESC.BASICA FRANCISCO PETRINOVIC KARLOVAC','Metropolitana','COLINA','Municipal'),
('10410','ESCUELA BASICA SAN VICENTE DE LO ARCAYA','Metropolitana','COLINA','Municipal'),
('10411','ESCUELA BASICA SANTA MARTA DE LIRAY','Metropolitana','COLINA','Municipal'),
('10412','ESCUELA SAN FRANCISCO DE ASIS','Metropolitana','COLINA','Municipal'),
('10413','ESCUELA PARTICULAR PAPELUCHO','Metropolitana','COLINA','Part. Subvencionado'),
('10415','ESCUELA PARTICULAR DESIREE','Metropolitana','COLINA','Part. Subvencionado'),
('10416','CENTRO DE TRATAMIENTO INTEGRAL LOS LAURELES','Metropolitana','COLINA','Part. Subvencionado'),
('10419','LICEO BICENTENARIO MANUEL PLAZA REYES DE LAMPA','Metropolitana','LAMPA','Municipal'),
('10420','ESCUELA MANUEL SEGOVIA MONTENEGRO','Metropolitana','LAMPA','Municipal'),
('10421','ESCUELA REPUBLICA DE POLONIA','Metropolitana','LAMPA','Municipal'),
('10422','ESCUELA BASICA CACIQUE COLIN','Metropolitana','LAMPA','Municipal'),
('10424','ESCUELA SANTA  BARBARA','Metropolitana','LAMPA','Municipal'),
('10425','ESCUELA POLONIA GUTIERREZ C.','Metropolitana','LAMPA','Municipal'),
('10426','ESCUELA BASICA F-N°371 SANTA ROSA DE LAMPA','Metropolitana','LAMPA','Municipal'),
('10427','ESCUELA BASICA F - N°372 SANTA SARA','Metropolitana','LAMPA','Municipal'),
('10428','ESCUELA BASICA PROFESOR OMAR ARANDA ARAYA','Metropolitana','LAMPA','Municipal'),
('10429','NORMA GONZÁLEZ GUERRA','Metropolitana','LAMPA','Municipal'),
('10430','ESCUELA BASICA SAN SEBASTIAN DE BATUCO','Metropolitana','LAMPA','Part. Subvencionado'),
('10431','ESC. ESPECIAL PADRE LUIS GUANELLA','Metropolitana','LAMPA','Part. Subvencionado'),
('10432','LICEO POLIVALENTE MANUEL RODRIGUEZ','Metropolitana','TILTIL','Municipal'),
('10433','LICEO HUERTOS FAMILIARES','Metropolitana','TILTIL','Municipal'),
('10435','ESCUELA BASICA G-N°345 RUNGUE','Metropolitana','TILTIL','Municipal'),
('10436','ESCUELA BASICA G-N° 346','Metropolitana','TILTIL','Municipal'),
('10439','ESCUELA BASICA G-N°348','Metropolitana','TILTIL','Municipal'),
('10441','ESCUELA BASICA G-N°349','Metropolitana','TILTIL','Municipal'),
('10442','ESCUELA BASICA G-N°350','Metropolitana','TILTIL','Municipal'),
('10443','LICEO MONTENEGRO','Metropolitana','TILTIL','Municipal'),
('10444','ESCUELA BASICA G-N°352 PLAZUELA DE POLPAICO','Metropolitana','TILTIL','Municipal'),
('10447','ESCUELA PARTICULAR LA MERCED','Metropolitana','TILTIL','Part. Subvencionado'),
('10449','ESCUELA CAMINO DE LUZ','Metropolitana','PUENTE ALTO','Municipal'),
('10450','ESCUELA CONSOLIDADA','Metropolitana','PUENTE ALTO','Municipal'),
('10452','LICEO PUENTE ALTO','Metropolitana','PUENTE ALTO','Municipal'),
('10453','LICEO IND. MUNICIPALIZADO A N_ 116','Metropolitana','PUENTE ALTO','Municipal'),
('10455','LICEO SAN GERONIMO','Metropolitana','PUENTE ALTO','Municipal'),
('10456','LICEO COMERCIAL DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Municipal'),
('10457','COLEGIO MAIPO','Metropolitana','PUENTE ALTO','Municipal'),
('10458','ESCUELA VILLA INDEPENDENCIA','Metropolitana','PUENTE ALTO','Municipal'),
('10459','ESCUELA REPUBLICA DE GRECIA','Metropolitana','PUENTE ALTO','Municipal'),
('10460','CENTRO EDUCACIONAL NUEVA CREACION','Metropolitana','PUENTE ALTO','Municipal'),
('10461','ESCUELA LOS ANDES','Metropolitana','PUENTE ALTO','Municipal'),
('10462','ESCUELA NONATO COO','Metropolitana','PUENTE ALTO','Municipal'),
('10464','ESCUELA VILLA PEDRO AGUIRRE CERDA','Metropolitana','PUENTE ALTO','Municipal'),
('10465','ESCUELA EJERCITO LIBERTADOR','Metropolitana','PUENTE ALTO','Municipal'),
('10470','LICEO MUNIC.ING.MILITAR JUAN MACKENA O.','Metropolitana','PUENTE ALTO','Municipal'),
('10472','ESCUELA CASAS VIEJAS','Metropolitana','PUENTE ALTO','Municipal'),
('10473','ESCUELA OSCAR BONILLA','Metropolitana','PUENTE ALTO','Municipal'),
('10474','ESCUELA LUIS MATTE LARRAIN','Metropolitana','PUENTE ALTO','Municipal'),
('10475','ESCUELA GABRIELA','Metropolitana','PUENTE ALTO','Municipal'),
('10476','ESCUELA LAS PALMAS','Metropolitana','PUENTE ALTO','Municipal'),
('10478','ESCUELA SAN LUIS GONZAGA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10479','COLEGIO ESTELA SEGURA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10480','ESCUELA PIERRE VAYER','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10482','COLEGIO ARTURO PRAT','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10484','COLEGIO CORDILLERA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10487','COLEGIO POLIVALENTE DOMINGO MATTE MESIAS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10488','ESCUELA GENOVEVA MOLL BRIONES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10489','LICEO NUESTRA SENORA DE LAS MERCEDES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10491','ESCUELA SANTA JOAQUINA DE VEDRUNA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10492','COLEGIO CRISTIANO BELEN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10493','COLEGIO INGLES SAN LUIS GONZAGA II','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10495','ESC. PART. SAN ANDRES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10496','ESCUELA INDUSTRIAL LAS NIEVES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10497','ESC. PARTICULAR JOSEFINA GANA DE J.','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10500','COLEGIO POLIV. EL ALBORADA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10501','COLEGIO POLIV. PROFESOR ILDEFONSO CALDERON','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10502','ESCUELA PARTICULAR MIGUEL CRUCHAGA T.','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10503','COLEGIO EDUC.PART. COMP.DE MARIA P. ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10505','LICEO POLIVALENTE MARIA REINA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10506','COLEGIO SENDA DEL SABER','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10507','LICEO BICENTENARIO TÉCNICO LAS NIEVES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10512','COLEGIO LOS AROMOS','Metropolitana','PUENTE ALTO','Part. Pagado'),
('10513','COLEGIO PARTICULAR NIDAL','Metropolitana','PUENTE ALTO','Part. Pagado'),
('10515','ESCUELA DOMINGO FAUSTINO SARMIENTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('10516','LICEO MUNIC. TEC. PROF. EL LLANO','Metropolitana','PIRQUE','Municipal'),
('10519','ESCUELA BASICA G-N°646 LO ARCAYA','Metropolitana','PIRQUE','Municipal'),
('10520','LICEO  EL PRINCIPAL','Metropolitana','PIRQUE','Municipal'),
('10522','ESCUELA BASICA G-N°643 SAN JUAN DE PIRQUE','Metropolitana','PIRQUE','Municipal'),
('10524','ESCUELA BASICA G-841 SANTOS RUBIO MORALES','Metropolitana','PIRQUE','Municipal'),
('10526','LICEO POLIVALENTE SAN JOSE DE MAIPO','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10527','ESCUELA JULIETA BECERRA ALVAREZ','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10528','ESCUELA GABRIELA TOBAR PARDO','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10529','ESCUELA BASICA F-N°638 EL MELOCOTON','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10530','ESCUELA BASICA F-N°629 DE CONCENTRACION FRONTERIZA','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10532','ESCUELA BASICA G-N°631 FRONTERIZA','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10536','ESCUELA BASICA G-N°635 INTEGRADORA EL MANZANO','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10537','ESCUELA BASICA G-N°636 SAN ALFONSO','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10538','ESCUELA BASICA G-N°637 LAS MELOSAS','Metropolitana','SAN JOSÉ DE MAIPO','Corp. Municipal'),
('10540','COLEGIO RAFAEL EYZAGUIRRE','Metropolitana','SAN JOSÉ DE MAIPO','Part. Subvencionado'),
('10541','LICEO COMERCIAL DE SAN BERNARDO','Metropolitana','SAN BERNARDO','Adm. Delegada'),
('10542','CENTRO EDUCACIONAL BALDOMERO LILLO','Metropolitana','SAN BERNARDO','Servicio Local'),
('10543','LICEO POLIVALENTE A-127 FIDEL PINOCHET LE-BRUN','Metropolitana','SAN BERNARDO','Servicio Local'),
('10544','LICEO ELVIRA BRADY MALDONADO-SN.BERNARDO','Metropolitana','SAN BERNARDO','Servicio Local'),
('10545','LICEO IND. MIGUEL AYLWIN GAJARDO','Metropolitana','SAN BERNARDO','Servicio Local'),
('10546','ESCUELA PILAR MOLINER DE NUEZ','Metropolitana','SAN BERNARDO','Servicio Local'),
('10547','ESCUELA REPUBLICA DEL BRASIL','Metropolitana','SAN BERNARDO','Servicio Local'),
('10548','ESCUELA ISABEL RIQUELME','Metropolitana','SAN BERNARDO','Servicio Local'),
('10550','ESCUELA L.GRAL. BERNARDO O´HIGGINS','Metropolitana','SAN BERNARDO','Servicio Local'),
('10551','LICEO POLIV. LUCILA GODOY ALCAYAGA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10553','ESCUELA MARCIAL MARTINEZ FERRARI','Metropolitana','EL BOSQUE','Servicio Local'),
('10554','ESCUELA GENERAL RENE SCHNEIDER CHEREAU','Metropolitana','SAN BERNARDO','Servicio Local'),
('10555','ESCUELA BASICA BASE EL BOSQUE','Metropolitana','EL BOSQUE','Servicio Local'),
('10556','ESCUELA ALEMANIA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10557','ESCUELA GENERAL ALBERTO A. BACHELET MARTINEZ','Metropolitana','EL BOSQUE','Servicio Local'),
('10558','ESCUELA REPUBLICA DE LOS EE.UU. DE AMERICA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10559','ESCUELA BERNARDO LEIGHTON','Metropolitana','EL BOSQUE','Servicio Local'),
('10560','ESCUELA JAVIERA CARRERA VERDUGO','Metropolitana','SAN BERNARDO','Servicio Local'),
('10561','ESCUELA CLAUDIO ARRAU LEON','Metropolitana','EL BOSQUE','Servicio Local'),
('10563','ESCUELA MANUEL MAGALLANES MOURE','Metropolitana','SAN BERNARDO','Servicio Local'),
('10564','ESCUELA REPUBLICA DEL PERU','Metropolitana','SAN BERNARDO','Servicio Local'),
('10565','ESCUELA DIEGO PORTALES','Metropolitana','SAN BERNARDO','Servicio Local'),
('10567','ESCUELA MAHUIDA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10568','ESCUELA ORLANDO LETELIER','Metropolitana','EL BOSQUE','Servicio Local'),
('10569','LICEO NUEVO PORVENIR','Metropolitana','SAN BERNARDO','Servicio Local'),
('10570','ESCUELA BASICA DR LUIS SEPULVEDA SALVATI','Metropolitana','SAN BERNARDO','Servicio Local'),
('10571','ESCUELA ESCRITORA  MARCELA PAZ','Metropolitana','SAN BERNARDO','Servicio Local'),
('10572','LICEO FRAY LUIS BELTRAN','Metropolitana','EL BOSQUE','Servicio Local'),
('10573','CENTRO EDUCACIONAL MATIAS COUSINO','Metropolitana','EL BOSQUE','Servicio Local'),
('10574','ESCUELA ESPANA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10576','ESCUELA BÁSICA BRISAS DE CHENA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10577','ESCUELA DE EDUCACION DIFERENCIAL','Metropolitana','SAN BERNARDO','Servicio Local'),
('10578','ESCUELA STA. TERESA DE LOS MORROS','Metropolitana','SAN BERNARDO','Servicio Local'),
('10579','ESCUELA JOSE NUEZ MARTIN','Metropolitana','SAN BERNARDO','Servicio Local'),
('10580','ESCUELA ABRAHAM LINCOLN','Metropolitana','SAN BERNARDO','Servicio Local'),
('10581','ESCUELA BASICA ANTUPILLAN','Metropolitana','SAN BERNARDO','Servicio Local'),
('10584','LICEO DE ADULTOS PUCARA DE CHENA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10586','ESCUELA ELEODORO YANEZ PONCE DE LEON','Metropolitana','SAN BERNARDO','Servicio Local'),
('10588','LICEO CARDENAL ANTONIO SAMORE','Metropolitana','SAN BERNARDO','Servicio Local'),
('10589','ESCUELA HARAS LOS CONDORES','Metropolitana','SAN BERNARDO','Servicio Local'),
('10590','ESCUELA TERESA GARCIA HUIDOBRO','Metropolitana','SAN BERNARDO','Servicio Local'),
('10592','LICEO CLARA SOLOVERA','Metropolitana','SAN BERNARDO','Servicio Local'),
('10594','COLEGIO SAINT ARIELI','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10595','ESCUELA BASICA PARTICULAR ROBERTO LORCA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10600','COLEGIO MONTESSORI','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10601','ESCUELA PARTICULAR SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10604','COLEGIO VILLA SANTA MARIA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10606','COLEGIO GETSEMANI','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10607','COLEGIO DOMINGO EYZAGUIRRE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10608','COLEGIO SUPERIOR DEL MAIPO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10610','COLEGIO SAN JOSE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10611','COLEGIO AMERICAN ACADEMY','Metropolitana','SAN BERNARDO','Part. Pagado'),
('10615','COLEGIO  INGLES ISAAC NEWTON','Metropolitana','SAN BERNARDO','Part. Pagado'),
('10618','INSTITUTO SAN PABLO MISIONERO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10619','ESCUELA PARTICULAR JOSE MIGUEL CARRERA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10621','ESCUELA JOSÉ ABELARDO NÚÑEZ N°2','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10622','ESCUELA PARTICULAR MARVIT SCHOOL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10623','ESCUELA DIFERENCIAL JUAN SANDOVAL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10625','ESCUELA PARTICULAR MARIA MEDIANERA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10626','COLEGIO JUAN BAUTISTA DURAN','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10628','COLEGIO ARAGON','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10629','ESCUELA PARTICULAR EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10631','COLEGIO QUILLAHUE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('10632','CENTRO EDUC. DENVER COLORADO SCHOOL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('10635','INSTITUTO SAGRADO CORAZON','Metropolitana','SAN BERNARDO','Part. Pagado'),
('10638','LICEO 131','Metropolitana','BUIN','Municipal'),
('10640','COLEGIO DE MAIPO','Metropolitana','BUIN','Municipal'),
('10641','LICEO ALTO JAHUEL','Metropolitana','BUIN','Municipal'),
('10642','LICEO POLIVALENTE LOS GUINDOS','Metropolitana','BUIN','Municipal'),
('10643','ESCUELA VILLASECA','Metropolitana','BUIN','Municipal'),
('10645','LICEO FRANCISCO JAVIER KRUGGER ALVARADO','Metropolitana','BUIN','Municipal'),
('10646','ESCUELA VALDIVIA DE PAINE','Metropolitana','BUIN','Municipal'),
('10648','ESCUELA LO SALINAS','Metropolitana','BUIN','Municipal'),
('10649','ESCUELA HUMBERTO MORENO RAMIREZ','Metropolitana','BUIN','Municipal'),
('10651','ESCUELA LOS ROSALES DEL BAJO','Metropolitana','BUIN','Municipal'),
('10652','ESCUELA VILUCO','Metropolitana','BUIN','Municipal'),
('10655','ESCUELA ESPECIAL DEFIC MENTAL CAMPOSANO','Metropolitana','BUIN','Municipal'),
('10656','ESCUELA BASICA G-N°813 LOS AROMOS DE EL RECURSO','Metropolitana','BUIN','Municipal'),
('10658','LICEO POLIVALENTE MODERNO CARDENAL CARO','Metropolitana','BUIN','Part. Subvencionado'),
('10661','CENTRO DE EDUC.ESPECIAL HNO.BERNARDO','Metropolitana','BUIN','Part. Subvencionado'),
('10662','COLEGIO SAINT MARY COLLEGE','Metropolitana','BUIN','Part. Subvencionado'),
('10663','CENTRO EDUC. ENRIQUE BERNSTEIN CARABANTE','Metropolitana','PAINE','Corp. Municipal'),
('10665','ESCUELA ALEMANIA','Metropolitana','PAINE','Corp. Municipal'),
('10666','LICEO POLIVALENTE GREGORIO MORALES MIRANDA','Metropolitana','PAINE','Corp. Municipal'),
('10667','LICEO  MARIA CARVAJAL FUENZALIDA','Metropolitana','PAINE','Corp. Municipal'),
('10668','ESCUELA ELIAS SANCHEZ ORTUZAR','Metropolitana','PAINE','Corp. Municipal'),
('10669','ESCUELA  BARBARA KAST RIST','Metropolitana','PAINE','Corp. Municipal'),
('10671','ESCUELA CARMEN REVECO NUNEZ','Metropolitana','PAINE','Corp. Municipal'),
('10672','COLEGIO  CHALLAY','Metropolitana','PAINE','Corp. Municipal'),
('10673','ESCUELA BASICA F-N°835 HERMANOS SANCHEZ CERDA','Metropolitana','PAINE','Corp. Municipal'),
('10674','ESCUELA SENDERO DE CULITRIN','Metropolitana','PAINE','Corp. Municipal'),
('10675','ESCUELA  LAS COLONIAS','Metropolitana','PAINE','Corp. Municipal'),
('10676','ESCUELA BASICA G-N°830 FRANCISCO LETELIER VALDES','Metropolitana','PAINE','Corp. Municipal'),
('10677','ESCUELA BASICA G N°831 JAVIER EYZAGUIRRE ECHAURREN','Metropolitana','PAINE','Corp. Municipal'),
('10679','ESCUELA  BASICA G-N°832 AGUILA SUR','Metropolitana','PAINE','Corp. Municipal'),
('10680','ESCUELA HUGO PINO VILCHEZ','Metropolitana','PAINE','Corp. Municipal'),
('10685','COLEGIO PART. MARIA ANA MOGAS','Metropolitana','PAINE','Part. Subvencionado'),
('10686','LICEO MUNICIPAL POETISA GABRIELA MISTRAL','Metropolitana','CALERA DE TANGO','Servicio Local'),
('10687','ESCUELA BASICA F-N°798 CALERA DE TANGO','Metropolitana','CALERA DE TANGO','Servicio Local'),
('10688','LICEO LONQUEN','Metropolitana','CALERA DE TANGO','Servicio Local'),
('10689','ESCUELA EL ROTO CHILENO','Metropolitana','TALAGANTE','Municipal'),
('10692','ESCUELA PARTICULAR SAN IGNACIO','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('10694','ESCUELA PRESIDENTE PRIETO','Metropolitana','TALAGANTE','Municipal'),
('10696','LICEO TALAGANTE','Metropolitana','TALAGANTE','Municipal'),
('10697','LICEO POLITECNICO DE TALAGANTE','Metropolitana','TALAGANTE','Municipal'),
('10699','LICEO REPUBLICA DE GRECIA','Metropolitana','TALAGANTE','Municipal'),
('10702','ESCUELA MANUEL RODRIGUEZ ERDOIZA','Metropolitana','TALAGANTE','Municipal'),
('10703','ESCUELA ESTRELLA DE BELEN','Metropolitana','TALAGANTE','Municipal'),
('10704','ESCUELA ALBORADA DE TALAGANTE','Metropolitana','TALAGANTE','Municipal'),
('10705','ESCUELA LUIS UNDURRAGA','Metropolitana','TALAGANTE','Municipal'),
('10706','ESCUELA EL PINO VIEJO DE LONQUEN','Metropolitana','TALAGANTE','Municipal'),
('10710','COLEGIO ALCANTARA DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10711','LICEO COMERCIAL TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10712','ESCUELA BAS. COLEGIO NACIONAL','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10713','COLEGIO NINO JESUS','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10715','INSTITUTO SUBTTE.LUIS CRUZ MARTINEZ','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10716','ESCUELA BAS. BARTOLOME BLUMENTHAL','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10717','ESCUELA TECNICA SANTA MARIA MICAELA','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10719','INSTITUTO TALAGANTE','Metropolitana','TALAGANTE','Part. Pagado'),
('10721','ENGLISH COLLEGE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10722','COLEGIO TORREON','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10723','COLEGIO PARTICULAR INTEGRAL ARTURO PRAT','Metropolitana','TALAGANTE','Part. Subvencionado'),
('10724','COLEGIO CARAMPANGUE','Metropolitana','TALAGANTE','Part. Pagado'),
('10725','LICEO BICENTENARIO ISLA DE MAIPO','Metropolitana','ISLA DE MAIPO','Municipal'),
('10726','LICEO BICENTENARIO MARIO BERTERO CEVASCO','Metropolitana','ISLA DE MAIPO','Municipal'),
('10727','LICEO REPUBLICA DE ITALIA','Metropolitana','ISLA DE MAIPO','Municipal'),
('10729','ESCUELA BASICA EFRAIN MALDONADO TORRES','Metropolitana','ISLA DE MAIPO','Municipal'),
('10730','ESC.BASICA SAN ANTONIO DE NALTAGUA','Metropolitana','ISLA DE MAIPO','Municipal'),
('10734','CENTRO EDUC. PART. MARIA REINA INMACULADA','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('10735','LICEO POLIV. LUIS HUMBERTO ACOSTA GAY','Metropolitana','EL MONTE','Corp. Municipal'),
('10736','ESCUELA REPUBLICA DEL ECUADOR','Metropolitana','EL MONTE','Corp. Municipal'),
('10737','ESC. BASICA  JAVIERA CARRERA VERDUGO','Metropolitana','EL MONTE','Corp. Municipal'),
('10738','ESCUELA REPUBLICA DE HONDURAS','Metropolitana','EL MONTE','Corp. Municipal'),
('10740','ESCUELA CHINIGUE EL CRISTO','Metropolitana','EL MONTE','Corp. Municipal'),
('10741','ESCUELA EL REMANSO','Metropolitana','EL MONTE','Corp. Municipal'),
('10742','ESCUELA BAS. DIVINA PROVIDENCIA','Metropolitana','EL MONTE','Part. Subvencionado'),
('10743','INSTITUTO SAN FRANCISCO','Metropolitana','EL MONTE','Part. Subvencionado'),
('10744','ESCUELA BAS. COLEGIO EMELINA URRUTIA','Metropolitana','EL MONTE','Part. Subvencionado'),
('10746','LICEO MUNICIPALIZADO PENAFLOR','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10747','ESCUELA TERESA DE CALCUTA','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10748','ESCUELA EMILIA LASCAR','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10749','LICEO BICENTENARIO DE EXCELENCIA PAUL HARRIS','Metropolitana','PADRE HURTADO','Corp. Municipal'),
('10750','ESCUELA ROSALINA PESCIO VARGAS','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10751','LICEO COMERCIAL REPUBLICA DE BRASIL','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10752','ESCUELA REPUBLICA ARGENTINA','Metropolitana','PADRE HURTADO','Corp. Municipal'),
('10753','ESCUELA REPUBLICA CHECA','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10754','ESCUELA MAND EDUARDO FREI MONTALVA','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10755','ESCUELA ESPECIAL NAZARETH','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10756','ESCUELA SONIA PLAZA CASTRO','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10757','COLEGIO ALBERTO HURTADO CRUCHAGA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('10758','ESCUELA MALLOCO','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10760','ESCUELA REPUBLICA DE ISRAEL','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10763','ESCUELA CRISTAL CHILE','Metropolitana','PADRE HURTADO','Corp. Municipal'),
('10764','ESCUELA LA ESPERANZA','Metropolitana','PADRE HURTADO','Corp. Municipal'),
('10765','ESCUELA BASICA G-N°673 PELVIN SAN FRANCISCO DE ASIS','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10766','ESCUELA DOLORES CATTIN FAUNDEZ','Metropolitana','PEÑAFLOR','Corp. Municipal'),
('10767','ESCUELA BASICA ACADEMIA MALLOCO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('10768','ESCUELA BASICA N 41 AUGUSTO D`HALMAR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('10769','ESC.BASICA PART.BENJAMIN VERGARA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('10771','ESCUELA BAS. PART. COLEGIO CLAUDIO GAY','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('10772','COL.PART.INMAC.CONC. DE NTRA.SRA. DE LOURDES','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('10773','COMPLEJO EDUC.PART. LUIS PASTEUR','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('10774','ESCUELA PARTICULAR EL REFUGIO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('10777','COLEGIO TERRANOVA','Metropolitana','PEÑAFLOR','Part. Pagado'),
('10778','ESCUELA SAN MIGUEL','Metropolitana','MELIPILLA','Municipal'),
('10780','LICEO POLIV. HNOS. SOTOMAYOR BAEZA','Metropolitana','MELIPILLA','Municipal'),
('10781','LICEO POLITECNICO MUNICIPAL MELIPILLA','Metropolitana','MELIPILLA','Municipal'),
('10782','ESCUELA IGNACIO SERRANO MONTANER','Metropolitana','MELIPILLA','Municipal'),
('10783','LICEO GABRIELA MISTRAL DE MELIPILLA','Metropolitana','MELIPILLA','Municipal'),
('10784','COLEGIO HUILCO ALTO','Metropolitana','MELIPILLA','Municipal'),
('10785','COLEGIO MONS. JAIME LARRAIN BUNSTER','Metropolitana','MELIPILLA','Municipal'),
('10786','ESCUELA SAN JOSE DE LA VILLA','Metropolitana','MELIPILLA','Municipal'),
('10789','ESCUELA GRAL. CAROL URZUA','Metropolitana','MELIPILLA','Municipal'),
('10790','ESCUELA REPUBLICA DEL BRASIL','Metropolitana','MELIPILLA','Municipal'),
('10791','COLEGIO POMAIRE','Metropolitana','MELIPILLA','Municipal'),
('10792','LICEO POLIV. EL BOLLENAR','Metropolitana','MELIPILLA','Municipal'),
('10794','ESCUELA SANTA ROSA ESMERALDA','Metropolitana','MELIPILLA','Municipal'),
('10795','ESCUELA CLAUDIO ARRAU','Metropolitana','MELIPILLA','Municipal'),
('10796','ESCUELA PATRICIO LARRAIN GANDARILLAS','Metropolitana','MELIPILLA','Municipal'),
('10797','ESCUELA PEDRO MARIN ALEMANY','Metropolitana','MELIPILLA','Municipal'),
('10798','ESCUELA BASICA CARMEN BAJO','Metropolitana','MELIPILLA','Municipal'),
('10799','ESCUELA RAMON NOGUERA PRIETO','Metropolitana','MELIPILLA','Municipal'),
('10800','ESCUELA CHOLQUI','Metropolitana','MELIPILLA','Municipal'),
('10805','ESCUELA PUANGUE','Metropolitana','MELIPILLA','Municipal'),
('10810','ESCUELA LIDIA MATTE HURTADO','Metropolitana','MELIPILLA','Municipal'),
('10816','ESCUELA JOSE CAMARENA ESCRIVA','Metropolitana','MELIPILLA','Municipal'),
('10818','ESCUELA HUECHUN','Metropolitana','MELIPILLA','Municipal'),
('10821','ESCUELA RAQUEL FERNANDEZ DE MORANDE','Metropolitana','MELIPILLA','Municipal'),
('10825','ESCUELA PADRE ALBERTO HURTADO','Metropolitana','MELIPILLA','Municipal'),
('10827','ESCUELA BASICA EL PABELLON','Metropolitana','MELIPILLA','Municipal'),
('10828','COLEGIO PARTICULAR ALONSO DE ERCILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10829','ESC. BAS. NUESTRA SEÑORA Y MADRE DEL CARMEN','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10830','COLEGIO POLITEC.NTRA.SRA.DE LA PRESENTAC','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10831','COLEGIO PARTICULAR MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10832','COLEGIO POLIVALENTE SAN AGUSTIN','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10833','CENTRO EDUCACIONAL MENESIANO','Metropolitana','MELIPILLA','Part. Subvencionado'),
('10834','COLEGIO MARAMBIO','Metropolitana','MELIPILLA','Part. Pagado'),
('10835','LICEO MUNICIPAL F-N°860','Metropolitana','MARÍA PINTO','Municipal'),
('10836','ESCUELA BASICA F-N° 732 CHOROMBO ALTO','Metropolitana','MARÍA PINTO','Municipal'),
('10837','ESCUELA BASICA F-N°738 LOS RULOS','Metropolitana','MARÍA PINTO','Municipal'),
('10838','ESCUELA BASICA G-N°733 CHOROMBO BAJO','Metropolitana','MARÍA PINTO','Municipal'),
('10839','ESCUELA BASICA G-N°734 LAS MERCEDES','Metropolitana','MARÍA PINTO','Municipal'),
('10840','ESCUELA BASICA G-N°737 SANTA EMILIA','Metropolitana','MARÍA PINTO','Municipal'),
('10842','ESCUELA BASICA VALLE DE PUANGUE','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10844','ESCUELA SAN JOSE OBRERO DE CURACAVI','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10845','LICEO BICENTENARIO PRESIDENTE BALMACEDA','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10846','ESCUELA FERNANDO CARVAJAL PINTO','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10848','ESCUELA ELIECER PEREZ VARGAS','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10849','ESCUELA HERIBERTO ERLWEIN  S.','Metropolitana','CURACAVÍ','Corp. Municipal'),
('10851','COLEGIO INSTITUTO SAN LUIS DE CURACAVI','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('10852','ESCUELA BASICA N°403 NUESTRA SRA. DE LA GUARDIA','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('10854','LICEO MUNICIPAL DE SAN PEDRO','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10856','ESCUELA BASICA G-N°126','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10858','ESCUELA BASICA G-N°128 ATALICIO AGUILAR A.','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10861','ESCUELA BASICA G-N°130','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10862','ESCUELA BASICA G-N°131','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10864','ESCUELA BASICA G-N°134 NIHUE','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10865','ESCUELA ENRIQUE REYMOND ALDUNATE','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10868','ESCUELA BASICA G-N°139','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10869','ESCUELA BASICA G-N°140','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10870','ESCUELA BASICA G-N°141','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10871','ESCUELA BASICA G-N°498','Metropolitana','SAN PEDRO','Corp. Municipal'),
('10873','LICEO MUNICIPAL SARA TRONCOSO TRONCOSO','Metropolitana','ALHUÉ','Corp. Municipal'),
('10877','ESCUELA EL ASIENTO','Metropolitana','ALHUÉ','Corp. Municipal'),
('10878','ESCUELA BARRANCAS DE PICHI','Metropolitana','ALHUÉ','Corp. Municipal'),
('10879','ESCUELA SAN ALFONSO','Metropolitana','ALHUÉ','Corp. Municipal'),
('10880','ESCUELA HACIENDA ALHUE','Metropolitana','ALHUÉ','Corp. Municipal'),
('10881','COLEGIO SAN SEBASTIAN','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('10884','ESC. EDUCACION ESPECIAL LOS IBISCOS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('10887','ESCUELA DE CHITITA','Arica y Parinacota','CAMARONES','Servicio Local'),
('10889','CENTRO TRAT. INTEG. LOS TAMARUGOS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('10892','NORTH AMERICAN COLLEGE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('10893','ESCUELA EJERCITO DE SALVACION','Arica y Parinacota','ARICA','Part. Subvencionado'),
('10897','ESCUELA DE ILLAPATA','Arica y Parinacota','CAMARONES','Servicio Local'),
('10898','JARDIN INFANTIL ACUARELA','Tarapacá','IQUIQUE','Part. Pagado'),
('10900','COLEGIO LIRIMA','Tarapacá','IQUIQUE','Part. Pagado'),
('10901','COLEGIO SAN MARTIN','Tarapacá','IQUIQUE','Part. Subvencionado'),
('10905','ESCUELA BASICA FUERTE BAQUEDANO','Tarapacá','POZO ALMONTE','Municipal'),
('10906','COLEGIO FORD COLLEGE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('10911','LICEO BICENTENARIO PABLO NERUDA','Arica y Parinacota','ARICA','Servicio Local'),
('10912','ESCUELA VALLE DE PARCOHAYLLA','Arica y Parinacota','CAMARONES','Servicio Local'),
('10913','CENTRO CAP.LAB. REINO DE BELGICA','Arica y Parinacota','ARICA','Servicio Local'),
('10915','COLEGIO CARDENAL ANTONIO SAMORE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('10916','ESCUELA CALETA CHANAVAYITA','Tarapacá','IQUIQUE','Servicio Local'),
('10917','LICEO S.S JUAN PABLO SEGUNDO','Tarapacá','ALTO HOSPICIO','Servicio Local'),
('10956','ESCUELA DIFERENCIAL SANTA CECILIA','Antofagasta','CALAMA','Part. Subvencionado'),
('10962','COLEGIO JUAN PABLO II','Antofagasta','CALAMA','Part. Subvencionado'),
('10963','COLEGIO EVANGELICO EJERCITO DE SALVACION CATHERINE BOOTH','Antofagasta','CALAMA','Part. Subvencionado'),
('10967','LICEO ELEUTERIO RAMIREZ MOLINA','Antofagasta','CALAMA','Servicio Local'),
('10968','LICEO MAYOR GRAL.(E) OSCAR BONILLA','Antofagasta','ANTOFAGASTA','Municipal'),
('10970','LICEO TECNICO PROFESIONAL JORGE ALESSANDRI RODRIGUEZ','Antofagasta','CALAMA','Servicio Local'),
('10971','ANEXO LICEO NOCTURNO','Antofagasta','CALAMA','Servicio Local'),
('10974','ESCUELA NUEVA LUZ ALEJANDRO MARTINETTI TAPIA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('10975','ESCUELA DE PARVULOS SAINT PATRICK S SCH.','Antofagasta','CALAMA','Part. Subvencionado'),
('10976','ESC. PARVULOS PRESBITERIANA EL REDENTOR','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('10979','LICEO A.RENDIC I, ANEXO CENTRO PREVENCION FEM','Antofagasta','ANTOFAGASTA','Municipal'),
('11025','ESCUELA FRONTERIZA','Atacama','ALTO DEL CARMEN','Servicio Local'),
('11027','ESCUELA HORNITOS','Atacama','TIERRA AMARILLA','Servicio Local'),
('11029','ESCUELA PROFESOR LUIS GARRIDO PÁVEZ','Atacama','CHAÑARAL','Servicio Local'),
('11030','ESCUELA ANDRÉS BELLO','Atacama','VALLENAR','Servicio Local'),
('11031','ESCUELA SARA CRUZ ALVAYAY','Atacama','ALTO DEL CARMEN','Servicio Local'),
('11032','ESCUELA CRISTIANA BÁSICA BETHEL','Atacama','VALLENAR','Part. Subvencionado'),
('11033','ESCUELA BÁSICA ANGELINA SALAS OLIVARES','Atacama','CHAÑARAL','Servicio Local'),
('11034','LICEO JORGE ALESSANDRI RODRÍGUEZ','Atacama','TIERRA AMARILLA','Servicio Local')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
