-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 27 de 31 | filas 10401-10800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('26001','COLEGIO ALICANTE DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26003','ESC. ESPECIAL ELSA MATILDE ULRICH JARA','Metropolitana','COLINA','Municipal'),
('26004','ESCUELA ESP. RENACERES','Metropolitana','RECOLETA','Part. Subvencionado'),
('26005','ESCUELA ESP. MI MUNDO EN PALABRAS','Metropolitana','LO PRADO','Part. Subvencionado'),
('26006','COLEGIO ECOLOGICO PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('26012','COLEGIO BICENTENARIO MODERNO PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('26013','ESCUELA ESP.  JOSE MAZA FERNANDEZ','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26014','ESCUELA ESP. BILBAO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26015','ESC.BASICA Y ESP.MARIA DE LOS ANGELES DE BUIN','Metropolitana','BUIN','Part. Subvencionado'),
('26016','ESCUELA ESP. ESPERANZA DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26017','ESCUELA BAS. KINGS SCHOOL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26019','ESCUELA BASICA Y ESPECIAL N° 2078 GENESIS 2005','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26021','ESC. DE PARV. Y ESP. SAN PIO DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('26022','ESCUELA ESP. FERNANDA FRIAS RETAMAL','Metropolitana','RECOLETA','Part. Subvencionado'),
('26025','COLEGIO SANTA BARBARA COLLEGE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26027','COLEGIO DE AD. INSTITUTO NUEVA IMAGEN','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26028','COLEGIO EMMANUEL HIGH SCHOOL','Metropolitana','LA FLORIDA','Part. Pagado'),
('26030','COLEGIO DE ADULTOS INSTITUTO NUEVO BILBAO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('26031','ESCUELA DE PARV. MI PRIMERA AVENTURA','Metropolitana','MACUL','Part. Subvencionado'),
('26032','INSTITUTO DE EDUCACIÓN DE ADULTOS LA CASTRINA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('26033','COLEGIO  SAN CARLOS DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('26035','ESCUELA PART. SAN JOSE DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26036','ESCUELA ESPECIAL N 2086 HOSPITAL CLINICO PONTIFICIA UNIVERSIDAD CATÓLICA DE CHILE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('26037','COLEGIO LO BARNECHEA BICENTENARIO','Metropolitana','LO BARNECHEA','Corp. Municipal'),
('26039','ESCUELA BAS. SAN MATEO SCHOOL DE CONCHALI','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('26043','ESCUELA SANTA TERESA DE LOS ANDES','Metropolitana','BUIN','Part. Pagado'),
('26044','ESCUELA BAS. Y ESP. LIKAN-RAY DE LA PINTANA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26045','ESCUELA  SAN PEDRO VALLE GRANDE','Metropolitana','LAMPA','Part. Subvencionado'),
('26046','COLEGIO  MANQUECURA CIUDAD DE LOS VALLES','Metropolitana','PUDAHUEL','Part. Pagado'),
('26047','ESCUELA DE PARV. PIN PON','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('26050','ESCUELA DE PARV. TIA LORENA','Metropolitana','MAIPÚ','Part. Pagado'),
('26051','ESCUELA DE PARV. EL CASTILLO','Metropolitana','MAIPÚ','Part. Pagado'),
('26052','ESCUELA DE PARV. CRECER FELIZ','Metropolitana','MAIPÚ','Part. Pagado'),
('26053','COLEGIO ATENAS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26054','COLEGIO DE ADULTOS INSTITUTO ROGERIANO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26057','ESCUELA DE PARVULOS N°2097 LOS ENANITOS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26058','ESCUELA DE PARV. ANAKENA','Metropolitana','PUENTE ALTO','Part. Pagado'),
('26061','COLEGIO DE ADULTO LAURA VICUNA DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('26062','COLEGIO DE AD. SAN JAVIER DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('26063','COLEGIO DE AD. INSTITUTO HUMBOLDT','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26064','ESCUELA ESP. SAN MARTIN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26065','ESC. PARV. ITACA','Metropolitana','LA FLORIDA','Part. Pagado'),
('26066','ESC. DE PARV. SEMILLITA MONTESSORI','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('26068','ESCUELA BAS. LICARITO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26070','CENTRO EDUC. REGULAR DE ADULTOS CEDEA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26071','ESCUELA DE PARVULOS Y ESP. DA VINCE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26073','ESC. DE PARV. COPITO DE NIEVE','Metropolitana','CERRILLOS','Part. Pagado'),
('26075','ESCUELA BAS. SAN JOSE DE PENALOLEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26076','ESCUELA DE PARVULOS OESTE','Metropolitana','CERRILLOS','Part. Subvencionado'),
('26077','COLEGIO DE ADULTOS SEMBRADOR SAN BENITO','Metropolitana','COLINA','Part. Subvencionado'),
('26079','ESCUELA DE PARV. HELLO CHILDREN','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('26080','COLEGIO SAINT ANDREW','Metropolitana','LAS CONDES','Part. Pagado'),
('26081','ESCUELA ESP. DICKENS COLLEGE','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('26082','ESCUELA DE PARVULOS HAMELIN','Metropolitana','ESTACIÓN CENTRAL','Part. Pagado'),
('26083','COLEGIO SAN ALBERTO HURTADO','Metropolitana','QUILICURA','Part. Subvencionado'),
('26084','COLEGIO EL BOSQUE DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('26087','COLEGIO DE ADULTOS HERNANDO DE MAGALLANES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26088','ESCUELA DE PARVULOS SANTA GEMITA DE GALGANI','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26089','ESCUELA DE PARVULOS NIDITOS','Metropolitana','LA FLORIDA','Part. Pagado'),
('26090','ESCUELA DE PARV. GIRASOL DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26091','ESC. ESPECIAL SEMILLITA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26092','COLEGIO PEUMAYEN','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26093','ESCUELA ESPECIAL TONKI TONKI TON','Metropolitana','EL MONTE','Part. Subvencionado'),
('26094','COLEGIO LAS AMERICAS DE PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('26097','ESCUELA ESP. ALDEBARAN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26098','ESCUELA ESPECIAL DANICALIN','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26099','ESCUELA DE PARV. MANZANITA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26100','ESCUELA ESP. EL RIEL','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('26101','ESCUELA ESP. INTEGRA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26102','ESCUELA DE PARV. LI-MARLIN','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26103','ESC. ESP. NUESTRA SEÑORA DE COVADONGA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26104','ESCUELA ESP. TERESIANA DEL ESFUERZO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26106','ESCUELA ESP. RUTH DE CONCHALI','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('26107','ESCUELA ESPECIAL BARCELONA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26108','ESC. BAS. Y ESP. SAN ANDRES DE PENAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26110','COLEGIO SANTIAGO - QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('26111','ESC. DE PARV. Y ESP. PUKARAY','Metropolitana','BUIN','Part. Subvencionado'),
('26112','COLEGIO DE AD. INSTITUTO SAN SEBASTIAN DE BEL','Metropolitana','PROVIDENCIA','Part. Pagado'),
('26113','ESCUELA ESP. RINCONADA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26114','ESCUELA ESP. LA VILLETE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26115','COLEGIO TUPAHUE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26116','ESCUELA ESP. SILABAS','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26117','ESCUELA BÁSICA N 149 SAN MARCEL','Metropolitana','BUIN','Part. Subvencionado'),
('26118','COLEGIO DE AD. BARTOLOME DE LAS CASAS DE MACU','Metropolitana','MACUL','Part. Subvencionado'),
('26121','ESCUELA ESP. CAMILA BINFA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26126','ESC. ESP. MI NUEVO ARLEQUIN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26128','ESC. DE PARV. Y ESP. KIMANTU DE PENAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26129','ESCUELA BAS. MARIA JESUS','Metropolitana','PROVIDENCIA','Part. Pagado'),
('26130','ESC. BAS. Y ESP. CHRIST SCHOOL DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('26134','COLEGIO QUIMAY','Metropolitana','LAS CONDES','Part. Pagado'),
('26135','ESC.BAS. EMPRENDER LARAPINTA','Metropolitana','LAMPA','Part. Subvencionado'),
('26137','COLEGIO DEL REAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26138','ESCUELA ESP. TRAGALUZ DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26139','ESCUELA BAS. VILLA SAN IGNACIO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('26140','ESCUELA ESP. ANDALUE','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26143','COLEGIO DE AD. ANTONIO ACEVEDO','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('26144','ESCUELA ESP. ANTIYAL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26147','ESCUELA ESPECIAL N° 2141 ALTA VIDA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26148','ESC. ESP. CENTRO DE RECURSOS SUYAY','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26150','COLEGIO  FITZROY COLLEGE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26151','ESCUELA ESP. ACTIVACION DE LA INTELIGENCIA SE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26152','ESCUELA BASICA SAN PEDRO APOSTOL DE PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('26155','ESCUELA BASICA N°2145 COLEGIO DUNALASTAIR PEÑALOLÉN','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('26157','LICEO MUNICIPAL BICENTENARIO DE BATUCO','Metropolitana','LAMPA','Municipal'),
('26158','ESCUELA BAS. AKORI','Metropolitana','CERRILLOS','Part. Subvencionado'),
('26159','ESCUELA ESP. ANTUKUYEN DE EL MONTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('26163','ESCUELA ESPECIAL NEWEN DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26164','COLEGIO SAN JOSE DE CERRILLOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('26165','ESCUELA DE PARV. MI MUNDO','Metropolitana','PUENTE ALTO','Part. Pagado'),
('26166','ESCUELA ESP. PALABRAS MAGICAS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26168','COLEGIO POLIVALENTE SAN PEDRO DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('26169','ESCUELA ESP. MI ISLITA','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('26171','ESCUELA BASICA N° 2150, COLEGIO MOUNIER','Metropolitana','LAS CONDES','Part. Pagado'),
('26172','ESCUELA BAS. FALCON COLLEGE LITTLE','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('26174','ESCUELA DE PARV. SANTA TERESITA DE JESUS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26180','ESCUELA DE PARV. LA CASITA ENCANTADA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26182','ESCUELA ESPECIAL TRIPANTU DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26183','ESCUELA DE PARV. BLANCA NIEVES DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26187','ESCUELA DE PARV. LOS PEQUES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26188','ESC. DE PARV. MY LITTLE GARDEN DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26189','ESCUELA DE PARV. BAM-BAM','Metropolitana','LA FLORIDA','Part. Pagado'),
('26191','ESCUELA DE PARV. PEQUEÑO ARCOIRIS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26195','ESCUEL DE PARV. LOS PIRINCHOS','Metropolitana','ESTACIÓN CENTRAL','Part. Pagado'),
('26197','ESCUELA DE PARV. LOS CARIÑOSITOS','Metropolitana','PAINE','Part. Subvencionado'),
('26200','ESCUELA DE PARV. PUDU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26201','COLEGIO DE AD. EDUCAP','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26202','ESCUELA ESP. MI MUNDO EN PALABRAS DE BUIN','Metropolitana','BUIN','Part. Subvencionado'),
('26206','ESCUELA DE PARVULOS N°2169 MY HOUSE','Metropolitana','COLINA','Part. Pagado'),
('26208','ESCUELA DE PARV. JARDIN INFANTIL MIRO','Metropolitana','LA FLORIDA','Part. Pagado'),
('26209','COLEGIO SAN JUAN DIEGO DE GUADALUPE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26211','ESCUELA DE PARVULOS N193 VALLE DEL SOL','Metropolitana','PUENTE ALTO','Part. Pagado'),
('26212','ESC. DE PARVULOS JARD. INFANTIL ARTISTICO VAL','Metropolitana','PUENTE ALTO','Part. Pagado'),
('26214','CENTRO DE EDUCACIÓN DE ADULTOS BERNARDO O´HIGGINS DE MAIPÚ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26216','ESCUELA DE PARV. MUSICAL GARFIELD','Metropolitana','RENCA','Part. Subvencionado'),
('26219','CENTRO EDUC. GOYENECHEA','Metropolitana','RENCA','Part. Subvencionado'),
('26221','ESCUELA DE PARV. TIO RICO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26222','ESCUELA ESP. SANTA MARIA DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26223','ESCUELA DE PARVULOS CAMILA BINFA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26224','ESCUELA ESP. CANTOS NUEVOS','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('26225','COLEGIO DE ADULTOS ROCKET','Metropolitana','MACUL','Part. Subvencionado'),
('26226','ESCUELA DE PARV. ARMONIA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26227','ESCUELA ESP. ARCA DE LOS NIÑOS','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('26228','ESCUELA BAS. ECHAURREN N° 2','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26230','ESCUELA ESP. SOL NACIENTE','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26231','ESCUELA ESP. ALEGRIA DE NIÑOS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26235','ESCUELA BASICA PARTICULAR PAICAVI DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26236','ESCUELA ESP. DIVERSIDAD','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26237','ESCUELA ESPECIAL AGORA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('26238','COLEGIO DEL VERBO DIVINO DE CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('26239','ESCUELA DE PARV. Y ESP. AMANECER DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26240','ESCUELA ESPECIAL SEMILLITAS DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26241','ESCUELA ESP. SAN CLEMENTE DE HUECHURABA','Metropolitana','HUECHURABA','Part. Subvencionado'),
('26242','ESCUELA ESP. CANTARES','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('26243','ESCUELA ESP. SAN CARLOS DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26244','ESCUELA BAS. SAN ESTEBAN DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26245','ESCUELA BAS. CRISTIANO EL SEMBRADOR','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('26246','ESCUELA ESP. PROFESORA ELSA BENITEZ','Metropolitana','RENCA','Part. Subvencionado'),
('26249','ESCUELA BASICA MIRAFLORES DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26250','ESCUELA BAS. MISIONERO DE AGOSTINI','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26252','ESCUELA ESP. SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26254','COLEGIO SANTA MARIA GORETTI DE PADRE HUR','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26255','ESCUELA ESP. CLEMENTE DE JESUS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26256','ESCUELA ESP. PLAZUELA ENCANTADA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26257','ESCUELA ESP. FLORECER','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26258','ESCUELA DE PARV. HEIDI DE LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('26259','ESCUELA ESP. ANTOBEL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26260','LINCOLN COLLEGE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('26261','ESCUELA ESP. SANTA CATALINA DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('26262','CENTRO EDUC. ESPECIAL HANS ASPERGER','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26263','ESCUELA ESP. EL PALACIO DE LOS NIÑOS DE SAN B','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26264','ESCUELA ESP. SEMILLITA DE RECOLETA','Metropolitana','RECOLETA','Part. Subvencionado'),
('26267','ESCUELA ESP. RUCA RAYEN','Metropolitana','LA REINA','Part. Subvencionado'),
('26268','COLEGIO SAINT LOUIS SCHOOL','Metropolitana','MAIPÚ','Part. Pagado'),
('26269','COLEGIO ALTO DEL VALLE','Metropolitana','BUIN','Part. Subvencionado'),
('26270','ESCUELA ESP. ARCOIRIS DE BUIN','Metropolitana','BUIN','Part. Subvencionado'),
('26271','ESCUELA BAS. VALLE VERDE','Metropolitana','COLINA','Part. Subvencionado'),
('26272','COLEGIO WESTON ACADEMY','Metropolitana','QUILICURA','Part. Pagado'),
('26273','ESCUELA ESP. MONTE CARMELO DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26274','ESCUELA BAS. REINA NORTE','Metropolitana','COLINA','Part. Subvencionado'),
('26275','ESCUELA ESPECIAL KITARI','Metropolitana','LAMPA','Part. Subvencionado'),
('26276','ESCUELA ESP. NIÑO JESUS DE SAN JOAQUIN','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('26278','ESCUELA BASICA ARISTA VITAE','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26280','ESCUELA DE PARV. SEVILLA','Metropolitana','MAIPÚ','Part. Pagado'),
('26281','ESCUELA ESPECIAL EL TREBOL','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26286','COLEGIO DE ADULTOS ANTU-ANAY','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26289','ESCUELA ESP. DESPERTARES DE PEDRO AGUIRRE CER','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('26292','LICEO POLIVALENTE MUNICIPAL DE LA FLORIDA','Metropolitana','LA FLORIDA','Municipal'),
('26293','ESCUELA BAS. INTEGRAL ENLACES DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26297','COLEGIO MONTAHUE','Metropolitana','HUECHURABA','Part. Pagado'),
('26298','ESCUELA LA ARAUCARIA DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26299','ESCUELA ESP. EPUMALEN','Metropolitana','RECOLETA','Part. Subvencionado'),
('26303','COLEGIO ENRIQUE ALVEAR DE CERRO NAVIA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('26304','ESCUELA BAS. PEÑIHUEN ANDINO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26305','COLEGIO MONTAHUE DE PEÑALOLEN','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('26306','ESC. ESP. DE COLORES PANDO','Metropolitana','MACUL','Part. Subvencionado'),
('26309','ESCUELA ESPECIAL  MAGOS','Metropolitana','RECOLETA','Part. Subvencionado'),
('26310','ESCUELA DE PARVULOS PASITOS DE QUILICURA','Metropolitana','QUILICURA','Part. Pagado'),
('26311','COLEGIO LINCOLN INTERN ACADEMY VALLE NORTE CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('26316','ESCUELA ESP. ALTUE DE CERRO NAVIA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('26317','ESCUELA  ESPECIAL  DE  LENGUAJE N° 2235,  ANTÚ KÚYEN','Metropolitana','CERRILLOS','Part. Subvencionado'),
('26318','ESCUELA ESPECIAL SANTA RITA DE CASIA DE LA GR','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26320','ESC. ESP. CORAZON DE JESUS DE SAN BERNARDO','Metropolitana','TALAGANTE','Part. Subvencionado'),
('26321','ESC. DE PARV. JARDIN INFANTIL GIRASOL DE SAN','Metropolitana','SAN BERNARDO','Part. Pagado'),
('26322','ESCUELA DE PARVULOS Y ESPECIAL N°2237 SAN BENITO EDUCA','Metropolitana','MAIPÚ','Part. Pagado'),
('26323','THE ALMOND SCHOOL III','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26324','EST. EDUC. PART. ARCANGEL GABRIEL N° 2','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('26327','ESC. ESP. ANTILAF DE PEÑAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26328','COLEGIO ANTUQUENU ANDINO','Metropolitana','LA FLORIDA','Part. Pagado'),
('26330','ESC. ESP. PEUMAYEN DE MAIPU N°2','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26333','C. INTEGRAL DE AD. PROFESORA TERESA MOYA REYE','Metropolitana','PUENTE ALTO','Municipal'),
('26334','ESC. ESP. EL CANELO DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26335','COLEGIO DUNALASTAIR VALLE NORTE','Metropolitana','COLINA','Part. Pagado'),
('26337','ESCUELA ESPECIAL ADAES','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26338','ESC. DE PARV. CASPER','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26340','ESC. PARV. ADRIANNA BERZINS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26341','ESC. BAS. NUEVA ESPERANZA DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26342','ESC. DE PARV. LOS DUENDECITOS DE LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26344','ESCUELA DE PARVULOS Y ESPECIAL CRISOL DE EL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26345','ESC. BAS. EJERCITO DE SALVACION DE SANTIAGO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('26347','ESC. ESP. SANTA GEMA GALGANI','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26348','ESCUELA DE PARVULOS N 2251 ANDALUE DE SAN J','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('26349','ESC ESP. CENTROS DE RETOS MULTIPLES LUZ Y ESP','Metropolitana','BUIN','Part. Subvencionado'),
('26350','ESCUELA ESP. SAN MARTIN DE PORRES','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('26351','ESCUELA ESPECIAL N°2253 ANTULAF','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26352','ESC. PROFESOR FELIX ALVAREZ','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('26353','ESC. DE PARVULOS SOL Y LUNA DE LA REINA','Metropolitana','LA REINA','Part. Subvencionado'),
('26354','ESCUELA ESP. ALTAZOR DE ESTACION CENTRAL','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('26355','ESCUELA DE LENGUAJE MILLARAHUE','Metropolitana','HUECHURABA','Part. Subvencionado'),
('26356','ESCUELA ESPECIAL N° 2258 NIÑO JESUS DE LA GR','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26357','ESCUELA ESPECIAL UN MUNDO DE PALABRAS','Metropolitana','QUILICURA','Part. Subvencionado'),
('26358','ESCUELA ESPECIAL CREA','Metropolitana','EL MONTE','Part. Subvencionado'),
('26359','ESCUELA ESPECIAL GABRIELA RUBIO','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26360','ESC. PARV. UN RINCON DE ALEGRIA','Metropolitana','RENCA','Part. Subvencionado'),
('26361','ESC. ESP. EL PRINCIPITO DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26362','COLEGIO SAN FRANCISCO DE ASIS DE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26364','ESCUELA ESPECIAL N°165 MONTESOL','Metropolitana','BUIN','Part. Subvencionado'),
('26365','COLEGIO BICENTENARIO SAN ALBERTO HURTADO DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('26367','LINCOLN COLLEGE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26368','COLEGIO SAN FRANCISCO DE SALES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26370','ESC. ESP. SAN ANTONIO DE LO PRADO','Metropolitana','LO PRADO','Part. Subvencionado'),
('26371','COLEGIO DE ADULTOS LOS LIBERTADORES DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26372','COLEGIO SAN LUCAS DE LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('26373','ESCUELA DE PARVULOS Y ESPECIAL SANTA TERESA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26378','ESCUELA PATRONA DE LOURDES','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26379','COLEGIO SOL DEL VALLE','Metropolitana','LAMPA','Part. Subvencionado'),
('26381','COLEGIO NUEVA ERA SIGLO XXI SEDE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26383','COLEGIO INSTITUTO CALERA DE TANGO','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('26384','COLEGIO TEC. PROF. SAN RAMON LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26386','ESCUELA ESP. ANDELEN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26388','ESCUELA ESP. SAN CRISTOBAL DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26390','ESC. PARV.JARDIN INFANTIL COLONIAL DE LOS HAL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26391','ESCUELA BASICA NAMUNCURA','Metropolitana','RENCA','Part. Subvencionado'),
('26392','ESC. ALTAS CUMBRES DEL ROSAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26393','ESCUELA DE PARVULOS EL CANELO DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26395','ESCUELA DE PARVULOS Y ESPECIAL SAN FRANCISCO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26396','ESCUELA ESPECIAL 2274 MATER','Metropolitana','QUILICURA','Part. Subvencionado'),
('26397','ESCUELA ESP. DE LENGUAJE CARAMELO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26398','ESCUELA DE PARVULOS BURBUJITAS','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('26399','COLEGIO PUMAHUE CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('26403','INSTITUTO SEMBRADOR DE PEÑAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26404','CENTRO EDUC DE AD STA TERESITA DE PADRE HURTA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26405','COLEGIO HERMANOS CARRERA DE CHILE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26406','ESCUELA ESPECIAL N° 2278 NUESTRAS HUELLAS','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('26407','ESCUELA ESP SANTA INES DE LA PAZ','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26408','ESC.ESPECIAL Nº 2279 SAN EXPEDITO DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26409','ESCUELA ESPECIAL PEQUE SOL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26410','ESCUELA ESPECIAL VIVAN LOS NIÑOS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('26411','COLEGIO NOVA TERRA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26412','ESCUELA DE PARVULOS FANTASIAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26414','ESCUELA ESPECIAL Nº 168 NAJU','Metropolitana','BUIN','Part. Subvencionado'),
('26415','ESCUELA ESPECIAL CONGUILLIO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26416','COLEGIO PREMILITAR CAPITAN IGNACIO CARRERA PINTO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26417','ESCUELA DE PARVULOS N°160 MANITOS TRAVIESAS','Metropolitana','PEÑAFLOR','Part. Pagado'),
('26418','ESCUELA DE PARVULOS N°2282 SANTA MARIA DE VITACURA','Metropolitana','VITACURA','Part. Pagado'),
('26419','ESCUELA ESPECIAL DE LENGUAJE MALEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26420','ESCUELA ESPECIAL Nº 2284 LOS ANGELITOS FELICE','Metropolitana','RECOLETA','Part. Subvencionado'),
('26421','ESCUELA DE PARVULOS EL ARCA DE NOE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26424','ESCUELA BASICA Nº 2286 LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('26426','COLEGIO ESPECIAL HOSPITALARIO CON TODO EL COR','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('26428','ESCUELA BASICA N°213 SCUOLA IMPERIALE','Metropolitana','PUENTE ALTO','Part. Pagado'),
('26429','ESC DE PARVULOS MI RINCON MAGICO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26432','ESCUELA ESPECIAL MI MUNDO EN PALABRAS','Metropolitana','LAMPA','Part. Subvencionado'),
('26434','COLEGIO ALVARO LAVÍN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26435','ESCUELA ESP SANTA MARCELA CRECER','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26436','COLEGIO TERRAUSTRAL DEL SOL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26438','ESC ESP SAN GABRIEL DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26439','ESCUELA ESPECIAL NIDO DE PALABRAS','Metropolitana','LAS CONDES','Part. Subvencionado'),
('26441','ESCUELA ESPECIAL JESUS ANGEL GAZO','Metropolitana','RENCA','Part. Subvencionado'),
('26442','ESC ESP STA MARTA DE PADRE HURTADO','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26443','ESCUELA ESPECIAL RENACER','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26445','ESCUELA ESPECIAL VENTANAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26446','ESCUELA DE LENGUAJE AMERICA II','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26447','ESCUELA ESPECIAL SANTA BARBARA DE PEÑAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('26448','ESCUELA ESPECIAL ELUNEY','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('26449','ESCUELA DE LENGUAJE MIS TRES ANGELITOS','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26450','ESCUELA ESPECIAL PARAISO','Metropolitana','LAMPA','Part. Subvencionado'),
('26451','ESCUELA ESPECIAL FLORES DE BOLLENAR','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26452','ESCUELA ESPECIAL ANTU-MAWEN','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('26453','TIEMPO DE CRECER','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26454','COLEGIO SANTIAGO EMPRENDEDORES','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26455','ESCUELA ESPECIAL SAN LUCAS DEL PAICO','Metropolitana','EL MONTE','Part. Subvencionado'),
('26456','ESCUELA ESPECIAL SANTA AMELIA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26457','ESCUELA ESPECIAL MI MUNDO EN PALABRAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26459','ESCUELA ESPECIAL ANCHIMALLEN','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26460','ESCUELA BASICA JOSE MARIA DE LA CRUZ','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('26462','EL ARCA DE LOS NIÑOS LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('26463','COLEGIO SCHULHAUS MONTESSORI','Metropolitana','ISLA DE MAIPO','Part. Pagado'),
('26464','ESCUELA DE LENGUAJE AMERICA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26465','COLEGIO INSTITUTO RAMÓN FREIRE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26466','ESCUELA BASICA ELIODORO MATTE OSSA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('26469','ESCUELA ESPECIAL EL ARCA DE LOS NIÑOS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26471','ESCUELA ESPECIAL AGUSTINA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('26472','ESCUELA ESPECIAL DE LENGUAJE ANTU','Metropolitana','TALAGANTE','Part. Subvencionado'),
('26474','ESCUEL ESPECIAL BAMBÚ','Metropolitana','LAMPA','Part. Subvencionado'),
('26476','COLEGIO LINCOLN COLLEGE HUECHURABA','Metropolitana','HUECHURABA','Part. Pagado'),
('26477','ESCUELA ESPECIAL MILLARAY','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26478','ESCUELA ESPECIAL DE LENGUAJE EXPLORA PORVENIR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26479','ESCUELA ESPECIAL DE LENGUAJE EXPLORA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26480','ESCUELA DE LENGUAJE LUZ DE ESPERANZA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('26481','ESCUELA ESPECIAL LA MORENITA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26482','COLEGIO INGLES SAN JOSE DE LINDEROS','Metropolitana','BUIN','Part. Pagado'),
('26483','ESCUELA ESPECIAL DE LENGUAJE LOS CLARINES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26484','ESCUELA ESPECIAL EL PASTORCITO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('26485','ESCUELA ESPECIAL N 200 CARAMELO II','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26487','ESCUELA ESPECIAL PIRQUE','Metropolitana','PIRQUE','Part. Subvencionado'),
('26490','ESCUELA ESPECIAL DE LENGUAJE EL LUCERO','Metropolitana','QUILICURA','Part. Subvencionado'),
('26491','ESCUELA DE PARVULOS GUSANITO Nº2','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26493','ESCUELA DE LENGUAJE GUSANITO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26494','ESCUELA BASICA SAN JAVIER DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('26495','ESCUELA ESPECIAL NUEVA ESPERANZA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26496','ESCUELA ESPECIAL AMIGOS DEL BOSQUE','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('26497','ESCUELA ESPECIAL MIS ANGELITOS','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('26498','ESCUELA ESPECIAL ENITEO CREACIONES','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('26500','ESCUELA ESPECIAL DE LENGUAJE SAN GABRIEL','Metropolitana','CERRILLOS','Part. Subvencionado'),
('26501','LICEO TECNICO PROFESIONAL PATRICIO AYLWIN AZOCAR','Metropolitana','LA GRANJA','Servicio Local'),
('26502','ESCUELA DE PARVULOS KIDS PLACE','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('26503','COLEGIO SAINT LOUIS SCHOOL','Metropolitana','TILTIL','Part. Subvencionado'),
('26507','COLEGIO SAN FRANCISCO DE PAINE','Metropolitana','PAINE','Part. Pagado'),
('26509','ESCUELA ESPECIAL MANDARINA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26512','ESCUELA ESPECIAL GRIBEL DE LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26513','ESCUELA ESPECIAL DE LENGUAJE LILIPUT','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26514','ESCUELA ESPECIAL DE LENGUAJE BOY HAPPY','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('26516','ESCUELA BASICA N°2327 CONDORES','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('26517','ESCUELA ESPECIAL NUEVO MUNDO PAC','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('26518','ESCUELA ALTO MAWIDA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26519','LICEO VESPERTINO DE ADULTOS FUTURO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('26520','ESC. ESP. JERUSALEN DE QUINTA NORMAL','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('26521','ESCUELA ESPECIAL MAGOS DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('26522','ESC. ESPECIAL STA. MARGARITA DE PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('26523','ESC. ESP. MAGICAS PALABRAS','Metropolitana','RENCA','Part. Subvencionado'),
('26524','COLEGIO ANTIMANQUE','Metropolitana','PEÑAFLOR','Part. Pagado'),
('26526','ESCUELA ESPECIAL TERESITA DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('26527','ESCUELA ESPECIAL SAGRADA FAMILIA','Metropolitana','LAMPA','Part. Subvencionado'),
('26529','ESCUELA ESPECIAL ALTIOR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26530','ESCUELA ESPECIAL ESPERANZA NUEVA','Metropolitana','COLINA','Part. Subvencionado'),
('26531','COLEGIO DE ADULTOS ESCUELA DEL CARIÑO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('26532','COLEGIO LO  BOZA ROSALBA LAGOS MONACO','Metropolitana','RENCA','Part. Subvencionado'),
('26533','ESCUELA ESPECIAL ARBOLIRIS','Metropolitana','PAINE','Part. Subvencionado'),
('26534','ESCUELA DE LENGUAJE LA GRANJITA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('26535','ESCUELA ESPECIAL N° 2338 SONSOLES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26536','ESCUELA ESPECIAL Nº 2339 ATRAVIA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('26538','COLEGIO TERRAUSTRAL OESTE S.A','Metropolitana','MAIPÚ','Part. Subvencionado'),
('26541','ESCUELA ESPECIAL Nº 206 COLORES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26543','ESCUELA ESPECIAL MUNDO INFANTIL RUTA SUR','Metropolitana','PAINE','Part. Subvencionado'),
('26544','ESCUELA ESPECIAL COSAS DE NINOS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('30001','THE INTERNATIONAL SCHOOL ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30002','COLEGIO EL ROBLE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30003','COLEGIO JUAN PABLO II','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30004','ESCUELA ESPECIAL DE LENGUAJE ARCO IRIS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30005','COLEGIO MARIA MONTESSORI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30006','COLEGIO HISPANO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30007','ESC. ESP. LENG. LA GRANJITA SCHOOL','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30010','ESCUELA ESPECIAL DE LENGUAJE LUCERITO MUSIKAL','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30012','COLEGIO AMARU ANKU SCHOOL','Arica y Parinacota','ARICA','Part. Subvencionado'),
('30013','THE AZAPA VALLEY SCHOOL','Arica y Parinacota','ARICA','Part. Pagado'),
('31001','ESCUELA EL AROMO','Los Ríos','PAILLACO','Part. Subvencionado'),
('31002','LICEO MATER POPULI DEI','Los Ríos','MARIQUINA','Part. Subvencionado'),
('31003','ESC. ESP. TRANS. DE LENG SAN MIGUEL','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31005','COL. EDUC VICTOR MANUEL GIOVANETTI ASTUDILLO','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('31006','COLEGIO LAS GAVIOTAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31008','ESCUELA DE LENGUAJE PEQUEÑAS VOCES','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31009','ESCUELA DE LENGUAJE ALONQUEO','Los Ríos','LANCO','Part. Subvencionado'),
('31010','LICEO BICENTENARIO CIUDAD DE LOS RIOS VALDIVI','Los Ríos','VALDIVIA','Servicio Local'),
('31012','INSTITUTO BICENTENARIO DE EXCELENCIA CHILE ASIA PACIFICO','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31013','ESCUELA DE LENGUAJE LAS LETRAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31015','ESCUELA DE LENGUAJE ALTUE','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('31016','COLEGIO ECOLOGICO SAN FELIPE','Los Ríos','VALDIVIA','Part. Subvencionado'),
('31017','ESCUELA PARTICULAR RURAL JUAN PABLO SEGUNDO','Los Ríos','LANCO','Part. Subvencionado'),
('31018','JARDIN INFANTIL BLANCANIEVES II','Los Ríos','VALDIVIA','Part. Pagado'),
('31019','ESCUELA BASICA Y DE LENGUAJE GLORIA SKILLMANN','Los Ríos','LANCO','Part. Subvencionado'),
('31021','COLEGIO JUAN PABLO SEGUNDO','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('31022','ESCUELA ESPECIAL TRANSTORNOS DE LENGUAJE TRAI TRAI LAFQUEN','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('31029','ESCUELA ESPECIAL CAPULLITO DE SOL DE ISLA DE','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('31030','ESCUELA PRE MILITAR HEROES DE LA CONCEPCION','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('31032','ESCUELA ESPECIAL JESUS DE PRAGA','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('31033','ESCUELA ESPECIAL ANTAY','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('31034','COLEGIO HUGO LANDAURO HENRIQUEZ','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31035','ESCUELA ESPECIAL ENCANTA PALABRAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31036','ESC. PARV.Y ESP MUNDOPALABRA DE BUIN','Metropolitana','BUIN','Part. Subvencionado'),
('31037','LICEO INSTITUTO CUMBRE DE CONDORES','Metropolitana','RENCA','Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
