-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 7 de 31 | filas 2401-2800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('3739','LICEO BICENTENARIO DE EXCELENCIA AGRÍCOLA DE CHILLÁN - CATO','Ñuble','CHILLÁN','Adm. Delegada'),
('3740','ESCUELA GENERAL DOMINGO URRUTIA','Ñuble','SAN CARLOS','Servicio Local'),
('3741','CENTRO EDUCACIÓN INTEGRAL ADULTOS CLAUDIO MATTE PÉREZ','Ñuble','SAN CARLOS','Servicio Local'),
('3742','LICEO POLITECNICO CAP. IGNACIO CARRERA P','Ñuble','SAN CARLOS','Servicio Local'),
('3743','LICEO BICENTENARIO DE EXCELENCIA DIEGO PORTALES PALAZUELOS','Ñuble','SAN CARLOS','Servicio Local'),
('3744','ESCUELA GENERAL JOSÉ MIGUEL CARRERA VERDUGO','Ñuble','SAN CARLOS','Servicio Local'),
('3745','ESCUELA GENERAL SOFANOR PARRA HERMOSILLA','Ñuble','SAN CARLOS','Servicio Local'),
('3747','ESCUELA FRANCISCO MOYA CLEMENT','Ñuble','SAN CARLOS','Servicio Local'),
('3748','ESCUELA ESPECIAL RENACER','Ñuble','SAN CARLOS','Servicio Local'),
('3749','ESCUELA JOAQUIN DEL PINO ROZAS Y NEGRETE','Ñuble','SAN CARLOS','Servicio Local'),
('3754','ESCUELA BULI','Ñuble','SAN CARLOS','Servicio Local'),
('3755','ESCUELA NINQUIHUE','Ñuble','SAN CARLOS','Servicio Local'),
('3757','ESCUELA AGUA BUENA','Ñuble','SAN CARLOS','Servicio Local'),
('3758','ESCUELA EL CARBON','Ñuble','SAN CARLOS','Servicio Local'),
('3759','ESCUELA CACHAPOAL','Ñuble','SAN CARLOS','Servicio Local'),
('3760','ESCUELA RIBERA DE NUBLE','Ñuble','SAN CARLOS','Servicio Local'),
('3762','ESCUELA MONTE BLANCO','Ñuble','SAN CARLOS','Servicio Local'),
('3766','ESCUELA QUINQUEHUA','Ñuble','SAN CARLOS','Servicio Local'),
('3768','ESCUELA LAS ARBOLEDAS','Ñuble','SAN CARLOS','Servicio Local'),
('3776','ESCUELA QUILELTO','Ñuble','SAN CARLOS','Servicio Local'),
('3781','ESCUELA MILLAUQUEN','Ñuble','SAN CARLOS','Servicio Local'),
('3782','ESCUELA MANUEL ANTONIO CASTILLO VELASCO','Ñuble','SAN CARLOS','Servicio Local'),
('3783','ESCUELAS LAS JUNTAS','Ñuble','SAN CARLOS','Servicio Local'),
('3784','ESCUELA JUNQUILLO','Ñuble','SAN CARLOS','Servicio Local'),
('3785','ESCUELA TRES ESQUINAS','Ñuble','SAN CARLOS','Servicio Local'),
('3786','ESCUELA EL SAUCE','Ñuble','SAN CARLOS','Servicio Local'),
('3791','ESCUELA EL TORREON','Ñuble','SAN CARLOS','Servicio Local'),
('3795','INSTITUTO SANTA MARIA DE SAN CARLOS','Ñuble','SAN CARLOS','Part. Subvencionado'),
('3796','LICEO BICENTENARIO POLIVALENTE NUESTRA SEÑORA DE LA MERCED','Ñuble','SAN CARLOS','Part. Subvencionado'),
('3797','COLEGIO SAGRADO CORAZON DE JESUS','Ñuble','SAN CARLOS','Part. Subvencionado'),
('3798','ESCUELA SAN JORGE DE NIQUEN','Ñuble','ÑIQUÉN','Servicio Local'),
('3799','ESCUELA CHACAY','Ñuble','ÑIQUÉN','Servicio Local'),
('3800','LICEO TIUQUILEMU','Ñuble','ÑIQUÉN','Servicio Local'),
('3801','ESCUELA NIQUEN','Ñuble','ÑIQUÉN','Servicio Local'),
('3802','LICEO SAN GREGORIO','Ñuble','ÑIQUÉN','Servicio Local'),
('3804','ESCUELA ZEMITA','Ñuble','ÑIQUÉN','Servicio Local'),
('3807','ESCUELA BELEN','Ñuble','ÑIQUÉN','Servicio Local'),
('3808','ESCUELA LA GLORIA','Ñuble','ÑIQUÉN','Servicio Local'),
('3814','ESCUELA LAS ROSAS','Ñuble','ÑIQUÉN','Servicio Local'),
('3815','ESCUELA PUERTAS DE VIRGUIN','Ñuble','ÑIQUÉN','Servicio Local'),
('3818','ESCUELA COLVINDO','Ñuble','ÑIQUÉN','Servicio Local'),
('3820','ESCUELA BULI-CASERIO','Ñuble','ÑIQUÉN','Servicio Local'),
('3823','LICEO BICENTENARIO POLIVALENTE JORGE ALESSANDRI RODRIGUEZ','Ñuble','SAN FABIÁN','Servicio Local'),
('3828','ESCUELA BASICA LOS COIGUES','Ñuble','SAN FABIÁN','Servicio Local'),
('3829','ESCUELA BÁSICA JOSÉ ANDRES LEIVA LEIVA','Ñuble','SAN FABIÁN','Servicio Local'),
('3831','ESCUELA BASICA PASO ANCHO','Ñuble','SAN FABIÁN','Servicio Local'),
('3832','ESCUELA BASICA FABIAN DE LA FUENTE','Ñuble','SAN FABIÁN','Servicio Local'),
('3833','ESCUELA BASICA TRABUNCURA','Ñuble','SAN FABIÁN','Servicio Local'),
('3835','ESCUELA BRITANICA GUILLERMINA DRAKE WOOD','Ñuble','COIHUECO','Servicio Local'),
('3836','ESCUELA DOMITILA URREJOLA MENCHACA','Ñuble','COIHUECO','Servicio Local'),
('3837','ESCUELA ENRIQUE GRAF REYES','Ñuble','COIHUECO','Servicio Local'),
('3838','ESCUELA BASICA TANILVORO','Ñuble','COIHUECO','Servicio Local'),
('3839','ESCUELA TALQUIPEN','Ñuble','COIHUECO','Servicio Local'),
('3840','ESCUELA BASICA NIBLINTO','Ñuble','COIHUECO','Servicio Local'),
('3841','ESCUELA GUARDIA MARINA ERNESTO RIQUELME','Ñuble','COIHUECO','Servicio Local'),
('3842','ESCUELA HEROES DE IQUIQUE','Ñuble','COIHUECO','Servicio Local'),
('3843','ESCUELA PORVENIR DE CATO','Ñuble','COIHUECO','Servicio Local'),
('3845','ESCUELA MANUEL MONTT','Ñuble','COIHUECO','Servicio Local'),
('3846','ESCUELA BÁSICA EMBALSE COIHUECO','Ñuble','COIHUECO','Servicio Local'),
('3849','ESCUELA CAMILO HENRIQUEZ','Ñuble','CHILLÁN','Corp. Municipal'),
('3850','ESCUELA JUAN JOSE SAN MARTIN','Ñuble','COIHUECO','Servicio Local'),
('3851','ESCUELA HERNÁN MERINO CORREA','Ñuble','COIHUECO','Servicio Local'),
('3852','ESCUELA ANIBAL PINTO','Ñuble','COIHUECO','Servicio Local'),
('3853','ESCUELA JULIO MONTT SALAMANCA','Ñuble','COIHUECO','Servicio Local'),
('3854','ESCUELA CANCHA RAYADA','Ñuble','COIHUECO','Servicio Local'),
('3855','ESCUELA GENERAL PEDRO LAGOS MARCHANT','Ñuble','COIHUECO','Servicio Local'),
('3856','ESCUELA MANUEL MATUS HERMOSILLA','Ñuble','COIHUECO','Servicio Local'),
('3857','ESCUELA BENJAMIN VICUNA MACKENNA','Ñuble','COIHUECO','Servicio Local'),
('3859','ESCUELA SAN ANTONIO DE FRUTILLARES','Ñuble','COIHUECO','Servicio Local'),
('3862','ESCUELA JUAN DE DIOS ALDEA','Ñuble','COIHUECO','Servicio Local'),
('3865','COLEGIO ADVENTISTA DE CHILE','Ñuble','CHILLÁN','Part. Subvencionado'),
('3866','ESCUELA PARTICULAR LAS MARIPOSAS','Ñuble','CHILLÁN','Part. Subvencionado'),
('3867','ESCUELA PARTIC.LOS ALTOS DE MIRAFLORES','Ñuble','COIHUECO','Part. Subvencionado'),
('3869','ESCUELA AGROECOLÓGICAS LAS ISLAS','Ñuble','COIHUECO','Part. Subvencionado'),
('3870','ESCUELA PARTICULAR AMANECER','Ñuble','COIHUECO','Part. Subvencionado'),
('3871','LICEO BICENTENARIO POLITÉCNICO JOSÉ MANUEL PINTO ARIAS','Ñuble','PINTO','Servicio Local'),
('3872','ESCUELA JOSE TOHA SOLDEVILLA','Ñuble','PINTO','Servicio Local'),
('3874','ESCUELA JAVIER JARPA SOTOMAYOR','Ñuble','PINTO','Servicio Local'),
('3876','ESCUELA HECTOR MANUEL ARIAS CORTES','Ñuble','PINTO','Servicio Local'),
('3877','ESCUELA SANTA EDUVIGES','Ñuble','PINTO','Servicio Local'),
('3882','ESCUELA NIDO DE GOLONDRINAS','Ñuble','PINTO','Servicio Local'),
('3883','ESCUELA BASICA JUAN JORGE','Ñuble','PINTO','Servicio Local'),
('3884','ESCUELA SAN ALFONSO','Ñuble','PINTO','Servicio Local'),
('3885','COLEGIO FRANCISCO DE ASIS','Ñuble','PINTO','Part. Subvencionado'),
('3886','LICEO BICENTENARIO MANUEL JESUS ORTIZ','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3887','LICEO BICENTENARIO DE EXCELENCIA PUEBLO SECO','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3888','COLEGIO BICENTENARIO DE EXCELENCIA POLITECNICO VICTOR JARA','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3890','ESCUELA MARÍA LUISA ESPINOZA RUIZ','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3891','ESCUELA LAS QUILAS','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3894','ESCUELA SANTA MARIA','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3897','ESCUELA CALLE ALEGRE','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3898','ESCUELA SANTA JUANA','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3899','ESCUELA COLTON VARIANTE','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3900','ESCUELA JOSÉ HUMBERTO BARRERA BARRERA','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3903','ESCUELA MAYULERMO','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3904','ESCUELA LOURDES','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3906','ESCUELA SELVA NEGRA','Ñuble','SAN IGNACIO','Corp. Municipal'),
('3907','COLEGIO BICENTENARIO MARY WARD','Ñuble','SAN IGNACIO','Part. Subvencionado'),
('3909','LICEO BICENTENARIO DE EXCELENCIA POLIVALENTE JUVENAL HERNÁNDEZ JAQUE','Ñuble','EL CARMEN','Corp. Municipal'),
('3910','ESCUELA VIRGEN DEL CARMEN','Ñuble','EL CARMEN','Corp. Municipal'),
('3912','ESCUELA DEL CARMEN SAN MARTÍN OTÁROLA','Ñuble','EL CARMEN','Corp. Municipal'),
('3913','ESCUELA NAVIDAD-TREHUALEMU','Ñuble','EL CARMEN','Corp. Municipal'),
('3914','ESCUELA BERNARDINO MUNOZ GONZALEZ','Ñuble','EL CARMEN','Corp. Municipal'),
('3916','ESCUELA CAPILLA NORTE','Ñuble','EL CARMEN','Corp. Municipal'),
('3917','ESCUELA VALLE DE ATACALCO','Ñuble','EL CARMEN','Corp. Municipal'),
('3918','ESCUELA LUIS TEODORO ORTEGA OYARCE','Ñuble','EL CARMEN','Corp. Municipal'),
('3920','ESCUELA SAN RICAEL','Ñuble','EL CARMEN','Corp. Municipal'),
('3921','ESCUELA LAS HORMIGAS','Ñuble','EL CARMEN','Corp. Municipal'),
('3922','ESCUELA MATA REDONDA','Ñuble','EL CARMEN','Corp. Municipal'),
('3924','ESCUELA VERGARA','Ñuble','EL CARMEN','Corp. Municipal'),
('3926','ESCUELA SAN JOSE SUR','Ñuble','EL CARMEN','Corp. Municipal'),
('3927','ESCUELA CHAMIZAL','Ñuble','EL CARMEN','Corp. Municipal'),
('3932','ESCUELA MAIPO','Ñuble','EL CARMEN','Corp. Municipal'),
('3934','ESCUELA SAN ISIDRO','Ñuble','EL CARMEN','Corp. Municipal'),
('3935','ESCUELA DE SAN VICENTE ALTO','Ñuble','EL CARMEN','Corp. Municipal'),
('3937','ESCUELA BALSA ZAPALLAR','Ñuble','EL CARMEN','Corp. Municipal'),
('3938','ESCUELA BÁSICA ADULTOS YUNGAY','Ñuble','YUNGAY','Corp. Municipal'),
('3940','LICEO DE YUNGAY','Ñuble','YUNGAY','Corp. Municipal'),
('3941','LICEO CAMPANARIO','Ñuble','YUNGAY','Corp. Municipal'),
('3944','ESCUELA EL AVELLANO','Ñuble','YUNGAY','Corp. Municipal'),
('3945','ESCUELA LOS PUQUIOS','Ñuble','YUNGAY','Corp. Municipal'),
('3947','ESCUELA PANGAL DEL LAJA','Ñuble','YUNGAY','Corp. Municipal'),
('3948','ESCUELA SAN MIGUEL DE ITATA','Ñuble','YUNGAY','Corp. Municipal'),
('3949','ESCUELA EL ROBLE','Ñuble','YUNGAY','Corp. Municipal'),
('3952','ESCUELA SANTA IRMA','Ñuble','YUNGAY','Corp. Municipal'),
('3955','ESCUELA BASICA RANCHILLOS','Ñuble','YUNGAY','Corp. Municipal'),
('3957','ESCUELA LOS MAYOS','Ñuble','YUNGAY','Corp. Municipal'),
('3958','ESCUELA LOS LAURELES','Ñuble','YUNGAY','Corp. Municipal'),
('3959','ESCUELA PALLAHUALA','Ñuble','YUNGAY','Corp. Municipal'),
('3960','COLEGIO DIVINA PASTORA','Ñuble','YUNGAY','Part. Subvencionado'),
('3961','LICEO POLIVALENTE TOMÁS ARNALDO HERRERA VEGA','Ñuble','PEMUCO','Corp. Municipal'),
('3962','ESCUELA BASICA EL CIPRES','Ñuble','PEMUCO','Corp. Municipal'),
('3964','ESCUELA JOSE FRANCISCO ZAPATA DOMINGUEZ','Ñuble','PEMUCO','Corp. Municipal'),
('3965','ESCUELA BASICA SANTA JULIA','Ñuble','PEMUCO','Corp. Municipal'),
('3966','ESCUELA VILLA SAN PEDRO','Ñuble','PEMUCO','Corp. Municipal'),
('3967','ESCUELA BASICA GENERAL CRUZ','Ñuble','PEMUCO','Corp. Municipal'),
('3968','ESCUELA BASICA MONTE EL LEON','Ñuble','PEMUCO','Corp. Municipal'),
('3970','ESCUELA BASICA CANELILLO','Ñuble','PEMUCO','Corp. Municipal'),
('3971','ESCUELA JOSÉ RENÉ SALGADO','Ñuble','PEMUCO','Corp. Municipal'),
('3972','ESCUELA ARTURO MATTE ALESSANDRI','Ñuble','PEMUCO','Corp. Municipal'),
('3974','ESCUELA BASICA VALLE HERMOSO','Ñuble','PEMUCO','Corp. Municipal'),
('3975','ESCUELA BASICA SALTO DE DANICALQUI','Ñuble','PEMUCO','Corp. Municipal'),
('3976','LICEO MANUEL BULNES','Ñuble','BULNES','Corp. Municipal'),
('3977','LICEO BICENTENARIO SANTA CRUZ DE LARQUI','Ñuble','BULNES','Corp. Municipal'),
('3978','ESCUELA CELIA URRUTIA PRIETO','Ñuble','BULNES','Corp. Municipal'),
('3979','LICEO POLIVALENTE ADULTOS DE ITATA','Ñuble','BULNES','Corp. Municipal'),
('3980','ESCUELA BASICA PUEBLO SECO SANTA CLARA','Ñuble','BULNES','Corp. Municipal'),
('3981','ESCUELA EL PALPAL DE SANTA CLARA','Ñuble','BULNES','Corp. Municipal'),
('3982','ESCUELA BATALLA DEL ROBLE','Ñuble','BULNES','Corp. Municipal'),
('3983','ESCUELA EVARISTA OGALDE ORTEGA','Ñuble','BULNES','Corp. Municipal'),
('3984','ESCUELA CANTA RANA','Ñuble','BULNES','Corp. Municipal'),
('3991','ESCUELA COLTON QUILLAY','Ñuble','BULNES','Corp. Municipal'),
('3992','ESCUELA MILAHUE','Ñuble','BULNES','Corp. Municipal'),
('3994','ESCUELA LOS ESTANQUES','Ñuble','BULNES','Corp. Municipal'),
('3995','ESCUELA LOS TILOS JOSÉ ANDRADES VÁSQUEZ','Ñuble','BULNES','Corp. Municipal'),
('3997','ESCUELA EL CARACOL','Ñuble','BULNES','Corp. Municipal'),
('3998','LICEO POLIVALENTE LUIS CRUZ MARTINEZ','Ñuble','QUILLÓN','Corp. Municipal'),
('3999','ESCUELA BASICA HEROES DEL ITATA','Ñuble','QUILLÓN','Corp. Municipal'),
('4000','ESCUELA BÁSICA AMANDA CHÁVEZ NAVARRETE','Ñuble','QUILLÓN','Corp. Municipal'),
('4001','ESCUELA PEDRO ENRIQUE TORRES SABELLE','Ñuble','QUILLÓN','Corp. Municipal'),
('4002','ESCUELA BASICA EL CASINO','Ñuble','QUILLÓN','Corp. Municipal'),
('4003','ESCUELA BASICA HUACAMALA','Ñuble','QUILLÓN','Corp. Municipal'),
('4005','ESCUELA BÁSICA PUERTO LOS FRUTALES DE COYANCO','Ñuble','QUILLÓN','Corp. Municipal'),
('4006','ESCUELA BASICA LIUCURA BAJO','Ñuble','QUILLÓN','Corp. Municipal'),
('4016','ESCUELA BASICA PASO EL ROBLE','Ñuble','QUILLÓN','Corp. Municipal'),
('4017','ESCUELA BASICA MANUEL BAQUEDANO GONZALEZ','Ñuble','RANQUIL','Corp. Municipal'),
('4019','ESCUELA BÁSICA LAGUNA AVENDAÑO','Ñuble','QUILLÓN','Corp. Municipal'),
('4022','ESCUELA QUINEL','Biobío','CABRERO','Corp. Municipal'),
('4025','LICEO BICENTENARIO DE EXCELENCIA POLIVALENTE VIRGINIO ARIAS','Ñuble','RANQUIL','Corp. Municipal'),
('4026','ESCUELA BASICA NUEVA ALDEA','Ñuble','RANQUIL','Corp. Municipal'),
('4027','ESCUELA BASICA VEGAS DE CONCHA','Ñuble','RANQUIL','Corp. Municipal'),
('4029','ESCUELA BASICA SAN IGNACIO DE PALOMARES','Ñuble','RANQUIL','Corp. Municipal'),
('4030','ESCUELA BASICA BLANCA ROSA GUZMAN REYES','Ñuble','RANQUIL','Corp. Municipal'),
('4032','LICEO BICENTENARIO DE EXCELENCIA NIBALDO SEPÚLVEDA FERNÁNDEZ','Ñuble','PORTEZUELO','Corp. Municipal'),
('4034','ESCUELA LOMAS DE CHUDAL','Ñuble','PORTEZUELO','Corp. Municipal'),
('4037','ESCUELA MEMBRILLAR','Ñuble','PORTEZUELO','Corp. Municipal'),
('4039','ESCUELA SAN FRANCISCO DE ASIS','Ñuble','PORTEZUELO','Corp. Municipal'),
('4040','ESCUELA CUCHA URREJOLA','Ñuble','PORTEZUELO','Corp. Municipal'),
('4043','COLEGIO NUESTRA SEÑORA DEL CARMEN','Ñuble','PORTEZUELO','Part. Subvencionado'),
('4048','ESCUELA VILLA JESUS DE COELEMU','Ñuble','COELEMU','Corp. Municipal'),
('4049','LICEO BICENTENARIO DE EXCELENCIA DOMINGO ORTÍZ DE ROZAS','Ñuble','COELEMU','Corp. Municipal'),
('4050','ESCUELA MARIA TERESA MARCHANT CONTRERAS','Ñuble','COELEMU','Corp. Municipal'),
('4051','ESCUELA CLEMENTINA MAUREIRA ALMANZA','Ñuble','COELEMU','Corp. Municipal'),
('4052','ESCUELA GUARILIHUE ALTO','Ñuble','COELEMU','Corp. Municipal'),
('4054','ESCUELA MAGDALENA','Ñuble','COELEMU','Corp. Municipal'),
('4058','ESCUELA HUARO','Ñuble','COELEMU','Corp. Municipal'),
('4059','ESCUELA FELIPE CUBILLOS SIGAL','Ñuble','COELEMU','Corp. Municipal'),
('4061','ESCUELA BASICA AMERICA','Ñuble','RANQUIL','Corp. Municipal'),
('4062','ESCUELA VEGAS DE ITATA','Ñuble','COELEMU','Corp. Municipal'),
('4063','ESCUELA BASICA VALLE LOS CASTANOS','Ñuble','COELEMU','Corp. Municipal'),
('4064','ESCUELA MEIPO','Ñuble','COELEMU','Corp. Municipal'),
('4067','ESCUELA SANTA FILOMENA','Ñuble','COELEMU','Corp. Municipal'),
('4068','ESCUELA BUENA FE DE TUBUL','Ñuble','COELEMU','Corp. Municipal'),
('4070','ESCUELA BASICA MAITENCO','Ñuble','TREHUACO','Corp. Municipal'),
('4071','ESCUELA BÁSICA VALLE LONQUÉN','Ñuble','TREHUACO','Corp. Municipal'),
('4073','ESCUELA BASICA MONTE OLIMPO','Ñuble','TREHUACO','Corp. Municipal'),
('4074','ESCUELA BASICA TAUCO','Ñuble','TREHUACO','Corp. Municipal'),
('4075','ESCUELA CERRO ALTO','Ñuble','TREHUACO','Corp. Municipal'),
('4076','ESCUELA BASICA MINAS DE LEUQUE','Ñuble','TREHUACO','Corp. Municipal'),
('4077','ESCUELA BASICA VILLA DENECAN','Ñuble','TREHUACO','Corp. Municipal'),
('4079','ESCUELA BASICA MATACO','Ñuble','TREHUACO','Corp. Municipal'),
('4081','ESCUELA BASICA ANTIQUEREO','Ñuble','TREHUACO','Corp. Municipal'),
('4084','LICEO POLIVALENTE DIEGO MISSENE BURGOS','Ñuble','COBQUECURA','Corp. Municipal'),
('4085','ESCUELA BASICA EL TOLLO','Ñuble','COBQUECURA','Corp. Municipal'),
('4087','ESCUELA BASICA BUCHUPUREO','Ñuble','COBQUECURA','Corp. Municipal'),
('4088','ESCUELA BASICA LA ANTENA','Ñuble','COBQUECURA','Corp. Municipal'),
('4089','ESCUELA BASICA LA ACHIRA','Ñuble','COBQUECURA','Corp. Municipal'),
('4090','ESCUELA BASICA COLMUYAO','Ñuble','COBQUECURA','Corp. Municipal'),
('4091','ESCUELA BASICA EL AVELLANAL','Ñuble','COBQUECURA','Corp. Municipal'),
('4093','ESCUELA BASICA LOS NEDANOS','Ñuble','COBQUECURA','Corp. Municipal'),
('4094','ESCUELA BASICA TAUCU','Ñuble','COBQUECURA','Corp. Municipal'),
('4095','ESCUELA BÁSICA MONTAÑA DE COPIHUES G 54-A','Ñuble','COBQUECURA','Corp. Municipal'),
('4096','ESCUELA BASICA QUILE','Ñuble','COBQUECURA','Corp. Municipal'),
('4097','ESCUELA BASICA LOS CORRALES','Ñuble','COBQUECURA','Corp. Municipal'),
('4100','ESCUELA BASICA MELA','Ñuble','COBQUECURA','Corp. Municipal'),
('4101','ESCUELA BASICA PULLAY','Ñuble','COBQUECURA','Corp. Municipal'),
('4102','LICEO BICENTENARIO DE EXCELENCIA CARLOS MONTANE CASTRO','Ñuble','QUIRIHUE','Corp. Municipal'),
('4103','ESCUELA GRUMETE CORTES','Ñuble','QUIRIHUE','Corp. Municipal'),
('4104','ESCUELA NUEVA AMERICA','Ñuble','QUIRIHUE','Corp. Municipal'),
('4106','ESCUELA BASICA HORIZONTE','Ñuble','QUIRIHUE','Corp. Municipal'),
('4107','ESCUELA BASICA SANTA CAROLINA','Ñuble','QUIRIHUE','Corp. Municipal'),
('4110','ESCUELA BASICA CAJON EL MANZANO','Ñuble','QUIRIHUE','Corp. Municipal'),
('4112','ESCUELA BASICA SANTA ELENA','Ñuble','QUIRIHUE','Corp. Municipal'),
('4115','ESCUELA BASICA SANTA EFIGENIA','Ñuble','QUIRIHUE','Corp. Municipal'),
('4116','ESCUELA BASICA EL CONCUYO','Ñuble','QUIRIHUE','Corp. Municipal'),
('4118','ESCUELA BASICA ALTO DE PIEDRA','Ñuble','QUIRIHUE','Corp. Municipal'),
('4120','ESCUELA BASICA LOS REMATES','Ñuble','QUIRIHUE','Corp. Municipal'),
('4121','ESCUELA BASICA EL SOL','Ñuble','QUIRIHUE','Corp. Municipal'),
('4124','LICEO BICENTENARIO DE EXCELENCIA ARTURO PRAT CHACON','Ñuble','NINHUE','Corp. Municipal'),
('4125','ESCUELA ROSARIO CHACON BARRIOS','Ñuble','NINHUE','Corp. Municipal'),
('4128','ESCUELA BASICA DE RELOCA','Ñuble','NINHUE','Corp. Municipal'),
('4130','ESCUELA BASICA EL RINCON','Ñuble','NINHUE','Corp. Municipal'),
('4131','ESCUELA DOCTOR DAVID BENAVENTE SEPÚLVEDA','Ñuble','NINHUE','Corp. Municipal'),
('4133','ESCUELA ALIPIA ACEVEDO','Ñuble','NINHUE','Corp. Municipal'),
('4134','ESCUELA BASICA TALHUAN','Ñuble','NINHUE','Corp. Municipal'),
('4139','ESCUELA PARTICULAR ADVENTISTA QUIRAO','Ñuble','NINHUE','Part. Subvencionado'),
('4140','LICEO BICENTENARIO DE EXCELENCIA POLIVALENTE SAN NICOLÁS','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4141','LICEO BICENTENARIO DE EXCELENCIA TÉCNICO PUENTE ÑUBLE','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4142','ESCUELA LA MERCED','Ñuble','SAN CARLOS','Servicio Local'),
('4146','ESCUELA BASICA LA LOMA','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4148','ESCUELA BASICA PENA SANTA ROSA','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4150','ESCUELA BASICA PIEDRA LISA','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4154','ESCUELA BASICA LAJUELAS','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4155','ESCUELA BASICA DADINCO','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4158','ESCUELA BASICA MONTELEON','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('4160','LICEO COMERCIAL CAMILO HENRIQUEZ','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4162','LICEO COMERCIAL DIEGO PORTALES PALAZUELO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4163','LICEO BICENTENARIO LOS ÁNGELES','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4164','LICEO COEDUCACIONAL SANTA MARÍA DE LOS ÁNGELES','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4165','LICEO INDUSTRIAL SAMUEL VIVANCO PARADA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4166','LICEO TECNICO BICENTENARIO JUANITA FERNANDEZ SOLAR','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4168','ESCUELA GENERAL BERNARDO O HIGGINS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4169','ESCUELA ESPANA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4171','ESCUELA COLONIA ARABE','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4172','ESCUELA GENERAL JOSE DE SAN MARTIN','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4173','ESCUELA BLANCO ENCALADA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4174','ESCUELA HOGAR NIEVES VASQUEZ PALACIOS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4175','ESCUELA THOMAS JEFFERSON','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4176','ESCUELA JOSE MANSO DE VELASCO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4177','ESCUELA CLARA REBOLLEDO DE GODOY','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4179','ESCUELA PEDRO RUIZ ALDEA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4180','ESCUELA ARTURO ALESSANDRI PALMA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4181','ESCUELA BASICA REPUBLICA DE ISRAEL','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4183','ESCUELA BASICA 21 DE MAYO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4185','ESCUELA ISLA DE LAJA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4186','ESCUELA BASICA REPUBLICA DE ALEMANIA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4187','ESCUELA BÁSICA ESPERANZA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4188','ESCUELA REPUBLICA DE GRECIA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4189','ESCUELA BASICA 11 DE SEPTIEMBRE','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4190','LICEO SANTA FE','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4191','ESCUELA BASICA SANTA CLARA DE CHACAYAL','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4193','ESCUELA BASICA LOS MOLINOS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4194','ESCUELA BASICA LA QUEBRADA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4195','LICEO AGROINDUSTRIAL LLANO BLANCO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4197','ESCUELA CORONEL GUILLERMO MARIN CARMONA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4199','ESCUELA BASICA LA AGUADA DE CUEL','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4200','ESCUELA BASICA VIRQUENCO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4201','ESCUELA BÁSICA HITILHUE','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4202','ESCUELA BASICA LOS TRONCOS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4204','ESCUELA BASICA MILLANTU','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4205','ESCUELA DIEGO PORTALES PALAZUELOS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4207','ESCUELA BÁSICA LA RINCONADA DEL SALTO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4210','ESCUELA BASICA COYANCO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4212','ESCUELA BASICA LAS QUINTAS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4216','ESCUELA BASICA EL CHEQUEN','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4221','ESCUELA BASICA LA CAPILLA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4228','ESCUELA BASICA LA MANCHA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4231','ESCUELA BASICA LA LEYENDA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4235','ESCUELA BASICA EL AMANECER DE DUQUECO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4239','ESCUELA BASICA HARAS EL LAJA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4241','ESCUELA TENIENTE IGNACIO SERRANO','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4254','ESCUELA PUENTE PERALES','Biobío','LAJA','Corp. Municipal'),
('4255','ESCUELA BASICA EL NOGAL.','Biobío','LOS ÁNGELES','Corp. Municipal'),
('4258','ESCUELA SANTA MARÍA DE LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4259','COLEGIO SAN NICOLÁS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4260','CENTRO EDUC. Y CAPAC. LABORAL CECAP','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4262','COLEGIO PARTICULAR MARTA BRUNET','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4263','COLEGIO SAN RAFAEL ARCANGEL','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4266','COLEGIO LOS ANGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4268','ESCUELA PARTICULAR ADVENTISTA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4269','COLEGIO HISPANOAMERICANO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4270','LICEO PARTICULAR CARLOS CONDELL','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4272','ESCUELA PARTICULAR DIEGO DE ALMAGRO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4275','ESCUELA PARTICULAR LA VICTORIA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4277','CENTRO EDUCACIÓN ADVENTISTA LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4280','ESCUELA PARTICULAR SAN JOSÉ','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4285','LICEO ALEMAN DEL VERBO DIVINO','Biobío','LOS ÁNGELES','Part. Pagado'),
('4286','COLEGIO ALEMAN LOS ANGELES','Biobío','LOS ÁNGELES','Part. Pagado'),
('4287','LICEO AGRÍCOLA Y FORESTAL EL HUERTÓN','Biobío','LOS ÁNGELES','Adm. Delegada'),
('4288','LICEO BICENTENARIO POLITÉCNICO MONTE ÁGUILA','Biobío','CABRERO','Corp. Municipal'),
('4289','LICEO MANUEL ARÍSTIDES ZAÑARTU','Biobío','CABRERO','Corp. Municipal'),
('4290','ESCUELA CHARRUA','Biobío','CABRERO','Corp. Municipal'),
('4292','ESCUELA SALTO EL LAJA','Biobío','CABRERO','Corp. Municipal'),
('4295','ESCUELA PILLANCO','Biobío','CABRERO','Corp. Municipal'),
('4297','ESCUELA LAS OBRAS','Biobío','CABRERO','Corp. Municipal'),
('4298','ESCUELA EL MANZANO','Biobío','CABRERO','Corp. Municipal'),
('4299','ESCUELA EL PARAISO','Biobío','CABRERO','Corp. Municipal'),
('4300','ESCUELA LOMAS DE ANGOL','Biobío','CABRERO','Corp. Municipal'),
('4302','ESCUELA COLICHEU','Biobío','CABRERO','Corp. Municipal'),
('4303','ESCUELA LOS CAULLES','Biobío','CABRERO','Corp. Municipal'),
('4304','ESCUELA LOS LEONES','Biobío','CABRERO','Corp. Municipal'),
('4305','HACIENDA MONTE ÁGUILA','Biobío','CABRERO','Corp. Municipal'),
('4306','ESCUELA EL PROGRESO','Biobío','CABRERO','Corp. Municipal'),
('4307','COLEGIO SAN JOSE','Biobío','CABRERO','Part. Subvencionado'),
('4308','COLEGIO ABEL INOSTROZA GUTIERREZ','Biobío','CABRERO','Part. Subvencionado'),
('4309','LICEO DE HUEPIL','Biobío','TUCAPEL','Corp. Municipal'),
('4310','LICEO ANDRÉS ALCÁZAR DE TUCAPEL','Biobío','TUCAPEL','Corp. Municipal'),
('4311','ESCUELA LOS AVELLANOS','Biobío','TUCAPEL','Corp. Municipal'),
('4312','ESCUELA ALEJANDRO PEREZ URBANO','Biobío','TUCAPEL','Corp. Municipal'),
('4314','ESCUELA LAS HIJUELAS','Biobío','TUCAPEL','Corp. Municipal'),
('4317','ESCUELA LOS AROMOS','Biobío','TUCAPEL','Corp. Municipal'),
('4320','ESCUELA LAS ASTAS','Biobío','TUCAPEL','Corp. Municipal'),
('4321','ESCUELA LOMAS DE TUCAPEL','Biobío','TUCAPEL','Corp. Municipal'),
('4323','ESCUELA LA COLONIA','Biobío','TUCAPEL','Corp. Municipal'),
('4324','LICEO DOCTOR VÍCTOR RÍOS RUIZ','Biobío','ANTUCO','Corp. Municipal'),
('4327','ESCUELA VOLCAN ANTUCO','Biobío','ANTUCO','Corp. Municipal'),
('4328','ESCUELA BASICA CERRO PILQUE','Biobío','ANTUCO','Corp. Municipal'),
('4330','ESCUELA OLGA RIOS DE PINOCHET','Biobío','ANTUCO','Corp. Municipal'),
('4331','LICEO BICENTENARIO FRANCISCO BASCUNAN GUERRERO','Biobío','QUILLECO','Corp. Municipal'),
('4333','LICEO ISABEL RIQUELME','Biobío','QUILLECO','Corp. Municipal'),
('4334','ESCUELA BASICA VILLA MERCEDES','Biobío','QUILLECO','Corp. Municipal'),
('4335','ESCUELA BASICA NUEVO AMANECER','Biobío','QUILLECO','Corp. Municipal'),
('4337','ESCUELA BASICA LA HOYADA','Biobío','QUILLECO','Corp. Municipal'),
('4338','ESCUELA BASICA CANICURA','Biobío','QUILLECO','Corp. Municipal'),
('4339','ESCUELA BASICA CENTINELA','Biobío','QUILLECO','Corp. Municipal'),
('4340','ESCUELA PROFESORA ALBERTINA SÁNCHEZ VALENZUELA','Biobío','QUILLECO','Corp. Municipal'),
('4341','ESCUELA LAS ARENAS','Biobío','QUILLECO','Corp. Municipal'),
('4342','ESCUELA ERMINDA GOMEZ DE POLIC.','Biobío','QUILLECO','Corp. Municipal'),
('4345','ESCUELA BASICA RIO PARDO','Biobío','QUILLECO','Corp. Municipal'),
('4347','ESCUELA BLANCA ESTRELLA','Biobío','QUILLECO','Corp. Municipal'),
('4348','ESCUELA BASICA EL ESFUERZO','Biobío','QUILLECO','Corp. Municipal'),
('4349','ESCUELA BASICA LA MESETA','Biobío','QUILLECO','Corp. Municipal'),
('4350','ESCUELA PARTICULAR LAS AGUILAS','Biobío','QUILLECO','Part. Subvencionado'),
('4351','ESCUELA MONSEÑOR OROZIMBO FUENZALIDA','Biobío','QUILLECO','Part. Subvencionado'),
('4352','ESCUELA BÁSICA ENRIQUE BERNSTEIN CARABANTES','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4353','LICEO CARDENAL ANTONIO SAMORE','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4354','ESCUELA DE CONCENTRACIÓN FRONTERIZA RALCO ALTO BIOBÍO','Biobío','ALTO BIOBÍO','Corp. Municipal'),
('4355','ESCUELA DE EDUCACIÓN GENERAL BÁSICA EL HUACHI','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4356','ESCUELA LOS BOLDOS','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4357','ESCUELA BASICA VILLACURA','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4358','ESCUELA MARIANO PUGA VEGA','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4359','ESCUELA BASICA MANIL','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4361','ESCUELA BASICA CORCOVADO','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4365','ESCUELA RINCONADA','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4368','ESCUELA LOS NOTROS','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4372','ESCUELA QUILLAILEO','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('4374','ESCUELA BASICA PITRIL','Biobío','ALTO BIOBÍO','Corp. Municipal'),
('4375','ESCUELA RALCO LEPOY','Biobío','ALTO BIOBÍO','Corp. Municipal'),
('4379','ESCUELA CALLAQUI','Biobío','ALTO BIOBÍO','Corp. Municipal'),
('4381','CENTRO DE LENGUAJE Y APRENDIZAJE','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('4382','COLEGIO SANTA BARBARA','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('4384','ESCUELA PARTICULAR QUEPUCA RALCO','Biobío','ALTO BIOBÍO','Part. Subvencionado'),
('4386','ESCUELA PARTICULAR EDGARDO SOLAR ACUÑA','Biobío','ALTO BIOBÍO','Part. Subvencionado'),
('4387','ESCUELA LAS PARCELAS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('4389','ESCUELA PARTICULAR TRAPA TRAPA','Biobío','ALTO BIOBÍO','Part. Subvencionado'),
('4391','ESCUELA EL CASTILLO','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('4392','LICEO BICENTENARIO VALLE DEL SOL QUILACO','Biobío','QUILACO','Corp. Municipal'),
('4393','ESCUELA BASICA RUCALHUE','Biobío','QUILACO','Corp. Municipal'),
('4395','ESCUELA BASICA CERRO EL PADRE','Biobío','QUILACO','Corp. Municipal'),
('4396','ESCUELA BASICA CAMPAMENTO','Biobío','QUILACO','Corp. Municipal'),
('4397','ESCUELA BASICA DANICALQUI','Biobío','QUILACO','Corp. Municipal'),
('4398','ESCUELA BASICA DE BELLAVISTA','Biobío','QUILACO','Corp. Municipal'),
('4402','ESCUELA BASICA LONCOPANGUE','Biobío','QUILACO','Corp. Municipal'),
('4403','ESCUELA DE ADULTOS RIO SUR','Biobío','MULCHÉN','Corp. Municipal'),
('4404','LICEO MIGUEL ÁNGEL CERDA LEIVA','Biobío','MULCHÉN','Corp. Municipal'),
('4405','ESCUELA BLANCO ENCALADA','Biobío','MULCHÉN','Corp. Municipal'),
('4406','ESCUELA BASICA MULCHEN','Biobío','MULCHÉN','Corp. Municipal'),
('4407','ESCUELA IGNACIO VERDUGO CAVADA','Biobío','MULCHÉN','Corp. Municipal'),
('4408','LICEO CRISOL','Biobío','MULCHÉN','Corp. Municipal'),
('4409','ESCUELA SACERDOTE ALEJANDRO MANERA','Biobío','MULCHÉN','Corp. Municipal'),
('4410','ESCUELA ARTÍSTICA VILLA LAS PEÑAS','Biobío','MULCHÉN','Corp. Municipal'),
('4412','ESCUELA ALHUELEMU','Biobío','MULCHÉN','Corp. Municipal'),
('4414','ESCUELA BASICA MUNILQUE IZAURIETA','Biobío','MULCHÉN','Corp. Municipal'),
('4417','ESCUELA BASICA SAN LUIS DE MALVEN','Biobío','MULCHÉN','Corp. Municipal'),
('4419','ESCUELA BASICA BUREO','Biobío','MULCHÉN','Corp. Municipal'),
('4421','ESCUELA BASICA PILGUEN','Biobío','MULCHÉN','Corp. Municipal'),
('4426','ESCUELA BASICA EL PARRON','Biobío','MULCHÉN','Corp. Municipal'),
('4432','ESCUELA BASICA EL EDEN','Biobío','MULCHÉN','Corp. Municipal'),
('4433','ESCUELA BASICA RAPELCO','Biobío','MULCHÉN','Corp. Municipal'),
('4435','ESCUELA BASICA LOS HINOJOS','Biobío','MULCHÉN','Corp. Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
