-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 18 de 31 | filas 6801-7200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('12593','J.I.SAINT MARGARET ROSE GARDEN','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12594','COLEGIO ANTAMARA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12599','JARDIN INFANTIL ANAKENA','Tarapacá','IQUIQUE','Part. Pagado'),
('12602','ESC. BASICA Y PARV. KRONOS SCHOOL','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12603','LICEO LOS CONDORES','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12604','ESCUELA BASICA CORONA SCHOOL','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12605','ACADEMIA HOSPICIO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12606','JARDIN INFANTIL LOS TATITAS','Tarapacá','IQUIQUE','Part. Pagado'),
('12607','JARDIN INFANTIL MIS PRIMEROS PASOS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12609','ESCUELA DE LENGUAJE INTI-PAXI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12610','LICEO INSTITUTO COMERCIAL DE ARICA','Arica y Parinacota','ARICA','Servicio Local'),
('12613','JARDIN INFANTIL TALPIOT','Tarapacá','IQUIQUE','Part. Pagado'),
('12617','ESCUELA ESTRELLA DEL SUR','Tarapacá','POZO ALMONTE','Municipal'),
('12619','JARDIN INFANTIL HAPPY DAY','Tarapacá','IQUIQUE','Part. Pagado'),
('12621','JARDIN INFANTIL D`STEPHANO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12622','JARDIN INFANTIL PEQUENO ARRAU','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12623','ESCUELA SAN ANDRES DE PICA','Tarapacá','PICA','Corp. Municipal'),
('12630','COLEGIO LEONARDO DA VINCI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12631','COLEGIO INGLES','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12632','COLEGIO SIMON BOLIVAR','Tarapacá','ALTO HOSPICIO','Servicio Local'),
('12634','COLEGIO SAN LORENZO DE TARAPACA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12635','ACADEMIA IQUIQUE','Tarapacá','IQUIQUE','Part. Pagado'),
('12636','COLEGIO NIMARA','Tarapacá','IQUIQUE','Part. Pagado'),
('12646','COSTA COLLEGE','Tarapacá','IQUIQUE','Part. Pagado'),
('12648','JARDIN INFANTIL HAPPY GARDEN','Tarapacá','IQUIQUE','Part. Pagado'),
('12649','LICEO SUPERIOR DIEGO PORTALES','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12650','COLEGIO SAGRADO CORAZON DE JESUS','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12652','COLEGIO SANTO DOMINGO SAVIO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12655','COLEGIO SAN PEDRO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12657','EAGLES COLLEGE','Tarapacá','IQUIQUE','Part. Pagado'),
('12658','LICEO AGR. TEC. PROF. PADRE FRANCISCO NAPOLITANO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12659','COLEGIO DEL ALBA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12660','ESC. ESP. DE LENGUAJE MONSERRAT','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12661','J. I. PUKARA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12664','ESCUELA SAN SANTIAGO DE MACAYA','Tarapacá','POZO ALMONTE','Municipal'),
('12667','COLEGIO HUMBERSTONE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12668','ESCUELA SOTOCA','Tarapacá','HUARA','Corp. Municipal'),
('12669','COLEGIO HISPANO BRITANICO IQUIQUE','Tarapacá','IQUIQUE','Part. Pagado'),
('12670','ESC.ESP.DE TRANS. DE LA COM. ARUSINA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12672','COLEGIO SALESIANO DE IQUIQUE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12674','J. I.  MY FRIEND','Tarapacá','IQUIQUE','Part. Pagado'),
('12675','ESC. ESP. DE LENGUAJE MILLARAY','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12678','JARDIN INFANTIL CARITAS CONTENTAS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12680','ESC.TRANS.DE LA COMUN. IKI ARU','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12681','ESC.TRAST.DE LA COM.FLOR DE LIRIO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12682','COLEGIO BULNES','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12685','ESC.ESP. DE TRASTORNO DE LA COMUN ISLUGA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12686','LICEO ACADEMIA NACIONAL','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12688','COLEGIO GOLDEN NORTH','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12691','COLEGIO JESUS DE NAZARETH','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12693','COLEGIO MACAYA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12694','COLEGIO MOSAICOS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12695','ESCUELA ESP DE LENGUAJE PARINA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12696','LICEO TECNICO PROF. DE ADULTOS PUKARA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12697','ESC. ESPECIAL DE TRASTORNOS AUDIMED IQUIQUE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12698','ESC ESP DE LENGUAJE STA CAROLINA DE MATILLA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12699','ESC. ESP. DE LENGUAJE KHANA ARU','Tarapacá','POZO ALMONTE','Part. Subvencionado'),
('12700','ESC. ESP. TRANST. COM. SANTA LAURA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12702','J. I. LITTLE SUN','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12704','JARDIN INFANTIL AMANECER','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12705','JARDIN INFANTIL DON OSITO','Arica y Parinacota','ARICA','Part. Pagado'),
('12708','ESCUELA ESPECIAL JACARANDA','Tarapacá','PICA','Corp. Municipal'),
('12709','ACADEMIA NERUDIANA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12710','COLEGIO HUANTAJAYA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12712','COLEGIO CHILE NORTE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12713','LICEO BICENTENARIO COLEGIO CARDENAL RAUL SILVA HENRIQUEZ','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12714','ESC.PARV.DE LENGUAJE DIVINO NINO JESUS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12715','COLEGIO MARAN-ATHA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12716','COLEGIO BICENTENARIO MIRAMAR DE EXCELENCIA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12717','JARDIN INFANTIL AMTIRI','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12719','LICEO PABLO NERUDA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12720','COLEGIO ADOLFO BEYZAGA OVANDO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12721','JARDIN INFANTIL CASTILLLO DEL SABER','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12722','JARDIN INFANTIL GIRASOLES','Tarapacá','IQUIQUE','Part. Pagado'),
('12724','J.  I. AGU','Tarapacá','IQUIQUE','Part. Pagado'),
('12725','ESCUELA ESPECIAL PADRE PIO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12726','COLEGIO MONTE CARMELO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12727','ESCUELA ESPECIAL DE LENG. PIECECITOS DE NIÑO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12728','COLEGIO ALTURAS','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12730','LICEO TEC. PROF. DE ADULTOS CORESOL','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12731','ESCUELA ESPECIAL DE LENGUAJE LOS ANDES','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12732','ESC ESP DE LENGUAJE COLINA CAMPESTRE','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12733','JARDIN INFANTIL LA GRANJITA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12734','ESC ESP DE LENGUAJE ESPISANT','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12736','ACADEMIA POZO ALMONTE','Tarapacá','POZO ALMONTE','Part. Subvencionado'),
('12738','ESC.ESP. DE LENGUAJE SANTA LUCIA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12739','ESC ESP DE LENGUAJE OASIS DEL SABER','Tarapacá','IQUIQUE','Servicio Local'),
('12741','COLEGIO LATIONOAMERICANO LAS PARINAS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12742','ESCUELA ESPECIAL DE LENGUAJE INTI - JALLU','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12746','ESCUELA ESPECIAL DE LENGUAJE VILENKA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12747','COLEGIO RUPANIC SCHOOL','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12748','ESCUELA ESP. DE LENG MANANTIAL DEL SABER','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12749','COLEGIO MARISTA HERMANO FERNANDO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12750','LICEO DE ADULTOS JUNIOR COLLEGE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12751','ESCUELA DE LENGUAJE KERIMA LTDA.','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12753','ESC ESP DE LENGUAJE MI RAYITO DE SOLAZ','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12756','JARDIN INFANTIL DAELY','Tarapacá','IQUIQUE','Part. Pagado'),
('12757','JARDIN INFANTIL SAMCA ARUMANTI DE IQUIQUE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12758','LICEO C.E.I.A. JOSE ALEJANDRO SORIA VARAS','Tarapacá','IQUIQUE','Servicio Local'),
('12759','LICEO CAMIÑA','Tarapacá','CAMIÑA','Corp. Municipal'),
('12761','ESCUELA BASICA FRANCISCO FORGIONE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12762','IQRA ARABIAN BRITISH SCHOOL','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12764','ESCUELA ESPECIAL DE LENGUAJE QUILLECO','Biobío','QUILLECO','Part. Subvencionado'),
('12765','ESCUELA ESPECIAL DIVERSIA','Coquimbo','LOS VILOS','Part. Subvencionado'),
('12766','COLEGIO DE ADULTOS MANQUEHUE DE TIL TIL','Metropolitana','TILTIL','Part. Subvencionado'),
('12767','COLEGIO INGLÉS THE SOWER SCHOOL','Biobío','YUMBEL','Part. Subvencionado'),
('12770','ESCUELA ESPECIAL GEORGES POMPIDOU','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('12772','COLEGIO EXPERIMENTAL ARTISTICO ALBORES','Los Lagos','ANCUD','Part. Subvencionado'),
('12773','ESCUELA ESPECIAL DE LENGUAJE DIALECTA ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('12774','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑAS CUMBRES','Coquimbo','LA SERENA','Part. Subvencionado'),
('12775','INSTITUTO  DOMINGO  EYZAGUIRRE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('12776','ESCUELA DE LENGUAJE MI MUNDO DE LETRAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('12778','ESCUELAS  DEL  CARIÑO ALBORADA','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('12779','COLEGIO ALTOS DEL CERRO GRANDE','Coquimbo','LA SERENA','Part. Subvencionado'),
('12780','COLEGIO EDUCACION ESPECIAL ZAYED','Coquimbo','LA SERENA','Part. Subvencionado'),
('12781','AMAZING GRACE ENGLISH SCHOOL','Coquimbo','LA SERENA','Part. Pagado'),
('12800','COLEGIO BAUTISTA LOIS HART','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12802','FUND.EDUC.COL.FEMENINO MADRE DEL ROSARIO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12805','ESCUELA DE PARVULOS CARINOSITOS 1','Antofagasta','CALAMA','Part. Subvencionado'),
('12810','ESCUELA KAMAC MAYU','Antofagasta','CALAMA','Servicio Local'),
('12811','ESCUELA DE PARVULOS QUILLA ANTAY','Antofagasta','CALAMA','Servicio Local'),
('12814','ESCUELA DE PARVULOS RENATITO','Antofagasta','CALAMA','Part. Subvencionado'),
('12815','JARDIN INFANTIL PEKIN','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12820','ESCUELA DE PARVULOS MI HIJO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12822','ESCUELA DE PARVULOS SEMILLITA','Antofagasta','ANTOFAGASTA','Municipal'),
('12823','COLEGIO CALAMA','Antofagasta','CALAMA','Part. Subvencionado'),
('12824','COL  SUNFLOWER SCHOOL','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12827','ESCUELA ARTURO PRAT CHACON ANEXO','Antofagasta','TOCOPILLA','Servicio Local'),
('12829','COL  LEONARDO DA VINCI','Antofagasta','CALAMA','Part. Pagado'),
('12830','LICEO DE ESTUDIOS CONTABLES Y ADMINISTR.','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12831','ESCUELA DE PARVULOS TIERNO AMANECER','Antofagasta','CALAMA','Part. Subvencionado'),
('12832','COL  SAN IGNACIO','Antofagasta','CALAMA','Part. Pagado'),
('12834','C EST SUP  ESANE DEL NORTE','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12836','LICEO BICENTENARIO COLEGIO RÍO LOA','Antofagasta','CALAMA','Part. Subvencionado'),
('12837','COLEGIO PARTICULAR BET- EL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12838','COLEGIO ECOLOGICO MONTESSORI','Antofagasta','CALAMA','Part. Subvencionado'),
('12840','ESCUELA JUAN PABLO II','Antofagasta','ANTOFAGASTA','Municipal'),
('12842','LICEO BICENTENARIO AGROPECUARIO LIKAN ANTAI','Antofagasta','SAN PEDRO DE ATACAMA','Servicio Local'),
('12846','COLEGIO CHAÑARES','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12847','ESC  PARV  LOS 7 ENANITOS DEL BOSQUE','Antofagasta','CALAMA','Part. Pagado'),
('12851','COLEGIO PADRE ALBERTO HURTADO','Antofagasta','CALAMA','Part. Subvencionado'),
('12853','COLEGIO PARTICULAR SAN NICOLAS','Antofagasta','CALAMA','Part. Subvencionado'),
('12855','LICEO COMERCIAL COMPUTACIONAL STA SARA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12860','COLEGIO DIVINA PASTORA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12861','ESCUELA DE PARVULOS KING LIONS SCHOOL','Antofagasta','CALAMA','Part. Subvencionado'),
('12862','ESCUELA LAPICITO DE COLOR','Antofagasta','CALAMA','Part. Pagado'),
('12863','ESC  PARV  MY CASTLE GARDEN','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12864','COLEGIO UNIVERSITARIO ANTONIO RENDIC','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12865','ESC.DE PARVULOS LA CASITA DE CHOCOLATE','Antofagasta','CALAMA','Part. Subvencionado'),
('12867','COL  LICANCABUR','Antofagasta','CALAMA','Part. Pagado'),
('12868','COLEGIO EBEN EZER','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12869','ESCUELA DE PARVULOS GATO CON BOTAS','Antofagasta','CALAMA','Part. Subvencionado'),
('12870','C.E.I.A. ANTONIO RENDIC.','Antofagasta','ANTOFAGASTA','Municipal'),
('12871','ESCUELA BASICA VALENTIN LETELIER','Antofagasta','CALAMA','Servicio Local'),
('12872','ESCUELA MARÍA ANGÉLICA ELIZONDO BRICEÑO','Antofagasta','MEJILLONES','Corp. Municipal'),
('12875','ESC  PARV  CARINOSITOS 2','Antofagasta','CALAMA','Part. Pagado'),
('12876','LOESS SCHOOL','Antofagasta','CALAMA','Part. Pagado'),
('12877','ESC  PARV  CORAZONCITO','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12878','COLEGIO MI HIJO N_2','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12882','ESCUELA DE PARVULOS INTI PANNI','Antofagasta','CALAMA','Servicio Local'),
('12884','COL. INTERNACIONAL ANTOFAGASTA LTDA.','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12885','COLEGIO SAN AGUSTIN','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12886','ESCUELA DE PARVULOS MI MUNDO MAGICO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12887','ACUARELINES','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12888','ESC.ESPEC.DE LENGUAJE CAMINO DE AMOR','Antofagasta','CALAMA','Part. Subvencionado'),
('12889','EL PRINCIPITO FELIZ','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12890','MIS MAGICAS PALABRAS','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12891','NEW HEAVEN HIGH SCHOOL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12932','ESC. PARV. MINNIE`S KIDS','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12934','ESCUELA DE PARVULOS SAN LUCIANO','Antofagasta','MEJILLONES','Part. Subvencionado'),
('12935','COLEGIO PROVIDENCIA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12936','ESCUELA ESPECIAL DE LENGUAJE NAZARETH','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12939','SAN NICOLITO','Antofagasta','CALAMA','Part. Pagado'),
('12941','ESCUELA ALONDRA ROJAS BARRIOS','Antofagasta','TALTAL','Corp. Municipal'),
('12942','ESCUELA GABRIELA MISTRAL','Antofagasta','TOCOPILLA','Servicio Local'),
('12943','COLEGIO TECNICO INDUSTRIAL DON BOSCO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12944','REVERENDO PADRE PATRICIO CARIOLA','Antofagasta','ANTOFAGASTA','Municipal'),
('12945','ESCUELA ECOLOGICA PADRE ALBERTO HURTADO','Antofagasta','ANTOFAGASTA','Municipal'),
('12946','ESC. PARV. GREEN GARDEN','Antofagasta','CALAMA','Part. Pagado'),
('12948','ESCUELA DE PARVULOS NINO DE BELEN','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12949','ESC. PARV. SNOOPY 2','Antofagasta','CALAMA','Part. Pagado'),
('12951','ESCUELA EDUCACION ESPECIAL RAICES','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12952','J Y N SCHOOL','Antofagasta','CALAMA','Part. Subvencionado'),
('12953','ESCUELA ESPECIAL DE LENGUAJE LOS PANDITAS','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12955','ESCUELA BASICA JAVIERA CARRERA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12956','ESC. PARV. ANSCO','Antofagasta','CALAMA','Part. Pagado'),
('12958','THE GIANT SCHOOL ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12959','ESCUELA ESPECIAL DE LENGUAJE MIS MAGICAS PALA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12960','ESCUELA ESPECIAL DE LENGUAJE RIMAY ARU','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12961','LICEO RADOMIRO TOMIC ROMERO','Antofagasta','CALAMA','Servicio Local'),
('12962','ESCUELA ELMO FUNEZ CARRIZO','Antofagasta','ANTOFAGASTA','Municipal'),
('12963','THE ANTOFAGASTA BAPTIST COLLEGE','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12966','COLEGIO SAN PATRICIO','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12967','ESCUELA ESPECIAL DE LENGUAJE MARGARETH','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12968','ESCUELA ESPECIAL SAN SEBASTIAN','Antofagasta','MEJILLONES','Part. Subvencionado'),
('12969','ESCUELA DE PARVULOS MUNDO KIDS','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12970','NORTH COLLEGE','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12971','ESCUELA ESPECIAL DE LENGUAJE MONTESSORI','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12972','COLEGIO LA CONCEPCION','Antofagasta','ANTOFAGASTA','Municipal'),
('12974','COLEGIO INGLES-ALEMAN','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('12977','HARVEST CHRISTIAN SCHOOL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12979','ESCUELA DE PARVULOS PLANETA TIERRA','Antofagasta','CALAMA','Part. Subvencionado'),
('12980','LICEO BICENTENARIO DIEGO PORTALES PALAZUELOS','Antofagasta','CALAMA','Servicio Local'),
('12982','COLEGIO ESPECIAL LAURENT CLERC','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12983','ESCUELA DE PÀRVULOS DREAM SCHOOL','Antofagasta','CALAMA','Part. Pagado'),
('12984','ESCUELA DE PÁRVULOS CHUQUICAMATA','Antofagasta','CALAMA','Part. Pagado'),
('12986','ESCUELA ESPECIAL DE LENGUAJE MONTESSORI 2','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('12987','ESC. ESP. DE LENG. ARCO IRIS DE PALABRAS','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('13103','COLEGIO PARTICULAR CALDERA','Atacama','CALDERA','Part. Subvencionado'),
('13104','ESCUELA MANUEL ORELLA ECHANEZ','Atacama','CALDERA','Servicio Local'),
('13105','ESCUELA ESPECIAL PARTICULAR LOS CONEJITOS','Atacama','COPIAPÓ','Part. Subvencionado'),
('13107','JARDIN INFANTIL PARTICULAR   AGAZZI','Atacama','COPIAPÓ','Part. Pagado'),
('13108','JARDIN INFANTIL   BAMBI','Atacama','COPIAPÓ','Part. Pagado'),
('13112','COLEGIO SAN AGUSTÍN DE ATACAMA','Atacama','COPIAPÓ','Part. Subvencionado'),
('13116','ESCUELA BÁSICA RURAL JAIME PROHENS','Atacama','TIERRA AMARILLA','Servicio Local'),
('13117','COLEGIO PARTICULAR   SAN LORENZO','Atacama','COPIAPÓ','Part. Pagado'),
('13118','ESCUELA BÁSICA MARTA EMILIANA AGUILAR ZERÓN','Atacama','TIERRA AMARILLA','Servicio Local'),
('13121','ESCUELA BÁSICA CAPITÁN RAFAEL TORREBLANCA','Atacama','VALLENAR','Servicio Local'),
('13122','CENTRO DE EDUCACIÓN INTEGRADA DE ADULTOS CEIA','Atacama','VALLENAR','Servicio Local'),
('13123','JARDÍN INFANTIL PASITOS DE NIÑOS','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('13124','COLEGIO FELIX SUSAETA','Atacama','TIERRA AMARILLA','Part. Subvencionado'),
('13125','SCUOLA ITALIANA GIUSSEPPE VERDI','Atacama','COPIAPÓ','Part. Pagado'),
('13128','ESCUELA RURAL MOISÉS LÓPEZ TRUJILLO','Atacama','HUASCO','Servicio Local'),
('13131','JARDIN INFANTIL MANANTIAL','Atacama','COPIAPÓ','Part. Pagado'),
('13133','ESCUELA MANUEL RODRÍGUEZ','Atacama','COPIAPÓ','Servicio Local'),
('13134','ESCUELA MIREYA ZULETA ASTUDILLO','Atacama','HUASCO','Servicio Local'),
('13135','ESCUELA BÁSICA IGNACIO DOMEYKO','Atacama','CHAÑARAL','Servicio Local'),
('13136','JARDIN INFANTIL ARCO IRIS','Atacama','COPIAPÓ','Part. Pagado'),
('13138','COLEGIO FLORA NORMILLA','Atacama','COPIAPÓ','Part. Subvencionado'),
('13141','ESCUELA ESPECIAL DE TRASTORNOS DE LA COMUNICACIÓN APIR','Atacama','COPIAPÓ','Part. Subvencionado'),
('13142','JARDIN  INFANTIL  CARRUSEL','Atacama','VALLENAR','Part. Pagado'),
('13143','ESCUELA BYRON GIGOUX JAMES','Atacama','CALDERA','Servicio Local'),
('13145','LICEO TECNOLÓGICO DE COPIAPÓ','Atacama','COPIAPÓ','Servicio Local'),
('13146','ESCUELA INDUSTRIAL SALESIANOS COPIAPÓ','Atacama','COPIAPÓ','Part. Subvencionado'),
('13149','COLEGIO ALMENAR DE COPIAPO','Atacama','COPIAPÓ','Part. Pagado'),
('13152','ESCUELA ESPECIAL DE LENGUAJE AYLLU','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('13154','ESCUELA EL CHAÑAR','Atacama','COPIAPÓ','Servicio Local'),
('13155','JARDÍN INFANTIL MI RAYITO DE SOL','Atacama','CHAÑARAL','Part. Subvencionado'),
('13156','COLEGIO HÉROES DE ATACAMA','Atacama','COPIAPÓ','Part. Subvencionado'),
('13157','ESCUELA ESPECIAL CENTRO TRASTORNO DE LA COMUNICACIÓN PADRE ALBERTO HURTADO','Atacama','VALLENAR','Part. Subvencionado'),
('13159','JARDIN INFANTIL PARTICULAR   KOVACIC','Atacama','COPIAPÓ','Part. Pagado'),
('13162','ESCUELA DIFERENCIAL PUKARÁ','Atacama','COPIAPÓ','Servicio Local'),
('13163','ESCUELA CARLOS MARÍA SAYAGO','Atacama','COPIAPÓ','Servicio Local'),
('13164','JARDIN INFANTIL PARTICULAR PEQUITAS','Atacama','COPIAPÓ','Part. Pagado'),
('13167','ESCUELA EDMUNDO QUEZADA ARAYA','Atacama','VALLENAR','Servicio Local'),
('13168','LICEO EL PALOMAR','Atacama','COPIAPÓ','Servicio Local'),
('13169','ESCUELA TRASTORNO LENGUAJE RAYITO DE SOL','Atacama','COPIAPÓ','Part. Subvencionado'),
('13170','ESCUELA BASICA SARA CORTES CORTES','Atacama','DIEGO DE ALMAGRO','Servicio Local'),
('13171','ESCUELA DE ARTES MARTA COLVIN','Atacama','COPIAPÓ','Part. Pagado'),
('13172','ESCUELA ESP.TRAST.COMUNIC. AMANCAY','Atacama','TIERRA AMARILLA','Part. Subvencionado'),
('13176','CENTRO DE EDUCACIÓN INTEGRADA DE ADULTOS','Atacama','COPIAPÓ','Servicio Local'),
('13177','ESCUELA DE DESARROLLO ARTÍSTICO CALDERA','Atacama','CALDERA','Servicio Local'),
('13178','COLEGIO HISPANO AMÉRICA','Atacama','CHAÑARAL','Part. Subvencionado'),
('13181','ESCUELA EMILIA SCHWABE RUMOHR','Atacama','FREIRINA','Servicio Local'),
('13185','LICEO INSTITUTO TÉCNICO DE SERVICIOS PROFESIONALES','Atacama','VALLENAR','Servicio Local'),
('13186','CENTRO DE EDUCACIÓN INTEGRADA DE ADULTOS','Atacama','DIEGO DE ALMAGRO','Servicio Local'),
('13187','ESCUELA ESPECIAL DE LENGUAJE RAYITO DE SOL II','Atacama','COPIAPÓ','Part. Subvencionado'),
('13188','COLEGIO CERVANTINO','Atacama','COPIAPÓ','Part. Subvencionado'),
('13190','COLEGIO SAN FRANCISCO DE LA SELVA','Atacama','COPIAPÓ','Part. Pagado'),
('13191','ESCUELA ESPECIAL DE LENGUAJE LAURA VICUÑA','Atacama','VALLENAR','Part. Subvencionado'),
('13193','CENTRO DE EDUCACIÓN INTEGRADA DE ADULTOS CALDERA','Atacama','CALDERA','Servicio Local'),
('13195','ESCUELA DE LENGUAJE RINCÓN DEL SABER','Atacama','VALLENAR','Part. Subvencionado'),
('13196','ESCUELA ESPECIAL DE TRASTORNO DEL LENGUAJE FLOR DEL DESIERTO','Atacama','CALDERA','Part. Subvencionado'),
('13197','ESCUELA DE LENGUAJE MUNDO MÁGICO','Atacama','VALLENAR','Part. Subvencionado'),
('13198','ESCUELA ESPECIAL DE LENGUAJE MI ESTACIÓN','Atacama','COPIAPÓ','Part. Subvencionado'),
('13199','ESCUELA ESPECIAL DE LENGUAJE MIS RAÍCES','Atacama','HUASCO','Part. Subvencionado'),
('13200','ESCUELA ESPECIAL DE LENGUAJE NUEVA JUVENTUD','Atacama','HUASCO','Part. Subvencionado'),
('13202','LICEO BICENTENARIO DE VALLENAR','Atacama','VALLENAR','Servicio Local'),
('13203','ESCUELA DE TRASTORNO DEL LENGUAJE STELLA MARIS COPIAPÓ','Atacama','COPIAPÓ','Part. Subvencionado'),
('13204','ESCUELA  ESPECIAL  N°2420 LA  HUERTA','Metropolitana','TILTIL','Part. Subvencionado'),
('13206','ESCUELA ESPECIAL MUNDO COLOR','Valparaíso','LOS ANDES','Part. Subvencionado'),
('13207','ESCUELA ESPECIAL DE LENGUAJE EL CASTILLO DE VILCÚN','La Araucanía','VILCÚN','Part. Subvencionado'),
('13208','CENTRO DE EDUCACIÓN DE ADULTOS LA HAYA','La Araucanía','TEMUCO','Part. Subvencionado'),
('13212','ESCUELA  ESPECIAL  N°2422 AYEKAN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('13214','ESCUELA ESPECIAL DE LENGUAJE MI MUNDO DE COLORES','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('13215','COLEGIO HOSPITALARIO  CLINICA INDISA','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('13216','ESCUELA EPU NEWEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('13217','ESCUELA ESPECIAL DE LENGUAJE NEWEN ALON','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('13218','ESCUELA  ESPECIAL  N°196 AURINKO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('13220','COLEGIO LICARAYEN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('13300','COLEGIO ALEMAN','Coquimbo','LA SERENA','Part. Pagado'),
('13302','ESCUELA PARTICULAR CERRO BLANCO','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13305','COLEGIO TRINITY','Coquimbo','LA SERENA','Part. Subvencionado'),
('13309','ESC. BASICA LA HIGUERA DE PUNITAQUI','Coquimbo','PUNITAQUI','Corp. Municipal'),
('13312','ESCUELA PARTICULAR CHEPICA','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('13313','COLEGIO FRANCIS SCHOOL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13314','COLEGIO CRISTOBAL COLON','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13319','SCUOLA ITALIANA ALCIDE DE GASPERI','Coquimbo','LA SERENA','Part. Pagado'),
('13320','COLEGIO PARTICULAR TONGOY','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13324','COLEGIO SANTA MARIA DE BELEN N_ 162','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13328','JARDIN INF  DE LA UNIVERSIDAD DE LA SERENA','Coquimbo','LA SERENA','Part. Pagado'),
('13329','JARDIN INFANTIL HAPPY KING','Coquimbo','LA SERENA','Part. Pagado'),
('13330','COLEGIO PARTICULAR PIERROT','Coquimbo','LA SERENA','Part. Subvencionado'),
('13332','COLEGIO SAINT MARY SCHOOL','Coquimbo','COQUIMBO','Part. Pagado'),
('13333','ESC. FAMILIAR AGRICOLA VALLE DEL ELQUI','Coquimbo','LA SERENA','Part. Subvencionado'),
('13336','ESCUELA BASICA JOSE IGNACIO ZENTENO','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('13339','JARDIN INFANTIL SAN DANIEL','Coquimbo','LA SERENA','Part. Pagado'),
('13341','COLEGIO PART. KOMVUX - COQUIMBO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13342','COLEGIO PARTICULAR SAN FRANCISCO JAVIER','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13344','COLEGIO AMERICANO','Coquimbo','LA SERENA','Part. Subvencionado'),
('13352','LICEO POLIV.PADRE JOSE HERDE P-LHER','Coquimbo','CANELA','Corp. Municipal'),
('13356','COLEGIO ALBERT EINSTEIN','Coquimbo','LA SERENA','Part. Subvencionado'),
('13358','ESCUELA JUAN RENDIC','Coquimbo','VICUÑA','Servicio Local'),
('13360','COLEGIO SAN NICOLAS','Coquimbo','LA SERENA','Part. Subvencionado'),
('13361','KID´S WORLD SCHOOL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13362','ESCUELA BASICA LOS ANGELES DE RAPEL','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('13363','ESCUELA BASICA MUNICIPAL LA GRANJITA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('13365','ESCUELA BASICA MINILLAS','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('13370','COLEGIO DEL ALBA','Coquimbo','COQUIMBO','Part. Pagado'),
('13372','COLEGIO FRANCISCO PALAU','Coquimbo','LA SERENA','Part. Subvencionado'),
('13373','COLEGIO PARTICULAR LEONARDO DA VINCI','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13375','ESCUELA BASICA EL MEMBRILLO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('13376','COLEGIO SAN MANUEL','Coquimbo','LA SERENA','Part. Subvencionado'),
('13378','COLEGIO SER','Coquimbo','LA SERENA','Part. Pagado'),
('13379','ESCUELA BASICA CUMBRE DE LOS ANDES','Coquimbo','ILLAPEL','Corp. Municipal'),
('13380','ESCUELA BASICA MUNICIPAL LOS PERALES','Coquimbo','ILLAPEL','Corp. Municipal'),
('13383','COLEGIO CAMBRIDGE SCHOOL','Coquimbo','SALAMANCA','Part. Subvencionado'),
('13384','SAINT JOHN´S SCHOOL','Coquimbo','LA SERENA','Part. Subvencionado'),
('13387','COLEGIO DE ARTES ELISEO VIDELA JORQUERA','Coquimbo','OVALLE','Corp. Municipal'),
('13388','COLEGIO SANTO TOMAS LA SERENA','Coquimbo','LA SERENA','Part. Subvencionado'),
('13389','JARDIN INFANTIL RICITOS DORADOS','Coquimbo','LA SERENA','Part. Pagado'),
('13393','JARDIN INFANTIL MUNDO CLUB','Coquimbo','LA SERENA','Part. Subvencionado'),
('13394','CORAZON DE JESUS','Coquimbo','SALAMANCA','Part. Subvencionado'),
('13395','ESCUELA ESPECIAL HOLANDA','Coquimbo','SALAMANCA','Corp. Municipal'),
('13396','CENTRO EST.Y DES.INTEGRAL DEL NINO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13398','JARDIN INFANTIL TISKA MAMA','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13401','JARDIN INFANTIL CINDERELLA','Coquimbo','COQUIMBO','Part. Pagado'),
('13403','JARDIN INFANTIL LOS ROBLECITOS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13405','JARDIN INFANTIL MUNDO FELIZ','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13406','JARDIN INFANTIL PIECECITOS DE NINO','Coquimbo','LA SERENA','Part. Pagado'),
('13411','JARDIN INFANTIL FUERTE ALEGRIA','Coquimbo','LA SERENA','Part. Pagado'),
('13412','COLEGIO BASICO RENACER DE CERRILLOS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('13415','LICEO DE ADULTOS MAX PLANCK','Coquimbo','LA SERENA','Part. Subvencionado'),
('13416','COLEGIO ARTISTICO CULTURAL FORM-ARTE','Coquimbo','LA SERENA','Part. Subvencionado'),
('13417','COLEGIO ELQUI','Coquimbo','LA SERENA','Part. Subvencionado'),
('13420','COLEGIO NUESTRA SENORA DE ANDACOLLO','Coquimbo','LA SERENA','Part. Subvencionado'),
('13423','ESCUELA BASICA AMANECER','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('13424','JARDIN INFANTIL SUEÑO AZUL','Coquimbo','LA SERENA','Part. Subvencionado'),
('13426','COLEGIO SAN LUCAS','Coquimbo','LA SERENA','Part. Subvencionado'),
('13427','COLEGIO LOS CONQUISTADORES','Coquimbo','MONTE PATRIA','Part. Subvencionado'),
('13428','ESCUELA BASICA SAN ISIDRO DE CUZ CUZ','Coquimbo','ILLAPEL','Corp. Municipal'),
('13434','COLEGIO SAN JOAQUIN','Coquimbo','LA SERENA','Part. Pagado'),
('13439','COLEGIO PUCARA','Coquimbo','OVALLE','Part. Subvencionado'),
('13442','COLEGIO SANTA FAMILIA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13445','COLEGIO ESPANOL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13446','MARIA EDUCA','Coquimbo','LA SERENA','Part. Subvencionado'),
('13450','COLEGIO ANDRES BELLO - PAMPA','Coquimbo','LA SERENA','Part. Pagado'),
('13451','JARDIN INFANTIL JESUS DE NAZARET','Coquimbo','LA SERENA','Part. Subvencionado'),
('13455','ESCUELA ESPECIAL ILLAPEL','Coquimbo','ILLAPEL','Corp. Municipal'),
('13461','LICEO CARMEN AURORA RODRIGUEZ HENRIQUEZ','Coquimbo','COQUIMBO','Servicio Local'),
('13462','COLEGIO CERRO GUAYAQUIL','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('13463','COLEGIO CARLOS CONDELL DE LA HAZA','Coquimbo','LA SERENA','Servicio Local'),
('13467','COLEGIO SANTA MARIA DEL REFUGIO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13469','JARDIN INFANTIL GRAN MOZART','Coquimbo','LA SERENA','Part. Subvencionado'),
('13471','ESC. ESPECIAL DE TRAN. DE LA COM. SANTA LUISA','Coquimbo','LA SERENA','Part. Subvencionado'),
('13474','COLEGIO LA MISION','Coquimbo','LA SERENA','Part. Subvencionado'),
('13475','COLEGIO SAN MARTIN DE PORRES','Coquimbo','LA SERENA','Part. Subvencionado'),
('13476','JARDIN INFANTIL EL MUNDO DE LOS PELUSITAS','Coquimbo','LA SERENA','Part. Pagado'),
('13478','JARDIN INFANTIL MI RINCON','Coquimbo','LA SERENA','Part. Pagado'),
('13479','ESCUELA ESPECIAL EL SENDERO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13480','ESCUELA ESPECIAL PALABRITAS','Coquimbo','OVALLE','Part. Subvencionado'),
('13481','ESCUELA ESPECIAL GALILEO','Coquimbo','OVALLE','Part. Subvencionado'),
('13482','ESC. ESPECIAL DE TRAST. DE LA COMUN. PLUMA D','Coquimbo','ILLAPEL','Part. Subvencionado'),
('13484','ESCUELA ESP. TRANS. DE LA COM. ENTREMUNDOS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13486','COLEGIO SAN FRANCISCO JAVIER','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13488','ESCUELA ESP. DE TRANS. DE LA COM. NUEVA BELEN','Coquimbo','LA SERENA','Part. Subvencionado'),
('13489','COLEGIO MARIA EDUCA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13491','COLEGIO ALTAZOR','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13493','ESCUELA DE LENGUAJE RENACER','Coquimbo','OVALLE','Part. Subvencionado'),
('13494','COLEGIO LA VILLA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('13498','ESCUELA BASICA ALTOS DE PECHEN','Coquimbo','PUNITAQUI','Corp. Municipal'),
('13499','ESC.ESP.DE TRANST. DE LA COM. CEDIN - TIERRA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13500','ESC.ESP.DE TRANST.DE LA COM. CUNA DE CONDORES','Coquimbo','ILLAPEL','Part. Subvencionado'),
('13501','JARDIN INFANTIL PUCARA','Coquimbo','COQUIMBO','Part. Pagado'),
('13503','COLEGIO VALENTIN LETELIER','Coquimbo','LA SERENA','Part. Subvencionado'),
('13504','COLEGIO SAN LORENZO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13505','ESC.ESP.DE TRANST.ESPEC. DE LENG. SAN SEBASTI','Coquimbo','SALAMANCA','Part. Subvencionado'),
('13506','COLEGIO AYELEN','Coquimbo','PUNITAQUI','Part. Subvencionado'),
('13510','ESC.ESP.DE TRANST. ESPEC. DEL LENGUAJE GUAYAS','Coquimbo','LA SERENA','Part. Subvencionado'),
('13512','COLEGIO JOAQUIN VICUÐA LARRAIN','Coquimbo','VICUÑA','Servicio Local'),
('13513','COLEGIO DALMACIA','Coquimbo','OVALLE','Part. Subvencionado'),
('13514','COLEGIO MARIA DE ANDACOLLO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13515','ESCUELA ESPECIAL Y LENGUAJE ROCIO','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('13517','ESCUELA ESPECIAL DE LENGUAJE SAN GUILLERMO','Coquimbo','VICUÑA','Part. Subvencionado'),
('13518','COLEGIO ARAUCO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13524','ESCUELA ESPECIAL ALCAZAR','Coquimbo','ILLAPEL','Part. Subvencionado'),
('13525','COLEGIO OLIMPO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13527','COLEGIO AGUILA MAYOR','Coquimbo','LA SERENA','Part. Pagado'),
('13528','COLEGIO ADULTOS SAN LUIS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13529','JARDIN INFANTIL EL BOSQUE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13530','ESC. DE TRAST. ESPECIFICOS DE LEGUAJE JOSE M','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13531','ESC. ESP.TRASTORNO LENGUAJE MANATI','Coquimbo','LOS VILOS','Part. Subvencionado'),
('13532','ESCUELA DE PARVULOS HAPPY KINDER','Coquimbo','OVALLE','Part. Subvencionado'),
('13534','ESC.ESP.DE TRAST.ESPECIFICOS DEL LENGUAJE AYE','Coquimbo','SALAMANCA','Part. Subvencionado'),
('13535','COLEGIO CERRO GRANDE','Coquimbo','LA SERENA','Part. Subvencionado'),
('13536','JARDIN INFANTIL SANTA ANNA','Coquimbo','COQUIMBO','Part. Pagado'),
('13538','JARDIN INFANTIL PARVUS','Coquimbo','OVALLE','Part. Subvencionado'),
('13539','ESCUELA LATINOAMERICA EDUCA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('13540','ESC.ESP.DE LENG.HABLA PALABRA NORTE','Coquimbo','OVALLE','Part. Subvencionado'),
('13541','ESCUELA ESPECIAL SANTA ELENA','Coquimbo','MONTE PATRIA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
