-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 11 de 31 | filas 4001-4400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('6545','ESCUELA PARTICULAR CHANGO','La Araucanía','CARAHUE','Part. Subvencionado'),
('6546','ESCUELA SAN CARLOS LLUFQUENTÚE','La Araucanía','GALVARINO','Part. Subvencionado'),
('6547','ESCUELA PARTICULAR CENTRO LONCOYAMO','La Araucanía','CARAHUE','Part. Subvencionado'),
('6549','ESCUELA PARTICULAR COLONIA LAS NOCHAS','La Araucanía','CARAHUE','Part. Subvencionado'),
('6550','ESCUELA PARTICULAR VISTA HERMOSA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6552','ESCUELA CODIHUE','La Araucanía','CARAHUE','Part. Subvencionado'),
('6553','ESCUELA PARTICULAR ALTO TIRUA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6555','ESCUELA PARTICULAR PILMAIQUENCO','La Araucanía','CARAHUE','Part. Subvencionado'),
('6560','ESCUELA PARTICULAR EL AMANECER','La Araucanía','CARAHUE','Part. Subvencionado'),
('6562','ESCUELA PARTICULAR LA ALBORADA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6564','ESCUELA PARTIC.JOSE MIGUEL CARRERA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6566','ESCUELA PARTICULAR JAVIERA CARRERA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6567','ESCUELA PARTICULAR JOSE ABELARDO NUNEZ','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6569','ESCUELA PARTICULAR LUIS CRUZ MARTINEZ','La Araucanía','CARAHUE','Part. Subvencionado'),
('6570','ESCUELA PARTICULAR PEDRO DE VALDIVIA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6572','ESCUELA PARTICULAR RAMON FREIRE','La Araucanía','CARAHUE','Part. Subvencionado'),
('6575','ESCUELA PARTICULAR ALONSO DE ERCILLA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6576','ESCUELA PARTICULAR CLAUDIO MATTE','La Araucanía','CARAHUE','Part. Subvencionado'),
('6577','COLEGIO DREAM HOUSE','La Araucanía','CARAHUE','Part. Subvencionado'),
('6578','ESCUELA PARTICULAR LA MONTANA','La Araucanía','CARAHUE','Part. Subvencionado'),
('6580','ESCUELA PARTICULAR CAMILO HENRIQUEZ','La Araucanía','CARAHUE','Part. Subvencionado'),
('6583','ESCUELA PARTICULAR RUCATRARO','La Araucanía','CARAHUE','Part. Subvencionado'),
('6584','LICEO INDUSTRIAL C-16 NUEVA IMPERIAL','La Araucanía','NUEVA IMPERIAL','Adm. Delegada'),
('6585','LICEO BICENTENARIO LUIS GONZALEZ VASQUEZ 6585-4','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6586','LICEO BICENTENARIO JAMES MUNDELL','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6587','ESCUELA ALEJANDRO GOROSTIAGA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6588','ESCUELA REPUBLICA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6589','ESCUELA JUAN XXIII','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6590','ESCUELA PÚBLICA AVANCEMOS JUNTOS','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6591','FEDERICO GARC-A LORCA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6593','ESCUELA BASICA EL CRUCERO','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6594','ESCUELA BASICA LOS AVELLANOS','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6595','ESCUELA BASICA RAYEN RUNGI','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6599','ESCUELA BASICA COIHUE CURACO','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6600','ESCUELA EL COPIHUAL','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6602','ESCUELA BASICA CATRIANCHE','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6604','ESCUELA LOS CARRERA','La Araucanía','LAUTARO','Corp. Municipal'),
('6605','ESC.BASICA RAYEN MAHUIDA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6608','ESC. BASICA LA ARAUCARIA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6611','ESC. BASICA CHIVILCOYAN','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6612','ESC. BASICA PICHIRAYEN','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6616','ESC. BASICA SANTA CAROLINA','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6621','ESC. BASICA MALALCHE BAJO','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6622','ESC. BASICA CAMPANARIO','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6623','ESCUELA ARENAS BLANCAS','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6624','ESC. BASICA EL PROGRESO','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6625','ESC. BASICA LOS CANELOS','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6626','ESC. BASICA RUCAPANGUE','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6627','ESC. BASICA ALTAMIRA','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6628','ESC. BASICA LIFKO','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6630','ESC. BASICA NUEVA AURORA','La Araucanía','CHOLCHOL','Corp. Municipal'),
('6633','ESC. BASICA SANTA MARIA DE BOROA','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6635','ESC. BASICA LOS ROBLES','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6639','ESCUELA BASICA MANIO DUCANAN','La Araucanía','NUEVA IMPERIAL','Servicio Local'),
('6641','LICEO AGRICOLA CHOL CHOL','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6643','LICEO INTERCULTURAL TÉCNICO PROFESIONAL GUACOLDA','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6644','LICEO SAN FCO DE ASIS DE NVA IMPERIAL','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6649','LICEO SAN FRANCISCO DE ASIS DE CHOL CHOL','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6650','COLEGIO ANGLICANO WILLIAM WILSON','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6652','ESCUELA PARTICULAR BOROA','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6653','ESCUELA PARTICULAR COILACO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6654','ESCUELA PARTICULAR ENTRE RIOS','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6656','ESCUELA PARTICULAR LOS GUINDOS','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6662','ESCUELA PARTICULAR LOMA LARGA','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6666','ESCUELA PARTICULAR ALMAGRO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6667','ESCUELA PARTICULAR RULO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6668','ESCUELA PARTICULAR COPINCHE','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6669','ESCUELA PARTICULAR DOLLIMCO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6670','ESCUELA PARTICULAR HUEICO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6671','ESCUELA PARTICULAR RENACO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6673','ESCUELA PARTICULAR PUEL MAPU','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6674','ESCUELA PARTICULAR ALTO MANIO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6678','ESCUELA PARTICULAR SANTA MARIA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6679','ESCUELA PARTICULAR PIUHUICHEN','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6684','ESCUELA PARTICULAR SAN ANTONIO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6686','ESCUELA PARTICULAR LIDIA RIQUELME','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6688','ESCUELA PARTICULAR TRANAMIL RULO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6690','ESCUELA PARTICULAR PEDRO AGUIRRE CERDA','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6691','ESCUELA PARTICULAR GABRIELA MISTRAL','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6692','ESCUELA PARTICULAR ARTURO PRAT','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6695','ESCUELA PARTICULAR FAIZI','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6699','ESCUELA PARTICULAR AMBROSIO OHIGGINS','La Araucanía','VILCÚN','Part. Subvencionado'),
('6700','ESCUELA PARTICULAR TRAYENCO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6701','ESCUELA PARTICULAR ANIBAL PINTO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6702','ESCUELA PARTICULAR INES DE SUAREZ','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6705','ESCUELA PARTICULAR PROF.NIMIA RIVAS','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('6708','LICEO GREGORIO URRUTIA','La Araucanía','GALVARINO','Corp. Municipal'),
('6709','ESCUELA MUNICIPAL RIO QUILLEN','La Araucanía','GALVARINO','Corp. Municipal'),
('6710','ESCUELA BASICA DE LA PIEDRA','La Araucanía','GALVARINO','Corp. Municipal'),
('6711','ESCUELA BASICA MANIUCO','La Araucanía','GALVARINO','Corp. Municipal'),
('6712','ESCUELA SAN JUAN DE AILLINCO','La Araucanía','GALVARINO','Corp. Municipal'),
('6714','ESCUELA MUNICIPAL DE LLUQUENTUE','La Araucanía','GALVARINO','Corp. Municipal'),
('6715','ESCUELA BASICA TRABUNQUILLEM','La Araucanía','GALVARINO','Corp. Municipal'),
('6716','ESC. BASICA QUETRE','La Araucanía','GALVARINO','Corp. Municipal'),
('6718','ESCUELA BASICA DE EL CAPRICHO','La Araucanía','GALVARINO','Corp. Municipal'),
('6719','ESCUELA BASICA CHACAICO','La Araucanía','GALVARINO','Corp. Municipal'),
('6721','ESCUELA REDUCCION PANGUECO','La Araucanía','GALVARINO','Corp. Municipal'),
('6722','ESCUELA BASICA QUINAHUE','La Araucanía','GALVARINO','Corp. Municipal'),
('6725','ESCUELA DE HUAMPOMALLIN','La Araucanía','GALVARINO','Corp. Municipal'),
('6726','ESCUELA BASICA SANTA MARGARITA','La Araucanía','GALVARINO','Corp. Municipal'),
('6728','ESCUELA BASICA TRIF TRIFCO','La Araucanía','GALVARINO','Corp. Municipal'),
('6731','ESCUELA BASICA PELANTARO','La Araucanía','GALVARINO','Corp. Municipal'),
('6732','ESC. BASICA FORTIN NIELOL','La Araucanía','GALVARINO','Corp. Municipal'),
('6734','ESCUELA PARTICULAR SAN SEBASTIAN','La Araucanía','GALVARINO','Part. Subvencionado'),
('6735','ESCUELA PARTICULAR ADVENTISTA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6736','ESCUELA PARTICULAR RAPA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6737','ESCUELA PARTICULAR PAILLAHUE','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('6738','ESCUELA PARTICULAR REPOCURA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6739','ESCUELA MUNICIPAL NILPE','La Araucanía','GALVARINO','Corp. Municipal'),
('6741','ESCUELA PARTICULAR EL PROGRESO','La Araucanía','GALVARINO','Part. Subvencionado'),
('6743','ESCUELA PARTICULAR RENICURA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6745','ESCUELA PARTICULAR BELLAVISTA','La Araucanía','GALVARINO','Part. Subvencionado'),
('6747','ESCUELA PARTICULAR EL PERAL','La Araucanía','GALVARINO','Part. Subvencionado'),
('6748','ESCUELA PARTICULAR EL JARDIN','La Araucanía','GALVARINO','Part. Subvencionado'),
('6750','ESCUELA LLOLLETUE','La Araucanía','TEMUCO','Part. Subvencionado'),
('6751','INSTITUTO COMERCIAL DE VALDIVIA','Los Ríos','VALDIVIA','Servicio Local'),
('6752','LICEO TECNICO VALDIVIA','Los Ríos','VALDIVIA','Servicio Local'),
('6753','LICEO SANTA MARIA LA BLANCA','Los Ríos','VALDIVIA','Servicio Local'),
('6754','LICEO ARMANDO ROBLES RIVERA','Los Ríos','VALDIVIA','Servicio Local'),
('6755','LICEO INDUSTRIAL VALDIVIA','Los Ríos','VALDIVIA','Servicio Local'),
('6757','INSTITUTO DE RECURSOS RENOVABLES Y TECNOLOGÍA LOS RÍOS','Los Ríos','VALDIVIA','Servicio Local'),
('6759','ESCUELA CHILE','Los Ríos','VALDIVIA','Servicio Local'),
('6762','ESCUELA MEXICO','Los Ríos','VALDIVIA','Servicio Local'),
('6764','ESCUELA ESPANA','Los Ríos','VALDIVIA','Servicio Local'),
('6765','COLEGIO DEPORTIVO MUNICIPAL DE VALDIVIA','Los Ríos','VALDIVIA','Servicio Local'),
('6766','COLEGIO TENIENTE HERNAN MERINO CORREA','Los Ríos','VALDIVIA','Servicio Local'),
('6767','ESCUELA LEONARDO DA VINCI','Los Ríos','VALDIVIA','Servicio Local'),
('6768','ESCUELA DIFERENCIAL ANN SULLIVAN','Los Ríos','VALDIVIA','Servicio Local'),
('6770','COLEGIO BICENTENARIO DE MUSICA JUAN SEBASTIAN BACH','Los Ríos','VALDIVIA','Servicio Local'),
('6772','C.E.I.A. NARCISO GARCIA BARRIA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('6773','ESCUELA LAS ANIMAS','Los Ríos','VALDIVIA','Servicio Local'),
('6774','ESCUELA EL LAUREL','Los Ríos','VALDIVIA','Servicio Local'),
('6777','ESCUELA FEDOR M.DOSTOIEVSKI','Los Ríos','VALDIVIA','Servicio Local'),
('6780','ESCUELA FERNANDO SANTIVAN','Los Ríos','VALDIVIA','Servicio Local'),
('6781','ESCUELA ALEMANIA','Los Ríos','VALDIVIA','Servicio Local'),
('6785','ESCUELA ANGACHILLA','Los Ríos','VALDIVIA','Servicio Local'),
('6786','ESCUELA ESPECIAL WALTER SCHMIDT ROESTEL','Los Ríos','VALDIVIA','Servicio Local'),
('6787','CENTRO EDUC.ADULTOS LUIS MOLL BRIONES','Los Ríos','VALDIVIA','Servicio Local'),
('6791','ESCUELA DE NIEBLA JUAN BOSCH','Los Ríos','VALDIVIA','Servicio Local'),
('6793','ESCUELA RURAL HUELLELHUE','Los Ríos','VALDIVIA','Servicio Local'),
('6797','ESCUELA RURAL CURINANCO','Los Ríos','VALDIVIA','Servicio Local'),
('6798','ESCUELA RURAL PUNUCAPA','Los Ríos','VALDIVIA','Servicio Local'),
('6803','ESCUELA RURAL CASA BLANCA','Los Ríos','VALDIVIA','Servicio Local'),
('6804','ESCUELA RURAL LOS GUINDOS','Los Ríos','VALDIVIA','Servicio Local'),
('6805','ESCUELA RURAL SANTO DOMINGO','Los Ríos','VALDIVIA','Servicio Local'),
('6807','ESCUELA RURAL PISHUINCO','Los Ríos','VALDIVIA','Servicio Local'),
('6814','ESCUELA RURAL MISION DE ARIQUE','Los Ríos','VALDIVIA','Servicio Local'),
('6815','ESCUELA RURAL LOS MOLINOS','Los Ríos','VALDIVIA','Servicio Local'),
('6816','ESCUELA RURAL CAYUMAPU','Los Ríos','VALDIVIA','Servicio Local'),
('6817','ESCUELA RURAL ANDRES FRIED KOPP','Los Ríos','VALDIVIA','Servicio Local'),
('6818','ESCUELA RURAL LOS PELLINES','Los Ríos','VALDIVIA','Servicio Local'),
('6826','COLEGIO SANTA MARTA DE VALDIVIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6828','COLEGIO AUSTRAL','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6829','INSTITUTO SALESIANO','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6830','COLEGIO NUESTRA SENORA DEL CARMEN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6832','COLEGIO MARIA AUXILIADORA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6833','INSTITUTO EDUCACIONAL COLLICO','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6834','COLEGIO METODISTA LA TRINIDAD','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6835','COLEGIO ADVENTISTA DE VALDIVIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6836','COLEGIO ALONSO DE ERCILLA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6841','COLEGIO VALLE DE LOS RIOS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('6843','COLEGIO WINDSOR SCHOOL','Los Ríos','VALDIVIA','Part. Pagado'),
('6844','INSTITUTO ALEMAN CARLOS ANWANDTER','Los Ríos','VALDIVIA','Part. Pagado'),
('6846','LICEO SAN LUIS DE ALBA','Los Ríos','MARIQUINA','Servicio Local'),
('6848','ESCUELA PARTICULAR EL BOSQUE','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('6852','COLEGIO PELCHUQUIN','Los Ríos','MARIQUINA','Servicio Local'),
('6853','LICEO POLITECNICO PESQUERO','Los Ríos','MARIQUINA','Servicio Local'),
('6855','ESCUELA RURAL MAIQUILLAHUE','Los Ríos','MARIQUINA','Servicio Local'),
('6857','ESCUELA RURAL MISSISSIPPI','Los Ríos','MARIQUINA','Servicio Local'),
('6865','ESCUELA RURAL HUIFCO','Los Ríos','MARIQUINA','Servicio Local'),
('6866','ESCUELA RURAL ALFONSO OSSES PEREZ','Los Ríos','MARIQUINA','Servicio Local'),
('6867','ESC.RURAL JORGE ROBERTO FONTANNAZ BLUAS','Los Ríos','MARIQUINA','Servicio Local'),
('6868','ESCUELA RURAL INIPULLI','Los Ríos','MARIQUINA','Corp. Municipal'),
('6876','ESCUELA FRAY BERNABE DE LUCERNA','Los Ríos','MARIQUINA','Servicio Local'),
('6877','ESCUELA RURAL OSVALDO FERNANDEZ V.','Los Ríos','MARIQUINA','Servicio Local'),
('6878','ESCUELA RURAL PAILLACO','Los Ríos','MARIQUINA','Servicio Local'),
('6882','ESCUELA RURAL LINGUENTO','Los Ríos','MARIQUINA','Servicio Local'),
('6884','ESCUELA RURAL FLORA MARTIN IMIGO','Los Ríos','MARIQUINA','Servicio Local'),
('6886','ESCUELA VALLE DE MARIQUINA','Los Ríos','MARIQUINA','Servicio Local'),
('6891','ESC.RURAL JUAN POBLETE SAINT-SIMON','Los Ríos','MARIQUINA','Servicio Local'),
('6893','ESCUELA RURAL TRALCAO','Los Ríos','MARIQUINA','Corp. Municipal'),
('6895','LICEO BICENTENARIO SANTA CRUZ','Los Ríos','MARIQUINA','Part. Subvencionado'),
('6896','SEMINARIO SAN FIDEL','Los Ríos','MARIQUINA','Part. Subvencionado'),
('6897','LICEO BICENTENERIO DE EXCELENCIA CAMILO HENRIQUEZ GONZALEZ DE LANCO.','Los Ríos','LANCO','Servicio Local'),
('6898','ESCUELA FELIPE BARTHOU CORBEAUX','Los Ríos','LANCO','Servicio Local'),
('6899','LICEO REPUBLICA DEL BRASIL','Los Ríos','LANCO','Servicio Local'),
('6901','ESCUELA RURAL REDUCCION ANTILHUE','Los Ríos','LANCO','Servicio Local'),
('6902','ESCUELA RURAL RUCAKLEN','Los Ríos','LANCO','Servicio Local'),
('6903','ESCUELA RURAL PUQUINE BAJO','Los Ríos','LANCO','Servicio Local'),
('6905','ESCUELA RURAL AYLIN','Los Ríos','LANCO','Servicio Local'),
('6916','ESCUELA ALBERTO CORDOVA LATORRE','Los Ríos','LANCO','Servicio Local'),
('6917','ESCUELA PARTICULAR PADRE CARLOS','Los Ríos','LANCO','Part. Subvencionado'),
('6918','ESCUELA PARTICULAR SAN FRANCISCO','Los Ríos','LANCO','Part. Subvencionado'),
('6920','ESCUELA PARTICULAR GUIDO BECK','Los Ríos','LANCO','Part. Subvencionado'),
('6922','LICEO PADRE ALCUINO','Los Ríos','LANCO','Part. Subvencionado'),
('6925','COLEGIO MARIA REINA','Los Ríos','LANCO','Part. Subvencionado'),
('6929','LICEO BICENTENARIO ALBERTO BLEST GANA','Los Ríos','LOS LAGOS','Servicio Local'),
('6930','ESCUELA FRANCIA','Los Ríos','LOS LAGOS','Servicio Local'),
('6932','ESCUELA NEVADA','Los Ríos','LOS LAGOS','Servicio Local'),
('6933','ESCUELA RURAL FOLILCO','Los Ríos','LOS LAGOS','Servicio Local'),
('6934','ESCUELA NUEVA ESPANA','Los Ríos','LOS LAGOS','Servicio Local'),
('6935','ESCUELA RURAL ANTILHUE','Los Ríos','LOS LAGOS','Servicio Local'),
('6938','ESCUELA RURAL CHANCO','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6941','ESCUELA RURAL EL VERGEL','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6942','ESCUELA RURAL EL TREBOL','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6944','ESCUELA RURAL USTARITZ','Los Ríos','LOS LAGOS','Servicio Local'),
('6945','ESCUELA RURAL LOS BAJOS','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6946','ESCUELA RURAL COMUNIDAD STA CARLA','Los Ríos','LOS LAGOS','Servicio Local'),
('6950','ESCUELA RURAL LAS HUELLAS','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6951','ESCUELA RURAL LA VICTORIA','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6953','ESCUELA RURAL EL SALTO','Los Ríos','LOS LAGOS','Servicio Local'),
('6955','ESCUELA RURAL ENRIQUE HEVIA LABBE','Los Ríos','LOS LAGOS','Servicio Local'),
('6956','ESCUELA RURAL ALICIA MERA OVALLE','Los Ríos','LOS LAGOS','Servicio Local'),
('6957','ESCUELA RURAL TRAFUN','Los Ríos','LOS LAGOS','Corp. Municipal'),
('6963','ESCUELA CENTROS UNIDOS SAN JUAN','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6964','ESCUELA PARTICULAR LOS MAITENES','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6965','ESCUELA PARTICULAR HUAIQUIMILLA','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6969','ESCUELA PARTICULAR EL FAROL','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6970','ESCUELA PARTICULAR PATAGONIA','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6972','ESCUELA COLEGUAL NUM.32','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6975','ESCUELA PARTICULAR COVADONGA','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6978','ESCUELA PARTICULAR SANTA ANA','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6982','ESCUELA PARTICULAR MI TIERRA','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('6983','COLEGIO JOSE MANUEL BALMACEDA FÉRNANDEZ','Los Ríos','FUTRONO','Corp. Municipal'),
('6984','ESCUELA RURAL NONTUELA','Los Ríos','FUTRONO','Corp. Municipal'),
('6986','ESCUELA FRONTERIZA DE LLIFEN','Los Ríos','FUTRONO','Corp. Municipal'),
('6988','ESCUELA RURAL LONCOPAN BAJO','Los Ríos','FUTRONO','Corp. Municipal'),
('6989','ESCUELA RURAL LOS CERRILLOS','Los Ríos','FUTRONO','Corp. Municipal'),
('6990','ESCUELA RURAL EL LLOLLY','Los Ríos','PAILLACO','Servicio Local'),
('6991','ESCUELA RURAL ISLA HUAPI','Los Ríos','FUTRONO','Corp. Municipal'),
('6992','ESCUELA RURAL VISTA HERMOSA','Los Ríos','FUTRONO','Corp. Municipal'),
('6996','ESCUELA RURAL PUMOL','Los Ríos','FUTRONO','Corp. Municipal'),
('7000','ESCUELA RURAL HUEINAHUE','Los Ríos','FUTRONO','Corp. Municipal'),
('7003','ESCUELA RURAL CURRINE','Los Ríos','FUTRONO','Corp. Municipal'),
('7004','COLEGIO MARIA DEOGRACIA','Los Ríos','FUTRONO','Part. Subvencionado'),
('7006','LICEO SAN CONRADO DE FUTRONO','Los Ríos','FUTRONO','Part. Subvencionado'),
('7009','ESCUELA PARTICULAR CHOLLINCO','Los Ríos','FUTRONO','Part. Subvencionado'),
('7011','ESCUELA PARTICULAR CHIHUIO','Los Ríos','FUTRONO','Part. Subvencionado'),
('7013','ESCUELA PARTICULAR NONTUELA ALTO','Los Ríos','FUTRONO','Part. Subvencionado'),
('7015','LICEO BICENTENARIO DE EXCELENCIA CARLOS HAVERBECK RICHTER','Los Ríos','CORRAL','Servicio Local'),
('7016','ESCUELA BASICA DE CORRAL','Los Ríos','CORRAL','Servicio Local'),
('7018','ESCUELA RURAL TRES CHIFLONES ALTO','Los Ríos','CORRAL','Servicio Local'),
('7020','ESCUELA RURAL CARBONEROS','Los Ríos','CORRAL','Servicio Local'),
('7023','ESCUELA RURAL LA AGUADA','Los Ríos','CORRAL','Servicio Local'),
('7024','ESCUELA RURAL SAN CARLOS','Los Ríos','CORRAL','Servicio Local'),
('7025','ESCUELA RURAL EL HUAPE','Los Ríos','CORRAL','Servicio Local'),
('7026','ESCUELA RURAL CHAIHUIN','Los Ríos','CORRAL','Servicio Local'),
('7030','ESCUELA RURAL LAS COLORADAS','Los Ríos','CORRAL','Servicio Local'),
('7031','LICEO BICENTENARIO GABRIELA MISTRAL','Los Ríos','MÁFIL','Servicio Local'),
('7032','ESCUELA ARTÍSTICA ALABAMA','Los Ríos','MÁFIL','Servicio Local'),
('7037','ESCUELA RURAL SANTA HIGIDIA','Los Ríos','MÁFIL','Servicio Local'),
('7038','ESCUELA RURAL HUILLICOIHUE','Los Ríos','MÁFIL','Servicio Local'),
('7039','ESCUELA RURAL ENRIQUE TALADRIZ','Los Ríos','MÁFIL','Servicio Local'),
('7040','ESCUELA RURAL RUNCA','Los Ríos','MÁFIL','Servicio Local'),
('7044','LICEO SANTO CURA DE ARS','Los Ríos','MÁFIL','Part. Subvencionado'),
('7049','CENTRO EDUCATIVO FERNANDO SANTIVAN','Los Ríos','PANGUIPULLI','Servicio Local'),
('7050','ESCUELA MARIA ALVARADO GARAY','Los Ríos','PANGUIPULLI','Servicio Local'),
('7051','ESCUELA RURAL PANGUILELFUN','Los Ríos','PANGUIPULLI','Servicio Local'),
('7057','ESCUELA RURAL PITREN','Los Ríos','PANGUIPULLI','Servicio Local'),
('7058','ESCUELA RURAL HUITAG','Los Ríos','PANGUIPULLI','Servicio Local'),
('7059','ESCUELA MANUEL ANABALÓN SÁEZ','Los Ríos','PANGUIPULLI','Servicio Local'),
('7061','ESCUELA RURAL LA RINCONADA','Los Ríos','PANGUIPULLI','Servicio Local'),
('7062','ESCUELA RURAL PULLINQUE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7063','ESCUELA RURAL HUELLAHUE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7064','ESCUELA BASICA REPUBLICA DE CHILE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7065','ESCUELA RURAL EL MANZANO','Los Ríos','PANGUIPULLI','Servicio Local'),
('7069','ESCUELA RURAL COZ COZ','Los Ríos','PANGUIPULLI','Servicio Local'),
('7071','ESCUELA RURAL LAGO AZUL','Los Ríos','PANGUIPULLI','Servicio Local'),
('7072','ESCUELA RURAL LLANCAHUE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7074','ESCUELA RURAL CACIQUE AILLAPAN','Los Ríos','PANGUIPULLI','Servicio Local'),
('7076','ESCUELA ESTADIO','La Araucanía','VILLARRICA','Corp. Municipal'),
('7077','ESCUELA ALIHUEN','La Araucanía','VILLARRICA','Corp. Municipal'),
('7078','ESCUELA RURAL CARRIRINE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7079','ESCUELA RURAL MALCHEHUE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7083','ESCUELA RURAL BOCATOMA','Los Ríos','PANGUIPULLI','Servicio Local'),
('7085','COMPLEJO EDUCACIONAL TIERRA DE ESPERANZA','Los Ríos','PANGUIPULLI','Servicio Local'),
('7086','ESCUELA RURAL COIHUECO','Los Ríos','PANGUIPULLI','Servicio Local'),
('7088','ESCUELA RURAL CAYUMAPU','Los Ríos','PANGUIPULLI','Servicio Local'),
('7089','ESCUELA RURAL LAGO NELTUME','Los Ríos','PANGUIPULLI','Servicio Local'),
('7090','ESCUELA RURAL PUNAHUE','Los Ríos','PANGUIPULLI','Servicio Local'),
('7092','ESCUELA RURAL REHUEICO','Los Ríos','PANGUIPULLI','Servicio Local'),
('7095','ESCUELA RURAL MILLEUCO','Los Ríos','PANGUIPULLI','Servicio Local'),
('7100','ESCUELA RURAL LLONQUEN','Los Ríos','PANGUIPULLI','Servicio Local'),
('7101','ESCUELA RURAL CACHIM','Los Ríos','PANGUIPULLI','Servicio Local'),
('7102','LICEO PADRE SIGISFREDO','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7108','ESCUELA PART. PADRE ENRIQUE ROMER','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7109','ESCUELA PARTICULAR PELEHUE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7111','ESCUELA PARTICULAR PUCURA','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7112','ESCUELA PARTICULAR PAMPA NANCUL','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7113','ESCUELA PARTICULAR LIQUINE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7114','ESCUELA FRANCISCO DE ASIS','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7115','ESCUELA PARTICULAR NUEVA LIQUINE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7116','ESCUELA PARTICULAR EL PORVENIR','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7118','ESCUELA PARTICULAR TRAITRAICO','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7122','COL. DE ARTES, CIENCIA Y TEC. DA VINCI','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7123','ESCUELA PARTICULAR TRELEHUENO','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7125','ESCUELA PARTICULAR PADRE BERGER','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('7128','COLEGIO DE CULTURA Y DIFUSION ARTISTICA','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7129','LICEO BICENTENARIO RECTOR ABDON ANDRADE COLOMA','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7130','ESCUELA LA UNION','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7131','ESCUELA PRESIDENTE JORGE ALESSANDRI R.','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7132','ESC.DIFERENC.VILLA SAN JOSE DE LA UNION','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7133','ESCUELA RADIMADI','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7135','COLEGIO TECNICO PROFESIONAL N°1 HONORIO OJEDA VALDERAS','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7136','ESCUELA RURAL CATAMUTUN','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7137','ESCUELA RURAL CHOROICO','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7138','ESCUELA RURAL PUERTO NUEVO','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7140','ESCUELA RURAL LOS ESTEROS','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7141','ESCUELA RURAL FOLLECO','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7142','ESCUELA RURAL CUINCO','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7147','ESCUELA RURAL HUILLINCO','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7157','ESCUELA RURAL TRAIGUEN','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7158','ESCUELA RURAL CARIMANCA','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7160','ESCUELA RURAL FLOR M. MUNDACA H.','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7166','ESCUELA ALDEA CAMPESINA','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7168','ESCUELA RURAL LLANCACURA','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7170','ESCUELA RURAL MASHUE','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7172','ESCUELA RURAL PILPILCAHUIN','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7173','ESCUELA RURAL EL HUAPE','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7174','ESCUELA RURAL LOS CHILCOS','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7178','ESCUELA RURAL HUACAHUE','Los Ríos','LA UNIÓN','Corp. Municipal'),
('7180','COLEGIO ALEMAN R.A. PHILIPPI','Los Ríos','LA UNIÓN','Part. Pagado'),
('7181','COLEGIO SANTA MARTA','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7183','COLEGIO PADRE DAMIAN','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7184','ESCUELA PARTICULAR CAMPO LINDO','Los Ríos','PAILLACO','Part. Subvencionado'),
('7185','ESCUELA PARTICULAR LOS AVELLANOS','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7186','ESCUELA PARTICULAR MONTES AZULES','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7188','ESCUELA PARTICULAR TRES VENTANAS','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7192','ESCUELA PARTICULAR PUMAIHUE','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7193','ESCUELA PARTICULAR LAGO VERDE','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('7200','LICEO RODULFO AMANDO PHILIPPI','Los Ríos','PAILLACO','Servicio Local'),
('7202','COLEGIO PROYECTO DE FUTURO','Los Ríos','PAILLACO','Servicio Local'),
('7203','ESCUELA OLEGARIO MORALES OLIVA','Los Ríos','PAILLACO','Servicio Local'),
('7204','ESCUELA NUEVA AURORA','Los Ríos','PAILLACO','Servicio Local'),
('7205','ESCUELA ROBERTO OJEDA TORRES','Los Ríos','PAILLACO','Servicio Local'),
('7206','ESCUELA RURAL 21 DE MAYO','Los Ríos','PAILLACO','Servicio Local'),
('7212','ESCUELA RURAL EL NARANJO','Los Ríos','PAILLACO','Servicio Local'),
('7214','ESCUELA RURAL MANAO','Los Ríos','PAILLACO','Servicio Local'),
('7217','ESCUELA RURAL ESTRELLA DE CHILE','Los Ríos','PAILLACO','Servicio Local'),
('7220','ESCUELA RURAL LA PENA','Los Ríos','PAILLACO','Servicio Local'),
('7225','ESCUELA RURAL EDUVIGES SCHULZ DE MOHR','Los Ríos','PAILLACO','Servicio Local'),
('7231','ESCUELA PARTICULAR ALEMANA','Los Ríos','PAILLACO','Part. Subvencionado'),
('7234','ESCUELA PADRE ALEJANDRO CORCUERA MARTINEZ','Los Ríos','PAILLACO','Part. Subvencionado'),
('7236','LICEO BICENTENARIO VICENTE PÉREZ ROSALES','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7237','ESCUELA BASICA RIO BUENO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7238','ESCUELA BASICA PATRICIO LYNCH','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7239','ESCUELA BASICA SAN JOSE DE FILUCO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7240','COLEGIO BICENTENARIO CRUCERO OSCAR DANIEL','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7242','ESCUELA RURAL VIVANCO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7243','ESCUELA RURAL CARIMALLIN BAJO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7244','ESCUELA RURAL COLONIA DIUMEN','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7249','ESCUELA RURAL TIQUECO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7250','ESCUELA RURAL VALLE MANTILHUE BAJO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7252','ESCUELA RURAL MANTILHUE ALTO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7253','ESCUELA RURAL CURRALHUE GRANDE','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7256','ESCUELA RURAL FOLILCO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7257','ESCUELA RURAL FUTAHUENTE','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7260','ESCUELA RURAL CHAMPULLI','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7261','ESCUELA RURAL CHIRRE','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7262','ESCUELA RURAL PISU-PISUE','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7266','ESCUELA RURAL TRAPI','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7268','ESCUELA RURAL CURRALHUE CHICO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7273','ESCUELA RURAL EL ARRAYAN','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7276','COLEGIO SANTA CRUZ','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7279','ESCUELA PART LA AGUADA','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7282','ESCUELA PARTICULAR NUEVA LUMACO','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7284','ESCUELA PARTICULAR NUEVA PINDACO','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7285','ESCUELA PARTICULAR BOQUIAL','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7288','ESCUELA CHISCAIHUE','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7290','ESCUELA PARTICULAR TREHUACO','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7296','ESCUELA PARTICULAR LOS AZADORES','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7297','ESCUELA RURAL SANTA ISABEL','Los Ríos','RÍO BUENO','Corp. Municipal'),
('7298','ESCUELA PARTICULAR EL RADAL','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('7299','LICEO ANTONIO VARAS','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7301','ESCUELA RURAL ILIHUE','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7302','ESCUELA RURAL PITRENO','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7303','ESCUELA RURAL RININAHUE','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7304','ESCUELA RURAL CALCURRUPE','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7305','ESCUELA RURAL ILLAHUAPI','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7306','ESCUELA RURAL QUILLIN','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7307','ESCUELA RURAL LA ENSENADA','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7308','ESCUELA RURAL LA JUNTA','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7309','ESCUELA RURAL PITRIUCO','Los Ríos','LAGO RANCO','Corp. Municipal'),
('7312','ESCUELA PARTICULAR CARRAN','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('7314','ESCUELA PARTICULAR LOS GUINDOS','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('7315','ESCUELA PARTICULAR RUPUMEICA','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('7316','ESCUELA PARTICULAR POCURA','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('7318','ESCUELA PARTICULAR HUEIMEN','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('7321','ESCUELA PARTICULAR SAN SEBASTIÁN DE CHANCOYAN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('7323','COLEGIO INTI SUYAY','Los Lagos','OSORNO','Corp. Municipal'),
('7325','LICEO CARMELA CARVAJAL DE PRAT','Los Lagos','OSORNO','Corp. Municipal'),
('7326','LICEO INDUSTRIAL OSORNO','Los Lagos','OSORNO','Corp. Municipal'),
('7328','LICEO RAHUE','Los Lagos','OSORNO','Corp. Municipal'),
('7329','LICEO BICENTENARIO DE EXCELENCIA ELEUTERIO RAMIREZ','Los Lagos','OSORNO','Corp. Municipal'),
('7331','LICEO BICENTENARIO DE EXCELENCIA INSTITUTO COMERCIAL DE OSORNO','Los Lagos','OSORNO','Corp. Municipal'),
('7332','ESCUELA JUAN RICARDO SANCHEZ ASCENCIO','Los Lagos','OSORNO','Corp. Municipal'),
('7333','ESCUELA ESPAÑA','Los Lagos','OSORNO','Corp. Municipal'),
('7334','ESCUELA EFRAIN CAMPANA SILVA','Los Lagos','OSORNO','Corp. Municipal'),
('7335','ESCUELA SUIZA','Los Lagos','OSORNO','Corp. Municipal'),
('7336','ESCUELA FUNDACION PAUL HARRIS','Los Lagos','OSORNO','Corp. Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
