-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 6 de 31 | filas 2001-2400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('3067','ESCUELA LEOPOLDO GUARDA GEYNTES','Maule','SAN CLEMENTE','Corp. Municipal'),
('3068','ESCUELA BELLA UNION','Maule','SAN CLEMENTE','Corp. Municipal'),
('3069','ESCUELA QUERI','Maule','SAN CLEMENTE','Corp. Municipal'),
('3070','ESCUELA CHEQUEN DE LA PENA','Maule','SAN CLEMENTE','Corp. Municipal'),
('3073','ESCUELA BAJO LIRCAY','Maule','SAN CLEMENTE','Corp. Municipal'),
('3076','ESCUELA BRAMADERO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3077','ESCUELA COREL','Maule','SAN CLEMENTE','Corp. Municipal'),
('3079','ESCUELA ELENA BURGOS MOREIRA','Maule','SAN CLEMENTE','Corp. Municipal'),
('3081','ESCUELA BAJO PERQUIN','Maule','SAN CLEMENTE','Corp. Municipal'),
('3082','ESCUELA SAN DIEGO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3084','ESCUELA LOS ROBLES DE VILCHES CENTRO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3085','ESCUELA PASO NEVADO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3086','ESCUELA LOS MONTES','Maule','SAN CLEMENTE','Corp. Municipal'),
('3088','ESCUELA VILCHES ALTO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3090','ESCUELA EL COLORADO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3092','ESCUELA NACIONES UNIDAS','Maule','SAN CLEMENTE','Corp. Municipal'),
('3093','ESCUELA CARRETONES','Maule','SAN CLEMENTE','Corp. Municipal'),
('3096','ESCUELA LOS ALMENDROS','Maule','SAN CLEMENTE','Corp. Municipal'),
('3104','ESCUELA LA PLACETA','Maule','SAN CLEMENTE','Corp. Municipal'),
('3106','ESCUELA FLOR DEL LLANO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3107','ESCUELA SANTA ELENA','Maule','SAN CLEMENTE','Corp. Municipal'),
('3108','COLEGIO PAULA MONTAL','Maule','SAN CLEMENTE','Part. Subvencionado'),
('3110','COMPLEJO EDUCACIONAL MAULE','Maule','MAULE','Corp. Municipal'),
('3111','ESCUELA VILLA CULENAR','Maule','TALCA','Corp. Municipal'),
('3112','ESCUELA CALLEJONES','Maule','MAULE','Corp. Municipal'),
('3113','ESCUELA COLIN','Maule','MAULE','Corp. Municipal'),
('3114','ESCUELA CHACARILLA','Maule','MAULE','Corp. Municipal'),
('3115','ESCUELA RURAL DUAO','Maule','MAULE','Corp. Municipal'),
('3117','ESCUELA RURAL NUMPAY','Maule','MAULE','Corp. Municipal'),
('3118','ESCUELA QUINIPEUMO','Maule','MAULE','Corp. Municipal'),
('3121','ESCUELA EL FUERTE','Maule','MAULE','Corp. Municipal'),
('3122','ESCUELA EL CANELO','Maule','MAULE','Corp. Municipal'),
('3123','ESCUELA SANTA ROSA DE LAVADEROS','Maule','MAULE','Corp. Municipal'),
('3124','ESCUELA LINARES DE PERALES','Maule','MAULE','Corp. Municipal'),
('3125','ESCUELA VILLA COBIN','Maule','MAULE','Corp. Municipal'),
('3126','LICEO TECNICO AGRICOLA MARIA AUXILIADORA','Maule','MAULE','Part. Subvencionado'),
('3127','ESCUELA AGRICOLA SAN JOSE DE DUAO','Maule','MAULE','Adm. Delegada'),
('3128','LICEO SAN IGNACIO','Maule','EMPEDRADO','Servicio Local'),
('3130','ESCUELA PEDRO ANTONIO TEJOS TEJOS','Maule','EMPEDRADO','Servicio Local'),
('3134','ESCUELA MARIA OLGA VEGA VEGA','Maule','EMPEDRADO','Servicio Local'),
('3138','COMPLEJO EDUCACIONAL PENCAHUE','Maule','PENCAHUE','Corp. Municipal'),
('3139','ESCUELA PADRE LUIS OLIVA NAVARRETE','Maule','PENCAHUE','Corp. Municipal'),
('3140','ESCUELA CORINTO','Maule','PENCAHUE','Corp. Municipal'),
('3143','ESCUELA SANTA LAURA DE LO FIGUEROA','Maule','PENCAHUE','Corp. Municipal'),
('3146','ESCUELA LA ESPERANZA DEL FUTURO','Maule','PENCAHUE','Corp. Municipal'),
('3158','ESCUELA LA PATAGUA','Maule','PENCAHUE','Corp. Municipal'),
('3159','ESCUELA RIVERA DEL MAULE','Maule','PENCAHUE','Corp. Municipal'),
('3163','INSTITUTO BICENTENARIO DE EXCELENCIA POLITECNICO SUPERIOR EGIDIO ROZZI SACHETTI','Maule','CONSTITUCIÓN','Adm. Delegada'),
('3165','LICEO CONSTITUCION','Maule','CONSTITUCIÓN','Servicio Local'),
('3166','ESCUELA ENRIQUE DONN MULLER','Maule','CONSTITUCIÓN','Servicio Local'),
('3168','ESCUELA SUPERIOR NUEVA BILBAO','Maule','CONSTITUCIÓN','Servicio Local'),
('3169','ESCUELA CERRO ALTO JOSE OPAZO DIAZ','Maule','CONSTITUCIÓN','Servicio Local'),
('3170','CENTRO EDUCACIONAL CONSTITUCION','Maule','CONSTITUCIÓN','Servicio Local'),
('3172','LICEO BICENTENARIO DE EXCELENCIA TECNICO PROFESIONAL PUTÚ','Maule','CONSTITUCIÓN','Servicio Local'),
('3173','LICEO RURAL ENRIQUE MAC IVER','Maule','CONSTITUCIÓN','Servicio Local'),
('3174','ESCUELA LAS CORRIENTES','Maule','CONSTITUCIÓN','Servicio Local'),
('3176','ESCUELA JUNQUILLAR','Maule','CONSTITUCIÓN','Servicio Local'),
('3177','ESCUELA MARIA INES MAROMILLAS','Maule','CONSTITUCIÓN','Servicio Local'),
('3179','ESCUELA BARRANQUILLAS','Maule','CONSTITUCIÓN','Servicio Local'),
('3185','ESCUELA COSTA BLANCA','Maule','CONSTITUCIÓN','Servicio Local'),
('3186','ESCUELA MIGUEL FAUNDEZ MORALES','Maule','CONSTITUCIÓN','Servicio Local'),
('3187','ESCUELA CARRIZALILLO','Maule','CONSTITUCIÓN','Servicio Local'),
('3189','ESCUELA TERESA CONSUELO','Maule','CONSTITUCIÓN','Servicio Local'),
('3190','ESCUELA RURAL QUEBRADA VERDE','Maule','CONSTITUCIÓN','Servicio Local'),
('3191','ESCUELA SANTA AURORA DE CARRIZAL','Maule','CONSTITUCIÓN','Servicio Local'),
('3196','ESCUELA LEONTINA LETELIER LETELIER','Maule','CONSTITUCIÓN','Servicio Local'),
('3198','ESCUELA EDUARDO MACHADO CORSI','Maule','CONSTITUCIÓN','Servicio Local'),
('3201','ESCUELA PARTICULAR SANTA ROSA','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('3202','COLEGIO BICENTENARIO DE EXCELENCIA SAN ALBERTO HURTADO','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('3203','COLEGIO SANTIAGO ONEDERRA','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('3204','COLEGIO CONSTITUCION','Maule','CONSTITUCIÓN','Part. Pagado'),
('3205','LICEO LUIS EDMUNDO CORREA ROJAS','Maule','CUREPTO','Corp. Municipal'),
('3206','ESCUELA FRAY PEDRO ARMENGOL VALENZUELA','Maule','CUREPTO','Corp. Municipal'),
('3207','ESCUELA PEDRO ANTONIO GONZALEZ','Maule','CUREPTO','Corp. Municipal'),
('3208','ESCUELA LAS MERCEDES','Maule','CUREPTO','Corp. Municipal'),
('3209','ESCUELA ELENA ARMIJO MORALES','Maule','CUREPTO','Corp. Municipal'),
('3212','ESCUELA ANA LUISA ESPINA RIVERO','Maule','CUREPTO','Corp. Municipal'),
('3213','ESCUELA LA TRICHERA','Maule','CUREPTO','Corp. Municipal'),
('3215','ESCUELA EL SANTO DE TABUNCO','Maule','CUREPTO','Corp. Municipal'),
('3216','ESCUELA CAPILLA DE RAPILERMO','Maule','CUREPTO','Corp. Municipal'),
('3217','ESCUELA JUAN JESUS GONZALEZ AVENDAÑO','Maule','CUREPTO','Corp. Municipal'),
('3219','ESCUELA LA ORILLA','Maule','CUREPTO','Corp. Municipal'),
('3221','ESCUELA DOCAMAVIDA','Maule','CUREPTO','Corp. Municipal'),
('3222','ESCUELA CARMEN ROSA MARTINEZ BAEZA','Maule','CUREPTO','Corp. Municipal'),
('3223','ESCUELA DOMULGO','Maule','CUREPTO','Corp. Municipal'),
('3229','ESCUELA MANANTIALES','Maule','CUREPTO','Corp. Municipal'),
('3230','ESCUELA JOSE LUIS RICHARDS GONZALEZ','Maule','CUREPTO','Corp. Municipal'),
('3233','ESCUELA JOSE MIGUEL CARRERA','Maule','CUREPTO','Corp. Municipal'),
('3235','ESCUELA MAURICIO LETELIER LETELIER','Maule','CUREPTO','Corp. Municipal'),
('3236','ESCUELA QUEBRADA DE LOS GUINDOS','Maule','CUREPTO','Corp. Municipal'),
('3238','ESCUELA MARINA ROJAS SANDOVAL','Maule','CUREPTO','Corp. Municipal'),
('3240','ESCUELA GASPAR HERRERA HERRERA','Maule','CUREPTO','Corp. Municipal'),
('3242','ESCUELA SAN FRANCISCO DE ASIS','Maule','CUREPTO','Corp. Municipal'),
('3243','ESCUELA ALAMEDA LINARES','Maule','LINARES','Corp. Municipal'),
('3244','ESCUELA ESPECIAL LAS VIOLETAS','Maule','LINARES','Corp. Municipal'),
('3247','LICEO VALENTIN LETELIER','Maule','LINARES','Corp. Municipal'),
('3248','INSTITUTO COMERCIAL','Maule','LINARES','Corp. Municipal'),
('3249','ESCUELA UNO ISABEL RIQUELME','Maule','LINARES','Corp. Municipal'),
('3250','ESCUELA PRESIDENTE CARLOS IBANEZ DEL C.','Maule','LINARES','Corp. Municipal'),
('3251','COLEGIO MARGOT LOYOLA PALACIOS','Maule','LINARES','Corp. Municipal'),
('3252','LICEO TECNICO PROFESIONAL DIEGO PORTALES','Maule','LINARES','Corp. Municipal'),
('3253','JUAN MARTINEZ DE ROZAS','Maule','LINARES','Corp. Municipal'),
('3255','ESCUELA SANTA BARBARA','Maule','LINARES','Corp. Municipal'),
('3256','ESCUELA RAMON BELMAR SALDIAS','Maule','LINARES','Corp. Municipal'),
('3257','ESCUELA ALEJANDRO GIDI','Maule','LINARES','Corp. Municipal'),
('3258','ESCUELA BASICA ESPANA','Maule','LINARES','Corp. Municipal'),
('3260','ESCUELA LOS LEONES','Maule','LINARES','Corp. Municipal'),
('3261','PEDRO AGUIRRE CERDA','Maule','LINARES','Corp. Municipal'),
('3263','ESCUELA MAITENES','Maule','LINARES','Corp. Municipal'),
('3264','ESCUELA SAN VICTOR ALAMOS','Maule','LINARES','Corp. Municipal'),
('3265','ESCUELA LAS TOSCAS','Maule','LINARES','Corp. Municipal'),
('3266','ESCUELA SAN ANTONIO','Maule','LINARES','Corp. Municipal'),
('3267','ESCUELA GRACIELA LETELIER','Maule','LINARES','Corp. Municipal'),
('3268','ESCUELA SALOMON SALMAN DABUD','Maule','LINARES','Corp. Municipal'),
('3269','ESCUELA LAS HORNILLAS','Maule','LINARES','Corp. Municipal'),
('3270','JANUARIO ESPINOSA','Maule','LINARES','Corp. Municipal'),
('3271','ESCUELA LOS HUALLES','Maule','LINARES','Corp. Municipal'),
('3272','ESCUELA CHUPALLAR','Maule','LINARES','Corp. Municipal'),
('3273','ESCUELA MATIAS COUSINO','Maule','LINARES','Corp. Municipal'),
('3277','ESCUELA JORGE HERRERA GUZMAN','Maule','LINARES','Corp. Municipal'),
('3282','ESCUELA EL CULMEN','Maule','LINARES','Corp. Municipal'),
('3284','ESCUELA VIOLETA PARRA','Maule','LINARES','Corp. Municipal'),
('3285','ESCUELA LLANKANAO MANUEL FRANCISCO MEZA SECO','Maule','LINARES','Corp. Municipal'),
('3286','ESCUELA BELLAVISTA','Maule','LINARES','Corp. Municipal'),
('3287','ESCUELA LOS MOGOTES','Maule','LINARES','Corp. Municipal'),
('3288','ESCUELA CAMILO HENRIQUEZ','Maule','LINARES','Corp. Municipal'),
('3289','ESCUELA DE ROBLERIA','Maule','LINARES','Corp. Municipal'),
('3290','LICEO MARIA AUXILIADORA','Maule','LINARES','Part. Subvencionado'),
('3291','ESCUELA BASICA ALCALDE HECTOR PINOCHET C','Maule','LINARES','Part. Subvencionado'),
('3292','ESCUELA PARTICULAR GABRIELA MISTRAL','Maule','LINARES','Part. Subvencionado'),
('3294','COLEGIO PARTICULAR MANUEL BULNES','Maule','LINARES','Part. Subvencionado'),
('3296','ESC.AGRIC.PART.SALESIANA DON BOSCO','Maule','LINARES','Part. Subvencionado'),
('3297','ESCUELA PARTICULAR PROSPERO VILLAR BRAVO','Maule','LINARES','Part. Subvencionado'),
('3298','LICEO NUESTRA SEÑORA DEL ROSARIO','Maule','LINARES','Part. Subvencionado'),
('3299','ESCUELA MARCELA PAZ','Maule','LINARES','Part. Subvencionado'),
('3300','INSTITUTO LINARES','Maule','LINARES','Part. Subvencionado'),
('3302','COLEGIO LA PROVIDENCIA','Maule','LINARES','Part. Subvencionado'),
('3303','COLEGIO AMELIA TRONCOSO','Maule','LINARES','Part. Subvencionado'),
('3304','COLEGIO SAN MIGUEL ARCANGEL','Maule','LINARES','Part. Subvencionado'),
('3305','INSTITUTO POLITECNICO IRENEO BADILLA FUENTES','Maule','LINARES','Corp. Municipal'),
('3308','COLEGIO CONCEPCION LINARES','Maule','LINARES','Part. Subvencionado'),
('3310','COLEGIO EVANGELICO ADONAY','Maule','LINARES','Part. Subvencionado'),
('3311','ESCUELA LUCILA GODOY','Maule','LINARES','Part. Subvencionado'),
('3313','LICEO JUAN DE DIOS PUGA','Maule','YERBAS BUENAS','Corp. Municipal'),
('3314','ESCUELA MAITENCILLO','Maule','YERBAS BUENAS','Corp. Municipal'),
('3315','ESCUELA SILVANO FERNANDEZ','Maule','YERBAS BUENAS','Corp. Municipal'),
('3316','ESCUELA SANTA ANA DE QUERI','Maule','YERBAS BUENAS','Corp. Municipal'),
('3317','LICEO JUAN GOMEZ MILLAS','Maule','YERBAS BUENAS','Corp. Municipal'),
('3318','ESCUELA JORGE SALGADO PICA','Maule','YERBAS BUENAS','Corp. Municipal'),
('3319','ESCUELA ALFREDO NOGUERA PRIETO','Maule','VILLA ALEGRE','Corp. Municipal'),
('3320','ESCUELA BERNARDO OHIGGINS','Maule','YERBAS BUENAS','Corp. Municipal'),
('3321','ESCUELA SANTA ELENA','Maule','YERBAS BUENAS','Corp. Municipal'),
('3322','ESCUELA COIRONAL','Maule','YERBAS BUENAS','Corp. Municipal'),
('3323','ESCUELA LUIS AMBROSIO CONCHA','Maule','YERBAS BUENAS','Corp. Municipal'),
('3325','ESCUELA PARTICULAR ARTURO PRAT','Maule','YERBAS BUENAS','Part. Subvencionado'),
('3327','LICEO BICENTENARIO AGRÍCOLA MARTA MARTÍNEZ CRUZ','Maule','YERBAS BUENAS','Adm. Delegada'),
('3328','LICEO CAPITAN IGNACIO CARRERA PINTO','Maule','COLBÚN','Corp. Municipal'),
('3329','ESCUELA MAULE SUR OLGA PINTO GARCIA','Maule','COLBÚN','Corp. Municipal'),
('3330','ESCUELA LA FLORESTA','Maule','COLBÚN','Corp. Municipal'),
('3332','ESCUELA ANDRES BELLO','Maule','COLBÚN','Corp. Municipal'),
('3333','ESCUELA CARLOS DEL CAMPO RIVERA','Maule','COLBÚN','Corp. Municipal'),
('3334','ESCUELA MONSENOR MANUEL LARRAIN E.','Maule','COLBÚN','Corp. Municipal'),
('3335','ESCUELA PANIMAVIDA','Maule','COLBÚN','Corp. Municipal'),
('3336','ESCUELA RARI','Maule','COLBÚN','Corp. Municipal'),
('3337','ESCUELA AMALIA AMSTRONG DE TORRES','Maule','COLBÚN','Corp. Municipal'),
('3338','ESCUELA KURT MOLLER BOCHERENS','Maule','COLBÚN','Corp. Municipal'),
('3340','ESCUELA LA GUARDIA','Maule','COLBÚN','Corp. Municipal'),
('3345','ESCUELA LOMAS DE PUTAGAN','Maule','COLBÚN','Corp. Municipal'),
('3346','ESCUELA SANTA ELENA','Maule','COLBÚN','Corp. Municipal'),
('3347','ESCUELA PARTICULAR MARTA BRUNET','Maule','COLBÚN','Part. Subvencionado'),
('3348','LICEO ARTURO ALESSANDRI PALMA','Maule','LONGAVÍ','Corp. Municipal'),
('3349','ESCUELA JUAN DE LA CRUZ DOMINGUEZ G.','Maule','LONGAVÍ','Corp. Municipal'),
('3352','ESCUELA ANSELMO DEL CARMEN TAPIA LOYOLA','Maule','LONGAVÍ','Corp. Municipal'),
('3353','ESCUELA ROBERTO OPAZO GALVEZ','Maule','LONGAVÍ','Corp. Municipal'),
('3354','ESCUELA ONOFRE VASQUEZ NORAMBUENA','Maule','LONGAVÍ','Corp. Municipal'),
('3355','ESCUELA GABRIELA MISTRAL','Maule','LONGAVÍ','Corp. Municipal'),
('3356','ESCUELA CARDENAL JOSE MARIA CARO','Maule','LONGAVÍ','Corp. Municipal'),
('3358','ESCUELA JOSE MIGUEL CARRERA','Maule','LONGAVÍ','Corp. Municipal'),
('3359','LICEO LAURA URRUTIA BENAVENTE','Maule','LONGAVÍ','Corp. Municipal'),
('3361','ESCUELA FRANCISCO URRUTIA URRUTIA','Maule','LONGAVÍ','Corp. Municipal'),
('3362','ESCUELA GABRIEL BENAVENTE BENAVENTE','Maule','LONGAVÍ','Corp. Municipal'),
('3364','ESCUELA LUIS PEREIRA INIGUEZ','Maule','LONGAVÍ','Corp. Municipal'),
('3365','ESCUELA MARIA AMBROSIA TAPIA MENDEZ','Maule','LONGAVÍ','Corp. Municipal'),
('3366','ESCUELA CARLOS MONTERO JARAMILLO','Maule','LONGAVÍ','Corp. Municipal'),
('3367','ESCUELA DOMINGA CUELLAR IBANEZ','Maule','LONGAVÍ','Corp. Municipal'),
('3368','ESCUELA JUAN SEGUNDO MUNOZ BRIONES','Maule','LONGAVÍ','Corp. Municipal'),
('3369','ESCUELA ROBERTO MUNOZ VALDES','Maule','LONGAVÍ','Corp. Municipal'),
('3371','ESCUELA PAULA JARAQUEMADA','Maule','LONGAVÍ','Corp. Municipal'),
('3373','ESCUELA EL CARMEN','Maule','LONGAVÍ','Corp. Municipal'),
('3375','ESCUELA CARLOS CONDELL','Maule','LONGAVÍ','Corp. Municipal'),
('3376','ESCUELA MARCELA PAZ','Maule','LONGAVÍ','Corp. Municipal'),
('3377','ESCUELA MANUEL ROZAS ARISTIA','Maule','LONGAVÍ','Corp. Municipal'),
('3378','ESCUELA SOFIA VASQUEZ REBOLLEDO','Maule','LONGAVÍ','Corp. Municipal'),
('3381','ESCUELA ANGEL CRUCHAGA SANTA MARIA','Maule','LONGAVÍ','Corp. Municipal'),
('3382','ESCUELA PEDRO ALESSANDRI VARGAS','Maule','LONGAVÍ','Corp. Municipal'),
('3383','ESCUELA SANTIAGO BUERAS AVARIA','Maule','LONGAVÍ','Corp. Municipal'),
('3384','ESCUELA RAMBERTO CARRERA MARTINEZ','Maule','LONGAVÍ','Corp. Municipal'),
('3387','LICEO FEDERICO HEISE MARTI','Maule','PARRAL','Corp. Municipal'),
('3389','ESCUELA SANTIAGO URRUTIA BENAVENTE','Maule','PARRAL','Corp. Municipal'),
('3390','ESCUELA LUIS ARMANDO GOMEZ MUNOZ','Maule','PARRAL','Corp. Municipal'),
('3393','ESCUELA ARRAU MENDEZ','Maule','PARRAL','Corp. Municipal'),
('3395','ESCUELA NIDER ORREGO QUEVEDO','Maule','PARRAL','Corp. Municipal'),
('3396','ESCUELA JUANITA ZUNIGA FUENTES','Maule','PARRAL','Corp. Municipal'),
('3398','ESCUELA JOSE MATTA CALLEJON','Maule','PARRAL','Corp. Municipal'),
('3400','COLEGIO ALBERTO MOLINA CASTILLO','Maule','PARRAL','Corp. Municipal'),
('3401','ESCUELA EL LIBERTADOR','Maule','PARRAL','Corp. Municipal'),
('3402','ESCUELA FRANCISCO PEREZ LAVIN','Maule','PARRAL','Corp. Municipal'),
('3403','ESCUELA MANUEL MEJIAS MILLAR','Maule','PARRAL','Corp. Municipal'),
('3404','ESCUELA IGNACIO URRUTIA DE LA SOTTA','Maule','PARRAL','Corp. Municipal'),
('3405','ESCUELA ARMANDO GUZMAN MORALES','Maule','PARRAL','Corp. Municipal'),
('3406','ESCUELA CARLOS ZINIGA FUENTES','Maule','PARRAL','Corp. Municipal'),
('3408','ESCUELA FRANCISCO MAUREIRA','Maule','PARRAL','Corp. Municipal'),
('3413','ESCUELA VILLA REINA','Maule','PARRAL','Corp. Municipal'),
('3415','ESCUELA PERQUILAUQUEN SANTA MARIA','Maule','PARRAL','Corp. Municipal'),
('3419','ESCUELA EL CIENAGO','Maule','PARRAL','Corp. Municipal'),
('3420','ESCUELA UNICAVEN','Maule','PARRAL','Corp. Municipal'),
('3421','ESCUELA JUAN BULNES ALDUNATE','Maule','PARRAL','Corp. Municipal'),
('3429','ESCUELA LA FORTUNA','Maule','PARRAL','Corp. Municipal'),
('3430','INSTITUTO PARRAL','Maule','PARRAL','Part. Subvencionado'),
('3431','COLEGIO SAN JOSE','Maule','PARRAL','Part. Subvencionado'),
('3432','COLEGIO PARTICULAR PROVIDENCIA','Maule','PARRAL','Part. Subvencionado'),
('3433','COLEGIO CONCEPCION DE PARRAL','Maule','PARRAL','Part. Subvencionado'),
('3434','LICEO GUILLERMO MARIN LARRAIN','Maule','RETIRO','Corp. Municipal'),
('3435','ESCUELA MANUEL MONTT','Maule','RETIRO','Corp. Municipal'),
('3436','ESCUELA COPIHUE','Maule','RETIRO','Corp. Municipal'),
('3437','ESCUELA RAMON BARROS LUCO','Maule','RETIRO','Corp. Municipal'),
('3439','ESCUELA SAN ISIDRO','Maule','RETIRO','Corp. Municipal'),
('3440','ESCUELA GERTRUDIS ALARCON ARCE','Maule','RETIRO','Corp. Municipal'),
('3442','COLEGIO AJIAL','Maule','RETIRO','Corp. Municipal'),
('3443','COLEGIO ROBINSON CABRERA BELTRAN','Maule','RETIRO','Corp. Municipal'),
('3444','ESCUELA AMANDA BENAVENTE D.','Maule','RETIRO','Corp. Municipal'),
('3445','ESCUELA ROMERAL','Maule','RETIRO','Corp. Municipal'),
('3447','ESCUELA SANTA ADRIANA','Maule','RETIRO','Corp. Municipal'),
('3448','ESCUELA SANTA ISABEL','Maule','RETIRO','Corp. Municipal'),
('3449','ESCUELA SAN RAMON','Maule','RETIRO','Corp. Municipal'),
('3450','ESCUELA SANTA DELFINA','Maule','RETIRO','Corp. Municipal'),
('3452','ESCUELA PATRICIO LARRAIN VALENZUELA','Maule','RETIRO','Corp. Municipal'),
('3453','ESCUELA SANTA CECILIA','Maule','RETIRO','Corp. Municipal'),
('3454','ESCUELA LOS ROBLES','Maule','RETIRO','Corp. Municipal'),
('3457','ESCUELA MANTUL','Maule','RETIRO','Corp. Municipal'),
('3458','ESCUELA MARIA IGNACIA MENA MONROY','Maule','RETIRO','Corp. Municipal'),
('3459','ESCUELA LA CAPILLA','Maule','RETIRO','Corp. Municipal'),
('3460','COLEGIO BICENTENARIO POLIVALENTE LAS CAMELIAS','Maule','RETIRO','Part. Subvencionado'),
('3461','LICEO FRANCISCO ANTONIO ENCINA ARMANET','Maule','VILLA ALEGRE','Corp. Municipal'),
('3462','ESCUELA TIMOTEO ARAYA ALEGRIA','Maule','VILLA ALEGRE','Corp. Municipal'),
('3463','ESCUELA MALAQUIAS CONCHA ORTIZ','Maule','VILLA ALEGRE','Corp. Municipal'),
('3464','ESCUELA HERNAN LOBOS ARIAS','Maule','VILLA ALEGRE','Corp. Municipal'),
('3465','ESCUELA ALCALDE SERAFIN GUTIERREZ F.','Maule','VILLA ALEGRE','Corp. Municipal'),
('3466','ESCUELA ALCALDE ORLANDO RODRIGUEZ DEL C.','Maule','VILLA ALEGRE','Corp. Municipal'),
('3467','ESCUELA ALCALDE MANUEL SALVADOR DEL C.','Maule','VILLA ALEGRE','Corp. Municipal'),
('3468','ESCUELA ASCENCIO ASTORQUIZA ZABALA','Maule','VILLA ALEGRE','Corp. Municipal'),
('3470','ESCUELA TRINIDAD ALCAINO TAPIA','Maule','VILLA ALEGRE','Corp. Municipal'),
('3471','ESCUELA PROFESOR RAMON LEIVA NARVAEZ','Maule','VILLA ALEGRE','Corp. Municipal'),
('3475','ESCUELA JOSE PALMA FERNANDEZ','Maule','VILLA ALEGRE','Corp. Municipal'),
('3478','ESCUELA AGRICOLA SAGRADOS CORAZONES','Maule','VILLA ALEGRE','Part. Subvencionado'),
('3479','LICEO MANUEL MONTT','Maule','SAN JAVIER','Corp. Municipal'),
('3480','ESCUELA JOSE MANUEL BALMACEDA','Maule','SAN JAVIER','Corp. Municipal'),
('3481','ESCUELA MANUEL DE SALAS','Maule','SAN JAVIER','Corp. Municipal'),
('3482','ESCUELA JUSTA NARVAEZ','Maule','SAN JAVIER','Corp. Municipal'),
('3483','ESCUELA GERONIMO LAGOS LISBOA','Maule','SAN JAVIER','Corp. Municipal'),
('3484','ESCUELA DE EDUCACION DIFERENCIAL','Maule','SAN JAVIER','Corp. Municipal'),
('3488','ESCUELA IRENE MORALES','Maule','SAN JAVIER','Corp. Municipal'),
('3489','ESCUELA JORGE GONZALEZ BASTIAS','Maule','SAN JAVIER','Corp. Municipal'),
('3490','ESCUELA JULIO MONTT SALAMANCA','Maule','SAN JAVIER','Corp. Municipal'),
('3491','ESCUELA JUAN DE DIOS ALDEA','Maule','SAN JAVIER','Corp. Municipal'),
('3492','ESCUELA BERNARDO OHIGGINS','Maule','SAN JAVIER','Corp. Municipal'),
('3494','ESCUELA MANUEL RODRIGUEZ','Maule','SAN JAVIER','Corp. Municipal'),
('3495','ESCUELA PEDRO LAGOS','Maule','SAN JAVIER','Corp. Municipal'),
('3497','ESCUELA JOSE MIGUEL CARRERA','Maule','SAN JAVIER','Corp. Municipal'),
('3502','ADELAIDA RIQUELME MESA','Maule','SAN JAVIER','Corp. Municipal'),
('3503','ESCUELA PATRICIO LINCH','Maule','SAN JAVIER','Corp. Municipal'),
('3506','ESCUELA INES DE SUAREZ','Maule','SAN JAVIER','Corp. Municipal'),
('3511','ESCUELA JUAN MARTINEZ DE ROSAS','Maule','SAN JAVIER','Corp. Municipal'),
('3513','ESCUELA IGNACIO SERRANO','Maule','SAN JAVIER','Corp. Municipal'),
('3515','ESCUELA RAMON CARNICER','Maule','SAN JAVIER','Corp. Municipal'),
('3517','ESCUELA CANDELARIA PEREZ','Maule','SAN JAVIER','Corp. Municipal'),
('3518','ESCUELA MARIANO EGANA','Maule','SAN JAVIER','Corp. Municipal'),
('3520','ESCUELA MARIANO LATORRE','Maule','SAN JAVIER','Corp. Municipal'),
('3523','ESCUELA CARLOS CONDELL','Maule','SAN JAVIER','Corp. Municipal'),
('3524','ESCUELA MANUEL BULNES','Maule','SAN JAVIER','Corp. Municipal'),
('3526','ESCUELA AURELIO MEZA RIVERA','Maule','SAN JAVIER','Corp. Municipal'),
('3527','ESCUELA CAMILA MATTA VIAL','Maule','SAN JAVIER','Corp. Municipal'),
('3528','ESCUELA LA CONCEPCION','Maule','SAN JAVIER','Corp. Municipal'),
('3530','COLEGIO PARTICULAR SAN JOSE','Maule','SAN JAVIER','Part. Subvencionado'),
('3531','INSTITUTO REGIONAL DEL MAULE','Maule','SAN JAVIER','Part. Subvencionado'),
('3532','COLEGIO PARTICULAR PIAGET','Maule','SAN JAVIER','Part. Subvencionado'),
('3533','LICEO SAGRADOS CORAZONES','Maule','SAN JAVIER','Part. Subvencionado'),
('3535','ESCUELA MARIANO LATORRE','Maule','CAUQUENES','Servicio Local'),
('3537','ESCUELA ESPECIAL HORIZONTE','Maule','CAUQUENES','Servicio Local'),
('3538','LICEO ANTONIO VARAS','Maule','CAUQUENES','Servicio Local'),
('3539','LICEO CLAUDINA URRUTIA DE LAVIN','Maule','CAUQUENES','Servicio Local'),
('3540','LICEO POLITECNICO PEDRO AGUIRRE CERDA','Maule','CAUQUENES','Servicio Local'),
('3541','ESCUELA ANIBAL PINTO','Maule','CAUQUENES','Servicio Local'),
('3544','COLEGIO BLANCO ENCALADA','Maule','CAUQUENES','Servicio Local'),
('3545','ESCUELA ARTISTICA BARRIO ESTACION','Maule','CAUQUENES','Servicio Local'),
('3546','ESCUELA INDEPENDENCIA','Maule','CAUQUENES','Servicio Local'),
('3548','ESCUELA ECOLOGICA ROSITA OHIGGINS','Maule','CAUQUENES','Servicio Local'),
('3549','ESCUELA PORONGO','Maule','CAUQUENES','Servicio Local'),
('3550','ESCUELA PURISIMA CONCEPCION DE POCILLAS','Maule','CAUQUENES','Servicio Local'),
('3551','ESCUELA LOS CONQUISTADORES','Maule','CAUQUENES','Servicio Local'),
('3552','ESCUELA ADOLFO QUIROZ HERNANDEZ','Maule','CAUQUENES','Servicio Local'),
('3554','ESCUELA CLORINDO ALVEAR','Maule','CAUQUENES','Servicio Local'),
('3555','ESCUELA OCTAVIO PALMA PEREZ','Maule','CAUQUENES','Servicio Local'),
('3559','ESCUELA IVAN ALEJANDRO DE LA CUADRA','Maule','CAUQUENES','Servicio Local'),
('3564','ESCUELA HECTOR SILVESTRE PAIVA MANRIQUEZ','Maule','CAUQUENES','Servicio Local'),
('3569','ESCUELA JAVIERA CARRERA','Maule','CAUQUENES','Servicio Local'),
('3573','ESCUELA PEDRO DE VALDIVIA','Maule','CAUQUENES','Servicio Local'),
('3579','ESCUELA JOSÉ DOLORES MUÑOZ LABRA','Maule','CAUQUENES','Servicio Local'),
('3580','ESCUELA PEDERNALES','Maule','CAUQUENES','Servicio Local'),
('3583','ESCUELA MARIA GONZALEZ VERA','Maule','CAUQUENES','Servicio Local'),
('3586','ESCUELA CHORRILLOS','Maule','CAUQUENES','Servicio Local'),
('3588','ESCUELA ESTER URRUTIA DE RUIZ','Maule','CAUQUENES','Servicio Local'),
('3596','ESCUELA LA CAPILLA DE PILEN ALTO','Maule','CAUQUENES','Servicio Local'),
('3599','ESCUELA MIXTA ATENEA','Maule','CAUQUENES','Servicio Local'),
('3601','ESCUELA LA PATAGUA','Maule','CAUQUENES','Servicio Local'),
('3602','ESCUELA EL TROZO','Maule','CAUQUENES','Servicio Local'),
('3604','ESCUELA CABRERIA','Maule','CAUQUENES','Servicio Local'),
('3608','LICEO INMACULADA CONCEPCION','Maule','CAUQUENES','Part. Subvencionado'),
('3609','LICEO PELLUHUE','Maule','PELLUHUE','Servicio Local'),
('3610','ESCUELA GLADYS CANALES PAREDES','Maule','PELLUHUE','Servicio Local'),
('3611','ESCUELA BLANCA BUSTOS CASTILLO','Maule','PELLUHUE','Servicio Local'),
('3612','ESCUELA SAN ALFONSO CANELILLO','Maule','PELLUHUE','Servicio Local'),
('3614','ESCUELA JOSE RIVAS HERNANDEZ','Maule','PELLUHUE','Servicio Local'),
('3615','ESCUELA ESCRITORA MARCELA PAZ','Maule','PELLUHUE','Servicio Local'),
('3616','ESCUELA BENITO MANCILLA PEREZ','Maule','PELLUHUE','Servicio Local'),
('3618','LICEO FEDERICO ALBERT FAUPP','Maule','CHANCO','Servicio Local'),
('3619','ESCUELA LOS HEROES','Maule','CHANCO','Servicio Local'),
('3621','ESCUELA SAN AMBROSIO','Maule','CHANCO','Servicio Local'),
('3622','ESCUELA PAHUIL','Maule','CHANCO','Servicio Local'),
('3623','ESCUELA CARRERAS CORTAS','Maule','CHANCO','Servicio Local'),
('3624','ESCUELA LOS PEUMOS','Maule','CHANCO','Servicio Local'),
('3625','ESCUELA GABRIELA MISTRAL','Maule','CHANCO','Servicio Local'),
('3626','ESCUELA RELOCA','Maule','CHANCO','Servicio Local'),
('3629','ESCUELA EL SAUCE','Maule','CHANCO','Servicio Local'),
('3630','ESCUELA RICARDO SALGADO','Maule','CHANCO','Servicio Local'),
('3631','ESCUELA EMA VASQUEZ GUTIERREZ','Maule','CHANCO','Servicio Local'),
('3632','ESCUELA ANTONIETA LEON VERDUGO','Maule','CHANCO','Servicio Local'),
('3633','ESCUELA QUINIPATO','Maule','CHANCO','Servicio Local'),
('3636','ESCUELA LOANCO','Maule','CHANCO','Servicio Local'),
('3638','LICEO BICENTENARIO MARTA BRUNET CÁRAVES','Ñuble','CHILLÁN','Corp. Municipal'),
('3639','LICEO NARCISO TONDREAU','Ñuble','CHILLÁN','Corp. Municipal'),
('3640','INSTITUTO SUPERIOR DE COMERCIO PROFESOR FERNANDO PÉREZ BECERRA','Ñuble','CHILLÁN','Adm. Delegada'),
('3641','INSTITUTO INDUSTRIAL SUPERIOR DE CHILLÁN','Ñuble','CHILLÁN','Adm. Delegada'),
('3642','INSTITUTO TÉCNICO MABEL CONDEMARÍN GRIMBERG','Ñuble','CHILLÁN','Adm. Delegada'),
('3643','LICEO BICENTENARIO DE EXCELENCIA MARTÍN RUIZ DE GAMBOA','Ñuble','CHILLÁN','Corp. Municipal'),
('3644','ESCUELA NUEVA ESPERANZA','Ñuble','CHILLÁN','Corp. Municipal'),
('3645','LICEO VIDA NUEVA','Ñuble','CHILLÁN','Corp. Municipal'),
('3649','ESCUELA ESPECIAL LAS ACACIAS','Ñuble','CHILLÁN','Corp. Municipal'),
('3650','ESCUELA PARVULARIA FEDERICO FROEBEL','Ñuble','CHILLÁN','Corp. Municipal'),
('3656','LICEO POLIVALENTE JUAN PACHECO ALTAMIRANO','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3657','LICEO LIBERTADOR BERNARDO O´HIGGINS RIQUELME','Ñuble','CHILLÁN','Corp. Municipal'),
('3659','ESCUELA ARTURO MERINO BENITEZ','Ñuble','CHILLÁN','Corp. Municipal'),
('3660','ESCUELA GABRIELA MISTRAL','Ñuble','CHILLÁN','Corp. Municipal'),
('3662','LICEO REPÚBLICA DE ITALIA ARTURO BONOMETTI BROGI','Ñuble','CHILLÁN','Corp. Municipal'),
('3663','ESCUELA REPUBLICA DE MEXICO','Ñuble','CHILLÁN','Corp. Municipal'),
('3664','ESCUELA BASICA EL TEJAR','Ñuble','CHILLÁN','Corp. Municipal'),
('3666','ESCUELA MARIA AMALIA SAAVEDRA MARTINEZ','Ñuble','CHILLÁN','Corp. Municipal'),
('3667','ESCUELA BASICA LA CASTILLA','Ñuble','CHILLÁN','Corp. Municipal'),
('3668','ESCUELA PALESTINA','Ñuble','CHILLÁN','Corp. Municipal'),
('3669','ESCUELA BÁSICA ROSITA O´HIGGINS RIQUELME','Ñuble','CHILLÁN','Corp. Municipal'),
('3670','ESCUELA BASICA REYES DE ESPANA','Ñuble','CHILLÁN','Corp. Municipal'),
('3671','ESCUELA BASICA JUAN MADRID AZOLA','Ñuble','CHILLÁN','Corp. Municipal'),
('3672','ESC. BASICA ARTURO MUTIZABAL SOTOMAYOR','Ñuble','CHILLÁN','Corp. Municipal'),
('3673','ESCUELA BASICA QUILAMAPU','Ñuble','CHILLÁN','Corp. Municipal'),
('3675','ESCUELA BASICA JOSE MARIA CARO RODRIGUEZ','Ñuble','CHILLÁN','Corp. Municipal'),
('3677','ESCUELA BASICA LAS CANOAS','Ñuble','CHILLÁN','Corp. Municipal'),
('3678','ESCUELA 27 DE ABRIL','Ñuble','CHILLÁN','Corp. Municipal'),
('3681','ESCUELA BASICA CAPILLA COX','Ñuble','CHILLÁN','Corp. Municipal'),
('3683','ESCUELA BASICA RUCAPEQUEN','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3685','ESCUELA BASICA QUINCHAMALI','Ñuble','CHILLÁN','Corp. Municipal'),
('3686','ESCUELA BASICA NEBUCO','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3687','ESCUELA BASICA EL PEUMO','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('3691','ESCUELA PAUL HARRIS','Ñuble','CHILLÁN','Corp. Municipal'),
('3694','ESCUELA BASICA LLOLLINCO','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3697','ESCUELA BASICA CONFLUENCIA','Ñuble','CHILLÁN','Corp. Municipal'),
('3698','ESCUELA BASICA QUILMO','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3703','ESCUELA ANTONIO MACHADO','Ñuble','CHILLÁN','Corp. Municipal'),
('3704','ESCUELA BASICA COLLIGUAY','Ñuble','CHILLÁN','Corp. Municipal'),
('3707','ESCUELA LOS JARDINES DE LAUTARO','Ñuble','CHILLÁN','Corp. Municipal'),
('3709','ESCUELA BASICA LOS COLIGUES','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('3710','ESCUELA BASICA PUENTE EL ALA','Ñuble','SAN NICOLÁS','Corp. Municipal'),
('3711','COLEGIO DE LA PURISIMA CONCEPCION','Ñuble','CHILLÁN','Part. Subvencionado'),
('3713','COLEGIO SEMINARIO PADRE ALBERTO HURTADO','Ñuble','CHILLÁN','Part. Subvencionado'),
('3714','ESCUELA PARTICULAR ADVENTISTA','Ñuble','CHILLÁN','Part. Subvencionado'),
('3716','COLEGIO SANTA ISABEL CHILLÁN','Ñuble','CHILLÁN','Part. Subvencionado'),
('3717','ESCUELA PARTICULAR HISPANO AMERICANO','Ñuble','CHILLÁN','Part. Subvencionado'),
('3718','INSTITUTO SANTA MARIA','Ñuble','CHILLÁN','Part. Subvencionado'),
('3719','COLEGIO COYAM','Ñuble','CHILLÁN','Part. Subvencionado'),
('3720','DEUTSCHE SCHULE CHILLAN','Ñuble','CHILLÁN','Part. Pagado'),
('3723','COLEGIO DARIO SALAS','Ñuble','CHILLÁN','Part. Subvencionado'),
('3724','COLEGIO SAN VICENTE DE PAUL','Ñuble','CHILLÁN','Part. Subvencionado'),
('3725','ESCUELA ESPECIAL DIFERENCIAL AVANZANDO JUNTOS','Ñuble','CHILLÁN','Part. Subvencionado'),
('3726','COLEGIO CRISTIANO HOREB','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('3727','ESCUELA BASICA DIFERENCIAL EL ROBLE','Ñuble','CHILLÁN','Part. Subvencionado'),
('3728','COLEGIO SAN BUENAVENTURA','Ñuble','CHILLÁN','Part. Subvencionado'),
('3730','COLEGIO SAGRADO CORAZÓN DE JESÚS','Ñuble','CHILLÁN','Part. Subvencionado'),
('3731','COLEGIO SAN VALENTIN','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('3733','COLEGIO GABRIELA MISTRAL','Ñuble','CHILLÁN','Part. Subvencionado'),
('3735','COLEGIO CHILLAN','Ñuble','CHILLÁN','Part. Subvencionado'),
('3738','LICEO TÉCNICO PROFESIONAL SAN RAFAEL DE CHILLÁN','Ñuble','CHILLÁN','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
