-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 23 de 31 | filas 8801-9200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('20165','CHRISTIAN COLLEGE','La Araucanía','LONCOCHE','Part. Subvencionado'),
('20167','COLEGIO LIAHONA','La Araucanía','PUCÓN','Part. Subvencionado'),
('20168','JARDIN INFANTIL HORMIGUITA','La Araucanía','LAUTARO','Part. Subvencionado'),
('20173','LICEO HUMANISTA CIENTIFICO BRAINSTORM','La Araucanía','TEMUCO','Part. Subvencionado'),
('20175','LICEO JUAN PABLO II','La Araucanía','GALVARINO','Part. Subvencionado'),
('20176','LICEO DE ADULTOS CAUTIN','La Araucanía','TEMUCO','Part. Subvencionado'),
('20179','COLEGIO CAMPESTRE RAFAEL POMBO','La Araucanía','LONCOCHE','Part. Subvencionado'),
('20180','ESC.CRISTIANA DESARROLLO INTEGRAL','La Araucanía','TEMUCO','Part. Subvencionado'),
('20181','COLEGIO SAINT PATRICK SCHOOL','La Araucanía','TEMUCO','Part. Subvencionado'),
('20182','COLEGIO JUAN PABLO II','La Araucanía','CUNCO','Part. Subvencionado'),
('20184','LICEO SAN SEBASTIAN','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20186','COLEGIO SAN MARCOS','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20187','ESCUELA PARTICULAR NUEVO AMANECER','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('20193','COMPLEJO EDUCACIONAL MAQUEHUE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20194','COLEGIO INGLES MI MUNDO','La Araucanía','TRAIGUÉN','Part. Subvencionado'),
('20195','JARDIN INFANTIL MI CASITA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20196','COLEGIO EDUCACION DE ADULTOS NAHUEL','La Araucanía','LAUTARO','Part. Subvencionado'),
('20197','JARDIN INFANTIL CASITA DEL BOSQUE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20200','ESCUELA MUNICIPAL GABRIELA MISTRAL','La Araucanía','GALVARINO','Corp. Municipal'),
('20202','ESCUELA PARTICULAR SAN ALBERTO','La Araucanía','PURÉN','Part. Subvencionado'),
('20203','ESCUELA ESPECIAL DE LENGUAJE CRE-SER','La Araucanía','TEMUCO','Part. Subvencionado'),
('20204','ESCUELA ESPECIAL RUCA MAHUIDA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20205','ESCUELA PARTICULAR HABIT-ART','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20206','ESCUELA ESP.LENGUAJE ANDALUE','La Araucanía','LAUTARO','Part. Subvencionado'),
('20208','COLEGIO EDUC. DE ADULTOS NAHUEL','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20209','COLEGIO RAITRAI DE PUCON','La Araucanía','PUCÓN','Part. Subvencionado'),
('20212','COLEGIO HEBREO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20213','COLEGIO PEDRO DE VALDIVIA DE VILLARRICA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20214','COLEGIO DE EDUC. DE ADULTOS ANDES','La Araucanía','TEMUCO','Part. Subvencionado'),
('20215','ESCUELA PARTICULAR SAN LEONARDO','La Araucanía','ERCILLA','Part. Subvencionado'),
('20216','JARDIN INFANTIL ALEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('20218','ESCUELA PART. TEMUCO COLLEGE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20219','COLEGIO BICENTENARIO DE EXCELENCIA ADENAUER','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('20222','ESCUELA PARTICULAR INALKO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20223','ESCUELA ESPECIAL LIWEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('20225','ESCUELA DE LENGUAJE MANANTIAL','La Araucanía','TEMUCO','Part. Subvencionado'),
('20226','COLEGIO NEWHARVEST','La Araucanía','TEMUCO','Part. Subvencionado'),
('20227','COLEGIO JUAN PABLO II','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20228','ESCUELA ESPECIAL DE LENGUAJE ARCO IRIS','La Araucanía','ANGOL','Part. Subvencionado'),
('20230','LICEO PARTICULAR SAN ROQUE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20232','COLEGIO DE ADULTOS INAPEWMA','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('20234','JARDIN INFANTIL DE COLORES','La Araucanía','TEMUCO','Part. Subvencionado'),
('20235','GEORGE CHAYTOR ENGLISH COLLEGE','La Araucanía','TEMUCO','Part. Pagado'),
('20237','ESCUELA ESPECIAL DE LENGUAJE HABLAPALABRAS','La Araucanía','TEMUCO','Part. Subvencionado'),
('20239','ESCUELA ESPECIAL DE LENGUAJE VICTORIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('20240','ESCUELA ESPECIAL DE LENGUAJE CAPULLITO','La Araucanía','CURACAUTÍN','Part. Subvencionado'),
('20242','ESCUELA ESPECIAL DE LENGUAJE COLEN','La Araucanía','RENAICO','Part. Subvencionado'),
('20243','ESCUELA ESPECIAL DE LENGUAJE PEKES','La Araucanía','TEMUCO','Part. Subvencionado'),
('20244','COLEGIO DE ADULTOS RAYENCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20245','COLEGIO DE ADULTOS TRINIDAD','La Araucanía','GORBEA','Part. Subvencionado'),
('20246','ESCUELA ESPECIAL DE LENGUAJE ALEMANIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20247','ESC. ESPECIAL LENGUAJE STA. PATRICIA','La Araucanía','LAUTARO','Part. Subvencionado'),
('20248','LICEO MUNICIPAL TROVOLHUE','La Araucanía','CARAHUE','Servicio Local'),
('20250','ESCUELA ESPECIAL DE LENGUAJE RAICES DEL SUR','La Araucanía','TEMUCO','Part. Subvencionado'),
('20252','ESCUELA ESPECIAL DE LENGUAJE WILEF','La Araucanía','TEMUCO','Part. Subvencionado'),
('20256','JARDIN INFANTIL CLARO DE LUNA','La Araucanía','LAUTARO','Part. Subvencionado'),
('20257','ESCUELA ESPECIAL  DE LENGUAJE SUYAI','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20258','COLEGIO BICENTENARIO CUMBRES DE LABRANZA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20259','ESCUELA SAN MIGUEL DE IMPERIALITO','La Araucanía','CARAHUE','Part. Subvencionado'),
('20260','COLEGIO FILADELFIA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20261','COLEGIO DE EDUCACION ADULTOS CORDILLERA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20262','JARDIN INFANTIL KIMUN','La Araucanía','TEMUCO','Part. Subvencionado'),
('20263','COLEGIO JUAN XXIII','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20264','ESC.ESPECIAL LENGUAJE MANITOS PINTADAS','La Araucanía','LOS SAUCES','Part. Subvencionado'),
('20265','COLEGIO LOS ROBLES','La Araucanía','TEMUCO','Part. Subvencionado'),
('20266','LICEO BICENTENARIO DE TEMUCO','La Araucanía','TEMUCO','Corp. Municipal'),
('20267','ESCUELA DE PÁRVULOS MONTE SIÓN','La Araucanía','TEMUCO','Part. Subvencionado'),
('20268','ESCUELA ESPECIAL DE LENGUAJE NIÑO JESUS','La Araucanía','LONCOCHE','Part. Subvencionado'),
('20270','COLEGIO DE ADULTOS HACIA UN NUEVO HORIZONTE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20271','ESCUELA ESPECIAL DE LENGUAJE SUYAI VILCÚN','La Araucanía','VILCÚN','Part. Subvencionado'),
('20273','ESCUELA ESPECIAL DE LENGUAJE ALUN SUYAI','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20274','COLEGIO FOR LIFE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20276','ESCUELA ESP. DE LENGUAJE MI MUNDO EN PALABRAS','La Araucanía','LAUTARO','Part. Subvencionado'),
('20277','ESCUELA ESPECIAL HOSPITALARIA SAN EXPEDITO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20278','ESCUELA ESPECIAL HOSPITALARIA REVIVIR','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20279','COLEGIO INTERCULTURAL CERRO LONCOCHE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20281','COLEGIO ARRAYAN','La Araucanía','VILCÚN','Part. Subvencionado'),
('20282','COLEGIO CUMBRE DE SAN RAMON','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20283','ESCUELA ESPECIAL DE LENGUAJE RAYEN','La Araucanía','GORBEA','Part. Subvencionado'),
('20284','ESCUELA ESPECIAL DE LENGUAJE WE LIWEN','La Araucanía','TOLTÉN','Part. Subvencionado'),
('20285','COLEGIO EMANUEL','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('20287','ESCUELA ESPECIAL AMPALU','La Araucanía','ANGOL','Part. Subvencionado'),
('20288','COLEGIO EL CASTILLO DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20289','ESCUELA NUEVOS COPIHUES','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('20290','COLEGIO THE FOREST SCHOOL','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('20291','ESCUELA DE LENGUAJE MUNDO NUEVO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20292','ESCUELA ESPECIAL DE LENGUAJE LETRITAS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('20293','ESCUELA ESPECIAL DE LENGUAJE SEMILLITA','Biobío','ARAUCO','Part. Subvencionado'),
('20294','ESCUELA ESPECIAL N° 2458 KIMUNTUWE','Metropolitana','LAMPA','Part. Subvencionado'),
('20295','ESCUELA  ESPECIAL  N° 208 LA  RONDA','Metropolitana','BUIN','Part. Subvencionado'),
('20296','ESCUELA ESPECIAL DE LENGUAJE PEUMAYEN','Biobío','HUALPÉN','Part. Subvencionado'),
('20297','ESCUELA NUEVO AMANECER DE QUILACO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20298','COLEGIO PUENTE MAIPO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('20300','COLEGIO DIEGO THOMPSON','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('20301','ESCUELA ESPECIAL DE TRANSTORNOS ESPECIFICOS DEL LENGUAJE ANDALUE','Coquimbo','LA SERENA','Part. Subvencionado'),
('20302','ESCUELA ESPECIAL DE LENGUAJE KOLIBRI','Coquimbo','LA SERENA','Part. Subvencionado'),
('20303','ESC. PARV. Nº203 GARDEN LAND PRE SCHOOL','Metropolitana','TALAGANTE','Part. Subvencionado'),
('20304','ESCUELA ESPECIAL Nº204 MONTEALTO','Metropolitana','EL MONTE','Part. Subvencionado'),
('20306','ESCUELA ESPECIAL N°209 PEPITA DE SANDIA','Metropolitana','PAINE','Part. Subvencionado'),
('20307','COLEGIO MONTAHUE','Coquimbo','LA SERENA','Part. Pagado'),
('20308','COLEGIO ALTERRA','Metropolitana','SAN BERNARDO','Part. Pagado'),
('20310','COLEGIO DE ADULTOS PULMAHUE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('20311','COLEGIO HUINGANAL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('20313','ESC.ESP.RIGOBERTA MENCHÚ II','Metropolitana','LA PINTANA','Part. Subvencionado'),
('20314','ESCUELA ESPECIAL DE LENGUAJE SAN IGNACIO','Maule','CURICÓ','Part. Subvencionado'),
('20315','ESCUELA DE LENGUAGE ELISA GOMEZ','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('20316','COLEGIO ALTAZOR','Ñuble','CHILLÁN','Part. Subvencionado'),
('20317','CENTRO EDUCACIONAL LUZ DE LUNA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('20321','ESCUELA ESPECIAL N° 2462 SAN ANDRES DE BATUCO','Metropolitana','LAMPA','Part. Subvencionado'),
('20323','CARIQUEO','Metropolitana','QUILICURA','Part. Subvencionado'),
('20324','ALTOS DEL HUERTO','Metropolitana','TILTIL','Part. Subvencionado'),
('20325','ESCUELA ESPECIAL DE LENGUAJE KAILIN URUGUAY','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20326','COLEGIO DE ADULTOS SU SANTIDAD JUAN PABLO II','Coquimbo','COQUIMBO','Part. Pagado'),
('20327','ESCUELA ESPECIAL DE LENGUAJE `PASITOS`','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('20328','ESCUELA ESPECIAL DE LENGUAJE SAN FRANCISCO DE ASIS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20329','ESCUELA BASICA N° 2464 `COLEGIO BASICO INTEGRADO PADRE PIO`','Metropolitana','TILTIL','Part. Subvencionado'),
('20330','INSTITUTO RAILEF','O''Higgins','PICHILEMU','Part. Subvencionado'),
('20331','ESCUELA ESPECIAL DE LENGUAJE `GENIOS DEL FUTURO`','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('20332','ESCUELA ESPECIAL DEL LENGUAJE ALEGRIA DEL SABER','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20334','ESCUELA ESPECIAL DE LENGUAJE ESTRELLITA DE BELÉN','Arica y Parinacota','ARICA','Part. Subvencionado'),
('20335','ESCUELA ESPECIAL DE LENGUAJE MIS TESOROS','Maule','RETIRO','Part. Subvencionado'),
('20337','SALA CUNA Y JARDIN INFANTIL CAPULLITO','Maule','TALCA','Part. Pagado'),
('20338','ESC.PARV.N° 2465 ARTISTICO NUEVO SOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('20339','ESCUELA ESPECIAL DE LENGUAJE RAYITO DE LUZ','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('20340','ESCUELA ESPECIAL DE LENGUAJE LA COLMENA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('20341','ESCUELA ESPECIAL DE LENGUAJE PANKULL','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('20342','ESCUELA ESPECIAL DE LENGUAJE POLHUIN','Maule','CHANCO','Servicio Local'),
('20343','ESCUELA   ESPECIAL  N°  211 `KIMKUMTUN`','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('20344','ESCUELA ESPECIAL DE LENGUAJE PALABRAS DE CRISTAL','Maule','LONGAVÍ','Part. Subvencionado'),
('20345','ESCUELA ESPECIAL N° 205 SANTA MARIA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('20346','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑO MUNDO','Coquimbo','LA SERENA','Part. Subvencionado'),
('20347','C.E.I.A. AMIGOS DEL PADRE HURTADO','Coquimbo','LA SERENA','Part. Subvencionado'),
('20348','NORTH CROSS SCHOOL','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('20349','ESCUELA ESPECIAL DE LENGUAJE ARBOL SAGRADO','O''Higgins','MACHALÍ','Part. Subvencionado'),
('20350','ESCUELA ESPECIAL DE LENGUAJE PEUMAYEN','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('20351','ESCUELA ESPECIAL PLAY SCHOOL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('20352','COLEGIO BUEN PASTOR','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('20354','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS REYES','Valparaíso','LA CRUZ','Part. Subvencionado'),
('20355','ESCUELA ESPECIAL DE LENGUAJE SAN SEBASTIAN','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20356','COLEGIO DE JOVENES Y ADULTOS BALMACEDA','Coquimbo','LA SERENA','Part. Subvencionado'),
('20357','ESCUELA ESPECIAL DE LENGUAJE ZAPATITO JUGUETON','La Araucanía','VILCÚN','Part. Subvencionado'),
('20358','ESCUELA ESPECIAL DE LENGUAJE EDUCARTE','Los Ríos','VALDIVIA','Part. Subvencionado'),
('20359','INSTITUTO  PARA  ADULTOS COSTEAU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('20360','ESCUELA ESPECIAL DE LENGUAJE ARBOLIRIS','Coquimbo','LA SERENA','Part. Subvencionado'),
('20361','COLEGIO TRAPANANDA','Aysén','COYHAIQUE','Part. Subvencionado'),
('20363','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS ARTISTAS','Valparaíso','QUILLOTA','Part. Subvencionado'),
('20364','COLEGIO AYELEN','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20365','ESCUELA ESPECIAL DE LENGUAJE MI MUNDO IDEAL','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('20366','ESCUELA ESPECIAL DE LENGUAJE AYEKANTUN','Valparaíso','QUILLOTA','Part. Subvencionado'),
('20368','ESCUELA ESPECIAL DE LENGUAJE EL DUENDE DAPAFE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('20369','CENTRO DE EDUCACION DE ADULTOS LA SERENA','Coquimbo','LA SERENA','Part. Pagado'),
('20371','ESCUELA ESPECIAL DE LENGUAJE ENE-TENE-TÚ','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('20372','ESCUELA ESPECIAL Y DE LENGUAJE EL SAUCE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20373','ESCUELA ESPECIAL DE LENGUAJE RAIMAU','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('20374','ESCUELA ESPECIAL DE LENGUAJE LAWAL','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('20375','ESCUELA ESPECIAL DE LENGUAJE ESMERALDA','O''Higgins','RENGO','Part. Subvencionado'),
('20376','COLEGIO NUEVA ALERCE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('20377','ESCUELA ESPECIAL DE LENGUAJE SANTA MARIANA','Coquimbo','LA SERENA','Part. Subvencionado'),
('20378','ESCUELA BASICA RENACER','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('20379','ESCUELA ESPECIAL DE LENGUAJE SEMILLITAS DE AMOR','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('20381','ESCUELA ESPECIAL DE LENGUAJE APRENDO FELIZ','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('20382','JARDÍN INFANTIL Y SALA CUNA CRICRI','Los Lagos','PUERTO VARAS','Part. Pagado'),
('20383','ESCUELA ESPECIAL DE LENGUAJE SAYEN','Los Lagos','OSORNO','Part. Subvencionado'),
('20385','ESCUELA ESPECIAL DE LENGUAJE ALMAGRO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20386','ESCUELA ESPECIAL DE LENGUAJE LANKUYEN CARELMAPU','Los Lagos','MAULLIN','Part. Subvencionado'),
('20387','ESCUELA ESPECIAL N° 206, DANTE ALIGHIERI','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('20389','ESCUELA ESPECIAL DE LENGUAJE CAPULLOS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20390','COLEGIO CIELOS DEL VALLE','Coquimbo','LA SERENA','Part. Subvencionado'),
('20391','ESCUELA ESPECIAL DE LENGUAJE EL NOGAL','Biobío','FLORIDA','Part. Subvencionado'),
('20392','COLEGIO SAN PABLO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20393','CENTRO DE EDUCACION INTEGRADA DE ADULTOS POETA ALFONSO MORA','Biobío','TOMÉ','Corp. Municipal'),
('20395','COLEGIO DE ADULTOS ANDRES BELLO','Ñuble','CHILLÁN','Part. Subvencionado'),
('20397','ESCUELA ESPECIAL N°2466 NUESTROS HIJOS','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('20399','COLEGIO EDUCAADULTOS CONCHALI','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('20400','COLEGIO KIMEN MONTESSORI','Metropolitana','COLINA','Part. Pagado'),
('20401','ESCUELA BASICA N° 2468, RONALDO MUÑOZ GIBBS','Metropolitana','LAMPA','Part. Subvencionado'),
('20402','ESCUELA DEL CARIÑO KIMELTUWE','Metropolitana','BUIN','Part. Subvencionado'),
('20404','ESCUELA DEL CARIÑO SAINT CHRISTIAN','Metropolitana','LA GRANJA','Part. Subvencionado'),
('20406','CENTRO DE EDUCACION INTEGRADA DE ADULTOS MONSEÑOR ALFREDO SILVA SANTIAGO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('20407','ESCUELA ESPECIAL Y DE LENGUAJE ALIWEN','Coquimbo','LA SERENA','Part. Subvencionado'),
('20408','ESCUELA ESPECIAL DE LENGUAJE HUELLITAS','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('20409','ESCUELA HOSPITALARIA PUERTO MONTT','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('20410','COLEGIO GENESIS','Los Lagos','PURRANQUE','Part. Subvencionado'),
('20411','CENTRO DE EDUCACION DE ADULTOS ANDRES BELLO','Los Lagos','OSORNO','Part. Subvencionado'),
('20412','ESCUELA DIFERENCIAL Y CENTRO DE ATENCION TEMPRANA LIBERTAD','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('20413','ESPECIAL DE LENGUAJE COLORIN COLORADO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20414','ESCUELA ESPECIAL DE LENGUAJE BRISTOL','Biobío','HUALPÉN','Part. Subvencionado'),
('20416','ESCUELA ESPECIAL DE LENGUAJE CREANDO SUEÑOS','Ñuble','ÑIQUÉN','Part. Subvencionado'),
('20418','ESCUELA ESPECIAL DE LENGUAJE CARACOL','Biobío','MULCHÉN','Part. Subvencionado'),
('20419','ESCUELA DE PARVULOS N°2467 LARAPINTA EL SOL','Metropolitana','LAMPA','Part. Subvencionado'),
('20421','ESCUELA ESPECIAL DE LENGUAJE TUCAPEL','Biobío','TUCAPEL','Part. Subvencionado'),
('20422','ESCUELA ESPECIAL DE LENGUAJE ESPERANZA','Biobío','CABRERO','Part. Subvencionado'),
('20423','ECO ESCUELA QUPA YAPU DE TRASTORNOS ESPECÍFICOS DEL LENGUAJE','Atacama','COPIAPÓ','Part. Subvencionado'),
('20424','ESCUELA ESPECIAL DE LENGUAJE Y ESCUELA BASICA MY COLLEGE','Ñuble','CHILLÁN','Part. Subvencionado'),
('20425','COLEGIO EDUCRECE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('20426','ESCUELA BASICA N° 2469 COLEGIO NEHUEN','Metropolitana','LAMPA','Part. Subvencionado'),
('20427','ESCUELA BASICA ÑIPAS','Ñuble','RANQUIL','Corp. Municipal'),
('20428','ESCUELA DE PAVULOS N°2471 ESCUELA PRE ESCOLAR CANTAGALLO','Metropolitana','LO BARNECHEA','Part. Pagado'),
('20429','ESCUELA ESPECIAL N° 2470 ÁRBOL DE COLORES','Metropolitana','LA PINTANA','Part. Subvencionado'),
('20430','ESCUELA ESPECIAL DE LENGUAJE PEUMAYEN','Biobío','CORONEL','Part. Subvencionado'),
('20432','ESCUELA ESPECIAL N° 2472 GIRASOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('20433','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS AMIGOS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('20435','COLEGIO CALASANZ KURAREWE','La Araucanía','CURARREHUE','Part. Subvencionado'),
('20436','COLEGIO  ALONSO  DE  CORDOVA','Metropolitana','RENCA','Part. Subvencionado'),
('20437','ESCUELA ESPECIAL DE LENGUAJE GIRASOLES','Ñuble','CHILLÁN','Part. Subvencionado'),
('20438','ESCUELA ESPECIAL DE LENGUAJE SANTA LEONOR','Biobío','TALCAHUANO','Part. Subvencionado'),
('20439','ESCUELA ESPECIAL DE LENGUAJE MUNICIPAL','Los Ríos','LA UNIÓN','Corp. Municipal'),
('20440','LICEO DOCTOR JUAN VERDAGUER PLANAS','Metropolitana','RECOLETA','Corp. Municipal'),
('20441','COLEGIO CABO DE HORNOS','Metropolitana','COLINA','Part. Pagado'),
('20443','INSTITUTO DE EDUCACIÓN DE ADULTOS ACONCAGUA','Valparaíso','CALERA','Part. Subvencionado'),
('20444','ESCUELA DE PARVULOS N°2475 AMERICAN BRITISH FIRST','Metropolitana','LA FLORIDA','Part. Pagado'),
('20445','COLEGIO WESTON ACADEMY','Metropolitana','LAMPA','Part. Pagado'),
('20446','CENTRO DE EDUCACION ESPECIAL SAN FRANCISCO DE ASIS','Los Ríos','MARIQUINA','Part. Subvencionado'),
('20447','ESCUELA  ESPECIAL  N°2476  MIS  FUTURAS  PALABRAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('20449','ESCUELA BÁSICA N°209 COLEGIO SANTA CLAUDIA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('20450','ESCUELA DE LENGUAJE ALMA MATER','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('20452','COLEGIO DE EDUCACION DE ADULTOS PAULO FREIRE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20454','ESCUELA ESPECIAL DE LENGUAJE ARBOL','O''Higgins','PALMILLA','Part. Subvencionado'),
('20455','ESCUELA  ESPECIAL  N° 2481  `SANTA  EMILIA `','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('20456','ESCUELA  DIFERENCIAL N° 2480  ` AMULEN`','Metropolitana','RENCA','Part. Subvencionado'),
('20457','ESCUELA ESPECIAL N° 2479 MARGARITA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('20458','ESCUELA ESPECIAL N° 2478 ANGELES','Metropolitana','QUILICURA','Part. Subvencionado'),
('20460','COLEGIO LA MISION MOSTAZAL','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('20461','COLEGIO TECNICO PROFESIONAL SAN ESTEBAN','Ñuble','BULNES','Part. Subvencionado'),
('20462','ESCUELA ESPECIAL DE LENGUAJE AMAPOLA','O''Higgins','OLIVAR','Part. Subvencionado'),
('20463','ESCUELA ESPECIAL DE LENGUAJE TRAVESÍA','Coquimbo','LA SERENA','Part. Subvencionado'),
('20464','LICEO PRESIDENTE CARLOS IBÁÑEZ DEL CAMPO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('20466','COLEGIO DE ADULTOS PABLO NERUDA DE TALCA','Maule','TALCA','Part. Subvencionado'),
('20467','ESCUELA ESPECIAL DE LENGUAJE EL CASTILLO DE VICENTE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20469','CENTRO DE EDUCACION INTEGRAL DE ADULTOS PAIHUEN DE VICUÑA','Coquimbo','VICUÑA','Part. Subvencionado'),
('20470','CENTRO DE EDUCACION INTERGRADA DE ADULTOS ICADE','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20471','ESCUELA DE PARVULOS N°2482 KINDERGARTEN ALTONA','Metropolitana','VITACURA','Part. Pagado'),
('20472','ESCUELA ESPECIAL DE LENGUAJE MI PEQUEÑO SUEÑO','Maule','LINARES','Part. Subvencionado'),
('20474','COLEGIO VIRGINIA SUBERCASEAUX','Metropolitana','PIRQUE','Part. Pagado'),
('20475','COLEGIO ACADEMIA POLIVALENTE DE FORMACIÒN PREMILITAR GENERAL JOSE MIGUEL CARRERA','Metropolitana','EL MONTE','Part. Subvencionado'),
('20476','JARDIN INFANTIL Y SALA CUNA THE GREEN VALLEY','Los Lagos','PUERTO MONTT','Part. Pagado'),
('20477','COLEGIO TALCA','Maule','TALCA','Part. Pagado'),
('20478','COLEGIO TÉCNICO INDUSTRIAL DON BOSCO - CALAMA','Antofagasta','CALAMA','Part. Subvencionado'),
('20480','ESCUELA ESPECIAL N° 238 MAGUS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('20481','ESCUELA DE ADULTOS RESPLANDECER','Los Lagos','SAN PABLO','Part. Pagado'),
('20483','JARDIN INFANTIL MUNAYI MONTESSORI','Tarapacá','IQUIQUE','Part. Pagado'),
('20484','AULA HOSPITALARIA SAN SEBASTIAN DE IQUIQUE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('20486','JARDIN INFANTIL SEMILLITAS DEL VALLE','La Araucanía','GALVARINO','Part. Subvencionado'),
('20487','ESCUELA ESPECIAL N° 2483 ANKATU','Metropolitana','COLINA','Part. Subvencionado'),
('20489','COLEGIO CIMA','O''Higgins','COINCO','Part. Subvencionado'),
('20490','ESCUELA ESPECIAL MONTE DE LOS OLIVOS','La Araucanía','TEMUCO','Part. Subvencionado'),
('20491','ESCUELA ESPECIAL DIFERENCIAL ALEN','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('20492','ESCUELA ESPECIAL MASTER EDUCA','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('20493','ESCUELA ESPECIAL Nº239 CARRUSEL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('20494','CENTRO DE EDUCACION INTEGRAL DE ADULTOS `RENACER`','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20497','ESCUELA ESPECIAL DE LENGUAJE MANDALA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('20498','COLEGIO PARA ADULTOS `CARPE DIEM`','O''Higgins','RANCAGUA','Part. Subvencionado'),
('20500','COLEGIO TRICAHUE','O''Higgins','REQUÍNOA','Part. Pagado'),
('20502','COLEGIO PUMAHUE CHICAUMA','Metropolitana','LAMPA','Part. Pagado'),
('20504','CENTRO EDUCACIONAL HACIENDA DE TENO','Maule','TENO','Corp. Municipal'),
('20505','AULA HOSPITALARIA DE COQUIMBO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20506','ESCUELA HOSPITALARIA DE ANCUD','Los Lagos','ANCUD','Servicio Local'),
('20507','COLEGIO CREE CERRO NAVIA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('20508','COLEGIO VILLA CARTAGO','Valparaíso','CARTAGENA','Corp. Municipal'),
('20509','COLEGIO EDUCAD LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('20510','COLEGIO  EDUCAR ADULTOS  RECOLETA','Metropolitana','RECOLETA','Part. Subvencionado'),
('20511','ESCUELA  ESPECIAL N° 2486 EDELWEISS','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('20512','ESCUELA ESPECIAL DIFERENCIAL CENTRO DE FORMACION LABORAL AMANECER DE CARRIZALES','Ñuble','COELEMU','Corp. Municipal'),
('20513','AMAZING GRACE ENGLISH SCHOOL - PEÑUELAS','Coquimbo','COQUIMBO','Part. Pagado'),
('20514','ESCUELA ESPECIAL DE LENGUAJE ANELEY','Valparaíso','PANQUEHUE','Part. Subvencionado'),
('20516','ESCUELA DE LENGUAJE NUEVA ESPERANZA DE DICHATO','Biobío','TOMÉ','Part. Subvencionado'),
('20518','ESCUELA ESPECIAL DE LENGUAJE AGUA SANTA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('20519','COLEGIO CIENTIFICO HUMANISTA ALVARO COVARRUBIAS','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('20520','COLEGIO SAN MARCOS DE ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('20521','JARDIN INFANTIL ALMINAR','O''Higgins','SAN FERNANDO','Part. Pagado'),
('20526','JARDÍN INFANTIL Y SALA CUNA KRIPPE','Tarapacá','IQUIQUE','Part. Pagado'),
('20533','ESCUELA ESPECIAL DE LENGUAJE MIS PRIMEROS PASITOS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('20549','ESCUELA ESPECIAL DIFERENCIAL HUALLEREHUE','Biobío','SANTA JUANA','Servicio Local'),
('20562','ESCUELA ESPECIAL LAUTRARU PADRE HURTADO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('20564','JARDIN INFANTIL ANTUNEYEN','Coquimbo','OVALLE','Part. Subvencionado'),
('20566','JARDIN INFANTIL AGUSTINA PAZ','Valparaíso','LIMACHE','Part. Pagado'),
('20567','ENGLISH COLLEGE LOS RÍOS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('20582','ESCUELA ESPECIAL DE LENGUAJE CLUSTER','La Araucanía','VICTORIA','Part. Subvencionado'),
('20585','ESCUELA ESPECIAL Nº 2487  ` OMILEN  ANTU `','Metropolitana','MAIPÚ','Part. Subvencionado'),
('20586','ESCUELA DE PARVULOS N°210 JARDIN INFANTIL PEPITAS DE AMOR','Metropolitana','MELIPILLA','Part. Pagado'),
('20592','ESCUELA ESPECIAL Nº 213 PRINCIPADO INFANCIA FELIZ','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('20593','ESCUELA ESPECIAL Nº 214 PROFESOR ANTONIO OROZ','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('20600','ESCUELA REMIGIO AGURTO FUENTES DE PARRAL','Maule','PARRAL','Corp. Municipal'),
('20601','COLEGIO TERRAVIDA','Los Lagos','PUERTO VARAS','Part. Pagado'),
('20604','ESCUELA ESPECIAL DE LENGUAJE GRANJERITOS','Maule','SAN CLEMENTE','Part. Subvencionado'),
('20631','ESCUELA HOSPITALARIA PADRE HURTADO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('20632','JARDIN INFANTIL Y SALA CUNA ARCO IRIS DEL SABER','Tarapacá','IQUIQUE','Part. Pagado'),
('20634','ESCUELA ESPECIAL DE LENGUAJE ESTOY FELIZ','Biobío','CORONEL','Part. Subvencionado'),
('20638','ESCUELA ESPECIAL DE LENGUAJE ANTAKARI','Coquimbo','COQUIMBO','Part. Subvencionado'),
('20663','ESCUELA HOSPITALARIA DOCTORA ELOISA DIAZ INSUNZA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('20665','ANTOFAGASTA GREENHILL SCHOOL','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('20691','ESCUELA DE EDUCACIÓN ESPECIAL KANTATURU','Arica y Parinacota','ARICA','Part. Subvencionado'),
('22007','COLEGIO ARTISTICO SANTA CECILIA','Los Lagos','OSORNO','Part. Subvencionado'),
('22009','COLEGIO SANTA MARIA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22010','COLEGIO CHILOE','Los Lagos','ANCUD','Part. Subvencionado'),
('22012','LICEO PUNTA DE RIELES','Los Lagos','LOS MUERMOS','Servicio Local'),
('22013','ESCUELA ESPECIAL N.316 LOS CIRUELILLOS','Los Lagos','CASTRO','Part. Subvencionado'),
('22014','COLEGIO BAQUEDANO','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22016','ESCUELA PARTICULAR CARRAN CHICO','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('22019','ESCUELA PARTICULAR N. 320 ADVENTISTA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22020','COLEGIO CAHUALA','Los Lagos','CASTRO','Part. Pagado'),
('22021','LICEO LAS AMERICAS','Los Lagos','PUYEHUE','Corp. Municipal'),
('22022','LICEO IGNACIO CARRERA PINTO','Los Lagos','FRUTILLAR','Servicio Local'),
('22024','LICEO TECNICO PROFESIONAL RADIO 24','Los Ríos','PAILLACO','Part. Subvencionado'),
('22025','ESCUELA PARTICULAR SAN MIGUEL','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22027','LICEO HORNOPIREN','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('22029','COLEGIO STAR COLLEGE','Los Lagos','OSORNO','Part. Pagado'),
('22038','JARDIN INFANTIL `LOS CARIÑOSITOS`','Los Lagos','CASTRO','Part. Pagado'),
('22041','CENTRO EDUCACIONAL PAZ Y AMOR','Los Lagos','ANCUD','Part. Subvencionado'),
('22048','ESCUELA RURAL CHANGUE','Los Lagos','MAULLIN','Corp. Municipal'),
('22049','ESCUELA PARTICULAR N.322','Los Lagos','MAULLIN','Part. Subvencionado'),
('22050','LICEO BICENTENARIO DE EXCELENCIA BENJAMIN MUÑOZ GAMERO','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('22051','ESC. ESPECIAL DE LENGUAJE PEKE LINES','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22065','COLEGIO SAN FRANCISCO DE ASIS','Los Lagos','CASTRO','Part. Subvencionado'),
('22066','CENTRO DE EDUCACION DE ADULTOS PAULO FREIRE','Los Lagos','MAULLIN','Part. Subvencionado'),
('22070','ESCUELA PARVULARIA `RAYITO DE SOL`','Los Lagos','PUYEHUE','Corp. Municipal'),
('22077','ESCUELA PARTICULAR LLAQUITO','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22078','ESCUELA ESPECIAL DE LENGUAJE MAIHUE','Los Lagos','CASTRO','Part. Subvencionado'),
('22083','COLEGIO ALMIRANTE JUAN JOSE LATORRE','Los Lagos','CHAITÉN','Corp. Municipal'),
('22084','LICEO POLITECNICO ANTULAFKEN','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('22086','LICEO RURAL LAS QUEMAS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22089','C.E.I.A. SALOMON FUENTES MARTINEZ','Los Lagos','ANCUD','Servicio Local'),
('22091','JARDIN INFANTIL RAYITO DE LUZ','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22092','ESCUELA PARTICULAR LOS HALCONES','Los Lagos','HUALAIHUÉ','Part. Subvencionado'),
('22094','COLEGIO WANELEN WE','Los Lagos','CASTRO','Part. Subvencionado'),
('22095','ESCUELA PARTICULAR EL HUIRO','Los Ríos','CORRAL','Part. Subvencionado'),
('22096','ESCUELA PARTICULAR JUANITA FERNANDEZ SOLAR','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22098','ESCUELA RURAL INIO','Los Lagos','QUELLÓN','Servicio Local'),
('22100','ESCUELA RURAL EL VARAL','Los Lagos','HUALAIHUÉ','Corp. Municipal'),
('22101','ESCUELA DIFERENCIAL `ASPADEP`','Los Lagos','PUERTO VARAS','Servicio Local'),
('22103','CENTRO DE REHABILITACION DE LA PARALISIS CEREBRAL OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('22105','ESCUELA BASICA FRESIA','Los Lagos','FRESIA','Servicio Local'),
('22111','ESCUELA PARTICULAR MALIHUE','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22112','ESCUELA RURAL PUNTA WHITE','Los Lagos','QUELLÓN','Servicio Local'),
('22113','LICEO FRAY PABLO DE ROYO','Los Lagos','SAN PABLO','Corp. Municipal'),
('22114','LICEO PREMILITAR HÉROES DE LA CONCEPCIÓN','Los Lagos','OSORNO','Part. Subvencionado'),
('22116','JARDIN INFANTIL `ARLEQUIN`','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22117','JARDIN INFANTIL `AGUALUNA`','Los Lagos','CHONCHI','Part. Pagado'),
('22119','COLEGIO `SAN ANDRES`','Los Lagos','ANCUD','Part. Pagado'),
('22125','ESCUELA PARTICULAR COMUY','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('22127','JARDIN INFANTIL `EL TALLITO`','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22130','ESCUELA ALLA-KINTUY','Los Lagos','QUELLÓN','Servicio Local'),
('22133','ESCUELA ESPECIAL DE LENGUAJE PALABRAS MAGICAS','Los Lagos','OSORNO','Part. Subvencionado'),
('22134','ESCUELA RURAL BONIFACIO','Los Ríos','VALDIVIA','Servicio Local'),
('22137','JARDIN INFANTIL `LA CAMPIÑA`','Los Lagos','OSORNO','Part. Pagado'),
('22138','ESCUELA RURAL EL TIGRE','Los Lagos','PALENA','Corp. Municipal'),
('22139','ESCUELA ESPECIAL `LAURA VICUÑA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22140','LICEO BICENTENARIO INGENIERO RICARDO FENNER RUEDI','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22142','ESCUELA RURAL BLANCHARD','Los Lagos','QUELLÓN','Servicio Local'),
('22144','COLEGIO PUERTO VARAS','Los Lagos','PUERTO VARAS','Part. Pagado'),
('22145','ESCUELA RURAL EL MIRADOR','Los Ríos','LOS LAGOS','Servicio Local'),
('22146','COLEGIO ABRAHAM LINCOLN','Los Lagos','OSORNO','Part. Subvencionado'),
('22148','ESCUELA PART. EL PARQUE PONHUIPA','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('22153','ESCUELA PARTICULAR ESTRELLA SOLITARIA','Los Ríos','LAGO RANCO','Part. Subvencionado'),
('22155','COLEGIO CARPE DIEM','Los Lagos','CASTRO','Part. Subvencionado'),
('22158','ESCUELA PARTICULAR EL PRADO','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22160','MARTIN LUTHER KING COLLEGE','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22162','ESCUELA PARTICULAR PUILE','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22165','ESCUELA PARTICULAR MARANATA','Los Ríos','LANCO','Part. Subvencionado'),
('22172','JARDIN INFANTIL CASITA ENCANTADA','Los Ríos','VALDIVIA','Part. Pagado'),
('22173','JARDIN INFANTIL ADVENTISTA','Los Lagos','CASTRO','Part. Subvencionado'),
('22175','ESCUELA PABLO NERUDA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22176','ESCUELA PADRE HURTADO','Los Lagos','CASTRO','Servicio Local'),
('22177','COLEGIO SAN LUIS DE ALBA','Los Ríos','VALDIVIA','Part. Pagado'),
('22180','ESCUELA PART.HUMBERTO HERNANDEZ','Los Ríos','CORRAL','Part. Subvencionado'),
('22181','ESCUELA PARTICULAR RALUYA','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22184','ESCUELA PARTICULAR RUBEN BASTIDAS','Los Lagos','MAULLIN','Part. Subvencionado'),
('22186','ESC. PART. CONDE DE LEMU','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22187','LICEO MANUEL BAQUEDANO','Los Lagos','OSORNO','Part. Subvencionado'),
('22188','CENTRO EDUCACION ADULTOS ANDRES BELLO','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22189','LICEO SAN FRANCISCO','Los Lagos','ANCUD','Part. Subvencionado'),
('22191','COLEGIO EMPRENDER OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('22192','COLEGIO CATOLICO BEATO FEDERICO OZANAM','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22195','COLEGIO CRISTIANO BETESDA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22196','COLEGIO QUELLON','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22200','INSTITUTO DEL PACIFICO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22201','CENTRO PARA LA INTEGRACION `JEROME BRUNER`','Los Lagos','OSORNO','Part. Subvencionado'),
('22203','COLEGIO LACUY','Los Lagos','ANCUD','Part. Subvencionado'),
('22204','ESCUELA DE PARVULOS REY SALOMON','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22207','ESCUELA PARTICULAR SAN SEBASTIAN','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22209','ESCUELA RURAL EL LLOLLE','Los Lagos','MAULLIN','Corp. Municipal'),
('22210','CENTRO EDUCACIONAL SAN ANDRES','Los Lagos','ANCUD','Part. Subvencionado'),
('22211','COLEGIO CAHUALA INSULAR','Los Lagos','CASTRO','Part. Subvencionado'),
('22214','ESCUELA RURAL PIEDRA LILE','Los Lagos','QUELLÓN','Servicio Local'),
('22215','CENTRO DE ESTUDIOS LA ARAUCANA','Los Lagos','OSORNO','Part. Pagado'),
('22218','COLEGIO PUFUDI','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22219','ESCUELA SANTA CECILIA','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22220','COLEGIO FRANCISCO COLOANE','Los Lagos','QUEMCHI','Part. Subvencionado'),
('22221','ESCUELA FRAY LEONARDO','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22223','CENTRO EDUCACIONAL LOS CARRERA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22224','COLEGIO PROYECCION SIGLO XXI','Los Lagos','OSORNO','Part. Subvencionado'),
('22225','ESC. PARTICULAR CHAQUIAN','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22226','COLEGIO LAURA VICUNA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22227','COLEGIO AUSTRALIS','Los Ríos','LANCO','Part. Pagado'),
('22228','ESCUELA PARTICULAR AYELEN','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22229','ESCUELA BASICA LICARAYEN','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22230','COLEGIO JUAN XXIII','Los Lagos','OSORNO','Part. Subvencionado'),
('22231','COLEGIO DOMUS MATER','Los Ríos','VALDIVIA','Part. Pagado'),
('22234','COLEGIO SAN VICENTE DE PAUL','Los Lagos','PUERTO OCTAY','Part. Subvencionado'),
('22236','BLAS PASCAL SCHOOL','Los Lagos','OSORNO','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
