-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 10 de 31 | filas 3601-4000
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('5756','ESCUELA PARTICULAR RENGALIL','La Araucanía','TEMUCO','Part. Subvencionado'),
('5759','ESCUELA PARTICULAR BOYECO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5760','ESCUELA PARTICULAR DIEGO PORTALES','La Araucanía','TEMUCO','Part. Subvencionado'),
('5761','ESCUELA SAN MARTIN DE PORRES','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5763','ESCUELA PARTICULAR MANZANAR DE LLEUPECO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5764','ESCUELA P-416 DORCA LLANCAVIL ZANJA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5765','ESCUELA PARTICULAR KIMELTU DE PANCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5766','ESCUELA BÁSICA PARTICULAR SUBVENCIONADA GUIDO BUCHER','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5767','ESCUELA PARTICULAR TRES CERROS','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5768','ESCUELA PARTICULAR SAN VICENTE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5770','ESCUELA BASICA KOYAM','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5773','ESCUELA PARTICULAR LUIS CRUZ MARTINEZ','La Araucanía','TEMUCO','Part. Subvencionado'),
('5774','ESCUELA PARTICULAR SAN FRANCISCO DE CUNCO CHICO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5776','ESCUELA PARTICULAR VIRGEN DE GUADALUPE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5778','ESCUELA PARTICULAR EL VALLE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5779','ESCUELA PARTICULAR EL ESFUERZO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5781','ESCUELA PARTICULAR ARAUCO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5782','ESCUELA PARTICULAR SIGLO XXI','La Araucanía','TEMUCO','Part. Subvencionado'),
('5783','ESCUELA PARTICULAR SAN JOSE','La Araucanía','TEMUCO','Part. Subvencionado'),
('5784','ESCUELA PARTICULAR SARGENTO CANDELARIA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5785','ESCUELA PARTICULAR SAN MATEO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5790','ESCUELA PARTICULAR EL CRUCERO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5791','ESCUELA PARTICULAR WITRAMALAL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5793','ESCUELA ANDRES BELLO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5794','ESCUELA PARTICULAR PROF.ANDRES AGUAYO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5796','ESCUELA PARTICULAR DOCTOR MUHAJIR','La Araucanía','TEMUCO','Part. Subvencionado'),
('5797','ESCUELA PARTICULAR REPOCURA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5798','ESCUELA PARTICULAR NIRRIMAPU','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5799','ESCUELA SANTA INES DE CAIVICO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5800','ESCUELA PARTICULAR JOSE LUIS SANFUENTES','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5801','ESCUELA PARTICULAR POETA ERCILLA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5803','ESCUELA PARTICULAR PICHI ITINENTO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5806','ESCUELA PARTICULAR DAVID RIADI MATUS','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('5808','COLEGIO DE LA SALLE','La Araucanía','TEMUCO','Part. Pagado'),
('5810','COLEGIO BAUTISTA','La Araucanía','TEMUCO','Part. Pagado'),
('5812','COLEGIO ALEMAN','La Araucanía','TEMUCO','Part. Pagado'),
('5813','COLEGIO CENTENARIO DE TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('5814','COLEGIO SANTA CRUZ','La Araucanía','TEMUCO','Part. Subvencionado'),
('5816','COLEGIO METODISTA','La Araucanía','TEMUCO','Part. Subvencionado'),
('5823','LICEO H-C JORGE TEILLIER SANDOVAL','La Araucanía','LAUTARO','Corp. Municipal'),
('5824','ESC. BASICA NUMERO SEIS','La Araucanía','LAUTARO','Corp. Municipal'),
('5825','ESC. BASICA AMELIA GODOY','La Araucanía','LAUTARO','Corp. Municipal'),
('5827','ESCUELA IRENE FREI','La Araucanía','LAUTARO','Corp. Municipal'),
('5828','ESC. BASICA GUACOLDA','La Araucanía','LAUTARO','Corp. Municipal'),
('5829','ESCUELA LOS CACHORROS','La Araucanía','LAUTARO','Corp. Municipal'),
('5830','ESCUELA DE LAUTARO','La Araucanía','LAUTARO','Corp. Municipal'),
('5831','LICEO LOS CASTANOS','La Araucanía','LAUTARO','Corp. Municipal'),
('5832','ESC. BASICA NIERECO','La Araucanía','LAUTARO','Corp. Municipal'),
('5833','ESC. BASICA REWE KIMUN','La Araucanía','LAUTARO','Corp. Municipal'),
('5834','ESCUELA SANTA ROSA','La Araucanía','LAUTARO','Corp. Municipal'),
('5835','ESC. BASICA VILLA COIHUECO','La Araucanía','LAUTARO','Corp. Municipal'),
('5837','ESCUELA DOLLICO ALTO','La Araucanía','LAUTARO','Corp. Municipal'),
('5838','ESC. BASICA LAS MINAS','La Araucanía','LAUTARO','Corp. Municipal'),
('5844','ESC. BASICA SAN LUIS DE ROBLER-A','La Araucanía','LAUTARO','Corp. Municipal'),
('5846','ESC. BASICA TRES ESQUINAS','La Araucanía','LAUTARO','Corp. Municipal'),
('5847','ESC. BASICA SANTA YOLANDA','La Araucanía','LAUTARO','Corp. Municipal'),
('5849','ESC. BASICA PUMALAL','La Araucanía','LAUTARO','Corp. Municipal'),
('5850','ESC. BASICA VISTA HERMOSA','La Araucanía','LAUTARO','Corp. Municipal'),
('5851','ESC. BASICA CHUMIL','La Araucanía','LAUTARO','Corp. Municipal'),
('5852','ESC. BASICA EL ESCUDO','La Araucanía','LAUTARO','Corp. Municipal'),
('5854','ESC. BASICA VEGA LARGA','La Araucanía','LAUTARO','Corp. Municipal'),
('5855','ESC. BASICA MUCO CHUREO','La Araucanía','LAUTARO','Corp. Municipal'),
('5857','ESC. BASICA MALPICHAHUE','La Araucanía','LAUTARO','Corp. Municipal'),
('5861','ESC.PART.SAN FRANCISCO DE ASIS - LAUTARO','La Araucanía','LAUTARO','Part. Subvencionado'),
('5862','ESCUELA PARTICULAR CORAZON DE JESUS','La Araucanía','LAUTARO','Part. Subvencionado'),
('5868','ESCUELA PARTICULAR QUILACURA','La Araucanía','LAUTARO','Part. Subvencionado'),
('5869','ESCUELA PARTICULAR SANTA TERESA','La Araucanía','LAUTARO','Part. Subvencionado'),
('5871','ESCUELA PARTICULAR SANTA TERESITA','La Araucanía','LAUTARO','Part. Subvencionado'),
('5873','ESCUELA PARTICULAR LOS HUALLES','La Araucanía','LAUTARO','Part. Subvencionado'),
('5875','ESCUELA PARTICULAR NUEVA DOLLINCO','La Araucanía','LAUTARO','Part. Subvencionado'),
('5876','ESCUELA PARTICULAR SAN RAFAEL','La Araucanía','LAUTARO','Part. Subvencionado'),
('5878','ESCUELA PARTICULAR VALLEPENCO','La Araucanía','LAUTARO','Part. Subvencionado'),
('5879','LICEO ISABEL POBLETE V.','La Araucanía','PERQUENCO','Corp. Municipal'),
('5880','ESCUELA EDUARDO FREI MONTALVA','La Araucanía','PERQUENCO','Corp. Municipal'),
('5885','ESCUELA LOS QUIQUES','La Araucanía','PERQUENCO','Corp. Municipal'),
('5888','ESC. BASICA PARLAMENTO','La Araucanía','PERQUENCO','Corp. Municipal'),
('5893','ESCUELA PARTICULAR LAS CEREZAS','La Araucanía','PERQUENCO','Part. Subvencionado'),
('5894','ESCUELA PARTICULAR LA ESTRELLA','La Araucanía','PERQUENCO','Part. Subvencionado'),
('5896','ESCUELA JAPON','La Araucanía','VILCÚN','Corp. Municipal'),
('5897','COLEGIO AMERICA','La Araucanía','VILCÚN','Corp. Municipal'),
('5899','ESCUELA DAGOBERTO GODOY','La Araucanía','VILCÚN','Corp. Municipal'),
('5901','ESC. BASICA VEGA REDONDA','La Araucanía','VILCÚN','Corp. Municipal'),
('5902','ESCUELA MARTIN ALONQUEO PIUTRIN','La Araucanía','VILCÚN','Corp. Municipal'),
('5905','ESC. BASICA COLLIN ALTO','La Araucanía','VILCÚN','Corp. Municipal'),
('5911','ESC. BASICA CANTINO','La Araucanía','VILCÚN','Corp. Municipal'),
('5919','ESCUELA PADRE OSVALDO VEGA','La Araucanía','VILCÚN','Part. Subvencionado'),
('5921','LICEO BICENTENARIO PADRE NICOLÁS','La Araucanía','VILCÚN','Part. Subvencionado'),
('5923','LICEO AGRICOLA CRUZ DEL SUR','La Araucanía','VILCÚN','Part. Subvencionado'),
('5927','ESCUELA PARTICULAR CODINHUE','La Araucanía','VILCÚN','Part. Subvencionado'),
('5930','ESCUELA PARTICULAR SANTA GERTRUDIS','La Araucanía','VILCÚN','Part. Subvencionado'),
('5933','ESCUELA PARTICULAR EL NATRE','La Araucanía','VILCÚN','Part. Subvencionado'),
('5935','ESCUELA PARTICULAR SANTA TERESITA','La Araucanía','VILCÚN','Part. Subvencionado'),
('5938','SAN MIGUEL DE QUINTRILPE','La Araucanía','VILCÚN','Part. Subvencionado'),
('5940','ESCUELA PARTICULAR VIRGEN DE FATIMA','La Araucanía','VILCÚN','Part. Subvencionado'),
('5942','ESCUELA PARTICULAR SAN ANTONIO','La Araucanía','VILCÚN','Part. Subvencionado'),
('5947','ESCUELA PARTICULAR CRUZ DEL SUR','La Araucanía','VILCÚN','Part. Subvencionado'),
('5952','ESCUELA PARTICULAR SANTA MONICA','La Araucanía','VILCÚN','Part. Subvencionado'),
('5954','ESCUELA PARTICULAR LOS ROBLES','La Araucanía','VILCÚN','Part. Subvencionado'),
('5955','ESCUELA PARTICULAR MONTERREY','La Araucanía','VILCÚN','Part. Subvencionado'),
('5957','LICEO MUNICIPAL ATENEA','La Araucanía','CUNCO','Corp. Municipal'),
('5959','LICEO ARTURO VALENZUELA','La Araucanía','CUNCO','Corp. Municipal'),
('5960','ESCUELA BASICA LAS HORTENCIAS','La Araucanía','CUNCO','Corp. Municipal'),
('5962','ESCUELA HECTOR VALENZUELA CEA','La Araucanía','VILLARRICA','Corp. Municipal'),
('5964','ESC. BASICA SAN CAMILO','La Araucanía','CUNCO','Corp. Municipal'),
('5970','ESCUELA VIDA Y PAZ','La Araucanía','CUNCO','Corp. Municipal'),
('5973','ESC. BASICA EL ROSAL','La Araucanía','CUNCO','Corp. Municipal'),
('5977','ESC. BASICA QUINETRU','La Araucanía','CUNCO','Corp. Municipal'),
('5980','ESC. BASICA LLAULLAHUE','La Araucanía','CUNCO','Corp. Municipal'),
('5981','ESCUELA PAULO ARAVENA ARAVENA','La Araucanía','CUNCO','Corp. Municipal'),
('5984','ESC. BASICA LO SCHMITH','La Araucanía','CUNCO','Corp. Municipal'),
('5985','ESCUELA LA MANANA','La Araucanía','CUNCO','Corp. Municipal'),
('5987','ESC. BASICA LEUFUCHE','La Araucanía','CUNCO','Corp. Municipal'),
('5990','ESCUELA BASICA QUECHEREHUE','La Araucanía','CUNCO','Corp. Municipal'),
('5992','LICEO BICENTENARIO DE EXCELENCIA JUAN BOSCO','La Araucanía','CUNCO','Part. Subvencionado'),
('5993','ESCUELA LEOVIGILDO KLEY','La Araucanía','CUNCO','Part. Subvencionado'),
('5994','ESCUELA PARTICULAR SUBVENCIONADA PADRE MARCELINO HUICHAMIL','La Araucanía','CUNCO','Part. Subvencionado'),
('5995','ESCUELA PARTICULAR QUECHEREHUE','La Araucanía','CUNCO','Part. Subvencionado'),
('5998','ESCUELA PARTICULAR LA BASTILLA','La Araucanía','CUNCO','Part. Subvencionado'),
('5999','ESCUELA PARTICULAR PADRE BERNABE','La Araucanía','CUNCO','Part. Subvencionado'),
('6003','ESC. PART. STA. ISABEL DE TRAFAMPULLI','La Araucanía','CUNCO','Part. Subvencionado'),
('6005','ESCUELA AURORA DE CHILE','La Araucanía','CUNCO','Corp. Municipal'),
('6006','ESCUELA PARTICULAR ALAMEDA','La Araucanía','CUNCO','Part. Subvencionado'),
('6007','LICEO LOS ANDES','La Araucanía','MELIPEUCO','Corp. Municipal'),
('6009','ESC. BASICA MOLULCO','La Araucanía','MELIPEUCO','Corp. Municipal'),
('6011','ESC. BASICA MOLULCO','La Araucanía','MELIPEUCO','Corp. Municipal'),
('6012','ESC. BASICA CUMCUMLLAQUE','La Araucanía','MELIPEUCO','Corp. Municipal'),
('6015','ESC. BASICA CURACALCO','La Araucanía','CUNCO','Corp. Municipal'),
('6017','ESCUELA MUNICIPAL CARÉN','La Araucanía','MELIPEUCO','Corp. Municipal'),
('6018','ESCUELA PARTICULAR SAN GABRIEL','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6019','ESCUELA PARTICULAR LLAIMA','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6021','ESCUELA PARTICULAR CAREN','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6022','ESCUELA PARTICULAR LA SUERTE','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6023','ESCUELA PARTICULAR PALIHUEPILLAN','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6024','ESCUELA PARTICULAR EL RETIRO','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6025','ESCUELA DAHUELHUE','La Araucanía','MELIPEUCO','Part. Subvencionado'),
('6027','COMPLEJO EDUCACIONAL MONSEÑOR FRCO. VALDES S','La Araucanía','CURARREHUE','Corp. Municipal'),
('6029','ESCUELA RUCA MANKE','La Araucanía','CURARREHUE','Corp. Municipal'),
('6030','ESCUELA JERONIMO NECULPAN','La Araucanía','CURARREHUE','Corp. Municipal'),
('6031','ESCUELA EL SANTILLO','La Araucanía','CURARREHUE','Corp. Municipal'),
('6032','ESCUELA MAMUIL MALAL','La Araucanía','CURARREHUE','Corp. Municipal'),
('6036','ESCUELA LICANCURA','La Araucanía','CURARREHUE','Corp. Municipal'),
('6037','ESCUELA PUENTE BASA','La Araucanía','CURARREHUE','Corp. Municipal'),
('6038','COMPLEJO EDUCACIONAL RUKA NGEN','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6039','ESCUELA PARTICULAR CATRIPULLI','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6040','ECO ESCUELA ANTU MAWIDA','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6041','ESCUELA PARTICULAR LOS RAULIES','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6042','ESCUELA PARTICULAR VIRGEN DE RINCONADA','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6043','ESCUELA PARTICULAR LONCOFILO','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6044','ESCUELA PARTICULAR MAITE','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6045','ESCUELA PARTICULAR PANQUE','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6046','ESCUELA PARTICULAR MAITE ALTO','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6048','ESCUELA PARTICULAR MAICHIN','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6051','LICEO BICENTENARIO   HOTELERIA Y TURISMO','La Araucanía','PUCÓN','Corp. Municipal'),
('6052','ESCUELA CARLOS HOLZAFEL','La Araucanía','PUCÓN','Corp. Municipal'),
('6053','ESCUELA JOSE MIGUEL MARTINEZ SOTO','La Araucanía','PUCÓN','Corp. Municipal'),
('6054','ESC. BASICA QUELHUE','La Araucanía','PUCÓN','Corp. Municipal'),
('6056','ESCUELA BASICA MUNICIPAL DE EL CLARO','La Araucanía','PUCÓN','Corp. Municipal'),
('6060','ESC. BASICA VILLA SAN PEDRO','La Araucanía','PUCÓN','Corp. Municipal'),
('6062','ESC. BASICA PICHARES','La Araucanía','PUCÓN','Corp. Municipal'),
('6063','ESC. BASICA CANDELARIA','La Araucanía','PUCÓN','Corp. Municipal'),
('6066','ESC. BASICA CARILEUFU','La Araucanía','PUCÓN','Corp. Municipal'),
('6069','ESC.BASICA PAILLACO','La Araucanía','PUCÓN','Corp. Municipal'),
('6070','COMPLEJO EDUCACIONAL PABLO SEXTO','La Araucanía','PUCÓN','Part. Subvencionado'),
('6071','ESCUELA PARTICULAR NTRA.SRA.DE FATIMA','La Araucanía','PUCÓN','Part. Subvencionado'),
('6072','ESCUELA PARTICULAR RAMON GUINEZ','La Araucanía','PUCÓN','Part. Subvencionado'),
('6075','ESCUELA PARTICULAR SAN LUIS','La Araucanía','PUCÓN','Part. Subvencionado'),
('6076','ESCUELA PARTICULAR CABURGUA','La Araucanía','PUCÓN','Part. Subvencionado'),
('6077','ESCUELA PARTICULAR QUETROLELFU','La Araucanía','PUCÓN','Part. Subvencionado'),
('6082','ESCUELA SANTA ROSA DE LLAFENCO','La Araucanía','PUCÓN','Part. Subvencionado'),
('6083','ESCUELA PARTICULAR RELICURA','La Araucanía','PUCÓN','Part. Subvencionado'),
('6084','LICEO BICENTENARIO ARAUCANÍA','La Araucanía','VILLARRICA','Corp. Municipal'),
('6085','LICEO BICENTENARIO DE EXCELENCIA POLITECNICO VILLARRICA','La Araucanía','VILLARRICA','Corp. Municipal'),
('6086','ESCUELA JOSE ABELARDO NUNEZ','La Araucanía','VILLARRICA','Corp. Municipal'),
('6087','LICEO BICENTENARIO DE EXCELENCIA ARTÍSTICO ALEXANDER GRAHAM BELL','La Araucanía','VILLARRICA','Corp. Municipal'),
('6088','ESCUELA VALENTIN LETELIER','La Araucanía','VILLARRICA','Corp. Municipal'),
('6089','ESCUELA VOIPIR DE NANCUL','La Araucanía','VILLARRICA','Corp. Municipal'),
('6090','ESCUELA MARIANO LATORRE','La Araucanía','VILLARRICA','Corp. Municipal'),
('6091','ESC.ESP.RET.MENTAL BEATO LUIS ORIONE','La Araucanía','VILLARRICA','Corp. Municipal'),
('6092','ESCUELA EPUKLEI','La Araucanía','VILLARRICA','Corp. Municipal'),
('6093','ESCUELA MOLCO ALTO','La Araucanía','VILLARRICA','Corp. Municipal'),
('6097','ESCUELA LAS VERTIENTES','La Araucanía','VILLARRICA','Corp. Municipal'),
('6107','ESCUELA CONQUIL','La Araucanía','VILLARRICA','Corp. Municipal'),
('6108','ESCUELA MANANTIAL','La Araucanía','VILLARRICA','Corp. Municipal'),
('6112','COLEGIO DE HUMANIDADES DE VILLARICA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6113','ESCUELA INDUSTRIAL SAN JOSE','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6115','LICEO BICENTENARIO DE EXCELENCIA SAN AGUSTÍN','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6116','ESCUELA PARTICULAR SAGRADA FAMILIA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6117','ESCUELA PARTICULAR NANCUL','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6118','COLEGIO SANTA CRUZ','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6119','LICEO PART. LIBERTAD','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6120','COLEGIO ALBERTO HURTADO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6121','ESCUELA PARTICULAR PUCARA ALTO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6122','ESCUELA PARTICULAR ADVENTISTA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6123','ESCUELA PARTICULAR ARTURO PRAT','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6124','ESCUELA PARTICULAR PEDRO AGUIRRE CERDA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6126','ESCUELA PARTICULAR NUEVA ESPERANZA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6127','ESCUELA PARTICULAR CUDICO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6129','COLEGIO INGLES CAMBRIDGE VILLARRICA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6135','ESCUELA PARTICULAR LUIS CRUZ MARTINEZ','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6137','ESCUELA PARTICULAR SAN LUIS','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6138','ESCUELA PARTICULAR CALFUTUE','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6139','ESCUELA PARTICULAR SANTA RITA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6140','ESCUELA PARTICULAR NUEVA LONCOTRARO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6142','ESCUELA PARTICULAR LIUMALLA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6143','ESCUELA PARTICULAR RAYENKO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6147','ESCUELA PARTICULAR NELTUME','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6149','ESCUELA PARTICULAR SANTA FILOMENA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6151','ESCUELA PARTICULAR PUENTE BASA','La Araucanía','CURARREHUE','Part. Subvencionado'),
('6154','ESCUELA PARTICULAR CURILELFU','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6155','ESCUELA PARTICULAR SAN FRANCISCO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6157','ESCUELA PARTICULAR VIRGEN CANDELARIA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6160','ESCUELA PARTICULAR CARMELITA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('6161','COLEGIO ALEMAN VILLARRICA','La Araucanía','VILLARRICA','Part. Pagado'),
('6163','LICEO BICENTENARIO DE EXCELENCIA JUAN SCHLEYER','La Araucanía','FREIRE','Corp. Municipal'),
('6164','ESCUELA JUAN SEGUEL','La Araucanía','FREIRE','Corp. Municipal'),
('6165','ESCUELA RAIMAPU','La Araucanía','FREIRE','Corp. Municipal'),
('6166','ESCUELA LA ESPERANZA','La Araucanía','FREIRE','Corp. Municipal'),
('6167','ESC. ESP.RET.MENTAL PAUL HARRIS','La Araucanía','FREIRE','Corp. Municipal'),
('6168','ESCUELA LENFUEN','La Araucanía','PADRE LAS CASAS','Corp. Municipal'),
('6170','ESCUELA ARMANDO QUINTULEN','La Araucanía','FREIRE','Corp. Municipal'),
('6173','ESCUELA RUCAHUE','La Araucanía','FREIRE','Corp. Municipal'),
('6175','ESCUELA LAS PALMERAS','La Araucanía','FREIRE','Corp. Municipal'),
('6177','ESCUELA CACIQUE AILLANIR','La Araucanía','FREIRE','Corp. Municipal'),
('6178','ESCUELA BASICA QUETROCO','La Araucanía','FREIRE','Corp. Municipal'),
('6179','ESCUELA RURAL EL LLIUCO','La Araucanía','FREIRE','Corp. Municipal'),
('6180','ESCUELA DOLLINCO','La Araucanía','FREIRE','Corp. Municipal'),
('6181','ESCUELA COIPUE','La Araucanía','FREIRE','Corp. Municipal'),
('6183','ESCUELA ALLIPEN','La Araucanía','FREIRE','Corp. Municipal'),
('6188','COLEGIO SANTA CRUZ DE FREIRE','La Araucanía','FREIRE','Part. Subvencionado'),
('6189','ESCUELA PARTICULAR ARTURO PRAT','La Araucanía','FREIRE','Part. Subvencionado'),
('6190','ESCUELA PARTICULAR GENERAL PRIETO','La Araucanía','FREIRE','Part. Subvencionado'),
('6192','ESCUELA PARTICULAR LAS PATAGUAS','La Araucanía','FREIRE','Part. Subvencionado'),
('6198','COLEGIO AYÜN MAPU','La Araucanía','FREIRE','Part. Subvencionado'),
('6200','ESCUELA PARTICULAR EL TESORO','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('6204','ESCUELA PARTICULAR SAN ISIDRO LABRADOR','La Araucanía','FREIRE','Part. Subvencionado'),
('6205','ESCUELA PARTICULAR SAN MANUEL DE LOLEN','La Araucanía','FREIRE','Part. Subvencionado'),
('6206','ESCUELA PARTICULAR ROSARIO VASQUEZ DE V.','La Araucanía','FREIRE','Part. Subvencionado'),
('6207','ESCUELA PARTICULAR RUPAYAN DE MALLOHUE','La Araucanía','FREIRE','Part. Subvencionado'),
('6208','REDUCCIÓN PAINEMIL','La Araucanía','FREIRE','Part. Subvencionado'),
('6210','LICEO AGRICOLA PUQUEREO','La Araucanía','FREIRE','Part. Subvencionado'),
('6211','ESCUELA PARTICULAR MAHUIDACHE','La Araucanía','FREIRE','Part. Subvencionado'),
('6214','ESCUELA PARTICULAR RENACER','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('6216','ESCUELA PARTICULAR SAN ANTONIO','La Araucanía','FREIRE','Part. Subvencionado'),
('6219','ESCUELA PARTICULAR TRAPILHUE','La Araucanía','FREIRE','Part. Subvencionado'),
('6220','ESCUELA PARTICULAR PATRIA NUEVA','La Araucanía','FREIRE','Part. Subvencionado'),
('6221','ESCUELA PARTICULAR SAN ROQUE','La Araucanía','FREIRE','Part. Subvencionado'),
('6222','ESCUELA PARTICULAR SANTA ELENA','La Araucanía','FREIRE','Part. Subvencionado'),
('6223','LICEO BICENTENARIO CIENCIAS Y HUMANIDADES RBD 6223-5','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6224','ESCUELA UNION LATINOAMERICANA','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6225','ESCUELA JUAN BTA. CHESTA CH.','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6227','ESCUELA LAS AMERICAS','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6228','ESCUELA RIO TOLTEN','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6230','LICEO MUNICIPAL LA FRONTERA','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6231','ESC. BASICA LOS GALPONES','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6237','ESCUELA NUEVO HORIZONTE','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6244','ESCUELA SUSANA ORTIZ','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6245','ESCUELA EL ESFUERZO','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6248','ESCUELA CHADA','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6251','ESCUELA RESERVA FORESTAL MAHUIDANCHI','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('6252','LICEO BICENTENARIO POLITECNICO PITRUFQUEN','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6253','LICEO BICENTENARIO DE EXCELENCIA MONSEÑOR GUILLERMO HARTL','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6254','COLEGIO MADRES DOMINICAS','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6262','ESCUELA PARTICULAR RESERVA RAIN','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6263','ESCUELA PARTICULAR MUNE BAJO','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6267','LICEO PARTICULAR SUBV.QUINQUE','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6268','ESCUELA PARTICULAR HUEFEL COMUY','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('6269','LICEO BICENTENARIO COMPLEJO EDUCACIONAL ANDRES ANTONIO GORBEA','La Araucanía','GORBEA','Corp. Municipal'),
('6270','LICEO JOSE VICTORINO LASTARRIA','La Araucanía','GORBEA','Corp. Municipal'),
('6271','ESCUELA BASICA CINCO','La Araucanía','GORBEA','Corp. Municipal'),
('6272','ESCUELA BASICA LICARAYEN','La Araucanía','GORBEA','Corp. Municipal'),
('6273','ESC.PRESBITERO JOSE AGUSTIN GOMEZ Z.','La Araucanía','GORBEA','Corp. Municipal'),
('6276','ESCUELA BASICA MUNICIPAL SAN JUSTO','La Araucanía','GORBEA','Corp. Municipal'),
('6279','ESCUELA MELIRREHUE','La Araucanía','GORBEA','Corp. Municipal'),
('6280','ESCUELA BASICA EL RINCO','La Araucanía','GORBEA','Corp. Municipal'),
('6281','ESCUELA EL LIUCO','La Araucanía','GORBEA','Corp. Municipal'),
('6282','ESCUELA EL LAUREL','La Araucanía','GORBEA','Corp. Municipal'),
('6283','ESCUELA CUARTA FAJA','La Araucanía','GORBEA','Corp. Municipal'),
('6285','ESCUELA BASICA LOS PERALES','La Araucanía','GORBEA','Corp. Municipal'),
('6289','ESCUELA FAJA RICCI','La Araucanía','GORBEA','Corp. Municipal'),
('6290','ESCUELA PIDENCO ALTO','La Araucanía','GORBEA','Corp. Municipal'),
('6294','ESCUELA PARTICULAR NTRA.SRA.DEL CARMEN','La Araucanía','GORBEA','Part. Subvencionado'),
('6300','COLEGIO JUAN PABLO II','La Araucanía','GORBEA','Part. Subvencionado'),
('6301','LICEO BICENTENARIO DE EXCELENCIA TÉCNICO PROFESIONAL ANDRÉS BELLO','La Araucanía','LONCOCHE','Corp. Municipal'),
('6302','LICEO BICENTENARIO PADRE ALBERTO HURTADO CRUCHAGA','La Araucanía','LONCOCHE','Corp. Municipal'),
('6303','ESCUELA EGON ERNTS KEUTMANN BESGEN','La Araucanía','LONCOCHE','Corp. Municipal'),
('6304','ESCUELA ALBORADA','La Araucanía','LONCOCHE','Corp. Municipal'),
('6305','ESCUELA DOMITILA PINNA PARRA','La Araucanía','LONCOCHE','Corp. Municipal'),
('6308','CENTRO EDUCACIONAL DE DESARROLLO INTEGRAL WE NEPEN','La Araucanía','LONCOCHE','Corp. Municipal'),
('6315','ESCUELA RUCAHUE','La Araucanía','LONCOCHE','Corp. Municipal'),
('6317','ESCUELA EL CASTILLO','La Araucanía','VILLARRICA','Corp. Municipal'),
('6319','ESCUELA ESMERALDA','La Araucanía','LONCOCHE','Corp. Municipal'),
('6322','ESCUELA WINGKUL-NIGEN','La Araucanía','LONCOCHE','Corp. Municipal'),
('6323','ESCUELA WENUY KUDAU','La Araucanía','LONCOCHE','Corp. Municipal'),
('6325','ESCUELA PUKOYAM','La Araucanía','LONCOCHE','Corp. Municipal'),
('6327','ESCUELA ESTADO DE ISRAEL','La Araucanía','LONCOCHE','Corp. Municipal'),
('6329','ESCUELA QUESQUECHAN','La Araucanía','LONCOCHE','Corp. Municipal'),
('6332','ESCUELA BASICA NILCAHUIN','La Araucanía','LONCOCHE','Corp. Municipal'),
('6336','COLEGIO SANTA CRUZ DE LONCOCHE','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6337','ESCUELA PARTICULAR JUAN XXIII','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6343','ESCUELA PARTICULAR COLLICO','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6344','ESCUELA PARTICULAR LIGLELFUN','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6345','ESCUELA PARTICULAR PULMAHUE','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6347','ESCUELA PARTICULAR SUBVENCIONADA LA FAMILIA','La Araucanía','LONCOCHE','Part. Subvencionado'),
('6348','COMPLEJO EDUCACIONAL MARTIN KLEINKNECHT','La Araucanía','TOLTÉN','Servicio Local'),
('6349','ESCUELA AGUAS Y GAVIOTAS','La Araucanía','TOLTÉN','Servicio Local'),
('6350','ESCUELA RAYEN LAFQUEN QUEULE','La Araucanía','TOLTÉN','Servicio Local'),
('6351','ESCUELA EL SEMBRADOR','La Araucanía','TOLTÉN','Servicio Local'),
('6352','ESCUELA AMANECER DE VILLA LOS BOLDOS','La Araucanía','TOLTÉN','Servicio Local'),
('6353','ESCUELA SAN PEDRO','La Araucanía','TOLTÉN','Servicio Local'),
('6354','ESCUELA LA CASCADA','La Araucanía','TOLTÉN','Servicio Local'),
('6358','ESCUELA BASICA ESTACION TOLTEN','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6361','ESCUELA DE CAYCHAYEN','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6363','ESCUELA PUCHILCO','La Araucanía','TOLTÉN','Servicio Local'),
('6370','ESCUELA LA CONCEPCION','La Araucanía','TOLTÉN','Servicio Local'),
('6371','ESCUELA ANTU-LAFQUEN','La Araucanía','TOLTÉN','Servicio Local'),
('6373','ESCUELA PORMA','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6374','ESCUELA BASICA RURAL FLOR DEL VALLE','La Araucanía','TOLTÉN','Servicio Local'),
('6377','ESCUELA DE CAMAGUEY','La Araucanía','TOLTÉN','Servicio Local'),
('6379','ESCUELA PART. SUBV. SAN JOSÈ OBRERO','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6380','ESCUELA PARTICULAR SUBVENCIONADA PADRE ISIDORO','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6381','ESCUELA PARTICULAR PURALACO','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6382','ESCUELA PARTICULAR RAQUINCURA','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6385','ESCUELA PARTICULAR CHANQUIN','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6389','ESCUELA POCOYAN','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6390','ESCUELA PARTICULAR ARAUCANA PELEHUE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6391','ESCUELA PARTICULAR VILLA BOLDOS','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6393','ESCUELA PARTICULAR FRUTILLAR','La Araucanía','TOLTÉN','Part. Subvencionado'),
('6397','LICEO MUNICIPAL BARROS ARANA','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6398','COMPLEJO EDUCACIONAL NUEVA ALBORADA','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6399','ESCUELA HORIZONTES','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6400','ESCUELA ISLA LLICAN','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6407','ESCUELA NOHUALHUE','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6410','ESCUELA MALALHUE','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6411','ESCUELA PUYEHUE','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6413','ESCUELA DE RUCA-CURA','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6415','ESCUELA LOS TRONCOS','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('6420','ESCUELA PARTICULAR PADRE ALEJANDRO ORTEGA','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6421','ESCUELA PARTICULAR BAUTISTA','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6423','ESCUELA PARTICULAR HUALPIN','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6424','ESCUELA PARTICULAR ARTURO ALESSANDRI','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6425','ESCUELA PARTICULAR QUILIMANZANO','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6427','ESCUELA PARTICULAR QUILMER','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6429','ESCUELA PARTICULAR REBECA MATTE BELLO','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6432','ESCUELA PARTICULAR ALTO CHELLE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6433','ESCUELA PARTICULAR HUILO','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6434','ESCUELA PARTICULAR PORMA','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6435','ESCUELA PARTICULAR HUIDIMA','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6442','ESCUELA PARTICULAR LAS DELICIAS','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6443','ESCUELA PART. KOM PU LOF NI KIMELTUWE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6446','ESCUELA PARTICULAR SAN MIGUEL DE TRAUHUE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('6452','LICEO REINO DE SUECIA','La Araucanía','SAAVEDRA','Servicio Local'),
('6454','ESCUELA BASICA COLLICO RANCO','La Araucanía','SAAVEDRA','Servicio Local'),
('6455','ESCUELA BASICA BARTOLO LLANCALEO','La Araucanía','SAAVEDRA','Servicio Local'),
('6456','ESCCUELA BASICA INALAFQUEN','La Araucanía','SAAVEDRA','Servicio Local'),
('6457','ESC. BASICA AUGUSTO WINTER TAPIA','La Araucanía','SAAVEDRA','Servicio Local'),
('6458','ESCUELA BASICA CALOF','La Araucanía','SAAVEDRA','Servicio Local'),
('6459','ESC. BASICA ANTONIO LADINO','La Araucanía','SAAVEDRA','Servicio Local'),
('6460','ESCUELA PARTICULAR SAN SEBASTIAN','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6461','ESCUELA PARTICULAR PADRE JUAN WEVERING','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6464','ESCUELA PARTICULAR HUAPI','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6465','LICEO PART. SUBVENC. LA SIERRA','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6471','ESCUELA PARTICULAR SOL NACIENTE','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6474','ESCUELA PARTICULAR QUIFO','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6475','ESCUELA PARTICULAR LLAGUEY','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6477','ESCUELA PARTICULAR PERQUINAN','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6478','ESCUELA PARTICULAR PIEDRA ALTA','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6479','ESCUELA PARTICULAR DEUME','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6480','ESCUELA PARTICULAR NUEVA RUCATRARO','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6481','ESCUELA PARTICULAR CHEUCAN','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6482','ESCUELA PARTICULAR NUEVO QUIFO','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6485','ESCUELA PADRE ERNESTO WILHELM','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6486','ESCUELA PARTICULAR SAN GASTON','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6487','ESCUELA PARTICULAR LOS CISNES','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6488','ESCUELA PARTICULAR DIEGO PORTALES','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6490','ESCUELA PARTICULAR MANUEL ROJAS','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6492','ESCUELA PARTICULAR DAGOBERTO GODOY','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6495','ESCUELA RUCA RAQUI','La Araucanía','SAAVEDRA','Servicio Local'),
('6496','ESCUELA GABRIELA MISTRAL','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('6497','LICEO PUBLICO BICENTENARIO DE EXCELENCIA CLAUDIO ARRAU LEON','La Araucanía','CARAHUE','Servicio Local'),
('6499','ROMILIO ADRIAZOLA','La Araucanía','CARAHUE','Servicio Local'),
('6500','COMPLEJO EDUCACIONAL DARÍO SALAS','La Araucanía','CARAHUE','Servicio Local'),
('6501','ESCUELA BASICA KIM RUKA','La Araucanía','CARAHUE','Servicio Local'),
('6502','ESCUELA BASICA NEHUENTUE','La Araucanía','CARAHUE','Servicio Local'),
('6504','ESCUELA TRANAPUENTE','La Araucanía','CARAHUE','Servicio Local'),
('6506','ESCUELA MUNICIPAL DINAMARCA','La Araucanía','CARAHUE','Servicio Local'),
('6508','ESCUELA BASICA DINAMARCA, LUCERO','La Araucanía','CARAHUE','Servicio Local'),
('6510','ESCUELA BASICA PAILACOYAN','La Araucanía','CARAHUE','Servicio Local'),
('6512','ESCUELA VILLA LAS ARAUCARIAS','La Araucanía','CARAHUE','Servicio Local'),
('6515','ESCUELA CATRIPULLI','La Araucanía','CARAHUE','Servicio Local'),
('6518','ESCUELA BASICA EL MANZANO','La Araucanía','CARAHUE','Servicio Local'),
('6521','ESCUELA BASICA CAMARONES','La Araucanía','CARAHUE','Servicio Local'),
('6522','ESCUELA BASICA PUYANGUE','La Araucanía','CARAHUE','Servicio Local'),
('6523','ESCUELA BASICA CHOMIO','La Araucanía','CARAHUE','Servicio Local'),
('6524','ESCUELA CULLINCO','La Araucanía','CARAHUE','Servicio Local'),
('6526','ESCUELA BASICA EL PERAL','La Araucanía','CARAHUE','Servicio Local'),
('6528','ESCUELA BASICA BAJO YUPEHUE','La Araucanía','CARAHUE','Servicio Local'),
('6529','ESCUELA BASICA MATTE Y SANCHEZ','La Araucanía','CARAHUE','Servicio Local'),
('6539','ESCUELA BASICA COI COI','La Araucanía','CARAHUE','Servicio Local'),
('6540','ESCUELA BASICA COLICO','La Araucanía','CARAHUE','Servicio Local'),
('6542','ESCUELA PARTICULAR ADVENTISTA','La Araucanía','CARAHUE','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
