-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 4 de 31 | filas 1201-1600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('1758','ESCUELA DE PARVULOS CRISOLITO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1759','COLEGIO SAN LUIS DE MIRAFLORES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1760','ESCUELA ESPECIAL JUAN SANDOVAL C.','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1761','COLEGIO FRIENDLY HIGH SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1763','CENTRO TRAT. INTEGRAL LAS DALIAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1769','COLEGIO RAYEN CAVEN','Valparaíso','CONCÓN','Part. Subvencionado'),
('1772','COLEGIO BLANCA VERGARA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1774','SEMINARIO SAN RAFAEL','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1775','COLEGIO ARABE','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1776','SAINT PETER´S SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1777','COLEGIO SAINT DOMINIC','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1780','COLEGIO PATMOS','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1781','ALLIANCE FRANCAISE DE VALPARAISO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1783','COLEGIO BRITANICO ST. MARGARET`S S.A.','Valparaíso','CONCÓN','Part. Pagado'),
('1787','HEBREO DR. JAIM WEITZMAN','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1788','THE MACKAY SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1789','COLEGIO PROFESOR HUGUET','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1791','SAINT PAUL´S SCHOOL','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1792','COLEGIO DE LOS SAGRADOS CORAZONES (ALVAREZ)','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1795','COLEGIO SAN IGNACIO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1796','COLEGIO COMPAÑIA DE MARIA','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1801','COLEGIO MARIA AUXILIADORA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1803','ESC. STA. TERESITA DE JESUS','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1807','ESCUELA JEFFERSON SCHOOL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1819','COLLEGE CHRETIEN FRANCAIS LE BEAU JOUR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1826','JARDIN INFANTIL CONEJITO COSTALIN','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1828','JARDIN INFANTIL ARCO IRIS','Valparaíso','CONCÓN','Part. Pagado'),
('1839','COLEGIO ALEMAN DE VALPARAISO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1840','LICEO MAX PLANCK','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1842','COLEGIO SAN ANDRES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1844','COLEGIO FRANCO INGLES','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1847','COLEGIO SAINT MICHAEL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1851','LICEO POLITECNICO QUINTERO','Valparaíso','QUINTERO','Servicio Local'),
('1853','COLEGIO ARTÍSTICO COSTA MAUCO','Valparaíso','QUINTERO','Servicio Local'),
('1855','ESCUELA BASICA REPUBLICA DE FRANCIA','Valparaíso','QUINTERO','Servicio Local'),
('1856','ESCUELA MANTAGUA','Valparaíso','QUINTERO','Servicio Local'),
('1857','ESCUELA JUAN JOSE TORTEL','Valparaíso','QUINTERO','Servicio Local'),
('1858','COLEGIO DON ORIONE','Valparaíso','QUINTERO','Part. Subvencionado'),
('1859','COLEGIO SANTA FILOMENA','Valparaíso','QUINTERO','Part. Subvencionado'),
('1860','COLEGIO INGLES','Valparaíso','QUINTERO','Part. Subvencionado'),
('1863','COLEGIO GENERAL JOSE VELASQUEZ BORQUEZ','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1864','COMPLEJO EDUCACIONAL SARGENTO ALDEA','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1867','COLEGIO LA GREDA','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1868','ESCUELA LA CHOCOTA','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1869','ESCUELA LOS MAQUIS','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1870','ESCUELA CAMPICHE','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1871','ESCUELA BASICA EL RINCON','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1873','ESCUELA HORCON','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1874','ESCUELA BASICA LA LAGUNA','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1875','COLEGIO MAITENCILLO','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1876','ESCUELA BASICA LA QUEBRADA','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1877','ESCUELA PUCALAN','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1878','ESCUELA BASICA EL RUNGUE','Valparaíso','PUCHUNCAVÍ','Servicio Local'),
('1880','COLEGIO INDUSTRIAL ANDRES BELLO LOPEZ','Valparaíso','QUILPUÉ','Municipal'),
('1881','COLEGIO LUIS CRUZ MARTÍNEZ','Valparaíso','QUILPUÉ','Municipal'),
('1882','LICEO GUILLERMO GRONEMEYER ZAMORANO','Valparaíso','QUILPUÉ','Municipal'),
('1884','LICEO COMERCIAL ALEJANDRO LUBET V','Valparaíso','QUILPUÉ','Municipal'),
('1885','COLEGIO CAPITAN IGNACIO CARRERA PINTO','Valparaíso','QUILPUÉ','Municipal'),
('1886','COLEGIO MANUEL BULNES PRIETO','Valparaíso','QUILPUÉ','Municipal'),
('1887','ESCUELA GUARDIAMARINA GUILLERMO ZANARTU I.','Valparaíso','QUILPUÉ','Municipal'),
('1888','ESC.CDTE. ELEUTERIO RAMIREZ MOLINA','Valparaíso','QUILPUÉ','Municipal'),
('1889','COLEGIO FERNANDO DURAN VILLARREAL','Valparaíso','QUILPUÉ','Municipal'),
('1890','COLEGIO JOSE MIGUEL INFANTE','Valparaíso','QUILPUÉ','Municipal'),
('1891','ESCUELA BASICA JORGE ROCK LARA','Valparaíso','QUILPUÉ','Municipal'),
('1892','ESCUELA BASICA GASPAR CABRALES','Valparaíso','QUILPUÉ','Municipal'),
('1893','ESCUELA BASICA DARIO SALAS','Valparaíso','QUILPUÉ','Municipal'),
('1894','CENTRO DE EDUCACION DE ADULTOS','Valparaíso','QUILPUÉ','Municipal'),
('1895','LICEO TECNICO PROFESIONAL MANNHEIM','Valparaíso','QUILPUÉ','Municipal'),
('1898','ESCUELA THEODOR HEUSS','Valparaíso','QUILPUÉ','Municipal'),
('1899','ESCUELA TENIENTE IGNACIO SERRANO MONTANER','Valparaíso','QUILPUÉ','Municipal'),
('1900','ESCUELA LOS MOLLES DE MARGA MARGA','Valparaíso','QUILPUÉ','Municipal'),
('1901','ESCUELA SANTIAGO BUERAS','Valparaíso','QUILPUÉ','Municipal'),
('1906','ESCUELA DELFINA ALARCON HENRIQUEZ','Valparaíso','QUILPUÉ','Municipal'),
('1908','COLEGIO ULISES GNECCO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1909','COLEGIO LIAHONA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1911','COLEGIO CREP','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1917','ESCUELA PARTICULAR EXEQUIEL PUELMA SILVA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1918','COLEGIO LOS LEONES DE QUILPUE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1919','COLEGIO H. F. CAMILO HENRIQUEZ','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1923','COLEGIO CRISTIANO DE QUILPUE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1924','ESCUELA PARTICULAR INFANTES DEL SOL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1930','ABRAHAM LINCOLN MEMORIAL COLLEGE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1931','KING EDWARD SCHOOL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1932','COLEGIO PANAL II','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1934','COLEGIO ESPERANZA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1937','COLEGIO COEDUCACIONAL PART. QUILPUE','Valparaíso','QUILPUÉ','Part. Pagado'),
('1941','COLEGIO EL BELLOTO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('1949','JARDIN INFANTIL COLIBRI','Valparaíso','QUILPUÉ','Part. Pagado'),
('1958','LICEO TECNOLOGICO VILLA ALEMANA','Valparaíso','VILLA ALEMANA','Municipal'),
('1959','WINDMILL COLLEGE','Valparaíso','VILLA ALEMANA','Municipal'),
('1961','ESCUELA LATINA INES GALLARDO ORELLANA','Valparaíso','VILLA ALEMANA','Municipal'),
('1963','ESCUELA BASICA DIEGO BARROS ARANA','Valparaíso','VILLA ALEMANA','Municipal'),
('1965','COLEGIO ITALO COMPOSTO SCARPATI','Valparaíso','VILLA ALEMANA','Municipal'),
('1966','ESCUELA BASICA CATALUNYA','Valparaíso','VILLA ALEMANA','Municipal'),
('1967','LICEO BICENTENARIO TÉCNICO PROFESIONAL MARY GRAHAM','Valparaíso','VILLA ALEMANA','Municipal'),
('1968','ESCUELA MELVIN JONES','Valparaíso','VILLA ALEMANA','Municipal'),
('1969','COLEGIO CHARLES DARWIN','Valparaíso','VILLA ALEMANA','Municipal'),
('1970','ESCUELA DIEGO PORTALES','Valparaíso','VILLA ALEMANA','Municipal'),
('1971','ESCUELA MANUEL MONTT','Valparaíso','VILLA ALEMANA','Municipal'),
('1972','ESCUELA DE EDUC. DIFERENCIAL NUEVO AMANECER','Valparaíso','VILLA ALEMANA','Municipal'),
('1975','ESCUELA JUAN BAUTISTA ALBERDI','Valparaíso','VILLA ALEMANA','Municipal'),
('1976','ESCUELA EL PATAGUAL','Valparaíso','VILLA ALEMANA','Municipal'),
('1977','COLEGIO NACIONAL','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('1980','COLEGIO PARTICULAR JEAN PIAGET','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('1985','CENTRO INFANTIL EL BUEN CAMINO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('1987','COLEGIO NUEVO CHILENO BRITANICO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('1989','INTERNADO ALEMAN','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('1996','LICEO MANUEL DE SALAS','Valparaíso','CASABLANCA','Corp. Municipal'),
('1997','ESCUELA DOMINGO ORTIZ DE ROZAS','Valparaíso','CASABLANCA','Corp. Municipal'),
('1998','ESCUELA ARTURO ECHAZARRETA LARRAIN','Valparaíso','CASABLANCA','Corp. Municipal'),
('1999','ESCUELA MANUEL BRAVO REYES','Valparaíso','CASABLANCA','Corp. Municipal'),
('2003','ESCUELA SAN PEDRO DE QUINTAY','Valparaíso','CASABLANCA','Corp. Municipal'),
('2005','ESCUELA BASICA LAGUNILLAS','Valparaíso','CASABLANCA','Corp. Municipal'),
('2007','COLEGIO PARTIC. JULIO MONTT SALAMANCA','Valparaíso','CASABLANCA','Part. Subvencionado'),
('2008','ESCUELA PURISIMA DE LO VASQUEZ','Valparaíso','CASABLANCA','Part. Subvencionado'),
('2009','COLEGIO INSULAR ROBINSON CRUSOE','Valparaíso','JUAN FERNÁNDEZ','Servicio Local'),
('2011','ESCUELA ESPECIAL DIVINO MAESTRO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2012','PROFESOR JUAN DANTE PARRAGUEZ ARELLANO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2013','INST.COMERCIAL MARITIMO PACIFICO SUR','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2014','ESCUELA POETA PABLO NERUDA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2017','ESCUELA VILLA LAS DUNAS','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2018','ESCUELA MOVILIZADORES PORTUARIOS','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2019','COLEGIO ESPANA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2020','ESCUELA PRESIDENTE PEDRO AGUIRRE CERDA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2021','PADRE ANDRE COINDRE','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2022','ESCUELA BASICA SAN JOSE DE CALASANZ','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2023','ESCUELA CRISTO DEL MAIPO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2024','PROFESOR PEDRO VIVEROS ORMENO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2025','ESCUELA PRE-BASICA PETER PAN','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2026','ESCUELA BASICA CERRO PLACILLA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2027','ESCUELA POETA HUIDOBRO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2028','PARVULARIO RAYITO DE SOL','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2035','COLEGIO AGRÍCOLA CUNCUMÉN GONZALO BARROS AMUNÁTEGUI','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2036','ESCUELA BASICA LEYDA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2037','EDUARDO FERNANDEZ DE ASTURIAS','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2038','ESCUELA BASICA EL ASILO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('2040','LICEO NACIONAL DE LLO LLEO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2041','LICEO SANTA TERESITA DE LLOLLEO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2042','INSTITUTO DEL PUERTO DE SAN ANTONIO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2043','INSTITUTO ERCILLA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2044','ESCUELA INDUSTRIAL SAN ANTONIO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2045','LICEO GABRIELA MISTRAL','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2047','COLEGIO PARTICULAR SARA CRUCHAGA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2048','COLEGIO SAGRADA FAMILIA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2049','COLEGIO FUND.EDUC. FERNANDEZ LEON','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2050','COLEGIO NUESTRA SENORA DE POMPEYA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2052','COLEGIO PROVIDENCIA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2053','INSTITUTO PSICOPEDAGOGICO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2054','COLEGIO PART.GUILLERMO BLEST GANA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2055','COLEGIO EL RETIRO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('2064','LICEO POETA VICENTE HUIDOBRO','Valparaíso','CARTAGENA','Corp. Municipal'),
('2065','ESCUELA PRESIDENTE AGUIRRE CERDA','Valparaíso','CARTAGENA','Corp. Municipal'),
('2066','LICEO EUGENIA SUBERCASEAUX','Valparaíso','CARTAGENA','Corp. Municipal'),
('2068','ESCUELA CARMEN ROMERO AGUIRRE','Valparaíso','CARTAGENA','Corp. Municipal'),
('2069','ESCUELA LO ZARATE','Valparaíso','CARTAGENA','Corp. Municipal'),
('2071','ESCUELA BASICA SAN FRANCISCO','Valparaíso','CARTAGENA','Corp. Municipal'),
('2074','ESCUELA BASICA LAS CRUCES','Valparaíso','EL TABO','Corp. Municipal'),
('2075','COLEGIO EL TABO','Valparaíso','EL TABO','Corp. Municipal'),
('2076','ESCUELA BASICA QUILLAYCILLO','Valparaíso','EL TABO','Corp. Municipal'),
('2078','COMPLEJO EDUCACIONAL CLARA SOLOVERA','Valparaíso','EL QUISCO','Corp. Municipal'),
('2079','ESCUELA POETA NERUDA DE ISLA NEGRA','Valparaíso','EL QUISCO','Corp. Municipal'),
('2081','ESCUELA EL TOTORAL','Valparaíso','EL QUISCO','Corp. Municipal'),
('2083','ESC.PART. SAN MIGUEL ARCANGEL','Valparaíso','EL QUISCO','Part. Subvencionado'),
('2084','COLEGIO CARLOS ALESSANDRI ALTAMIRANO','Valparaíso','ALGARROBO','Corp. Municipal'),
('2085','ESCUELA BASICA RURAL EL YECO','Valparaíso','ALGARROBO','Corp. Municipal'),
('2087','ESCUELA BASICA RURAL SAN JOSE','Valparaíso','ALGARROBO','Corp. Municipal'),
('2089','ESCUELA PARTICULAR SAN JOSE','Valparaíso','ALGARROBO','Part. Subvencionado'),
('2090','COLEGIO TERESA DE LOS ANDES-ALGARROBO','Valparaíso','ALGARROBO','Part. Subvencionado'),
('2091','COLEGIO BICENTENARIO PEOPLE HELP PEOPLE','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('2092','ESCUELA EL CONVENTO','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('2093','ESCUELA BUCALEMITO','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('2095','ESCUELA BASICA JUANITA FERNANDEZ S.','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('2096','ESCUELA BASICA CLAUDIO VICUNA','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('2099','COLEGIO STO. DOMINGO HELEN LEE LASSEN','Valparaíso','SANTO DOMINGO','Part. Subvencionado'),
('2101','COLEGIO BASICO LORENZO BAEZA VEGA','Valparaíso','ISLA DE PASCUA','Corp. Municipal'),
('2102','LICEO TECNICO A-4','O''Higgins','RANCAGUA','Adm. Delegada'),
('2103','LICEO BICENTENARIO INDUSTRIAL PRESIDENTE PEDRO AGUIRRE','O''Higgins','RANCAGUA','Adm. Delegada'),
('2104','LICEO BICENTENARIO COMERCIAL DIEGO PORTALES','O''Higgins','RANCAGUA','Municipal'),
('2105','LICEO INDUSTRIAL ERNESTO PINTO LAGARRIGUE','O''Higgins','RANCAGUA','Adm. Delegada'),
('2109','LICEO DE NIÑAS DE RANCAGUA','O''Higgins','RANCAGUA','Municipal'),
('2110','LICEO MUNICIPAL OSCAR CASTRO ZUNIGA','O''Higgins','RANCAGUA','Municipal'),
('2111','LICEO MUNICIPAL JOSE VICTORINO LASTARRIA','O''Higgins','RANCAGUA','Municipal'),
('2112','ESCUELA MUNICIPAL MOISES MUSSA','O''Higgins','RANCAGUA','Municipal'),
('2114','ESCUELA MUNICIPAL MARCELA PAZ','O''Higgins','RANCAGUA','Municipal'),
('2115','ESCUELA MUNICIPAL RENE SCHNEIDER CHEREAU','O''Higgins','RANCAGUA','Municipal'),
('2116','COLEGIO MUNICIPAL EDUARDO DE GEYTER','O''Higgins','RANCAGUA','Municipal'),
('2118','COLEGIO ESPANA','O''Higgins','RANCAGUA','Municipal'),
('2119','ESCUELA MUNICIPAL MANUEL RODRIGUEZ','O''Higgins','RANCAGUA','Municipal'),
('2120','ESCUELA MUNICIPAL MINERAL EL TENIENTE','O''Higgins','RANCAGUA','Municipal'),
('2121','COLEGIO REPUBLICA ARGENTINA','O''Higgins','RANCAGUA','Municipal'),
('2122','ESCUELA MUNICIPAL EL COBRE','O''Higgins','RANCAGUA','Municipal'),
('2123','INSTITUTO TECNOLOGICO MINERO BERNARDO OHIGGINS','O''Higgins','RANCAGUA','Municipal'),
('2124','LICEO INTEGRADO LIBERTADOR SIMÓN BOLIVAR','O''Higgins','RANCAGUA','Municipal'),
('2125','COLEGIO PABLO GARRIDO','O''Higgins','RANCAGUA','Municipal'),
('2126','COL. JOSE A. MANSO DE VELASCO Y S.','O''Higgins','RANCAGUA','Municipal'),
('2129','COLEGIO AURORA DE CHILE','O''Higgins','RANCAGUA','Municipal'),
('2131','ESCUELA MUNICIPAL CARLOS MIRANDA MIRANDA','O''Higgins','RANCAGUA','Municipal'),
('2132','ESCUELA MUNICIPAL PATRICIO MEKIS','O''Higgins','RANCAGUA','Municipal'),
('2133','COL.ESPECIAL DR. RICARDO OLEA GULDEMONT','O''Higgins','RANCAGUA','Municipal'),
('2134','LICEO COMERCIAL JORGE ALESSANDRI R.','O''Higgins','RANCAGUA','Municipal'),
('2135','ESCUELA MUNICIPAL JEAN PIAGET','O''Higgins','RANCAGUA','Municipal'),
('2136','ESCUELA MUNICIPAL ISABEL RIQUELME','O''Higgins','RANCAGUA','Municipal'),
('2138','ESCUELA MUNICIPAL ALBERTO BLEST GANA','O''Higgins','RANCAGUA','Municipal'),
('2139','ESCUELA MUNICIPAL VIRGINIA BRAVO','O''Higgins','RANCAGUA','Municipal'),
('2140','ESCUELA MUNICIPAL AUGUSTO D HALMAR','O''Higgins','RANCAGUA','Municipal'),
('2143','ESCUELA MUNICIPAL HERMANOS CARRERA','O''Higgins','RANCAGUA','Municipal'),
('2145','ESCUELA MUNICIPAL MARTA BRUNET','O''Higgins','RANCAGUA','Municipal'),
('2146','COLEGIO MANUEL ROJAS','O''Higgins','RANCAGUA','Municipal'),
('2147','ESCUELA MUNICIPAL J.M. BALMACEDA','O''Higgins','RANCAGUA','Municipal'),
('2150','INSTITUTO SAGRADO CORAZON','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2151','COLEGIO PARTICULAR SANTA MARIA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2155','COLEGIO PARTICULAR WHIPPLE SCHOOL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2159','COLEGIO PARTICULAR INFANTES DE O´HIGGINS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2160','ESCUELA PARTICULAR JULIO VALENZUELA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2162','COLEGIO PARTICULAR ADVENTISTA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2163','COLEGIO CUISENAIRE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2164','COLEGIO PARTICULAR GABRIELA MISTRAL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2165','COLEGIO NIÑO JESUS DE PRAGA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2166','INSTITUTO REGIONAL DE EDUCACION','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2167','INSTITUTO SEWELL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2170','COLEGIO PARTICULAR JAVIERA CARRERA','O''Higgins','RANCAGUA','Part. Pagado'),
('2171','COLEGIO PARTICULAR ANDRES BELLO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2174','COLEGIO SANTO TOMAS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2178','ESCUELA PARTICULAR SAINT PAUL COLLEGE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2179','COLEGIO PARTICULAR LOS CONQUISTADORES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2182','COLEGIO PARTICULAR SUBVENCIONADO MANZANAL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2183','COLEGIO PARTICULAR INSTITUTO SAN ANDRES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2184','ESCUELA PARTICULAR BUEN PASTOR','O''Higgins','RANCAGUA','Part. Subvencionado'),
('2185','COLEGIO ALONSO DE ERCILLA','O''Higgins','RANCAGUA','Part. Pagado'),
('2191','COLEGIO SAGRADO CORAZON','O''Higgins','RANCAGUA','Part. Pagado'),
('2194','INSTITUTO INGLES RANCAGUA','O''Higgins','RANCAGUA','Part. Pagado'),
('2200','INSTITUTO O´HIGGINS','O''Higgins','RANCAGUA','Part. Pagado'),
('2205','LICEO PROFESOR MISAEL LOBOS MONROY','O''Higgins','GRANEROS','Corp. Municipal'),
('2206','ESCUELA SIXTO MENDEZ PARADA','O''Higgins','GRANEROS','Corp. Municipal'),
('2207','ESCUELA HERNAN OLGUIN MAYBE','O''Higgins','GRANEROS','Corp. Municipal'),
('2209','COLEGIO ANTONIO TRDAN ARKO','O''Higgins','GRANEROS','Corp. Municipal'),
('2210','ESCUELA MUNICIPAL VILLA LA COMPANIA','O''Higgins','GRANEROS','Corp. Municipal'),
('2212','ESCUELA MUNICIPAL DE TUNICHE','O''Higgins','GRANEROS','Corp. Municipal'),
('2215','ESCUELA MUNICIPAL DE LAS HIGUERAS','O''Higgins','GRANEROS','Corp. Municipal'),
('2217','COLEGIO PARTICULAR NUESTRA SENORA','O''Higgins','GRANEROS','Part. Subvencionado'),
('2218','COLEGIO PARTICULAR GRANEROS','O''Higgins','GRANEROS','Part. Subvencionado'),
('2219','ESCUELA AGRICOLA CRISTO OBRERO','O''Higgins','GRANEROS','Part. Subvencionado'),
('2220','COLEGIO PARTICULAR SAN MARTIN','O''Higgins','GRANEROS','Part. Subvencionado'),
('2222','LICEO BICENTENARIO DE EXCELENCIA ALBERTO HURTADO','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2223','COLEGIO ANDRES BELLO','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2224','LICEO ELVIRA SANCHEZ DE GARCES','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2226','ESC. HIJOS DEL SOL','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2227','ESC. SAN FRANCISCO DE ASIS','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2228','ESCUELA EL RINCON','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2231','COLEGIO DEL CAMINO REAL MARIO MIRANDA PINTO','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2232','ESC. DE PARV. LAURITA VICUNA','O''Higgins','MOSTAZAL','Corp. Municipal'),
('2233','COLEGIO TECNOLOGICO PULMAHUE','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('2234','COLEGIO JESUS ANDINO','O''Higgins','CODEGUA','Corp. Municipal'),
('2235','COLEGIO MARIANO LATORRE','O''Higgins','CODEGUA','Corp. Municipal'),
('2236','ESCUELA EUGENIO GARCIA FERNANDEZ','O''Higgins','CODEGUA','Corp. Municipal'),
('2237','ESCUELA LA CANTERA DE CALLEJONES','O''Higgins','CODEGUA','Corp. Municipal'),
('2238','COLEGIO SANTA TERESA DE TUNCA','O''Higgins','CODEGUA','Corp. Municipal'),
('2240','COLEGIO MUNICIPAL CRISTO DEL PARQUE','O''Higgins','CODEGUA','Corp. Municipal'),
('2243','COLEGIO NATALIA PERALTA P','O''Higgins','CODEGUA','Corp. Municipal'),
('2244','INSTITUTO LAUTARO DE CODEGUA','O''Higgins','CODEGUA','Part. Subvencionado'),
('2246','COLEGIO JUAN TACHOIRE MOENA','O''Higgins','MACHALÍ','Corp. Municipal'),
('2247','COLEGIO GABRIELA MISTRAL','O''Higgins','MACHALÍ','Corp. Municipal'),
('2248','PARVULARIO GRAL. O. BONILLA','O''Higgins','MACHALÍ','Corp. Municipal'),
('2249','COLEGIO LOS LLANOS','O''Higgins','MACHALÍ','Corp. Municipal'),
('2250','COLEGIO ARTÍSTICO SANTA TERESA DE MACHALI','O''Higgins','MACHALÍ','Corp. Municipal'),
('2251','COLEGIO BELLAVISTA','O''Higgins','MACHALÍ','Corp. Municipal'),
('2255','ESC. SAN JUAQUIN DE LOS MAYOS','O''Higgins','MACHALÍ','Corp. Municipal'),
('2257','ESCUELA CHACAYES','O''Higgins','MACHALÍ','Corp. Municipal'),
('2258','ESCUELA PARTICULAR SAN LORENZO','O''Higgins','MACHALÍ','Part. Subvencionado'),
('2259','COLEGIO PARTICULAR ARTURO PRAT','O''Higgins','MACHALÍ','Part. Subvencionado'),
('2260','COLEGIO COYA','O''Higgins','MACHALÍ','Part. Pagado'),
('2262','COL.MARIA VILLALOBOS ARTEAGA','O''Higgins','OLIVAR','Corp. Municipal'),
('2263','ESCUELA MUNICIPAL DE GULTRO','O''Higgins','OLIVAR','Corp. Municipal'),
('2264','ESCUELA NUESTRA SRA. DE LA MERCED','O''Higgins','OLIVAR','Corp. Municipal'),
('2265','ESCUELA BERTA SAAVEDRA SEGURA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2266','ESCUELA BASICA CAMPO LINDO','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2267','ESC. REPUBLICA DE FRANCIA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2268','ESCUELA MUNICIPAL SANTA AMALIA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2271','ESCUELA MUNICIPAL SUECIA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2274','COLEGIO LA PIMPINELA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2275','ESCUELA DAVID DEL CURTO','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2278','LICEO SAN JOSE DE REQUINOA','O''Higgins','REQUÍNOA','Part. Subvencionado'),
('2279','ESCUELA CANADA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('2280','LICEO BICENTENARIO DE EXCELENCIA TOMÁS MARÍN DE POVEDA','O''Higgins','RENGO','Corp. Municipal'),
('2282','COLEGIO MUNICIPAL LO DE LOBO','O''Higgins','RENGO','Corp. Municipal'),
('2283','LICEO LUIS URBINA FLORES','O''Higgins','RENGO','Corp. Municipal'),
('2284','ESCUELA LA PAZ','O''Higgins','RENGO','Corp. Municipal'),
('2285','COLEGIO MANUEL FRANCISCO CORREA','O''Higgins','RENGO','Corp. Municipal'),
('2286','COLEGIO MUNICIPAL LUIS GALDAMES','O''Higgins','RENGO','Corp. Municipal'),
('2288','ESCUELA CARLOS CONDELL DE LA HAZA','O''Higgins','RENGO','Corp. Municipal'),
('2289','ESCUELA REPUBLICA DE ALEMANIA','O''Higgins','RENGO','Corp. Municipal'),
('2291','ESCUELA DIFERENCIAL TERESA NARETTO DE NICOLETTI','O''Higgins','RENGO','Corp. Municipal'),
('2292','ESCUELA VICENTE HUIDOBRO','O''Higgins','RENGO','Corp. Municipal'),
('2293','COLEGIO MUNICIPAL LOS CHOAPINOS','O''Higgins','RENGO','Corp. Municipal'),
('2294','COLEGIO MUNICIPAL LA ESMERALDA','O''Higgins','RENGO','Corp. Municipal'),
('2296','COLEGIO MUNICIPAL LO CARTAGENA','O''Higgins','RENGO','Corp. Municipal'),
('2297','ESCUELA GUSTAVO BISQUERTT S.','O''Higgins','RENGO','Corp. Municipal'),
('2299','COLEGIO MUNICIPAL EL CERRILLO','O''Higgins','RENGO','Corp. Municipal'),
('2300','ESCUELA LA ISLA EMMA ESCOBAR DE LAGOS','O''Higgins','RENGO','Corp. Municipal'),
('2301','COLEGIO MUNICIPAL DE APALTA','O''Higgins','RENGO','Corp. Municipal'),
('2302','ESCUELA BASICA VICTOR NICOLETTI TAMANINI','O''Higgins','RENGO','Corp. Municipal'),
('2304','COLEGIO MUNICIPAL VILLA DEL COBIL','O''Higgins','RENGO','Corp. Municipal'),
('2307','ESCUELA MARTA AVARIA SALVATIERRA','O''Higgins','RENGO','Corp. Municipal'),
('2308','COLEGIO SAN ANTONIO DEL BALUARTE','O''Higgins','RENGO','Part. Subvencionado'),
('2309','CENTRO EDUCACIONAL ASUNCION','O''Higgins','RENGO','Part. Subvencionado'),
('2310','ESC.ALCIDES REYES FRIAS','O''Higgins','MALLOA','Corp. Municipal'),
('2311','ESCUELA PELEQUEN','O''Higgins','MALLOA','Corp. Municipal'),
('2312','ESCUELA MUNICIPAL DE PANQUEHUE','O''Higgins','MALLOA','Corp. Municipal'),
('2313','ESCUELA MUNICIPAL DE LIMAHUE','O''Higgins','MALLOA','Corp. Municipal'),
('2314','ESCUELA MUNICIPAL DE CORCOLEN','O''Higgins','MALLOA','Corp. Municipal'),
('2318','ESCUELA MUNICIPAL DE PELEQUEN VIEJO','O''Higgins','MALLOA','Corp. Municipal'),
('2319','LICEO REPUBLICA DE ITALIA','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2320','VIOLETA FUENTES CARVAJAL','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2321','ESCUELA AMPARO RAYO HORTA','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2322','ESCUELA RURAL LA VINILLA','O''Higgins','SAN VICENTE','Municipal'),
('2324','ESCUELA JAIME FELDMAN MILLER','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2325','COLEGIO RAÚL RAMÍREZ MAYOL','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2326','COLEGIO SAGRADO CORAZON DE JESUS','O''Higgins','QUINTA DE TILCOCO','Part. Subvencionado'),
('2327','COLEGIO MUNICIPAL DE EDUCACION ESPECIAL','O''Higgins','QUINTA DE TILCOCO','Corp. Municipal'),
('2328','ESCUELA ESPECIAL PAULA JARAQUEMADA','O''Higgins','SAN VICENTE','Municipal'),
('2329','LICEO IGNACIO CARRERA PINTO','O''Higgins','SAN VICENTE','Municipal'),
('2330','ESC.CARMEN GALLEGOS DE ROBLE','O''Higgins','SAN VICENTE','Municipal'),
('2331','CENTRO EDUC. REQUEGUA','O''Higgins','SAN VICENTE','Municipal'),
('2333','ESC.GUIDO ASSIS GONZALEZ','O''Higgins','SAN VICENTE','Municipal'),
('2334','ESCUELA MUNICIPAL RASTROJOS','O''Higgins','SAN VICENTE','Municipal'),
('2335','ESC. ENRIQUE YANEZ GONZALEZ','O''Higgins','SAN VICENTE','Municipal'),
('2336','ESCUELA EL LIBERTADOR','O''Higgins','SAN VICENTE','Municipal'),
('2338','ESC.JUAN BARROS ROLDAN','O''Higgins','SAN VICENTE','Municipal'),
('2339','ESCUELA MUNICIPAL ZUNIGA','O''Higgins','SAN VICENTE','Municipal'),
('2343','ESCUELA MUNICIPAL TOQUIHUA','O''Higgins','SAN VICENTE','Municipal'),
('2347','ESC.PARROCO M.BUSTAMANTE','O''Higgins','SAN VICENTE','Municipal'),
('2348','ESCUELA MUNICIPAL VINA TAGUA TAGUA','O''Higgins','SAN VICENTE','Municipal'),
('2350','ESCUELA SAN ALBERTO DE IDAHUE','O''Higgins','SAN VICENTE','Municipal'),
('2352','ESCUELA LAS PATAGUAS','O''Higgins','SAN VICENTE','Municipal'),
('2355','COLEGIO EL SALVADOR','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('2356','COLEGIO SANTA INES','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('2358','JARDIN INFANTIL EL PRINCIPITO VALIENTE','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('2359','ESCUELA LARMAHUE','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2360','CENTRO EDUCATIVO SIGLO XXI','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2361','ESCUELA ENRIQUE SERRANO DE VIALE RIGO','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2362','ESCUELA AMELIA LYNCH DE LYON','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2363','ESCUELA MUNICIPAL DE SAN ROBERTO','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2364','ESCUELA REINO DE DINAMARCA','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2365','ESCUELA BASICA PATAGUAS CERRO','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2366','ESCUELA FERNANDO HUERTA PENA','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2367','ESCUELA BASICA JOSE BERNALES CASTILLO','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2372','ESCUELA MUNICIPAL EL SALTO','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2373','ESCUELA BASICA SAN JOSE','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2374','ESCUELA MUNICIPAL DE CALEUCHE','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2375','LICEO BICENTENARIO LATINOAMERICANO DE PICHIDEGUA','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('2377','ESCUELA ESPECIAL DE ADULTOS F Nº 142','O''Higgins','PEUMO','Corp. Municipal'),
('2378','LICEO JEAN BUCHANAN DE LARRAIN','O''Higgins','PEUMO','Corp. Municipal'),
('2379','ESCUELA BASICA ANTONIO DE ZUNIGA','O''Higgins','PEUMO','Corp. Municipal'),
('2380','ESCUELA MUNICIPAL ALCALDE G. BURMESTER','O''Higgins','PEUMO','Corp. Municipal'),
('2381','ESCUELA JUAN VALDES ORTUZAR','O''Higgins','PEUMO','Corp. Municipal'),
('2384','ESCUELA BASICA ROSARIO DE CODAO','O''Higgins','PEUMO','Corp. Municipal'),
('2386','ESCUELA PART. LUIS GARCIA DE LA HUERTA','O''Higgins','PEUMO','Part. Subvencionado'),
('2387','ESCUELA MUNICIPAL OSVALDO RUIZ GARCIA','O''Higgins','COLTAUCO','Corp. Municipal'),
('2388','ESCUELA MUNIC.SBTE LUIS CRUZ MARTINEZ','O''Higgins','COLTAUCO','Corp. Municipal'),
('2389','COLEGIO NUESTRA SEÑORA DE LORETO','O''Higgins','COLTAUCO','Corp. Municipal'),
('2390','COLEGIO QUILLAYQUEN RINCONADA DE PARRAL','O''Higgins','COLTAUCO','Corp. Municipal'),
('2391','ESC. SUBTENIENTE JULIO MONTT SALAMANCA','O''Higgins','COLTAUCO','Corp. Municipal'),
('2392','ESC. LUCILA GODOY ALCAYAGA','O''Higgins','COLTAUCO','Corp. Municipal'),
('2393','ESCUELA MUNICIPAL DE LO DE CUEVAS','O''Higgins','COLTAUCO','Corp. Municipal'),
('2394','ESCUELA MUNICIPAL JOSEFINA VIAL DE VIAL','O''Higgins','COLTAUCO','Corp. Municipal'),
('2395','ESCUELA MUNICIPAL DE VINA LA CRUZ','O''Higgins','COLTAUCO','Corp. Municipal'),
('2396','ESCUELA MUNICIPAL DE RINCONADA DE IDAHUE','O''Higgins','COLTAUCO','Corp. Municipal'),
('2397','ESCUELA CAPITAN IGNACIO CARRERA PINTO','O''Higgins','COLTAUCO','Corp. Municipal'),
('2398','ESCUELA SUBTTE. ARTURO PEREZ CANTO','O''Higgins','COLTAUCO','Corp. Municipal'),
('2400','COLEGIO AMADA SOFIA GARCIA','O''Higgins','COLTAUCO','Part. Subvencionado'),
('2401','ESCUELA AGRICOLA SAN VICENTE DE PAUL','O''Higgins','COLTAUCO','Part. Subvencionado'),
('2406','LICEO MUNICIPAL LUIS GREGORIO VALENZUELA LAVIN','O''Higgins','COINCO','Corp. Municipal'),
('2407','ESCUELA MUNICIPAL CHILLEHUE','O''Higgins','COINCO','Corp. Municipal'),
('2409','ESCUELA MUNICIPAL COPEQUEN','O''Higgins','COINCO','Corp. Municipal'),
('2410','ESCUELA MUNICIPAL EL RULO','O''Higgins','COINCO','Corp. Municipal'),
('2411','LICEO CLAUDIO ARRAU LEON','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2412','ESCUELA LAURA MATUS MELENDEZ','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2413','ESC. DE PARVULOS MIS PRIMEROS PASOS','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2414','COLEGIO MUNICIPAL LA ISLA','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2415','ESCUELA LO MIRANDA','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2416','COLEGIO REPUBLICA DE CHILE','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2417','ESCUELA CERRILLOS','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2419','COLEGIO JULIO SILVA LAZO','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2420','ESCUELA PLAZUELA','O''Higgins','DOÑIHUE','Corp. Municipal'),
('2422','LICEO FRANCISCO ANTONIO ENCINA ARMANET','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2423','ESCUELA BASICA ROMILIO ARELLANO TRONCOSO','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2424','ESCUELA OSVALDO CORREA FUENZALIDA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2425','ESCUELA MUNICIPAL DE LOS AROMOS','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2426','ESC. CONTRAMAESTRE CONSTANTINO MICALVI','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2427','ESCUELA MUNICIPAL MAESTRO JORGE LOPEZ OSORIO','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2428','ESCUELA REPUBLICA DE GRECIA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2429','COLEGIO INES DE SUAREZ','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2432','ESCUELA MUNICIPAL VILMA ALIAGA CALDERON','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2436','ESCUELA MUNICIPAL DE SANTA EUGENIA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2437','ESCUELA TENIENTE HERNAN MERINO CORREA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2438','COLEGIO MARIA LUISA FABRES VERGARA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2439','ESCUELA MUNICIPAL DE PALMERIA','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2440','COLEGIO CARMEN OJEDA SANTANDER','O''Higgins','LAS CABRAS','Corp. Municipal'),
('2441','COLEGIO PART.SANT.VIRGEN MARIA','O''Higgins','LAS CABRAS','Part. Subvencionado'),
('2442','LICEO TECNICO BICENTENARIO FELISA TOLUP','O''Higgins','SAN FERNANDO','Adm. Delegada')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
