-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 26 de 31 | filas 10001-10400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('25397','ESCUELA ESPECIAL PART. ACONCAGUA DE PUDAHEL N','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25398','ESC. ESPECIAL 1775 SAN ANTONIO II','Metropolitana','LAMPA','Part. Subvencionado'),
('25399','ESCUELA ESPECIAL PART. TRIPANTU','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25400','ESC. ESP. CHILE CUBA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25402','COL.  PART. SALES. EL PATROCINIO DE SAN JOSE','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('25403','ESC. ESPECIAL GULLIVER','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25404','ESCUELA ESPECIAL ` MANQUEMAPU`','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25405','ESCUELA ESPECIAL PART. TRAGALUZ','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25406','ESCUELA ESPECIAL MARIO BAEZA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25408','ESCUELA ESPECIAL GABRIELA MISTRAL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25413','ESC. DE PARV. Y ESP. ENANITOS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25414','ESCUELA ESPEC. PART. ARCO IRIS DE RECOLETA','Metropolitana','RECOLETA','Part. Subvencionado'),
('25415','ESC. ESPECIAL TIEMPO NUEVO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25417','ESCUELA PARTICULAR 1788 EDEN DE SAN RAMON','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('25418','COLEGIO POLIV. SAN BERNARDO ABAD','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25420','ESC. PARV. Y ESP. GABRIELA MISTRAL DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25421','ESCUELA ESPECIAL ARCANGEL GABRIEL','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25423','COLEGIO PARTICULAR IGNACIO SERRANO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25425','ESC.ESP. PART. EL OLIVAR','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25426','ESC. ESP. PART. PALU','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25427','ESCUELA ESPECIAL BELEN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25428','ESC. ESP. PART. KADES BARNEA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25429','ESC. ESP. PART. LOS AROMOS DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25430','ESCUELA PARTICULAR N_ 1796 NUEVO HORIZONTE','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('25431','ESCUELA BASICA PART SANTA MARIA DE ESMERALDA','Metropolitana','COLINA','Part. Subvencionado'),
('25433','ESCUELA ESP. RUCAMALEN','Metropolitana','LO PRADO','Part. Subvencionado'),
('25434','COLEGIO PARTICULAR FORJADORES','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25436','COLEGIO PART. SOCHIDES RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('25437','ESC. BASICA Y ESP.  EL NAZARENO','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25439','CENTRO EDUCACIONAL SAN CARLOS DE ARAGON','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25440','ESCUELA ESPECIAL ADENNUN N_ 2','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('25442','COLEGIO TALAGANTE GARDEN SCHOOL','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25443','ESC  ESP PART  PUERTA DEL SOL DE LA REINA','Metropolitana','LA REINA','Part. Subvencionado'),
('25447','COLEGIO VALLE DE MALLARAUCO','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25448','CENTRO EDUC. NINO DIOS DE MALLOCO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25450','COLEGIO SALTAIRAM','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25451','ESC. ESP. NTRA. SRA. DEL BUEN CONSEJO I','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25452','COLEGIO TREBULCO','Metropolitana','TALAGANTE','Part. Pagado'),
('25454','COLEGIO PART. ANDINO ANTUQUELEN','Metropolitana','SAN JOSÉ DE MAIPO','Part. Subvencionado'),
('25458','COLEGIO POLIVALENTE FALCON COLLEGE','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25459','ESC. ESP. PART. PABLO NERUDA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25460','ESC. ESP. PART. LA PAMPA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25461','ESCUELA ESPECIAL PART. NINOS DE LA REINA','Metropolitana','LA REINA','Part. Subvencionado'),
('25462','COLEGIO ALTO GABRIELA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25463','COLEGIO CTRO. INTEG  ADULTOS ALTAZOL','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25464','COLEGIO POLIVALENTE AGUSTINIANO DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25465','ESC. BAS. PART.  JERUSALEN','Metropolitana','LAMPA','Part. Subvencionado'),
('25466','ESCUELA BÁSICA N°1812 EL PORVENIR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25467','ESC. BAS. PART. SAN JUAN LEONARDI','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25470','ESCUELA DE PARV. ICHUAC','Metropolitana','CERRILLOS','Part. Subvencionado'),
('25471','COLEGIO PART. KING EDWARDS SCHOOL I','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25473','ESCUELA ESPECIAL PART. GUENIPILLAN - MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25474','ESCUELA BASICA  Nº1817 ANIDA','Metropolitana','LA FLORIDA','Part. Pagado'),
('25475','COLEGIO PART. PADRE JOSE KENTENICH','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25477','COLEGIO LA MISION','Metropolitana','CALERA DE TANGO','Part. Pagado'),
('25478','COLEGIO  MAYOR DE PEÑALOLEN','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('25480','COLEGIO JOSE LUIS LEGRANGE DE LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25481','COLEGIO INSTITUTO O¦HIGGINS DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25482','ESC. PART. ARTISTICA EL TRIGAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25484','ESC PART. SIGLO XXI DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('25485','ESC. BASICA  `SAN BENIGNO`','Metropolitana','COLINA','Part. Subvencionado'),
('25487','COLEGIO  MANQUECURA VALLE LO CAMPINO','Metropolitana','QUILICURA','Part. Pagado'),
('25490','ESC. ESP. NTRA. SRA. DEL BUEN CONSE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25492','ESCUELA BASICA PARTICULAR TRUPAN','Metropolitana','CONCHALÍ','Part. Pagado'),
('25495','ESCUELA DE PARVULOS  N°1827 MY LITTLE GARDEN N° 2','Metropolitana','SANTIAGO','Part. Pagado'),
('25496','INSTITUTO TECNOLÓGICO BICENTENARIO DE EXCELENCIA SAN MATEO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25497','ESC. DE PARV.CAMPANITA DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25500','ESCUELA ESPEC.STA. TERESA DE AVILA','Metropolitana','CERRILLOS','Part. Subvencionado'),
('25501','COLEGIO SAN ANDRES DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25502','COLEGIO DE ADULTOS JOSE ABELARDO NUNEZ','Metropolitana','HUECHURABA','Part. Subvencionado'),
('25504','COLEGIO DE ADULTOS JOSE ABELARDO NUNEZ EL BOS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25506','ESCUELA ESPECIAL N°1832 EXPLORADORES DE BATUCO','Metropolitana','LAMPA','Part. Subvencionado'),
('25507','ESC. BASICA PARTICULAR SAN PABLO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25508','COLEGIO PART. GABRIELA MISTRAL SOCIEDAD EDUCA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25509','COLEGIO PARTICULAR MARÍA AUXILIADORA DE SANTIAGO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25510','ESCUELA ESPECIAL DESPERTAR DE LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('25511','ESCUELA DE PARV. BRITISH NURSERY SCHOOL','Metropolitana','LA FLORIDA','Part. Pagado'),
('25513','ESCUELA ESPECIAL  NINO DE JESUS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25514','INSTITUTO DE EDUCACION DE ADULTOS MACUL','Metropolitana','MACUL','Servicio Local'),
('25516','ESCUELA ESPECIAL PADRE PIO COLLEGE','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25517','ESC. ESP. PART MADRE MARIA MAZZARELLO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25520','COL. PART. SAGRADO CORAZON DE JESUS DE LA RE','Metropolitana','LA REINA','Part. Subvencionado'),
('25521','ESCUELA DE PARVULOS N°1840 HERMANO ANDRES','Metropolitana','SANTIAGO','Part. Pagado'),
('25523','CARDENAL JUAN FRANCISCO FRESNO LARRAIN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25524','CENTRO EDUCACIONAL ADULTOS KAIROS','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25525','COLEGIO PARTICULAR EL ALBA DE MACUL','Metropolitana','MACUL','Part. Subvencionado'),
('25526','ESCUELA PART.  CURACAVI COLLEGE','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('25527','ESCUELA ESPECIAL PART. N_ 110  TRINIDAD FERR','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25528','ESCUELA ESPECIAL PARTICULAR ROMPE MI SILENCIO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25529','ESCUELA ESPECIAL  GEORGINA DE LAS NIEVES','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25530','ESCUELA ESPECIAL LOS CORCELES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25532','ESCUELA ESPECIAL PARTICULAR MARTIN PESCADOR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25533','ESCUELA BAS. Y ESP. SAN JOSE DE ISLA DE MAIPO','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('25534','ESC. ESP. PARTICULAR MANANTIAL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25537','ESCUELA DE PARV. Y ESPECIAL PELUSITA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25539','EJERCITO LIBERTADOR DE CERRILLOS','Metropolitana','CERRILLOS','Servicio Local'),
('25540','COLEGIO MONTE OLIVO DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25541','COLEGIO PART. JOSEFINO SANTISIMA TRINIDAD','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('25542','COLEGIO SANTA BARBARA H.S.','Metropolitana','QUILICURA','Part. Subvencionado'),
('25543','COLEGIO POLIV. SAN CRISTOBAL APOSTOL','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25544','ESC. ESP. Y BAS. FRANCES DE LA PINTANA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25545','ESCUELA ESPECIAL PART. N_ 1850 TRALEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25546','ESCUELA ESPECIAL PART. MERCEDES','Metropolitana','RECOLETA','Part. Subvencionado'),
('25547','ESCUELA PARTICULAR NUEVA ESMERALDA','Metropolitana','COLINA','Part. Subvencionado'),
('25550','ESC. BASICA PART. BOSTON COLLEGE LA FARFANA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25551','ESCUELA ESP. MANANTIAL DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25554','ESCUELA ESPECIAL Y  DE  PARVULOS PARTICULAR EL NIDITO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25555','ESCUELA PART. DE LENGUAJE APORE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25556','COLEGIO SOCHIDES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25557','ESC BASICA PART EMILIA GONZALEZ ESPINOZA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25558','COLEGIO PARTICULAR ALTAZOR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25561','ESCUELA DIVINO MAESTRO','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25562','ESC BASICA PART SAN JOSE DE LA FAMILIA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25563','ESC. ESP. PARTICULAR  MI CASITA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25564','ESCUELA ESPECIAL PART. TALENTOS','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25565','ESC ESP PART PROF RAQUEL TORRES GUZMAN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25566','ESC ESP PART RAYITO DE LUZ DE QTA NORMAL','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25568','ESCUELA BAS. Y ESP. ANTILLANCA DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25569','ESC ESPECIAL PARTICULAR  MI FAMILIA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25571','COLEGIO EL RACO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25572','ESCUELA ESPECIAL PART. MAHUIDANCHE','Metropolitana','RECOLETA','Part. Subvencionado'),
('25573','ESC. DE PARV. Y ESP. PART. CENTILEN','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25574','ESCUELA ESPECIAL PART. MELODIA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25575','ESCUELA ESPECIAL PART. ALAMEDA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25576','ESCUELA BASICA PART. SAN JORGE DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25577','COLEGIO PART. FAMILIA DE NAZARETH','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25580','COLEGIO PARTICULAR MIRADOR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25581','ESCUELA ESP. SAN JOSE OBRERO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25582','ESCUELA ESP. PART. GIRASOL DE RECOLETA','Metropolitana','RECOLETA','Part. Subvencionado'),
('25583','ESC. ESP. PART. SANTISIMA TRINIDAD DE PUDAHUE','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25585','ESCUELA ESPECIAL PART. UNAMKALEN','Metropolitana','COLINA','Part. Subvencionado'),
('25586','ESCUELA ESP. PART. RAIHUEN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25589','COLEGIO JESUS SERVIDOR','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25591','LICEO TECNICO PROFESIONAL DE BUIN','Metropolitana','BUIN','Municipal'),
('25592','INSTITUTO SAN MIGUEL','Metropolitana','COLINA','Municipal'),
('25593','MARY ANNE SCHOOL DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25594','ESCUELA ESP. PART. SOL Y LUNA','Metropolitana','LA REINA','Part. Subvencionado'),
('25595','ESC. ESPECIAL PART. BELLA ACUARELA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25596','ESCUELA ESPECIAL PART. ANTULEMU','Metropolitana','RECOLETA','Part. Subvencionado'),
('25599','COLEGIO PART. SAN PEDRO DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25601','ESCUELA PARV. MY HAPPY SCHOOL','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25602','ESC. PART. PABLO APOSTOL DE BUIN','Metropolitana','BUIN','Part. Pagado'),
('25604','ESCUELA ESP. NUEVO MUNDO DE LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25607','ESCUELA ESP. BOSQUE DE NINOS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25608','ESC. ESP. Nº 109 SAN VALENTIN DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25609','COLEGIO PADRE CHAMINADE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25610','ESCUELA ESP. TREM TREMO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25611','ESCUELA BASICA N°1889 BARRIE MONTESSORI Nº 2','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('25612','ESC. DE PARV. Y ESP. AMANECER DE PADRE HURTA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25613','COLEGIO BICENTENARIO DE EXCELENCIA PEDRO APOSTOL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25614','ESC. ESP. SAN ANDRES DE LO BARNECHEA','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('25615','COLEGIO POLIVALENTE SAINT PETER COLLEGE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25616','ESCUELA ESPECIAL LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25618','ESC. ESP. MILLARAY DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25621','ESCUELA ESPECIAL EDUCCERE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25622','ESCUELA ESPECIAL PART. ABRA PALABRA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25624','ESC. BAS. Y ESP. NUEVA INTEGRAL ALTAZOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25625','COLEGIO PART. SWEDENBORG COLLEGE','Metropolitana','MACUL','Part. Subvencionado'),
('25627','ESCUELA PARVULOS INST. SWEET N1','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25629','ESCUELA ESPECIAL EL ALBA DE LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25631','ESCUELA ESPECIAL PASO A PASO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25632','ESCUELA PARVULOS PART. GENTECITA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25633','COLEGIO ADULTOS  ALFRED NOBEL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25636','ESCUELA ESPECIAL BELEN, DE QTA. NORMAL','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25638','ESCUELA ESPECIAL CASTORCITO','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25639','ESCUELA BASICA Y ESPECIAL N° 1905 JACARANDA','Metropolitana','RENCA','Part. Subvencionado'),
('25640','COLEGIO  MANQUECURA PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Pagado'),
('25641','ESCUELA ESP. ANTU-MAWIDA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25642','ESCUELA BAS. MUNIC. CUYUNCAVI','Metropolitana','CURACAVÍ','Corp. Municipal'),
('25643','ESCUELA BASICA N°1906 THE INTERNATIONAL PREPARATORY SCHOOL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('25644','COLEGIO PART. NEW LITTLE COLLEGE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25645','COLEGIO PART. NTRA. SRA. MARIA INMACULADA DEL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25646','ESCUELA ESPECIAL N° 151 ANTAL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25647','ESC. BAS Y ESP. N° 113 SAN LORENZO DE ISLA DE MAIPO','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('25649','ESCUELA ESPECIAL SEMILLITA DE JESUS II','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25650','COLEGIO AMERICAN BRITISH COLLEGE','Metropolitana','LA FLORIDA','Part. Pagado'),
('25652','ESCUELA ESPECIAL HOSPITAL FELIX BULNES','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('25653','ESCUELA DE PARVULOS N°152 SEMILLITAS DE AMOR','Metropolitana','PUENTE ALTO','Part. Pagado'),
('25654','COLEGIO EVEREST','Metropolitana','LO BARNECHEA','Part. Pagado'),
('25655','COLEGIO SANTO TOMAS DE AQUINO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25656','ESC. ESPECIAL PASITOS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25658','ESCUELA ESPECIAL PART. SANTA JAVIERA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25661','ESCUELA DE PARV. CAPULLITOS DE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25662','ESCUELA DE PARVULOS REMOLINO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25663','ESCUELA DE PARVULOS N°1914 MYCKEY','Metropolitana','RECOLETA','Part. Pagado'),
('25664','ESCUELA ESP. EL SEMBRADOR DE CERRILLOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('25666','COLEGIO  INSTITUTO PASCAL','Metropolitana','PROVIDENCIA','Part. Pagado'),
('25667','ESCUELA ESP. GROWING SCHOOL','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25668','ESCUELA ESP. SANTA GABRIELA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25669','COLEGIO HIGHLANDS','Metropolitana','COLINA','Part. Pagado'),
('25671','COLEGIO SAN MARTIN DE PORRES DE LA PINTANA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25674','ESCUELA INSTITUTO RAMON FREIRE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25675','COLEGIO PART. CORAZON DE MARIA DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Pagado'),
('25676','COLEGIO POLIVALENTE ELISA VALDES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25677','ESCUELA BASICA  N°1921 SISTER VERENANCE','Metropolitana','MAIPÚ','Part. Pagado'),
('25681','COLEGIO OXFORD','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25683','ESCUELA ESP. PART. HORIZONTE MANQUEHUE','Metropolitana','LAS CONDES','Part. Subvencionado'),
('25688','ESC. DE PARV. PART. MI PEQUENO MUNDO DE SAN R','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('25692','COLEGIO PART. MANSO DE VELASCO MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25693','COLEGIO MADRE DE LA DIVINA PROVIDENC','Metropolitana','MACUL','Part. Subvencionado'),
('25695','COLEGIO DE LA INMACULADA CONCEPCIÓN','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25697','COLEGIO O`HIGGINS','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25698','COLEGIO CORDILLERA DE LOS ANDES','Metropolitana','SAN BERNARDO','Servicio Local'),
('25700','COLEGIO LOS ALPES MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25703','COLEGIO PART. ALCANTARA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25704','COLEGIO PART. ALCANTARA DE LA CORDILLERA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25705','ESCUELA DE PÁRVULOS PARTICULAR Nº 1930 MIS AMIGUITOS','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25709','LINCOLN COLLEGE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25710','ESCUELA ESPECIAL PART. DAME LA MANO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25711','ESC. BASICA MUNICIPAL PAULA JARAQUEMADA ALQUI','Metropolitana','PAINE','Corp. Municipal'),
('25712','COLEGIO PART. ANDARES DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25713','COLEGIO PART. MANANTIAL DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25714','COLEGIO PART. INSTITUTO CORINTIO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25716','COLEGIO PART. NEW HEINRICH HIGH SCHOOL','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('25717','COLEGIO ALCÁNTARA DE LOS ALTOS DE PEÑALOLEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25718','COLEGIO PART. LOS ANGELES SANTIAGO DE SAN MIG','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25719','ESC. DE PARVULOS LOS OSITOS DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25722','COLEGIO PART. PATRONA SENORA DE LOURDES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25723','COLEGIO PART. ALTAMIRA-ADULTOS','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25724','COLEGIO PARTICULAR ANTILHUE','Metropolitana','LA FLORIDA','Part. Pagado'),
('25725','ESCUELA PART. NAHUEL','Metropolitana','PAINE','Part. Subvencionado'),
('25726','ESCUELA PARTICULAR SANTA LAURA DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25727','LICEO PART. SALESIANO MANUEL ARRIARAN BARROS','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25733','ESCUELA PART. SANTA TERESA DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25735','CENTRO EDUCACIONAL DE ADULTOS SAN ALFONSO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25736','CENTRO EDUC. DE ADULTOS ISABEL LA CATOLICA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25737','COLEGIO PART. ACROPOLIS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25738','ESCUELA BASICA PARTICULAR SAN JOSE DE  MELIP¦','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25739','COLEGIO NTRA. SRA. DEL CARMEN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25740','ESC. ESP. PART. SANTA TERESITA DE LOS ANDES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25741','ESC. ESPECIAL RUGENDAS','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25742','ESCUELA ESP. PART. S.M. CRECER','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25743','ESC. DE PARVULOS PART. LA FAROLA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25747','ESC. DE PARV. Y ESP. CARACOLA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25749','COLEGIO PART. ALICANTE DEL ROSAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25750','ESCUELA ESPECIAL SONRISA DE NINOS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25751','COLEGIO LIAHONA CORDILLERA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25752','CENTRO DE EDUC. INTEGRADA DE ADULTOS TALAGANT','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25753','CENTRO EDUC. PRINCIPADO DE ASTURIA ADULTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25754','ESC. ESPECIAL LAS ESPIGAS DE ESTACION CENTRAL','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25756','ESCUELA ESPECIAL PART. ELIAS CANESSA VERGARA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25757','ESC. ESP. PART. TRIGAL DE HUECHURABA','Metropolitana','HUECHURABA','Part. Subvencionado'),
('25764','ESC. DE PARV. Y ESP. CASABLANCA DE SAN BERNAR','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25765','ESC. ESPECIAL PART. AULENCO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25766','LINCOLN COLLEGE SAN MARTIN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25767','COLEGIO SAN JORGE DE LAS CONDES','Metropolitana','LAS CONDES','Part. Subvencionado'),
('25768','COLEGIO PART. EXTREMADURA DE VITACURA','Metropolitana','VITACURA','Part. Subvencionado'),
('25770','LICEO NACIONAL DE MAIPU','Metropolitana','MAIPÚ','Servicio Local'),
('25772','ESCUELA DE PARV. PART. HAPPY GARDEN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25773','ESCUELA ESP. PART. SAGRADA FAMILIA DE SAN BER','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25774','ESCUELA ESP. PART. ARRAYAN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25775','COLEGIO PARTICULAR DE ADULTOS SANTA MARIA DEL TRABAJO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25776','ESC. PART. PARV. HEIDI GARDEN SCHOOL','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25779','COLEGIO POLIV. CARDENAL JOSE MARIA CARO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25781','COLEGIO BICENTENARIO ARZOBISPO CRESCENTE ERRAZURIZ','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25782','ESC. ESP. PART. ARAUCARIAS DE PENALOLEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25783','COLEGIO POLIV. ARZOBISPO MANUEL VICUNA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25784','ESCUELA ESP. PART. ARBOLIRIS','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25785','COLEGIO PART. ROYAL AMERICAN SCHOOL','Metropolitana','MAIPÚ','Part. Pagado'),
('25786','ESCUELA ESPECIAL PARTICULAR KINERET','Metropolitana','QUILICURA','Part. Subvencionado'),
('25787','ESC. ESP. PART. DIEGO THOMPSON','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('25788','ESCUELA BASICA ANA FRANK','Metropolitana','QUILICURA','Servicio Local'),
('25790','COLEGIO POLIV. DIEGO PORTALES DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25791','ESCUELA ESP. PART. RIGOBERTA MENCHU','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25792','ESCUELA ESP. PART. SANTA MARIA DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25793','ESC. ESP. PART. GABRIELA MISTRAL DE PENALOLEN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25795','COLEGIO PARTICULAR BLUMENTHAL','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25797','ESCUELA B-SICA PUCARA LASANA','Metropolitana','QUILICURA','Servicio Local'),
('25798','COLEGIO RELIGIOSO SANTA MARGARITA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25799','ESC. BAS. PART. ERNESTINA KRISCHUK','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25801','ESCUELA ESP. LA ESPIGA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25803','ESC. PART. ALBERT SCHWEITZER','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25804','COLEGIO PART. ANTUPIREN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25807','ESCUELA ESP. PART. LA PASCANA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25808','ESC. BAS. PART. LAS NACIONES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25809','ESC.ESP. PART.SAN VICENTE DE PAUL DE CONCHAL-','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25812','LICEO MUNICIP. DE ADULTOS PEDRO J. RODRIGUEZ','Metropolitana','LAMPA','Municipal'),
('25814','COLEGIO SAYEN','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25817','COLEGIO CENTRO DE EDUC PERM.DE ADULTOS S','Metropolitana','MAIPÚ','Part. Pagado'),
('25818','COLEGIO PART. ADULTOS INSTITUTO ICEL','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25819','ESCUELA ESP. PART. SAN PIO DE PIETRELCINA','Metropolitana','TILTIL','Part. Subvencionado'),
('25820','ESCUELA DE PARVULOS N°1977 LA VILLITA','Metropolitana','HUECHURABA','Part. Pagado'),
('25822','ESCUELA DE PARVULOS N°1980  SAN ANTONIO MARIA ZACCARIA II','Metropolitana','SANTIAGO','Part. Pagado'),
('25823','ESCUELA DE LAS ARTES Y LA TECNOLOGIA','Metropolitana','MAIPÚ','Municipal'),
('25824','LICEO SERGIO SILVA BASCUNAN','Metropolitana','LA PINTANA','Servicio Local'),
('25825','COLEGIO SAN MIGUEL ARCANGEL DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('25826','COLEGIO ADVENTISTA LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25828','ESC. ESPECIAL PART. JAN VAN DIJK','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('25829','COLEGIO PART. SAN ADRIAN DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25831','ESCUELA BASICA PARTICULAR CONTEMPORA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25832','COLEGIO PART. PAN AMERICAN COLLEGE SANTIAGO','Metropolitana','SAN MIGUEL','Part. Pagado'),
('25833','ESCUELA BASICA N° 1986 SAINT PAUL MONTESSORI SCHOOL','Metropolitana','LAS CONDES','Part. Pagado'),
('25834','ESCUELA ESP. PART. EL PRINCIPITO DE LO HERRER','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25836','ESCUELA PART. ROSA JARAQUEMADA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('25838','ESCUELA BAS. MY GARDEN SCHOOL','Metropolitana','LO PRADO','Part. Subvencionado'),
('25839','ESC. BAS. Y ESP. CELEI','Metropolitana','LO PRADO','Part. Subvencionado'),
('25842','COLEGIO DIVINA PASTORA','Metropolitana','LA FLORIDA','Part. Pagado'),
('25843','COLEGIO PART. SAGRADO CORAZON DE TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25845','ESCUELA PART. SAN MARCELO N_ 3','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25847','ESCUELA ESP. PART. SANTA ROSA DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25850','COLEGIO DEL VALLE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25851','ESC. PART. EL ARRAYAN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25852','COLEGIO DIVINA PASTORA NUNOA','Metropolitana','ÑUÑOA','Part. Pagado'),
('25853','COLEGIO POLIVALENTE NOVO HORIZONTE','Metropolitana','QUILICURA','Part. Subvencionado'),
('25854','CENTRO ESTI. DE HAB. COMUNICATIVAS AMERICA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25855','LICEO BICENTENARIO CHACABUCO','Metropolitana','COLINA','Municipal'),
('25856','ESCUELA ESP. PART. APRAVI','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25859','ESCUELA ESP. PART. RALUI','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25860','ESCUELA ESP. PART. CORDILLERA ORIENTE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25862','ESCUELA ESP. PART. CAPULLITOS DE SOL','Metropolitana','MACUL','Part. Subvencionado'),
('25865','SAN IGNACIO COLLEGE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25866','ESCUELA ESPECIAL N° 2000 SANTA ROSA DE LOS ANDES','Metropolitana','PROVIDENCIA','Part. Pagado'),
('25867','ESCUELA PART. AMANECER DE LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25868','ESCUELA ESPECIAL N° 2002 FUNDACION LEOPOLDO DONNEBAUM','Metropolitana','LA REINA','Part. Pagado'),
('25869','ESCUELA ESP. PART. SAN NICOLAS','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25871','ESCUELA DE PARVULOS N°2005 PHILLIPS GARDEN','Metropolitana','LA FLORIDA','Part. Pagado'),
('25872','ESCUELA DE PARV. CARRUSEL DE AMIGOS','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25873','ESCUELA ESP. DE LENGUAJE PLAZA SESAMO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25874','COLEGIO DE ADULTOS PART. VASCO DE GAMA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25876','COLEGIO CENTRO EDUC. Y FAMILIAR PTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25877','ESCUELA ESPECIAL DE LENGUAJE SAN NICOLÁS DE BELÉN','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25878','ESCUELA ESP. PART. AMANTU','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25881','ESCUELA ESP. PART. PATAGONIA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25882','COLEGIO NOBEL GABRIELA MISTRAL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25883','ESC. ESP. PART. SAN MATEO DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25884','ESCUELA ESP. PART. ACONCAGUA DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('25885','COLEGIO INTERCULTURAL TREMEMN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25886','ESCUELA ESPECIAL RICALHUE','Metropolitana','PAINE','Part. Subvencionado'),
('25887','ESCUELA ESPECIAL PART. ARCO IRIS','Metropolitana','PAINE','Part. Subvencionado'),
('25890','ESCUELA ESPECIAL DE LENGUJE MIS AMIGUITOS','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25894','COLEGIO MANANTIAL DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25895','COLEGIO SANTIAGO DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25897','ESCUELA PART. INSTITUTO S.A','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25899','LICEO JOSE ABELARDO NUÑEZ Nº 4','Metropolitana','HUECHURABA','Part. Subvencionado'),
('25900','ESC. ESP. VOCARE','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25901','ESC. EVANG. PENTECOSTAL DR. WILLIS C. HOOVER','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25902','ESC. DE PARV. Y ESP. RAHUE','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25903','ESCUELA ESP. MI ESPACIO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25904','ESCUELA ESP. PART. VALLE DEL SOL','Metropolitana','MACUL','Part. Subvencionado'),
('25905','ESCUELA DE PARVULOS TRENCITO FELIZ','Metropolitana','ESTACIÓN CENTRAL','Part. Pagado'),
('25906','ESCUELA ESP. PARTICULAR OSCAR CASTRO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25907','ESCUELA ESP. PART. SAN JOSE DE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25909','ESCUELA ESPECIAL ARCOIRIS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25912','ESCUELA ESP. PART. SAN JORGE DE QUINTA NORMAL','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25913','ESCUELA ESP. PART. CHARLES DE GAULLE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25914','ESCUELA PARTICULAR SUBVENCIONADA SAN JORGE DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('25916','ESCUELA BAS. SAN SEBASTIAN DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('25917','ESCUELA DE PARVULOS N°2028 SAN SEBASTIAN GARDEN','Metropolitana','COLINA','Part. Pagado'),
('25918','ESCUELA ESP. PART. CAMINO A BELEN N¦ 2','Metropolitana','HUECHURABA','Part. Subvencionado'),
('25919','ESCUELA BASICA NEHUEN','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25920','ESCUELA ESP. PART. CALIN','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25921','COLEGIO CENTRO EDUCACIONAL ROUSSEAU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25922','COLEGIO TERRA AUSTRALIS','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25923','ESCUELA ESP. PADRE PIO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25926','COLEGIO POLIV. JERUSALEN DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('25927','ESCUELA BASICA TERRA DI BIMBI','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25928','ESCUELA BASICA N° 2033 ALAMIRO','Metropolitana','LAS CONDES','Part. Pagado'),
('25929','COLEGIO PADRE PEDRO ARRUPE SAGRADA FAMILIA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25931','ESCUELA ESP. SANTA RITA DE CASIA DE QTA. NORM','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('25932','COLEGIO DE ADULTOS LONDON DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25933','ESCUELA BASICA ALBORADA SCHOOL','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25935','ESCUELA ESPECIAL LA ISLA','Metropolitana','TALAGANTE','Part. Subvencionado'),
('25936','COLEGIO NUEVO HORIZONTE DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25937','ESC. DE PARV. Y ESPECIAL COMUNICA','Metropolitana','EL MONTE','Part. Subvencionado'),
('25938','LICEO DE ADULTOS CEIA DE LA PINTANA','Metropolitana','LA PINTANA','Servicio Local'),
('25940','ESCUELA DE PARV. PARQUE O''HIGGINS','Metropolitana','SANTIAGO','Corp. Municipal'),
('25941','ESCUELA PART. SPRING COLLEGE N_ 2','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25944','ESCUELA PART. PARTHENON COLLEGE','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25946','ESCUELA PARVULOS MY SECOND HOME','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25950','COLEGIO SEMPER ALTIUS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25951','COLEGIO DE ADULTOS CARELMAPU DE CONCHALI','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25952','ESCUELA DE PARV. BERNARD COLLEGE DE SAN BERNA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25953','ESC. ESP.PART. SAN AGUSTIN DE INDEPENDENCIA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('25954','ESC. BAS. Y ESP. NTRA. SRA. DE LAS NIEVES','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25958','ESCUELA BASICA N°2047 MIRASOL DE SANTIAGO','Metropolitana','SANTIAGO','Part. Pagado'),
('25959','ESC. ESPECIAL HOSPITAL SAN JUAN DE DIOS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25960','CENTRO EDUC. PADRE ALBERTO HURTADO DE SAN BER','Metropolitana','SAN BERNARDO','Servicio Local'),
('25961','COLEGIO PALMARES','Metropolitana','QUILICURA','Part. Subvencionado'),
('25964','ESCUELA ESP. PART. ACONCAGUA DE BATUCO','Metropolitana','LAMPA','Part. Subvencionado'),
('25965','ESCUELA ESP. LAS BARRANCAS','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25967','ESCUELA DE PARVULOS N° 2054 EL PALACIO DE LOS NIÑOS','Metropolitana','MAIPÚ','Part. Pagado'),
('25969','COLEGIO TERCER MILENIO','Metropolitana','QUILICURA','Part. Subvencionado'),
('25970','ESCUELA BAS. Y ESP. EDUCAR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25971','ESCUELA ESP. ESTACION ACUARELA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25972','ESCUELA ESP. DIVINO MAESTRO DE CERRILLOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('25976','ESC. BASICA Nº 136 SAN SEBASTIAN DE PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('25977','COLEGIO DE AD. SANTA MARIA DEL TRABAJO DE EST','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('25979','ESCUELA DE PARV. CIUDAD BEBE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25982','CENTRO EDUCACIONAL DE ADULTOS PADRE ALBERTO HURTADO','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25983','ESCUELA DE PARVULOS TERESITA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25984','COLEGIO DREYSE BELSER','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25988','COLEGIO JUAN LUIS UNDURRAGA ANINAT','Metropolitana','QUILICURA','Part. Subvencionado'),
('25991','ESCUELA BAS. AMANKAY DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('25994','ESCUELA ESP. PABLO NERUDA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25995','CENTRO POLITEC. CARLOS CONDELL DE LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25996','ESCUELA ESP. EL CARMEN','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('25997','ESCUELA ESP. KINCUIN','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25998','ESCUELA ESP. TU ESPERANZA','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25999','COLEGIO ALICANTE DEL SOL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('26000','ESCUELA ESP. SOL DE LA REINA','Metropolitana','LA REINA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
