-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 24 de 31 | filas 9201-9600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('22240','ESCUELA DE PARVULOS LOS PUMITAS','Los Ríos','FUTRONO','Corp. Municipal'),
('22246','COLEGIO SHADDAI','Los Lagos','OSORNO','Part. Subvencionado'),
('22248','INSTITUTO ALEMAN PURRANQUE','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22251','JARDIN INFANTIL `MI PEQUEÑO SALESIANO`','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22253','ESCUELA PARTICULAR PROFESOR JOSE VELASQUEZ VARGAS','Los Lagos','CALBUCO','Part. Subvencionado'),
('22255','COLEGIO ADOLFO KOLPING','Los Lagos','OSORNO','Part. Subvencionado'),
('22256','CENTRO PARA LA ESTIMULACION DEL LENGUAJE INF','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22257','ESCUELA PARTICULAR PORVENIR','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22259','JARDIN INFANTIL CRISPIN','Los Ríos','VALDIVIA','Part. Pagado'),
('22260','COLEGIO SANTA ANA','Los Lagos','QUEMCHI','Part. Subvencionado'),
('22261','ESCUELA PARTICULAR PABLO NERUDA','Los Lagos','MAULLIN','Part. Subvencionado'),
('22262','COLEGIO SAN CRISTOBAL','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('22263','COLEGIO SAN MARCOS','Los Lagos','OSORNO','Part. Subvencionado'),
('22265','GREEN COUNTRY SCHOOL','Los Lagos','OSORNO','Part. Subvencionado'),
('22268','ESCUELA PARTICULAR GABRIELA MISTRAL','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22269','ESCUELA PARTICULAR TRAFUN CHICO','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22271','COLEGIO LUIS PASTEUR','Los Lagos','OSORNO','Part. Subvencionado'),
('22275','COLEGIO PARTICULAR GRACIA PAZ','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22276','LICEO DE ADULTOS CRECER OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('22277','COLEGIO NACIONAL DE LA UNION','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22280','ESCUELA PARTICULAR ALONSO DE ERCILLA','Los Ríos','FUTRONO','Part. Subvencionado'),
('22282','ESCUELA ESPECIAL DE LENGUAJE `NUEVA LENGUA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22283','COLEGIO SAN MIGUEL','Los Lagos','OSORNO','Part. Subvencionado'),
('22284','ESCUELA PARTICULAR HUALINTO','Los Lagos','RÍO NEGRO','Part. Subvencionado'),
('22291','COLEGIO KIMEL','Los Ríos','PAILLACO','Part. Subvencionado'),
('22293','ESCUELA ESPECIAL `SAN AGUSTIN`','Los Lagos','FRUTILLAR','Servicio Local'),
('22294','ESCUELA-TALLER PARA AUTISTAS `BERNARD RIMLAND`','Los Lagos','OSORNO','Part. Subvencionado'),
('22296','CORPORACION DE EDUCACION LA ARAUCANA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22306','COLEGIO PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22307','CENTRO DE EDUCACION DE ADULTOS QUELLON','Los Lagos','QUELLÓN','Servicio Local'),
('22308','ESCUELA PARA AUTISTAS `CAMINO DE ESPERANZA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22309','COLEGIO INGLÉS MABEL CONDEMARÍN','Los Lagos','LOS MUERMOS','Servicio Local'),
('22310','ESCUELA RURAL YERBAS BUENAS','Los Lagos','LOS MUERMOS','Servicio Local'),
('22312','ESCUELA HUILLON','Los Ríos','MÁFIL','Part. Subvencionado'),
('22317','COLEGIO SAN ANTONIO','Los Ríos','PAILLACO','Part. Subvencionado'),
('22318','JARDIN INFANTIL DUENDELIN','Los Ríos','PAILLACO','Part. Subvencionado'),
('22319','COLEGIO PRINCIPE DE ASTURIAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22320','ESCUELA ESPECIAL DE LENGUAJE KAUKALEM','Los Lagos','OSORNO','Part. Subvencionado'),
('22321','ESCUELA DE LENGUAJE FOR FARIS','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22322','DHARMA COLLEGE','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22323','ESCUELA PARTICULAR LA POZA','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22325','ESCUELA PARTICULAR CHOVI-SAN JUAN','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22327','COLEGIO GABRIELA MISTRAL','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22330','CENTRO EDUCACIONAL SAN AGUSTIN','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22332','ESCUELA DE PARVULOS `ADRICLAUS`','Los Lagos','OSORNO','Part. Pagado'),
('22333','ESCUELA FRANCIA','Los Ríos','VALDIVIA','Servicio Local'),
('22334','ESCUELA PARTICULAR EL ARRAYAN','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22337','ESCUELA PARTICULAR LOS CASTANOS','Los Ríos','FUTRONO','Part. Subvencionado'),
('22338','ESCUELA PARTICULAR PEDERNAL ALTO','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22339','COLEGIO GHANDI','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22340','ESCUELA PARTICULAR EL COPIHUE','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22342','ESCUELA PARTICULAR DELIA DOMINGUEZ','Los Lagos','OSORNO','Part. Subvencionado'),
('22343','COLEGIO SAN SEBASTIAN','Los Lagos','CALBUCO','Part. Subvencionado'),
('22346','ESCUELA PARTICULAR SANTA ROSA','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('22348','ESCUELA PARTICULAR SAGRADO CORAZON','Los Lagos','MAULLIN','Part. Subvencionado'),
('22349','ESCUELA PARTICULAR SICHAHUE','Los Ríos','FUTRONO','Part. Subvencionado'),
('22351','INSTITUTO INMACULADA CONCEPCION','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22352','ESCUELA PARTICULAR EL DESPERTAR','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('22353','ESCUELA PARTICULAR TRULLUN MAPU','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22354','ESCUELA EL MAITEN','Los Ríos','LA UNIÓN','Corp. Municipal'),
('22355','COLEGIO SAN ANDRES','Los Lagos','OSORNO','Part. Subvencionado'),
('22356','COLEGIO PAIDEIA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22358','COLEGIO INGLES','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22361','COLEGIO PARTICULAR ANTARES DE ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22363','CENTRO DE LENGUAJE KALEM','Los Lagos','CASTRO','Part. Subvencionado'),
('22366','COLEGIO ROBERT PACE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22367','ESCUELA PARTICULAR BOSQUE VERDE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22372','COMPLEJO EDUCACIONAL SAN CRESCENTE','Los Lagos','CASTRO','Part. Subvencionado'),
('22373','ESCUELA PARTICULAR MILLARAY','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22374','INSTITUTO TECNOLOGICO DEL SUR','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22375','ESCUELA PARTICULAR ALLA MAPU','Los Lagos','ANCUD','Part. Subvencionado'),
('22379','ESCUELA DE LENGUAJE `ABRAPALABRA`','Los Lagos','CHONCHI','Part. Subvencionado'),
('22380','ESCUELA BASICA SECTOR ORIENTE','Los Lagos','QUELLÓN','Servicio Local'),
('22382','ESCUELA ESPECIAL DE LENGUAJE `SAN JUAN`','Los Lagos','ANCUD','Part. Subvencionado'),
('22383','ESCUELA PARTICULAR ROSALIA OJEDA SANCHEZ','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22384','JARDIN INFANTIL CARRUSEL','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22386','JARDIN INFANTIL `TIA MARTITA`','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22387','ESCUELA ESPECIAL DE LENGUAJE GIRASOL','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22388','CENTRO DE EDUC. DE ADULTOS SANDROCK','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22390','ESCUELA PARTICULAR CANDELARIA','Los Lagos','MAULLIN','Part. Subvencionado'),
('22394','ESCUELA ESPECIAL `SANTA HELENA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22395','JARDIN INFANTIL `PRINCIPITO`','Los Lagos','QUELLÓN','Part. Pagado'),
('22396','ESCUELA PARTICULAR LA COLONIA','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('22397','COLEGIO TECNICO PROFESIONAL SANTA TERESA DE LOS ANDES','Los Lagos','OSORNO','Part. Subvencionado'),
('22398','COLEGIO ALIWEN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22401','CENTRO DE EDUCACION DE ADULTOS ESMERALDA','Los Lagos','ANCUD','Part. Subvencionado'),
('22402','ESCUELA DE TRASTORNOS DE LA COMUNICACION `ALEXANDRIA`','Los Lagos','OSORNO','Part. Subvencionado'),
('22403','LICEO DE CULTURA Y DIFUSIÓN ARTÍSTICA DE CHILOE','Los Lagos','CASTRO','Servicio Local'),
('22405','CENTRO EDUCACIONAL DE ADULTOS DIEGO PORTALES','Los Lagos','OSORNO','Part. Subvencionado'),
('22408','ESCUELA PARTICULAR JEAN PIAGET','Los Lagos','CALBUCO','Part. Subvencionado'),
('22410','COLEGIO CREACION OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('22413','COLEGIO TENAUN ALTO','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22414','ESCUELA PAMPA RIOS','Los Ríos','RÍO BUENO','Corp. Municipal'),
('22415','INST. SUPERIOR DE ADMINISTRACION Y TURISMO','Los Ríos','VALDIVIA','Servicio Local'),
('22418','ESCUELA BASICA KIMUN LAWAL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22419','ESCUELA PADRE ALBERTO HURTADO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22420','ESCUELA NUEVA PENSYLVANIA','Los Lagos','MAULLIN','Corp. Municipal'),
('22421','CENTRO DE INTEGRACION LABORAL','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22424','JARDIN INFANTIL MANITOS TRAVIESAS','Los Lagos','OSORNO','Part. Subvencionado'),
('22425','ESCUELA PARTICULAR CURAMO','Los Lagos','ANCUD','Part. Subvencionado'),
('22427','ESCUELA PARTICULAR EMMANUEL','Los Lagos','PUERTO OCTAY','Part. Subvencionado'),
('22428','ESCUELA PADRE LUIS BELTRAN','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22429','ESCUELA PARTICULAR WE LIWEN','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22430','COLEGIO CRECER','Los Lagos','PURRANQUE','Corp. Municipal'),
('22433','ESCUELA PARTICULAR PUERTO ESPERANZA','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('22434','COLEGIO DOMINGO SANTA MARIA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22436','THE MISSION COLLEGE','Los Lagos','OSORNO','Part. Subvencionado'),
('22438','ESCUELA ESPECIAL `TALLERES LABORALES INPROA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22439','COLEGIO TERRA NOVA','Los Lagos','QUEILÉN','Part. Subvencionado'),
('22444','ESCUELA LLEQUEN','Los Lagos','ANCUD','Part. Subvencionado'),
('22445','CENTRO DE EDUC. DE ADULTOS ELIER','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22446','CENT.EDUC.INTEG.ADULTOS PROFASOC','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('22447','CENTRO EDUCACIONAL TRAF TREMUN','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22448','ESCUELA PARTICULAR EL CARDO','Los Ríos','PAILLACO','Part. Subvencionado'),
('22451','COLEGIO RENUEVO','Los Lagos','SAN PABLO','Part. Subvencionado'),
('22452','COLEGIO MOUNTAIN GREEN SCHOOL','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22456','COLEGIO SAN PABLO','Los Lagos','ANCUD','Part. Subvencionado'),
('22458','COLEGIO CELIPRAS RIO BUENO','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('22459','COLEGIO LAICO VALDIVIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22461','COLEGIO NUEVO HORIZONTE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22462','COLEGIO BERNARDO FELMER NIKLITSCHEK','Los Ríos','LANCO','Part. Subvencionado'),
('22464','LICEO BICENTENARIO DE EXCELENCIA DE DALCAHUE','Los Lagos','DALCAHUE','Servicio Local'),
('22466','LICEO DE ADMINISTRACION Y COMERCIO SAN SEBASTIAN','Los Lagos','OSORNO','Part. Subvencionado'),
('22467','COLEGIO LAFQUEN MONTESSORI PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22468','ESCUELA ESPECIAL DE LENGUAJE `AMAPOLA`','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22471','JARDIN INFANTIL BAMBI Y CELIN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22472','JARDIN INFANTIL `MANZANITA`','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22473','INSTITUTO APRENDER','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22475','INSTITUTO APRENDER','Los Lagos','FRESIA','Part. Subvencionado'),
('22476','COLEGIO SAN JOSE','Los Ríos','MARIQUINA','Servicio Local'),
('22478','COLEGIO VENCEDOR','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22479','ESCUELA DE LENGUAJE AYELEN','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22480','COLEGIO LOS ALERCES','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22482','CENTRO EDUCACIONAL AMANCAY','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22483','LICEO BICENTENARIO DE EXCELENCIA ALTAMIRA','Los Ríos','PANGUIPULLI','Servicio Local'),
('22485','COLEGIO DE ADULTOS PUDETO','Los Lagos','ANCUD','Part. Subvencionado'),
('22486','ESCUELA SAN FRANCISCO DE LLENEHUE','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22487','CENTRO INTEGRAL DE EDUCACION GABRIELA PASCHUAN','Los Lagos','ANCUD','Part. Subvencionado'),
('22489','ESCUELA PARTICULAR RAYEN QUITRAL','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22492','ESCUELA PARTICULAR TICALHUE','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22493','ESCUELA VICENTE PEREZ ROSALES','Los Lagos','FRUTILLAR','Servicio Local'),
('22494','LICEO TECNICO PROFESIONAL AGRICOLA MARITIMO BOSQUE NATIVO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22496','CENTRO EDUCACIONAL SAN NICOLAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22499','INSTITUTO INGLES ANTUQUENU','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22503','COLEGIO AGUILAS DEL SUR','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22504','LICEO FRANCISCO COLOANE','Los Lagos','CASTRO','Servicio Local'),
('22505','COLEGIO CHARLES DARWIN DE ANCUD','Los Lagos','ANCUD','Part. Subvencionado'),
('22506','COLEGIO PUMAHUE','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22509','ESCUELA ALEMANIA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22514','CENTRO INTEGRAL DE ADULTOS TREUCANCHE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22516','INSTITUTO CRISTIANO GRACIA Y PAZ','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22519','COLEGIO MIRADOR DEL LAGO','Los Lagos','PUERTO VARAS','Servicio Local'),
('22520','ESCUELA DE LENGUAJE MIS PALABRAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22521','ESCUELA ESPECIAL DE ESTIMULACION E INTEGRACION EL UMBRAL','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22522','COLEGIO SAN MARTIN DE LAS LOMAS','Los Ríos','MÁFIL','Part. Subvencionado'),
('22525','JARDIN INFANTIL ANGELITO','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22526','JARDIN INFANTIL LOS CISNES','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22527','CENTRO EDUCACIONAL SAN SEBASTIAN','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('22529','ESCUELA ESPECIAL DE LENGUAJE KALEM RAHUE','Los Lagos','OSORNO','Part. Subvencionado'),
('22531','ESCUELA CLAUDIO ARRAU LEON','Los Ríos','PANGUIPULLI','Servicio Local'),
('22532','ESCUELA EL BOSQUE','Los Ríos','VALDIVIA','Servicio Local'),
('22533','COLEGIO MON MAPU','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22535','LICEO BILINGUE TERESA DE LOS ANDES','Los Lagos','CASTRO','Servicio Local'),
('22536','CENTRO EDUCACIONAL SAN SEBASTIAN DE ANCUD','Los Lagos','ANCUD','Part. Subvencionado'),
('22537','COLEGIO FRANCISCA BELEN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22539','ESCUELA JOSE MANUEL BALMACEDA','Los Lagos','CALBUCO','Corp. Municipal'),
('22540','INSTITUTO ITALIA DE VALDIVIA','Los Ríos','VALDIVIA','Servicio Local'),
('22542','COLEGIO SAN ALBERTO HURTADO','Los Lagos','OSORNO','Part. Subvencionado'),
('22543','LICEO COMERCIAL MIRAMAR','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22544','LICEO POLIVALENTE BENJAMIN VICUÑA MACKENNA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22545','INSTITUTO CECAL SUR','Los Lagos','CASTRO','Part. Subvencionado'),
('22546','GREEN COLLEGE','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22547','ESCUELA ESPECIAL DE LENGUAJE PULMAHUE','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22549','CENTRO DE EDUCACIÓN INTEGRAL DE ADULTOS NUEVO HORIZONTE','Los Ríos','PANGUIPULLI','Servicio Local'),
('22550','JARDIN INFANTIL BLANCANIEVES','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22551','LICEO TECNICO PROFESIONAL GABRIELA MISTRAL','Los Lagos','CASTRO','Part. Subvencionado'),
('22552','ESCUELA PARTICULAR SAGRADA FAMILIA','Los Ríos','FUTRONO','Part. Subvencionado'),
('22553','INSTITUTO TÉCNICO FORJADORES DE ALERCE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22554','ESCUELA BASICA SAN CARLOS DE CHONCHI','Los Lagos','CHONCHI','Servicio Local'),
('22556','ESCUELA PARTICULAR COLONIA DEGAÑ','Los Lagos','ANCUD','Part. Subvencionado'),
('22558','ESCUELA NUEVA COLLILELFU','Los Ríos','LOS LAGOS','Servicio Local'),
('22560','COLEGIO COLONOS DE ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22561','COLEGIO ESTRELLA DE BELEN','Los Lagos','CALBUCO','Part. Subvencionado'),
('22564','LICEO BICENTENARIO ADOLFO MATTHEI','Los Lagos','OSORNO','Part. Subvencionado'),
('22565','COLEGIO EL PILAR','Los Lagos','ANCUD','Part. Subvencionado'),
('22566','ESCUELA PARTICULAR BICENTENARIO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22571','CENTRO DE ESTIMULACION TEMPRANA INKA POYEN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22573','ESCUELA ESPECIAL TALLER LABORAL RIE','Los Lagos','OSORNO','Part. Subvencionado'),
('22574','ESCUELA ESPECIAL DE LENGUAJE CRECER','Los Lagos','CALBUCO','Part. Subvencionado'),
('22575','JARDIN INFANTIL GASPARIN','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('22578','ESCUELA ESPECIAL DE LENGUAJE ABRACADABRA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22579','ESCUELA ESPECIAL DE LENGUAJE ANDORRA','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22580','ESCUELA ESPECIAL DE LENGUAJE LAS VOCALES','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22581','COLEGIO RAICES DE LEMUY','Los Lagos','PUQUELDÓN','Part. Subvencionado'),
('22584','ESCUELA PARTICULAR MI FUTURO','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22585','ESCUELA ESPECIAL DE LENGUAJE HABLARTE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22588','COLEGIO CRISTIANO BELEN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22591','JARDIN INFANTIL BLANCA NIEVES','Los Ríos','PAILLACO','Part. Subvencionado'),
('22595','JARDIN INFANTIL INALUN','Los Lagos','CASTRO','Part. Pagado'),
('22596','CENTRO INCLUSIVO DE PARVULOS INALUN','Los Lagos','CASTRO','Part. Subvencionado'),
('22597','LICEO TECNICO PROFESIONAL SAN JOSE','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22599','ESCUELA ESPECIAL DE LENGUAJE MARIA PAZ','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22601','ESCUELA DE PARVULOS DUENDELIN','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22602','SAINT PAUL COLLEGE','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('22603','ESCUELA ESPECIAL `UN MUNDO ESPECIAL`','Los Lagos','OSORNO','Part. Subvencionado'),
('22604','INSTITUTO APRENDER','Los Lagos','HUALAIHUÉ','Part. Subvencionado'),
('22606','ESCUELA INTEGRADA JUAN PABLO II','Los Lagos','MAULLIN','Part. Subvencionado'),
('22608','COLEGIO EL LABRADOR','Los Lagos','OSORNO','Part. Subvencionado'),
('22609','COLEGIO CHILENO NORTEAMERICANO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22610','ESCUELA PARTICULAR NIDO DE CISNES','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22612','CENTRO EDUCACIONAL GARYES','Los Lagos','ANCUD','Part. Subvencionado'),
('22613','ESCUELA PARTICULAR CRECER','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22614','ESCUELA ESPECIAL DE LENGUAJE SOÑANDO Y CREANDO','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22615','ESCUELA PARTICULAR OMILEN ANTU','Los Lagos','ANCUD','Part. Subvencionado'),
('22616','COLEGIO MOZART','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22617','ESCUELA ESPECIAL DE LENGUAJE RELMU DUNGUN','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22618','ESCUELA DIFERENCIAL CELIPRAS','Los Ríos','LOS LAGOS','Part. Subvencionado'),
('22620','ESCUELA PARTICULAR ANTUMAPU','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('22621','COLEGIO CALBUCO','Los Lagos','CALBUCO','Part. Subvencionado'),
('22623','COLEGIO AYELEN','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22624','COLEGIO DE ADULTOS BONILLA','Los Lagos','ANCUD','Part. Subvencionado'),
('22626','INSTITUTO BICENTENARIO DE EXCELENCIA POLITECNICO','Los Lagos','OSORNO','Corp. Municipal'),
('22627','HAMPTON COLLEGE','Los Ríos','VALDIVIA','Part. Pagado'),
('22629','COLEGIO LOS CONQUISTADORES','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22633','LICEO TEC. PROF. DE ADULTOS CORESOL DE VALDIV','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22634','INSTITUTO PRINCIPE DE ASTURIAS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22637','C.E.I.A. ARTURO PRAT','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22638','LICEO TECNICO PROFESIONAL DE ADULTOS CORESOL DE PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22639','ESCUELA HOSPITALARIA VALDIVIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22641','COLEGIO SAGRADA FAMILIA','Los Lagos','HUALAIHUÉ','Part. Subvencionado'),
('22643','ESCUELA ESPECIAL ANDRES BELLO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22646','ROYAL SCHOOL','Los Lagos','OSORNO','Part. Subvencionado'),
('22647','ESCUELA ESPECIAL DE LENGUAJE GIRASOLES','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('22648','ESCUELA ESPECIAL DE LENGUAJE LOS CISNES','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('22654','ESCUELA ESPECIAL DE LENGUAJE DEL SABER','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('22655','LICEO CARELMAPU','Los Lagos','MAULLIN','Corp. Municipal'),
('22656','COLEGIO LLACOLEN','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22657','COLEGIO PARTICULAR GOLETA ANCUD','Los Lagos','ANCUD','Part. Subvencionado'),
('22658','CENTRO EDUCACIONAL EMANUEL','Los Lagos','QUELLÓN','Part. Subvencionado'),
('22660','CENTRO DE ESTUDIOS LA ARAUCANA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22661','ESCUELA ESPECIAL DE LENGUAJE DIALECTA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22662','JARDIN INFANTIL RINCONCITO FELIZ','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22663','COLEGIO MONTE VERDE','Los Lagos','CASTRO','Part. Subvencionado'),
('22664','LICEO POLITECNICO MIRASOL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22665','ESCUELA ESPECIAL DE LENGUAJE BOSQUEMAR','Los Lagos','ANCUD','Part. Subvencionado'),
('22668','CENTRO EDUCACIONAL AMADOR CARDENAS PAREDES','Los Lagos','QUINCHAO','Part. Subvencionado'),
('22669','SALA CUNA Y JARDIN INFANTIL BICHITOS DE LUZ','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22671','COLEGIO FRANCISCO HERNANDEZ ORTIZ','Los Lagos','CALBUCO','Part. Subvencionado'),
('22672','COLEGIO ALTAS CUMBRES','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22673','LA ARAUCANA EDUCACION','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22674','LICEO BICENTENARIO POLIVALENTE DE QUEILEN','Los Lagos','QUEILÉN','Servicio Local'),
('22676','ESCUELA ESPECIAL DE LENGUAJE ALEGRIA','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22677','ESCUELA ESPECIAL Y TALLER LABORAL RAICES','Los Lagos','OSORNO','Part. Subvencionado'),
('22679','ESCUELA ESPECIAL DE LENGUAJE TECNOLOGICA','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22680','ESCUELA ESPECIAL DE LENGUAJE ACUARELA DE PALABRAS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22682','ESCUELA ESPECIAL DE LENGUAJE ALIWEN','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('22683','COLEGIO BRITISH ROYAL SCHOOL PUERTO VARAS','Los Lagos','OSORNO','Part. Subvencionado'),
('22685','ESCUELA PARTICULAR SAN BENITO','Los Lagos','SAN PABLO','Part. Subvencionado'),
('22686','ESCUELA BASICA LAS CAMELIAS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('22687','ESCUELA ESPECIAL DE LENGUAJE SEMBRANDO PALABRAS','Los Lagos','PURRANQUE','Part. Subvencionado'),
('22688','COLEGIO BOSQUES DE ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22690','COLEGIO AYTUE','Los Lagos','ANCUD','Part. Subvencionado'),
('22691','LICEO FRANCISCO HERNANDEZ ORTIZ-PIZARRO','Los Lagos','CALBUCO','Corp. Municipal'),
('22692','PATAGONIA COLLEGE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22696','JARDIN INFANTIL Y SALA CUNA EL CASTILLITO','Los Lagos','PUERTO VARAS','Part. Pagado'),
('22697','CENTRO EDUCACIONAL SAN GABRIEL','Los Lagos','CASTRO','Part. Subvencionado'),
('22699','CENTRO EDUCACIONAL CRECER','Los Lagos','DALCAHUE','Part. Subvencionado'),
('22700','ESCUELA ESPECIAL DE LENGUAJE FANTASIA','Los Lagos','OSORNO','Part. Subvencionado'),
('22701','CENTRO DE INTEGRACION LABORAL LAGOS DEL SUR','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('22702','COLEGIO PATAGONIA ALERCE CORDILLERA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22704','ESCUELA ESPECIAL DE LENGUAJE CASTILLO DE PALABRAS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22705','SALA CUNA Y JARDIN INFANTIL MAGICA FANTASIA','Los Lagos','PUERTO MONTT','Part. Pagado'),
('22706','ESCUELA ESPECIAL DE LENGUAJE AVELLANOS','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('22707','COLEGIO GILGAL','Los Lagos','OSORNO','Part. Subvencionado'),
('22709','ESCUELA ESPECIAL DE LENGUAJE EDELWEISS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22710','ESCUELA ESPECIAL DE LENGUAJE SOL DE IDEAS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('22719','ESCUELA ESPECIAL Nº2489 SAN MIGUEL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('22736','ESCUELA ESPECIAL DE LENGUAJE RINCÓN DEL SABER','Ñuble','BULNES','Part. Subvencionado'),
('22738','COLEGIO SAN LUCAS DE VALDIVIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22739','CENTRO EDUCACIONAL INFANTIL MELIANTU','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22742','ESCUELA ESPECIAL DE LENGUAJE ABRACADABRA','Los Ríos','PAILLACO','Part. Subvencionado'),
('22743','GARDEN COLLEGE','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22744','ESCUELA DE LENGUAJE AMANKAY','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22745','JARDIN INFANTIL TRENCITO DE LOS SUEÑOS','Los Ríos','VALDIVIA','Part. Pagado'),
('22747','CENTRO EDUCATIVO SAGRADO CORAZON DE JESUS','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22749','ESCUELA PARTICULAR COUNTRY SCHOOL','Los Ríos','PAILLACO','Part. Subvencionado'),
('22752','LICEO BICENTENARIO DE EXCELENCIA AGRICOLA TECNOLOGICO WERNER GROB STOLZENBACH','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('22753','ESCUELA PARTICULAR ADONAI','Los Ríos','PAILLACO','Part. Subvencionado'),
('22754','CTRO. EDUC.ESTIM. INTEGRAL HUELEMU','Los Ríos','FUTRONO','Part. Subvencionado'),
('22755','LICEO TECNICO PROFESIONAL DE RIO BUENO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('22756','COLEGIO AUSTRAL LANCO','Los Ríos','LANCO','Part. Subvencionado'),
('22757','CENTRO DE CAPAC.LAB. ALERCE ANDINO','Los Ríos','MARIQUINA','Part. Subvencionado'),
('22758','LICEO BICENTENARIO COMPLEJO EDUCACIONAL IGNAO','Los Ríos','LAGO RANCO','Corp. Municipal'),
('22759','MASTER COLLEGE','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22760','ESCUELA ESPECIAL DE LENGUAJE WORDS WISE','Los Ríos','VALDIVIA','Part. Subvencionado'),
('22762','COLEGIO ESPECIAL CELIPRAS','Los Ríos','PAILLACO','Part. Subvencionado'),
('22766','COLEGIO SAN MARCOS','Los Ríos','VALDIVIA','Part. Subvencionado'),
('24201','LICEO BICENTENARIO AUSTRAL LORD COCHRANE','Aysén','COCHRANE','Servicio Local'),
('24203','LICEO RAUL BROUSSAIN CAMPINO','Aysén','AYSÉN','Servicio Local'),
('24204','LICEO BICENTENARIO DE EXCELENCIA ARTURO PRAT CHACON','Aysén','CISNES','Servicio Local'),
('24206','CENTRO INTEGRAL DE EDUCACIÓN ALBORADA','Aysén','COYHAIQUE','Part. Subvencionado'),
('24207','LICEO SAN JOSE U.R.','Aysén','AYSÉN','Part. Subvencionado'),
('24209','COLEGIO SAGRADA FAMILIA','Aysén','AYSÉN','Part. Subvencionado'),
('24210','ESCUELA MADRE DE LA DIVINA PROVIDENCIA','Aysén','CISNES','Servicio Local'),
('24212','COLEGIO ALIANZA AUSTRAL DE COYHAIQUE','Aysén','COYHAIQUE','Part. Subvencionado'),
('24213','LICEO BICENTENARIO SANTA TERESA DE LOS ANDES','Aysén','AYSÉN','Part. Subvencionado'),
('24214','ESCUELA ALTAMIRA DE COYHAIQUE','Aysén','COYHAIQUE','Part. Subvencionado'),
('24215','CENTRO DE EDUCACION INTEGRADA DE ADULTOS','Aysén','COYHAIQUE','Servicio Local'),
('24216','ESCUELA BASICA DE CHILE CHICO','Aysén','CHILE CHICO','Servicio Local'),
('24218','ESC.NUESTRA SRA DE LA DIVINA PROVIDENCIA','Aysén','CISNES','Part. Subvencionado'),
('24220','ESCUELA ANEXA INDEPENDENCIA','Aysén','COYHAIQUE','Servicio Local'),
('24223','ESCUELA DE LENGUAJE KALEM','Aysén','AYSÉN','Part. Subvencionado'),
('24224','COLEGIO ANTOINE DE SAINT EXUPERY','Aysén','COYHAIQUE','Part. Subvencionado'),
('24226','COLEGIO EL CAMINO DE LA FUENTE','Aysén','COYHAIQUE','Part. Subvencionado'),
('24229','ESCUELA LITORAL AUSTRAL','Aysén','AYSÉN','Servicio Local'),
('24230','COLEGIO KALEM BICENTENARIO','Aysén','AYSÉN','Part. Subvencionado'),
('24231','COLEGIO DIEGO PORTALES','Aysén','COYHAIQUE','Part. Subvencionado'),
('24232','ESCUELA ESPECIAL PRE-BASICA CLUB DE LEONES','Aysén','COYHAIQUE','Part. Subvencionado'),
('24233','LICEO FRANCISCO XAVIER BUTINA','Aysén','COYHAIQUE','Part. Subvencionado'),
('24234','COLEGIO INSTITUTO IDEA DE COYHAIQUE','Aysén','COYHAIQUE','Part. Subvencionado'),
('24236','COLEGIO CAMPO DE HIELO','Aysén','COYHAIQUE','Part. Subvencionado'),
('24237','CEIA JOSEFINA MENDEZ E.I.R.L.','Aysén','COYHAIQUE','Part. Subvencionado'),
('24238','CENTRO DE ESTUDIOS PATAGONIA LTDA','Aysén','COYHAIQUE','Part. Subvencionado'),
('24240','LICEO BICENTENARIO ALTOS DEL MACKAY','Aysén','COYHAIQUE','Servicio Local'),
('24241','CENTRO DE ESTUDIOS PATAGONIA DE AYSEN','Aysén','AYSÉN','Part. Subvencionado'),
('24243','COLEGIO CRISTIANO SEMBRADORES','Aysén','COYHAIQUE','Part. Subvencionado'),
('24300','LICEO GABRIELA MISTRAL','Magallanes','NATALES','Servicio Local'),
('24302','ESCUELA GENERAL MANUEL BULNES P.','Magallanes','PUNTA ARENAS','Servicio Local'),
('24303','LICEO NOBELIUS','Magallanes','PUNTA ARENAS','Part. Pagado'),
('24305','COLEGIO PIERRE FAURE','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24307','LICEO JUAN BAUTISTA CONTARDI','Magallanes','PUNTA ARENAS','Servicio Local'),
('24311','COLEGIO FRANCES','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24312','CENTRO DE CAPAC. LABORAL LEON HUMBERTO SEGUEL','Magallanes','PUNTA ARENAS','Servicio Local'),
('24313','ESCUELA VILLA LAS NIEVES','Magallanes','PUNTA ARENAS','Servicio Local'),
('24314','COLEGIO CRUZ DEL SUR','Magallanes','PUNTA ARENAS','Part. Pagado'),
('24316','LICEO POLITEC.CARDENAL RAUL SILVA HENRIQUEZ','Magallanes','PUNTA ARENAS','Servicio Local'),
('24317','COLEGIO PUERTO NATALES','Magallanes','NATALES','Part. Subvencionado'),
('24318','ESCUELA PADRE ALBERTO HURTADO CRUCHAGA','Magallanes','PUNTA ARENAS','Servicio Local'),
('24319','COLEGIO PUNTA ARENAS','Magallanes','PUNTA ARENAS','Part. Pagado'),
('24320','TALLER LABORAL DE UNPADE','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24321','ESCUELA ESPECIAL CLUB DE LEONES CRUZ DEL SUR','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24322','ESCUELA BASICA RURAL SENO OBSTRUCCION','Magallanes','NATALES','Servicio Local'),
('24324','GREEN HILL COLLEGE','Magallanes','PUNTA ARENAS','Part. Pagado'),
('24325','ESCUELA RURAL CERRO GUIDO','Magallanes','TORRES DEL PAINE','Servicio Local'),
('24327','LICEO EXPERIMENTAL UMAG','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24329','LICEO SAN JOSE','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24330','FUNDACIÓN PARA EL DESARROLLO','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24331','ESCUELA ESPECIAL DE LENGUAJE IERUN TALJ','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24332','CEIA CARLOS YANEZ MOYA','Magallanes','NATALES','Servicio Local'),
('24333','ESCUELA ESPECIAL CLUB DE LEONES CRUZ DEL SUR','Magallanes','NATALES','Part. Subvencionado'),
('24335','ESC. ESP. DE LENGUAJE NUEVO SOL','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24336','ESC. ESP. DE LENGUAJE SANTA LAURA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24338','COLEGIO LUTERANO','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24339','ESC. ESP. DE TRASTORNOS DE LA COMUNICACION AL','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24341','ESCUELA PAMPA GUANACO','Magallanes','TIMAUKEL','Servicio Local'),
('24342','ESCUELA ESPECIAL DE LENGUAJE RAYITO DE LUZ','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('24400','ESCUELA BASICA PARTICULAR DEUTSCHLAND','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('24401','COLEGIO CAPITAN PASTENE','Metropolitana','LA FLORIDA','Municipal'),
('24403','COLEGIO SIMON BOLIVAR','Metropolitana','LA PINTANA','Servicio Local'),
('24405','COLEGIO POLIVALENTE LOVAINA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24406','ESCUELA BASICA PARTICULAR KIND`S SCHOOL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24407','COLEGIO SANTA TERESA DE JESUS DE LOS ANDES','Metropolitana','HUECHURABA','Part. Subvencionado'),
('24409','COLEGIO SAN NICOLAS DE MYRA','Metropolitana','LAS CONDES','Part. Pagado'),
('24410','COLEGIO SANTA MARIA DE LA CORDILLERA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24412','COLEGIO FINLANDIA','Metropolitana','PUDAHUEL','Servicio Local'),
('24414','ESCUELA DE PARVULOS N°1385 JARDIN INFANTIL ANDY','Metropolitana','LA FLORIDA','Part. Pagado'),
('24420','ESCUELA BASICA COLEGIO VILLA LOGRONO','Metropolitana','MELIPILLA','Part. Subvencionado'),
('24423','COLEGIO SAN JUAN DIEGO','Metropolitana','RECOLETA','Part. Subvencionado'),
('24424','COLEGIO PARTICULAR LA UNION','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24426','ESCUELA PARTICULAR PHILIPPE COUSTEAU','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24427','COLEGIO SAN VIATOR','Metropolitana','MACUL','Part. Subvencionado'),
('24428','ESCUELA BÁSICA PARTICULAR ARCÁNGEL DE MARÍA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24431','COLEGIO HAYDN DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24438','COLEGIO MERRYLAND','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24442','ESCUELA ESPECIAL OPEN DOOR','Metropolitana','PUENTE ALTO','Municipal'),
('24443','LICEO MUNICIPAL CHILOE','Metropolitana','PUENTE ALTO','Municipal'),
('24444','LICEO INDUSTRIAL HARDWARE','Metropolitana','SAN BERNARDO','Servicio Local'),
('24445','LICEO MUNICIPAL EL ROBLE','Metropolitana','LA PINTANA','Servicio Local'),
('24446','COMPLEJO EDUCACIONAL ERNESTO MULLER LOPEZ','Metropolitana','TALAGANTE','Part. Subvencionado'),
('24448','COLEGIO ARTISTICO EL SALVADOR ANEXO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24454','COLEGIO DE ADULTOS FEDESO','Metropolitana','RECOLETA','Part. Pagado'),
('24459','COLEGIO BETANIA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('24461','ESCUELA DE PARVULOS N°1246 EL OLYMPO','Metropolitana','MAIPÚ','Part. Pagado'),
('24464','ESCUELA BASICA MERCEDES MARIN DEL SOLAR','Metropolitana','PROVIDENCIA','Municipal'),
('24473','COLEGIO TEC.HOTELERIA Y GASTRONOMIA ACHIGA CO','Metropolitana','LAS CONDES','Part. Subvencionado'),
('24482','LICEO POLITECNICO PARTICULAR ANDES','Metropolitana','RENCA','Part. Subvencionado'),
('24484','ESC. ESPECIAL PART.NUESTRO HORIZONTE','Metropolitana','COLINA','Part. Subvencionado'),
('24486','COLEGIO POLIVALENTE SAN RAFAEL','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('24487','ESCUELA ESPECIAL N°1402 CENTRO DE EDUCACION ESPECIAL COOCENDE','Metropolitana','LAS CONDES','Part. Pagado'),
('24489','ESC. PART.BASICA SAINT PHILLIP OF NERY 2','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('24491','COLEGIO INTERNATIONAL COUNTRY SCHOOL','Metropolitana','PUENTE ALTO','Part. Pagado'),
('24493','ESCUELA PARVULOS N°61 BERNADETTE SOUBIROUS','Metropolitana','PEÑAFLOR','Part. Pagado'),
('24494','COLEGIO CRECES','Metropolitana','LAS CONDES','Part. Pagado'),
('24496','COLEGIO COMERCIAL DE PENAFLOR','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('24498','COLEGIO SAN JOAQUIN','Metropolitana','RENCA','Part. Subvencionado'),
('24503','ESCUELA ESPECIAL DE LENGUAJE ALIMALINA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('24508','ANEXO ESCUELA BASICA SAN JAVIER','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24510','ESC. PART. JARDIN INFANTIL PULGARCITO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24517','ESCUELA DE PARVULOS N°1407 INST. DE SALUD PUBLICA','Metropolitana','ÑUÑOA','Part. Pagado'),
('24520','ESC. BAS.MUNICIPAL MERCEDES FONTECILLA','Metropolitana','QUILICURA','Servicio Local')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
