-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 12 de 31 | filas 4401-4800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('7337','ESCUELA GARCIA HURTADO DE MENDOZA','Los Lagos','OSORNO','Corp. Municipal'),
('7338','ESCUELA LEONILA FOLCH LOPEZ','Los Lagos','OSORNO','Corp. Municipal'),
('7339','ESCUELA N.88 CANADA','Los Lagos','OSORNO','Corp. Municipal'),
('7340','ESCUELA CLAUDIO ARRAU','Los Lagos','OSORNO','Corp. Municipal'),
('7341','ESCUELA MONSEÑOR FRANCISCO VALDES SUBERCASEAUX','Los Lagos','OSORNO','Corp. Municipal'),
('7343','ESCUELA MEXICO DE MICHOACAN','Los Lagos','OSORNO','Corp. Municipal'),
('7346','ESCUELA N. 46 ITALIA','Los Lagos','OSORNO','Corp. Municipal'),
('7347','ESCUELA DEPORTIVA OSORNO','Los Lagos','OSORNO','Corp. Municipal'),
('7348','ESCUELA CARLOS CONDELL','Los Lagos','OSORNO','Corp. Municipal'),
('7349','ESCUELA DE ARTES Y CULTURA OSORNO','Los Lagos','OSORNO','Corp. Municipal'),
('7352','ESCUELA SOCIEDAD DE SOCORRO DE SEÑORAS','Los Lagos','OSORNO','Corp. Municipal'),
('7353','ESCUELA ESPECIAL `ANA AICHELE CARRASCO`','Los Lagos','OSORNO','Corp. Municipal'),
('7354','ESCUELA RURAL LUZ Y SABER','Los Lagos','OSORNO','Corp. Municipal'),
('7355','ESCUELA RURAL EMILIO SURBER SCHULZ','Los Lagos','OSORNO','Corp. Municipal'),
('7356','ESCUELA RURAL PELLECO','Los Lagos','OSORNO','Corp. Municipal'),
('7357','ESCUELA RURAL PUCOIHUE','Los Lagos','OSORNO','Corp. Municipal'),
('7359','ESCUELA RURAL TRINQUICAHUIN','Los Lagos','OSORNO','Corp. Municipal'),
('7366','ESCUELA RURAL MARIA LUISA BOMBAL','Los Lagos','OSORNO','Corp. Municipal'),
('7368','ESCUELA RURAL SANTA ROSA','Los Lagos','OSORNO','Corp. Municipal'),
('7369','ESCUELA AGROECOLOGICA PICHIL','Los Lagos','OSORNO','Corp. Municipal'),
('7371','ESCUELA RURAL FORRAHUE','Los Lagos','OSORNO','Corp. Municipal'),
('7372','ESCUELA RURAL CANCHA LARGA','Los Lagos','OSORNO','Corp. Municipal'),
('7377','ESCUELA RURAL WALTERIO MEYER RUSCA','Los Lagos','OSORNO','Corp. Municipal'),
('7380','ESCUELA RURAL LUMACO','Los Lagos','OSORNO','Corp. Municipal'),
('7381','ESCUELA RURAL CHACAYAL','Los Lagos','OSORNO','Corp. Municipal'),
('7382','ESCUELA RURAL LOS ABEDULES','Los Lagos','OSORNO','Corp. Municipal'),
('7384','ESCUELA RURAL TACAMO ALTO','Los Lagos','OSORNO','Corp. Municipal'),
('7385','ESCUELA PARTICULAR N.137 ARTURO ALESSANDRI','Los Lagos','OSORNO','Part. Subvencionado'),
('7388','COLEGIO SAN JOSE','Los Lagos','OSORNO','Part. Subvencionado'),
('7390','ESCUELA PARTICULAR N.130 AURORA DE CHILE','Los Lagos','OSORNO','Part. Subvencionado'),
('7391','COLEGIO BETEL','Los Lagos','OSORNO','Part. Subvencionado'),
('7396','COLEGIO BALDOMERO LILLO','Los Lagos','OSORNO','Part. Subvencionado'),
('7397','ESCUELA DE PARVULOS N.276 `PENEQUITA DOS`','Los Lagos','OSORNO','Part. Subvencionado'),
('7401','COLEGIO SANTA MARTA','Los Lagos','OSORNO','Part. Subvencionado'),
('7403','COLEGIO WILLIAM BOOTH','Los Lagos','OSORNO','Part. Subvencionado'),
('7404','COLEGIO RENE SORIANO BORQUEZ','Los Lagos','OSORNO','Part. Subvencionado'),
('7405','ESCUELA PARTICULAR N.134 ADVENTISTA','Los Lagos','OSORNO','Part. Subvencionado'),
('7406','COLEGIO SAN MATEO','Los Lagos','OSORNO','Part. Pagado'),
('7407','ESCUELA PARVULARIA `PEDRO AGUIRRE CERDA`','Los Lagos','OSORNO','Corp. Municipal'),
('7412','ESCUELA PARTICULAR N.127 VIRGEN DE CANDELARIA','Los Lagos','OSORNO','Part. Subvencionado'),
('7414','LICEO ALIANZA FRANCESA CLAUDE GAY','Los Lagos','OSORNO','Part. Pagado'),
('7415','INSTITUTO ALEMAN DE OSORNO','Los Lagos','OSORNO','Part. Pagado'),
('7416','LICEO OSORNO COLLEGE','Los Lagos','OSORNO','Part. Pagado'),
('7418','ESCUELA BASICA SAN PABLO','Los Lagos','SAN PABLO','Corp. Municipal'),
('7419','ESCUELA DELICIO CARDENAS BUSTAMANTE','Los Lagos','SAN PABLO','Corp. Municipal'),
('7420','ESCUELA RURAL SAN PEDRO','Los Lagos','SAN PABLO','Corp. Municipal'),
('7422','ESCUELA RURAL QUITRA QUITRA','Los Lagos','SAN PABLO','Corp. Municipal'),
('7423','ESCUELA RURAL ALEJANDRO VASQUEZ BALDEVELLANO','Los Lagos','SAN PABLO','Corp. Municipal'),
('7424','ESCUELA RURAL VILLA CARACOL','Los Lagos','SAN PABLO','Corp. Municipal'),
('7427','ESCUEAL RURAL QUILEN','Los Lagos','SAN PABLO','Corp. Municipal'),
('7431','ESCUELA RURAL TRUMAO','Los Lagos','SAN PABLO','Corp. Municipal'),
('7432','ESCUELA RURAL JULIO MOHR SCHULER','Los Lagos','SAN PABLO','Corp. Municipal'),
('7433','ESCUELA RURAL LA POZA','Los Lagos','SAN PABLO','Corp. Municipal'),
('7434','ESCUELA PARTICULAR N.143 SANTA CRUZ','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7435','COLEGIO ALEMAN','Los Lagos','PUERTO VARAS','Part. Pagado'),
('7436','ESCUELA PARTICULAR N.145 QUITRA QUITRA','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7437','ESCUELA PARTICULAR N.148 LOLOLHUE','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7438','ESCUELA PARTICULAR N.150 SANTA ROSA','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7440','ESCUELA PARTICULAR N.151 PUCOPIO','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7441','COLEGIO BICENTENARIO DE EXCELENCIA QUILACAHUIN','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7443','ESCUELA PARTICULAR N.153 EL ROBLE','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7446','ESCUELA PARTICULAR N.146 ROSARIO DE LAS ANIMAS','Los Lagos','SAN PABLO','Part. Subvencionado'),
('7448','ESCUELA ENTRE LAGOS','Los Lagos','PUYEHUE','Corp. Municipal'),
('7449','ESCUELA RURAL ARMANDO SCHEUCH EPPLE','Los Lagos','PUYEHUE','Corp. Municipal'),
('7450','ESCUELA RURAL LOS PELLINES','Los Lagos','PUYEHUE','Corp. Municipal'),
('7452','ESCUELA RURAL EL ENCANTO','Los Lagos','PUYEHUE','Corp. Municipal'),
('7453','ESCUELA RURAL RADALES','Los Lagos','PUYEHUE','Corp. Municipal'),
('7458','ESCUELA RURAL ÑADY','Los Lagos','PUYEHUE','Corp. Municipal'),
('7459','ESCUELA RURAL ESTACION NUEVO PORVENIR','Los Lagos','PUYEHUE','Corp. Municipal'),
('7460','ESCUELA RURAL PILMAIQUEN','Los Lagos','PUYEHUE','Corp. Municipal'),
('7463','ESCUELA RURAL DESAGUE RUPANCO','Los Lagos','PUYEHUE','Corp. Municipal'),
('7464','ESCUELA RURAL FUTACUHIN','Los Lagos','PUYEHUE','Corp. Municipal'),
('7465','ESCUELA RURAL TERMAS DE PUYEHUE','Los Lagos','PUYEHUE','Corp. Municipal'),
('7469','ESCUELA RURAL SANTA ELVIRA','Los Lagos','PUYEHUE','Corp. Municipal'),
('7470','LICEO BICENTENARIO PEOPLE HELP PEOPLE DE PILMAIQUEN','Los Lagos','PUYEHUE','Part. Subvencionado'),
('7471','ESCUELA RURAL PAJARITOS','Los Lagos','PUYEHUE','Corp. Municipal'),
('7476','ESCUELA ALBERTO HURTADO','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7477','ESCUELA RURAL ADMINISTRACION RUPANCO','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7478','ESCUELA RURAL LAS CASCADAS','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7479','ESCUELA RURAL EL ISLOTE RUPANCO','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7489','ESCUELA RURAL LA PELLINADA','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7493','ESCUELA RURAL LAGUNA BONITA','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7496','ESCUELA RURAL NOCHACO','Los Lagos','PUERTO OCTAY','Corp. Municipal'),
('7501','ESCUELA PARTICULAR N.179 NOCHACO','Los Lagos','PUERTO OCTAY','Part. Subvencionado'),
('7502','ESCUELA PARTICULAR N.181 LAS GAVIOTAS','Los Lagos','PUERTO OCTAY','Part. Subvencionado'),
('7505','LICEO BICENTENARIO TOMAS BURGOS','Los Lagos','PURRANQUE','Corp. Municipal'),
('7507','ESCUELA BERTOLDO HOFMANN KAHLER','Los Lagos','PURRANQUE','Corp. Municipal'),
('7508','ESCUELA VILLA LO BURGOS','Los Lagos','PURRANQUE','Corp. Municipal'),
('7509','CENTRO EDUCACION INTEGRAL DE ADULTOS','Los Lagos','PURRANQUE','Corp. Municipal'),
('7510','ESCUELA RURAL LA PAZ','Los Lagos','PURRANQUE','Corp. Municipal'),
('7511','ESCUELA RURAL ANTONIO SEGUNDO FERNANDEZ PORTALES','Los Lagos','PURRANQUE','Corp. Municipal'),
('7513','ESCUELA RURAL BAHIA SAN PEDRO','Los Lagos','PURRANQUE','Corp. Municipal'),
('7518','ESCUELA RURAL LOS RISCOS','Los Lagos','PURRANQUE','Corp. Municipal'),
('7522','ESCUELA RURAL CRUCERO NUEVO','Los Lagos','PURRANQUE','Corp. Municipal'),
('7528','ESCUELA RURAL ARTURO PEREZ CANTO','Los Lagos','PURRANQUE','Corp. Municipal'),
('7531','ESCUELA PURRANQUE','Los Lagos','PURRANQUE','Corp. Municipal'),
('7534','ESCUELA RURAL CONCORDIA','Los Lagos','PURRANQUE','Corp. Municipal'),
('7535','ESCUELA RURAL NUEVA ISRAEL','Los Lagos','PURRANQUE','Corp. Municipal'),
('7536','COLEGIO PRECIOSA SANGRE','Los Lagos','PURRANQUE','Part. Subvencionado'),
('7538','ESCUELA RURAL MANQUEMAPU','Los Lagos','PURRANQUE','Corp. Municipal'),
('7539','COLEGIO ALEMAN DE PURRANQUE','Los Lagos','PURRANQUE','Part. Pagado'),
('7541','ESCUELA ANDREW JACKSON','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7542','LICEO JOSE TORIBIO MEDINA','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7543','ESCUELA RIO NEGRO','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7544','COLEGIO RIACHUELO','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7552','ESCUELA RURAL RAMON PUSCHEL APPEL','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7557','ESCUELA RURAL HUILMA GRANDE','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7559','ESCUELA RURAL LOS CASTAÑOS','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7563','ESCUELA RURAL COSTA RIO BLANCO','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7569','ESCUELA RURAL CALETA HUELLELHUE','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7572','COLEGIO SAGRADA FAMILIA','Los Lagos','RÍO NEGRO','Part. Subvencionado'),
('7573','ESCUELA RURAL LLAHUALCO','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7574','ESCUELA RURAL SAN JOSE','Los Lagos','RÍO NEGRO','Corp. Municipal'),
('7575','ESCUELA PARTICULAR N.184 VISTA HERMOSA','Los Lagos','RÍO NEGRO','Part. Subvencionado'),
('7578','LICEO BICENTENARIO AGRICOLA `VISTA HERMOSA`','Los Lagos','RÍO NEGRO','Adm. Delegada'),
('7580','ESCUELA RURAL PULOTRE','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7583','ESCUELA RURAL PUAUCHO','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7586','ESCUELA RURAL LOMA DE LA PIEDRA','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7587','ESCUELA RURAL PUÑINQUE','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7588','ESCUELA RURAL PUCATRIHUE','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7590','ESCUELA RURAL LIUCURA','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7592','ESCUELA RURAL PURREHUIN','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7593','ESCUELA RURAL BAHIA MANSA','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7596','ESCUELA RURAL CARRICO','Los Lagos','SAN JUAN DE LA COSTA','Corp. Municipal'),
('7600','ESCUELA PARTICULAR N.163 LAFQUELMAPU','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7602','ESCUELA PARTICULAR N.161 HACIENDA HUITRAPULLI','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7606','ESCUELA PARTICULAR N.164 TROSCO','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7607','ESCUELA PARTICULAR N.156 CHANCO','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7612','ESCUELA PARTICULAR N.168 CUMILELFU','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7613','ESCUELA PARTICULAR N.169 LOS HUALLES','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7614','COLEGIO BICENTENARIO DE EXCELENCIA MISION SAN JUAN DE LA COSTA','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7616','ESCUELA PARTICULAR N.166 MONTE VERDE','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7617','ESCUELA PARTICULAR N.172 PUNOTRO','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7619','ESCUELA PARTICULAR N.173 HUAMPUTUE','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7620','ESCUELA PARTICULAR N.160 MILLAHUAIMO','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7622','ESCUELA PARTICULAR N.154 HUITRAPULLI','Los Lagos','SAN JUAN DE LA COSTA','Part. Subvencionado'),
('7624','ESCUELA DE ADULTOS RELONCAVI','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7625','LICEO INDUSTRIAL PUERTO MONTT','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7626','INSTITUTO COMERCIAL DE PUERTO MONTT','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7627','LICEO DE HOMBRES MANUEL MONTT','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7628','LICEO ISIDORA ZEGERS DE HUNEEUS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7629','LICEO ANDRES BELLO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7630','ESCUELA ESPANA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7631','ESCUELA N°2 REPUBLICA ARGENTINA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7632','ESCUELA N 10 ANGELMO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7633','ESCUELA CAPITAN ARTURO PRAT CHACON','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7634','ESCUELA MIRASOL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7636','ESCUELA N 5 MIRAMAR','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7637','ESCUELA N 7 ARABE-SIRIA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7638','ESCUELA N 3 MELIPULLI','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7639','COLEGIO DARIO SALAS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7641','ESCUELA BELLAVISTA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7642','ESCUELA BASICA GABRIELA MISTRAL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7643','ESCUELA CHILOE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7644','ESCUELA BASICA SANTA INES','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7645','ESCUELA DIFERENCIAL `LOS EUCALIPTOS`','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7646','ESCUELA ROTARIO PEDRO AVELINO BRAVO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7647','ESCUELA LIBERTAD','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7648','ESCUELA MARCELA PAZ','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7650','ESCUELA DE CULTURA Y DIFUSION ARTISTICA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7651','COLEGIO TECNICO PROFESIONAL PIEDRA AZUL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7654','ESCUELA RURAL LENCA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7655','ESCUELA RURAL MAILLEN','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7656','ESCUELA BASICA DE PELLUCO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7658','ESCUELA RURAL CORRENTOSO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7659','ESCUELA ALERCE HISTORICO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7661','ESCUELA RURAL COLONIA METRENQUEN','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7662','ESCUELA RURAL SENDA SUR','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7663','ESCUELA RURAL LOS COLONOS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7664','ESCUELA CAYENEL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7665','ESCUELA RURAL LA CHAMIZA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7667','CENTRO DE EDUCACION DE ADULTOS JOSE BERNARDO SUAREZ','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7668','COLEGIO ISLA TENGLO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7669','ESCUELA RURAL ILQUE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7670','ESCUELA RURAL CARE - CHILE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7671','ESCUELA RURAL LAGUNITAS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7672','ESCUELA RURAL CHAICAS','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7673','ESCUELA RURAL LOS PIONEROS DE SALTO CHICO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7675','ESCUELA RURAL TRAPEN','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7676','ESCUELA RURAL CHINQUIHUE ALTO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7677','ESCUELA RURAL METRI','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7679','ESCUELA RURAL HUELMO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7680','ESCUELA RURAL COLONIA EL GATO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7681','ESCUELA RURAL RIO CHICO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7682','ESCUELA RURAL LA PALOMA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7684','ESCUELA RURAL TEPUAL','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7685','ESCUELA RURAL LA VARA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7686','ESCUELA RURAL MAILLEN-PUQUELDON','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7688','ESCUELA RURAL LAUCA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7689','ESCUELA RURAL PICHIQUILLAIPE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7690','ESCUELA RURAL RIO BLANCO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7691','ESCUELA RURAL ·PUNTILLA TENGLO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7693','ESCUELA RURAL PELLINES DEL SALTO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7694','ESCUELA RURAL ALTO BONITO','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7695','ESCUELA RURAL SALTO GRANDE','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7696','ESCUELA ANAHUAC','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7698','ESCUELA RURAL CALETA LA ARENA','Los Lagos','PUERTO MONTT','Corp. Municipal'),
('7699','COLEGIO SALESIANO PADRE JOSE FERNANDEZ PEREZ','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7700','COLEGIO SAN FRANCISCO JAVIER','Los Lagos','PUERTO MONTT','Part. Pagado'),
('7701','COLEGIO ARRIARAN BARROS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7704','COLEGIO EJERCITO DE SALVACIÓN','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7705','INSTITUTO POLITECNICO MARIA AUXILIADORA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7706','COLEGIO SAN MAXIMILIANO KOLBE DE PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7707','COLEGIO INMACULADA CONCEPCION','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7709','COLEGIO SAN JOSE PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7710','ESCUELA PARTICULAR N. 197 SAN IGNACIO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7712','COLEGIO SAN ANTONIO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7714','ESCUELA PARTICULAR N. 193 NUEVA PANITAO','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7717','INSTITUTO ALEMAN DE PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Pagado'),
('7718','THE AMERICAN SCHOOL','Los Lagos','PUERTO MONTT','Part. Pagado'),
('7719','ESCUELA ESPECIAL N.280 `C.T.I. LOS NOTROS`','Los Lagos','OSORNO','Part. Subvencionado'),
('7720','LICEO PEDRO AGUIRRE CERDA','Los Lagos','PUERTO VARAS','Servicio Local'),
('7722','COLEGIO ROSITA NOVARO DE NOVARO PUERTO VARAS','Los Lagos','PUERTO VARAS','Servicio Local'),
('7723','ESCUELA GRUPO ESCOLAR','Los Lagos','PUERTO VARAS','Servicio Local'),
('7724','CNB ARTISTICO','Los Lagos','PUERTO VARAS','Servicio Local'),
('7725','ESCUELA RURAL COLONIA RIO SUR','Los Lagos','PUERTO VARAS','Servicio Local'),
('7726','ESCUELA RURAL SANTA MARIA','Los Lagos','PUERTO VARAS','Servicio Local'),
('7727','ESCUELA RURAL TRES PUENTES','Los Lagos','PUERTO VARAS','Servicio Local'),
('7729','ESCUELA RURAL JOSE WERNER MEIXNER','Los Lagos','PUERTO VARAS','Servicio Local'),
('7730','ESCUELA RURAL REINALDO RADDATZ HARRICH','Los Lagos','PUERTO VARAS','Servicio Local'),
('7732','ESCUELA RURAL JANEQUEO','Los Lagos','PUERTO VARAS','Servicio Local'),
('7738','ESCUELA RURAL HARDY MINTE BARTSCH','Los Lagos','PUERTO VARAS','Servicio Local'),
('7740','ESCUELA RURAL EPSON DE ENSENADA','Los Lagos','PUERTO VARAS','Servicio Local'),
('7741','ESCUELA RURAL RICARDO ROTH SCHUTZ','Los Lagos','PUERTO VARAS','Servicio Local'),
('7742','COLEGIO GERMANIA DEL VERBO DIVINO','Los Lagos','PUERTO VARAS','Part. Pagado'),
('7743','COLEGIO  BICENTENARIO FELMER NIKLITSCHEK','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('7744','COLEGIO INMACULADA CONCEPCION PUERTO VARAS','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('7745','ESCUELA PARTICULAR N.199 LINEA CRUZADA','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('7749','COLEGIO PORTAL DEL SUR','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('7752','ESCUELA PARTICULAR N.206 MARIA DOLORES','Los Lagos','PUERTO VARAS','Part. Subvencionado'),
('7753','ESCUELA BASICA FRONTERIZA JUAN SOLER MANFREDINI','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7754','ESCUELA RURAL JOHN KENNEDY','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7755','ESCUELA RURAL SOBERANIA CAPITAN DE BANDADA (A) MATIAS GONZALEZ COFRE DE PASO EL LEON','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7756','ESCUELA RURAL CRISTO REY','Los Lagos','PUERTO VARAS','Servicio Local'),
('7757','ESCUELA RURAL SANTA AGUEDA','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7758','ESCUELA RURAL SAN ANTONIO','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7759','ESCUELA RURAL CLOTILDE ALMONACID OLAVARRIA','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7760','ESCUELA RURAL RIO PUELO','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7761','ESCUELA RURAL LAS CAMELIAS','Los Lagos','PUERTO VARAS','Servicio Local'),
('7762','ESCUELA RURAL ESTUARIO DE RELONCAVI','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7763','ESCUELA RURAL CAPITÀN DE BANDADA CARLOS RODRIGUEZ PARIS','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7765','ESCUELA RURAL LA PENINSULA','Los Lagos','PUERTO VARAS','Servicio Local'),
('7768','ESCUELA RURAL PASO EL BOLSON','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7769','ESCUELA RURAL LITORAL DE LLAGUEPE','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7770','ESCUELA RURAL SANTA TERESITA DE LOS ANDES','Los Lagos','COCHAMÓ','Corp. Municipal'),
('7772','LICEO POLITECNICO CALBUCO','Los Lagos','CALBUCO','Corp. Municipal'),
('7773','COLEGIO EULOGIO GOYCOLEA GARAY','Los Lagos','CALBUCO','Corp. Municipal'),
('7774','ESCUELA RURAL SAN RAFAEL','Los Lagos','CALBUCO','Corp. Municipal'),
('7775','ESCUELA RURAL PARGUA','Los Lagos','CALBUCO','Corp. Municipal'),
('7776','ESCUELA RURAL EL SEMBRADOR','Los Lagos','CALBUCO','Corp. Municipal'),
('7777','ESCUELA RURAL EL ROSARIO','Los Lagos','CALBUCO','Corp. Municipal'),
('7782','ESCUELA RURAL QUEULLIN','Los Lagos','CALBUCO','Corp. Municipal'),
('7783','ESCUELA RURAL CHAUQUEAR','Los Lagos','CALBUCO','Corp. Municipal'),
('7784','ESCUELA RURAL LOS PINIS','Los Lagos','CALBUCO','Corp. Municipal'),
('7785','ESCUELA RURAL QUETROLAUQUEN','Los Lagos','CALBUCO','Corp. Municipal'),
('7786','ESCUELA RURAL DAITAO','Los Lagos','CALBUCO','Corp. Municipal'),
('7787','ESCUELA RURAL QUENU','Los Lagos','CALBUCO','Corp. Municipal'),
('7788','ESCUELA RURAL CHAYAHUE','Los Lagos','CALBUCO','Corp. Municipal'),
('7789','ESCUELA RURAL ALONSO DE ERCILLA','Los Lagos','CALBUCO','Corp. Municipal'),
('7790','ESCUELA RURAL SOL DEL PACIFICO','Los Lagos','CALBUCO','Corp. Municipal'),
('7791','ESCUELA RURAL AGUANTAO','Los Lagos','CALBUCO','Corp. Municipal'),
('7794','ESCUELA RURAL EL FARO ILTO','Los Lagos','CALBUCO','Corp. Municipal'),
('7797','ESCUELA RURAL SAN RAMON','Los Lagos','CALBUCO','Corp. Municipal'),
('7798','ESCUELA RURAL EL DAO','Los Lagos','CALBUCO','Corp. Municipal'),
('7801','ESCUELA RURAL PUTENIO','Los Lagos','CALBUCO','Corp. Municipal'),
('7802','ESCUELA RURAL SAN JOSE','Los Lagos','CALBUCO','Corp. Municipal'),
('7804','ESCUELA RURAL LA POZA','Los Lagos','CALBUCO','Corp. Municipal'),
('7805','ESCUELA RURAL PEDRO BARRIENTOS BARRIENTOS','Los Lagos','CALBUCO','Corp. Municipal'),
('7806','ESCUELA RURAL EL ESTERO RULO','Los Lagos','CALBUCO','Corp. Municipal'),
('7808','ESCUELA RURAL LA CAMPANA','Los Lagos','CALBUCO','Corp. Municipal'),
('7809','ESCUELA RURAL ISLA CHIDHUAPI','Los Lagos','CALBUCO','Corp. Municipal'),
('7810','ESCUELA RURAL SAN ANTONIO','Los Lagos','CALBUCO','Corp. Municipal'),
('7811','ESCUELA RURAL LOS BAJOS DE MAYELHUE','Los Lagos','CALBUCO','Corp. Municipal'),
('7812','ESCUELA RURAL CARMEN MIRANDA NAVARRO','Los Lagos','CALBUCO','Corp. Municipal'),
('7815','ESCUELA RURAL HUAPI ABTAO','Los Lagos','CALBUCO','Corp. Municipal'),
('7816','ESCUELA RURAL SIETE COLINAS','Los Lagos','CALBUCO','Corp. Municipal'),
('7818','ESCUELA RURAL PEÑASMO','Los Lagos','CALBUCO','Corp. Municipal'),
('7819','ESCUELA RURAL EL AVELLANAL','Los Lagos','CALBUCO','Corp. Municipal'),
('7820','ESCUELA RURAL CHUCAGUA','Los Lagos','CALBUCO','Corp. Municipal'),
('7821','ESCUELA RURAL ISLA TABON','Los Lagos','CALBUCO','Corp. Municipal'),
('7822','ESCUELA RURAL MACHIL','Los Lagos','CALBUCO','Corp. Municipal'),
('7823','ESCUELA RURAL EL YALE','Los Lagos','CALBUCO','Corp. Municipal'),
('7824','ESCUELA RURAL HUAYUN BAJO','Los Lagos','CALBUCO','Corp. Municipal'),
('7825','ESCUELA LIBERTADOR GENERAL BERNARDO O´HIGGINS RIQUELME','Los Lagos','CALBUCO','Corp. Municipal'),
('7826','COLEGIO SAN MIGUEL','Los Lagos','CALBUCO','Part. Subvencionado'),
('7830','LICEO CAPITAN DE FRAGATA FRANCISCO VIDAL GORMAZ','Los Lagos','MAULLIN','Corp. Municipal'),
('7832','ESCUELA RURAL FRANCISCO CORTES OJEDA','Los Lagos','MAULLIN','Corp. Municipal'),
('7833','ESCUELA JOSE ABELARDO NUÑEZ','Los Lagos','MAULLIN','Corp. Municipal'),
('7834','ESCUELA ENCARNACION OLIVARES','Los Lagos','MAULLIN','Corp. Municipal'),
('7836','ESCUELA RURAL DORILA AGUILA AGUILAR','Los Lagos','MAULLIN','Corp. Municipal'),
('7837','ESCUELA RURAL PADRE NELSON AGUILAR ESPAÑA','Los Lagos','MAULLIN','Corp. Municipal'),
('7839','ESCUELA RURAL  TEOFISTO CARCAMO SERON','Los Lagos','MAULLIN','Corp. Municipal'),
('7847','ESCUELA RURAL CHUYAGUEN','Los Lagos','MAULLIN','Corp. Municipal'),
('7850','ESCUELA RURAL LOS ARCES','Los Lagos','MAULLIN','Corp. Municipal'),
('7852','ESCUELA RURAL JUANITA FERNANDEZ','Los Lagos','MAULLIN','Corp. Municipal'),
('7854','ESCUELA RURAL JUANITA GALLARDO','Los Lagos','MAULLIN','Corp. Municipal'),
('7855','ESCUELA RURAL PUELPUN','Los Lagos','MAULLIN','Corp. Municipal'),
('7856','ESCUELA RURAL ASTILLEROS','Los Lagos','MAULLIN','Corp. Municipal'),
('7858','ESCUELA RURAL FRANCISCO HERNANDEZ NAVARRO','Los Lagos','MAULLIN','Corp. Municipal'),
('7860','ESCUELA RURAL MARIO ENRIQUE GUZMAN ACEVEDO','Los Lagos','MAULLIN','Corp. Municipal'),
('7861','ESCUELA RURAL EL JARDIN DE OLMOPULLI','Los Lagos','MAULLIN','Corp. Municipal'),
('7864','ESCUELA RURAL SAN JORGE','Los Lagos','MAULLIN','Corp. Municipal'),
('7866','ESCUELA RURAL HILDA HUNQUEN','Los Lagos','MAULLIN','Corp. Municipal'),
('7868','ESCUELA RURAL LOS PINOS DEL EMPALME','Los Lagos','MAULLIN','Corp. Municipal'),
('7871','ESCUELA PARTICULAR N.211 LAS ENCINAS','Los Lagos','MAULLIN','Part. Subvencionado'),
('7872','COLEGIO BICENTENARIO DE DIFUSION ARTISTICA LOS ULMOS','Los Lagos','LOS MUERMOS','Servicio Local'),
('7874','ESCUELA RURAL CAÑITAS','Los Lagos','LOS MUERMOS','Servicio Local'),
('7878','ESCUELA RURAL PALIHUE','Los Lagos','LOS MUERMOS','Servicio Local'),
('7879','ESCUELA RURAL QUILLAGUA','Los Lagos','LOS MUERMOS','Servicio Local'),
('7881','ESCUELA RURAL HUAUTRUNES','Los Lagos','LOS MUERMOS','Servicio Local'),
('7887','ESCUELA RURAL CARACOL','Los Lagos','LOS MUERMOS','Servicio Local'),
('7896','ESCUELA RURAL ESTAQUILLA','Los Lagos','LOS MUERMOS','Servicio Local'),
('7897','ESCUELA RURAL MANUEL GATICA ARRIAGADA','Los Lagos','LOS MUERMOS','Servicio Local'),
('7898','ESCUELA RURAL EL MELI','Los Lagos','LOS MUERMOS','Servicio Local'),
('7905','ESCUELA RURAL PARAGUAY CHICO','Los Lagos','LOS MUERMOS','Servicio Local'),
('7907','COLEGIO RAMON ANGEL JARA','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7908','ESCUELA PARTICULAR N.216 MIRAMAR','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7910','ESCUELA PARTICULAR N.212 LA ESPERANZA','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7911','ESCUELA PARTICULAR N.213 EL LAUREL','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7915','ESCUELA PARTICULAR N.217 MIRAMAR BAJO','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7918','ESCUELA PARTICULAR N.220 FUNDO LA PALOMA','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7919','ESCUELA PARTICULAR N.221 ESTAQUILLA BAJO','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7922','ESCUELA PARTICULAR N.232 EL PROGRESO','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('7924','ESCUELA RURAL SAN ANDRES','Los Lagos','FRESIA','Servicio Local'),
('7927','ESCUELA RURAL CAU-CAU','Los Lagos','FRESIA','Servicio Local'),
('7929','ESCUELA BASICA AGRICOLA HUEMPELEO','Los Lagos','FRESIA','Servicio Local'),
('7930','ESCUELA RURAL LUCILA GODOY ALCAYAGA','Los Lagos','FRESIA','Servicio Local'),
('7931','ESCUELA RURAL PATO LLICO','Los Lagos','FRESIA','Servicio Local'),
('7933','ESCUELA RURAL OLGA SOTO ALVARADO','Los Lagos','FRESIA','Servicio Local'),
('7936','ESCUELA RURAL RINCONADA','Los Lagos','FRESIA','Servicio Local'),
('7938','ESCUELA RURAL ENTRE RIOS','Los Lagos','FRESIA','Servicio Local'),
('7939','ESCUELA RURAL LINEA SIN NOMBRE','Los Lagos','FRESIA','Servicio Local'),
('7940','ESCUELA RURAL PARGA','Los Lagos','FRESIA','Servicio Local'),
('7941','LICEO CARLOS IBAÑEZ DEL CAMPO','Los Lagos','FRESIA','Servicio Local'),
('7942','COLEGIO PURISIMO CORAZON DE MARIA','Los Lagos','FRESIA','Part. Subvencionado'),
('7944','ESCUELA RURAL SANTA MONICA','Los Lagos','FRESIA','Servicio Local'),
('7945','ESCUELA RURAL EL PEUCHEN','Los Lagos','FRESIA','Servicio Local'),
('7946','ESCUELA PARTICULAR N. 224 PICHI MAULE','Los Lagos','FRESIA','Part. Subvencionado'),
('7947','ESCUELA PARTICULAR N. 225 LA ARAÑA','Los Lagos','FRESIA','Part. Subvencionado'),
('7950','ESCUELA PARTICULAR N. 228 EL PATO DE LLICO','Los Lagos','FRESIA','Part. Subvencionado'),
('7952','ESCUELA PARTICULAR N. 230 LA ESPERANZA','Los Lagos','FRESIA','Part. Subvencionado'),
('7953','ESCUELA PARTICULAR N. 231 SAN ANTONIO','Los Lagos','FRESIA','Part. Subvencionado'),
('7956','LICEO BICENTENARIO POLITECNICO HOLANDA','Los Lagos','LLANQUIHUE','Servicio Local'),
('7958','ESCUELA INES GALLARDO ALVARADO','Los Lagos','LLANQUIHUE','Servicio Local'),
('7959','ESCUELA BASICA GABRIELA MISTRAL','Los Lagos','LLANQUIHUE','Servicio Local'),
('7961','ESCUELA RURAL LOS PELLINES','Los Lagos','LLANQUIHUE','Servicio Local'),
('7962','ESCUELA RURAL LONCOTORO','Los Lagos','LLANQUIHUE','Servicio Local'),
('7966','ESCUELA RURAL LINEA SOLAR','Los Lagos','LLANQUIHUE','Servicio Local'),
('7967','ESCUELA RURAL COLEGUAL','Los Lagos','LLANQUIHUE','Servicio Local'),
('7968','ESCUELA RURAL COLIGUAL SAN JUAN','Los Lagos','LLANQUIHUE','Servicio Local'),
('7970','ESCUELA PARTICULAR N.239 LOS VOLCANES','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('7973','LICEO INDUSTRIAL CHILENO-ALEMAN','Los Lagos','FRUTILLAR','Servicio Local'),
('7975','ESCUELA ARTURO ALESSANDRI PALMA','Los Lagos','FRUTILLAR','Servicio Local'),
('7976','ESCUELA BERNARDO PHILIPPI','Los Lagos','FRUTILLAR','Servicio Local'),
('7977','ESCUELA RURAL LOS LINARES DE CASMA','Los Lagos','FRUTILLAR','Servicio Local'),
('7978','ESCUELA RURAL MARIO PEREZ NAVARRO','Los Lagos','FRUTILLAR','Servicio Local'),
('7982','ESCUELA RURAL PARAGUAY','Los Lagos','FRUTILLAR','Servicio Local'),
('7987','ESCUELA CARLOS SPRINGER NIKLITSCHEK','Los Lagos','FRUTILLAR','Servicio Local'),
('7989','COLEGIO PARTICULAR N. 244 `MADRE DE DIOS`','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('7990','ESCUELA RURAL COLONIA SAN MARTIN','Los Lagos','FRUTILLAR','Servicio Local'),
('7992','COLEGIO ICEBERG','Los Lagos','CALBUCO','Part. Subvencionado'),
('7993','ESCUELA PARTICULAR N. 240 LA HUACHA','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('7994','ESCUELA PARTICULAR N.241 LA PAZ','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('7998','ESCUELA PARTICULAR N.247 EL RETAMO','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('8000','INSTITUTO ALEMAN DE FRUTILLAR','Los Lagos','FRUTILLAR','Part. Pagado'),
('8001','LICEO POLITECNICO DE CASTRO','Los Lagos','CASTRO','Servicio Local'),
('8002','LICEO GALVARINO RIVEROS CARDENAS','Los Lagos','CASTRO','Servicio Local'),
('8003','ESCUELA LUIS URIBE DIAZ','Los Lagos','CASTRO','Servicio Local'),
('8004','ESCUELA INES MUNOZ DE GARCIA','Los Lagos','CASTRO','Servicio Local'),
('8005','LICEO AYTUE','Los Lagos','CASTRO','Servicio Local'),
('8006','ESCUELA RURAL PEDRO VELAZQUEZ BONTES','Los Lagos','CASTRO','Servicio Local'),
('8010','ESCUELA RURAL CURAHUE','Los Lagos','CASTRO','Servicio Local'),
('8012','ESCUELA RURAL ANA NELLY OYARZUN CARTES','Los Lagos','CASTRO','Servicio Local'),
('8013','ESCUELA RURAL MIRTA OYARZO VERA','Los Lagos','CASTRO','Servicio Local'),
('8014','ESCUELA RURAL MANUELA CARDENAS BARRIA','Los Lagos','CASTRO','Servicio Local'),
('8016','ESCUELA RURAL COIHUINCO','Los Lagos','CASTRO','Servicio Local'),
('8019','ESCUELA RURAL QUILQUICO','Los Lagos','CASTRO','Servicio Local'),
('8020','ESCUELA RURAL PAUL HARRIS','Los Lagos','CASTRO','Servicio Local'),
('8022','ESCUELA RURAL ERMELINDA SANCHEZ DE CIFUENTES','Los Lagos','CASTRO','Servicio Local'),
('8023','ESCUELA DE ADULTOS DE CASTRO','Los Lagos','CASTRO','Servicio Local'),
('8027','ESCUELA RURAL OLINDA BORQUEZ BORQUEZ','Los Lagos','CASTRO','Servicio Local'),
('8029','ESCUELA RURAL LLICALDAD','Los Lagos','CASTRO','Servicio Local'),
('8031','ESCUELA RURAL LA CHACRA','Los Lagos','CASTRO','Servicio Local'),
('8032','ESCUELA RURAL INES BAZAN','Los Lagos','CASTRO','Servicio Local'),
('8033','ESCUELA RURAL LA ESTANCIA','Los Lagos','CASTRO','Servicio Local'),
('8035','ESCUELA RURAL PIDPID','Los Lagos','CASTRO','Servicio Local'),
('8036','ESCUELA RURAL LOS ANGELES','Los Lagos','CASTRO','Servicio Local'),
('8037','ESCUELA RURAL LOS ROBLES','Los Lagos','CASTRO','Servicio Local'),
('8038','ESCUELA RURAL SAN MIGUEL','Los Lagos','CASTRO','Servicio Local'),
('8041','ESCUELA DIFERENCIAL `ANTU- KAU`','Los Lagos','CASTRO','Servicio Local'),
('8044','LICEO POLIVALENTE DE ANCUD','Los Lagos','ANCUD','Servicio Local'),
('8046','ESCUELA PUDETO','Los Lagos','ANCUD','Servicio Local'),
('8047','ESCUELA ANEXA','Los Lagos','ANCUD','Servicio Local'),
('8048','ESCUELA YERBAS BUENAS','Los Lagos','ANCUD','Servicio Local'),
('8049','ESCUELA RURAL VILLA CHACAO','Los Lagos','ANCUD','Servicio Local'),
('8051','ESCUELA RURAL EL PALOMAR','Los Lagos','ANCUD','Servicio Local'),
('8052','ESCUELA RURAL GUAPILACUY','Los Lagos','ANCUD','Servicio Local'),
('8053','ESCUELA RURAL SENDA CHACAO','Los Lagos','ANCUD','Servicio Local'),
('8054','ESCUELA RURAL MANAO','Los Lagos','ANCUD','Servicio Local'),
('8061','ESCUELA RURAL PUNTA CHILEN','Los Lagos','ANCUD','Servicio Local')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
