-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 28 de 31 | filas 10801-11200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('31038','ESCUELA ESPECIAL DE  LENGUAJE TEMPUS','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31039','COLEGIO DE ADULTOS ALTAZOL DE SANTIAGO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('31040','COLEGIO SAN FERNANDO DE BUIN','Metropolitana','BUIN','Part. Pagado'),
('31041','ESCUELA DE LENGUAJE LA DAVILITA','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('31042','COLEGIO SAN ANDRES DE CALERA DE TANGO','Metropolitana','CALERA DE TANGO','Part. Pagado'),
('31043','ESCUELA ESPECIAL EL PORVENIR','Metropolitana','LAMPA','Part. Subvencionado'),
('31046','ESCUELA ESPECIAL ANTILLANCA','Metropolitana','QUILICURA','Part. Subvencionado'),
('31047','CENTRO EDUCACIONAL LIFE SUPPORT','Metropolitana','LAS CONDES','Part. Pagado'),
('31048','COMPLEJO EDUC. ADULTOS CALETA SUR','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('31049','ESCUELA ESPECIAL DE LENGUAJE NIDO DE LUZ','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31051','ESCUELA ESPECIAL SAN LUIS DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('31052','COLEGIO VILLA EL SOL','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('31053','ESCUELA ESPECIAL PALABRAS MAGICAS','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('31054','COLEGIO EL LABRADOR','Metropolitana','BUIN','Part. Subvencionado'),
('31056','ESCUELA ESPECIAL SANTA ANA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('31060','ESCUELA  DE  PARVULOS CORAZON DE LEON','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31061','ESCUELA DE PARVULOS SAN JOSE SCHOOL','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31063','ESCUELA ESPECIAL PIECECITOS DE NIÑOS','Metropolitana','PIRQUE','Part. Subvencionado'),
('31064','COLEGIO ALBORADA DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('31065','LICEO TECNOLOGICO BICENTENARIO ENRIQUE KIRBERG BALTIANSKY','Metropolitana','MAIPÚ','Servicio Local'),
('31066','COLEGIO LOS ROBLES DE LOS LIBERTADORES','Metropolitana','EL MONTE','Part. Subvencionado'),
('31068','COLEGIO TERRA MONTE','Metropolitana','COLINA','Part. Subvencionado'),
('31069','ESCUELA ESPECIAL NUEVA AURORA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31070','ESC. DE  PARVULOS MAGIC -GARDEN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31071','LICEO BICENT. PROV.STA. TERESA DE LOS ANDES','Metropolitana','COLINA','Municipal'),
('31072','ESCUELA ESPECIAL EL RINCON DE JOSEFINA','Metropolitana','RENCA','Part. Subvencionado'),
('31073','ESCUELA DE PARVULOS Y ESPECIAL MANITOS CREATI','Metropolitana','CERRILLOS','Part. Subvencionado'),
('31074','LICEO BICENTENARIO DE NIÑAS DE MAIPU','Metropolitana','MAIPÚ','Servicio Local'),
('31075','ESCUELA DE LENGUAJE ECOLOGICA ANDALEN','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('31077','ESCUELA ESPECIAL PANDY','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31078','LICEO BICENTENARIO SAN PEDRO DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Municipal'),
('31080','COLEGIO RENACER TP','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31081','ESCUELA  SAN  IGNACIO  DE  BUIN','Metropolitana','BUIN','Part. Subvencionado'),
('31082','ESC. DE LENGUAJE PEWUNGUEN, TIEMPOS DE BROTES','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('31083','LICEO PAULA JARAQUEMADA DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('31084','COLEGIO ANTAMARO','Ñuble','CHILLÁN','Part. Subvencionado'),
('31085','COLEGIO EL ARRAYAN','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('31086','ESCUELA ESPECIAL DE LENGUAJE SANTA MARÍA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31087','COLEGIO ALCÁZARES DE ÑUBLE','Ñuble','CHILLÁN','Part. Subvencionado'),
('31088','ESCUELA ESPECIAL LENGUAJE PALABRAS MÁGICAS','Biobío','CORONEL','Part. Subvencionado'),
('31089','ESCUELA ESPECIAL RAYITO DE SOL','Biobío','MULCHÉN','Part. Subvencionado'),
('31090','COMPLEJO EDUCACIONAL VALLE DEL ITATA','Ñuble','RANQUIL','Part. Subvencionado'),
('31091','ESCUELA ESPECIAL INFANTIL SAN ANDRES','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('31092','ESCUELA ESPECIAL CENTRO DE CAPACITACIÓN E INTEGRACIÓN LABORAL KRIES','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('31094','ESCUELA ESPECIAL DE LENGUAJE TESÓN MINERO','Biobío','LOTA','Part. Subvencionado'),
('31097','ESCUELA ESPECIAL DE LENGUAJE MUNICIPAL EL CARMEN','Ñuble','EL CARMEN','Corp. Municipal'),
('31098','COLEGIO PARTICULAR PEMUCO','Ñuble','PEMUCO','Part. Subvencionado'),
('31099','ESCUELA ESPECIAL DE LENGUAJE RUCALAF','Biobío','ARAUCO','Part. Subvencionado'),
('31100','ESCUELA ESPECIAL DIFERENCIAL NIDAL','Biobío','TALCAHUANO','Part. Subvencionado'),
('31102','CENTRO EDUCACIONAL RUCAPEÑIHUE','Biobío','CONCEPCIÓN','Part. Pagado'),
('31103','LICEO BICENTENARIO DE CORONEL','Biobío','CORONEL','Servicio Local'),
('31104','LICEO TÉCNICO PROFESIONAL DE ADULTOS BIOBÍO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('31105','ESCUELA ESPECIAL DE LENGUAJE ANIDAPALABRAS','Ñuble','CHILLÁN','Part. Subvencionado'),
('31106','COLEGIO SAINT JOAN COLLEGE','Biobío','SANTA JUANA','Part. Subvencionado'),
('31107','COLEGIO ESPERANZA','Biobío','CABRERO','Part. Subvencionado'),
('31108','ESCUELA ESPECIAL DE LENGUAJE Y COLEGIO BÁSICO CUMBRES DEL VALLE COLLEGE','Ñuble','QUILLÓN','Part. Subvencionado'),
('31110','COLEGIO FRATERNIDAD','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('31111','ESCUELA ESPECIAL DE LENGUAJE TIERRA DE NIÑOS','Biobío','TOMÉ','Part. Subvencionado'),
('31114','ESCUELA DE ESPECIAL LENGUAJE ALIWENKO','Biobío','CORONEL','Part. Subvencionado'),
('31115','ESCUELA ESPECIAL DE LENGUAJE SONRISAS','Biobío','ARAUCO','Part. Subvencionado'),
('31116','COLEGIO BICENTENARIO ENRIQUE SALINAS BUSCOVICH','Ñuble','CHILLÁN','Part. Subvencionado'),
('31117','ESCUELA ESPECIAL DE LENGUAJE CUMBRES DE COBQUECURA','Ñuble','COBQUECURA','Part. Subvencionado'),
('31118','ESCUELA ESPECIAL DE LENGUAJE EXPLORADORES DEL SABER','Biobío','CORONEL','Part. Subvencionado'),
('31120','ESCUELA ESPECIAL DE LENGUAJE YUPANQUI','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('31121','COLEGIO DOCTOR OSVALDO QUINTEROS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31122','ESCUELA ESPECIAL DE LENGUAJE GOLDEN HOUSE','Biobío','CURANILAHUE','Part. Subvencionado'),
('31123','ESCUELA ESPECIAL DE LENGUAJE EXPRESIONES','Ñuble','CHILLÁN','Part. Subvencionado'),
('31124','COLEGIO PROACAP','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31125','ESCUELA ESPECIAL DE LENGUAJE ALIHUEN','Biobío','LOS ÁLAMOS','Part. Subvencionado'),
('31128','LICEO BICENTENARIO DE EXCELENCIA TREHUACO','Ñuble','TREHUACO','Corp. Municipal'),
('31129','ESCUELA ESPECIAL DE LENGUAJE SANTA DOMINGA','Biobío','CORONEL','Part. Subvencionado'),
('31130','COLEGIO PARTICULAR SUBVENCIONADO TIMONEL-CORONEL','Biobío','CORONEL','Part. Subvencionado'),
('31131','JARDIN INFANTIL CAMPANITA','Biobío','CABRERO','Part. Subvencionado'),
('31132','ESCUELA NUEVO FUTURO','Biobío','LOTA','Part. Subvencionado'),
('31133','ESCUELA ESPECIAL DIFERENCIAL CTRO.EDUC.DE DESARROLLO Y ESTIM ESP. PEQUEÑO NAZARENO','Ñuble','CHILLÁN','Part. Subvencionado'),
('31134','JARDIN INFANTIL SAN BENITO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31135','ESCUELA ESPECIAL DE LENGUAJE ELUNEY','Ñuble','BULNES','Part. Subvencionado'),
('31136','ESCUELA ESPECIAL DE LENGUAJE MUNDO PALABRITAS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31137','ESCUELA ESPECIAL DE LENGUAJE LETRITAS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('31138','ESCUELA DE LENGUAJE PEQUEÑO ROBLE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31140','ESCUELA ESPECIAL DIFERENCIAL NUEVO AMANECER','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('31141','ESCUELA ESPECIAL DE LENGUAJE RENACER 1','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31142','ESCUELA ESPECIAL MARIA GABRIELA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31144','ESCUELA DE LENGUAJE MARIPOSITAS','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31145','ESCUELA ESPECIAL DE LENGUAJE MUNDO RAVALEN','Metropolitana','TALAGANTE','Part. Subvencionado'),
('31148','ESC. ESP. DE LENGUAJE OMILEN ANTU','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('31149','ESCUELA ESPECIAL DE LENGUAJE KAORY','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('31152','ESCUELA ESPECIAL LAS PEPAS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31153','INSTITUTO CUMBRES DE CONDORES PONIENTE','Metropolitana','RENCA','Municipal'),
('31154','ESCUELA CAMINA ALTO','Metropolitana','COLINA','Municipal'),
('31155','ESCUELA  ESPECIAL  MANUEL RODRIGUEZ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31158','ESC. DE PARVULOS Y ESPECIAL','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('31159','ESCUELA DE LENGUAJE CANTILLANA Nº181','Metropolitana','TALAGANTE','Part. Subvencionado'),
('31161','COLEGIO LOS PENSAMIENTOS','Metropolitana','LA GRANJA','Part. Subvencionado'),
('31162','C.E.I.A. PROFESOR HECTOR DUARTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('31163','COLEGIO DE ADULTOS SAN ANDRES DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('31164','ESC.ESP.DE  LENGUAJE  MIS  PEQUEÑOS TESOROS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31165','ESCUELA ESPECIAL HUEPIL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('31166','ESC. ESP. DE LENGUAJE CAMINO DE VIDA','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('31167','CENTRO EDUCACIONAL INTEGRAL DE ADULT ACUARIO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('31168','ESCUELA ESPECIAL CUNCUNITAS DE AMOR','Metropolitana','SAN JOSÉ DE MAIPO','Part. Subvencionado'),
('31169','ESC. ESP. LENG. Y COMUNICACION SAN SEBASTIAN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31170','ESCUELA ESPECIAL  SANTA  LUISA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('31171','ESCUELA DE PARVULOS Y ESPECIAL EUSEBIO LILLO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31172','ESC. ESPECIAL DE LENGUAJE NOVA  AURORA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31173','ESC. ESPECIAL DE LENGUAJE KUMELEN','Metropolitana','QUILICURA','Part. Subvencionado'),
('31175','BICENTENARIO COLLEGE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31176','ESCUELA ESPECIAL PIONERITOS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('31177','ESCUELA DE PARVULOS LOS DUENDECITOS II','Metropolitana','LA GRANJA','Part. Subvencionado'),
('31178','ESCUELA ESP. DE LENGUAJE  SAN BENITO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31179','ESCUELA ESPECIAL MANZANITA 1','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31180','ESC.DE  PARVULOS  NUEVO  AMANECER','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31181','ESCUELA ESPECIAL CENTRO EDUCACIONAL PUKARA','Metropolitana','COLINA','Part. Subvencionado'),
('31182','ESCUELA ESPECIAL DE LENGUAJE EL CANELO','Metropolitana','BUIN','Part. Subvencionado'),
('31183','ESCUELA DE PARVULOS MUNDO MAGICO','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('31185','ESCUELA  DE  PARVULOS  CEMAR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31187','COLEGIO DE ADULTOS ALTOS DEL HUERTO','Metropolitana','TILTIL','Part. Subvencionado'),
('31189','COLEGIO HOSPITALARIO HOSPITAL MILITAR','Metropolitana','LA REINA','Part. Subvencionado'),
('31190','ESCUELA CUMBRES  DE  NOS','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31192','COLEGIO ADULTOS MANQUEHUE','Metropolitana','LAMPA','Part. Subvencionado'),
('31193','ESCUELA BASICA CRISTIANO JERUSALEN','Metropolitana','LAMPA','Part. Subvencionado'),
('31194','COLEGIO MONTEVERDI','Coquimbo','LA SERENA','Part. Subvencionado'),
('31196','ESCUELA ESPECIAL MUNDO NUEVO','Coquimbo','SALAMANCA','Part. Subvencionado'),
('31197','JARDIN INFANTIL INTI','Coquimbo','LA SERENA','Part. Pagado'),
('31199','COLEGIO DE EDUCACION ESPECIAL ALCALA','Coquimbo','LA SERENA','Part. Subvencionado'),
('31200','ESCUELA DE LENGUAJE MI SOLCITO','Coquimbo','LA SERENA','Part. Subvencionado'),
('31201','SAINT MARY SCHOOL - EL MILAGRO','Coquimbo','LA SERENA','Part. Pagado'),
('31202','ESCUELA DE LENGUAJE SAN ANDRES','Coquimbo','LA SERENA','Part. Subvencionado'),
('31203','COLEGIO DOMINGO SANTA MARIA','Coquimbo','VICUÑA','Part. Subvencionado'),
('31206','ESCUELA ESPECIAL DE LENGUAJE SEMBRANDO PALABR','Coquimbo','LA SERENA','Part. Subvencionado'),
('31209','ESCUELA ESPECIAL DE LENGUAJE HAMELIN','Coquimbo','COQUIMBO','Part. Subvencionado'),
('31211','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑA ORUGA','Coquimbo','LA SERENA','Part. Subvencionado'),
('31212','ESCUELA ESPECIAL DE LENGUAJE AMARANTA','Coquimbo','LA SERENA','Part. Subvencionado'),
('31214','ESCUELA ESP DE LENGUAJE LA FABRICA DE SUEÑOS','Coquimbo','LA SERENA','Part. Subvencionado'),
('31215','ESC.ESP.DE TRAS ESPEC. DE LENGUAJE WENUI','Coquimbo','COQUIMBO','Part. Subvencionado'),
('31216','ESCUELA ESPECIAL Y DEL LENGUAJE ANTARES','Coquimbo','LA SERENA','Part. Subvencionado'),
('31217','ESCUELA ESPECIAL DE LENGUAJE SUEÑO DORADO','Coquimbo','LA SERENA','Part. Subvencionado'),
('31218','ESCUELA CULTURAL DE LENGUAJE Y JARDÍN INFANTIL VALDANI','Coquimbo','COQUIMBO','Part. Subvencionado'),
('31219','COLEGIO VERSALLES','Coquimbo','LA SERENA','Part. Subvencionado'),
('31220','COLEGIO DE ADULTOS VALLE DE ELQUI','Coquimbo','VICUÑA','Part. Subvencionado'),
('31221','COLEGIO RUKALAF','Coquimbo','LA SERENA','Part. Subvencionado'),
('31222','MARTIN LUTHER KING ADULT SCHOOL','Coquimbo','LA SERENA','Part. Subvencionado'),
('31223','ESCUELA ESPECIAL DE LENGUAJE EL CASTILLO DEL SABER','Coquimbo','LA SERENA','Part. Subvencionado'),
('31235','JARDIN INFANTIL PEUMAYEN SAN FERNANDO','O''Higgins','SAN FERNANDO','Part. Pagado'),
('31249','ESCUELA ESPECIAL DE LENG CON AGUA DEL CIELO','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('31250','ESCUELA  ESPECIAL DE  LENGUAJE  VICUÑA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('31251','ESCUELA ESP. DE LENGUAJE LOS TRES REYES MAGOS','Metropolitana','QUILICURA','Part. Subvencionado'),
('31252','COLEGIO ROCKET ADULTOS DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31253','COLEGIO ALTO DEL MAIPO','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('31254','ESCUELA ESPECIAL Nº 2385 VALLE HERMOSO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('31256','ESCUELA  ESPECIAL  DAMASQUITO','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31257','ESCUELA ESP. Y PARV. EXPLORADORES DEL MUNDO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31258','COLEGIO WALDORF DE SANTIAGO','Metropolitana','ÑUÑOA','Part. Pagado'),
('31259','ESC. DE LENGUAJE Nº 2388 ARCOIRIS DE PALABRAS','Metropolitana','MACUL','Part. Subvencionado'),
('31260','COLEGIO ALTAZOL DEL MAIPO','Metropolitana','PAINE','Part. Subvencionado'),
('31261','ESCUELA ESPECIAL EL AGUILA Y EL ROBLE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31262','ESCUELA PART. SANTA MARIA DE GUADALUPE','Metropolitana','COLINA','Part. Subvencionado'),
('31263','ALBORADA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31264','ESCUELA BÁSICA SAN GENNARO','Metropolitana','PAINE','Part. Subvencionado'),
('31265','ESCUELA BASICA N°2392 JOHN JOHN HIGH SCHOOL','Metropolitana','ÑUÑOA','Part. Pagado'),
('31266','INSTITUTO PROFESOR HECTOR DUARTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('31267','INSTITUTO SAN ALBERTO HURTADO','Metropolitana','BUIN','Part. Pagado'),
('31270','ESCUELA ESPECIAL KAYROS KIDS','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('31271','COLEGIO HIGHLANDS MONTESSORI SCHOOL OF SANTIAGO','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('31273','COLEGIO REAL','Metropolitana','LA REINA','Part. Pagado'),
('31274','COLEGIO SANTA SOFIA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('31275','LA NONI ESCUELA DE PARVULOS Y LENGUAJE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('31276','COLEGIO GRACE COLLEGE','Metropolitana','HUECHURABA','Part. Pagado'),
('31277','ESC. ESP. DE LENGUAJE SAN  EXPEDITO','Metropolitana','LO PRADO','Part. Subvencionado'),
('31278','INSTITUTO COMERCIAL BARROS ARANA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31279','COLEGIO DE ADULTOS  ALBA DE ORO','Metropolitana','MELIPILLA','Part. Subvencionado'),
('31280','ESCUELA ESPECIAL ALIANZA MISIONERA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('31281','COLEGIO ESPECIAL HOSPITALARIO DE CARABINEROS','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('31282','COLEGIO NOVA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31283','ESCUELA LENG. Y PARVULOS  HORMIGUITA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('31285','ESCUELA ESPECIAL N°2395 MI FAMILIA EDUCA','Metropolitana','QUILICURA','Part. Subvencionado'),
('31287','ESCUELA DEL CARIÑO RICARDO NAVIA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31289','ESCUELA ESPECIAL DE LENGUAJE SOL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31290','COLEGIO SAN ANDRES MAIPU EL BOSQUE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31291','ESCUELA DE LENGUAJE  NUESTRO  HORIZONTE','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('31292','ESCUELA ESPECIAL EL RIEL 2','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('31293','LICEO NACIONAL BICENTENARIO DE EXCELENCIA','Metropolitana','SAN BERNARDO','Servicio Local'),
('31294','LICEO BICENTENARIO MARIA SOLEDAD MELENDEZ MOLINA','Metropolitana','TALAGANTE','Municipal'),
('31295','LICEO BICENTENARIO ITALIA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('31297','ESCUELA DE LENGUAJE N°2399 GRANDES SUEÑOS','Metropolitana','LAMPA','Part. Subvencionado'),
('31299','LICEO BICENTENARIO DE EXCELENCIA FRANCISCO BILBAO BARQUIN DE QUILICURA','Metropolitana','QUILICURA','Servicio Local'),
('31300','ESCUELA BÁSICA N°186 MANCHESTER COLLEGE','Metropolitana','TILTIL','Part. Subvencionado'),
('31302','COLEGIO LOS PINOS','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31303','ESCUELA ESPECIAL DE LENGUAJE AMANK`AY','Arica y Parinacota','ARICA','Part. Subvencionado'),
('31304','ESCUELA ESPECIAL DE LENGUAJE RELMU','Arica y Parinacota','ARICA','Part. Subvencionado'),
('31306','COLEGIO FINÉS RELMU','Arica y Parinacota','ARICA','Part. Subvencionado'),
('31308','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS ESTRATEGAS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('31317','JARDIN INFANTIL WENTEMIL MONTESSORI','O''Higgins','MACHALÍ','Part. Pagado'),
('31318','JARDIN INFANTIL QUERUBINES','O''Higgins','MACHALÍ','Part. Subvencionado'),
('31326','ESCUELA ESPECIAL ATRAVIA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31327','COLEGIO ALICANTE DEL VALLE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31328','JARDIN INFANTIL FRUTILLITA FELIZ','Metropolitana','LA FLORIDA','Part. Pagado'),
('31329','ESCUELA DE  LENGUAJE HELLO CHILDREN','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('31330','ESCUELA DE LENGUAJE CHILE','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('31331','ESCUELA ESPECIAL DIFERENCIAL SAGRADO CORAZON','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31332','COLEGIO CORAZONES DE JESUS','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('31334','ESCUELA DE LENGUAJE HABLANDO SIN PARAR','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('31335','ESCUELA ESPECIAL JAVIERA CARRERA','Metropolitana','TALAGANTE','Part. Subvencionado'),
('31337','ESCUELA  BASICA  ALTAS  CUMBRES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31338','AULA HOSPITALARIA SAN ANTONIO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('31339','AULA HOSPITALARIA SAN CARLOS','Antofagasta','CALAMA','Part. Subvencionado'),
('31340','NETLAND SCHOOL','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('31341','ESCUELA ESPECIAL DE LENGUAJE SAN ANTONIO','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('31342','COLEGIO SAN LUCAS EVANGELISTA DE ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('31343','LICEO CIENTIFICO HUMANISTA LA CHIMBA','Antofagasta','ANTOFAGASTA','Municipal'),
('31344','SAN MARTIN DE PORRES','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('31345','LICEO POLITÉCNICO LOS ARENALES','Antofagasta','ANTOFAGASTA','Municipal'),
('31346','INSTITUTO ANTONIO VARAS','Antofagasta','CALAMA','Part. Pagado'),
('31347','ESCUELA DE PARVULOS NORTH KINDERGARTEN','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('31350','ESCUELA ESPECIAL DE LENGUAJE EL CERESITO','Biobío','MULCHÉN','Part. Subvencionado'),
('31360','ESCUELA ESPECIAL N°189 `SAN VICENTE`','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31361','ESCUELA ESPECIAL MAGIC SCHOOL','Metropolitana','MACUL','Part. Subvencionado'),
('31362','ESCUELA ESPECIAL TERRA BAMBINI','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('31363','ESCUELA ESPECIAL ALTA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31364','ESCUELA DE LENGUAJE SANTA TERESA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('31365','ESCUELA ESPECIAL MIS PRIMEROS PASITOS E.I.R.L','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('31366','ESCUELA ESPECIAL N° 2410 GRANJERITOS','Metropolitana','LA GRANJA','Part. Subvencionado'),
('31368','CENTRO EDUCACIONAL DE ADULTOS DREYSE','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('31369','ESCUELA ESPECIAL N° 190 - SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31371','ESCUELA ESPECIAL MI CLUB RYMAI','Metropolitana','LA GRANJA','Part. Subvencionado'),
('31373','COLEGIO SAINT JOSEPH SCHOOL','Metropolitana','HUECHURABA','Part. Pagado'),
('31374','ESCUELA  ESPECIAL  MELODIAS  MAGICAS','Metropolitana','TALAGANTE','Part. Subvencionado'),
('31375','CENTRO DE ESTUDIOS FRANCISCO BILBAO DE CURACA','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('31376','LICEO  DE  ADULTOS  INSIEME','Metropolitana','SANTIAGO','Part. Subvencionado'),
('31378','ESCUELA BÁSICA PALMARES ORIENTE','Metropolitana','QUILICURA','Part. Subvencionado'),
('31379','COLEGIO PALMARES VALLE LOS CÓNDORES','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31380','ESCUELA ESPECIAL N°192 DE COLORES','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31381','ESCUELA ESPECIAL EL CASTILLO DE LOS TRES HERMANOS','Metropolitana','LA REINA','Part. Subvencionado'),
('31383','ESCUELA DE PARV. Y ESPECIAL MI PEQUEÑO DELFIN','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('31387','COLEGIO BOSTON COLLEGE ALTO MACUL','Metropolitana','LA FLORIDA','Part. Pagado'),
('31388','CENTRO TECNICO EDUCACIONAL SAN CAYETANO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31389','SEMBRANDO PALABRAS','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('31390','ESCUELA ESPECIAL ESCUELITA MANZANITA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31391','ESCUELA ESPECIAL N° 2398, ANTAY','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('31392','COLEGIO DENHAM SCHOOL','Metropolitana','SAN BERNARDO','Part. Pagado'),
('31394','NUEVA ALBORADA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('31396','ESCUELA ESPECIAL Nº 192 MONTESSORI DESPERTANDO PALABRAS','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('31405','EDUCAR LO BARNECHEA','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('31407','ESCUELA HOSPITALARIA EL CARMEN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31409','ESCUELA BASICA HUACALEMU','Ñuble','PORTEZUELO','Corp. Municipal'),
('31412','ESCUELA ESPECIAL DE LENGUAJE LAS AMÉRICAS','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('31419','ESCUELA BÁSICA Nº2490, COLEGIO INTERNACIONAL SEK AUSTRAL','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('31421','COLEGIO TERRA ANDINA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31423','ESCUELA  ESPECIAL  APRENDIENDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31424','ESCUELA DE LENGUAJE AMUILLAN','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('31425','COLEGIO SAN JOSÉ','Metropolitana','TALAGANTE','Part. Subvencionado'),
('31426','ESCUELA BASICA N°2403 GREEN FOREST COLLEGE','Metropolitana','ÑUÑOA','Part. Pagado'),
('31427','ESCUELA ESPECIAL Nº228 DE LENGUAJE ANDALIEN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31428','COLEGIO  INSTITUTO MANQUEHUE','Metropolitana','MELIPILLA','Part. Subvencionado'),
('31429','COLEGIO HOSPÍTALARIO CASABIERTA  COANIQUEM','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('31430','ESCUELA BASICA LAS ESPIGAS N° 2404','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('31431','ESCUELA ESPECIAL N°194 DE LENGUAJE NUEVO MUNDO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('31432','LICEO ALTO CORDILLERA DE LA FLORIDA','Metropolitana','LA FLORIDA','Municipal'),
('31433','ESCUELA ESPECIAL N° 2045 THE ALMOND SCHOOL','Metropolitana','LA PINTANA','Part. Subvencionado'),
('31435','ESCUELA ESPECIAL NUESTRA SEÑORA DEL MAIPO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31436','ESCUELA ESPECIAL ENTREPEQUES','Metropolitana','QUILICURA','Part. Subvencionado'),
('31437','ESCUELA ESPECIAL LUIS SEMBRADOR','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('31438','COLEGIO AULA CLINICA SANTA MARIA','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('31439','ESCUELA  DE  PARVULOS  RAYITO  DE  SOL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('31440','ESCUELA ESPECIAL EL CASTILLO  ENCANTADO','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('31441','ESCUELA ESPECIAL LICANCURA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('31443','ESCUELA ESPECIAL DE LENGUAJE LORD COCHRANE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('31445','COLEGIO FUNDADORES DE QUILPUE','Valparaíso','QUILPUÉ','Part. Pagado'),
('31446','ESC. ESP. DE LENGUAJE Y JARDIN INFANTIL EL CANELO','Valparaíso','CARTAGENA','Part. Subvencionado'),
('31447','ESCUELA ESPECIAL AITUE','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('31449','ESC. ESP. DE LENG. Y JARDIN NUEVO MUNDO','Valparaíso','QUINTERO','Part. Subvencionado'),
('31452','ESCUELA ESPECIAL DE LENGUAJE ARIKI MAU','Valparaíso','LOS ANDES','Part. Subvencionado'),
('31453','CENTRO DE DIAGNOSTICO Y TRATAMIENTO COMUNICAME','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('31455','ESC. ESP. DE LENGUAJE Y JARDIN INFANTIL PEUMAYEN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('31456','ESCUELA ESPECIAL DE LENGUAJE ANGELITOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('31458','ESCUELA ESPECIAL DE LENGUAJE HAKUNA MATATA','Valparaíso','SANTA MARÍA','Part. Subvencionado'),
('31459','ESCUELA ESPECIAL DE LENGUAJE CUMBRES DE LLAY LLAY','Valparaíso','LLAILLAY','Part. Subvencionado'),
('31460','ESCUELA ESPECIAL DE LENGUAJE PEUMAYEN','Valparaíso','QUILLOTA','Part. Subvencionado'),
('31461','ESCUELA ESPECIAL DE LENGUAJE NUEVA CALAFQUEN','Valparaíso','CARTAGENA','Part. Subvencionado'),
('31462','CENTRO EDUCACIONAL EL FARO','Valparaíso','QUINTERO','Part. Subvencionado'),
('31463','COLEGIO GOTITAS DE LUZ','Los Lagos','DALCAHUE','Part. Subvencionado'),
('31466','AULA HOSPITALARIA COPIAPÓ','Atacama','COPIAPÓ','Part. Subvencionado'),
('31486','CENTRO DE EDUCACION INTEGRADA DE ADULTOS CASA CHAMINADE','Maule','LINARES','Part. Subvencionado'),
('31489','SALA CUNA AMUYUNI','Tarapacá','IQUIQUE','Part. Pagado'),
('31492','ESC. ESP. Nº2411 TESORITOS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31494','COL HOSP. CONSTRUYENDO SUEÑOS, CLINICA DAVILA','Metropolitana','RECOLETA','Part. Subvencionado'),
('31495','COLEGIO LOS PENSAMIENTOS DE SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('31497','ESCUELA  ESPECIAL CASA  NIDO','Metropolitana','EL MONTE','Part. Subvencionado'),
('31498','ESC. ESPECIAL Nº 2413 LEYENDA DE NIÑOS','Metropolitana','HUECHURABA','Part. Subvencionado'),
('31499','COLEGIO THE SOUTHLAND','Metropolitana','LO BARNECHEA','Part. Pagado'),
('31500','ESC. BASICA Nº230 EL SEMBRADOR CASAS VIEJAS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('31502','ESC ESP PARV ELEFANTE MELODIA, LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('31503','ESCUELA ESPECIAL GOTITA BLUE','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('31504','ESCUELA BASICA N°2416 TREWHELA´S SCHOOL','Metropolitana','COLINA','Part. Pagado'),
('31505','ESCUELA ESPECIAL BAMBINI INSIEME','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('31506','ESCUELA BASICA  PETRA  COLLEGE','Metropolitana','ISLA DE MAIPO','Part. Subvencionado'),
('31507','ESCUELA  ESPECIAL  TAGORE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31508','ESCUELA ESPECIAL DE LENGUAJE NUEVO SOL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('31509','ESCUELA PREMILITAR  GENERAL BERNARDO OHIGGINS RIQUELME','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('31512','ESCUELA DE PARVULOS SALA CUNA Y JARDÍN INFANTIL KIDS SUN','Metropolitana','LAS CONDES','Part. Pagado'),
('31518','ESCUELA ESPECIAL Y DE PÁRVULOS HORMIGUITA 2','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('32022','CENTRO VITAMINA COSTANERA CENTER','Metropolitana','PROVIDENCIA','Part. Pagado'),
('32023','CENTRO VITAMINA PLAZA EGAÑA','Metropolitana','LA REINA','Part. Pagado'),
('32024','CENTRO VITAMINA PLAZA SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Pagado'),
('32025','CENTRO VITAMINA BARRIO REPÚBLICA','Metropolitana','SANTIAGO','Part. Pagado'),
('32026','CENTRO VITAMINA SAN FRANCISCO','Metropolitana','SANTIAGO','Part. Pagado'),
('32027','CENTRO VITAMINA ESTACIÓN CENTRAL','Metropolitana','ESTACIÓN CENTRAL','Part. Pagado'),
('32032','ESCUELA ESPECIAL DE LENGUAJE TORTUGUITA','Ñuble','CHILLÁN','Part. Subvencionado'),
('32040','JARDÍN INFANTIL  NIÑOS DEL BOSQUE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('32053','COLEGIO EL AVE MARIA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('32055','ESCUELA ESPECIAL DE LENGUAJE AMANCAY','Biobío','LAJA','Part. Subvencionado'),
('32058','ESCUELA ESPECIAL DE LENGUAJE SANTA TERESA','Coquimbo','LA SERENA','Part. Subvencionado'),
('32059','ESCUELA ECOLOGICA PEJERREYES','Coquimbo','OVALLE','Corp. Municipal'),
('32060','ESCUELA HOSPITALARIA CLÍNICA RED SALUD SANTIAGO','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('32061','SALA CUNA Y JARDÍN INFANTIL EL CASTILLO','Metropolitana','CALERA DE TANGO','Part. Pagado'),
('32068','JARDÍN INFANTIL PUPA PLACE','Metropolitana','VITACURA','Part. Pagado'),
('32080','JARDÍN INFANTIL BAMBOO','Metropolitana','COLINA','Part. Pagado'),
('32100','COLEGIO CAPIANNI','Atacama','COPIAPÓ','Part. Pagado'),
('32103','JARDÍN INFANTIL MONTESSORI NIDO DEL SIETECOLORES','Metropolitana','ÑUÑOA','Part. Pagado'),
('32107','JARDÍN INFANTIL CARITA DE LUNA','Metropolitana','LO PRADO','Part. Pagado'),
('32117','JARDÍN INFANTIL BANANITAS','Metropolitana','PADRE HURTADO','Part. Pagado'),
('32118','JARDÍN INFANTIL OESTE','Metropolitana','CERRILLOS','Part. Pagado'),
('32119','JARDÍN INFANTIL CONEJITO BLANCO','Metropolitana','SANTIAGO','Part. Pagado'),
('32139','JARDÍN INFANTIL EL RINCÓN DE LOS SUEÑOS','Metropolitana','SAN MIGUEL','Part. Pagado'),
('32140','ESCUELA BÁSICA Nº 211 INCLUSIVA SANTA MARIA','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('32160','ESCUELA ESPECIAL DE LENGUAJE ALTAZOR','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('32168','JARDIN INFANTIL Y SALA CUNA SUNNYSIDE','Metropolitana','SAN BERNARDO','Part. Pagado'),
('33065','JARDIN INFANTIL Y SALA CUNA MI RINCONCITO FELIZ','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('34263','JARDIN INFANTIL PASITOS DE AMOR','Biobío','FLORIDA','Servicio Local'),
('34356','BURBUJITAS','Biobío','TALCAHUANO','Corp. Municipal'),
('34367','DESTELLOS DEL AMANECER','Biobío','TOMÉ','Corp. Municipal'),
('34388','SALA CUNA Y JARDÍN INFANTIL FLORESTA','Biobío','HUALPÉN','Corp. Municipal'),
('34487','PASITOS DE ESPERANZA','Biobío','LOS ÁNGELES','Corp. Municipal'),
('34493','SEMBRANDO SUEÑOS VILLA LAS TRANQUERAS','Biobío','LOS ÁNGELES','Corp. Municipal'),
('34654','JARDIN INFANTIL PARQUE SAN ANDRES','Ñuble','EL CARMEN','Corp. Municipal'),
('35128','JARDIN INFANTIL SEMILLAS','Los Lagos','CALBUCO','Corp. Municipal'),
('35338','PASTORCITOS','Magallanes','PUNTA ARENAS','Servicio Local'),
('40000','ESC. PARVULOS CASITA DE CRISTAL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40001','ESCUELA DE PARVULOS OSITO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40006','COLEGIO LEONARDO DA VINCI','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40007','JARDIN INFANTIL MIS PRIMEROS PASOS 2','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40008','INSTITUTO DE EDUCACION PARA EL ADULTO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40009','CTRO.APOYO A LA EDUC.ESPEC.DE PUTAENDO','Valparaíso','PUTAENDO','Corp. Municipal'),
('40010','ESCUELA ESPECIAL SANTA TERESITA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40013','CTRO.INT.EDUC.ESP.NUEVA SIEMBRA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40014','COLEGIO ANTU-LEMU','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40015','ESCUELA DE LENGUAJE SAN RAFAEL','Valparaíso','OLMUÉ','Part. Subvencionado'),
('40016','ESC.ESPEC. DE LENGUAJE KAU KALEM','Valparaíso','QUILLOTA','Part. Subvencionado'),
('40017','COLEGIO INFANTES DE LIMACHE','Valparaíso','LIMACHE','Part. Subvencionado'),
('40018','ESC. ESPEC. DE TRANST. ESPECIF.DEL LENGUAJE A','Coquimbo','ILLAPEL','Part. Subvencionado'),
('40020','JARDIN INFANTIL ARCO IRIS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40023','COLEGIO SAN ALBERTO','O''Higgins','MACHALÍ','Part. Pagado'),
('40024','LICEO TECNICO MUNICIPAL JUAN HOPPE GANTZ','O''Higgins','OLIVAR','Corp. Municipal'),
('40025','LICEO REQUINOA','O''Higgins','REQUÍNOA','Corp. Municipal'),
('40026','JARDIN INFANTIL DISNEYLANDIA','Valparaíso','VALPARAÍSO','Part. Pagado'),
('40027','COLEGIO PASIONISTAS DE QUILPUE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40028','ESCUELA ESPECIAL NUEVA ESPERANZA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40029','LICEO BICENTENARIO DE EXCELENCIA LICEO MISTRALIANO','Coquimbo','PAIGUANO','Servicio Local'),
('40030','ESC. ESP. DE LENGUAJE CARITA FELIZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40033','COLEGIO DOMINGO FAUSTINO SARMIENTO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40034','ESC.ESP. DE LENGUAJE PATITO MARINO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40035','ESCUELA ESPECIAL ACUARELA','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40037','ESC. ESPECIAL DE LENGUAJE ALIWEN','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40038','COLEGIO WHIPPLE SCHOOL ORIENTE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40042','COLEGIO CASTILLA Y ARAGON','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40043','COLEGIO SUEÑO DEL MAÑANA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40045','CTRO ATENCION A LA DIVERSIDAD RAYUN','Valparaíso','EL QUISCO','Part. Subvencionado'),
('40047','COLEGIO SANTO TOMAS DE LAS ACACIAS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40048','ESC.DISCAPACIDAD INTELECTUAL NADIEL','Valparaíso','EL TABO','Part. Subvencionado'),
('40049','CTRO.ESTIM.DEL LENGUAJE SAN VALENTIN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40050','JARDIN INFANTIL MIS PEQUEÑOS ANGELITOS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40051','ESC.ESP.DE TRAST.ESP DEL LENG.MI PANAL','Coquimbo','LA SERENA','Part. Subvencionado'),
('40052','ESC. ESP. DE TRANST. ESP DEL LENGUAJE G.MISTR','Coquimbo','VICUÑA','Part. Subvencionado'),
('40054','ESCUELA SANTA LAURA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40055','ESC. ESP. TRANS. DEL LENG. CORDILLERA SINDEMP','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40056','ESC ESPECIAL DE LENGUAJE PUCARA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40057','JARDIN INFANTIL ARCOIRIS','Coquimbo','COQUIMBO','Part. Pagado'),
('40058','JARDIN INFANTIL Y ESCUELA ESPECIAL DE LENGUAJE  MY LITTLE ANGEL','Coquimbo','LA SERENA','Part. Subvencionado'),
('40059','JARDIN INFANTIL INDIGO','Coquimbo','LA SERENA','Part. Subvencionado'),
('40061','ESC.ESP.TRANS.ESPEC.DEL LENGUAJE LLAKOLEN','Coquimbo','OVALLE','Part. Subvencionado'),
('40062','ESC ESPEC DE LENGUAJE ALONQUEO-BELLOTO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40063','ESCUELA ESPECIAL LENGUAJE SAN JOSE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40064','COLEGIO ALTA CORDILLERA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40065','COLEGIO ERNESTO VILLARROEL TEN','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40066','ESCUELA DE PARVULOS ARCOIRIS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40068','ESCUELA DE LENGUAJE Y TRAST.DE LA COM.PALABRI','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40071','COLEGIO LANGUAGE SCHOOL','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('40073','COLEGIO MONTE SION','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40074','ESC.ESP.DE TRAST. ESPEC.DEL LENG.JARDIN DE SU','Coquimbo','LA SERENA','Part. Subvencionado'),
('40076','COLEGIO ADULTOS LAS VIOLETAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40077','ESCUELA ESPECIAL DE LENGUAJE SANTA GEMITA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40078','ESCUELA CARDENAL RAUL SILVA HENRIQUEZ','O''Higgins','LITUECHE','Corp. Municipal'),
('40079','JARDIN INFANTIL MELODIA','Tarapacá','IQUIQUE','Part. Pagado'),
('40080','LICEO FERMIN DEL REAL CASTILLO','O''Higgins','CHÉPICA','Corp. Municipal'),
('40082','ESC ESP.DE LENG SAN FRANCISCO DE ASIS','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40083','ESCUELA ESPECIAL DE LENGUAJE NAHUEL','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40085','ESC.ESPECIAL DE LENGUAJE ANTILLANKA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40089','ESCUELA ESPECIAL DE LENGUAJE LOS ALMENDROS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40090','ESCUELA ESPECIAL SANATORIO MARITIMO SN JUAN D','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40092','JARDIN INFANTIL LAS GOLONDRINAS','Valparaíso','QUILPUÉ','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
