-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 2 de 31 | filas 401-800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('585','COLEGIO THE INTERNATIONAL SCHOOL','Coquimbo','LA SERENA','Part. Pagado'),
('587','COLEGIO SERENA','Coquimbo','LA SERENA','Part. Pagado'),
('589','COLEGIO SANTO DOMINGO','Coquimbo','LA SERENA','Part. Subvencionado'),
('590','COLEGIO PARTICULAR SAN JOSE','Coquimbo','LA SERENA','Part. Pagado'),
('591','COLEGIO INGLES CATOLICO','Coquimbo','LA SERENA','Part. Pagado'),
('597','COLEGIO PEDRO PABLO MUÑOZ','Coquimbo','LA HIGUERA','Servicio Local'),
('598','ESCUELA DE PUNTA DE CHOROS','Coquimbo','LA HIGUERA','Servicio Local'),
('599','ESCUELA JOSE SANTOS OSSA','Coquimbo','LA HIGUERA','Servicio Local'),
('602','ESCUELA BASICA CARLOS CONDELL','Coquimbo','LA HIGUERA','Servicio Local'),
('604','ESCUELA DE PUNTA COLORADA','Coquimbo','LA HIGUERA','Servicio Local'),
('606','ESCUELA BASICA SAN ANDRES','Coquimbo','LA HIGUERA','Servicio Local'),
('608','ESCUELA DE LOS CHOROS','Coquimbo','LA HIGUERA','Servicio Local'),
('609','LICEO BICENTENARIO DE EXCELENCIA INSTITUTO SUPERIOR DE COMERCIO DE COQUIMBO','Coquimbo','COQUIMBO','Servicio Local'),
('610','LICEO INDUSTRIAL JOSE TOMAS DE URMENETA','Coquimbo','COQUIMBO','Servicio Local'),
('611','LICEO DIEGO PORTALES','Coquimbo','COQUIMBO','Servicio Local'),
('612','ESCUELA GUILLERMO CERECEDA','Coquimbo','COQUIMBO','Servicio Local'),
('613','COLEGIO DE ARTES CLAUDIO ARRAU','Coquimbo','COQUIMBO','Servicio Local'),
('614','ESCUELA PRESIDENTE ANIBAL PINTO','Coquimbo','COQUIMBO','Servicio Local'),
('615','ESCUELA COQUIMBO','Coquimbo','COQUIMBO','Servicio Local'),
('616','ESCUELA CARDENAL JOSE MARIA CARO','Coquimbo','COQUIMBO','Servicio Local'),
('617','COLEGIO SANTA CECILIA','Coquimbo','COQUIMBO','Servicio Local'),
('618','ESCUELA SANTO TOMAS DE AQUINO','Coquimbo','COQUIMBO','Servicio Local'),
('620','ESCUELA JOSE ALFARO ALFARO','Coquimbo','COQUIMBO','Servicio Local'),
('621','ESCUELA BASICA MARIO MUNOZ SILVA','Coquimbo','COQUIMBO','Servicio Local'),
('623','CENTRO LABORAL JEAN PIAGET','Coquimbo','COQUIMBO','Servicio Local'),
('624','ESCUELA DIFERENCIAL JUAN SANDOVAL C.','Coquimbo','COQUIMBO','Servicio Local'),
('625','ESCUELA TOMASA OLIVARES CAAMANO','Coquimbo','COQUIMBO','Servicio Local'),
('626','ESCUELA BASICA DAVID LEON TAPIA','Coquimbo','COQUIMBO','Servicio Local'),
('628','ESCUELA DE PENUELAS','Coquimbo','COQUIMBO','Servicio Local'),
('629','COLEGIO PABLO NERUDA','Coquimbo','COQUIMBO','Servicio Local'),
('630','COLEGIO LA HERRADURA','Coquimbo','COQUIMBO','Servicio Local'),
('631','ESCUELA SAN RAFAEL','Coquimbo','COQUIMBO','Servicio Local'),
('632','ESCUELA BASICA MANUEL DE SALAS','Coquimbo','COQUIMBO','Servicio Local'),
('634','ESCUELA DE HUACHALALUME','Coquimbo','COQUIMBO','Servicio Local'),
('635','ESCUELA DE TOTORALILLO','Coquimbo','COQUIMBO','Servicio Local'),
('637','ESCUELA LUCILA GODOY ALCAYAGA','Coquimbo','COQUIMBO','Servicio Local'),
('638','ESCUELA DE CAMARONES','Coquimbo','COQUIMBO','Servicio Local'),
('639','ESCUELA DE LAS BARRANCAS','Coquimbo','COQUIMBO','Servicio Local'),
('641','ESCUELA DE LAS CARDAS','Coquimbo','COQUIMBO','Servicio Local'),
('642','ESCUELA DE EL PENON','Coquimbo','COQUIMBO','Servicio Local'),
('643','ESCUELA DE TAMBILLOS','Coquimbo','COQUIMBO','Servicio Local'),
('644','ESCUELA DE PUERTO ALDEA','Coquimbo','COQUIMBO','Servicio Local'),
('645','ESCUELA DE EL TANGUE','Coquimbo','COQUIMBO','Servicio Local'),
('646','COLEGIO BERNARDO O´HIGGINS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('647','COLEGIO MANUEL MONTT','Coquimbo','COQUIMBO','Part. Subvencionado'),
('648','COLEGIO SANTA MARTA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('649','COLEGIO PARTICULAR GABRIELA MISTRAL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('650','ESCUELA PARTICULAR METODISTA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('655','COLEGIO PARTICULAR SAN IGNACIO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('656','LICEO BICENTENARIO DE EXCELENCIA LICEO PEDRO REGALADO S. VIDELA O.','Coquimbo','ANDACOLLO','Servicio Local'),
('657','ESCUELA LUIS CRUZ MARTINEZ','Coquimbo','ANDACOLLO','Servicio Local'),
('658','ESCUELA PATRICIO LYNCH','Coquimbo','ANDACOLLO','Servicio Local'),
('659','ESCUELA PADRE BLAS HERNANDEZ SANCHEZ','Coquimbo','ANDACOLLO','Servicio Local'),
('661','ESCUELA LUIS AMENABAR OSSA','Coquimbo','ANDACOLLO','Servicio Local'),
('662','ESCUELA DE MAITENCILLO','Coquimbo','ANDACOLLO','Servicio Local'),
('664','COLEGIO PARROQUIAL DE ANDACOLLO','Coquimbo','ANDACOLLO','Part. Subvencionado'),
('665','LICEO CARLOS ROBERTO MONDACA CORTES','Coquimbo','VICUÑA','Servicio Local'),
('666','ESCUELA BASICA LUCILA GODOY ALCAYAGA','Coquimbo','VICUÑA','Servicio Local'),
('668','ESCUELA EDMUNDO VIDAL CARDENAS','Coquimbo','VICUÑA','Servicio Local'),
('669','ESCUELA NEFTALI REYES','Coquimbo','VICUÑA','Servicio Local'),
('671','ESCUELA RIOS DE ELQUI','Coquimbo','VICUÑA','Servicio Local'),
('672','ESCUELA DE DIAGUITAS JUAN TORRES M.','Coquimbo','VICUÑA','Servicio Local'),
('673','ESCUELA JOSE ABELARDO NUNEZ','Coquimbo','VICUÑA','Servicio Local'),
('674','ESCUELA DE VINITA ALTA','Coquimbo','VICUÑA','Servicio Local'),
('676','ESCUELA DE SAN CARLOS','Coquimbo','VICUÑA','Servicio Local'),
('678','ESCUELA AMELIA BARAHONA MUJICA','Coquimbo','VICUÑA','Servicio Local'),
('680','ESCUELA FEDERICO BARNES PAYNE','Coquimbo','VICUÑA','Servicio Local'),
('681','ESCUELA DE EL ARENAL','Coquimbo','VICUÑA','Servicio Local'),
('682','ESCUELA DAGOBERTO CAMPOS NUNEZ','Coquimbo','VICUÑA','Servicio Local'),
('683','ESCUELA DE LA CALERA','Coquimbo','VICUÑA','Servicio Local'),
('686','ESCUELA BÁSICA MARIO AQUILES RODRIGUEZ','Coquimbo','PAIGUANO','Servicio Local'),
('687','ESCUELA DE HUANTA','Coquimbo','VICUÑA','Servicio Local'),
('688','ESCUELA DE CHAPILCA','Coquimbo','VICUÑA','Servicio Local'),
('689','ESCUELA DE VARILLAR','Coquimbo','VICUÑA','Servicio Local'),
('690','LICEO BICENTENARIO DE EXCELENCIA COLEGIO ANTONIO VARAS','Coquimbo','VICUÑA','Part. Subvencionado'),
('691','ESCUELA MUNICIPAL CIELO CLAROPAIHUANO','Coquimbo','PAIGUANO','Servicio Local'),
('692','ESCUELA JERONIMO GODOY VILLANUEVA','Coquimbo','PAIGUANO','Servicio Local'),
('693','ESCUELA BASICA HECTOR MANUEL HERNANDEZ','Coquimbo','PAIGUANO','Servicio Local'),
('694','ESCUELA GABRIELA MISTRAL','Coquimbo','PAIGUANO','Servicio Local'),
('695','ESCUELA BASICA SANTIAGO BUERAS A.','Coquimbo','PAIGUANO','Servicio Local'),
('696','ESCUELA MUNICIPAL LA ORTIGA','Coquimbo','PAIGUANO','Servicio Local'),
('697','ESCUELA MUNICIPAL ALCOHUAZ','Coquimbo','PAIGUANO','Servicio Local'),
('699','ESCUELA MARIA ISABEL PERALTA P.','Coquimbo','PAIGUANO','Servicio Local'),
('701','LICEO ESTELA AVILA MOLINA','Coquimbo','OVALLE','Corp. Municipal'),
('704','LICEO ALEJANDRO ALVAREZ JOFRE','Coquimbo','OVALLE','Corp. Municipal'),
('705','LICEO BICENTENARIO DE EXCELENCIA  POLITECNICO DE OVALLE','Coquimbo','OVALLE','Corp. Municipal'),
('706','COLEGIO FRAY JORGE','Coquimbo','OVALLE','Corp. Municipal'),
('707','ESCUELA BASICA HELENE LANG','Coquimbo','OVALLE','Corp. Municipal'),
('708','ESCUELA ANTONIO TIRADO LANAS','Coquimbo','OVALLE','Corp. Municipal'),
('709','ESCUELA BASICA OSCAR ARAYA MOLINA','Coquimbo','OVALLE','Corp. Municipal'),
('710','ESCUELA BASICA JOSE TOMAS OVALLE B.','Coquimbo','OVALLE','Corp. Municipal'),
('711','ESCUELA GUARDIAMARINA ERNESTO RIQUELME V','Coquimbo','OVALLE','Corp. Municipal'),
('712','ESCUELA BÁSICA ARTURO ALESSANDRI PALMA','Coquimbo','OVALLE','Corp. Municipal'),
('713','ESCUELA ARTURO VILLALON SIEULANNE','Coquimbo','OVALLE','Corp. Municipal'),
('714','ESCUELA BASICA VISTA HERMOSA','Coquimbo','OVALLE','Corp. Municipal'),
('715','ESCUELA BASICA BERNARDO O¦HIGGINS RIQUELME','Coquimbo','OVALLE','Corp. Municipal'),
('716','ESC.PADRE JOSEPH BENEDIKT STEGMEIER','Coquimbo','OVALLE','Corp. Municipal'),
('718','ESCUELA MARCOS MACUADA OGALDE','Coquimbo','OVALLE','Corp. Municipal'),
('719','COLEGIO YUNGAY','Coquimbo','OVALLE','Corp. Municipal'),
('721','ESCUELA BASICA FLORENCIO ESPINOZA LOPEZ','Coquimbo','OVALLE','Corp. Municipal'),
('722','ESC. HEBERTO VELAZQUEZ VELAZQUEZ','Coquimbo','OVALLE','Corp. Municipal'),
('723','ESCUELA VILLORRIO EL TALHUEN','Coquimbo','OVALLE','Corp. Municipal'),
('724','ESCUELA BASICA CALETA EL MAITEN','Coquimbo','OVALLE','Corp. Municipal'),
('725','ESCUELA EL CRISOL','Coquimbo','OVALLE','Corp. Municipal'),
('726','ESCUELA QUEBRADA SECA DE SOTAQUI','Coquimbo','OVALLE','Corp. Municipal'),
('727','ESCUELA LA PALOMA','Coquimbo','OVALLE','Corp. Municipal'),
('728','ESCUELA EL ALGARROBO','Coquimbo','OVALLE','Corp. Municipal'),
('729','ESCUELA BASICA LOS OLIVOS','Coquimbo','OVALLE','Corp. Municipal'),
('730','ESCUELA BASICA LUCIA NUNEZ DE LA CUADRA','Coquimbo','OVALLE','Corp. Municipal'),
('731','ESCUELA EL TRAPICHE','Coquimbo','OVALLE','Corp. Municipal'),
('733','ESCUELA SANTA CRISTINA','Coquimbo','OVALLE','Corp. Municipal'),
('735','ESCUELA LA QUIROGA','Coquimbo','OVALLE','Corp. Municipal'),
('736','ESCUELA BASICA LOS SOSSAS','Coquimbo','OVALLE','Corp. Municipal'),
('737','ESCUELA BASICA VALENTIN LETELIER','Coquimbo','OVALLE','Corp. Municipal'),
('740','ESCUELA PEDRO ENRIQUE ALFONSO BARRIOS','Coquimbo','OVALLE','Corp. Municipal'),
('743','ESCUELA CARACHILLA','Coquimbo','OVALLE','Corp. Municipal'),
('744','ESCUELA ORURO','Coquimbo','OVALLE','Corp. Municipal'),
('745','ESCUELA LA HIGUERA DE PALOMA','Coquimbo','OVALLE','Corp. Municipal'),
('746','ESCUELA EL SAUCE','Coquimbo','OVALLE','Corp. Municipal'),
('747','ESCUELA CERRO TAMAYA','Coquimbo','OVALLE','Corp. Municipal'),
('749','ESCUELA TRANQUE RECOLETA','Coquimbo','OVALLE','Corp. Municipal'),
('750','ESCUELA ELVIRA DEL CARMEN OCHOA AVILES','Coquimbo','OVALLE','Corp. Municipal'),
('752','ESCUELA VALLE HERMOSO','Coquimbo','OVALLE','Corp. Municipal'),
('753','ESC.BAS.JUAN PABLO ARTIGUES PENAFIEL','Coquimbo','OVALLE','Corp. Municipal'),
('754','ESCUELA LA ARAUCANA','Coquimbo','OVALLE','Corp. Municipal'),
('755','ESCUELA CANELILLA','Coquimbo','OVALLE','Corp. Municipal'),
('756','ESCUELA SANTA CATALINA','Coquimbo','OVALLE','Corp. Municipal'),
('757','ESCUELA BASICA EL GUINDO','Coquimbo','OVALLE','Corp. Municipal'),
('758','ESCUELA CORDILLERA','Coquimbo','OVALLE','Corp. Municipal'),
('759','ESCUELA BASICA GASPAR CABRALES','Coquimbo','OVALLE','Corp. Municipal'),
('760','ESCUELA LAS LOMAS DE PUNILLA','Coquimbo','OVALLE','Corp. Municipal'),
('762','ESCUELA CALETA EL TORO','Coquimbo','OVALLE','Corp. Municipal'),
('763','COLEGIO SAN JUAN BAUTISTA','Coquimbo','OVALLE','Part. Subvencionado'),
('766','COLEGIO SANTA MARIA EUFRASIA','Coquimbo','OVALLE','Part. Subvencionado'),
('767','COLEGIO PARTICULAR GABRIELA MISTRAL','Coquimbo','OVALLE','Part. Subvencionado'),
('768','COLEGIO LA PROVIDENCIA','Coquimbo','OVALLE','Part. Subvencionado'),
('769','COLEGIO SAN VIATOR','Coquimbo','OVALLE','Part. Subvencionado'),
('770','COLEGIO AMALIA ERRAZURIZ','Coquimbo','OVALLE','Part. Pagado'),
('771','ESCUELA PARTICULAR EL ARRAYAN','Coquimbo','OVALLE','Part. Subvencionado'),
('772','LICEO AGRICOLA DE OVALLE TADEO PERRY BARN','Coquimbo','OVALLE','Adm. Delegada'),
('773','ESCUELA SAMO ALTO','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('774','COLEGIO PICHASCA','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('775','ESCUELA BASICA DE FUNDINA','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('776','ES.BAS.SAN PEDRO DE RIO HURTADO','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('777','ESC.BASICA HIJOS DE EL CHANAR','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('778','ESCUELA BASICA LAS BREAS','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('780','ESCUELA BASICA TABAQUEROS','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('783','ESCUELA DOCTOR JOSE LUIS ARRANO','Coquimbo','ANDACOLLO','Servicio Local'),
('784','ESCUELA BASICA HUAMPULLA','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('785','ESCUELA BASICA LOS MAITENES DE SAMO ALTO','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('786','ESCUELA BASICA LA HUERTA','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('787','ESCUELA BASICA MORRILLOS','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('788','ESCUELA BASICA VADO DE MORRILLOS','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('789','ESCUELA EL ESPINAL DE RIO HURTADO','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('790','ESCUELA BASICA EL ROMERAL','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('792','ESCUELA BASICA ESTANCIA EL SAUCE','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('793','ESCUELA BASICA DE SERON','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('795','ESC.BASICA DOMINGO SANTA MARIA GONZALEZ','Coquimbo','ANDACOLLO','Servicio Local'),
('797','ESCUELA LOS MAITENES DE SERON','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('798','ESCUELA EL PALQUI','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('799','COLEGIO REPUBLICA DE CHILE','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('800','ESCUELA HUATULAME','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('802','LICEO BICENTENARIO DE EXCELENCIA LICEO PRESIDENTE EDUARDO FREI MONTALVA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('803','ESC.CONCENTRACION FRONTERIZA DE TULAHUEN','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('804','ESCUELA BASICA WENCESLAO VARGAS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('805','ESCUELA EL MAQUI','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('806','ESCUELA FRONTERA LAS RAMADAS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('807','ESCUELA EL MAITEN','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('809','ESCUELA DE HUANILLA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('810','ESCUELA CENTRAL HIDROELECTRICA LOS MOLLE','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('812','ESCUELA SOL DE LAS PRADERAS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('813','ESCUELA BASICA LA UNION','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('814','ESCUELA BASICA EL TAYAN','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('816','ESCUELA GUSTAVO CONTRERAS CASTRO','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('817','ESCUELA NUEVA ESPERANZA DE PEJERREYES','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('818','ESCUELA LOS CLONQUIS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('819','ESCUELA BUENAVENTURA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('820','ESCUELA SOL DEL CUYANO','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('821','ESCUELA DE FLOR DEL VALLE','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('822','ESCUELA JUNTAS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('823','ESCUELA BASICA COLLIGUAY','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('824','ESCUELA HEROES DE CHILE','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('825','ESCUELA BASICA PABLO NERUDA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('826','ESCUELA BASICA HACIENDA VALDIVIA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('827','COLEGIO RIO GRANDE','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('830','ESCUELA MARCELA PAZ','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('833','ESCUELA SANTA BERNARDITA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('835','ESCUELA CARMELA PRAT','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('836','ESCUELA INES DE SUAREZ','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('837','ESCUELA ESPERANZA DE HUANA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('838','ESCUELA PROFESOR MANUEL ORTIZ QUINTANA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('839','ESCUELA CHILECITO','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('843','ESCUELA LOS PERALES DE CAMPANARIO','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('844','ESCUELA PARTICULAR CERRILLOS DE RAPEL','Coquimbo','MONTE PATRIA','Part. Subvencionado'),
('845','LICEO BICENTENARIO DE EXCELENCIA LICEO SAMUEL ROMAN ROJAS','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('847','ESCUELA BASICA AMERICA','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('848','ESCUELA ALEJANDRO CHELEN ROJAS','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('849','ESCUELA BASICA JUANITA FERNANDEZ SOLAR','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('850','ESCUELA JUAN LUIS SAN FUENTES','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('851','ESCUELA BASICA ARTURO PEREZ CANTO','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('852','ESCUELA BASICA PEDRO DE VALDIVIA','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('857','ESCUELA LOS MORALES','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('859','ESCUELA REBECA MATTE DE INIGUEZ','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('862','ESCUELA ESTRELLA DE BELEN','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('864','ESCUELA BASICA VIOLETA PARRA SANDOVAL','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('865','ESCUELA BASICA DANIEL BARROS GREZ','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('868','ESCUELA AMERICA DE SUR','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('869','ESCUELA BASICA REBECA PONCE DE LEON V.','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('870','ESCUELA BASICA CAMILO HENRIQUEZ GONZALEZ','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('871','ESCUELA BASICA LUIS ENRIQUE BOU PEREZ','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('872','ESCUELA BASICA ROSITA OHIGGINS','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('875','ESCUELA BASICA PEDRO LIRA RENCORET','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('876','ESCUELA BASICA CLAUDIO MATTE','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('879','ESCUELA BASICA BENJAMIN VICUNA MACKENNA','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('886','ESCUELA LA VARIOLA','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('887','ESCUELA BASICA CAUPOLICAN','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('888','ESCUELA BASICA BOSQUE DE QUILLAY','Coquimbo','COMBARBALÁ','Corp. Municipal'),
('890','ESCUELA PARTICULAR LOS SAPOS','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('891','ESCUELA PARTICULAR RINCON DE LAS CHILCAS','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('892','ESCUELA PARTICULAR EL DURAZNO','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('896','ESCUELA PARTICULAR LA COLORADA','Coquimbo','COMBARBALÁ','Part. Subvencionado'),
('897','ESCUELA BELGICA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('899','ESCUELA LUZ DE LUNA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('900','ESCUELA BASICA LA HIGUERA DE QUILE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('902','ESCUELA BASICA ELENA CAFFARENA','Coquimbo','OVALLE','Corp. Municipal'),
('904','ESCUELA CAMPO LINDO','Coquimbo','OVALLE','Corp. Municipal'),
('905','ESCUELA CHALINGA','Coquimbo','OVALLE','Corp. Municipal'),
('906','ESCUELA LOS CANELOS','Coquimbo','OVALLE','Corp. Municipal'),
('907','ESCUELA HIJOS DEL PERAL','Coquimbo','PUNITAQUI','Corp. Municipal'),
('908','ESCUELA TABALI','Coquimbo','OVALLE','Corp. Municipal'),
('909','ESCUELA LOS AZAHARES DE CERRO BLANCO','Coquimbo','OVALLE','Corp. Municipal'),
('910','ESC.BASICA SAN ANTONIO DE LA VILLA','Coquimbo','OVALLE','Corp. Municipal'),
('911','ESCUELA LOS TRIGOS','Coquimbo','OVALLE','Corp. Municipal'),
('914','ESCUELA PENA BLANCA','Coquimbo','OVALLE','Corp. Municipal'),
('915','ESCUELA MARCOS RIGOBERTO PIZARRO ARAYA','Coquimbo','OVALLE','Corp. Municipal'),
('917','ESCUELA RINCON DE LA CALERA','Coquimbo','OVALLE','Corp. Municipal'),
('923','ESCUELA EL MAQUI DE QUILE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('924','ESCUELA LOS ACACIOS','Coquimbo','OVALLE','Corp. Municipal'),
('925','ESCUELA BASICA VILLA LOS QUILES','Coquimbo','PUNITAQUI','Corp. Municipal'),
('928','ESCUELA BASICA GRANEROS','Coquimbo','PUNITAQUI','Corp. Municipal'),
('929','ESCUELA LOS NOGALES','Coquimbo','OVALLE','Corp. Municipal'),
('931','ESCUELA SAN ANTONIO DE PADUA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('932','ESCUELA UNION CAMPESINA','Coquimbo','OVALLE','Corp. Municipal'),
('933','ESCUELA LAS CRUCES','Coquimbo','PUNITAQUI','Corp. Municipal'),
('934','ESCUELA BEATRIZ VEGA VEGA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('935','ESCUELA SALALA','Coquimbo','OVALLE','Corp. Municipal'),
('936','ESCUELA EL ESPINAL','Coquimbo','OVALLE','Corp. Municipal'),
('937','ESCUELA ALCONES BAJOS','Coquimbo','OVALLE','Corp. Municipal'),
('939','ESCUELA ALMENDRO DE QUILE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('940','ESCUELA SAN PEDRO','Coquimbo','PUNITAQUI','Corp. Municipal'),
('943','ESCUELA PADRE PABLO DIEHL HARTMAN','Coquimbo','OVALLE','Corp. Municipal'),
('945','ESCUELA SOL NACIENTE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('946','ESCUELA TERESITA DE LOS ANDES','Coquimbo','PUNITAQUI','Corp. Municipal'),
('947','ESCUELA AURORA DE CHILE','Coquimbo','OVALLE','Corp. Municipal'),
('949','ESCUELA EL DURAZNO DE QUILE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('950','ESCUELA LA CEBADAS','Coquimbo','OVALLE','Corp. Municipal'),
('951','ESCUELA LA CALERA DE SAN JULIAN','Coquimbo','OVALLE','Corp. Municipal'),
('952','ESCUELA BASICA LOS CIENAGOS','Coquimbo','OVALLE','Corp. Municipal'),
('953','ESCUELA PATRICIO ZEBALLOS','Coquimbo','OVALLE','Corp. Municipal'),
('954','ESCUELA EL AJIAL DE QUILE','Coquimbo','PUNITAQUI','Corp. Municipal'),
('955','ESCUELA VILLA LOS CORRALES','Coquimbo','PUNITAQUI','Corp. Municipal'),
('956','ESCUELA PORTEZUELOS BLANCOS','Coquimbo','PUNITAQUI','Corp. Municipal'),
('957','ESCUELA EL CIENAGO','Coquimbo','PUNITAQUI','Corp. Municipal'),
('959','COLEGIO PARTICULAR SALI HOCHSCHILD','Coquimbo','PUNITAQUI','Part. Subvencionado'),
('960','ESCUELA PARTICULAR EL LLANITO','Coquimbo','PUNITAQUI','Part. Subvencionado'),
('962','ESCUELA ALGARROBO DE HORNILLOS','Coquimbo','OVALLE','Corp. Municipal'),
('963','ESCUELA PARTICULAR EL TENIENTE','Coquimbo','OVALLE','Part. Subvencionado'),
('964','ESCUELA BASICA MUNICIPAL DE ADULTOS','Coquimbo','ILLAPEL','Corp. Municipal'),
('967','LICEO BICENTENARIO DE EXCELENCIA LICEO DOMINGO ORTIZ DE ROZAS','Coquimbo','ILLAPEL','Corp. Municipal'),
('968','LICEO POLITECNICO PABLO RODRIGUEZ CAVIEDES','Coquimbo','ILLAPEL','Corp. Municipal'),
('969','ESCUELA BASICA VALLE DEL CHOAPA','Coquimbo','ILLAPEL','Corp. Municipal'),
('970','ESCUELA JUAN CARRASCO RISCO','Coquimbo','ILLAPEL','Corp. Municipal'),
('971','ESCUELA BASICA SAN RAFAEL DE ROZAS','Coquimbo','ILLAPEL','Corp. Municipal'),
('972','ESCUELA BASICA JORGE ARACENA RAMOS','Coquimbo','ILLAPEL','Corp. Municipal'),
('973','ESCUELA BASICA CLEMENCIA VILLARROEL','Coquimbo','ILLAPEL','Corp. Municipal'),
('974','ESCUELA BASICA CAMILO HENRIQUEZ','Coquimbo','ILLAPEL','Corp. Municipal'),
('976','ESCUELA BASICA LAS PALMERAS DE LIMAHUIDA','Coquimbo','ILLAPEL','Corp. Municipal'),
('977','ESCUELA BASICA GRACIELA DIAZ ALLENDE','Coquimbo','ILLAPEL','Corp. Municipal'),
('978','ESCUELA BASICA MATANCILLA','Coquimbo','ILLAPEL','Corp. Municipal'),
('981','ESCUELA BASICA CHOAPA LINDO','Coquimbo','ILLAPEL','Corp. Municipal'),
('982','ESCUELA BASICA VILLA LOS NARANJOS','Coquimbo','ILLAPEL','Corp. Municipal'),
('984','ESCUELA BASICA TUNGA SUR','Coquimbo','ILLAPEL','Corp. Municipal'),
('985','ESCUELA BASICA ASIENTO VIEJO','Coquimbo','ILLAPEL','Corp. Municipal'),
('986','ESCUELA BASICA LAS CHINCHILLAS DE COCOU','Coquimbo','ILLAPEL','Corp. Municipal'),
('987','COLEGIO SANTA TERESA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('988','LICEO PARTICULAR LUIS ALBERTO VERA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('990','ESCUELA PARTICULAR LAS CANAS','Coquimbo','ILLAPEL','Part. Subvencionado'),
('991','ESCUELA PARTICULAR QUEBRADA EL PERAL','Coquimbo','ILLAPEL','Part. Subvencionado'),
('993','ESCUELA PARTICULAR CANELILLO ALTO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('994','ESCUELA PARTICULAR RINCON DEL ROMERO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('995','ESCUELA PARTICULAR CAREN','Coquimbo','ILLAPEL','Part. Subvencionado'),
('996','ESCUELA PARTICULAR EL LANCO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('997','ESCUELA PARTICULAR QUEBRADA DE CARCAMO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('998','ESCUELA PARTICULAR ILTA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('999','ESCUELA PARTICULAR 18 DE SEPTIEMBRE','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1000','ESCUELA PARTICULAR SAN ENRIQUE','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1001','ESCUELA PARTICULAR HERMINIA RAMOS','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1002','ESCUELA PARTICULAR EL SOCAVON','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1004','ESCUELA PARTICULAR LA CAPILLA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1005','ESCUELA PARTICULAR RINCON DE TUNGA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1006','ESCUELA MANUEL JOSE IRARRAZAVAL','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1008','ESCUELA PARTICULAR QUILLAICILLO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1010','ESCUELA PARTICULAR CUYUNTAGUA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1011','ESCUELA PARTICULAR MACUCO','Coquimbo','ILLAPEL','Part. Subvencionado'),
('1013','LICEO DE SALAMANCA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1014','ESCUELA MATILDE SALAMANCA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1015','ESCUELA BASICA DIAGUITAS DE CHALINGA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1016','ESCUELA TRANQUILLA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1017','ESCUELA BASICA BERTA HIDALGO BARAHONA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1018','ESCUELA EL TAMBO','Coquimbo','SALAMANCA','Corp. Municipal'),
('1019','ESCUELA BASICA CHILLEPIN','Coquimbo','SALAMANCA','Corp. Municipal'),
('1020','ESCUELA BASICA GUISELA GAMBOA SALINAS','Coquimbo','SALAMANCA','Corp. Municipal'),
('1022','ESCUELA COIRON','Coquimbo','SALAMANCA','Corp. Municipal'),
('1027','ESCUELA BASICA QUELEN BAJO','Coquimbo','SALAMANCA','Corp. Municipal'),
('1030','ESC.BASICA GUILLERMO BARRIOS VARGAS','Coquimbo','SALAMANCA','Corp. Municipal'),
('1031','ESCUELA BASICA JULIO ECHAVARRIA','Coquimbo','SALAMANCA','Corp. Municipal'),
('1032','ESCUELA BASICA SAN AGUSTIN','Coquimbo','SALAMANCA','Corp. Municipal'),
('1033','ESCUELA BASICA PANGUESILLO','Coquimbo','SALAMANCA','Corp. Municipal'),
('1034','ESCUELA LOS CORRALES','Coquimbo','SALAMANCA','Corp. Municipal'),
('1036','COLEGIO PARTICULAR SAN FRANCISCO DE ASIS','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1037','ESCUELA PARTICULAR HUANQUE','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1038','ESCUELA PARTICULAR EL PALQUIAL','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1041','ESCUELA PARTICULAR CAJON DE QUELEN','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1042','ESCUELA MUNICIPAL COLLIGUAY','Coquimbo','SALAMANCA','Corp. Municipal'),
('1044','ESCUELA PARTICULAR MANQUEHUA','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1045','ESCUELA PARTICULAR PUNTA NUEVA','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1046','ESCUELA PARTICULAR PLANTA PELADEROS','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1047','ESCUELA PARTICULAR VALLE CAMISAS','Coquimbo','SALAMANCA','Part. Subvencionado'),
('1048','LICEO NICOLAS FEDERICO LOHSE VARGAS','Coquimbo','LOS VILOS','Corp. Municipal'),
('1049','COLEGIO DIEGO DE ALMAGRO','Coquimbo','LOS VILOS','Corp. Municipal'),
('1050','ESCUELA BASICA ERCOLE BENCINI','Coquimbo','LOS VILOS','Corp. Municipal'),
('1051','ESCUELA BASICA TERESA CANNON DE B.','Coquimbo','LOS VILOS','Corp. Municipal'),
('1052','ESCUELA BASICA PABLO BARRIOLHET','Coquimbo','LOS VILOS','Corp. Municipal'),
('1053','ESCUELA BASICA FORJADORES DE CHILE','Coquimbo','LOS VILOS','Corp. Municipal'),
('1055','ESCUELA LOS MAQUIS','Coquimbo','LOS VILOS','Corp. Municipal'),
('1059','ESCUELA CLARA VIAL ORREGO','Coquimbo','LOS VILOS','Corp. Municipal'),
('1061','ESCUELA TILAMA','Coquimbo','LOS VILOS','Corp. Municipal'),
('1062','ESC.PDTE.FEDERICO ERRAZURIZ ECHAURREN','Coquimbo','LOS VILOS','Corp. Municipal'),
('1063','ESCUELA','Coquimbo','LOS VILOS','Corp. Municipal'),
('1064','ESCUELA BASICA EL QUELON','Coquimbo','LOS VILOS','Corp. Municipal'),
('1065','ESCUELA BASICA EL MANZANO','Coquimbo','LOS VILOS','Corp. Municipal'),
('1066','ESCUELA PARTICULAR DIVINA PROVIDENCIA','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1068','ESCUELA PARTICULAR CULIMO','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1069','ESCUELA PARTICULAR MINA LAS VACAS','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1071','ESCUELA PARTICULAR EL ROMERO','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1072','ESCUELA PARTICULAR INFIERNILLO','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1076','ESCUELA PARTICULAR MAIMALICAN','Coquimbo','LOS VILOS','Part. Subvencionado'),
('1077','ESCUELA BASICA HECTOR JORQUERA VALENCIA','Coquimbo','CANELA','Corp. Municipal'),
('1078','ESCUELA BASICA JUAN ANTONIO RIOS','Coquimbo','CANELA','Corp. Municipal'),
('1082','ESC.BASICA MERCEDES MARIN DEL SOLAR','Coquimbo','CANELA','Corp. Municipal'),
('1083','ESCUELA BASICA CARQUINDANO','Coquimbo','CANELA','Corp. Municipal'),
('1084','ESCUELA BASICA JABONERIA','Coquimbo','CANELA','Corp. Municipal'),
('1087','ESCUELA BASICA CANELA ALTA','Coquimbo','CANELA','Corp. Municipal'),
('1092','ESCUELA BASICA MINCHA NORTE','Coquimbo','CANELA','Corp. Municipal'),
('1093','ESCUELA BASICA ATELCURA ALTA','Coquimbo','CANELA','Corp. Municipal'),
('1094','ESCUELA BASICA POZA HONDA','Coquimbo','CANELA','Corp. Municipal'),
('1095','ESCUELA BASICA SARGENTO ALDEA','Coquimbo','CANELA','Corp. Municipal'),
('1096','ESCUELA BASICA LOS POZOS','Coquimbo','CANELA','Corp. Municipal'),
('1099','ESCUELA VIOLETA PARRA','Coquimbo','CANELA','Corp. Municipal'),
('1100','ESC.BASICA CARLOS VIAL ESPANTOSO','Coquimbo','CANELA','Corp. Municipal'),
('1101','ESCUELA BASICA JOSE MIGUEL CARRERA','Coquimbo','CANELA','Corp. Municipal'),
('1102','ESCUELA BASICA BALDOMERO LILLO FIGUEROA','Coquimbo','CANELA','Corp. Municipal'),
('1104','ESCUELA LA CORTADERA','Coquimbo','CANELA','Corp. Municipal'),
('1108','ESCUELA BASICA MARTA BRUNETT','Coquimbo','CANELA','Corp. Municipal'),
('1109','ESCUELA BASICA GABRIELA MISTRAL','Coquimbo','CANELA','Corp. Municipal'),
('1113','ESCUELA BASICA SALVADOR REYES','Coquimbo','CANELA','Corp. Municipal'),
('1114','ESCUELA PARTICULAR EL CHILCAL','Coquimbo','CANELA','Part. Subvencionado'),
('1116','ESCUELA PARTICULAR CANELILLA','Coquimbo','CANELA','Part. Subvencionado'),
('1117','ESCUELA PARTICULAR LOS TOMES','Coquimbo','CANELA','Part. Subvencionado'),
('1119','COLEGIO PARTICULAR SANTA MARIA','Valparaíso','LA LIGUA','Part. Subvencionado'),
('1120','CENTRO DE EDUCACION DE ADULTOS LA LIGUA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1121','LICEO PULMAHUE DE LA LIGUA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1122','ESCUELA REPUBLICA DE VENEZUELA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1123','ESCUELA GABRIELA MISTRAL','Valparaíso','LA LIGUA','Corp. Municipal'),
('1125','ESCUELA DIEGO PORTALES','Valparaíso','LA LIGUA','Corp. Municipal'),
('1126','ESCUELA ESPECIAL SOL NACIENTE','Valparaíso','LA LIGUA','Corp. Municipal'),
('1128','ESCUELA COMUNIDADES DE VALLE HERMOSO','Valparaíso','LA LIGUA','Corp. Municipal'),
('1129','ESCUELA ANGEL MENAY','Valparaíso','LA LIGUA','Corp. Municipal'),
('1130','ESC. BASICA LOS HORNOS DE HUAQUEN','Valparaíso','LA LIGUA','Corp. Municipal'),
('1131','ESC. BASICA CASAS VIEJAS DE LONGOTOMA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1132','ESCUELA BASICA POZA VERDE','Valparaíso','LA LIGUA','Corp. Municipal'),
('1133','ESC.BASICA LAS CASAS DE HUAQUEN','Valparaíso','LA LIGUA','Corp. Municipal'),
('1134','CARMEN SANCHEZ ARAYA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1135','ESCUELA BASICA LOS MOLLES','Valparaíso','LA LIGUA','Corp. Municipal'),
('1136','ESCUELA BASICA PUYANCON','Valparaíso','LA LIGUA','Corp. Municipal'),
('1137','ESCUELA BASICA HORTENCIA POWELL S.','Valparaíso','LA LIGUA','Corp. Municipal'),
('1139','ESCUELA MINISTRO GOMEZ MILLAS','Valparaíso','LA LIGUA','Corp. Municipal'),
('1140','ESCUELA BASICA CARLOS ARIZTIA RUIZ','Valparaíso','LA LIGUA','Corp. Municipal'),
('1142','ESCUELA LA CANELA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1143','ESCUELA BASICA QUEBRADILLA','Valparaíso','LA LIGUA','Corp. Municipal'),
('1144','ESCUELA BASICA PICHICUY','Valparaíso','LA LIGUA','Corp. Municipal'),
('1145','ESCUELA ENRIQUE DOLL ROJAS','Valparaíso','LA LIGUA','Corp. Municipal'),
('1147','ESCUELA FERNANDO GARCIA OLDINI','Valparaíso','PETORCA','Corp. Municipal'),
('1148','LICEO JOSE MANUEL BORGONO NUNEZ','Valparaíso','PETORCA','Corp. Municipal'),
('1149','LICEO CORDILLERA','Valparaíso','PETORCA','Corp. Municipal'),
('1150','ESCUELA BASICA NEFTALI REYES B.','Valparaíso','PETORCA','Corp. Municipal'),
('1151','ESCUELA BASICA VILLA SANTA ANA','Valparaíso','PETORCA','Corp. Municipal'),
('1152','ESCUELA EDUARDO FREI MONTALVA','Valparaíso','PETORCA','Corp. Municipal'),
('1153','ESCUELA BASICA EL CRUCERO','Valparaíso','PETORCA','Corp. Municipal'),
('1156','ESCUELA BASICA G-24','Valparaíso','PETORCA','Corp. Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
