-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 8 de 31 | filas 2801-3200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('4436','ESCUELA BASICA SANTA ADRIANA','Biobío','MULCHÉN','Corp. Municipal'),
('4437','ESCUELA BASICA AURORA DE ENERO','Biobío','MULCHÉN','Corp. Municipal'),
('4441','ESCUELA BASICA CASAS DE PILE','Biobío','MULCHÉN','Corp. Municipal'),
('4443','ESCUELA SAN BERNARDINO DE SENA','Biobío','MULCHÉN','Part. Subvencionado'),
('4445','ESCUELA PARTICULAR SUBVENCIONADO EL MIRADOR DEL BIOBÍO','Biobío','MULCHÉN','Part. Subvencionado'),
('4446','LICEO POLIVALENTE LA FRONTERA','Biobío','NEGRETE','Corp. Municipal'),
('4447','ESCUELA BASICA RIHUE','Biobío','NEGRETE','Corp. Municipal'),
('4448','ESCUELA BASICA VILLA COIGUE','Biobío','NEGRETE','Corp. Municipal'),
('4449','ESCUELA BASICA VAQUERIA','Biobío','NEGRETE','Corp. Municipal'),
('4451','LICEO POLIVALENTE MUNICIPAL DE NACIMIENTO','Biobío','NACIMIENTO','Corp. Municipal'),
('4452','ESCUELA EL SABER','Biobío','NACIMIENTO','Corp. Municipal'),
('4453','ESCUELA OSCAR GUERRERO QUINSAC','Biobío','NACIMIENTO','Corp. Municipal'),
('4454','ESCUELA CANADA','Biobío','NACIMIENTO','Corp. Municipal'),
('4455','ESCUELA TOQUI LAUTARO','Biobío','NACIMIENTO','Corp. Municipal'),
('4456','ESCUELA BASICA DOLLINCO','Biobío','NACIMIENTO','Corp. Municipal'),
('4459','ESCUELA SAN RAMON','Biobío','NACIMIENTO','Corp. Municipal'),
('4460','ESCUELA LOS PATOS','Biobío','NACIMIENTO','Corp. Municipal'),
('4462','ESCUELA BASICA EL PERAL','Biobío','NACIMIENTO','Corp. Municipal'),
('4466','ESCUELA VÍCTOR MANUEL BELTRÁN CARRIMÁN','Biobío','NACIMIENTO','Corp. Municipal'),
('4467','ESCUELA SANTA LUISA','Biobío','NACIMIENTO','Corp. Municipal'),
('4469','ESCUELA PALMILLA','Biobío','NACIMIENTO','Corp. Municipal'),
('4470','ESCUELA SAN FRANCISCO DE MILLAPOA','Biobío','NACIMIENTO','Corp. Municipal'),
('4471','ESCUELA CARRIZAL','Biobío','NACIMIENTO','Corp. Municipal'),
('4472','ESCUELA SAN ROQUE','Biobío','NACIMIENTO','Corp. Municipal'),
('4474','ESCUELA MILLAPOA DIUQUIN','Biobío','NACIMIENTO','Corp. Municipal'),
('4476','ESCUELA LOS GUINDOS ALTO','Biobío','NACIMIENTO','Corp. Municipal'),
('4478','ESCUELA LOS CASTANOS','Biobío','NACIMIENTO','Corp. Municipal'),
('4479','ESCUELA CHEQUENAL','Biobío','NACIMIENTO','Corp. Municipal'),
('4480','ESCUELA PARTICULAR EL CARRIZAL','Biobío','NACIMIENTO','Part. Subvencionado'),
('4481','ESCUELA JOSE ABELARDO NUNEZ','Biobío','LAJA','Corp. Municipal'),
('4482','ESCUELA NIVEQUETEN','Biobío','LAJA','Corp. Municipal'),
('4483','LICEO BICENTENARIO POLITECNICO HEROES DE LA CONCEPCIÓN','Biobío','LAJA','Corp. Municipal'),
('4484','ESCUELA BASICA LA COLONIA','Biobío','LAJA','Corp. Municipal'),
('4485','ESCUELA FRANCISCO PEDRO ZATTERA GUELFI','Biobío','LAJA','Corp. Municipal'),
('4486','ESCUELA LAS CIÉNAGAS','Biobío','LAJA','Corp. Municipal'),
('4491','ESCUELA LOS CERRILLOS','Biobío','LAJA','Corp. Municipal'),
('4494','ESCUELA RUCAHUE','Biobío','LAJA','Corp. Municipal'),
('4495','ESCUELA DIEGO JOSE BENAVENTE BUSTAMANTE','Biobío','LAJA','Corp. Municipal'),
('4496','COLEGIO PARTICULAR SAN MAURICIO','Biobío','LAJA','Part. Subvencionado'),
('4497','ESCUELA PARTICULAR ALFA Y OMEGA','Biobío','LAJA','Part. Subvencionado'),
('4499','COLEGIO SAN JORGE','Biobío','LAJA','Part. Pagado'),
('4500','LICEO ISIDORA AGUIRRE TUPPER','Biobío','SAN ROSENDO','Corp. Municipal'),
('4502','ESCUELA BASICA TURQUIA','Biobío','SAN ROSENDO','Corp. Municipal'),
('4503','ESCUELA BASICA LOS CALLEJONES','Biobío','SAN ROSENDO','Corp. Municipal'),
('4505','LICEO PADRE LUIS ALBERTO SALDES IRARRAZABAL','Biobío','YUMBEL','Corp. Municipal'),
('4506','ESCUELA HÉROES DE CHILE','Biobío','YUMBEL','Corp. Municipal'),
('4507','LICEO TÉCNICO PROFESIONAL GONZALO GUGLIELMI MONTIEL','Biobío','YUMBEL','Corp. Municipal'),
('4509','LICEO MUNICIPAL RIO CLARO','Biobío','YUMBEL','Corp. Municipal'),
('4510','ESCUELA MUNICIPAL CAMBRALES','Biobío','YUMBEL','Corp. Municipal'),
('4512','ESCUELA ENRIQUE PUFFE KIND','Biobío','YUMBEL','Corp. Municipal'),
('4513','ESCUELA PADRE PEDRO CAMPOS MENCHACA','Biobío','YUMBEL','Corp. Municipal'),
('4514','ESCUELA MUNICIPAL RERE','Biobío','YUMBEL','Corp. Municipal'),
('4527','ESCUELA MUNICIPAL CERRO PARRA','Biobío','YUMBEL','Corp. Municipal'),
('4530','INSTITUTO SAN SEBASTIÁN BÁSICO.','Biobío','YUMBEL','Part. Subvencionado'),
('4531','COLEGIO MARINA DE CHILE','Biobío','CONCEPCIÓN','Servicio Local'),
('4533','LICEO TÉCNICO FEMENINO A-29 DE CONCEPCIÓN','Biobío','CONCEPCIÓN','Adm. Delegada'),
('4534','LICEO BICENTENARIO DE EXCELENCIA COMERCIAL INSUCO','Biobío','CONCEPCIÓN','Adm. Delegada'),
('4535','LICEO INDUSTRIAL DE CONCEPCION','Biobío','CONCEPCIÓN','Adm. Delegada'),
('4536','LICEO COMERCIAL FEMENINO DE CONCEPCION','Biobío','CONCEPCIÓN','Adm. Delegada'),
('4540','ESCUELA PARVULARIA BLANCA ESTELA','Biobío','CONCEPCIÓN','Servicio Local'),
('4543','ESCUELA ESPECIAL CHILE ESPAÑA','Biobío','CONCEPCIÓN','Servicio Local'),
('4544','ESCUELA NUEVO HORIZONTES','Biobío','CONCEPCIÓN','Servicio Local'),
('4546','CENTRO INTEGRADO DE EDUCACIÓN ESPECIAL','Biobío','CONCEPCIÓN','Servicio Local'),
('4548','COLEGIO BIOBÍO','Biobío','CONCEPCIÓN','Servicio Local'),
('4550','ESCUELA DIFERENCIAL PIERRE MENDES FRANCE','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4551','ESCUELA BÁSICA COMÚN HOSPITAL','Biobío','CONCEPCIÓN','Servicio Local'),
('4553','LICEO DE NIÑAS','Biobío','CONCEPCIÓN','Servicio Local'),
('4555','LICEO ENRIQUE MOLINA GARMENDIA','Biobío','CONCEPCIÓN','Servicio Local'),
('4557','LICEO POLIVALENTE EXPERIMENTAL LUCILA GODOY ALCAYAGA','Biobío','CONCEPCIÓN','Servicio Local'),
('4558','LICEO DE ADULTOS JOSÉ MANUEL BALMACEDA FERNÁNDEZ','Biobío','CONCEPCIÓN','Servicio Local'),
('4559','LICEO LORENZO ARENAS OLIVO','Biobío','CONCEPCIÓN','Servicio Local'),
('4560','LICEO CHIGUAYANTE','Biobío','CHIGUAYANTE','Servicio Local'),
('4561','LICEO JUAN MARTINEZ DE ROZAS','Biobío','CONCEPCIÓN','Servicio Local'),
('4562','LICEO SAN PEDRO','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4563','COLEGIO REPÚBLICA DEL ECUADOR','Biobío','CONCEPCIÓN','Servicio Local'),
('4564','COLEGIO BICENTENARIO REPÚBLICA DEL BRASIL','Biobío','CONCEPCIÓN','Servicio Local'),
('4565','LICEO DOMINGO SANTA MARÍA','Biobío','CONCEPCIÓN','Servicio Local'),
('4566','ESCUELA BASICA REPUBLICA ARGENTINA','Biobío','CONCEPCIÓN','Servicio Local'),
('4569','ESCUELA DIEGO PORTALES PALAZUELOS','Biobío','CONCEPCIÓN','Servicio Local'),
('4571','COLEGIO JOSE HIPOLITO SALAS Y TORO','Biobío','CHIGUAYANTE','Servicio Local'),
('4572','COLEGIO GRAN BRETAÑA','Biobío','CONCEPCIÓN','Servicio Local'),
('4574','COLEGIO BICENTENARIO ESPAÑA','Biobío','CONCEPCIÓN','Servicio Local'),
('4575','COLEGIO JOHN KENNEDY','Biobío','CHIGUAYANTE','Servicio Local'),
('4576','ESCUELA BELGICA','Biobío','CHIGUAYANTE','Servicio Local'),
('4577','COLEGIO REPÚBLICA DE ISRAEL','Biobío','CONCEPCIÓN','Servicio Local'),
('4578','ESCUELA DARIO SALAS MARCHANT','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4579','ESCUELA BASICA RENE LOUVEL BERT','Biobío','CONCEPCIÓN','Servicio Local'),
('4581','ESCUELA OSCAR CASTRO ZUNIGA','Biobío','CONCEPCIÓN','Servicio Local'),
('4582','ESCUELA ESTHER HUNNEUS DE CLARO','Biobío','CONCEPCIÓN','Servicio Local'),
('4584','ESCUELA REPUBLICA FEDERAL ALEMANA','Biobío','CHIGUAYANTE','Servicio Local'),
('4585','LICEO REBECA MATTE BELLO','Biobío','CONCEPCIÓN','Servicio Local'),
('4586','ESCUELA BASICA MANQUIMAVIDA','Biobío','CHIGUAYANTE','Servicio Local'),
('4588','COLEGIO JUAN GREGORIO LAS HERAS','Biobío','CONCEPCIÓN','Servicio Local'),
('4589','LICEO LUCERO GONZALEZ','Biobío','CONCEPCIÓN','Servicio Local'),
('4591','COLEGIO REPUBLICA DE GRECIA','Biobío','CHIGUAYANTE','Servicio Local'),
('4592','ESCUELA BÁSICA IRENE FREI DE CID','Biobío','CONCEPCIÓN','Servicio Local'),
('4593','BASICA SARGENTO CANDELARIA PEREZ','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4594','ESCUELA MIGUEL JOSE ZANARTU SANTA MARIA','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4595','ESCUELA ENRIQUE SORO BARRIGA','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4597','ESCUELA LA ESPERANZA','Biobío','CHIGUAYANTE','Servicio Local'),
('4603','ESCUELA BASICA LAGOS DE CHILE','Biobío','CONCEPCIÓN','Servicio Local'),
('4609','ESCUELA PALESTINA DE PALOMARES','Biobío','CONCEPCIÓN','Servicio Local'),
('4611','ESCUELA BASICA LUIS ALBERTO ACEVEDO','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4612','ESCUELA LUIS ALFREDO MUÑOZ BURBOA','Biobío','CONCEPCIÓN','Servicio Local'),
('4613','ESCUELA BASICA LAUTARO','Biobío','CONCEPCIÓN','Servicio Local'),
('4614','ESCUELA BASICA AGUA DE LA GLORIA','Biobío','CONCEPCIÓN','Servicio Local'),
('4615','ESCUELA BASICA BOCA DEL BIO BIO SUR','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4616','ESCUELA BASICA MICHAIHUE','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4617','COLEGIO GALVARINO DE LOMAS COLORADAS','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('4622','ESCUELA BASICA FUNDO CHANCO','Biobío','CONCEPCIÓN','Servicio Local'),
('4626','ESCUELA JOSE MIGUEL CARRERA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4627','COLEGIO PARTICULAR AURORA DE CHILE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4628','ESCUELA PARTICULAR PRESIDENTE GABRIEL GONZÁLEZ VIDELA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4629','ESCUELA PARTICULAR PEDRO DE ONA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4630','COLEGIO DEL SAGRADO CORAZON','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4631','COLEGIO PARTICULAR ANDRÉS BELLO','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4633','COLEGIO PARTICULAR SANTA INES','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4635','COLEGIO LAGUNA REDONDA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4636','COLEGIO MARCELA PAZ','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4638','UNIDAD DE INTEGRACIÓN DEL LIMITADO VISUAL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4639','ESCUELA PARTICULAR SANTA EMILIA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4641','COLEGIO PARTICULAR ALBORADA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4644','COLEGIO PARTICULAR JUAN BOSCO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4645','COLEGIO PARTICULAR EL LIBERTADOR','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4646','COLEGIO SANTA SABINA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4647','COLEGIO PARTICULAR ALONSO DE ERCILLA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4648','ESCUELA BASICA MALVINA ROMERO VIDAL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4650','COLEGIO COLEGIO MARTÍN LUTHER','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4655','COLEGIO ADVENTISTA DE CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4656','ESCUELA PARTICULAR INSTITUTO SAN PEDRO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4658','ESCUELA PARTICULAR MANQUIMAVIDA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4659','COLEGIO LA PROVIDENCIA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4660','ESCUELA PARTTICULAR SANTA CATALINA DE SIENA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4662','COLEGIO SAN IGNACIO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4663','COLEGIO MARIA INMACULADA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4664','COLEGIO SANTA EUFRASIA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4665','COLEGIO EDWARD','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4666','COLEGIO SANTA LUISA DE CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4667','COLEGIO SAN PATRICIO','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4669','LICEO SAN AGUSTIN DE CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4670','ESCUELA PARTICULAR EL NAZARENO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4672','LICEO TÉCNICO PROFESIONAL BICENTENARIO JORGE SÁNCHEZ UGARTE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4675','ESCUELA PARTICULAR ANDRES BELLO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4677','ESCUELA PARTICULAR SAN JOSE','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('4679','KINGSTON COLLEGE','Biobío','CONCEPCIÓN','Part. Pagado'),
('4680','COLEGIO BAUTISTA DE CONCEPCION','Biobío','CONCEPCIÓN','Part. Pagado'),
('4686','INSTITUTO DE HUMANIDADES ALFREDO SILVA S','Biobío','CONCEPCIÓN','Part. Pagado'),
('4687','COLEGIO ALEMAN DE CONCEPCIÓN','Biobío','SAN PEDRO DE LA PAZ','Part. Pagado'),
('4688','CHARLES DE GAULLE','Biobío','CONCEPCIÓN','Part. Pagado'),
('4689','COLEGIO CONCEPCION','Biobío','CHIGUAYANTE','Part. Pagado'),
('4691','COLEGIO CHILENO ARABE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('4694','SAINT JOHN´S SCHOOL','Biobío','SAN PEDRO DE LA PAZ','Part. Pagado'),
('4698','SAN PEDRO NOLASCO','Biobío','CONCEPCIÓN','Part. Pagado'),
('4700','LICEO BICENTENARIO INDUSTRIAL DE LA CONSTRUCCIÓN HERNÁN VALENZUELA LEYTON','Biobío','HUALPÉN','Adm. Delegada'),
('4702','LICEO BICENTENARIO ALMIRANTE PEDRO ESPINA RITCHIE','Biobío','TALCAHUANO','Corp. Municipal'),
('4703','LICEO INDUSTRIAL JUAN ANTONIO RIOS','Biobío','TALCAHUANO','Corp. Municipal'),
('4706','LICEO TÉCNICO PROFESIONAL PEDRO DEL RÍO ZAÑARTU','Biobío','HUALPÉN','Corp. Municipal'),
('4707','LICEO COMERCIAL PROFESOR SERGIO MORAGA ARCIL','Biobío','TALCAHUANO','Corp. Municipal'),
('4708','LICEO POLIVALENTE LAS SALINAS','Biobío','TALCAHUANO','Corp. Municipal'),
('4709','LICEO TECNICO DE TALCAHUANO','Biobío','TALCAHUANO','Corp. Municipal'),
('4711','ARTURO PRAT CHACON','Biobío','TALCAHUANO','Corp. Municipal'),
('4712','LICEO SANTA LEONOR','Biobío','TALCAHUANO','Corp. Municipal'),
('4713','ESCUELA THOMAS JEFFERSON D 465','Biobío','HUALPÉN','Corp. Municipal'),
('4714','ESCUELA HELEN KELLER ADAMS','Biobío','HUALPÉN','Corp. Municipal'),
('4715','LICEO SIMÓN BOLÍVAR','Biobío','HUALPÉN','Corp. Municipal'),
('4717','LICEO TÉCNICO PROFESIONAL LUCILA GODOY ALCAYAGA','Biobío','HUALPÉN','Corp. Municipal'),
('4719','ESCUELA REPUBLICA DEL PERU','Biobío','HUALPÉN','Corp. Municipal'),
('4720','ESCUELA D N° 475','Biobío','TALCAHUANO','Corp. Municipal'),
('4722','ESCUELA BLANCA ESTELA PRAT CARVAJAL','Biobío','HUALPÉN','Corp. Municipal'),
('4723','ESCUELA MEXICO ESTADO DE GUERRERO','Biobío','TALCAHUANO','Corp. Municipal'),
('4724','ESCUELA BASICA LA DAMA BLANCA','Biobío','TALCAHUANO','Corp. Municipal'),
('4725','ESCUELA VILLA INDEPENDENCIA','Biobío','TALCAHUANO','Corp. Municipal'),
('4726','ESCUELA BASICA LAS HIGUERAS','Biobío','TALCAHUANO','Corp. Municipal'),
('4727','COLEGIO HUACHIPATO','Biobío','TALCAHUANO','Corp. Municipal'),
('4728','COLEGIO LOS CONDORES','Biobío','TALCAHUANO','Corp. Municipal'),
('4730','ESCUELA ALONKURA','Biobío','HUALPÉN','Corp. Municipal'),
('4731','ESCUELA BÁSICA CRISTÓBAL COLÓN','Biobío','HUALPÉN','Corp. Municipal'),
('4732','ESCUELA BASICA CRUZ DEL SUR','Biobío','TALCAHUANO','Corp. Municipal'),
('4733','LICEO BICENTENARIO ANITA SERRANO SEPULVEDA','Biobío','TALCAHUANO','Corp. Municipal'),
('4734','ESCUELA BASICA LIBERTAD','Biobío','TALCAHUANO','Corp. Municipal'),
('4736','ESCUELA CORNETA CABRALES','Biobío','TALCAHUANO','Corp. Municipal'),
('4737','COLEGIO BASICO VILLA ACERO','Biobío','HUALPÉN','Corp. Municipal'),
('4740','C.E.I.A. HUALPENCILLO','Biobío','HUALPÉN','Corp. Municipal'),
('4741','ESCUELA DIFERENCIAL PUERTA NUEVA','Biobío','TALCAHUANO','Corp. Municipal'),
('4742','COLEGIO REMODELACION SIMONS','Biobío','TALCAHUANO','Corp. Municipal'),
('4744','ESCUELA BASICA CERRO CORNOU','Biobío','TALCAHUANO','Corp. Municipal'),
('4746','ESCUELA BUENA VISTA ZAROR','Biobío','TALCAHUANO','Corp. Municipal'),
('4747','ESCUELA F 500 HUERTOS FAMILIARES','Biobío','TALCAHUANO','Corp. Municipal'),
('4750','ESCUELA SANTA CLARA','Biobío','TALCAHUANO','Corp. Municipal'),
('4751','CENTRO LABORAL POLIVALENTE ALONKURA','Biobío','TALCAHUANO','Corp. Municipal'),
('4753','ESCUELA BASICA PENINSULA DE TUMBES','Biobío','TALCAHUANO','Corp. Municipal'),
('4754','ESCUELA BASICA CERRO SAN FRANCISCO','Biobío','TALCAHUANO','Corp. Municipal'),
('4758','COLEGIO CARMELA CARVAJAL DE PRAT','Biobío','TALCAHUANO','Part. Subvencionado'),
('4760','COLEGIO BERNARDO O´HIGGINS','Biobío','HUALPÉN','Part. Subvencionado'),
('4762','LICEO LA ASUNCION','Biobío','TALCAHUANO','Part. Subvencionado'),
('4767','ESCUELA PARTICULAR MANUEL RODRIGUEZ','Biobío','HUALPÉN','Part. Subvencionado'),
('4768','CENTRO INTEGRAL LOS AROMOS','Biobío','HUALPÉN','Part. Subvencionado'),
('4772','ESCUELA ADVENTISTA DE HUALPEN','Biobío','HUALPÉN','Part. Subvencionado'),
('4774','ESCUELA PARTICULAR ENRIQUE MOLINA GARMENDIA','Biobío','HUALPÉN','Part. Subvencionado'),
('4776','COLEGIO PARTICULAR LOS ARAUCANOS','Biobío','TALCAHUANO','Part. Subvencionado'),
('4777','ESCUELA PARTICULAR ESMERALDA','Biobío','TALCAHUANO','Part. Subvencionado'),
('4778','COLEGIO PARTICULAR TALCAHUANO','Biobío','TALCAHUANO','Part. Subvencionado'),
('4779','COLEGIO ADVENTISTA DE TALCAHUANO CENTRO','Biobío','TALCAHUANO','Part. Subvencionado'),
('4781','ESCUELA BASICA ELIEZER','Biobío','TALCAHUANO','Part. Subvencionado'),
('4782','CENTRO EDUCACIÓN EVANGÉLICO DE HUALPÉN','Biobío','HUALPÉN','Part. Subvencionado'),
('4785','COLEGIO SANTA BERNARDITA','Biobío','TALCAHUANO','Part. Subvencionado'),
('4786','ESCUELA SANTA TERESITA','Biobío','HUALPÉN','Part. Subvencionado'),
('4790','COLEGIO MONTANER DE HUALPEN','Biobío','HUALPÉN','Part. Subvencionado'),
('4791','ESCUELA PARTICULAR DIEGO PORTALES','Biobío','HUALPÉN','Part. Subvencionado'),
('4792','COLEGIO SANTA CECILIA','Biobío','TALCAHUANO','Part. Subvencionado'),
('4796','ARTURO PRAT CHACON','Biobío','TALCAHUANO','Part. Pagado'),
('4798','SAGRADOS CORAZONES','Biobío','HUALPÉN','Part. Pagado'),
('4803','ESCUELA DIFERENCIAL MARTA STOWHAS KARGUS','Biobío','PENCO','Corp. Municipal'),
('4805','LICEO PENCOPOLITANO','Biobío','PENCO','Corp. Municipal'),
('4806','ESCUELA REPUBLICA DE ITALIA','Biobío','PENCO','Corp. Municipal'),
('4807','ESCUELA ISLA DE PASCUA','Biobío','PENCO','Corp. Municipal'),
('4808','ESCUELA PENCO','Biobío','PENCO','Corp. Municipal'),
('4809','ESCUELA EDUARDO CAMBELL SAAVEDRA','Biobío','PENCO','Corp. Municipal'),
('4810','ESCUELA ALMIRANTE JORGE MONTT ÁLVAREZ','Biobío','PENCO','Corp. Municipal'),
('4811','ESCUELA ALMIRANTE PATRICIO LYNCH','Biobío','PENCO','Corp. Municipal'),
('4812','ESCUELA LA GREDA','Biobío','PENCO','Corp. Municipal'),
('4813','ESCUELA VIPLA','Biobío','PENCO','Corp. Municipal'),
('4814','ESCUELA ETHEL HENCK DE GRANT','Biobío','PENCO','Corp. Municipal'),
('4817','ESCUELA BASICA PRIMER AGUA ABAJO','Biobío','PENCO','Corp. Municipal'),
('4818','COLEGIO PARTICULAR FUNNY SCHOOL','Biobío','PENCO','Part. Subvencionado'),
('4820','ESCUELA PARTICULAR QUEEN ELIZABETH SCHOOL','Biobío','PENCO','Part. Subvencionado'),
('4822','COLEGIO EL REFUGIO','Biobío','PENCO','Part. Subvencionado'),
('4824','LICEO BICENTENARIO DE EXCELENCIA INDUSTRIAL DE TOME','Biobío','TOMÉ','Adm. Delegada'),
('4825','LICEO COMERCIAL DE TOME','Biobío','TOMÉ','Corp. Municipal'),
('4827','ESCUELA ESPECIAL TOMÉ','Biobío','TOMÉ','Corp. Municipal'),
('4829','LICEO VICENTE ALBERTO PALACIOS VALDES','Biobío','TOMÉ','Corp. Municipal'),
('4830','LICEO REPÚBLICA DEL ECUADOR','Biobío','TOMÉ','Corp. Municipal'),
('4831','ESCUELA BASICA BELLAVISTA','Biobío','TOMÉ','Corp. Municipal'),
('4832','ESCUELA BASICA IGNACIO SERRANO MONTANER','Biobío','TOMÉ','Corp. Municipal'),
('4834','ESCUELA BASICA DICHATO','Biobío','TOMÉ','Corp. Municipal'),
('4835','ESCUELA BASICA ARTURO PRAT','Biobío','TOMÉ','Corp. Municipal'),
('4836','ESCUELA BASICA REPUBLICA DE PANAMA','Biobío','TOMÉ','Corp. Municipal'),
('4837','ESCUELA BASICA RAFAEL','Biobío','TOMÉ','Corp. Municipal'),
('4838','ESCUELA BASICA CARLOS MAHNS CHOUPAY','Biobío','TOMÉ','Corp. Municipal'),
('4839','ESCUELA BASICA COCHOLGUE','Biobío','TOMÉ','Corp. Municipal'),
('4840','ESCUELA PATRIMONIAL CALIFORNIA','Biobío','TOMÉ','Corp. Municipal'),
('4841','ESCUELA BASICA CERRO ESTANQUE','Biobío','TOMÉ','Corp. Municipal'),
('4842','ESCUELA MARIANO EGANA','Biobío','TOMÉ','Corp. Municipal'),
('4843','ESCUELA BÁSICA LISA ENRIQUETA PETER TEUBNER','Biobío','TOMÉ','Corp. Municipal'),
('4844','ESCUELA BASICA MENQUE','Biobío','TOMÉ','Corp. Municipal'),
('4845','ESCUELA BASICA PUNTA DE PARRA','Biobío','TOMÉ','Corp. Municipal'),
('4848','ESCUELA BASICA SAN CARLITOS','Biobío','TOMÉ','Corp. Municipal'),
('4851','ESCUELA BASICA BURCA','Biobío','TOMÉ','Corp. Municipal'),
('4852','ESCUELA BASICA CALETA DEL MEDIO','Biobío','TOMÉ','Corp. Municipal'),
('4854','ESCUELA BASICA SAN FRANCISCO','Biobío','TOMÉ','Corp. Municipal'),
('4855','ESCUELA BASICA MILLAHUE','Biobío','TOMÉ','Corp. Municipal'),
('4858','ESCUELA BASICA CORONEY','Biobío','TOMÉ','Corp. Municipal'),
('4859','ESCUELA BASICA CHUPALLAR','Biobío','TOMÉ','Corp. Municipal'),
('4860','ESCUELA BASICA VEGAS DE COLIUMO','Biobío','TOMÉ','Corp. Municipal'),
('4861','ESCUELA BASICA SAN ANTONIO','Biobío','TOMÉ','Corp. Municipal'),
('4865','ESCUELA PARTICULAR MARGARITA NASEAU','Biobío','TOMÉ','Part. Subvencionado'),
('4866','COLEGIO DOCTOR GUILLERMO VELASCO BARROS','Biobío','TOMÉ','Part. Subvencionado'),
('4867','ESCUELA BASICA RAFAEL AMPUERO VILLARROEL','Biobío','TOMÉ','Part. Subvencionado'),
('4868','COLEGIO PADRE LUIS AMIGO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('4869','ESCUELA BASICA FLORIDA','Biobío','FLORIDA','Servicio Local'),
('4870','LICEO LUIS DE ALAVA','Biobío','FLORIDA','Servicio Local'),
('4871','LICEO COPIULEMU','Biobío','FLORIDA','Servicio Local'),
('4873','ESCUELA RAHUIL','Biobío','FLORIDA','Servicio Local'),
('4874','ESCUELA BASICA GRANERILLO','Biobío','FLORIDA','Servicio Local'),
('4875','ESCUELA BASICA CANCHA DE LOS MONTERO','Biobío','FLORIDA','Servicio Local'),
('4876','ESCUELA BASICA LA PAZ','Biobío','FLORIDA','Servicio Local'),
('4877','ESCUELA BASICA PONEN','Biobío','FLORIDA','Servicio Local'),
('4879','ESCUELA BASICA PUENTE SIETE','Biobío','FLORIDA','Servicio Local'),
('4882','ESCUELA BASICA QUEBRADA LAS ULLOA','Biobío','FLORIDA','Servicio Local'),
('4886','ESCUELA BASICA SAN SEBASTIAN DE MANCO','Biobío','FLORIDA','Servicio Local'),
('4887','ESCUELA BASICA CRUCERO DE HUARO','Biobío','FLORIDA','Servicio Local'),
('4889','ESCUELA BASICA PENINHUEQUE','Biobío','FLORIDA','Servicio Local'),
('4890','ESCUELA BASICA VILLAMAVIDA','Biobío','FLORIDA','Servicio Local'),
('4892','ESCUELA BASICA JUAN CHICO','Biobío','FLORIDA','Servicio Local'),
('4894','PARVULARIO RURAL MANDERSCHEID','Biobío','FLORIDA','Part. Subvencionado'),
('4896','ESCUELA PARTICULAR UNICORNIO','Biobío','FLORIDA','Part. Subvencionado'),
('4897','LICEO SAN JUAN BAUTISTA DE HUALQUI','Biobío','HUALQUI','Servicio Local'),
('4898','ESCUELA MANUEL AMAT Y JUNIET','Biobío','HUALQUI','Servicio Local'),
('4901','ESCUELA BASICA EL MAITEN','Biobío','HUALQUI','Servicio Local'),
('4902','ESCUELA CARLOS ALBERTO FERNÁNDEZ CASTILLO','Biobío','HUALQUI','Servicio Local'),
('4903','ESCUELA BASICA SANTA FILOMENA DE PICHACO','Biobío','HUALQUI','Servicio Local'),
('4904','ESCUELA BASICA RANGUEL','Biobío','HUALQUI','Servicio Local'),
('4905','ESCUELA QUINQUIBUENO','Biobío','HUALQUI','Servicio Local'),
('4906','ESCUELA SAN JOSE LA PALMA','Biobío','HUALQUI','Servicio Local'),
('4907','ESCUELA GOMERO','Biobío','HUALQUI','Servicio Local'),
('4908','ESCUELA ALEJANDRO VARELA SANTA MARIA','Biobío','HUALQUI','Servicio Local'),
('4909','ESCUELA PROFESORA JUANA SALGADO PARRA DE UNIHUE','Biobío','HUALQUI','Servicio Local'),
('4910','ESCUELA GUILLERMO BARBERI MASSA','Biobío','HUALQUI','Servicio Local'),
('4911','ESCUELA DE CHILLANCITO','Biobío','HUALQUI','Servicio Local'),
('4912','ESCUELA MAQUEUTO','Biobío','HUALQUI','Servicio Local'),
('4913','ESCUELA BARRANCAS JUNTAS','Biobío','HUALQUI','Servicio Local'),
('4915','ESCUELA LA CALLE','Biobío','HUALQUI','Servicio Local'),
('4917','ESCUELA SANTA SUSANA DE PICHACO','Biobío','HUALQUI','Servicio Local'),
('4918','ESCUELA AGUA CORTA','Biobío','HUALQUI','Servicio Local'),
('4920','ESCUELA SAN NICANOR','Biobío','HUALQUI','Servicio Local'),
('4921','ESCUELA ARMANDO JOSE SANTOS IBANEZ VARGA','Biobío','HUALQUI','Servicio Local'),
('4922','COLEGIO CONCEPCION HUALQUI','Biobío','HUALQUI','Part. Subvencionado'),
('4923','ESCUELA PARTICULAR SANTA CRUZ','Biobío','HUALQUI','Part. Subvencionado'),
('4924','ESCUELA PARTICULAR SANTO DOMINGO','Biobío','HUALQUI','Part. Subvencionado'),
('4925','LICEO NUEVA ZELANDIA','Biobío','SANTA JUANA','Servicio Local'),
('4926','ESCUELA RECAREDO VIGUERAS ARANEDA','Biobío','SANTA JUANA','Servicio Local'),
('4927','ESCUELA COLICO ALTO','Biobío','SANTA JUANA','Servicio Local'),
('4929','ESCUELA ESPIGADO','Biobío','SANTA JUANA','Servicio Local'),
('4930','ESCUELAS LAS CACHANAS','Biobío','SANTA JUANA','Corp. Municipal'),
('4932','ESCUELA PODUCO ALTO','Biobío','SANTA JUANA','Corp. Municipal'),
('4933','ESCUELA CABRERA','Biobío','SANTA JUANA','Corp. Municipal'),
('4936','ESCUELA PURGATORIO','Biobío','SANTA JUANA','Corp. Municipal'),
('4940','ESCUELA CURAMAVIDA','Biobío','SANTA JUANA','Servicio Local'),
('4942','ESCUELA TANAHUILLIN','Biobío','SANTA JUANA','Servicio Local'),
('4943','ESCUELA CHACAYAL','Biobío','SANTA JUANA','Servicio Local'),
('4946','ESCUELA LA GENERALA','Biobío','SANTA JUANA','Servicio Local'),
('4947','ESCUELA PARTICULAR CLORINDA AVELLO','Biobío','SANTA JUANA','Part. Subvencionado'),
('4948','LICEO POLITECNICO ROSAURO SANTANA RIOS','Biobío','LOTA','Servicio Local'),
('4949','LICEO COMERCIAL PRESIDENTE FREI MONTALVA','Biobío','LOTA','Servicio Local'),
('4950','ESCUELA ESPECIAL LUIS COUSINO SQUELLA','Biobío','LOTA','Servicio Local'),
('4951','LICEO CARLOS COUSIÑO GOYENECHEA','Biobío','LOTA','Servicio Local'),
('4952','LICEO BALDOMERO LILLO FIGUEROA','Biobío','LOTA','Servicio Local'),
('4953','ESCUELA ISIDORA GOYENECHEA','Biobío','LOTA','Servicio Local'),
('4954','ESCUELA BASICA SANTA MARIA DE GUADALUPE','Biobío','LOTA','Servicio Local'),
('4955','ESCUELA BASICA KONRAD ADENAUER','Biobío','LOTA','Servicio Local'),
('4956','ESCUELA BASICA BELLO HORIZONTE','Biobío','LOTA','Servicio Local'),
('4958','LICEO THOMPSON MATTHEWS','Biobío','LOTA','Servicio Local'),
('4960','COLEGIO ANGEL DE PEREDO','Biobío','LOTA','Servicio Local'),
('4961','ESCUELA BASICA COLCURA','Biobío','LOTA','Servicio Local'),
('4965','C.E.I.A SAN LUIS DE POTOSI REPÚBLICA DE MÉXICO','Biobío','LOTA','Servicio Local'),
('4967','ESCUELA BASICA CENTENARIO','Biobío','LOTA','Servicio Local'),
('4968','ESCUELA BÁSICA ARTÍSTICA ISAÍAS GUEVARA SOTO','Biobío','LOTA','Servicio Local'),
('4969','LICEO SANTA DORIS','Biobío','LOTA','Part. Subvencionado'),
('4971','ESCUELA PARTICULAR SANTA TERESA','Biobío','LOTA','Part. Subvencionado'),
('4973','INSTITUTO HUMANIDADES SAN FRANCISCO DE ASIS','Biobío','LOTA','Part. Subvencionado'),
('4974','ESCUELA PARTICULAR GETSEMANI','Biobío','LOTA','Part. Subvencionado'),
('4975','LICEO BICENTENARIO DE EXCELENCIA INDUSTRIAL FEDERICO SCHWAGER','Biobío','CORONEL','Adm. Delegada'),
('4977','LICEO COMERCIAL ANDRES BELLO LOPEZ','Biobío','CORONEL','Servicio Local'),
('4978','CENTRO EDUCACIÓN INTEGRADA DE ADULTOS SERGIO PERALTA MORALES','Biobío','CORONEL','Corp. Municipal'),
('4979','ESCUELA DIFERENCIAL MARÍA ESTER BREVE GONZÁLEZ','Biobío','CORONEL','Servicio Local'),
('4982','LICEO CORONEL ANTONIO SALAMANCA','Biobío','CORONEL','Servicio Local'),
('4983','LICEO YOBILO DE CORONEL','Biobío','CORONEL','Servicio Local'),
('4984','ESCUELA ROSITA RENARD','Biobío','CORONEL','Servicio Local'),
('4985','ESCUELA BASICA PLAYAS NEGRAS','Biobío','CORONEL','Servicio Local'),
('4986','ESCUELA ROSA MEDEL AGUILERA','Biobío','CORONEL','Servicio Local'),
('4987','ESCUELA BASICA JAVIERA CARRERA','Biobío','CORONEL','Servicio Local'),
('4988','ESCUELA RAFAEL SOTOMAYOR BAEZA','Biobío','CORONEL','Servicio Local'),
('4989','ESCUELA VICTOR DOMINGO SILVA','Biobío','CORONEL','Servicio Local'),
('4990','ESCUELA AMBROSIO O´HIGGINS','Biobío','CORONEL','Servicio Local'),
('4991','ESCUELA REPUBLICA DE FRANCIA','Biobío','CORONEL','Servicio Local'),
('4992','ESCUELA REMIGIO CASTRO ABURTO','Biobío','CORONEL','Servicio Local'),
('4994','ESCUELA ADELAIDA MIGUIELES SOTO','Biobío','CORONEL','Servicio Local'),
('4995','ESCUELA OCTAVIO SALINAS CARIAGA','Biobío','CORONEL','Servicio Local'),
('4996','ESCUELA VISTA HERMOSA','Biobío','CORONEL','Servicio Local'),
('4997','ESCUELA JORGE ROJAS MIRANDA','Biobío','CORONEL','Servicio Local'),
('4998','ESCUELA ROSA YANEZ RODRIGUEZ','Biobío','CORONEL','Servicio Local'),
('4999','ESCUELA BASICA RAMON FREIRE SERRANO','Biobío','CORONEL','Servicio Local'),
('5001','ESCUELA ARTURO HUGHES CERNA','Biobío','CORONEL','Servicio Local'),
('5002','ESCUELA JUAN JOSE LATORRE BENAVENTE','Biobío','CORONEL','Servicio Local'),
('5003','ESCUELA FRANCISCO COLOANE','Biobío','CORONEL','Servicio Local'),
('5005','ESCUELA ESCUADRON','Biobío','CORONEL','Servicio Local'),
('5006','ESCUELA BASICA PATAGUAL','Biobío','CORONEL','Servicio Local'),
('5009','COLEGIO PARTICULAR GABRIELA MISTRAL','Biobío','CORONEL','Part. Subvencionado'),
('5010','ESCUELA METODISTA','Biobío','CORONEL','Part. Subvencionado'),
('5012','COLEGIO PARTICULAR SAN PEDRO','Biobío','CORONEL','Part. Subvencionado'),
('5015','ESCUELA PARTICULAR SAN MARCOS','Biobío','CORONEL','Part. Subvencionado'),
('5016','COLEGIO PARTICULAR IGNACIO CARRERA PINTO','Biobío','CORONEL','Part. Subvencionado'),
('5019','ESCUELA GENARO RIOS CAMPOS','Biobío','CORONEL','Part. Subvencionado'),
('5020','COLEGIO ANIBAL ESQUIVEL TAPIA','Biobío','CORONEL','Part. Subvencionado'),
('5021','LICEO TÉCNICO PROFESIONAL DOCTOR RIGOBERTO IGLESIAS BASTÍAS DE LEBU','Biobío','LEBU','Corp. Municipal'),
('5022','ESCUELA ESPECIAL JUAN SANDOVAL CARRASCO','Biobío','LEBU','Corp. Municipal'),
('5023','ESCUELA PROFESOR ALAMIRO GALLEGOS MUÑOZ','Biobío','LEBU','Corp. Municipal'),
('5024','LICEO BICENTENARIO ISIDORA RAMOS DE GAJARDO','Biobío','LEBU','Corp. Municipal'),
('5025','ESCUELA PROFESORA REBECA CASTRO ARANEDA','Biobío','LEBU','Corp. Municipal'),
('5026','ESCUELA FRESIA GRACIELA MULLER RUIZ','Biobío','LEBU','Corp. Municipal'),
('5028','ESCUELA BOCA LEBU','Biobío','LEBU','Corp. Municipal'),
('5029','DOMINGO FAUSTINO SARMIENTO','Biobío','LEBU','Corp. Municipal'),
('5031','ESCUELA DR.ARNOLDO EBENSPERGER RICHTER','Biobío','LEBU','Corp. Municipal'),
('5032','ESCUELA JOSE JOAQUIN PEREZ','Biobío','LEBU','Corp. Municipal'),
('5033','ESCUELA ARTURO EBENSPERGER RICHTER','Biobío','LEBU','Corp. Municipal'),
('5034','ESCUELA LA FORTUNA','Biobío','LEBU','Corp. Municipal'),
('5035','ESCUELA ARMANDO ARANCIBIA OLIVOS','Biobío','LEBU','Corp. Municipal'),
('5036','ESCUELA RUCA RAQUI','Biobío','LEBU','Corp. Municipal'),
('5038','ESCUELA PEHUEN','Biobío','LEBU','Corp. Municipal'),
('5039','ESCUELA GUILLERMO RODRIGUEZ RIOBO','Biobío','LEBU','Corp. Municipal'),
('5040','ESCUELA VILLARRICA','Biobío','LEBU','Corp. Municipal'),
('5046','ESCUELA PARTICULAR CERRO LA CRUZ','Biobío','LEBU','Part. Subvencionado'),
('5047','ESCUELA LIBERTADOR GENERAL','Biobío','ARAUCO','Corp. Municipal'),
('5048','LICEO BICENTENARIO SAN FELIPE DE ARAUCO','Biobío','ARAUCO','Corp. Municipal'),
('5049','ESCUELA BASICA VICENTE MILLAN IRIARTE','Biobío','ARAUCO','Corp. Municipal'),
('5050','ESCUELA BÁSICA MARE NOSTRUM','Biobío','ARAUCO','Corp. Municipal'),
('5051','ESCUELA BÁSICA DE CARAMPANGUE','Biobío','ARAUCO','Corp. Municipal'),
('5052','ESCUELA LOS PINOS','Biobío','ARAUCO','Corp. Municipal'),
('5053','ESCUELA JORGE IVAN VALENZUELA ZUNIGA','Biobío','ARAUCO','Corp. Municipal'),
('5054','ESCUELA BASICA SAN PEDRO DE LARAQUETE','Biobío','ARAUCO','Corp. Municipal'),
('5055','ESCUELA VALLE RAMADILLAS','Biobío','ARAUCO','Corp. Municipal'),
('5056','ESCUELA BASICA CARLOS SAEZ SAEZ','Biobío','ARAUCO','Corp. Municipal'),
('5057','LICEO TÉCNICO PESQUERO FILIDOR GAETE MONSÁLVEZ','Biobío','ARAUCO','Corp. Municipal'),
('5059','ESCUELA HUGO CABRERA AGUIRRE','Biobío','ARAUCO','Corp. Municipal'),
('5060','ESCUELA ARMANDO WIESSE FUENTE-ALBA','Biobío','ARAUCO','Corp. Municipal'),
('5062','ESCUELA LOMAS DE ANGUILLAS','Biobío','ARAUCO','Corp. Municipal'),
('5064','ESCUELA FERMIN IBARRA FRITZ','Biobío','ARAUCO','Corp. Municipal'),
('5065','ESCUELA QUILANTRAL','Biobío','ARAUCO','Corp. Municipal'),
('5066','ESCUELA BASICA PASO LOS TEMOS','Biobío','ARAUCO','Corp. Municipal'),
('5067','ESCUELA MAR LOS PINOS','Biobío','ARAUCO','Corp. Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
