-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 15 de 31 | filas 5601-6000
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('9612','ESCUELA BASICA ISLAS DE CHILE','Metropolitana','LA GRANJA','Servicio Local'),
('9614','ESCUELA BASICA KARELMAPU','Metropolitana','SAN RAMÓN','Servicio Local'),
('9616','LICEO VICTOR JARA','Metropolitana','LA PINTANA','Servicio Local'),
('9617','LICEO MUNICIPAL LA GRANJA POETA NERUDA','Metropolitana','LA GRANJA','Servicio Local'),
('9618','ESCUELA BAS. BENJAMIN SUBERCASEAUX','Metropolitana','LA GRANJA','Servicio Local'),
('9620','ESCUELA BASICA JUAN DE DIOS ALDEA','Metropolitana','LA PINTANA','Servicio Local'),
('9625','ESCUELA BASICA VILLA LA CULTURA','Metropolitana','SAN RAMÓN','Servicio Local'),
('9626','ESCUELA BAS. REINA GUILLERMINA DE HOLANDA','Metropolitana','LA GRANJA','Servicio Local'),
('9629','ESCUELA BASICA ALIVEN','Metropolitana','SAN RAMÓN','Servicio Local'),
('9631','ESCUELA ESPECIAL DE ADULTOS','Metropolitana','SAN RAMÓN','Servicio Local'),
('9634','COLEGIO MARISTA MARCELINO CHAMPAGNAT','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9635','ESCUELA ESPECIAL PART. EDUCADORAS AGAZZI','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9636','CHILEAN EAGLES COLLEGE-LA PINTANA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9637','COLEGIO CHRISTIAN GARDEN SCHOOL','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9638','COLEGIO POLIVALENTE PADRE ESTEBAN GUMUCIO VIVES','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9639','ESCUELA PARTICULAR EMA DIAZ SIERRA','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9642','ESCUELA PARTICULAR TTE.DAGOBERTO GODOY','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9646','COLEGIO POLIVALENTE FRANCISCO RAMIREZ','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9647','LICEO BICENTENARIO SAN FRANCISCO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9648','ESCUELA PARTICULAR FRANCISCO DE MIRANDA','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9653','ESCUELA BASICA PRESBITERIANA EL SALVADOR','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9654','ESCUELA PARTICULAR FRANCISCO RAMIREZ','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9655','ESCUELA PARTICULAR CLAUDIO MATTE','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9656','ESCUELA PARTICULAR PDTE.JOSE J.PRIETO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9659','ESCUELA COLEGIO ALBERTO BLEST GANA','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9660','ESCUELA PARTIC PARROQUIAL DOMINGO SAVIO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9663','ESCUELA PARTICULAR ELSA RAMIREZ','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9664','COLEGIO PARTICULAR PUERTO NAVARINO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9665','CENTRO EDUCACIONAL SANTA ROSA DEL SUR','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9666','ESC. PART. CELESTIN FREINET','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9667','ESC.PART. ESPECIAL NUESTRO MUNDO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9668','COLEGIO OSCAR SALINAS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9669','COLEGIO NUESTRO MUNDO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9673','ESCUELA PARTICULAR ARTURO MATTE LARRAIN','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9674','ESCUELA BASICA ALAS DE AGUILA','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('9676','ESCUELA PARTICULAR SAN MARCELO','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9680','COMPLEJO EDUC.STA.RITA DE CASIA-ANEXO 1','Metropolitana','LA PINTANA','Part. Subvencionado'),
('9684','COLEGIO SAN GREGORIO DE LA SALLE','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9685','ESCUELA BASICA PARTIC ESTRELLA DE CHILE','Metropolitana','LA GRANJA','Part. Subvencionado'),
('9686','LICEO TÉCNICO CLOTARIO BLEST RIFFO','Metropolitana','PEDRO AGUIRRE CERDA','Adm. Delegada'),
('9687','LICEO CHRISTA MC AULIFFE','Metropolitana','EL BOSQUE','Servicio Local'),
('9688','LICEO JUAN GOMEZ MILLAS','Metropolitana','EL BOSQUE','Servicio Local'),
('9690','CENTRO DUC.CARDENAL JOSE MARIA CARO','Metropolitana','LO ESPEJO','Servicio Local'),
('9693','LICEO POLITECNICO CIENCIA Y TECNOLOGIA','Metropolitana','LA CISTERNA','Servicio Local'),
('9694','INSTITUTO COMERCIAL PADRE ALBERTO HURTADO DE PEDRO AGUIRRE CERDA','Metropolitana','PEDRO AGUIRRE CERDA','Adm. Delegada'),
('9695','LICEO POLIVALENTE EUGENIO PEREIRA SALAS','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9697','LICEO POLIVALENTE','Metropolitana','LO ESPEJO','Servicio Local'),
('9698','ESCUELA BASICA AVIADORES','Metropolitana','EL BOSQUE','Servicio Local'),
('9699','COLEGIO NACIONES UNIDAS','Metropolitana','LA CISTERNA','Servicio Local'),
('9700','COLEGIO PALESTINO','Metropolitana','LA CISTERNA','Servicio Local'),
('9701','LICEO POLIVALENTE OLOF PALME','Metropolitana','LA CISTERNA','Servicio Local'),
('9702','ESCUELA BASICA MARIO ARCE GATICA','Metropolitana','EL BOSQUE','Servicio Local'),
('9703','ESCUELA ESPERANZA JOVEN','Metropolitana','LA CISTERNA','Servicio Local'),
('9704','ESCUELA LO VALLEDOR','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9705','ESCUELA BASICA SALOMON SACK','Metropolitana','LO ESPEJO','Servicio Local'),
('9706','ESCUELA BAS. OSCAR ENCALADA YOVANOVICH','Metropolitana','LA CISTERNA','Servicio Local'),
('9709','ESCUELA BLUE STAR COLLEGE','Metropolitana','LO ESPEJO','Servicio Local'),
('9710','ESCUELA BASICA SANTA ADRIANA','Metropolitana','LO ESPEJO','Servicio Local'),
('9713','COMPLEJO EDUCACIONAL FELIPE HERRERA LANE','Metropolitana','EL BOSQUE','Servicio Local'),
('9714','ESCUELA BASICA JOSE MARTI','Metropolitana','EL BOSQUE','Servicio Local'),
('9715','ESCUELA BASICA VILLA SANTA ELENA','Metropolitana','EL BOSQUE','Servicio Local'),
('9716','ESCUELA BASICA ACAPULCO','Metropolitana','LO ESPEJO','Servicio Local'),
('9717','ESCUELA CIUDAD DE LYON','Metropolitana','EL BOSQUE','Servicio Local'),
('9718','ESCUELA BASICA PAUL HARRIS','Metropolitana','EL BOSQUE','Servicio Local'),
('9719','ESCUELA BASICA','Metropolitana','LO ESPEJO','Servicio Local'),
('9720','COLEGIO HERNAN OLGUIN','Metropolitana','LO ESPEJO','Servicio Local'),
('9721','ESCUELA NEMESIO ANTUNEZ','Metropolitana','EL BOSQUE','Servicio Local'),
('9722','LICEO PORTAL DE LA CISTERNA','Metropolitana','LA CISTERNA','Servicio Local'),
('9726','LICEO TENIENTE FRANCISCO MERY AGUIRRE','Metropolitana','LO ESPEJO','Servicio Local'),
('9727','ESCUELA CIUDAD DE BARCELONA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9728','ESCUELA DIFERENCIAL PARA NINOS SORDOS','Metropolitana','EL BOSQUE','Servicio Local'),
('9729','ESCUELA VILLA SUR','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9730','COLEGIO ANTU','Metropolitana','LA CISTERNA','Servicio Local'),
('9733','ESCUELA BASICA CLARA  ESTRELLA','Metropolitana','LO ESPEJO','Servicio Local'),
('9734','ESCUELA  RAUL SAEZ SAEZ','Metropolitana','LO ESPEJO','Servicio Local'),
('9736','ESCUELA BASICA BERNARDO O´HIGGINS','Metropolitana','LO ESPEJO','Servicio Local'),
('9738','COLEGIO PARQUE LAS AMERICAS','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9740','ESCUELA BASICA REPUBLICA DE LAS FILIPINAS','Metropolitana','LO ESPEJO','Servicio Local'),
('9741','ESCUELA BASICA COEDUCACIONAL','Metropolitana','LO ESPEJO','Servicio Local'),
('9747','C.E.I.A.PEDRO AGUIRRE CERDA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9750','COLEGIO LO ESPEJO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9754','INSTITUTO COMERCIAL PARTICULAR LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9757','CENTRO EDUCACIONAL SANTA CLARA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9758','COLEGIO SANTA ISABEL DE HUNGRIA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9759','LICEO LAURA VICUNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9766','COLEGIO SANTA MARIA DE LOS ANGELES','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9767','LICEO MADRE CECILIA LAZZERI','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9768','ESCUELA Y LICEO LIAHONA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9771','CHILEAN EAGLES COLLEGE - LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9772','ESCUELA ESPECIAL NTA SENORA DE LAS PENAS','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9778','ESCUELA JOSE ABELARDO NUNEZ Nº 1','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9779','CENTRO EDUCACIONAL SANTA ROSA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9780','COLEGIO TENIENTE DAGOBERTO GODOY','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9781','CENTRO POLITECNICO PARTICULAR SAN RAMON','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9784','LICEO TÉCNICO INDUSTRIAL LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9786','ROSA MARCKMANN DE GONZALEZ','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9788','ESCUELA PARTICULAR GRACIELA L.DE IBANEZ','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9789','ESCUELA PARTICULAR PABLO GOYENECHE IVER','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9796','ESC. PART.ADVENTISTA BUENAVENTURA','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9797','COLEGIO ADVENTISTA LA CISTERNA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9799','COMPLEJO EDUC.PART.MONSENOR LUIS A.PEREZ','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9800','ESCUELA BAS. ROSA ELVIRA MATTE DE PRIETO','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9801','COLEGIO POLIV. SAINT ORLAND','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9803','ESCUELA PARTICULAR HISPANO AMERICANO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9804','ESCUELA PABLO DE TARSO','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9805','ESCUELA PARTICULAR CAMPANITA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9807','ESCUELA PARTICULAR LOCARNO','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9808','ESCUELA PARTICULAR GUIA ESTUDIANTIL','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9809','ESCUELA PARTICULAR SAINT PHILLIP OF NERY','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9810','LICEO POLITECNICO PART.SAGRADO CORAZON','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9811','ESCUELA PART. REPUBLICA ALEMANIA FEDERAL','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9816','ESCUELA PARTICULAR STA.MARIA MAZZARELLO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9817','COLEGIO PARTICULAR KENNEDY','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9824','COMPLEJO EDUCACIONAL STELLA MARIS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9825','ESCUELA PARTICULAR ESPECIAL G.MISTRAL','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9826','ESCUELA PARTICULAR LOS CAPULLITOS','Metropolitana','LA CISTERNA','Part. Pagado'),
('9827','COLEGIO IDOP LIMITADA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9828','COLEGIO SOL DE CHILE','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9829','COLEGIO BICENTENARIO DE EXCELENCIA MIGUEL DE CERVANTES','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9834','COLEGIO POLITEC. MARIA GRISELDA VALLE S.','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9841','ESCUELA PARTICULAR MIGUEL DE CERVANTES','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9842','ESCUELA PARTICULAR NUESTRA INFANCIA','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9844','COLEGIO EL ALMENDRO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9845','COLEGIO GRACE SCHOOL','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9847','ESCUELA PARTICULAR KAROL C.DE CRACOVIA','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9850','ESCUELA PARTICULAR LOS LAGOS CHILE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9852','ESCUELA PARTICULAR VILLA EL SOL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('9853','COLEGIO POLIV. SAINT TRINITY COLLEGE','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('9855','COLEGIO PRINCESS ANNE SCHOOL','Metropolitana','LA CISTERNA','Part. Pagado'),
('9859','COLEGIO PARTICULAR VILLA JESUS','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9860','LICEO BICENTENARIO INDUSTRIAL DE ELECTROTECNIA RAMON B','Metropolitana','LA CISTERNA','Adm. Delegada'),
('9861','CENTRO EDUC.MUNIC. DR. AMADOR NEGHME RODRIGUEZ','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9862','LICEO BICENTENARIO POLIVALENTE A N°71 GUILLERMO FELIU CRUZ','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9863','LICEO SANTIAGO BUERAS Y AVARIA','Metropolitana','MAIPÚ','Servicio Local'),
('9864','LICEO JOSE IGNACIO ZENTENO','Metropolitana','MAIPÚ','Servicio Local'),
('9865','LICEO POLIVALENTE DR. LUIS VARGAS SALCEDO','Metropolitana','CERRILLOS','Servicio Local'),
('9866','LICEO COMERCIAL B-72','Metropolitana','ESTACIÓN CENTRAL','Adm. Delegada'),
('9867','CENTRO DE EDUC. TECN.PROFESIONAL CODEDUC','Metropolitana','MAIPÚ','Servicio Local'),
('9869','ESCUELA BASICA REPUBLICA DE FRANCIA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9870','ESCUELA BASICA CONDORES DE PLATA','Metropolitana','CERRILLOS','Servicio Local'),
('9872','ESCUELA BASICA PROF.RAMON DEL RIO','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9873','ESCUELA BASICA PACTO ANDINO','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9874','ESCUELA LOTHAR KOMMER BRUGER','Metropolitana','CERRILLOS','Servicio Local'),
('9875','ESCUELA CERRILLOS','Metropolitana','CERRILLOS','Servicio Local'),
('9876','ESCUELA GENERAL SAN MARTIN','Metropolitana','MAIPÚ','Servicio Local'),
('9877','ESCUELA GENERAL OHIGGINS','Metropolitana','MAIPÚ','Servicio Local'),
('9878','ESCUELA PRESIDENTE RIESCO ERRAZURIZ','Metropolitana','MAIPÚ','Servicio Local'),
('9879','ESCUELA BASICA CAROLINA VERGARA AYARES','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9880','ESCUELA  BASICA  ESTADO  DE  PALESTINA','Metropolitana','ESTACIÓN CENTRAL','Servicio Local'),
('9881','ESCUELA VICENTE REYES PALAZUELOS','Metropolitana','MAIPÚ','Servicio Local'),
('9882','ESCUELA J.PRIETO VIAL','Metropolitana','CERRILLOS','Servicio Local'),
('9883','ESCUELA BÁSICA N 263 RAMON FREIRE','Metropolitana','MAIPÚ','Servicio Local'),
('9884','ESCUELA LEON HUMBERTO VALENZUELA','Metropolitana','MAIPÚ','Servicio Local'),
('9886','ESCUELA ESTRELLA REINA DE CHILE','Metropolitana','CERRILLOS','Servicio Local'),
('9887','LICEO EL LLANO DE MAIPU','Metropolitana','MAIPÚ','Servicio Local'),
('9888','ESCUELA SANTA ADELA','Metropolitana','CERRILLOS','Servicio Local'),
('9889','LICEO REINO DE DINAMARCA','Metropolitana','MAIPÚ','Servicio Local'),
('9890','ESCUELA TOMAS VARGAS','Metropolitana','MAIPÚ','Servicio Local'),
('9891','REPUBLICA DE GUATEMALA','Metropolitana','MAIPÚ','Servicio Local'),
('9892','ESCUELA LAS AMERICAS','Metropolitana','MAIPÚ','Servicio Local'),
('9893','ESCUELA ESPECIAL ANDALUE','Metropolitana','MAIPÚ','Servicio Local'),
('9895','ESCUELA BASICA REINA DE SUECIA','Metropolitana','MAIPÚ','Servicio Local'),
('9896','LICEO MAIPÚ DE LAS ARTES Y LA TECNOLOGÍA','Metropolitana','MAIPÚ','Servicio Local'),
('9897','LICEO BICENTENARIO DE EXCELENCIA POLITÉCNICO HANNOVER','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9900','COLEGIO BICENTENARIO DE EXCELENCIA POLITECNICO ALEMAN ALBERT EINSTEIN','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9901','ESCUELA PARTICULAR FRANZ LISZT','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9902','ESCUELA PARTICULAR ESPECIAL DON ORIONE','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9903','COLEGIO LOS CONQUISTADORES','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9905','LICEO SAN PEDRO POVEDA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9906','COLEGIO INSTITUTO AMERICA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9907','COLEGIO POLIVALENTE CAMILO HENRIQUEZ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9909','CENTRO EDUCACIONAL PIAMARTINO CAROLINA LLONA DE CUEVAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9910','COLEGIO PARTICULAR SAN FELIX','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9911','COLEGIO DE LA PROVIDENCIA C.LARRAIN DE I','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9912','COLEGIO PART. ASCENSION NICOL','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9913','COLEGIO ESC.  JOSE MANSO DE VELASCO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9916','ESCUELA DE PARVULOS LOS PAISES BAJOS','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9917','COLEGIO POLIVALENTE PATRICIO MEKIS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9919','COLEGIO PARTICULAR MATER DEI','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9920','ESC. BASICA DIVINO JESUS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9922','ESCUELA PARTICULAR HOLANDA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9924','COLEGIO ALBERTO PEREZ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9926','COLEGIO SOFIA INFANTE HURTADO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9928','ESCUELA PARTICULAR AMANECER','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9930','ESCUELA PARTICULAR JOSE ANTONIO LECAROS','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9937','LICEO MATER PURISSIMA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9939','ESCUELA BASICA CAMPOS DE MAIPU-CERRILLOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9940','ESCUELA LICEO MADRE VICENCIA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9941','COLEGIO PARTICULAR DE ASIS','Metropolitana','MAIPÚ','Part. Pagado'),
('9942','ESCUELA, COLEGIO POLITEC.H.DE MAGALLANES','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9943','ESCUELA DE PARVULOS ENANO GROUMPY','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9945','COLEGIO ELLEN COLLEGE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9946','ESCUELA PARTICULAR LA MONTANA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9947','COLEGIO INDUSTRIAL PART. DON ORIONE','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9948','ESCUELA PARTICULAR SAINT RODRIC COLLEGE','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9950','COLEGIO EL REDENTOR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9953','CENTRO EDUCACIONAL SAN ANDRES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9955','COLEGIO ROSITA SANCHEZ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9957','LICEO INDUSTRIAL ALBERTO WIDMER','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9959','COMPLEJO EDUCACIONAL MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9960','ESCUELA PARTICULAR VILLA ESPANA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('9963','COLEGIO PARTICULAR ESPECIAL JUAN XXIII','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9967','ESCUELA PARTICULAR RUBEN DARIO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9968','ESCUELA ESPECIAL EDUCACIONAL AGAZZI','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9972','COLEGIO SAINT MAURICE S','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9973','COLEGIO SANTA URSULA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('9979','COLEGIO PETER COLLEGE','Metropolitana','CERRILLOS','Part. Subvencionado'),
('9981','LICEO INDUSTRIAL DOMINGO MATTE PEREZ','Metropolitana','MAIPÚ','Adm. Delegada'),
('9982','LICEO COMERCIAL MOLINA LAVIN','Metropolitana','QUINTA NORMAL','Adm. Delegada'),
('9985','LICEO GUILLERMO LABARCA HUBERTSON','Metropolitana','QUINTA NORMAL','Municipal'),
('9986','LICEO POLITECNICO CAPITAN DE CORBETA INFANTE DE MARINA PEDRO GONZÁLEZ PACHECO','Metropolitana','QUINTA NORMAL','Municipal'),
('9987','ESCUELA PLATON','Metropolitana','QUINTA NORMAL','Municipal'),
('9991','ESCUELA ABATE MOLINA','Metropolitana','QUINTA NORMAL','Municipal'),
('9992','ESCUELA DIEGO PORTALES','Metropolitana','QUINTA NORMAL','Municipal'),
('9993','ESCUELA INGLATERRA','Metropolitana','QUINTA NORMAL','Municipal'),
('9994','ESCUELA ANGELMO','Metropolitana','QUINTA NORMAL','Municipal'),
('9995','ESCUELA INSIGNE GABRIELA','Metropolitana','QUINTA NORMAL','Municipal'),
('9996','ESCUELA ESPANA','Metropolitana','QUINTA NORMAL','Municipal'),
('9998','ESCUELA LO FRANCO','Metropolitana','QUINTA NORMAL','Municipal'),
('9999','ESCUELA ANTUMALAL','Metropolitana','QUINTA NORMAL','Municipal'),
('10000','ESCUELA CALICANTO','Metropolitana','QUINTA NORMAL','Municipal'),
('10001','ESCUELA MEMBRILLAR','Metropolitana','QUINTA NORMAL','Municipal'),
('10005','ESCUELA BASICA MUNICIPAL GRENOBLE','Metropolitana','QUINTA NORMAL','Municipal'),
('10006','ESCUELA REPUBLICA DE LA INDIA','Metropolitana','QUINTA NORMAL','Municipal'),
('10010','MUSTAFA KEMAL ATATURK','Metropolitana','LO PRADO','Servicio Local'),
('10012','ESCUELA GIL DE CASTRO','Metropolitana','QUINTA NORMAL','Municipal'),
('10014','ESCUELA PARTICULAR ANDRES BELLO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10015','ESCUELA OLGA NAVARRO SEPULVEDA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10018','ESCUELA PARTICULAR JOSE JOAQUIN PEREZ','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10019','ESCUELA PARTICULAR SAN JOSE SCHOOL','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('10021','ESCUELA PARTICULAR VICTOR HUGO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10023','LICEO ALBERTO HURTADO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10026','ESCUELA PARTICULAR MONTE GRANDE','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10028','ESCUELA N°1124 ALIANZA AMERICANA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10030','LICEO POLIV.SAN JOSE DE LA PRECIOSA SANG','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10032','ESCUELA BASICA PARTICULAR  Nº 488 `ZENON TORREALBA`','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10035','ESCUELA PARTICULAR NUEVO HORIZONTE','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10036','ESCUELA PARTICULAR PDTE. ABRAHAM LINCOLN','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10041','COLEGIO SAINT MARK','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10042','COLEGIO BICENTENARIO ELVIRA HURTADO DE MATTE DE SANTIAGO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10044','CENTRO EDUCACIONAL ALBERTO HURTADO','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10046','ESCUELA PARTICULAR SAGRADA FAMILIA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10052','LICEO POLIVALENTE SAN FRANCISCO','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10056','ESCUELA DIFERENCIAL LOS LIRIOS','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10058','COLEGIO POLIVALENTE PRINCIPE DE GALES','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('10063','ESCUELA PARTICULAR CARMEN CHACON','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10064','ESCUELA PARTICULAR MARIA CRISTINA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10069','COLEGIO MARQUEL','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('10073','LICEO BICENTENARIO INDUSTRIAL VICENTE PEREZ ROSALES','Metropolitana','QUINTA NORMAL','Adm. Delegada'),
('10074','ESCUELA ALIANZA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10075','LICEO POLIVALENTE LOS HEROES DE LA CONCEPCIÓN','Metropolitana','CERRO NAVIA','Servicio Local'),
('10076','COMPLEJO EDUCACIONAL PEDRO PRADO','Metropolitana','LO PRADO','Servicio Local'),
('10077','LICEO CENTRO EXPERIMENTAL PUDAHUEL CAREN','Metropolitana','PUDAHUEL','Servicio Local'),
('10080','ESCUELA TENIENTE HERNAN MERINO CORREA','Metropolitana','PUDAHUEL','Servicio Local'),
('10081','ESCUELA ESTRELLA DE CHILE','Metropolitana','PUDAHUEL','Servicio Local'),
('10083','ESCUELA PRESIDENTE ROOSEVELT','Metropolitana','CERRO NAVIA','Servicio Local'),
('10085','ESCUELA ESTADO DE FLORIDA','Metropolitana','PUDAHUEL','Servicio Local'),
('10086','ESCUELA REPUBLICA DE ITALIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10087','LICEO REPUBLICA DE CROACIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10088','ESCUELA HERMINDA DE LA VICTORIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10089','ESCUELA JAIME GOMEZ GARCIA','Metropolitana','LO PRADO','Servicio Local'),
('10090','ESCUELA ALEXANDER GRAHAM BELL','Metropolitana','PUDAHUEL','Servicio Local'),
('10091','LICEO PROFESORA GLADYS VALENZUELA','Metropolitana','LO PRADO','Servicio Local'),
('10092','ESCUELA GOLDA MEIR','Metropolitana','LO PRADO','Servicio Local'),
('10093','ESCUELA MILLAHUE','Metropolitana','CERRO NAVIA','Servicio Local'),
('10095','ESCUELA IGNACIO CARRERA PINTO','Metropolitana','LO PRADO','Servicio Local'),
('10097','ESCUELA MARISCAL DE AYACUCHO','Metropolitana','LO PRADO','Servicio Local'),
('10098','ESCUELA PROVINCIA DE ARAUCO','Metropolitana','CERRO NAVIA','Servicio Local'),
('10099','ESCUELA GENERAL RENE ESCAURIAZA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10100','ESCUELA EL SALITRE','Metropolitana','PUDAHUEL','Servicio Local'),
('10102','ESCUELA ALBERT EINSTEIN','Metropolitana','PUDAHUEL','Servicio Local'),
('10103','ESCUELA SOR TERESA DE LOS ANDES','Metropolitana','LO PRADO','Servicio Local'),
('10104','ESCUELA MONSENOR CARLOS OVIEDO','Metropolitana','PUDAHUEL','Servicio Local'),
('10105','ESCUELA FEDERICO ACEVEDO SALAZAR','Metropolitana','CERRO NAVIA','Servicio Local'),
('10106','LICEO BICENTENARIO POETA PABLO NERUDA','Metropolitana','LO PRADO','Servicio Local'),
('10107','ESCUELA BASICA PAULO FREIRE','Metropolitana','CERRO NAVIA','Servicio Local'),
('10108','ESCUELA LEONARDO DA VINCI','Metropolitana','CERRO NAVIA','Servicio Local'),
('10109','ESCUELA DOCTOR TREVISO GIRARDI TONELLI','Metropolitana','CERRO NAVIA','Servicio Local'),
('10113','ESCUELA ELVIRA SANTA CRUZ OSSA','Metropolitana','PUDAHUEL','Servicio Local'),
('10114','ESCUELA BASICA N°389 REPUBLICA DE ESTADOS UNIDOS','Metropolitana','LO PRADO','Servicio Local'),
('10116','COLEGIO NEPTUNO','Metropolitana','CERRO NAVIA','Servicio Local'),
('10117','ESCUELA MARIA LUISA BOMBAL','Metropolitana','CERRO NAVIA','Servicio Local'),
('10119','ESCUELA POETA VICENTE HUIDOBRO','Metropolitana','LO PRADO','Servicio Local'),
('10120','LICEO DE ADULTOS ALBERTO GALLEGUILLOS J.','Metropolitana','PUDAHUEL','Servicio Local'),
('10121','ESCUELA CIUDAD SANTO DOMINGO DE GUZMAN','Metropolitana','CERRO NAVIA','Servicio Local'),
('10122','ESCUELA PROF. MANUEL GUERRERO CEBALLOS','Metropolitana','CERRO NAVIA','Servicio Local'),
('10123','ESCUELA BASICA MELVIN JONES','Metropolitana','PUDAHUEL','Servicio Local'),
('10124','ESCUELA SAN DANIEL','Metropolitana','PUDAHUEL','Servicio Local'),
('10125','ESCUELA SARGENTO CANDELARIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10126','COMPLEJO EDUCACIONAL CERRO NAVIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('10127','ESC.DE EDUCACION DIFERENCIAL QUILLAHUE','Metropolitana','LO PRADO','Servicio Local'),
('10128','ESCUELA CENTRO EDUC.INTEGRAL DE ADULTOS','Metropolitana','LO PRADO','Servicio Local'),
('10130','LICEO CIUDAD DE BRASILIA','Metropolitana','PUDAHUEL','Servicio Local'),
('10133','ESCUELA BASICA G-N°320 LIPANGUE','Metropolitana','LAMPA','Municipal'),
('10134','ESC.COMODORO ARTURO MERINO BENITEZ','Metropolitana','PUDAHUEL','Servicio Local'),
('10135','ESCUELA LO BOZA','Metropolitana','PUDAHUEL','Servicio Local'),
('10140','ESCUELA PARTICULAR FRINGS COLLEGE','Metropolitana','LO PRADO','Part. Subvencionado'),
('10142','ESCUELA BASICA PARTICULAR N°811 DRA.VICTORIA GARCIA','Metropolitana','LO PRADO','Part. Subvencionado'),
('10143','ESCUELA PARTICULAR ESPANA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10147','ESCUELA PARTICULAR BABILONIA','Metropolitana','LO PRADO','Part. Subvencionado'),
('10149','ESCUELA PARTICULAR RAPA NUI','Metropolitana','LO PRADO','Part. Subvencionado'),
('10151','COLEGIO CRISTIAN AND CAREN SCHOOL','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10152','ESCUELA PARTICULAR ANDANTINO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10155','ESCUELA CHARLES SCHOOL-DIURNA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10156','ESCUELA JARDIN LO PRADO','Metropolitana','LO PRADO','Part. Subvencionado'),
('10157','COLEGIO MINISTRO DIEGO PORTALES','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10158','COLEGIO BICENTENARIO SAN DAMIAN DE MOLOKAI','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10159','ESCUELA PARTICULAR ROBERT KENNEDY','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10160','ESCUELA BAS. COLEGIO BAU','Metropolitana','LO PRADO','Part. Subvencionado'),
('10162','LICEO TENIENTE DAGOBERTO GODOY NO.3','Metropolitana','LO PRADO','Part. Subvencionado'),
('10164','COLEGIO SAN FRANCISCO JAVIER','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10167','ESCUELA BASICA N°1058 SANTA BEATRIZ','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10168','ESCUELA PARTICULAR SAN VICENTE FERRER','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10171','ESCUELA PARTICULAR VILLA LOURDES','Metropolitana','LO PRADO','Part. Subvencionado'),
('10172','ESC BAS PART CENTRO EDUCACIONAL SN PABLO','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10173','ESCUELA PART. SUNS SCHOOL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10176','ESCUELA PARTICULAR ESPECIAL RENACER','Metropolitana','LO PRADO','Part. Subvencionado'),
('10182','ESCUELA  BASICA  N° 912 ELLEN  COLLEGE','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10183','ESCUELA PARTICULAR CARLOS PEZOA VELIZ','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10186','ESCUELA PARTICULAR LA FRONTERA','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10187','COLEGIO BICENTENARIO MADRE ANA EUGENIA','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10191','ESCUELA PARTICULAR LA CIUDAD EDUCATIVA','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('10193','ESCUELA BASICA COLEGIO SAINT ORLAND N 3','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('10195','ESCUELA DE PARVULOS N°1168 PINOCHO','Metropolitana','LO PRADO','Part. Pagado'),
('10196','LICEO INDUSTRIAL BICENTENARIO BENJAMIN DAVILA LARRAIN','Metropolitana','RENCA','Adm. Delegada'),
('10197','ESCUELA JUANA DE LESTONAC','Metropolitana','RENCA','Municipal'),
('10199','LICEO POLIVALENTE A80 PRESIDENTE JOSE MANUEL BALMACEDA','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('10200','ESCUELA BASICA ISABEL LE BRUN','Metropolitana','RENCA','Municipal'),
('10201','LICEO THOMAS ALVA EDISON','Metropolitana','RENCA','Municipal'),
('10202','ESCUELA DOMINGO SANTA MARIA GONZALEZ','Metropolitana','RENCA','Municipal'),
('10204','ESCUELA CAPITAN JOSE LUIS ARANEDA','Metropolitana','RENCA','Municipal'),
('10205','ESCUELA GENERAL MANUEL BULNES PRIETO','Metropolitana','RENCA','Municipal'),
('10207','ESCUELA REBECA MATTE BELLO','Metropolitana','RENCA','Municipal'),
('10210','LICEO GENERAL ALEJANDRO GOROSTIAGA ORREGO','Metropolitana','RENCA','Municipal'),
('10212','ESCUELA JUANA ATALA DE HIRMAS','Metropolitana','RENCA','Municipal'),
('10216','ESC. BASICA MONSERRAT ROBERT DE GARCIA','Metropolitana','RENCA','Municipal'),
('10217','COLEGIO PARTICULAR HELENICO','Metropolitana','RENCA','Part. Subvencionado'),
('10219','COLEGIO CORAZON DE JESUS DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('10220','COLEGIO PRESIDENTE ALESSANDRI','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10221','COLEGIO PARTICULAR CHARLES DARWIN','Metropolitana','RENCA','Part. Subvencionado'),
('10223','LICEO SANTA TERESITA','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10224','COLEGIO ARTURO TORO AMOR','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('10225','ESCUELA PARTIC. COLEGIO BALMACEDA-RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('10226','ESCUELA PARTICULAR SAN GENARO','Metropolitana','RENCA','Part. Subvencionado'),
('10228','ESCUELA PARTICULAR PRIMITIVA ECHEVERRIA','Metropolitana','RENCA','Part. Subvencionado'),
('10229','ESCUELA PARTICULAR JOSE BERNARDO SUAREZ','Metropolitana','RENCA','Part. Subvencionado'),
('10232','COLEG. POLIV. SANTA MARIA DE LA PROVIDENCIA','Metropolitana','RENCA','Part. Subvencionado'),
('10233','ESCUELA PARTICULAR SAN FIDEL','Metropolitana','RENCA','Part. Subvencionado'),
('10234','ESCUELA ESPECIAL PARTICULAR ESPERANZA','Metropolitana','RENCA','Part. Subvencionado'),
('10235','ESCUELA BASICA  N° 878  LOS ACACIOS','Metropolitana','RENCA','Part. Subvencionado'),
('10239','ESCUELA ESTADO DE MICHIGAN','Metropolitana','QUILICURA','Servicio Local'),
('10240','ESCUELA LUIS CRUZ MARTINEZ','Metropolitana','QUILICURA','Servicio Local'),
('10241','ESCUELA BASICA EL MANIO','Metropolitana','QUILICURA','Servicio Local'),
('10245','PARROQUIAL NUESTRA SEÑORA DEL CARMEN DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('10246','COLEGIO POLIV. SANTA MARIA','Metropolitana','QUILICURA','Part. Subvencionado'),
('10247','ESCUELA BASICA PART PAULA JARAQUEMADA','Metropolitana','QUILICURA','Part. Subvencionado'),
('10248','LICEO INSTITUTO TECNOLOGICO Y COMERCIAL RECOLETA-INTECO','Metropolitana','RECOLETA','Adm. Delegada'),
('10250','CENTRO EDUCACIONAL BICENTENARIO DE EXCELENCIA DE HUECHURABA','Metropolitana','HUECHURABA','Corp. Municipal'),
('10251','LICEO POETA FEDERICO GARCIA LORCA','Metropolitana','CONCHALÍ','Servicio Local'),
('10252','LICEO ARTURO PEREZ CANTO','Metropolitana','RECOLETA','Corp. Municipal'),
('10253','LICEO POLIV. ABDON CIFUENTES','Metropolitana','CONCHALÍ','Servicio Local'),
('10254','CENTRO EDUCACIONAL JOSE MIGUEL CARRERA','Metropolitana','RECOLETA','Corp. Municipal'),
('10255','COMPLEJO EDUCACIONAL JUANITA FERNANDEZ SOLAR','Metropolitana','RECOLETA','Corp. Municipal'),
('10257','ESCUELA SARGENTO 2. DANIEL REBOLLEDO','Metropolitana','RECOLETA','Corp. Municipal'),
('10259','LICEO ALBERTO BLEST GANA','Metropolitana','CONCHALÍ','Servicio Local'),
('10260','ESCUELA UNESCO','Metropolitana','CONCHALÍ','Servicio Local'),
('10262','ESCUELA ESPANA','Metropolitana','RECOLETA','Corp. Municipal'),
('10263','ESCUELA D-114','Metropolitana','CONCHALÍ','Servicio Local'),
('10264','ESCUELA SOL NACIENTE','Metropolitana','CONCHALÍ','Servicio Local'),
('10265','ESCUELA HORACIO JOHNSON GANA','Metropolitana','CONCHALÍ','Servicio Local'),
('10266','ESCUELA DRA.ELOISA DIAZ INSUNZA','Metropolitana','CONCHALÍ','Servicio Local'),
('10267','ESCUELA ESCRITORA MARCELA PAZ','Metropolitana','RECOLETA','Corp. Municipal'),
('10268','ESCUELA PUERTO RICO','Metropolitana','RECOLETA','Corp. Municipal'),
('10269','LICEO MUNC.ALMIRANTE GALVARINO RIVEROS','Metropolitana','CONCHALÍ','Servicio Local'),
('10270','CENTRO EDUC.ESCRITORES DE CHILE','Metropolitana','RECOLETA','Corp. Municipal'),
('10271','ESCUELA ARAUCARIAS DE CHILE','Metropolitana','CONCHALÍ','Servicio Local'),
('10272','ESCUELA BASICA CARLOS PRATS G.','Metropolitana','HUECHURABA','Corp. Municipal'),
('10273','ESCUELA VALLE DEL INCA','Metropolitana','CONCHALÍ','Servicio Local'),
('10277','ESCUELA ADELAIDA LA FETRA','Metropolitana','HUECHURABA','Corp. Municipal'),
('10278','ESCUELA PEDRO AGUIRRE CERDA','Metropolitana','CONCHALÍ','Servicio Local'),
('10279','ESCUELA ALLIPEN','Metropolitana','CONCHALÍ','Servicio Local'),
('10280','ESCUELA BÁSICA POETA EUSEBIO LILLO','Metropolitana','CONCHALÍ','Servicio Local'),
('10281','ESCUELA ATENEA','Metropolitana','CONCHALÍ','Servicio Local'),
('10282','ESCUELA LUIS GALDAMES','Metropolitana','INDEPENDENCIA','Corp. Municipal'),
('10283','ESCUELA AVIADOR DAGOBERTO GODOY F.','Metropolitana','CONCHALÍ','Servicio Local'),
('10285','ESCUELA SANTA VICTORIA DE HUECHURABA','Metropolitana','HUECHURABA','Corp. Municipal'),
('10288','ESCUELA BASICA LIKAN-ANTAI','Metropolitana','CONCHALÍ','Servicio Local'),
('10290','ESCUELA LAS CANTERAS','Metropolitana','HUECHURABA','Corp. Municipal'),
('10291','ESCUELA VICTOR CUCCUINI','Metropolitana','RECOLETA','Corp. Municipal'),
('10293','ESCUELA ESP. HUMBERTO ARANDA IRRIBARREN','Metropolitana','CONCHALÍ','Servicio Local'),
('10300','ESCUELA MARTA COLVIN','Metropolitana','RECOLETA','Corp. Municipal'),
('10301','ESCUELA CAMILO HENRIQUEZ','Metropolitana','CONCHALÍ','Servicio Local'),
('10302','ESCUELA ANNE ELEONOR ROOSEVELT','Metropolitana','RECOLETA','Corp. Municipal'),
('10305','ESCUELA SANTIAGO DE GUAYAQUIL','Metropolitana','HUECHURABA','Corp. Municipal'),
('10306','ESCUELA MUN.HERMANA MARIA GORETTI','Metropolitana','RECOLETA','Corp. Municipal'),
('10307','ESCUELA RAFAEL VALDIVIESO','Metropolitana','RECOLETA','Corp. Municipal'),
('10309','ESCUELA EDUC.DIF. STA. TERESA DE AVILA','Metropolitana','RECOLETA','Corp. Municipal'),
('10313','COLEGIO POLIV. ALEJANDRO FLORES','Metropolitana','RECOLETA','Part. Subvencionado'),
('10315','COLEGIO CRISTOBAL COLON','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('10320','LICEO AVENIDA RECOLETA','Metropolitana','RECOLETA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
