-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 21 de 31 | filas 8001-8400
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('16630','CENTRO EDUCATIVO DE LENGUAJE ANDALEN','Maule','CURICÓ','Part. Subvencionado'),
('16631','ESCUELA DE LENGUAJE TORREBLANCA','Maule','SAN JAVIER','Part. Subvencionado'),
('16633','ESCUELA DE LENGUAJE ABEJITA MAYA','Maule','TALCA','Part. Subvencionado'),
('16634','COLEGIO POLITECNICO AQUELARRE','Maule','TENO','Part. Subvencionado'),
('16636','ESCUELA DE LENGUAJE MILLAHUE','Maule','TALCA','Part. Subvencionado'),
('16639','ESCUELA INTY LLAN','Maule','TALCA','Part. Subvencionado'),
('16640','ESCUELA DE LENGUAJE SAN VALENTIN SUR ORIENTE','Maule','TALCA','Part. Subvencionado'),
('16642','COLEGIO ANTAMARO','Maule','LINARES','Part. Subvencionado'),
('16644','COLEGIO LEONARDO DA VINCI','Maule','SAN JAVIER','Part. Subvencionado'),
('16645','COLEGIO LAS ESTRELLITAS','Maule','COLBÚN','Part. Subvencionado'),
('16646','ESCUELA DE LENGUAJE ARCOIRIS','Maule','MOLINA','Part. Subvencionado'),
('16647','COLEGIO ESPECIAL CRECER','Maule','TALCA','Part. Subvencionado'),
('16649','ESCUELA ESPECIAL SAN VICENTE','Maule','TENO','Part. Subvencionado'),
('16652','CENTRO EDUCATIVO MACHU PICCHU','Maule','CURICÓ','Part. Subvencionado'),
('16654','ESCUELA DIFERENCIAL LOS GERANIOS','Maule','TALCA','Part. Subvencionado'),
('16656','LICEO VICTORIA','Maule','TALCA','Part. Subvencionado'),
('16658','LICEO NUESTRA SENORA DE LAS MERCEDES','Maule','CAUQUENES','Part. Subvencionado'),
('16659','ESCUELA DE LENGUAJES EDUCALEN','Maule','PENCAHUE','Part. Subvencionado'),
('16661','ESCUELA DE PARVULOS PRINCIPITO DE SANTA ANA','Maule','SAGRADA FAMILIA','Part. Subvencionado'),
('16662','JARDIN INFANTIL CASTILLO PALABRAS MAGICAS','Maule','TALCA','Part. Subvencionado'),
('16663','ESCUELA DE LENGUAJE CARACOLA','Maule','TALCA','Part. Subvencionado'),
('16664','ESCUELA DE PARVULOS SAN JOSE DE CALASANZ','Maule','TALCA','Part. Subvencionado'),
('16665','JARDIN INFANTIL SONRISAS','Maule','TALCA','Part. Subvencionado'),
('16666','ESCUELA DE LENGUAJE RENACER','Maule','TALCA','Part. Subvencionado'),
('16667','ESCUELA ESPECIAL DE LENGUAJE VICTORIA','Maule','TALCA','Part. Subvencionado'),
('16668','ESCUELA ESPECIAL DE LENGUAJE NINO JESUS','Maule','CAUQUENES','Part. Subvencionado'),
('16671','ESCUELA ESPECIAL DE LENGUAJE SAN ESTEBAN','Maule','TALCA','Part. Subvencionado'),
('16672','ESCUELA ESPECIAL DE LENGUAJE ALHUE','Maule','TALCA','Part. Subvencionado'),
('16673','COLEGIO CLUB DE LEONES TALCA','Maule','TALCA','Part. Subvencionado'),
('16675','ESCUELA ESPEC. DE LENGUAJE ALFREDO GIDI JALIL','Maule','PARRAL','Part. Subvencionado'),
('16676','LICEO COMPLEJO EDUCACIONAL JAVIERA CARRERA','Maule','TALCA','Corp. Municipal'),
('16677','COLEGIO IRIS RETAMAL','Maule','RETIRO','Part. Subvencionado'),
('16678','COLEGIO LOS AGUSTINOS EDUCA Y DEPORTE','Maule','TALCA','Part. Subvencionado'),
('16679','CTRO. EDUCACIONAL Y ESC. DE LENGUAJE PABLO FR','Maule','SAN JAVIER','Part. Subvencionado'),
('16680','LICEO TECNICO PROF.AGRARIO LUXEMBURGO DE RAUC','Maule','RAUCO','Part. Subvencionado'),
('16682','COL GRAL. DE DIVISION EMILIO SOTOMAYOR BAEZA','Maule','LINARES','Part. Subvencionado'),
('16683','ESCUEA ESPECIAL DE LENGUAJE MILLARAY','Maule','CURICÓ','Part. Subvencionado'),
('16685','COLEGIO HENRI CETTY','Maule','MOLINA','Part. Subvencionado'),
('16686','ESCUELA ESPECIAL DE LENGUAJE REY LEON','Maule','TALCA','Part. Subvencionado'),
('16687','CENTRO PEDAGOGICO PREESCOLAR VALLE DEL MAULE','Maule','MAULE','Part. Subvencionado'),
('16689','COLEGIO ESPECIAL DE DISCAPACIDADES MULTIPLES','Maule','TALCA','Part. Subvencionado'),
('16690','COLEGIO SUYAI','Maule','MAULE','Part. Subvencionado'),
('16692','ESCUELA ESPECIAL DE LENGUAJE GIRASOL','Maule','SAN JAVIER','Part. Subvencionado'),
('16693','ESCUELA ESPECIAL DE LENGUAJE SEMBRANDO PALABR','Maule','CURICÓ','Part. Subvencionado'),
('16694','ESCUELA DE LENGUAJE REMOLINO','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16695','ESCUELA BASICA DE ADMINISTRACION Y COMERCIO','Maule','CURICÓ','Part. Subvencionado'),
('16696','ESCUELA HOSPITAL LINARES','Maule','LINARES','Part. Subvencionado'),
('16697','COLEGIO INITEC DE INNOVACION TECNOLOGICA','Maule','CURICÓ','Part. Subvencionado'),
('16698','CENTRO EDUCACIONAL KIMEL','Maule','CURICÓ','Part. Subvencionado'),
('16699','ESCUELA ESPECIAL UNPADE','Maule','TALCA','Part. Subvencionado'),
('16701','ESC.DE LENGUAJE Y JARDIN INFANTIL NELTUME','Maule','MAULE','Part. Subvencionado'),
('16702','ESC.ESPECIAL DE LENGUAJE HABLAPALABRAS','Maule','TALCA','Part. Subvencionado'),
('16703','ESCUELA ESPECIAL DE LENGUAJE MIS PRIMERAS PAL','Maule','MAULE','Part. Subvencionado'),
('16704','COLEGIO CLEMENTINOS','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16705','LICEO TEC.PROFESIONAL AGROPECUARIO LUXEMBURGO','Maule','CURICÓ','Part. Subvencionado'),
('16708','COLEGIO PARTICULAR JOSEFINA MEDEL','Maule','LINARES','Part. Subvencionado'),
('16709','ESCUELA ESPECIAL DE LENGUAJE APRENDER','Maule','MAULE','Part. Subvencionado'),
('16711','ESCUELA DE LENGUAJE Y JARDIN INFANTIL PEQUEÑO','Maule','LICANTÉN','Part. Subvencionado'),
('16712','JARDIN INFANTIL MAGIC CASTLE','Maule','TENO','Part. Subvencionado'),
('16713','COLEGIO SAN PABLO','Maule','CURICÓ','Part. Subvencionado'),
('16715','COLEGIO EL BOLDO','Maule','CURICÓ','Corp. Municipal'),
('16716','LICEO BICENTENARIO ZAPALLAR DE CURICO','Maule','CURICÓ','Corp. Municipal'),
('16717','COLEGIO SANTA MADRE DE DIOS','Maule','SAN RAFAEL','Part. Subvencionado'),
('16718','ESCUELA ESPECIAL DE LENGUAJE ANTONIO CASTRO A','Maule','LINARES','Part. Subvencionado'),
('16721','ESCUELA ESP. CENTRO DE INTEGRACION PADRE PIO','Maule','PARRAL','Part. Subvencionado'),
('16722','COLEGIO CRISTIANO DE EDUC. DE ADULTOS EL SEMB','Maule','TALCA','Part. Subvencionado'),
('16723','ESCUELA HOSPITALARIA DE CAUQUENES','Maule','CAUQUENES','Part. Subvencionado'),
('16725','ESCUELA ESPECIAL DIFERENCIAL SOL Y LUNA','Maule','SAN JAVIER','Part. Subvencionado'),
('16727','COLEGIO DE ADULTOS PROMAUCAES','Maule','CAUQUENES','Part. Subvencionado'),
('16728','COLEGIO SANTO TOMAS DE TALCA','Maule','MAULE','Part. Subvencionado'),
('16729','INSTITUTO INGLES','Maule','CURICÓ','Corp. Municipal'),
('16730','LICEO BICENTENARIO ADMINISTRACION Y COMERCIO HC','Maule','CURICÓ','Part. Subvencionado'),
('16731','ESCUELA ESPECIAL DE LENGUAJE ENSEÑARTE','Maule','CAUQUENES','Part. Subvencionado'),
('16732','COLEGIO ALTO PEWEN','Maule','TALCA','Part. Subvencionado'),
('16733','COLEGIO ALTAS CUMBRES DE SAN CLEMENTE','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16734','JARDIN INFANTIL MIS TESOROS','Maule','TENO','Part. Subvencionado'),
('16735','ESCUELA DE LENGUAJE EL CASTILLO INFANTIL','Maule','CURICÓ','Part. Subvencionado'),
('16736','JARDIN INFANTIL Y SALA CUNA LOS RUILES','Maule','TALCA','Part. Pagado'),
('16739','CLARO DE LUNA CENTRO DE DESARROLLO COGNITIVO','Maule','YERBAS BUENAS','Part. Subvencionado'),
('16740','COLEGIO MARÍA DIZA PINO VARGAS','Maule','PARRAL','Part. Subvencionado'),
('16743','ESCUELA ESPECIAL AMANECER LONGAVI','Maule','LONGAVÍ','Part. Subvencionado'),
('16744','COLEGIO SAN ESTEBAN DE TALCA','Maule','MAULE','Part. Subvencionado'),
('16745','ESCUELA DE LENGUAJE MARCELA PAZ','Maule','MAULE','Part. Subvencionado'),
('16747','COLEGIO GABRIELA MISTRAL','Maule','CURICÓ','Corp. Municipal'),
('16748','LICEO BICENTENARIO ORIENTE DE TALCA','Maule','TALCA','Corp. Municipal'),
('16749','COLEGIO JUAN IGNACIO MOLINA DE LA FLORIDA','Maule','TALCA','Part. Subvencionado'),
('16751','LICEO BICENTENARIO DE CAUQUENES','Maule','CAUQUENES','Servicio Local'),
('16752','CENTRO EDUCACIONAL INTEGRAL ADULTOS VICTORIA','Maule','TALCA','Part. Subvencionado'),
('16753','ESCUELA ESP. LENGUAJE Y PARVULOS SAN ESTEBAN','Maule','LINARES','Part. Subvencionado'),
('16754','LICEO ARTURO ALESSANDRI PALMA','Maule','ROMERAL','Corp. Municipal'),
('16756','COLEGIO LOS AGUSTINOS','Maule','MAULE','Part. Subvencionado'),
('16757','COLEGIO JUAN IGNACIO MOLINA DE LICANTEN','Maule','LICANTÉN','Part. Subvencionado'),
('16758','ESCUELA ESPECIAL DE LENGUAJE ALTAHIR','Maule','TALCA','Part. Subvencionado'),
('16759','COLEGIO ALTAMIRA DE  MIS PEQUEÑOS TESOROS, PARRAL','Maule','PARRAL','Part. Subvencionado'),
('16761','INSTITUTO DE EDUCACION ESPECIAL CURICO','Maule','CURICÓ','Part. Subvencionado'),
('16762','ESCUELA ESPECIAL CENTRO EDUCATIVO DIDACTICA C','Maule','CURICÓ','Part. Subvencionado'),
('16763','ESCUELA PARVULOS SNOOPY','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('16765','TALLER LABORAL Y ESCUELA ESPECIAL CREANDO FUTURO','Los Lagos','LLANQUIHUE','Part. Subvencionado'),
('16766','GOLDEN EAGLE SCHOOL','Los Lagos','OSORNO','Part. Subvencionado'),
('16767','ESCUELA ESPECIAL DE LENGUAJE AMAPOLA ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16768','COLEGIO MANITOS DE LUZ','Los Lagos','ANCUD','Part. Subvencionado'),
('16770','COLEGIO ALIWE COLLEGE','Biobío','CORONEL','Part. Subvencionado'),
('16773','ESCUELA ESPECIAL N°2424 EL  VOLANTIN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('16775','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑO SAFARI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('16776','LYCÉE ANTOINE DE SAINT - EXUPÉRY','Metropolitana','COLINA','Part. Pagado'),
('16777','ESCUELA  DE  PARVULOS  Y  ESPECIAL  N°197 AMARAL','Metropolitana','EL MONTE','Part. Subvencionado'),
('16778','CENTRO DE FORMACION LABORAL HUELLAS','Biobío','CORONEL','Part. Subvencionado'),
('16779','ESCUELA ESPECIAL DE LENGUAJE PALABRAS DE NIÑOS','Biobío','CORONEL','Part. Subvencionado'),
('16780','COLEGIO ALTO LAUQUÉN','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16781','ESCUELA ESPECIAL DE LENGUAJE ALTO LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16782','ESCUELA ESPECIAL DE LENGUAJE REMOLINO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('16783','COLEGIO HOSPITALARIO HOSPITAL DEL  PINO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16784','ESCUELA DIFERENCIAL CABALLITO DE MAR','Biobío','CORONEL','Part. Subvencionado'),
('16785','ESCUELA ESPECIAL DE  LENGUAJE LOS  CHAVITOS','Metropolitana','LAMPA','Part. Subvencionado'),
('16787','ESCUELA  BASICA  N°198 GREENFIELD SCHOOL','Metropolitana','TALAGANTE','Part. Pagado'),
('16788','ESCUELA ESPECIAL N°197 MI  PEQUEÑO  MOZART','Metropolitana','BUIN','Part. Subvencionado'),
('16789','ESCUELA ESPECIAL N°2427 CARNAVAL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('16790','ESCUELA  ESPECIAL  BASILEA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('16791','ESC. ESP. DE LENGUAJE CUMBRES DE PLACILLA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16792','COLEGIO HALCONES DEL CARMEN','Ñuble','EL CARMEN','Part. Subvencionado'),
('16793','LICEO TECNICO PROFESIONAL LA ARAUCANA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('16794','ESCUELA NUEVA MILLARAYEN','La Araucanía','GALVARINO','Part. Subvencionado'),
('16797','ESC. ESP. DE LENGUAJE AMANECER DE COLORES','Valparaíso','LLAILLAY','Part. Subvencionado'),
('16798','COLEGIO NEW BUCKINGHAM','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('16799','CENTRO DE EDUCACION INTEGRADO DE  ADULTOS GLADYS LAZO Nº 2','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16800','ESCUELA ESPECIAL DE LENGUAJE ESMERALDA BARQUITO DE SUEÑOS','Biobío','CABRERO','Part. Subvencionado'),
('16802','ESCUELA ESPECIAL DE LENGUAJE SONRISAS','Ñuble','TREHUACO','Corp. Municipal'),
('16803','ESCUELA ESPECIAL DE LENGUAJE PALABRAS MAGICAS SALTO DEL LAJA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16806','CENTRO EDUCACIONAL AYECANTUN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('16807','COLEGIO LOS  ALERCES  DE  TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('16808','ESCUELA  ESPECIAL N°232 EL ARCA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('16809','ESCUELA  ESPECIAL N°198 LOS  GIRASOLES','Metropolitana','BUIN','Part. Subvencionado'),
('16810','ESCUELA  ESPECIAL  N°199 EL  AROMO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16811','ESCUELA ESPECIAL N° 2430 SAN ALBERTO HURTADO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('16812','ESCUELA ESPECIAL PARAPEQUES','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('16813','ESCUELA ESPECIAL NUEVA ESPERANZA','Valparaíso','RINCONADA','Part. Subvencionado'),
('16814','ESCUELA ESPECIAL N°199, MI  POLLITO  AMARILLITO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('16815','COLEGIO PATAGONIA DE BUIN','Metropolitana','BUIN','Part. Pagado'),
('16816','ESCUELA  BASICA N°201, REDWOOD COLLEGE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16817','ESCUELA DE LENGUAJE HABLA PALABRA','Maule','CURICÓ','Part. Subvencionado'),
('16818','JARDIN INFANTIL LE CYGNE','Coquimbo','LA SERENA','Part. Pagado'),
('16820','COLEGIO  PAULO  FREIRE  DE  SAN  MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('16821','ESCUELA ESPECIAL APRENDAMOS JUNTOS','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('16823','ESCUELA ESPECIAL N° 2433 LOS MUSICOS DE BREMEN','Metropolitana','LA PINTANA','Part. Subvencionado'),
('16825','COLEGIO  TRABUNCO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('16826','ESCUELA  ESPECIAL  N°2435 AITUE','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('16827','ESCUELA ESPECIAL Y DE PARVULOS PETIT PRINCE','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('16828','ESCUELA ESPECIAL ANTUMALEN N°202','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('16829','ESCUELA DE PARVULOS N°2437,  COLEGIO ALEMÁN CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('16830','RIELJAN COLLEGE','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('16831','ESCUELA ESPECIAL DE LENGUAJE MARIA MONTESSORI','O''Higgins','PLACILLA','Part. Subvencionado'),
('16832','ESCUELA  ESPECIAL  2438 `PEQUEÑOS  GENIOS  DE  VALLE  GRANDE`','Metropolitana','LAMPA','Part. Subvencionado'),
('16833','JARDIN INFANTIL Y SALA CUNA EMITA','Tarapacá','IQUIQUE','Part. Pagado'),
('16834','JARDÍN INFANTIL JIRAFITA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('16837','ESC.ESP.N°2439, MANQUEHUE DE TIL TIL','Metropolitana','TILTIL','Part. Subvencionado'),
('16838','ESCUELA ESPECIAL DIFERENCIAL EXPRESION DE AMOR','Biobío','TOMÉ','Part. Subvencionado'),
('16839','ESCUELA ESPECIAL DE LENGUAJE SAN MARCOS','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('16840','COLEGIO DE ADULTOS RENACIMIENTO','O''Higgins','PEUMO','Part. Subvencionado'),
('16843','LICEO BICENTENARIO DE EXCELENCIA TECNICO PROFESIONAL PEOPLE HELP PEOPLE DE PANGUIPULLI','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('16844','LICEO TECNICO PROFESIONAL PEOPLE HELP PEOPLE PULLINQUE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('16845','ESCUELA ESPECIAL DE LENGUAJE SARAH KAY','Maule','RETIRO','Part. Subvencionado'),
('16846','COLEGIO MIS IDEAS','Maule','MOLINA','Part. Subvencionado'),
('16847','ESCUELA DEL CARIÑO HENRY CETTY','Maule','MOLINA','Part. Subvencionado'),
('16848','ESCUELA ESPECIAL DE LENGUAJE PALABRAS DULCES','Maule','MOLINA','Part. Subvencionado'),
('16849','INSTITUTO EDUCACIONAL DE ADULTOS HERMANOS CARRERA','Maule','COLBÚN','Part. Subvencionado'),
('16850','JARDIN INFANTIL AMIGUITOS','Los Lagos','PUERTO MONTT','Part. Pagado'),
('16851','INSTITUTO BICENTENARIO JAVIERA CARRERA VERDUGO','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('16852','JARDIN INFANTIL EL SAPITO PIRI Y SUS AMIGOS','Los Lagos','PUERTO MONTT','Part. Pagado'),
('16854','JARDIN INFANTIL NIÑOS LUZ','Maule','MAULE','Part. Subvencionado'),
('16855','ESCUELA SARGENTO PRIMERO CRISTIAN VENEGAS OJEDA','Maule','MOLINA','Corp. Municipal'),
('16856','COLEGIO MELIAN','Maule','MAULE','Part. Subvencionado'),
('16857','CENTRO  EDUCACIONAL  DE  ADULTOS  EL MONTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('16858','ESCUELA ESPECIAL DE LENGUAJE SEMILLA DE GIRASOL','Los Lagos','ANCUD','Part. Subvencionado'),
('16859','ESCUELA DE PARVULOS N° 201 `MIKY`','Metropolitana','MELIPILLA','Part. Subvencionado'),
('16860','COLEGIO DE PARVULOS MI GATITO MARTIN','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16861','ESCUELA DE LENGUAJE DIEGO DUBLE URRUTIA','O''Higgins','LITUECHE','Part. Subvencionado'),
('16862','ESCUELA DE LENGUAJE AGUA SOL','Maule','TALCA','Part. Subvencionado'),
('16863','JARDÍN INFANTIL PEQUEÑA LULÚ','Biobío','CONCEPCIÓN','Part. Pagado'),
('16864','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS AMIGOS','Biobío','CORONEL','Part. Subvencionado'),
('16865','ESCUELA ESPECIAL DE LENGUAJE MI PEQUEÑO SUEÑO','Ñuble','CHILLÁN','Part. Subvencionado'),
('16866','ESCUELA  ESPECIAL  N° 2440 LEONARDO  DA  VINCI','Metropolitana','HUECHURABA','Part. Subvencionado'),
('16868','ESCUELA ESPECIAL DE LENGUAJE COMUNICA','Los Lagos','OSORNO','Part. Subvencionado'),
('16869','ESCUELA ESPECIAL DE LENGUAJE EL CASTILLO DE IGNACIA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('16872','JARDIN INFANTIL AMAUTA PRESCHOOL','Tarapacá','IQUIQUE','Part. Pagado'),
('16873','ESCUELA LENGUAJE VER Y HABLAR','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('16874','ESCCUELA MUNICIPAL PROFESOR DAVID FERNÁNDEZ PÉREZ','Biobío','YUMBEL','Corp. Municipal'),
('16876','ESCUELA DE LENGUAJE ALUN','O''Higgins','PALMILLA','Part. Subvencionado'),
('16877','ESCUELA DE LENGUAJE NAMASTE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('16878','ESCUELA ESPECIAL ECOLÓGICA N°2441, MAPU LIHUEN','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('16879','ESCUELA BÁSICA N°2442 `CENTRO EDUCACIONAL ERNESTO YAÑEZ RIVERA`','Metropolitana','HUECHURABA','Corp. Municipal'),
('16880','ESCUELA ESPECIAL N°  203 ALTO BUIN II','Metropolitana','BUIN','Part. Subvencionado'),
('16881','COLEGIO FILII FUTURI','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16882','CENTRO EDUCACIONAL INTEGRAL QUIDELL','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('16883','ESCUELA ESPECIAL EL ARBOL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('16886','COLEGIO VALLES DEL MAIPO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16887','CENTRO DE ESTUDIOS CREA FUTURO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16888','ESCUELA ESPECIAL N° 2446 `VOCES`','Metropolitana','MAIPÚ','Part. Subvencionado'),
('16889','ESCUELA ESPECIAL N° 2445 PAPELUCHO','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('16892','CENTRO DE ESTUDIO DE LA PATAGONIA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('16893','ESCUELA ESPECIAL N°2443 ARCOIRIS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('16894','ESCUELA ESPECIAL N°204 ANGEL MIGUEL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16895','COLEGIO MARIA AUXILIADORA','Magallanes','PORVENIR','Part. Subvencionado'),
('16897','ESCUELA DE PARVULOS PLANETA TIERRA II','Antofagasta','CALAMA','Part. Subvencionado'),
('16899','ESCUELA ESPECIAL DE LENGUAJE AMAPOLA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16900','ESCUELA ESPECIAL DE LENGUAJE MONTEACAY','Valparaíso','CONCÓN','Part. Subvencionado'),
('16901','ESCUELA ESPECIAL DE LENGUAJE RUCAHUE','Biobío','TALCAHUANO','Part. Subvencionado'),
('16902','ESCUELA ESPECIAL DE LENGUAJE MI CASTILLO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('16904','ESCUELA ESPECIAL N° 2447 `ESTRELLITAS  DE SAN JOSÉ`','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('16905','ESC.ESP.DE LENGUAJE Y COMUNICACIÓN `MUNDO FELIZ`','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('16906','CURAUMA LANGUAGE SCHOOL, ESC. ESP. DE LENG. Y DE PARV','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16907','JARDIN INFANTIL KINTU MONTESSORI','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('16908','ESCUELA ESPECIAL DE LENGUAJE MATEITOS','Coquimbo','OVALLE','Part. Subvencionado'),
('16909','ESCUELA ESPECIAL TEMAIKEN','O''Higgins','GRANEROS','Part. Subvencionado'),
('16910','ESCUELA BASICA PEUMA MEW','La Araucanía','VILLARRICA','Part. Subvencionado'),
('16911','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑAS PALABRAS','Biobío','NACIMIENTO','Part. Subvencionado'),
('16912','ESCUELA ESPECIAL DE LENGUAJE AQUALUNA','Coquimbo','LA SERENA','Part. Subvencionado'),
('16913','COLEGIO PADRE PIO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('16914','ESCUELA ESPECIAL SAN JOSE','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('16915','CENTRO DE EDUCACION INTEGRADA DE ADULTOS NAHUELQUIN','Biobío','CABRERO','Part. Subvencionado'),
('16916','ESCUELA ESPECIAL DEL LENGUAJE ARBOLITO','Coquimbo','LA SERENA','Part. Subvencionado'),
('16918','ESCUELA ESPECIAL DE LENGUAJE HIJOS DEL REY','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('16919','COLEGIO CUMBRES DE COIHUECO','Ñuble','COIHUECO','Part. Subvencionado'),
('16921','ESCUELA ESPECIAL N°234 `LAS FLORES`','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('16922','LICEO TECNICO PROFESIONAL DE ADULTOS CHILOE','Los Lagos','CASTRO','Part. Subvencionado'),
('16923','THE BRITISH SCHOOL PATAGONIA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16924','COLEGIO BELLO HORIZONTE','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('16925','ESCUELA ESPECIAL DE LENGUAJE MI CASTILLO FELIZ','Ñuble','SAN NICOLÁS','Part. Subvencionado'),
('16926','ESCUELA ESPECIAL DE LENGUAJE PINARES Y ESCUELA BÁSICA PINARES','Ñuble','YUNGAY','Part. Subvencionado'),
('16928','ESCUELA ESPECIAL DE LENGUAJE EL DESPERTAR','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('16931','JARDIN INFANTIL HISPANO BRITANICO S. A.','Tarapacá','IQUIQUE','Part. Pagado'),
('16932','COLEGIO ESCUELA PREMILITAR LAUTARO','O''Higgins','OLIVAR','Part. Subvencionado'),
('16933','ESCUELA ESPECIAL DE LENGUAJE DESCUBRE PALABRAS','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('16935','LICEO TECNICO PROFESIONAL DE ADULTOS DE ANTOFAGASTA','Antofagasta','ANTOFAGASTA','Part. Subvencionado'),
('16936','ESCUELA ESPECIAL DE LENGUAJE DORA','Los Lagos','RÍO NEGRO','Part. Subvencionado'),
('16937','ESCUELA ESPECIAL DE LENGUAJE SAN SEBASTIAN','Biobío','HUALPÉN','Part. Subvencionado'),
('16938','ESCUELA ESPECIAL DE LENGUAJE RAYUN','Ñuble','CHILLÁN','Part. Subvencionado'),
('16939','ESCUELA DE PARVULOS TINKERBELL','Antofagasta','CALAMA','Part. Subvencionado'),
('16940','ESCUELA DE PÁRVULOS CAMPANITA','Antofagasta','CALAMA','Part. Pagado'),
('16941','ESCUELA YAIMA','La Araucanía','GALVARINO','Part. Subvencionado'),
('16942','COMPLEJO EDUCACIONAL CRISTO REY','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('16943','JARDIN INFANTIL EL RINCÓN DEL SAPOSOPITO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('16944','COLEGIO ANDALUE','Ñuble','EL CARMEN','Part. Subvencionado'),
('16945','COLEGIO NUEVO HORIZONTE','Valparaíso','QUILLOTA','Part. Subvencionado'),
('16946','ESCUELA  ESPECIAL N° 2449,  `DE LA  MERCED`','Metropolitana','SANTIAGO','Part. Subvencionado'),
('16947','ESCUELA ESPECIAL DE LENGUAJE MI PEQUEÑO GRAN MUNDO','Los Lagos','FRESIA','Part. Subvencionado'),
('16949','ESCUELA ESPECIAL DE LENGUAJE NAHUEN','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16950','CENTRO EDUCACIONAL SAN PEDRO DE QUELLON','Los Lagos','QUELLÓN','Part. Subvencionado'),
('16952','ESCUELA ESPECIAL DE DISCAPACIDAD INTELECTUAL CORAZON DE JESUS','La Araucanía','TEMUCO','Part. Subvencionado'),
('16953','ESCUELA  ESPECIAL  N°235, `EL PRINCIPITO DE PUENTE  ALTO`','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('16954','ESCUELA ESPECIAL DE LENGUAJE MIS PRIMEROS PASOS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16955','ESCUELA BASICA COLEGIO SAN JUAN DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('16956','ESCUELA ESPECIAL N° 2451 `PUCALAN`','Metropolitana','RENCA','Part. Subvencionado'),
('16957','ESCUELA  ESPECIAL DE LENGUAJE PETRICOR','Metropolitana','RENCA','Part. Subvencionado'),
('16958','COLEGIO  ARTISTICO SOL DEL  ILLIMANI','Metropolitana','LA FLORIDA','Municipal'),
('16959','ESCUELA ESPECIAL DE LENGUAJE ARBOLIRIS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('16960','ESCUELA ESPECIAL DE LENGUAJE Y JARDIN INFANTIL CASTILLO TIA PAOLA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('16961','ESCUELA ESPECIAL DE LENGUAJE CHOL-CHOL','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('16962','ESCUELA MONTE SINAÍ','La Araucanía','CARAHUE','Part. Subvencionado'),
('16963','ESCUELA ESPECIAL N° 2453 `THE ALMOND SCHOOL II`','Metropolitana','LA PINTANA','Part. Subvencionado'),
('16964','ESCUELA ESPECIAL DE LENGUAJE PALABRITA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16966','ESCUELA ESPECIAL DIFERENCIAL FLORECER','Biobío','TALCAHUANO','Part. Subvencionado'),
('16967','COLEGIO ESPECIAL LOS ARRAYANES','Los Lagos','CALBUCO','Corp. Municipal'),
('16968','ESCUELA ESPECIAL DIFERENCIAL BENDICIONES DE AMOR','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16969','JARDIN INFANTIL CONQUISTADORES','Coquimbo','COQUIMBO','Part. Pagado'),
('16970','EDUCERE COLLEGE','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('16971','ESCUELA  ESPECIAL N°205 ,`MI MUNDO  EN  PALABRAS`','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('16972','ESCUELA ESPECIAL CREA Nº2455','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('16973','ESCUELA ESPECIAL DIFERENCIAL PALU','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16974','ESCUELA ESPECIAL DE LENGUAJE YIREH LOS MOLLES','Biobío','CORONEL','Part. Subvencionado'),
('16975','COLEGIO UNIÓN FRATERNA','Aysén','COYHAIQUE','Part. Subvencionado'),
('16978','COLEGIO KOPERNIKUS','Los Lagos','FRUTILLAR','Part. Pagado'),
('16980','ESCUELA  BASICA  N° 206, `PULMAHUE`','Metropolitana','PAINE','Part. Subvencionado'),
('16984','ESCUELA ESPECIAL DE LENGUAJE PIMPINO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('16985','LICEO BICENTENARIO PAULO FREIRE','Los Lagos','QUELLÓN','Servicio Local'),
('16986','LOS CAPULLITOS','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('16987','ESCUELA  ESPECIAL N° 2456 `TU  ARCOIRIS`','Metropolitana','LA GRANJA','Part. Subvencionado'),
('16988','ESCUELA ESPECIAL DE LENGUAJE MAKIATO','Valparaíso','LOS ANDES','Part. Subvencionado'),
('16989','CAMBRIDGE COLLEGE','Valparaíso','LOS ANDES','Part. Pagado'),
('16990','ESCUELA ESPECIAL DE LENGUAJE MAGRACE','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('16991','ESCUELA ESPECIAL DE LENGUAJE GREEN DAY','Valparaíso','LIMACHE','Part. Subvencionado'),
('16992','ESC. ESP. DE LENG. TROMPITA DE COLORES','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16993','CENTRO EDUCACIONAL DE ADULTOS AUROMAR','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('16994','ESC.ESP.N°236 `MILLARAY DE CASAS VIEJAS`','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('16995','ESCUELA ESPECIAL DIVINO NIÑO JESUS','Metropolitana','COLINA','Part. Subvencionado'),
('16997','COLEGIO AMERICAN SCHOOL','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('16998','ESCUELA ESPECIAL DE LENGUAJE CONTIGO APRENDO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('16999','ESCUELA ESPECIAL DE LENGUAJE PIONEROS','Biobío','CORONEL','Part. Subvencionado'),
('17000','COLEGIO ALTA CUMBRE','Valparaíso','LOS ANDES','Part. Subvencionado'),
('17001','ESCUELA ESPECIAL DE LENGUAJE EL SOL DE QUILACO','Biobío','QUILACO','Part. Subvencionado'),
('17600','COLEGIO SAN GABRIEL ARCANGEL','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17602','CENTRO DE EDUCACIÓN  INTEGRAL DIEGO PORTALES','Biobío','CONCEPCIÓN','Part. Pagado'),
('17605','COLEGIO INGLÉS WOODLAND','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17606','COLEGIO CONCEPCION SAN PEDRO','Biobío','SAN PEDRO DE LA PAZ','Part. Pagado'),
('17607','COLEGIO INGLÉS BRITISH ROYAL SCHOOL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17634','COLEGIO DE LA SANTISIMA TRINIDAD','Biobío','SAN PEDRO DE LA PAZ','Part. Pagado'),
('17635','COLEGIO CONCEPCION LOS ACACIOS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17636','ESCUELA CENTRO ECOEDUCATIVO LAS TRANCAS','Ñuble','PINTO','Servicio Local'),
('17637','ESCUELA ANEXO TANILVORO','Ñuble','COIHUECO','Servicio Local'),
('17638','COLEGIO SANTO TOMAS DE AQUINO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17640','ESCUELA BASICA EL PILME','Ñuble','QUIRIHUE','Corp. Municipal'),
('17641','ESCUELA BASICA CANA DULCE','Ñuble','TREHUACO','Corp. Municipal'),
('17642','JARDIN INFANTIL FABIOLA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17643','LICEO AGRICOLA DE NEGRETE','Biobío','NEGRETE','Part. Subvencionado'),
('17647','TALLER DE CAPACITACIÓN LABORAL UNPADE','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17648','COLEGIO PARTICULAR KENNEDY SCHOOL','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17650','CENTRO DE CAPACITACIÓN URCAE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17652','COLEGIO RAIQUEN','Biobío','YUMBEL','Part. Subvencionado'),
('17653','JARDIN INFANTIL SEMILLA','Ñuble','CHILLÁN','Part. Pagado'),
('17654','CENTRO EDUCACIÓN INTEGRADA DE ADULTOS','Biobío','CORONEL','Servicio Local'),
('17655','ESCUELA MUNICIPAL CARRIZAL - MENIR','Biobío','NACIMIENTO','Corp. Municipal'),
('17657','INSTITUTO DE HUMANIDADES ANTONIO MORENO CASAMITJANA','Biobío','CORONEL','Part. Subvencionado'),
('17658','COLEGIO EINSTEIN','Biobío','CONCEPCIÓN','Part. Pagado'),
('17660','SCUOLA ITALIANA DI CONCEPCION','Biobío','CORONEL','Part. Subvencionado'),
('17662','LICEO BICENTENARIO CLAUDIO ARRAU LEÓN','Ñuble','COIHUECO','Servicio Local'),
('17687','COLEGIO TERESIANO LOS ANGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17689','COLEGIO LICANRAY','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17690','COLEGIO BEATO DAMIÁN DE MOLOKAI','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17692','COLEGIO GOLDEN SCHOOL','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17693','COLEGIO BASICO NUEVA LOS LOBOS','Biobío','TALCAHUANO','Corp. Municipal'),
('17697','SOCIEDAD EDUCACIONAL LA ARAUCANA','Biobío','CONCEPCIÓN','Part. Pagado'),
('17698','ESCUELA RAMÓN VINAY SEPÚLVEDA','Ñuble','CHILLÁN','Corp. Municipal'),
('17699','ESCUELA ESP.DIF.CENTRO EDUCATIVO INTEGRAL LOS NARANJOS','Ñuble','CHILLÁN','Part. Subvencionado'),
('17701','CENTRO DE EDUCACIÓN DE ADULTOS NEWENTUN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17703','COLEGIO ESPIRITU SANTO','Biobío','TALCAHUANO','Part. Subvencionado'),
('17704','ESCUELA AMANDA LABARCA','Biobío','LAJA','Corp. Municipal'),
('17708','COLEGIO SAN CRISTOBAL','Biobío','TALCAHUANO','Part. Subvencionado'),
('17709','ESCUELA BALMACEDA SAAVEDRA L.','Biobío','CHIGUAYANTE','Servicio Local'),
('17710','ESCUELA BASICA EL MIRADOR','Biobío','TOMÉ','Corp. Municipal'),
('17711','ESCUELA BASICA EL ESPINO','Biobío','TOMÉ','Corp. Municipal'),
('17715','ESCUELA ACUMAR','Biobío','MULCHÉN','Part. Subvencionado'),
('17718','ESCUELA ESPECIAL DE LENGUAJE Y JARDIN INFANTIL WONDERFUL WORDL','Biobío','TALCAHUANO','Part. Subvencionado'),
('17719','COLEGIO PARTICULAR CONTINENTAL','Biobío','CURANILAHUE','Part. Subvencionado'),
('17723','ESCUELA DIEGO PORTALES','Biobío','SANTA JUANA','Servicio Local'),
('17725','COLEGIO SAN ESTEBAN DE BULNES','Ñuble','BULNES','Part. Subvencionado'),
('17726','CENTRO EVANGÉLICO PARA EDUCACIÓN ADULTOS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17728','COLEGIO EL BOSQUE','Biobío','ARAUCO','Part. Subvencionado'),
('17732','COLEGIO UMBRALES DEL ALBA','Biobío','MULCHÉN','Part. Subvencionado'),
('17733','COLEGIO CAMILO HENRIQUEZ','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17734','COLEGIO DA VINCI','Ñuble','CHILLÁN','Part. Subvencionado'),
('17735','COLEGIO BICENTENARIO DE EXCELENCIA DARIO SALAS CHILLAN VIEJO','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('17736','COLEGIO SAN IGNACIO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17737','COLEGIO PARROQUIAL SAN JOSE','Ñuble','CHILLÁN','Part. Subvencionado'),
('17739','JARDIN INFANTIL ANIBAL ESQUIBEL TAPIA','Biobío','CORONEL','Part. Subvencionado'),
('17741','ESCUELA REINO DE SUECIA','Ñuble','COBQUECURA','Corp. Municipal'),
('17742','ESCUELA BASICA EDUARDO FREI MONTALBA','Ñuble','BULNES','Corp. Municipal'),
('17745','COLEGIO STERNENKINDER NIÑOS DE LAS ESTRELLAS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17746','COLEGIO OLIMPIA GUZMAN BELLO','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17747','JARDIN INFANTIL NUEVO CAPULLITO','Biobío','HUALPÉN','Part. Subvencionado'),
('17749','ESCUELA PUCARA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17750','COLEGIO SALESIANO DE CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17751','ESCUELA VILLA LA GRANJA','Biobío','MULCHÉN','Corp. Municipal'),
('17753','ESCUELA DIFERENCIAL ALTO DEL REY','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17754','CENTRO DE EDUCACION DE ADULTOS INTECH','Ñuble','CHILLÁN','Part. Subvencionado'),
('17756','JARDIN INFANTIL CUNCUNITA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17762','ESCUELA PARTICULAR BAJO QUILANTAHUE','Biobío','TIRÚA','Part. Subvencionado'),
('17763','ESCUELA PARTICULAR CUYIMPALIHUE','Biobío','CAÑETE','Part. Subvencionado'),
('17764','LICEO TECNICO AGRICOLA SAN LORENCITO','Biobío','QUILLECO','Part. Subvencionado'),
('17765','COLEGIO MADRE PAULINA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17766','COLEGIO SAN JOSE','Ñuble','SAN CARLOS','Part. Subvencionado'),
('17768','PARVULARIO EL NAZARENO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17771','ESCUELA DE TRASTORNOS DE LA COMUNICACIÓN MILLARAY','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17772','LICEO POLITECNICO CANETE','Biobío','CAÑETE','Part. Subvencionado'),
('17774','JARDÍN INFANTIL MI PEQUEÑO AMOR','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17776','ESCUELA ESPECIAL AMANECER','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17778','COLEGIO SAN JUAN DE DIOS','Biobío','NACIMIENTO','Part. Subvencionado'),
('17779','COLEGIO PACIFIC SCHOOL','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17781','COLEGIO DE LENGUAJE SENDEROS DEL BIOBÍO','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17782','LICEO RIOS DE CHILE','Biobío','PENCO','Corp. Municipal'),
('17784','CENTRO DE CAPACITACIÓN Y ESTUDIOS LABORALES UNPADE','Ñuble','CHILLÁN','Part. Subvencionado'),
('17785','ESCUELA VILLA CENTINELA SUR','Biobío','TALCAHUANO','Corp. Municipal'),
('17786','COLEGIO SAN PABLO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17787','ESCUELA ORLANDO VERA VILLARROEL','Biobío','CABRERO','Corp. Municipal'),
('17788','COLEGIO AMANECER','Biobío','CORONEL','Part. Subvencionado'),
('17790','LICEO BICENTENARIO DE EXCELENCIA NUEVO MUNDO','Biobío','MULCHÉN','Corp. Municipal'),
('17791','CENTRO DE ATENCION INFANTIL TAMBORIN','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17793','COLEGIO CONCEPCION DE SAN CARLOS','Ñuble','SAN CARLOS','Part. Subvencionado'),
('17794','COLEGIO CONCEPCION DE CHILLAN','Ñuble','CHILLÁN','Part. Subvencionado'),
('17795','INSTITUTO PROFESIONAL Y CENTRO DE FORMACIÓN TÉCNICA SANTA LUCÍA E.I.R.L.','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17796','COLEGIO ADULTOS RENACER','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17797','ARAUCARIA SCHOOL','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('17798','COLEGIO ACUMAR','Biobío','NEGRETE','Part. Subvencionado'),
('17799','ESCUELA ESPECIAL TRASTORNOS DE LA COMUNICACIÓN NAHUEL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17800','COLEGIO SYDNEY COLLEGE','Ñuble','CHILLÁN','Part. Subvencionado'),
('17802','INSTITUTO DOWN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17805','JARDIN INFANTIL CRECECONMIGO','Biobío','CHIGUAYANTE','Part. Pagado'),
('17807','ESCUELA DE LENGUAJE JESUS MAESTRO','Biobío','NACIMIENTO','Part. Subvencionado'),
('17809','ESCUELA DE LENGUAJE SANTISIMA TRINIDAD','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17810','CENTRO DE EDUCACIÓN DE ADULTOS QUIMAHUE','Biobío','CAÑETE','Part. Subvencionado'),
('17812','COLEGIO CONCEPCION CHIGUAYANTE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17813','ESCUELA BÁSICA CACIQUE LEVIÁN','Biobío','SANTA BÁRBARA','Corp. Municipal'),
('17814','ESCUELA ALTO CABRERO','Biobío','CABRERO','Corp. Municipal'),
('17815','COLEGIO EINSTEIN','Biobío','CORONEL','Part. Pagado'),
('17816','ESCUELA DIFERENCIAL CON TRASTORNO LENGUAJE MI VENTANA','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17817','COLEGIO PARTICULAR FRANCYS','Biobío','ARAUCO','Part. Subvencionado'),
('17818','LICEO TECNICO PROFESIONAL DE LA MADERA','Biobío','CORONEL','Part. Subvencionado'),
('17821','CENTRO DE LENGUAJE EL UMBRAL','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17822','ESC. ESP. DE TRANST. COMUN DOMINGO PARRA','Biobío','CORONEL','Part. Subvencionado'),
('17823','ESCUELA ESPECIAL DE LENGUAJE WENGA','Biobío','LOTA','Part. Subvencionado'),
('17824','COLEGIO CLARO DE LUNA COLLEGE','Biobío','TALCAHUANO','Part. Subvencionado'),
('17828','ESCUELA EVANGÉLICA BETH-EL','Ñuble','CHILLÁN','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
