-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 25 de 31 | filas 9601-10000
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('24558','ESCUELA BASICA PART.BLAS CANAS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('24607','ESCUELA DE PARVULOS N°1418 NUESTRO HOGAR','Metropolitana','CONCHALÍ','Part. Pagado'),
('24612','ESCUELA ESP. SANTA MARIA DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('24616','ESCUELA DE PARVULOS N°1424 SNOOPY','Metropolitana','COLINA','Part. Pagado'),
('24617','ESCUELA BÁSICA N°62  SANTA JULIA','Metropolitana','MELIPILLA','Part. Pagado'),
('24618','ESCUELA DE PARVULOS N°831 COLORIN COLORADO','Metropolitana','LA CISTERNA','Part. Pagado'),
('24622','MIGUEL DE CERVANTES Y SAAVEDRA ANEXO A-8','Metropolitana','SANTIAGO','Corp. Municipal'),
('24623','COLEGIO JORGE ALESSANDRI RODRIGUEZ','Metropolitana','RENCA','Part. Subvencionado'),
('24624','COLEGIO TABOR Y NAZARETH','Metropolitana','LO BARNECHEA','Part. Pagado'),
('24625','COLEGIO SAN CRISTOBAL COLLEGE','Metropolitana','SAN MIGUEL','Part. Pagado'),
('24626','COMPLEJO EDUCACIONAL ALBERTO WIDMER','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24627','COLEGIO ETIEVAN','Metropolitana','LA REINA','Part. Pagado'),
('24629','ESCUELA DE PARVULOS N°1428 CABALLITO BLANCO','Metropolitana','LA FLORIDA','Part. Pagado'),
('24630','ESCUELA DE PARVULOS N°1429 HAPPY DAY','Metropolitana','LAS CONDES','Part. Pagado'),
('24638','LICEO MIGUEL DE CERVANTES Y SAAVEDRA','Metropolitana','SANTIAGO','Corp. Municipal'),
('24642','COLEGIO ALEMAN DE SANTIAGO ANEXO','Metropolitana','VITACURA','Part. Pagado'),
('24647','ESCUELA BASICA N°1436 COLEGIO IBEROAMERICANO','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('24648','COLEGIO LOS NOGALES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24649','ESCUELA DE PARVULOS SAMORITO','Metropolitana','LA FLORIDA','Municipal'),
('24652','ESCUELA AGROECOLOGICA DE PIRQUE','Metropolitana','PIRQUE','Part. Subvencionado'),
('24654','ESCUELA BASICA CINCO PINOS','Metropolitana','SAN BERNARDO','Servicio Local'),
('24657','COLEGIO CRISTIANO BETHEL II','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('24670','COLEGIO INTERNACIONAL  ALBA','Metropolitana','MAIPÚ','Part. Pagado'),
('24671','COLEGIO LA ABADIA','Metropolitana','LA REINA','Part. Pagado'),
('24675','COLEGIO SAN MANUEL','Metropolitana','MELIPILLA','Part. Subvencionado'),
('24684','ESCUELA PARTICULAR QUILLAHUE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24685','COLEGIO PIAMARTA','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('24686','LICEO POLIVALENTE SANTIAGO DE COMPOSTELA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('24689','CTRO.EDUC.CATOLICO DIDASCALIO STA. MARIA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24690','COLEGIO SANTIAGO EVANGELISTA','Metropolitana','LA REINA','Part. Pagado'),
('24699','COLEGIO MAITENES','Metropolitana','MELIPILLA','Part. Pagado'),
('24700','CENTRO EDUC.ADULTOS AMERICO VESPUCIO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('24707','ESCUELA BASICA ACADEMIA MALLOCO','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('24713','COLEGIO EL BOSQUE PROVINCIA CORDILLERA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24714','COLEGIO SANTO TOMAS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24715','COLEGIO CRISTOBAL COLON DE MELIPILLA','Metropolitana','MELIPILLA','Part. Pagado'),
('24716','ESCUELA BASICA LOS NAVIOS','Metropolitana','LA FLORIDA','Municipal'),
('24717','LICEO BICENTENARIO NUESTRA SEÑORA DE GUADALUPE','Metropolitana','LA GRANJA','Part. Subvencionado'),
('24718','COLEGIO HUELQUEN MONTESSORI','Metropolitana','LO BARNECHEA','Part. Pagado'),
('24719','COLEGIO BUIN','Metropolitana','BUIN','Part. Pagado'),
('24721','COLEGIO LEONARDO DA VINCI DE LAS CONDES','Metropolitana','LAS CONDES','Municipal'),
('24722','ESC. BASICA PART.PADRE ALBERTO HURTADO','Metropolitana','HUECHURABA','Part. Subvencionado'),
('24723','COLEGIO KENDAL ENGLISH SCHOOL','Metropolitana','ÑUÑOA','Part. Pagado'),
('24725','COLEGIO JUGENDLAND SCHULE','Metropolitana','TALAGANTE','Part. Pagado'),
('24730','COLEGIO ADVENTISTA SANTIAGO PONIENTE','Metropolitana','LO PRADO','Part. Subvencionado'),
('24732','ESC.BAS.PART.COLEGIO HALLEY - ANEXO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24733','COLEGIO SAN ANDRES DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('24736','ESCUELA DE PARVULOS N°1372 LOS COPIHUITOS','Metropolitana','LA FLORIDA','Part. Pagado'),
('24738','ESCUELA PARVULOS PIN PIN SERAFIN','Metropolitana','RECOLETA','Part. Subvencionado'),
('24739','ESCUELA DE PARVULOS N°1475 PIN PIN SERAFIN N° 2','Metropolitana','RECOLETA','Part. Pagado'),
('24740','ESCUELA DE PARVULOS N°1476 THE CHILDREN`S WORDL','Metropolitana','PEDRO AGUIRRE CERDA','Part. Pagado'),
('24742','ESCUELA ESPECIAL PARTICULAR CRECER','Metropolitana','RECOLETA','Part. Subvencionado'),
('24752','ESC.PARVULOS HERMANAS DE BETANIA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24754','CEIA GEORGINA SALAS DINAMARCA','Metropolitana','CERRO NAVIA','Servicio Local'),
('24755','ESCUELA ESPECIAL PART.CENTRO EDUC.RAYEN','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('24756','COLEGIO NAZARET DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24758','COLEGIO CRISTIANO BETHEL  N 3','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24759','ESC.NUESTRA SENORA DEL CARMEN DE CURACAV','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('24761','SAN JUAN DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('24762','COLEGIO SAINT MARY JOSEPH SCHOOL','Metropolitana','MACUL','Part. Pagado'),
('24763','LICEO ADULTOS PART.LAS AMERICAS MODERNAS','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('24765','ESCUELA DE PARV. LANCAHUE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24766','COLEGIO ALMENDRAL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24768','ESCUELA DE PARVULOS N°1213 LOS PATITOS DE SAN PATRICIO','Metropolitana','LAS CONDES','Part. Pagado'),
('24769','COLEGIO SAN ISAAC JOGUES','Metropolitana','QUILICURA','Part. Subvencionado'),
('24782','ESCUELA BÁSICA BARROS LUCO  Y ESPECIAL  DE LENGUAJE','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('24783','COLONIAL DE PIRQUE','Metropolitana','PIRQUE','Part. Pagado'),
('24790','COLEGIO EL PRADO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24795','COLEGIO EMAUS','Metropolitana','LAS CONDES','Part. Pagado'),
('24798','COLEGIO SANTA MARIA DE LO CANAS','Metropolitana','LA FLORIDA','Part. Pagado'),
('24800','COLEGIO FLORIDA HIGH SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24801','COLEGIO HENRY FAYOL','Metropolitana','ÑUÑOA','Part. Pagado'),
('24803','ESCUELA BASICA PART GRATUITA CASA AZUL','Metropolitana','LA GRANJA','Part. Subvencionado'),
('24804','ESCUELA ESPECIAL SGTO.CANDELARIA','Metropolitana','CERRO NAVIA','Servicio Local'),
('24806','ESCUELA DE PARVULOS N°1511 LA SEMILLITA','Metropolitana','CONCHALÍ','Part. Pagado'),
('24809','ESC. BASICA PART.JUANITA FERNANDEZ SOLAR','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24812','COLEGIO POLIV. SAN JOSE DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('24815','ESCUELA DE PARVULOS N°1515  HOSP. CLIN DE LA U. DE CHILE','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('24817','ESCUELA BASICA N°1517 MADRIGAL','Metropolitana','LA REINA','Part. Pagado'),
('24818','COLEGIO SUPERIOR CAMBRIDGE ANEXO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('24821','ESCUELA DE PARVULOS N°80 SANTA ROSA DE LIMA','Metropolitana','PUENTE ALTO','Part. Pagado'),
('24822','ESC. BAS. PDTE. SALVADOR ALLENDE G.','Metropolitana','EL BOSQUE','Servicio Local'),
('24826','COLEGIO NUESTRA SENORA DEL LORETO','Metropolitana','LAS CONDES','Part. Pagado'),
('24828','LICEO POLITEC.PARTIC.EL SENOR DE RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('24830','COLEGIO MAYA SCHOOL  ANEXO','Metropolitana','ÑUÑOA','Part. Pagado'),
('24832','INSTITUTO DOCENCIA','Metropolitana','LAS CONDES','Part. Pagado'),
('24836','COLEGIO SAN ISIDRO','Metropolitana','BUIN','Part. Pagado'),
('24840','COLEGIO DE ADULTOS INSTITUTO TABANCURA SEDE LONDRES','Metropolitana','SANTIAGO','Part. Pagado'),
('24842','COLEGIO LA FONTAINE','Metropolitana','ÑUÑOA','Part. Pagado'),
('24843','COLEGIO POLIV. SAN LUIS BELTRAN','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24850','ESCUELA DE PARVULOS N°1527 ALEXANDER MONTESSORI','Metropolitana','LAS CONDES','Part. Pagado'),
('24856','COLEGIO TEGUALDA','Metropolitana','TALAGANTE','Municipal'),
('24857','COLEGIO CRECES ANEXO','Metropolitana','LAS CONDES','Part. Pagado'),
('24861','ESCUELA DE PARVULOS N°1532 LOS DOS RATONCITOS','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('24864','COLEGIO SAN CRISTOBAL DE LAS CASAS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24868','ES.ESP.PART.PUERTA ABIERTA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('24873','COLEGIO  EPULLAY','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('24874','COLEGIO SAN BARTOLOME DE NOS','Metropolitana','CALERA DE TANGO','Part. Pagado'),
('24875','ESCUELA  ESPECIAL PART.PUDAHUEL NORTE','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24876','ESC.BASICA PROF.AURELIA ROJAS BURGOS','Metropolitana','LA PINTANA','Servicio Local'),
('24878','CENTRO EDUCACIONAL FERNANDO DE ARAGON','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24879','ESCUELA ESPECIAL PART.ARNOLD GESELL II','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24880','ESCUELA ESPECIAL GUENIPILLAN','Metropolitana','LA GRANJA','Part. Subvencionado'),
('24881','ESCUELA BASICA ESCRITOR PABLO NERUDA','Metropolitana','QUILICURA','Part. Subvencionado'),
('24882','CENTRO DE TRASTORNOS DE LA COMUNICACION','Metropolitana','HUECHURABA','Part. Subvencionado'),
('24883','ESCUELA BÁSICA MUNICIPAL SAN LUIS','Metropolitana','MAIPÚ','Servicio Local'),
('24884','COLEGIO ALCAZAR DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('24885','COLEGIO KING SCHOOL CORDILLERA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24889','LICEO BICENTENARIO MONSENOR ENRIQUE ALVEAR','Metropolitana','PUDAHUEL','Servicio Local'),
('24892','SANTA CRUZ COLLEGE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24893','ESCUELA NOVOMAR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24894','COLEGIO ARAUCARIA CORDILLERA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24896','INSTITUTO DE TABANCURA DE PROVIDENCIA','Metropolitana','PROVIDENCIA','Part. Pagado'),
('24897','COLEGIO FARMLAND SCHOOL','Metropolitana','CURACAVÍ','Part. Pagado'),
('24898','COLEGIO SAN FRANCISCO MISIONERO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24900','LICEO HUMBERTO DIAZ CASANUEVA','Metropolitana','COLINA','Municipal'),
('24903','COLEGIO MADRE DE JESUS','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('24904','ESCUELA DE PARVULOS N°1552 LOS PICAPIEDRAS','Metropolitana','CONCHALÍ','Part. Pagado'),
('24906','ESCUELA BASICA N°71 DOLMEN SCHOOL','Metropolitana','CURACAVÍ','Part. Pagado'),
('24907','COLEGIO ALMENAR DE PIRQUE','Metropolitana','PIRQUE','Part. Pagado'),
('24908','COLEGIO PEDRO DE VALDIVIA LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('24911','LICEO DE ADULTOS PART.FERMIN VIVACETA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('24912','COLEGIO SANTA MONICA DE MELIPILLA','Metropolitana','MELIPILLA','Part. Pagado'),
('24913','COLEGIO NUESTRA SENORA DE LA MERCED','Metropolitana','MELIPILLA','Part. Subvencionado'),
('24916','ESCUELA BASICA TACORA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24920','ESC. BAS. PART. ALBERT SCHWITZER LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24925','ESCUELA DE PARVULOS N°1558 ARLEQUIN','Metropolitana','LAS CONDES','Part. Pagado'),
('24926','CENTRO EDUCACIONAL DE ADULTOS','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('24927','COLEGIO SAN  ANSELMO','Metropolitana','COLINA','Part. Pagado'),
('24930','CENTRO EDUCACIONAL FUNDACION PAULA JARAQUEMAD','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('24931','ESC.PART.ALVARO COVARRUBIAS ARLEGUI','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('24932','ESC.ESPECIAL PARTICULAR PALABRAS MAGICAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24933','INSTITUTO SAN SEBASTIAN DE PROVIDENCIA','Metropolitana','PROVIDENCIA','Part. Pagado'),
('24935','COLEGIO POLIV. SIEMBRA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24937','ESC DE PARVULOS PART.EJERCITO DE SALVACION','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('24939','ESC. ESP.NUESTRA  SENORA DE SAN GERONIMO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24942','ESCUELA ESP. PART. EL MONTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('24944','COLEGIO NUESTRA SEÑORA DEL CAMINO','Metropolitana','LA REINA','Part. Pagado'),
('24946','COLEGIO JORGE HUNEEUS ZEGERS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24948','ESCUELA DE PARVULOS N°1565 JARDIN INFANTIL TUPAHUE WENUI','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('24952','ESCUELA ESPECIAL PARTICULAR ARCA DE NOE','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('24954','COLEGIO EL REDENTOR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('24956','COLEGIO TECNICO PROFESIONAL NOCEDAL','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24957','ESC. ESPECIAL PLANETA DE LOS NIÑOS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('24959','ESCUELA INTERCULTURAL KALLFÜ MAPU','Metropolitana','ÑUÑOA','Municipal'),
('24960','ESCUELA BASICA PARTICULAR HORIZONTE 11','Metropolitana','CERRO NAVIA','Part. Subvencionado'),
('24961','ESC.PARVULOS RENACER ALBORADA','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24963','COLEGIO BICENTENARIO DE SANTA MARIA DE EL MONTE','Metropolitana','EL MONTE','Part. Subvencionado'),
('24966','COLEGIO SAN FELIPE','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('24968','ESC.TRASTORNOS DE LA EDUCACION AURORA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('24971','COLEGIO EL ENCUENTRO','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('24972','ESCUELA BAS. NUESTRA SENORA MARIA INMACULADA','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('24976','COLEGIO SAN FELIPE DIACONO','Metropolitana','CALERA DE TANGO','Part. Pagado'),
('24977','COLEGIO MAYOR TOBALABA','Metropolitana','PUENTE ALTO','Part. Pagado'),
('24978','COLEGIO PART.POLITECNICO EYZAGUIRRE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24979','COLEGIO LOS ALERCES','Metropolitana','LO BARNECHEA','Part. Pagado'),
('24980','ESCUELA ESPECIAL PART.ANA CRUCHAGA T.','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24983','ESCUELA BASICA N°102 QUERUBIN SCHOOL','Metropolitana','PUENTE ALTO','Part. Pagado'),
('24985','COLEGIO KENDAL ENGLISH SCHOOL ANEXO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('24986','COLEGIO CENTENARIO','Metropolitana','MAIPÚ','Part. Pagado'),
('24987','ESCUELA ANDES DEL SUR','Metropolitana','PUENTE ALTO','Municipal'),
('24988','COLEGIO ALMENAR DEL MAIPO','Metropolitana','PUENTE ALTO','Part. Pagado'),
('24989','COMPLEJO EDUC. LUIS PASTEUR, ANEXO','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('24995','COLEGIO SAN FERNANDO DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('24997','ESCUELA SANTA MARIA DE PENALOLEN','Metropolitana','PEÑALOLÉN','Municipal'),
('24999','ESCUELA PROFESORA MARIA LUISA SEPULVEDA','Metropolitana','QUILICURA','Servicio Local'),
('25001','COLEGIO GREENLAND SCHOOL','Metropolitana','ESTACIÓN CENTRAL','Part. Pagado'),
('25002','ESCUELA BASICA PADRE ALBERTO HURTADO','Metropolitana','PUENTE ALTO','Municipal'),
('25005','ESC. BAS.SAN AGUSTIN DE CERRILLOS','Metropolitana','CERRILLOS','Part. Subvencionado'),
('25009','LICEO VALLE DE LLUTA','Metropolitana','SAN BERNARDO','Servicio Local'),
('25012','COLEGIO PART.SAN SEBASTIAN DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25014','CENTRO DE EDUCACION PAULA JARAQUEMADA','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('25015','CENTRO DE LENGUAJE MARCELA PAZ','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('25017','ESC. BAS. PATR. WILLINS HOOVER KURT','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25022','ESCUELA ESPECIAL PARTICULAR MILLANTU','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25026','COLEGIO POLIV. FRANCISCO DE VILLAGRA','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25027','COLEGIO POLIV. NUEVA NAZARET','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25028','CENTRO EDUC. DIEGO DE ALMAGRO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25030','CTRO. ESTIMULAC. DEL LENGUAJE CELQUI','Metropolitana','QUILICURA','Part. Subvencionado'),
('25031','ESCUELA ESPECIAL PART. VOCES','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25032','COLEGIO POLIVALENTE SEMBRADOR','Metropolitana','COLINA','Part. Subvencionado'),
('25034','ESCUELA BASICA PART. LAS PLEYADES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25036','ESCUELA ESPECIAL PARTICULAR  AUMEN','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25038','COLEGIO JOSE M.BALMACEDA DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25039','ESC. BAS.PART.FRANCISCO DE AGUIRRE','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25041','COLEGIO MARIA ELENA','Metropolitana','LA FLORIDA','Municipal'),
('25042','ESCUELA BASICA LOS BOSQUINOS','Metropolitana','MAIPÚ','Servicio Local'),
('25043','ESCUELA VOLCAN SAN JOSE','Metropolitana','PUENTE ALTO','Municipal'),
('25046','CENTRO PROFES..DE ESTIMULOS DE LENGUAJE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25047','ESCUELA ANTILHUE DE PUDAHUEL','Metropolitana','PUDAHUEL','Servicio Local'),
('25048','COLEGIO CASTELGANDOLFO','Metropolitana','PADRE HURTADO','Part. Pagado'),
('25050','COLEGIO PARTICULAR SAN MATEO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25054','COLEGIO DE ADULTOS CASA DE ESTUDIOS FUTURO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('25055','COLEGIO INSTITUCION TERESIANA','Metropolitana','LAS CONDES','Part. Pagado'),
('25057','COLEGIO DE ADULT.ACADEMIA ESTUDIOS MIRAFLORES','Metropolitana','SANTIAGO','Part. Pagado'),
('25058','COLEGIO LA CANTERA','Metropolitana','ÑUÑOA','Part. Pagado'),
('25059','CENTRO EDUCACIONAL LARUN RAYUN','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25061','COLEGIO POLIVALENTE RAULÍ','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25062','ESCUELA BÁSICA N°993 ANTONIO BORQUEZ SOLAR ANEXO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25065','COLEGIO PEDRO DE VALDIVIA -PEÑALOLEN','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('25070','COLEGIO NAVARRA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25071','LICEO JOSE ABELARDO NUNEZ Nº5','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25073','SANTA MARIA DEL PILAR DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25075','ESC.ESP.TRAT.DE LA COMUNICION EDEN','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25078','ESCUELA PART.COMANDANTE CARLOS CONDELL','Metropolitana','SAN BERNARDO','Servicio Local'),
('25079','ESCUELA ESPECIAL PART.JESUS NAZARENO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25080','ESCUELA ESPECIAL PARTICULAR ANTAI','Metropolitana','BUIN','Part. Subvencionado'),
('25082','COLEGIO BICENTENARIO APRENDER','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25084','ESCUELA RUDOLF DECK WERTH','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25085','CENTRO EDUCACIONAL RENCA','Metropolitana','RENCA','Part. Subvencionado'),
('25087','COLEGIO NOBEL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25089','LICEO LOS JAZMINES','Metropolitana','MELIPILLA','Municipal'),
('25091','ESC. BASICA BOSTON COLLEGE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25092','ESCUELA ESPECIAL PARTICULAR PALOMAR','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25093','ESCUELA DE PARVULOS N°1616 GRACE GARDEN','Metropolitana','LAS CONDES','Part. Pagado'),
('25094','COLEGIO PART.SAN ESTEBAN DE LAS VISCACHA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25095','COLEGIO PARTICULAR LAS ACACIAS DE MELIPILLA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('25098','ESC. BAS. EJERCITO DE SALVACION','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25099','COLEGIO DE ADULTOS INSTITUTO ANDES','Metropolitana','SANTIAGO','Part. Pagado'),
('25101','COLEGIO CORONEL ELEUTERIO RAMIREZ MOLINA','Metropolitana','LA REINA','Part. Subvencionado'),
('25103','ESC. ESPEC. CAMPANITA DE LA GRANJA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25107','COLEGIO MAIMONIDES SCHOOL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('25109','ESCUELA ESPECIAL PAR. CELQUI','Metropolitana','QUILICURA','Part. Subvencionado'),
('25111','ESCUELA DE PARVULOS N° 1624 BARRIE MONTESSORI','Metropolitana','LA REINA','Part. Pagado'),
('25112','ESCUELA PART. PEHUEN','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25114','ESC. BASICA PART.IBEROAMERICANO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25115','ESCUELA ESPECIAL PARTICULAR PIPAN','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25117','T Y C SPECIAL SCHOOL','Metropolitana','QUILICURA','Part. Subvencionado'),
('25118','ESC.DE TRAST.PRIM. DE LA COM.CHACABUCO','Metropolitana','COLINA','Part. Subvencionado'),
('25119','ESCUELA ESPECIAL PARTICULAR GENESIS','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25121','COLEGIO SAN ANTONIO DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('25125','ESCUELA DE PARVULOS ALADDIN','Metropolitana','RECOLETA','Part. Subvencionado'),
('25127','COLEGIO LEONARDO DA VINCI','Metropolitana','TALAGANTE','Part. Pagado'),
('25129','ESCUELA BASICA SAINT FRANCIS COLLEGE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25130','COLEGIO LOS CEIBOS','Metropolitana','TALAGANTE','Part. Pagado'),
('25131','ESC ESP Nº 1637 MAGDALENA AVALOS CRUZ ASPAUT','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25132','ESCUELA PART. MASTER SCHOOL DE LAMPA','Metropolitana','LAMPA','Part. Subvencionado'),
('25134','COLEGIO AMERICAN BRITISH SCHOOL','Metropolitana','LA FLORIDA','Part. Pagado'),
('25136','COMPLEJO EDUCACIONAL SAN ALFONSO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25138','COLEGIO ALBERT EINSTEIN','Metropolitana','RECOLETA','Part. Subvencionado'),
('25142','COLEGIO ANDINO ANTILLANCA','Metropolitana','LAS CONDES','Part. Pagado'),
('25143','COLEGIO SAN FRANCISCO JAVIER DE HUECHURABA','Metropolitana','HUECHURABA','Part. Pagado'),
('25145','ESCUELA ESPECIAL PARTICULAR ANTIRAY','Metropolitana','PAINE','Part. Subvencionado'),
('25153','COLEGIO PARTICULAR NUEVA ERA SIGLO XXI','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25154','ESCUELA ESPECIAL PARTICULAR LUNA NUEVA','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25155','ESC. PARTICULAR ALFARERO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25157','ESC. BAS. PARTICULAR 1650 MIRAVALLE','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25158','ESCUELA DE PARVULOS PULGARCITO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25160','COLEGIO VICTORIANO','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25162','ESC. PARTICULAR RAIN - BOW','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25166','COLEGIO PART. LOS OLMOS DE PTE. ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25171','CENTRO EDUC. PRINCIPADO DE ASTURIAS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25172','COLEGIO PUMAHUE','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('25173','ESC. BASICA MUNICIPAL RISOPATRON','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('25175','COLEGIO SAN NICOLAS DE MAIPU','Metropolitana','MAIPÚ','Part. Pagado'),
('25179','ESC.ESPECIAL NUESTRA SRA.DEL PILAR','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25180','COLEGIO RAYEN MAHUIDA','Metropolitana','COLINA','Part. Pagado'),
('25182','LICEO ALCALDE JORGE INDO','Metropolitana','QUILICURA','Servicio Local'),
('25185','COLEGIO PARTICULAR OZANAM','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25186','COLEGIO MUNIC.  SAN SEBASTIAN DE RINCONADA','Metropolitana','MAIPÚ','Servicio Local'),
('25187','ESCUELA ESPECIAL PARTICULAR N_ 1666 SANDELI','Metropolitana','MACUL','Part. Subvencionado'),
('25188','ESCUELA BÁSICA Y ESPECIAL N°90 AMANECER','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25189','ESCUELA BASICA FUTURO LAS MERCEDES','Metropolitana','ISLA DE MAIPO','Municipal'),
('25190','COLEGIO ADUL. INSTITUTO TABANCURA DE VITACURA','Metropolitana','VITACURA','Part. Pagado'),
('25191','ESC. ESPECIAL HERNAN LARRAIN PERO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25192','ESCUELA ESP. SAN NECTARIO','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('25194','ESCUELA MUNICIPAL VALLE DE LUNA','Metropolitana','QUILICURA','Servicio Local'),
('25196','PIERRE TEILHARD DE CHARDIN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25197','COL.PARTICULAR SAN VALENTIN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25198','COLEGIO SANTA MARIA DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25199','COLEGIO AMANCAY DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25201','ESCUELA BAS. Y ESP. N_ 115 RENACER','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25202','COLEGIO  PUMAHUE HUECHURABA','Metropolitana','HUECHURABA','Part. Pagado'),
('25204','ESC.ESP.ONCOL.HOSP.ROBERTO DEL RIO','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('25208','ESC. ESP. NTRA SRA. DEL BUEN CONSEJO','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25209','COLEGIO ESPECIAL FUNDAC.NUESTROS HIJOS','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25210','ESC. BASICA N_ 116 ONCOLOG. DR. SOTERO DEL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25211','ESCUELA PART.ESPECIAL CORPAMEG','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25212','INSTITUTO NACIONAL DE REHABILITACION PAC','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25213','COLEGIO HOSPITAL SAN BORJA ARRIARAN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25215','COLEGIO POLIV. GERONIMO DE ALDERETE','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25216','ESC. ESPECIAL SAN ANTONIO DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25217','ESC. ESPECIAL ARTESANOS DE LA VIDA','Metropolitana','RENCA','Part. Subvencionado'),
('25218','EXTREMADURA DE PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25219','ESC. ESPEICIAL VOCES II','Metropolitana','RENCA','Part. Subvencionado'),
('25220','COLEGIO ALMA MATER','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25221','COLEGIO  PABLO APOSTOL','Metropolitana','LA FLORIDA','Part. Pagado'),
('25222','ESC. ESPECIAL 120 MULTIVERSO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25223','COLEGIO MONTE DE ASIS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25224','COLEGIO BERTAIT COLLEGE','Metropolitana','LO BARNECHEA','Part. Pagado'),
('25225','ESCUELA BASICA RAYITO DE LUZ DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25226','ESC. PART. SAN FCO. DE ASIS PARA NINOS SORDOS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25227','ESCUELA ESPECIAL MADRE TERESA DE CALCUTA','Metropolitana','LO ESPEJO','Part. Subvencionado'),
('25230','ESC.BAS.Y ESP.INTEGRAL STA. ROSA DE CHENA.','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25232','ESC. ESP. PART SERAFIN DE MACUL','Metropolitana','MACUL','Part. Subvencionado'),
('25235','LICEO DE ADULTOS POETA VICENTE HUIDOBRO','Metropolitana','QUILICURA','Servicio Local'),
('25236','ESCUELA ESPECIAL PALABRAS MAGICAS','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25237','COLEGIO DE ADULTOS GLADYS LAZO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25238','COLEGIO CENTRO EDUCACIONAL ALTAIR','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25241','COLEGIO SAINT JAMES SCHOOL','Metropolitana','BUIN','Part. Pagado'),
('25247','COLEGIO ALICURA','Metropolitana','PEÑALOLÉN','Municipal'),
('25249','COLEGIO PARTICULAR TANTAUCO  EL BOSQUE','Metropolitana','EL BOSQUE','Part. Pagado'),
('25250','COLEGIO POLIV. ALMENDRAL DE LA PINTANA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25255','ESCUELA INMACULADA CONCEPCION','Metropolitana','COLINA','Part. Subvencionado'),
('25256','ESCUELA BASICA THE FOREST COLLEGE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25258','COLEGIO PREMILITAR GENERAL SAN MARTIN DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25260','ESC.ESPECIAL LOS COPIHUES DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25263','ESC.ESP.EL PRINCIPITO DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25264','ESCUELA ESPECIAL DE LENGUAJE RAYUN','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('25265','COLEGIO ANTIL MAWIDA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('25270','COLEGIO PART. DE ADULTOS ITSA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25271','PROFESOR FRANCISCO VERGARA BOBADILLA','Metropolitana','LA FLORIDA','Municipal'),
('25272','ESC.PARVULOS PARTICULAR  LOS ANGELITOS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25273','ESCUELA ESP. PART. EDUC. LAUDELINA ARANEDA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25277','ESCUELA ESPECIAL SANTIAGO APOSTOL','Metropolitana','SANTIAGO','Corp. Municipal'),
('25278','COLEGIO CAMPANARIO','Metropolitana','BUIN','Part. Pagado'),
('25279','ESCUELA PARTICULAR SALVADOR DALI','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25280','ESCUELA BASICA PARTICULAR BREMEN','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25281','ESCUELA ESPECIAL BAULIRURIRU','Metropolitana','LAS CONDES','Part. Subvencionado'),
('25282','COLEGIO POLIV. CARDENAL RAUL SILVA HENRIQUEZ','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25283','ESC.PART.ESPECIAL LA CONCEPCION DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('25284','ESUELA ESPECIAL DE LENGUAJE PIRAMIDE','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('25286','ESCUELA PARTICULAR  COMUNICATE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25287','ESCUELA BASICA PARTICULAR ESJELAVI','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25288','ESC. BAS. Y ESP. CENTRO INTEGRAL ALTAIR DE BA','Metropolitana','LAMPA','Part. Subvencionado'),
('25289','ESC. DE PARV. Y ESP. LUIS SEMBRADOR','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25290','ESCUELA BASICA PARTICULAR EL REY','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25296','ESC. ESPEC. LENGUAJE LOS CHIQUITINES','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25297','ESCUELA ESPECIAL Y LENGUAJE ROCIO','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('25298','ESCUELA ESPECIAL PARTICULAR LUDILEN','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25300','COLEGIO NUEVOS CASTANOS DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25301','ESC.ESPEC.SAGRADA FAMILIA DE MAIPU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25302','ESCUELA ESPECIAL STELLA MARIS DE NUNOA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('25303','CENTRO EDUCACIONAL LAURA VICUNA','Metropolitana','RENCA','Part. Subvencionado'),
('25304','COLEGIO PAUL HARRIS SCHOOL','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25305','ESCUELA ESPECIAL ARCOIRIS DE EL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25306','ESCUELA ESPECIAL TODOS LOS SANTOS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25310','COLEGIO SAN NICOLÁS DIÁCONO','Metropolitana','COLINA','Part. Pagado'),
('25314','ESCUELA BÁSICA 1737 LOS ALERCES DE MAIPÚ','Metropolitana','MAIPÚ','Servicio Local'),
('25315','ESCUELA PUERTO FUTURO','Metropolitana','PUDAHUEL','Servicio Local'),
('25316','COLEGIO PUELMAPU','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('25317','ESC. ESP. PART, PALOMAR DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25319','ESC. BAS. Y ESP. PART. KIMKELEN','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25320','ESCUELA  ESPEC. VIRGEN DE LAS PENAS','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25322','CENTRO EDUCACIONAL DE ADULTOS RAFAEL SOTOMAYO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25324','ESCUELA BASICA QUITALMAHUE','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25327','ESC. ESPEC. PART. LAS CAMELIAS','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('25328','INSTITUTO CRISTIANO LUIS GANDARILLAS','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25329','COLEGIO SANTA CRUZ DE CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('25330','COLEGIO POLIVALENTE ANTARES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25331','ESCUELA BASICA PART. CRISTIANO DE LOS HEROES','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25332','COLEGIO MONTESSORI PUCALAN','Metropolitana','COLINA','Part. Pagado'),
('25333','ESC. ESPECIAL PART. MARTA Y BERTA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25334','ESCUELA BASICA RAICES ALTAZOR','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25339','LICEO MUNICIPAL DE ADULTO MIGUEL CAMPINO LARRAIN','Metropolitana','PAINE','Corp. Municipal'),
('25342','ESCUELA RAIMAPU-TIERRA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25344','COLEGIO ALAMIRO PEREZ','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25347','COLEGIO SEBASTIAN EL CANO SAN BERNARDO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25348','COLEGIO  SAN JOSE DE CHICUREO','Metropolitana','COLINA','Part. Pagado'),
('25349','COLEGIO PARTICULAR MELFORD COLLEGE','Metropolitana','QUILICURA','Part. Subvencionado'),
('25350','ESC. PART. CRISTIANO ORIENTE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25351','ESCUELA ESPECIAL PARTICULAR KIMANTU','Metropolitana','CALERA DE TANGO','Part. Subvencionado'),
('25352','LICEO BICENTENARIO DE EXCELENCIA PATRICIO MEKIS DE PADRE HURTADO','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('25353','ESCUELA ESPECIAL DEL LENGUAJE ROMIYANCO','Metropolitana','BUIN','Part. Subvencionado'),
('25354','ESCUELA ESPECIAL JESUS DEL BOSQUE','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25355','ESC. DE PARVULOS PART 103 EL PRINCIPITO DE LO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25356','ESC. BASICA LA PRADERA DE CURACAVI','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('25358','ESCUELA ESPECIAL CAPULLITO','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25359','COLEGIO METODISTA DE SANTIAGO','Metropolitana','SANTIAGO','Part. Subvencionado'),
('25361','ESCUELA ESP. PART.  ANTUKUYEN','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('25362','ESC.PART. TALLERES PREVOCACIONALES PADRE HURT','Metropolitana','RENCA','Part. Subvencionado'),
('25363','ESC. ESP. PUERTA DEL SOL','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('25364','ESCUELA ESPECIAL N°104  SANTA MARIA DE VINCULO','Metropolitana','PAINE','Part. Subvencionado'),
('25365','COLEGIO AUSTRALIA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('25366','COLEGIO  LATINOAMERICANO','Metropolitana','LA FLORIDA','Part. Pagado'),
('25367','COLEGIO SANTIAGO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25368','COLEGIO BICENTENARIO DE EXCELENCIA CARDENAL CARLOS OVIEDO CAVADA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25369','COLEGIO PARTICULAR ALICANTE','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25370','ESCUELA ESPECIAL MISTRAL','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('25371','COLEGIO BICENTENARIO SANTA MARIA DE PAINE','Metropolitana','PAINE','Part. Subvencionado'),
('25372','ESCUELA DE PARVULOS N° 1759 ANTINIL N° 3','Metropolitana','LA REINA','Part. Pagado'),
('25373','COLEGIO SAN RAFAEL ARCANGEL','Metropolitana','LA REINA','Part. Pagado'),
('25375','ESCUELA ESPECIAL N°1761 MI PEQUEÑO COLIBRI PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25376','ESCUELA ESPECIAL NUEVA CORDILLERA N_ 1762','Metropolitana','LAS CONDES','Part. Subvencionado'),
('25377','ESCUELA ESPECIAL PARTICULAR DESPERTARES','Metropolitana','LA GRANJA','Part. Subvencionado'),
('25379','ESCUELA DE PARVULOS N°1765 KIMN','Metropolitana','SANTIAGO','Part. Pagado'),
('25381','ESC. ESPECIAL PART. REYES DE ESPANA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25382','COLEGIO SAINT CHARLES COLLEGE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25383','ESC. ESP. CENT. DES. INTEG. DE LA COMUN. ADON','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25384','ESCUELA ESPECIAL 1768 RENACER','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('25385','ESCUELA HERMANOS CARRERA','Metropolitana','MAIPÚ','Part. Subvencionado'),
('25386','COLEGIO PARTICULAR NOVO MUNDO','Metropolitana','QUILICURA','Part. Subvencionado'),
('25387','COLEGIO PARTICULAR SAN SEBASTIAN DE QUILICURA','Metropolitana','QUILICURA','Part. Subvencionado'),
('25389','COLEGIO `EMPRENDER OBISPO ALVEAR`','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('25390','ESC.BASICA PART. ACONCAGUA DE PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('25392','ESCUELA ESPECIAL PARTICULAR ANGELES','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('25393','COLEGIO QUINTO CENTENARIO CORDILLERA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('25394','ESC. ESP. NINOS DE LA LUNA','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('25395','COLEGIO BETTERLAND SCHOOL','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('25396','CENTRO POLITECNICO PARTICULAR CONCHALI','Metropolitana','CONCHALÍ','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
