-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 5 de 31 | filas 1601-2000
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('2443','LICEO INDUSTRIAL DE SAN FERNANDO','O''Higgins','SAN FERNANDO','Adm. Delegada'),
('2444','INSTITUTO COMERCIAL ALBERTO VALENZUELA LLANOS DE SAN FERNANDO','O''Higgins','SAN FERNANDO','Servicio Local'),
('2447','LICEO DE HOMBRES NEANDRO SCHILLING','O''Higgins','SAN FERNANDO','Servicio Local'),
('2448','LICEO EDUARDO CHARME','O''Higgins','SAN FERNANDO','Servicio Local'),
('2453','LICEO JOSÉ GREGORIO ARGOMEDO','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('2454','SAN FERNANDO COLLEGE','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('2455','COLEGIO INMACULADA CONCEPCION','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('2456','ESCUELA OLEGARIO LAZO BAEZA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2457','ESCUELA BASICA ISABEL LA CATOLICA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2458','ESCUELA JORGE MUNOZ SILVA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2459','COLEGIO GIUSEPPE BERTOLUZZI DE FELIP','O''Higgins','SAN FERNANDO','Servicio Local'),
('2460','ESCUELA MARIA LUISA BOUCHON','O''Higgins','SAN FERNANDO','Servicio Local'),
('2461','ESCUELA VILLA CENTINELA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2462','ESCUELA WASHINGTON OMAR VENEGAS','O''Higgins','SAN FERNANDO','Servicio Local'),
('2463','COLEGIO HERMANO FERNANDO DE LA FUENTE','O''Higgins','SAN FERNANDO','Servicio Local'),
('2464','ESCUELA JOSE DE SAN MARTIN','O''Higgins','SAN FERNANDO','Servicio Local'),
('2465','ESCUELA CONCENTRAC. RURAL SERGIO VERDUGO HERRERA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2467','ESCUELA BAS.ABEL BOUCHON FAURE','O''Higgins','SAN FERNANDO','Servicio Local'),
('2469','ESCUELA ABRAHAM LINCOLN DE AGUA BUENA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2470','ESCUELA BAS.SAN JOSE DE LOS LINGUES','O''Higgins','SAN FERNANDO','Servicio Local'),
('2471','ESCUELA BERNARDO MORENO FREDES','O''Higgins','SAN FERNANDO','Servicio Local'),
('2472','ESCUELA BASICA ANTONIO LARA MEDINA','O''Higgins','SAN FERNANDO','Servicio Local'),
('2475','ESCUELA LOS MAQUIS','O''Higgins','MALLOA','Corp. Municipal'),
('2476','ESCUELA BASICA GASPAR MARIN','O''Higgins','SAN FERNANDO','Servicio Local'),
('2482','FUNDACION EDUCACIONAL INSTITUTO SAN FERNANDO','O''Higgins','SAN FERNANDO','Part. Pagado'),
('2485','LICEO AGRICOLA EL CARMEN','O''Higgins','SAN FERNANDO','Adm. Delegada'),
('2486','LICEO MUNICIPAL COMPLEJO EDUC. CHIMBARONGO','O''Higgins','CHIMBARONGO','Servicio Local'),
('2487','ESCUELA BAS.FERNANDO ARENAS ALMARZA','O''Higgins','CHIMBARONGO','Servicio Local'),
('2488','ESCUELA MUNICIPAL E-456','O''Higgins','CHIMBARONGO','Servicio Local'),
('2489','ESCUELA BAS. VILLA CONVENTO VIEJO','O''Higgins','CHIMBARONGO','Servicio Local'),
('2490','ESCUELA MUNICIPAL TINGUIRIRICA ALTO F-411','O''Higgins','CHIMBARONGO','Servicio Local'),
('2491','ESCUELA MUNICIPAL LAS QUEZADAS F-413','O''Higgins','CHIMBARONGO','Servicio Local'),
('2492','ESCUELA MUNICIPAL F415 LO GONZALEZ','O''Higgins','CHIMBARONGO','Servicio Local'),
('2493','ESCUELA BAS. JOSE MIGUEL CARRERA VERDUGO','O''Higgins','CHIMBARONGO','Servicio Local'),
('2494','ESCUELA MUNICIPAL F449 PEOR ES NADA','O''Higgins','CHIMBARONGO','Servicio Local'),
('2495','ESCUELA MUNICIPAL F451 CODEGUA','O''Higgins','CHIMBARONGO','Servicio Local'),
('2496','ESCUELA MUNICIPAL F452 SANTA VALENTINA','O''Higgins','CHIMBARONGO','Servicio Local'),
('2498','ESCUELA MUNICIPAL EL ROMERAL F-455','O''Higgins','CHIMBARONGO','Servicio Local'),
('2500','ESCUELA MUNICIPAL G414 BARRIO ESTACION','O''Higgins','CHIMBARONGO','Servicio Local'),
('2501','ESCUELA BAS. PEDRO ETCHEVERRY','O''Higgins','CHIMBARONGO','Servicio Local'),
('2505','ESCUELA MUNICIPAL G448 HUEMUL','O''Higgins','CHIMBARONGO','Servicio Local'),
('2506','ESCUELA MUNICIPAL G453 SAN JOSE DE LO TORO','O''Higgins','CHIMBARONGO','Servicio Local'),
('2507','ESCUELA MUNICIPAL','O''Higgins','CHIMBARONGO','Servicio Local'),
('2508','ESCUELA SANTA EUGENIA','O''Higgins','CHIMBARONGO','Servicio Local'),
('2509','ESCUELA MUNICIPAL SANTA ISABEL G-503','O''Higgins','CHIMBARONGO','Servicio Local'),
('2513','ESCUELA MUNICIPAL LAS MERCEDES G-507','O''Higgins','CHIMBARONGO','Servicio Local'),
('2514','ESCUELA AGRICOLA LAS GARZAS','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('2517','ESCUELA PARTICULAR MELECIA TOCORNAL','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('2518','LICEO SAN FRANCISCO','O''Higgins','PLACILLA','Servicio Local'),
('2519','ESCUELA BASICA RAUL CACERES PACHECO','O''Higgins','PLACILLA','Servicio Local'),
('2520','ESCUELA MUNICIPAL LA DEHESA','O''Higgins','PLACILLA','Servicio Local'),
('2521','ESCUELA MUNICIPAL LA TUNA','O''Higgins','PLACILLA','Servicio Local'),
('2522','ESCUELA MUNICIPAL SN LUIS DE MANANTIALES','O''Higgins','PLACILLA','Servicio Local'),
('2523','ESCUELA EL AMANECER','O''Higgins','PLACILLA','Servicio Local'),
('2524','ESCUELA DANY GERMAN GONZALEZ SOTO','O''Higgins','PLACILLA','Servicio Local'),
('2525','COLEGIO BASICO CONSOLIDADO','O''Higgins','NANCAGUA','Servicio Local'),
('2526','ESCUELA BAS. IGNACIO CARRERA PINTO','O''Higgins','NANCAGUA','Servicio Local'),
('2527','ESCUELA BÁSICA PUQUILLAY','O''Higgins','NANCAGUA','Servicio Local'),
('2528','ESCUELA BAS. ADRIANA LYON VIAL','O''Higgins','NANCAGUA','Servicio Local'),
('2529','ESCUELA MUNICIPAL YAQUIL','O''Higgins','NANCAGUA','Servicio Local'),
('2530','LICEO MUNICIPAL JUAN PABLO II','O''Higgins','NANCAGUA','Servicio Local'),
('2531','COLEGIO PARTICULAR EL PRINCIPITO','O''Higgins','NANCAGUA','Part. Subvencionado'),
('2532','COLEGIO LIBERTADOR O´HIGGINS DE CHEPICA','O''Higgins','CHÉPICA','Corp. Municipal'),
('2534','ESCUELA EUGENIO RUIZ-TAGLE MONTES','O''Higgins','CHÉPICA','Corp. Municipal'),
('2535','COLEGIO MUNICIPAL LAS ALAMEDAS','O''Higgins','CHÉPICA','Corp. Municipal'),
('2536','COLEGIO MUNICIPAL EMILIA SALINAS DIAZ','O''Higgins','CHÉPICA','Corp. Municipal'),
('2537','ESCUELA LUIS ATHAS','O''Higgins','CHÉPICA','Corp. Municipal'),
('2538','ESCUELA LINDORFO MONTERO FUENZALIDA','O''Higgins','CHÉPICA','Corp. Municipal'),
('2539','ESCUELA LUIS ARTURO ZUNIGA FUENTES','O''Higgins','CHÉPICA','Corp. Municipal'),
('2540','ESCUELA MARIA MARTA DEL REAL CORREA','O''Higgins','CHÉPICA','Corp. Municipal'),
('2541','ESCUELA HECTOR RODOLFO CASTILLO MORENO','O''Higgins','CHÉPICA','Corp. Municipal'),
('2542','ESCUELA LUZ MARIA CRESPO URETA DE KERESTEGIAN','O''Higgins','CHÉPICA','Corp. Municipal'),
('2543','ESCUELA CARLOS DONOSO REBOLLEDO','O''Higgins','CHÉPICA','Corp. Municipal'),
('2544','COLEGIO CRUZ MARIA','O''Higgins','CHÉPICA','Corp. Municipal'),
('2545','ESCUELA GABRIELA MISTRAL','O''Higgins','CHÉPICA','Corp. Municipal'),
('2548','ESCUELA ESTRELLA DE DAVID','O''Higgins','CHÉPICA','Corp. Municipal'),
('2549','COLEGIO LUIS ALEJANDRO ALVAREZ MUÑOZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2551','LICEO MUNICIPAL DE SANTA CRUZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2552','LICEO BICENTENARIO INSTITUTO POLITECNICO SANTA CRUZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2553','ESCUELA LUIS OYARZUN PEÑA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2554','ESCUELA ESPECIAL DE SANTA CRUZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2555','ESCUELA MARIA ARAYA VALDES','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2556','ESCUELA MUNICIPAL DE PANIAHUE','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2557','ESCUELA GRANJA ADEODATO GARCIA VALENZUELA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2558','ESCUELA LA FINCA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2559','ESCUELA MUNICIPAL DE BARREALES','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2560','ESC. MUNICIPAL LA LAJUELA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2561','ESCUELA MUNICIPAL DE QUINAHUE','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2562','ESCUELA MUNICIPAL DE ISLA DE YAQUIL','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2563','ESCUELA MUNICIPAL DE LA PATAGUA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2565','ESCUELA MUNICIPAL DE MILLAHUE DE APALTA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2566','ESCUELA MUNICIPAL DE CUNACO','O''Higgins','NANCAGUA','Servicio Local'),
('2568','ESCUELA MUNICIPAL DE PANAMA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2570','ESCUELA MUNICIPAL DE LOS MAITENES','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2572','ESCUELA MUNICIPAL DE RINCON DE YAQUIL','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2575','COLEGIO SAN GREGORIO','O''Higgins','NANCAGUA','Servicio Local'),
('2576','ESCUELA MUNICIPAL DE GUINDO ALTO','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2577','ESCUELA ANGEL ARRIGORRIAGA','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('2579','INSTITUTO REGIONAL FEDERICO ERRAZURIZ','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('2580','LICEO MARIA AUXILIADORA','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('2583','LICEO DE LOLOL','O''Higgins','LOLOL','Corp. Municipal'),
('2584','ESCUELA OCTAVIO MUJICA VALENZUELA','O''Higgins','LOLOL','Corp. Municipal'),
('2590','ESCUELA MUNICIPAL RINCONADA DE QUIAHUE','O''Higgins','LOLOL','Corp. Municipal'),
('2591','ESCUELA MUNICIPAL JUANA GONZALEZ','O''Higgins','LOLOL','Corp. Municipal'),
('2592','ESCUELA MUNICIPAL EDUVIGIS PANTOJA L','O''Higgins','LOLOL','Corp. Municipal'),
('2594','ESCUELA BASICA HUGO URZUA URZUA','O''Higgins','LOLOL','Corp. Municipal'),
('2598','ESCUELA BASICA OLGA DE GOMEZ','O''Higgins','LOLOL','Corp. Municipal'),
('2599','LICEO FRANCISCA DE PAULA SEGURA Y RUIZ','O''Higgins','PUMANQUE','Corp. Municipal'),
('2601','ESCUELA MUNICIPAL DE NILAHUE CORNEJO','O''Higgins','PUMANQUE','Corp. Municipal'),
('2603','ESCUELA MUNICIPAL DE MATA REDONDA','O''Higgins','PUMANQUE','Corp. Municipal'),
('2604','ESCUELA PENABLANCA','O''Higgins','PUMANQUE','Corp. Municipal'),
('2607','ESCUELA MUNICIPAL DE RINCON LOS PERALES','O''Higgins','PUMANQUE','Corp. Municipal'),
('2609','ESCUELA MUNICIPAL DE PALMILLA DE RETO','O''Higgins','PUMANQUE','Corp. Municipal'),
('2611','ESCUELA MARGOT LOYOLA PALACIOS','O''Higgins','PALMILLA','Corp. Municipal'),
('2612','LICEO SAN JOSE DEL CARMEN','O''Higgins','PALMILLA','Corp. Municipal'),
('2613','ESCUELA MUNICIPAL SANTA MATILDE','O''Higgins','PALMILLA','Corp. Municipal'),
('2615','ESCUELA JORGE ERRAZURIZ ECHEÑIQUE','O''Higgins','PALMILLA','Corp. Municipal'),
('2621','ESCUELA REBECA CADIZ VALENZUELA','O''Higgins','PALMILLA','Corp. Municipal'),
('2622','ESCUELA MUNICIPAL VALLE HERMOSO','O''Higgins','PALMILLA','Corp. Municipal'),
('2624','ESCUELA MUNICIPAL LIHUEIMO','O''Higgins','PALMILLA','Corp. Municipal'),
('2625','LICEO BICENTENARIO VICTOR JARA MARTINEZ','O''Higgins','PERALILLO','Corp. Municipal'),
('2626','COLEGIO MANUEL RODRIGUEZ ERDOIZA','O''Higgins','PERALILLO','Corp. Municipal'),
('2627','ESCUELA GUSTAVO RIVERA BUSTOS','O''Higgins','PERALILLO','Corp. Municipal'),
('2629','ESCUELA MUNICIPAL SARA RAVELLO PARRAGUEZ','O''Higgins','PERALILLO','Corp. Municipal'),
('2633','ESCUELA MARTA VALDES ECHEÑIQUE','O''Higgins','PERALILLO','Corp. Municipal'),
('2634','ESCUELA PABLO NERUDA','O''Higgins','PERALILLO','Corp. Municipal'),
('2635','LICEO AGUSTIN ROSS EDWARDS','O''Higgins','PICHILEMU','Corp. Municipal'),
('2636','ESCUELA PUEBLO DE VIUDAS','O''Higgins','PICHILEMU','Corp. Municipal'),
('2637','ESCUELA MUNICIPAL VILLA SAN PEDRO','O''Higgins','PAREDONES','Corp. Municipal'),
('2642','ESCUELA COGUIL','O''Higgins','PICHILEMU','Corp. Municipal'),
('2643','ESCUELA PADRE ALBERTO HURTADO C.','O''Higgins','PICHILEMU','Corp. Municipal'),
('2646','ESCUELA LA AGUADA','O''Higgins','PICHILEMU','Corp. Municipal'),
('2650','ESCUELA CAHUIL','O''Higgins','PICHILEMU','Corp. Municipal'),
('2652','ESCUELA CIRUELOS','O''Higgins','PICHILEMU','Corp. Municipal'),
('2654','COLEGIO LIBERTADORES','O''Higgins','PICHILEMU','Corp. Municipal'),
('2656','COLEGIO DE LA PRECIOSA SANGRE','O''Higgins','PICHILEMU','Part. Subvencionado'),
('2657','LICEO MUNICIPAL PABLO NERUDA','O''Higgins','NAVIDAD','Corp. Municipal'),
('2658','COLEGIO MUNICIPAL DIVINA GABRIELA','O''Higgins','NAVIDAD','Corp. Municipal'),
('2660','ESCUELA FRANCISCO CHAVEZ CIFUENTES','O''Higgins','NAVIDAD','Corp. Municipal'),
('2661','ESCUELA MUNICIPAL EL MANZANO','O''Higgins','NAVIDAD','Corp. Municipal'),
('2664','ESCUELA BASICA CONFEDERACION HELVETICA','O''Higgins','NAVIDAD','Corp. Municipal'),
('2666','ESCUELA MUNICIPAL LA BOCA DE RAPEL','O''Higgins','NAVIDAD','Corp. Municipal'),
('2673','ESCUELA MUNICIPAL PADRE ALBERTO HURTADO','O''Higgins','NAVIDAD','Corp. Municipal'),
('2678','ESCUELA MUNICIPAL MARIA WILLIAMS','O''Higgins','NAVIDAD','Corp. Municipal'),
('2681','LICEO BICENTENARIO EL ROSARIO','O''Higgins','LITUECHE','Corp. Municipal'),
('2682','ESCUELA MUNICIPAL QUELENTARO','O''Higgins','LITUECHE','Corp. Municipal'),
('2685','ESCUELA MUNICIPAL MATANCILLA','O''Higgins','LITUECHE','Corp. Municipal'),
('2686','ESCUELA MUNICIPAL PULIN','O''Higgins','LITUECHE','Corp. Municipal'),
('2687','ESCUELA MUNICIPAL PASO DEL SOLDADO','O''Higgins','LITUECHE','Corp. Municipal'),
('2692','ESCUELA MUNICIPAL MANQUEHUA','O''Higgins','LITUECHE','Corp. Municipal'),
('2694','ESCUELA PROF. MONICA SILVA GOMEZ','O''Higgins','LA ESTRELLA','Corp. Municipal'),
('2698','ESCUELA MUNICIPAL GUADALAO','O''Higgins','LA ESTRELLA','Corp. Municipal'),
('2700','ESCUELA MUNICIPAL LA AGUADA','O''Higgins','LA ESTRELLA','Corp. Municipal'),
('2701','LICEO MUNICIPAL INSTITUTO CARDENAL CARO','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2702','ESCUELA MUNICIPAL LA QUEBRADA','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2703','ESCUELA MUNICIPAL EL SAUCE','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2704','ESCUELA RENÉ CARVAJAL MADARIAGA','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2705','ESCUELA TRINIDAD','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2706','ESCUELA MUNICIPAL LO MARCHANT','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2707','ESCUELA MUNICIPAL NOBELES DE CHILE','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2708','ESCUELA MUNICIPAL PAILIMO','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2711','ESCUELA MUNICIPAL SAN MIGUEL VILUCO','O''Higgins','MARCHIHUE','Corp. Municipal'),
('2714','ESCUELA UNION DE MUJERES AMERICANAS','O''Higgins','PAREDONES','Corp. Municipal'),
('2715','ESC.BASICA MERCEDES URZUA DIAZ','O''Higgins','PAREDONES','Corp. Municipal'),
('2716','ESCUELA MUNICIPAL SAN PEDRO DE ALCANTARA','O''Higgins','PAREDONES','Corp. Municipal'),
('2717','ESCUELA MUNICIPAL ALBERTINA VALENZUELA','O''Higgins','PAREDONES','Corp. Municipal'),
('2719','ESCUELA LUIS ARTEMON PEREZ A.','O''Higgins','PAREDONES','Corp. Municipal'),
('2721','ESCUELA SANTA ANA DE LA POBLACION','O''Higgins','PAREDONES','Corp. Municipal'),
('2722','ESCUELA LOS COPIHUES DEL CALVARIO','O''Higgins','PAREDONES','Corp. Municipal'),
('2723','ESCUELA MUNICIPAL LOS BRIONES','O''Higgins','PAREDONES','Corp. Municipal'),
('2724','ESCUELA MUNICIPAL EL CARDAL','O''Higgins','PAREDONES','Corp. Municipal'),
('2725','ESCUELA MUNICIPAL LO VALDIVIA','O''Higgins','PAREDONES','Corp. Municipal'),
('2727','ESCUELA MUNICIPAL ESMERALDA','O''Higgins','PAREDONES','Corp. Municipal'),
('2728','ESCUELA LAS CARMELITAS','O''Higgins','PAREDONES','Corp. Municipal'),
('2730','CENTRO EDUCATIVO INTEGRAL DE CURICO (CEIC)','Maule','CURICÓ','Corp. Municipal'),
('2731','ESC.CAPLLAN JOSE LUIS LOPEZ CARRASCO','Maule','CURICÓ','Corp. Municipal'),
('2732','LICEO FERNANDO LAZCANO','Maule','CURICÓ','Corp. Municipal'),
('2733','COLEGIO DEPORTIVO LUIS CRUZ MARTINEZ','Maule','CURICÓ','Corp. Municipal'),
('2734','COLEGIO ALESSANDRI','Maule','CURICÓ','Corp. Municipal'),
('2735','ESCUELA PRESIDENTE J.M.BALMACEDA','Maule','CURICÓ','Corp. Municipal'),
('2736','ESCUELA PALESTINA','Maule','CURICÓ','Corp. Municipal'),
('2737','COLEGIO POLIVALENTE JAPÓN','Maule','CURICÓ','Corp. Municipal'),
('2738','ESCUELA REPUBLICA DE BRASIL','Maule','CURICÓ','Corp. Municipal'),
('2740','ESCUELA GRECIA','Maule','CURICÓ','Corp. Municipal'),
('2741','ESCUELA ERNESTO CASTRO ARELLANO','Maule','CURICÓ','Corp. Municipal'),
('2742','COLEGIO URUGUAY','Maule','CURICÓ','Corp. Municipal'),
('2744','ESCUELA ESPANA','Maule','CURICÓ','Corp. Municipal'),
('2745','ESCUELA CATALUNA','Maule','CURICÓ','Corp. Municipal'),
('2747','COLEGIO DE ARTE Y CULTURA SAN ANTONIO','Maule','CURICÓ','Corp. Municipal'),
('2748','ESCUELA REPUBLICA ARGENTINA','Maule','CURICÓ','Corp. Municipal'),
('2749','COLEGIO LOS CONQUISTADORES','Maule','CURICÓ','Corp. Municipal'),
('2750','ESCUELA MARIA INES RODRIGUEZ','Maule','CURICÓ','Corp. Municipal'),
('2751','CENTRO INTEGRADO DE EDUCACION DE ADULTOS DE CURICO','Maule','CURICÓ','Corp. Municipal'),
('2753','ESCUELA REPUBLICA ESTADOS UNIDOS','Maule','CURICÓ','Corp. Municipal'),
('2754','CENTRO EDUCATIVO POTRERO GRANDE','Maule','CURICÓ','Corp. Municipal'),
('2755','ESCUELA MARIA OLGA FIGUEROA LEYTON','Maule','CURICÓ','Corp. Municipal'),
('2756','ESCUELA DIEGO PORTALES P.','Maule','CURICÓ','Corp. Municipal'),
('2758','COLEGIO MULTICULTURAL RAYEN MAPU','Maule','CURICÓ','Corp. Municipal'),
('2759','ESCUELA EL MAITENAL','Maule','CURICÓ','Corp. Municipal'),
('2761','ESCUELA LA OBRA','Maule','CURICÓ','Corp. Municipal'),
('2762','ESCUELA EL PORVENIR','Maule','CURICÓ','Corp. Municipal'),
('2763','ESCUELA REPUBLICA DE ITALIA','Maule','CURICÓ','Corp. Municipal'),
('2764','ESCUELA ISLA DE MARCHANT','Maule','CURICÓ','Corp. Municipal'),
('2765','ESCUELA RAMON FREIRE','Maule','CURICÓ','Corp. Municipal'),
('2766','ESCUELA VICTOR VERGARA CAMPOS','Maule','CURICÓ','Corp. Municipal'),
('2767','ESCUELA LOS CRISTALES','Maule','CURICÓ','Corp. Municipal'),
('2768','ESCUELA JOSE D. MORALES DIAZ','Maule','CURICÓ','Corp. Municipal'),
('2771','ESCUELA PABLO NERUDA','Maule','CURICÓ','Corp. Municipal'),
('2775','ESCUELA MONTE OSCURO','Maule','CURICÓ','Corp. Municipal'),
('2776','ESCUELA EL MAITEN','Maule','CURICÓ','Corp. Municipal'),
('2780','ESCUELA HOLANDA','Maule','CURICÓ','Corp. Municipal'),
('2782','COLEGIO SAN RAMON NONATO','Maule','CURICÓ','Part. Subvencionado'),
('2785','C.EDUC.MONS.MANUEL LARRAIN ERRAZURIZ.','Maule','CURICÓ','Part. Subvencionado'),
('2786','INSTITUTO SAN MARTIN','Maule','CURICÓ','Part. Pagado'),
('2787','COLEGIO SANTO TOMAS DE CURICO','Maule','CURICÓ','Part. Subvencionado'),
('2789','ALIANZA FRANCESA JEAN MERMOZ','Maule','CURICÓ','Part. Pagado'),
('2790','COLEGIO VICHUQUEN','Maule','CURICÓ','Part. Pagado'),
('2793','INSTITUTO POLITECNICO BICENTENARIO JUAN TERRIER DAILLY','Maule','CURICÓ','Adm. Delegada'),
('2794','LICEO TENO','Maule','TENO','Corp. Municipal'),
('2795','ESCUELA TENO','Maule','TENO','Corp. Municipal'),
('2796','ESCUELA COMALLE','Maule','TENO','Corp. Municipal'),
('2797','ESCUELA HACIENDA TENO','Maule','TENO','Corp. Municipal'),
('2799','ESCUELA LA PURISIMA','Maule','TENO','Part. Subvencionado'),
('2800','ESCUELA MORZA','Maule','TENO','Corp. Municipal'),
('2801','ESCUELA MONTERILLA','Maule','TENO','Corp. Municipal'),
('2802','ESCUELA SUSANA MONTES VELASCO','Maule','TENO','Corp. Municipal'),
('2803','ESCUELA LAS ARBOLEDAS','Maule','TENO','Corp. Municipal'),
('2804','ESC. MANUEL RODRIGUEZ ERDOIZA','Maule','TENO','Corp. Municipal'),
('2805','ESCUELA ALBORADA VENTANA DEL BAJO','Maule','TENO','Corp. Municipal'),
('2806','ESCUELA HUEMUL','Maule','TENO','Corp. Municipal'),
('2809','ESCUELA LAS LIRAS','Maule','TENO','Corp. Municipal'),
('2814','ESCUELA SAN RAFAEL','Maule','TENO','Corp. Municipal'),
('2815','ESCUELA EL CULENAR','Maule','TENO','Corp. Municipal'),
('2816','ESCUELA PDTE CARLOS IBANEZ DEL CAMPO','Maule','TENO','Corp. Municipal'),
('2817','ESCUELA SAN CRISTOBAL','Maule','TENO','Corp. Municipal'),
('2819','ESCUELA TENIENTE CRUZ','Maule','TENO','Corp. Municipal'),
('2820','ESCUELA LOS ALISOS','Maule','TENO','Corp. Municipal'),
('2821','ESCUELA BASICA SAN SEBASTIAN','Maule','TENO','Part. Subvencionado'),
('2822','ESCUELA ARTURO ALESSANDRI PALMA','Maule','ROMERAL','Corp. Municipal'),
('2823','ESCUELA RAMON FREIRE','Maule','ROMERAL','Corp. Municipal'),
('2825','ESCUELA AMERICA LATINA','Maule','ROMERAL','Corp. Municipal'),
('2826','ESCUELA TRES ESQUINAS','Maule','ROMERAL','Corp. Municipal'),
('2827','ESCUELA GUAICO CENTRO','Maule','ROMERAL','Corp. Municipal'),
('2829','ESCUELA BASICA LUIS ESCOBAR LARA','Maule','ROMERAL','Corp. Municipal'),
('2830','ESCUELA CARLOS LAZCANO ALFONSO','Maule','ROMERAL','Corp. Municipal'),
('2831','ESCUELA GERARDO RODRIGUEZ ORTUZAR','Maule','ROMERAL','Corp. Municipal'),
('2832','ESCUELA BASICA GISLLEN E. BERNUCCI GIUSTACORI','Maule','ROMERAL','Corp. Municipal'),
('2835','LICEO POLIVALENTE DE MOLINA','Maule','MOLINA','Corp. Municipal'),
('2836','LICEO JUAN AGUSTIN MORALES GONZALEZ','Maule','MOLINA','Corp. Municipal'),
('2839','ESCUELA PRESIDENTE EDUARDO FREI MONTALVA','Maule','MOLINA','Corp. Municipal'),
('2840','ESCUELA SUPERIOR DE MOLINA','Maule','MOLINA','Corp. Municipal'),
('2842','LUIS MALDONADO BOGGIANO','Maule','MOLINA','Corp. Municipal'),
('2843','ESCUELA EL PROGRESO','Maule','MOLINA','Corp. Municipal'),
('2844','ESC.INTERN.LAS PALMAS TRES ESQUINAS','Maule','MOLINA','Corp. Municipal'),
('2845','ESCUELA SAN PEDRO DE MOLINA','Maule','MOLINA','Corp. Municipal'),
('2846','ESCUELA BUENA PAZ','Maule','MOLINA','Corp. Municipal'),
('2847','ESCUELA CASA BLANCA','Maule','MOLINA','Corp. Municipal'),
('2848','ESCUELA QUECHEREGUAS DE PICHINGAL','Maule','MOLINA','Corp. Municipal'),
('2850','ESCUELA JULIA CATAN DABIKE','Maule','MOLINA','Corp. Municipal'),
('2851','ESCUELA BUENA FE','Maule','MOLINA','Corp. Municipal'),
('2854','ESCUELA SAN JORGE DE ROMERAL','Maule','MOLINA','Corp. Municipal'),
('2856','ESCUELA EL RADAL','Maule','MOLINA','Corp. Municipal'),
('2858','ESCUELA LA PALMILLA','Maule','MOLINA','Corp. Municipal'),
('2859','ESCUELA BAJO LOS ROMEROS','Maule','MOLINA','Corp. Municipal'),
('2860','ESCUELA EL CERRILLO','Maule','MOLINA','Corp. Municipal'),
('2861','ESCUELA ALBERTO GIRARDI FONTANA','Maule','MOLINA','Corp. Municipal'),
('2862','ESCUELA PARTICULAR NTRA.SRA.DEL TRANSITO','Maule','MOLINA','Part. Subvencionado'),
('2863','COLEGIO ADVENTISTA DE MOLINA','Maule','MOLINA','Part. Subvencionado'),
('2865','ESCUELA BICENTENARIO DE EXCELENCIA AGRICOLA SUPERIOR DE MOLINA','Maule','MOLINA','Adm. Delegada'),
('2866','ESCUELA VILLA PRAT','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2867','ESC.DE EDUC.GRAL. BASICA MONSENOR ENRIQUE COR','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2868','ESCUELA SANTA ROSA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2870','ESCUELA LA ISLA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2871','ESCUELA LO VALDIVIA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2873','ESCUELA JOSE CANEPA VACCAREZZA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2874','ESCUELA EL DURAZNO','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2875','ESCUELA SANTA EMILIA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2876','ESCUELA EUGENIO TAGLE VALDES','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2877','ESCUELA LA HIGUERILLA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('2879','ESCUELA SANTA MARIA','Maule','VICHUQUEN','Corp. Municipal'),
('2882','LICEO BICENTENARIO HUALAÑE','Maule','HUALAÑÉ','Corp. Municipal'),
('2883','ESCUELA LA HUERTA DE MATAQUITO','Maule','HUALAÑÉ','Corp. Municipal'),
('2884','ESCUELA CARLOS CORREA NUNEZ','Maule','HUALAÑÉ','Corp. Municipal'),
('2885','ESCUELA ORILLA DE NAVARRO','Maule','HUALAÑÉ','Corp. Municipal'),
('2888','ESCUELA EDUARDO NUNEZ FUENZALIDA','Maule','HUALAÑÉ','Corp. Municipal'),
('2890','ESCUELA JOSE SANTOS ALIAGA ROJAS','Maule','HUALAÑÉ','Corp. Municipal'),
('2892','ESCUELA DE BARBA RUBIA','Maule','HUALAÑÉ','Corp. Municipal'),
('2893','ESCUELA CAONE','Maule','HUALAÑÉ','Corp. Municipal'),
('2894','ESCUELA AMELIA VIAL DE CONCHA','Maule','HUALAÑÉ','Corp. Municipal'),
('2895','ESCUELA PARTICULAR LOS COIPOS','Maule','HUALAÑÉ','Part. Subvencionado'),
('2896','LICEO BICENTENARIO AUGUSTO SANTELICES VALENZUELA','Maule','LICANTÉN','Corp. Municipal'),
('2901','ESCUELA LOS COPIHUES','Maule','LICANTÉN','Corp. Municipal'),
('2903','COLEGIO DR. MANUEL AVILES INOSTROZA','Maule','LICANTÉN','Corp. Municipal'),
('2907','ESCUELA PLAYA LINDA DE LIPIMAVIDA','Maule','VICHUQUEN','Corp. Municipal'),
('2908','LICEO TECNICO PROFESIONAL ALEJANDRO ROJAS SIERRA','Maule','LICANTÉN','Corp. Municipal'),
('2909','LICEO NUEVO HORIZONTE','Maule','VICHUQUEN','Corp. Municipal'),
('2910','LICEO BICENTENARIO DE EXCELENCIA ENTRE AGUAS DE LLICO','Maule','VICHUQUEN','Corp. Municipal'),
('2911','ESCUELA LAGO VICHUQUEN','Maule','VICHUQUEN','Corp. Municipal'),
('2914','ESCUELA EMA CORNEJO DE CARDOEN','Maule','VICHUQUEN','Corp. Municipal'),
('2917','ESCUELA RAUCO','Maule','RAUCO','Corp. Municipal'),
('2918','ESCUELA LOS ALMENDROS','Maule','RAUCO','Corp. Municipal'),
('2920','ESCUELA LUIS LEYTON RUBIO','Maule','RAUCO','Corp. Municipal'),
('2921','ESCUELA LA ALBORADA','Maule','RAUCO','Corp. Municipal'),
('2927','ESCUELA EL PLUMERO','Maule','RAUCO','Corp. Municipal'),
('2928','ESCUELA EL PARRON','Maule','RAUCO','Corp. Municipal'),
('2930','LICEO DE CULTURA Y DIFUSION ARTISTICA','Maule','TALCA','Corp. Municipal'),
('2931','ESCUELA INÉS SYLVESTER DE ARTOZÓN','Maule','TALCA','Corp. Municipal'),
('2932','ESCUELA ESPECIAL ESPANA','Maule','TALCA','Corp. Municipal'),
('2933','ESCUELA CENTRO DE CAPACITACION LABORAL','Maule','TALCA','Corp. Municipal'),
('2934','LICEO TECNICO AMELIA COURBIS','Maule','TALCA','Corp. Municipal'),
('2935','LICEO MARTA DONOSO ESPEJO','Maule','TALCA','Corp. Municipal'),
('2937','LICEO INDUSTRIAL SUPERIOR','Maule','TALCA','Corp. Municipal'),
('2938','INST.SUP.DE COMERCIO ENRIQUE MALDONADO S','Maule','TALCA','Corp. Municipal'),
('2939','LICEO BICENTENARIO DIEGO PORTALES','Maule','TALCA','Corp. Municipal'),
('2940','LICEO CARLOS CONDELL','Maule','TALCA','Corp. Municipal'),
('2941','ESCUELA HERMANO GUIDO GOOSSENS','Maule','TALCA','Corp. Municipal'),
('2942','ESCUELA JUAN LUIS SANFUENTES','Maule','TALCA','Corp. Municipal'),
('2943','LICEO HECTOR PEREZ BIOTT','Maule','TALCA','Corp. Municipal'),
('2944','ESCUELA JOSE M. BALMACEDA Y FERNANDEZ','Maule','TALCA','Corp. Municipal'),
('2945','ESCUELA PROSPERIDAD','Maule','TALCA','Corp. Municipal'),
('2946','ESCUELA CARLOS SPANO','Maule','TALCA','Corp. Municipal'),
('2947','ESCUELA LAS ARAUCARIAS','Maule','TALCA','Corp. Municipal'),
('2948','ESCUELA CARLOS SALINAS LAGOS','Maule','TALCA','Corp. Municipal'),
('2949','ESCUELA BASICA','Maule','TALCA','Corp. Municipal'),
('2950','ESCUELA EL EDEN','Maule','TALCA','Corp. Municipal'),
('2951','ESCUELA LA FLORIDA','Maule','TALCA','Corp. Municipal'),
('2952','ESCUELA VILLA LA PAZ','Maule','TALCA','Corp. Municipal'),
('2955','ESCUELA FELIPE CUBILLOS BRILLA EL SOL','Maule','TALCA','Corp. Municipal'),
('2956','ESCUELA AURORA DE CHILE','Maule','TALCA','Corp. Municipal'),
('2957','ESCUELA UNO SAN AGUSTIN','Maule','TALCA','Corp. Municipal'),
('2958','ESCUELA JOSE ABELARDO NUNEZ','Maule','TALCA','Corp. Municipal'),
('2959','LORENZO VAROLI GHERARDI','Maule','TALCA','Corp. Municipal'),
('2961','LICEO TECNICO PROFESIONAL AULAS DE ESPERANZA DE TALCA','Maule','TALCA','Corp. Municipal'),
('2964','ESCUELA LAS AMERICAS','Maule','TALCA','Corp. Municipal'),
('2965','ESCUELA COOPERATIVA LIRCAY MANUEL YAÑEZ OLAVE','Maule','TALCA','Corp. Municipal'),
('2966','ESCUELA COSTANERA','Maule','TALCA','Corp. Municipal'),
('2968','ESCUELA ANTUPEHUEN','Maule','TALCA','Corp. Municipal'),
('2972','ESCUELA ESPERANZA','Maule','TALCA','Corp. Municipal'),
('2973','LICEO ABATE MOLINA','Maule','TALCA','Corp. Municipal'),
('2974','LICEO IGNACIO CARRERA PINTO','Maule','TALCA','Corp. Municipal'),
('2975','ESCUELA HUILQUILEMU','Maule','TALCA','Corp. Municipal'),
('2977','ESCUELA VINA PURISIMA','Maule','TALCA','Corp. Municipal'),
('2978','ESCUELA SAN MIGUEL','Maule','TALCA','Corp. Municipal'),
('2979','LICEO TECNICO-PROFESIONAL EL SAUCE','Maule','TALCA','Corp. Municipal'),
('2980','ESCUELA SANTA MARTA','Maule','TALCA','Corp. Municipal'),
('2981','ESCUELA PANGUILEMO','Maule','TALCA','Corp. Municipal'),
('2983','ESCUELA BASICA PUERTAS NEGRAS','Maule','TALCA','Corp. Municipal'),
('2986','ESCUELA EL ORIENTE','Maule','TALCA','Corp. Municipal'),
('2989','ESCUELA CENTINELA','Maule','TALCA','Corp. Municipal'),
('2990','ESCUELA PARTICULAR AMOR DE DIOS','Maule','TALCA','Part. Subvencionado'),
('2991','COLEGIO MONSENOR MANUEL LARRAIN','Maule','TALCA','Part. Subvencionado'),
('2992','COLEGIO INTEGRADO SAN PIO X SECTOR PTE.','Maule','TALCA','Part. Subvencionado'),
('2993','COLEGIO MARIA RAQUEL','Maule','TALCA','Part. Subvencionado'),
('2994','ESCUELA ESPECIAL EVANGEL.PRESBITERIANA','Maule','TALCA','Part. Subvencionado'),
('2995','INSTITUTO ANDRES BELLO','Maule','TALCA','Part. Subvencionado'),
('2997','COLEGIO DARIO SALAS','Maule','TALCA','Part. Subvencionado'),
('2999','COLEGIO CAMILO HENRIQUEZ','Maule','TALCA','Part. Subvencionado'),
('3003','COLEGIO PIAGET','Maule','TALCA','Part. Subvencionado'),
('3005','LICEO SANTA TERESITA','Maule','TALCA','Part. Subvencionado'),
('3006','CENTRO EDUCATIVO SALESIANOS TALCA','Maule','TALCA','Part. Subvencionado'),
('3008','COLEGIO ARTISTICO DEL MAULE','Maule','TALCA','Part. Subvencionado'),
('3010','COLEGIO SAN FRANCISCO DE ASIS','Maule','TALCA','Part. Subvencionado'),
('3012','COLEGIO DE LA SALLE','Maule','TALCA','Part. Pagado'),
('3013','COLEGIO JUAN IGNACIO MOLINA','Maule','TALCA','Part. Subvencionado'),
('3014','COLEGIO INGLES','Maule','TALCA','Part. Pagado'),
('3015','COLEGIO PARTICULAR MONTESSORI','Maule','TALCA','Part. Pagado'),
('3016','LICEO DE PELARCO','Maule','PELARCO','Corp. Municipal'),
('3017','ESCUELA SAN RAFAEL','Maule','SAN RAFAEL','Corp. Municipal'),
('3019','ESCUELA HERNAN CIUDAD INOSTROZA','Maule','PELARCO','Corp. Municipal'),
('3020','ESCUELA ALTO PANGUE','Maule','SAN RAFAEL','Corp. Municipal'),
('3022','ESCUELA PABLO CORREA MONTT','Maule','PELARCO','Corp. Municipal'),
('3023','ESCUELA FLAVIO PAVEZ GONZALEZ','Maule','PELARCO','Corp. Municipal'),
('3024','ESCUELA DANTE RONCAGLIOLO BAVESTRELLO','Maule','SAN RAFAEL','Corp. Municipal'),
('3025','ESCUELA PANGUE ARRIBA','Maule','SAN RAFAEL','Corp. Municipal'),
('3026','ESCUELA PANGUE ABAJO','Maule','SAN RAFAEL','Corp. Municipal'),
('3028','ESCUELA EL MILAGRO','Maule','SAN RAFAEL','Corp. Municipal'),
('3029','ESCUELA WILIBALDO NUNEZ','Maule','PELARCO','Corp. Municipal'),
('3030','ESCUELA LIHUENO','Maule','PELARCO','Corp. Municipal'),
('3032','ESCUELA PARTICULAR SAN SEBASTIAN','Maule','PELARCO','Part. Subvencionado'),
('3033','LICEO BICENTENARIO AGROINDUSTRIAL RIO CLARO','Maule','RÍO CLARO','Corp. Municipal'),
('3034','ESCUELA BASICA JUAN LUIS SANFUENTES ANDONAEGUI','Maule','RÍO CLARO','Corp. Municipal'),
('3036','ESCUELA EL BOLSICO','Maule','RÍO CLARO','Corp. Municipal'),
('3037','ESCUELA PORVENIR','Maule','RÍO CLARO','Corp. Municipal'),
('3038','ESCUELA LA CHISPA','Maule','RÍO CLARO','Corp. Municipal'),
('3039','ESCUELA ODESSA','Maule','RÍO CLARO','Corp. Municipal'),
('3042','ESCUELA EL GUINDO','Maule','RÍO CLARO','Corp. Municipal'),
('3045','ESCUELA SANTA HERMINIA','Maule','RÍO CLARO','Corp. Municipal'),
('3047','ESCUELA CASAS VIEJAS','Maule','RÍO CLARO','Corp. Municipal'),
('3048','ESCUELA PASO ANCHO','Maule','RÍO CLARO','Corp. Municipal'),
('3051','ESCUELA MAITENES','Maule','RÍO CLARO','Corp. Municipal'),
('3055','LICEO SAN CLEMENTE ENTRE RIOS','Maule','SAN CLEMENTE','Corp. Municipal'),
('3056','ESCUELA SAN CLEMENTE','Maule','SAN CLEMENTE','Corp. Municipal'),
('3057','ESCUELA ARTURO PRAT CHACON','Maule','SAN CLEMENTE','Corp. Municipal'),
('3058','ESCUELA AURORA','Maule','SAN CLEMENTE','Corp. Municipal'),
('3059','COLEGIO DEIDAMIA PAREDES BELLO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3060','ESCUELA RAMADILLAS','Maule','SAN CLEMENTE','Corp. Municipal'),
('3061','ESCUELA PUNTA DE DIAMANTE','Maule','SAN CLEMENTE','Corp. Municipal'),
('3062','ESCUELA PEUMO NEGRO','Maule','SAN CLEMENTE','Corp. Municipal'),
('3063','ESCUELA CORRALONES','Maule','SAN CLEMENTE','Corp. Municipal'),
('3065','ESCUELA ENRIQUE CORREA GUZMAN','Maule','SAN CLEMENTE','Corp. Municipal')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
