-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 3 de 31 | filas 801-1200
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('1157','ESCUELA BASICA LOS ALAMOS EL SOBRANTE','Valparaíso','PETORCA','Corp. Municipal'),
('1158','ESCUELA BASICA BENANCIO PEREZ','Valparaíso','PETORCA','Corp. Municipal'),
('1160','ESCUELA HOGAR FRONTERIZA DE CHALACO','Valparaíso','PETORCA','Corp. Municipal'),
('1161','ESCUELA BASICA PEDEGUA','Valparaíso','PETORCA','Corp. Municipal'),
('1162','ESCUELA PARTICULAR JUAN PABLO II','Valparaíso','PETORCA','Part. Subvencionado'),
('1164','COL. CATOLICO PDTE.MANUEL MONTT','Valparaíso','PETORCA','Part. Subvencionado'),
('1166','COLEGIO SAGRADO CORAZON','Valparaíso','PETORCA','Part. Subvencionado'),
('1167','LICEO Y ESCUELA MUNICIPAL','Valparaíso','CABILDO','Corp. Municipal'),
('1168','ESCUELA HANS WENKE MENGERS','Valparaíso','CABILDO','Corp. Municipal'),
('1170','ESCUELA BASICA VALLE DE ARTIFICIO','Valparaíso','CABILDO','Corp. Municipal'),
('1171','ESCUELA BASICA LA FRONTERA DE ALICAHUE','Valparaíso','CABILDO','Corp. Municipal'),
('1173','ESCUELA ESTER SILVA SOMARRIVA BARTOLILLO','Valparaíso','CABILDO','Corp. Municipal'),
('1174','ESCUELA BASICA SAN LORENZO','Valparaíso','CABILDO','Corp. Municipal'),
('1176','ESCUELA PABLO NERUDA','Valparaíso','CABILDO','Corp. Municipal'),
('1178','ESCUELA BASICA LA VINA','Valparaíso','CABILDO','Corp. Municipal'),
('1180','ESCUELA BASICA G-45','Valparaíso','CABILDO','Corp. Municipal'),
('1181','ESCUELA BASICA LOS ANGELES','Valparaíso','CABILDO','Corp. Municipal'),
('1182','ESCUELA BASICA G-47','Valparaíso','CABILDO','Corp. Municipal'),
('1183','LICEO BICENTENARIO DE ZAPALLAR','Valparaíso','ZAPALLAR','Corp. Municipal'),
('1184','COLEGIO TECNICO PROFESIONAL MERCEDES MATURANA GALLARDO','Valparaíso','ZAPALLAR','Corp. Municipal'),
('1185','ESCUELA BALNEARIO CACHAGUA','Valparaíso','ZAPALLAR','Corp. Municipal'),
('1189','ESCUELA BASICA AURELIO DURAN ALMENDRO','Valparaíso','ZAPALLAR','Corp. Municipal'),
('1190','COLEGIO PARROQUIAL FRANCISCO DIDIER','Valparaíso','ZAPALLAR','Part. Subvencionado'),
('1191','ESCUELA PAPUDO','Valparaíso','PAPUDO','Corp. Municipal'),
('1192','ESCUELA RURAL PULLALLY','Valparaíso','PAPUDO','Corp. Municipal'),
('1194','LICEO MAXIMILIANO SALAS MARCHAN','Valparaíso','LOS ANDES','Corp. Municipal'),
('1195','LICEO COMERCIAL DE LOS ANDES','Valparaíso','LOS ANDES','Adm. Delegada'),
('1196','LICEO BICENTENARIO TÉCNICO AMANCAY','Valparaíso','LOS ANDES','Corp. Municipal'),
('1197','ESCUELA ESPANA','Valparaíso','LOS ANDES','Corp. Municipal'),
('1198','LICEO REPUBLICA ARGENTINA','Valparaíso','LOS ANDES','Corp. Municipal'),
('1199','LICEO POLITECNICO AMERICA','Valparaíso','LOS ANDES','Corp. Municipal'),
('1200','ESCUELA JOHN KENNEDY','Valparaíso','LOS ANDES','Corp. Municipal'),
('1201','ESCUELA ESPECIAL VALLE ANDINO','Valparaíso','LOS ANDES','Corp. Municipal'),
('1202','ESCUELA FERROVIARIA','Valparaíso','LOS ANDES','Corp. Municipal'),
('1203','ESCUELA GABRIELA MISTRAL','Valparaíso','LOS ANDES','Corp. Municipal'),
('1204','ESCUELA BASICA GRAL.JOSE MIGUEL CARRERA','Valparaíso','LOS ANDES','Corp. Municipal'),
('1206','C.E.I.A DR. OSVALDO ROJAS GONZALEZ','Valparaíso','LOS ANDES','Corp. Municipal'),
('1208','ESCUELA BASICA RIO BLANCO','Valparaíso','LOS ANDES','Corp. Municipal'),
('1210','ESCUELA EL SAUCE','Valparaíso','LOS ANDES','Corp. Municipal'),
('1211','ESCUELA IGNACIO CARRERA PINTO','Valparaíso','LOS ANDES','Corp. Municipal'),
('1212','ESCUELA JUAN GOMEZ MILLAS','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1213','LICEO PARTICULAR MIXTO LOS ANDES','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1214','COLEGIO MARIA AUXILIADORA','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1215','ESCUELA PARTICULAR SAN JOSE','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1216','ESCUELA PARTICULAR HUMBERTO CASARINO','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1217','LICEO SANTA CLARA','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1218','ESCUELA PARTICULAR JEAN PIAGET','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1220','ESCUELA PARTICULAR N°27 EDÉN DEL NIÑO','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1221','COLEGIO ALCAZAR','Valparaíso','LOS ANDES','Part. Subvencionado'),
('1225','INSTITUTO CHACABUCO','Valparaíso','LOS ANDES','Part. Pagado'),
('1226','COLEGIO MARIA MONTESSORI','Valparaíso','LOS ANDES','Part. Pagado'),
('1229','COLEGIO PARTICULAR BREGA COLLEGE','Valparaíso','LOS ANDES','Part. Pagado'),
('1233','ESCUELA PABLO NERUDA','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1234','ESC. BASICA SILVIO ZENTENO VERGARA','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1235','ESCUELA LO CALVO','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1237','ESCUELA BÁSICA PADRE HUMBERTO MUÑOZ R.','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1238','ESCUELA INCLUSIVA SAN LORENZO','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1239','ESCUELA HERMANO FERNANDO DE LA FUENTE','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1240','ESCUELA RIO COLORADO','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1243','ESCUELA EL COBRE','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1244','ESCUELA SAN FRANCISCO','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1245','ESCUELA EL CORAZON','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1246','ESCUELA BÁSICA LIBERTAD','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('1247','ESCUELA BASICA MARIA ISABEL DE BROWN','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1248','ESCUELA BASICA LA PAMPILLA','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1249','ESCUELA BASICA PEDRO AGUIRRE CERDA','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1250','ESCUELA VICTOR KOERNER','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1251','ESCUELA BASICA CRISTO REDENTOR','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1252','ESCUELA BASICA VALLE ALEGRE','Valparaíso','CALLE LARGA','Corp. Municipal'),
('1255','INSTITUTO AGRICOLA PASCUAL BABURIZZA','Valparaíso','CALLE LARGA','Part. Subvencionado'),
('1256','COLEGIO PARTICULAR SAN JOSE','Valparaíso','CALLE LARGA','Part. Subvencionado'),
('1257','CENTRO DE FORMACIÓN ACADÉMICA PERFECTO DE LA FUENTE DEL VILLAR','Valparaíso','RINCONADA','Corp. Municipal'),
('1258','ESCUELA BASICA EMIGDIO GALDAMES ROBLES','Valparaíso','RINCONADA','Corp. Municipal'),
('1259','ESCUELA BASICA MANUEL LEON SALINAS','Valparaíso','RINCONADA','Corp. Municipal'),
('1260','LICEO PARROQUIAL TERESITA DE LOS ANDES','Valparaíso','RINCONADA','Part. Subvencionado'),
('1261','LICEO DOCTOR ROBERTO HUMERES O.','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1262','LICEO BICENTENARIO GUILLERMO RICHARDS CUEVAS','Valparaíso','SAN FELIPE','Adm. Delegada'),
('1263','LICEO BICENTENARIO CORINA URBINA VILLANUEVA','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1264','LICEO SAN FELIPE','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1265','ESCUELA BASICA BERNARDO O HIGGINS R.','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1266','ESCUELA MANUEL RODRIGUEZ ERDOIZA','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1268','ESCUELA BASICA JOSE DE SAN MARTIN','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1269','ESCUELA JOHN F KENNEDY','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1271','ESCUELA JOSÉ ANTONIO MANSO DE VELASCO','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1273','ESCUELA SAN RAFAEL','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1274','ESCUELA ALMENDRAL','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1275','ESCUELA BUEN PASTOR','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1276','ESCUELA ESPECIAL SAGRADO CORAZON','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1279','ESCUELA CARMELA CARVAJAL DE PRAT','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1280','ESCUELA 21 DE MAYO','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1281','ESCUELA REPUBLICA ARGENTINA','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1282','ESCUELA BUCALEMITO','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1283','ESCUELA HERIBERTO BERMUDEZ CRUZ','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1285','ESCUELA MATEO COKLJAT K','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1286','ESCUELA BASICA CAROLINA OCAMPO GARCIA','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1287','ESCUELA JOSE BERNARDO SUAREZ','Valparaíso','SAN FELIPE','Corp. Municipal'),
('1288','INSTITUTO ABDON CIFUENTES','Valparaíso','SAN FELIPE','Part. Pagado'),
('1289','COLEGIO ASSUNTA PALLOTA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('1290','COLEGIO SANTA JUANA DE ARCO','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('1291','COLEGIO JOSE AGUSTIN GOMEZ','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('1292','COLEGIO ALONSO DE ERCILLA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('1294','COLEGIO PARTICULAR PUMANQUE','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('1300','ESCUELA AGRICOLA DE SAN FELIPE','Valparaíso','SAN FELIPE','Adm. Delegada'),
('1301','LICEO MANUEL MARIN','Valparaíso','PUTAENDO','Corp. Municipal'),
('1302','LICEO RINCONADA DE SILVA','Valparaíso','PUTAENDO','Corp. Municipal'),
('1304','ESCUELA PASO HISTORICO EL TARTARO','Valparaíso','PUTAENDO','Corp. Municipal'),
('1305','ESCUELA RENACER','Valparaíso','PUTAENDO','Corp. Municipal'),
('1307','ESCUELA SAN ALBERTO','Valparaíso','PUTAENDO','Corp. Municipal'),
('1308','ESCUELA ALEJANDRINA CARVAJAL ASPEE','Valparaíso','PUTAENDO','Corp. Municipal'),
('1309','ESCUELA EDUARDO BECERRA BASCUNAN','Valparaíso','PUTAENDO','Corp. Municipal'),
('1310','ESCUELA MARIA LEIVA DE IBANEZ','Valparaíso','PUTAENDO','Corp. Municipal'),
('1311','ESCUELA EL AVE MARIA','Valparaíso','CALERA','Part. Subvencionado'),
('1312','ESC. BAS. GASTON ORMAZABAL CABRERA','Valparaíso','PUTAENDO','Corp. Municipal'),
('1313','ESCUELA CATAN DABIKE','Valparaíso','PUTAENDO','Corp. Municipal'),
('1316','COLEGIO MARIE POUSSEPIN','Valparaíso','PUTAENDO','Part. Subvencionado'),
('1318','LICEO DARIO SALAS','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1319','ESCUELA ESPECIAL MARÍA REBECA ESPÍNOLA ESPINOSA DE SANTA MARÍA','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1321','ESCUELA GUILLERMO BANADOS HONORATO','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1322','ESCUELA LA HIGUERA','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1323','ESCUELA SANTA FILOMENA','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1325','ESCUELA BASICA AURORA VELASCO PEREZ','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1326','ESCUELA JULIO TEJEDOR ZUNIGA','Valparaíso','SANTA MARÍA','Corp. Municipal'),
('1327','COLEGIO BICENTENARIO SANTA MARÍA DE ACONCAGUA','Valparaíso','SANTA MARÍA','Part. Subvencionado'),
('1328','ESCUELA INDEPENDENCIA','Valparaíso','PANQUEHUE','Corp. Municipal'),
('1329','ESCUELA EMA LOBOS REYES','Valparaíso','PANQUEHUE','Corp. Municipal'),
('1331','ESCUELA BASICA FRAY CAMILO HENRIQUEZ','Valparaíso','PANQUEHUE','Corp. Municipal'),
('1332','ESCUELA BASICA VINA ERRAZURIZ','Valparaíso','PANQUEHUE','Corp. Municipal'),
('1333','ESCUELA JORGE BARROS BEAUCHEF','Valparaíso','PANQUEHUE','Corp. Municipal'),
('1335','LICEO BICENTENARIO LICEO POLITECNICO LLAY LLAY','Valparaíso','LLAILLAY','Corp. Municipal'),
('1336','ESCUELA AGUSTIN EDWARDS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1337','ESCUELA HEROES DE IQUIQUE','Valparaíso','LLAILLAY','Corp. Municipal'),
('1338','ESCUELA NACIONES UNIDAS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1339','ESCUELA ELISA LATTAPIAT VARGAS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1340','ESCUELA HERMINIA ORTEGA DE CROXATO','Valparaíso','LLAILLAY','Corp. Municipal'),
('1341','ESCUELA BASICA EL PORVENIR','Valparaíso','LLAILLAY','Corp. Municipal'),
('1342','ESCUELA LAS PALMAS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1343','ESCUELA LAS PENAS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1345','ESCUELA LAS VEGAS','Valparaíso','LLAILLAY','Corp. Municipal'),
('1346','ESCUELA JORGE PRIETO LETELIER','Valparaíso','LLAILLAY','Corp. Municipal'),
('1347','LICEO MENESIANO SAGRADO CORAZON','Valparaíso','LLAILLAY','Part. Subvencionado'),
('1349','COLEGIO SALVADOR GONZALEZ','Valparaíso','LLAILLAY','Part. Subvencionado'),
('1350','ESC.PARTICULAR MARIA LETELIER DE PRIETO','Valparaíso','LLAILLAY','Part. Subvencionado'),
('1352','ESCUELA MARIA TERESA DEL CANTO','Valparaíso','CATEMU','Corp. Municipal'),
('1353','ESCUELA SAN JOSE DE CATEMU','Valparaíso','CATEMU','Corp. Municipal'),
('1354','LICEO BICENTENARIO POLIVALENTE FERNANDO SILVA CASTELLÓN','Valparaíso','CATEMU','Corp. Municipal'),
('1355','ESCUELA EL COBRE','Valparaíso','CATEMU','Corp. Municipal'),
('1356','ESC REBECA JOHNSON GARCIA-HUIDOBRO','Valparaíso','CATEMU','Corp. Municipal'),
('1358','ESCUELA BASICA EL NILHUE','Valparaíso','CATEMU','Corp. Municipal'),
('1359','ESCUELA BASICA LOS CERRILLOS','Valparaíso','CATEMU','Corp. Municipal'),
('1360','ESCUELA BASICA SANTA MARGARITA','Valparaíso','CATEMU','Corp. Municipal'),
('1361','COLEGIO PARTICULAR CALIFORNIA','Valparaíso','CATEMU','Part. Subvencionado'),
('1362','ESCUELA AGRICOLA SALESIANA F. HUIDOBRO','Valparaíso','CATEMU','Part. Subvencionado'),
('1363','LICEO SANTIAGO ESCUTI ORREGO','Valparaíso','QUILLOTA','Corp. Municipal'),
('1364','COLEGIO VALLE DE QUILLOTA','Valparaíso','QUILLOTA','Corp. Municipal'),
('1366','LICEO COMERCIAL DE QUILLOTA','Valparaíso','QUILLOTA','Corp. Municipal'),
('1367','COLEGIO ROBERTO MATTA','Valparaíso','QUILLOTA','Corp. Municipal'),
('1368','COLEGIO CANADÁ','Valparaíso','QUILLOTA','Corp. Municipal'),
('1369','ESCUELA SUPERIOR Nº 1','Valparaíso','QUILLOTA','Corp. Municipal'),
('1370','COLEGIO REPÚBLICA DE MÉXICO','Valparaíso','QUILLOTA','Corp. Municipal'),
('1371','COLEGIO BICENTENARIO ARAUCO','Valparaíso','QUILLOTA','Corp. Municipal'),
('1374','ESCUELA ESPECIAL LOS PALTOS','Valparaíso','QUILLOTA','Corp. Municipal'),
('1377','ESCUELA NUESTRO MUNDO','Valparaíso','QUILLOTA','Corp. Municipal'),
('1378','ESCUELA BASICA ABEL GUERRERO AGUIRRE','Valparaíso','QUILLOTA','Corp. Municipal'),
('1384','COLEGIO CUMBRES DE BOCO','Valparaíso','QUILLOTA','Corp. Municipal'),
('1385','ESCUELA BASICA LA PALMA','Valparaíso','QUILLOTA','Corp. Municipal'),
('1389','ESCUELA CRISTINA DURAN','Valparaíso','QUILLOTA','Corp. Municipal'),
('1390','ESCUELA BASICA LAS PATAGUAS','Valparaíso','QUILLOTA','Corp. Municipal'),
('1392','COLEGIO FRANCISCO DE MIRANDA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1393','COLEGIO NIÑO JESUS DE PRAGA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1394','ESCUELA PART. SAGRADOS CORAZONES','Valparaíso','CALERA','Part. Subvencionado'),
('1395','COLEGIO SAN PEDRO NOLASCO DE QUILLOTA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1397','ESCUELA PARTICULAR INDUSTRIAL E. BERTELSEN TEMPLE','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1400','CTRO. DE ESTUDIOS PARA JOVENES Y ADULTOS EDUCACION PARA TODOS','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1402','CENTRO EDUCACIONAL ARCO IRIS BAJO EL SOL','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1403','COL.NTRA.SEÑORA DEL HUERTO','Valparaíso','QUILLOTA','Part. Pagado'),
('1404','INSTITUTO RAFAEL ARIZTIA','Valparaíso','QUILLOTA','Part. Pagado'),
('1405','COLEGIO INGLES DE QUILLOTA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('1412','COLEGIO ROBERT AND ROSE','Valparaíso','QUILLOTA','Part. Pagado'),
('1414','COLEGIO LEONARDO DA VINCI','Valparaíso','LA CRUZ','Corp. Municipal'),
('1416','COLEGIO MARIA ALONSO CHACON','Valparaíso','LA CRUZ','Corp. Municipal'),
('1417','COLEGIO BOLONIA','Valparaíso','LA CRUZ','Corp. Municipal'),
('1418','ESCUELA BASICA','Valparaíso','LA CRUZ','Corp. Municipal'),
('1419','COLEGIO DOMINGO SANTA CRUZ WILSON','Valparaíso','LA CRUZ','Corp. Municipal'),
('1421','LICEO SAN ISIDRO','Valparaíso','LA CRUZ','Part. Subvencionado'),
('1422','LICEO PEDRO DE VALDIVIA','Valparaíso','CALERA','Corp. Municipal'),
('1423','ESCUELA BASICA JOSEFINA HUICI','Valparaíso','CALERA','Corp. Municipal'),
('1424','COLEGIO MUNICIPAL IRMA SAPIAIN SAPIAIN','Valparaíso','CALERA','Corp. Municipal'),
('1425','LICEO BICENTENARIO COMPLEJO EDUCACIONAL LAS ACACIAS DE ARTIFICIO','Valparaíso','CALERA','Corp. Municipal'),
('1427','ESCUELA BASICA PALESTINA','Valparaíso','CALERA','Corp. Municipal'),
('1428','ESCUELA ESPECIAL JESUS DE NAZARETH','Valparaíso','CALERA','Corp. Municipal'),
('1430','ESCUELA BASICA GABRIELA MISTRAL','Valparaíso','CALERA','Corp. Municipal'),
('1431','ESCUELA BASICA SANTA ROSA DEL HUERTO','Valparaíso','CALERA','Corp. Municipal'),
('1433','ESCUELA BASICA EL LIBERTADOR','Valparaíso','CALERA','Corp. Municipal'),
('1435','ESCUELA BASICA VILLA LA FLORIDA','Valparaíso','CALERA','Corp. Municipal'),
('1436','LICEO PARTICULAR SAN JOSE','Valparaíso','CALERA','Part. Subvencionado'),
('1437','COLEGIO TERESA BROWN DE ARIZTIA','Valparaíso','CALERA','Part. Subvencionado'),
('1438','COLEGIO SAULO DE TARSO','Valparaíso','CALERA','Part. Subvencionado'),
('1440','COLEGIO LUCERO','Valparaíso','CALERA','Part. Pagado'),
('1441','BARRIO ESTADIO MUNICIPAL','Valparaíso','CALERA','Part. Pagado'),
('1442','COLEGIO JOHN CRANE','Valparaíso','CALERA','Part. Subvencionado'),
('1443','LICEO INDUSTRIAL A-16 OSCAR CORONA BARAHO','Valparaíso','CALERA','Adm. Delegada'),
('1444','LICEO MUNICIPAL JUAN RUSQUE PORTAL','Valparaíso','NOGALES','Corp. Municipal'),
('1445','COLEGIO EL MELÓN','Valparaíso','NOGALES','Corp. Municipal'),
('1447','ESCUELA BASICA ULDA ARACENA GONZALEZ','Valparaíso','NOGALES','Corp. Municipal'),
('1448','ESCUELA BASICA LA PENA','Valparaíso','NOGALES','Corp. Municipal'),
('1449','COLEGIO CARMELITA FELIPE CORTÉS','Valparaíso','NOGALES','Part. Subvencionado'),
('1450','COLEGIO SANTA ISABEL','Valparaíso','NOGALES','Part. Subvencionado'),
('1453','LICEO MUNICIPAL LUIS LABORDA','Valparaíso','HIJUELAS','Corp. Municipal'),
('1454','ESCUELA ADRIANA RIQUELME NUNEZ','Valparaíso','HIJUELAS','Corp. Municipal'),
('1455','ESCUELA MONICA HURTADO EDWARDS','Valparaíso','HIJUELAS','Corp. Municipal'),
('1456','ESCUELA ANA JESUS IBACACHE','Valparaíso','HIJUELAS','Corp. Municipal'),
('1457','ESCUELA BASICA BENJAMIN MATTE LARRAIN','Valparaíso','HIJUELAS','Corp. Municipal'),
('1458','ESCUELA BASICA LA SOMBRA','Valparaíso','HIJUELAS','Corp. Municipal'),
('1459','ESCUELA BASICA RABUCO','Valparaíso','HIJUELAS','Corp. Municipal'),
('1460','ESCUELA BASICA CALIXTO OVALLE URZUA','Valparaíso','HIJUELAS','Corp. Municipal'),
('1461','ESCUELA MONTE CARMELO','Valparaíso','CALERA','Corp. Municipal'),
('1462','ESCUELA BASICA LOS TILOS DE HUALCAPO','Valparaíso','HIJUELAS','Corp. Municipal'),
('1464','LICEO DE LIMACHE','Valparaíso','LIMACHE','Corp. Municipal'),
('1465','ESCUELA COEDUC TTE HERNAN MERINO CORREA','Valparaíso','LIMACHE','Corp. Municipal'),
('1466','ESCUELA SUPERIOR MIXTA Nº88','Valparaíso','LIMACHE','Corp. Municipal'),
('1467','LICEO BICENTENARIO COLEGIO PASIÓN DE JESÚS DE LIMACHE','Valparaíso','LIMACHE','Corp. Municipal'),
('1468','COLEGIO BRASILIA','Valparaíso','LIMACHE','Corp. Municipal'),
('1469','LICEO HÉROES DE CHILE','Valparaíso','LIMACHE','Corp. Municipal'),
('1471','ESCUELA LIMACHITO','Valparaíso','LIMACHE','Corp. Municipal'),
('1472','ESCUELA BASICA LOS MAITENES','Valparaíso','LIMACHE','Corp. Municipal'),
('1473','ESCUELA TABOLANGO','Valparaíso','LIMACHE','Corp. Municipal'),
('1474','ESCUELA BASICA PUENTE COLMO','Valparaíso','CONCÓN','Servicio Local'),
('1475','ESC. BASICA TRANQUE LLIU LLIU','Valparaíso','LIMACHE','Corp. Municipal'),
('1478','COLEGIO DE LA SANTA CRUZ','Valparaíso','LIMACHE','Part. Subvencionado'),
('1482','COLEGIO LIMACHE COLLEGE','Valparaíso','LIMACHE','Part. Subvencionado'),
('1483','ESCUELA PARTICULAR MICAELA DESMAISSIERES','Valparaíso','LIMACHE','Part. Subvencionado'),
('1484','ESCUELA PARTICULAR INST. SANTA MARIA','Valparaíso','LIMACHE','Part. Subvencionado'),
('1488','ESCUELA MONTEVIDEO','Valparaíso','OLMUÉ','Corp. Municipal'),
('1489','LICEO DE OLMUE','Valparaíso','OLMUÉ','Corp. Municipal'),
('1490','ESCUELA BÁSICA QUEBRADA DE ALVARADO','Valparaíso','OLMUÉ','Corp. Municipal'),
('1491','ESCUELA BASICA LO NARVAEZ','Valparaíso','OLMUÉ','Corp. Municipal'),
('1493','ESCUELA LA DORMIDA','Valparaíso','OLMUÉ','Corp. Municipal'),
('1495','ESCUELA LA RAMAYANA','Valparaíso','OLMUÉ','Corp. Municipal'),
('1496','ESCUELA LAS PALMAS DEL NIÑO DIOS','Valparaíso','OLMUÉ','Corp. Municipal'),
('1498','ESCUELA LAS BELLOTAS DE LA VEGA','Valparaíso','OLMUÉ','Corp. Municipal'),
('1500','COLEGIO PART. IGNACIO CARRERA PINTO','Valparaíso','OLMUÉ','Part. Subvencionado'),
('1502','INST.SUP.COMERCIO FCO.ARAYA BENNET','Valparaíso','VALPARAÍSO','Servicio Local'),
('1503','ESCUELA INDUSTRIAL SUPERIOR DE VALPARAISO','Valparaíso','VALPARAÍSO','Adm. Delegada'),
('1504','LICEO TÉCNICO DE VALPARAÍSO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1506','CENTRO EDUCATIVO FLORIDA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1507','CENTRO EDUCATIVO HORIZONTE','Valparaíso','VALPARAÍSO','Servicio Local'),
('1508','CENTRO EDUCATIVO GRAN BRETAÑA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1509','CENTRO EDUCATIVO LUZ DE ESPERANZA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1510','ESCUELA ESPECIAL DE LENGUAJE LIBERTADOR DE LA PATRIA BERNARDO O`HIGGINS','Valparaíso','VALPARAÍSO','Servicio Local'),
('1511','CENTRO EDUCATIVO REINO DE SUECIA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1514','ESCUELA HERNAN OLGUIN','Valparaíso','VALPARAÍSO','Servicio Local'),
('1515','LICEO EDUARDO DE LA BARRA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1516','LICEO TECNOLÓGICO ALFREDO NAZAR FERES','Valparaíso','VALPARAÍSO','Servicio Local'),
('1517','LICEO MATILDE BRANDAU DE ROSS','Valparaíso','VALPARAÍSO','Servicio Local'),
('1518','LICEO MARIA LUISA BOMBAL','Valparaíso','VALPARAÍSO','Servicio Local'),
('1519','LICEO TECNICO PROFESIONAL BARON','Valparaíso','VALPARAÍSO','Servicio Local'),
('1520','LICEO BICENTENARIO MARITIMO DE VALPARAISO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1521','LICEO DE NINAS MARIA FRANCK DE MACDOUGAL','Valparaíso','VALPARAÍSO','Servicio Local'),
('1522','COLEGIO PEDRO MONTT','Valparaíso','VALPARAÍSO','Servicio Local'),
('1523','ESCUELA NACIONES UNIDAS','Valparaíso','VALPARAÍSO','Servicio Local'),
('1524','ESCUELA REPUBLICA ARABE SIRIA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1525','LICEO BICENTENARIO INSTITUTO TÉCNICO PROFESIONAL MARTÍTIMO DE VALPARAÍSO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1526','ESCUELA REPUBLICA DEL PARAGUAY','Valparaíso','VALPARAÍSO','Servicio Local'),
('1528','ESCUELA GASPAR CABRALES','Valparaíso','VALPARAÍSO','Servicio Local'),
('1529','ESCUELA GRECIA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1533','ESCUELA ALEMANIA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1534','ESCUELA REPUBLICA DEL URUGUAY','Valparaíso','VALPARAÍSO','Servicio Local'),
('1536','ESCUELA AMERICA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1537','ESCUELA RAMON BARROS LUCO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1538','ESCUELA JUAN JOSE LATORRE B','Valparaíso','VALPARAÍSO','Servicio Local'),
('1540','ESCUELA BLAS CUEVAS RAMON ALLENDE','Valparaíso','VALPARAÍSO','Servicio Local'),
('1541','ESCUELA REPUBLICA DE EL SALVADOR','Valparaíso','VALPARAÍSO','Servicio Local'),
('1542','ESCUELA JOAQUIN EDWARDS BELLO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1543','ESCUELA JORGE ALESSANDRI RODRIGUEZ','Valparaíso','VALPARAÍSO','Servicio Local'),
('1547','ESCUELA CARABINERO PEDRO A. CARIAGA M.','Valparaíso','VALPARAÍSO','Servicio Local'),
('1548','ESCUELA DIEGO PORTALES PALAZUELOS','Valparaíso','VALPARAÍSO','Servicio Local'),
('1549','ESCUELA REPUBLICA DE MEXICO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1550','ESCUELA PACIFICO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1551','ESCUELA MONTEDONICO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1553','ESCUELA ESPANA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1554','COLEGIO PABLO NERUDA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1555','ESCUELA REPUBLICA DE ISRAEL','Valparaíso','VALPARAÍSO','Servicio Local'),
('1556','ESCUELA ELEUTERIO RAMIREZ','Valparaíso','VALPARAÍSO','Servicio Local'),
('1557','ESCUELA VILLA BERLIN','Valparaíso','VALPARAÍSO','Servicio Local'),
('1563','ESCUELA JUAN WACQUEZ MOURFIN','Valparaíso','VALPARAÍSO','Servicio Local'),
('1567','ESCUELA BASICA DAVID BEN GURION','Valparaíso','VALPARAÍSO','Servicio Local'),
('1568','ESCUELA REPUBLICA ARGENTINA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1569','ESCUELA PILOTO 1° LUIS PARDO VILLALON','Valparaíso','VALPARAÍSO','Servicio Local'),
('1570','ESCUELA BASICA CIRUJANO VIDELA','Valparaíso','VALPARAÍSO','Servicio Local'),
('1571','ESCUELA SAN JUDAS TADEO','Valparaíso','VALPARAÍSO','Servicio Local'),
('1573','ESCUELA DR. ERNESTO QUIROZ WEBER','Valparaíso','VALPARAÍSO','Servicio Local'),
('1577','ESCUELA BÁSICA INTERCULTURAL LAGUNA VERDE','Valparaíso','VALPARAÍSO','Servicio Local'),
('1578','ESCUELA TTE. JULIO A. ALLENDE OVALLE','Valparaíso','VALPARAÍSO','Servicio Local'),
('1579','LICEO SANTA TERESA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1581','LICEO JUANA ROSS DE EDWARDS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1582','COLEGIO LUTERANO CONCORDIA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1583','COLEGIO JEANNE DARC VALPARAISO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1584','COLEGIO NOCTURNO RUBEN CASTRO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1585','LICEO COEDUCACIONAL LA IGUALDAD','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1586','COLEGIO CARLOS COUSINO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1587','COLEGIO MARIA AUXILIADORA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1588','COLEGIO NTRA.SRA.DE LA MISERICORDIA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1590','COLEGIO SALESIANO VALPARAISO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1593','ESCUELA PARTICULAR SANTA ANA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1594','COLEGIO SAN DAMIAN DE MOLOKAI','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1595','COLEGIO ARTURO EDWARDS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1596','COLEGIO SAN IGNACIO DE LOYOLA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1597','ESCUELA PARTICULAR SAN LUIS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1598','COLEGIO PARTICULAR ADVENTISTA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1599','COLEGIO SAGRADO CORAZON DE JESUS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1601','ESC SAGRADA FAMILIA DE NAZARET','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1602','COLEGIO ESPERANZA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1603','COLEGIO PARTICULAR SAN PIO X','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1604','COLEGIO LEONARDO MURIALDO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1607','COLEGIO TERESITA DE LISIEUX','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1609','ESC PART FRAY LUIS BELTRAN','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1610','COLEGIO ALBERTO HURTADO SEGUNDO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1619','COLEGIO PARTICULAR JUNIOR SCHOOL 2','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1620','COLEGIO MIGUEL DE UNAMUNO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1621','LICEO MIXTO JOSE MIGUEL CARRERA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1623','JARDIN INFANTIL SEMILLITA','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1624','JARDIN INFANTIL CARACOL','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1626','JARDIN INFANTIL CINDY','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1629','COLEGIO INTERNACIONAL','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1631','COLEGIO DE LOS SAGRADOS CORAZONES, PADRES FRANCESES','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('1632','COL. IDA.CONCEPC. NTRA.SRA.LOURDES','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1634','SEMINARIO SAN RAFAEL','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1635','COLEGIO AGUSTIN EDWARDS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1638','SCUOLA ITALIANA ARTURO DELL´ORO','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1641','COLEGIO SAN PEDRO NOLASCO','Valparaíso','VALPARAÍSO','Part. Pagado'),
('1650','COL. PART. CONSTANCIO VIGIL','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1653','COLEGIO SAN VICENTE','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1657','COLEGIO PRESB. DAVID TRUMBULL','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1663','INSTITUTO SUPERIOR DE COMERCIO ALBERTO BL','Valparaíso','VIÑA DEL MAR','Adm. Delegada'),
('1664','LICEO INDUSTRIAL MIRAFLORES ALTO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1666','C.E.I.A. LOS CASTANOS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1667','ESCUELA ESPECIAL ADOLFO TANNENBAUM B.','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1668','ESCUELA ESPECIAL RAPA NUI','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1669','ESCUELA ESPECIAL JUANITA DE AGUIRRE CERDA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1672','LICEO BICENTENARIO JOSÉ FRANCISCO VERGARA ETCHEVERS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1674','LICEO BENJAMIN VICUNA MACKENNA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1675','LICEO GUILLERMO RIVERA COTAPOS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1676','LICEO BICENTENARIO DE VIÑA DEL MAR','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1677','ESCUELA BASICA REPUBLICA DEL ECUADOR','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1678','ESCUELA UNESCO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1680','ESCUELA ORLANDO PENA CARVAJAL','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1681','COLEGIO REPUBLICA DE COLOMBIA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1682','COLEGIO MIRAFLORES','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1683','ESCUELA BASICA SANTA JULIA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1684','ESCUELA LIBERTADOR BERNARDO O^HIGGINS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1685','ESCUELA DR. OSCAR MARIN SOCIAS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1686','ESCUELA TEODORO LOWEY','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1688','ESCUELA ALMIRANTE LUIS GOMEZ CARRENO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1689','ESCUELA ORO NEGRO','Valparaíso','CONCÓN','Servicio Local'),
('1691','ESCUELA LORD COCHRANE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1692','ESCUELA ARTURO PRAT CHACON','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1693','ESCUELA BASICA 21 DE MAYO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1695','ESCUELA PEDRO AGUIRRE CERDA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1696','ESCUELA BASICA CHORRILOS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1697','ESCUELA GASTON OSSA SAINT MARIE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1698','ESCUELA PAUL HARRIS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1699','ESCUELA BASICA IRMA SALAS SILVA','Valparaíso','CONCÓN','Servicio Local'),
('1700','ESCUELA DOCTOR ADRIANO MACHADO PARDO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1701','ESCUELA LA PARVA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1702','ESCUELA CANAL BEAGLE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1703','ESCUELA PRESIDENTE JOSE MANUEL BALMACEDA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1704','ESCUELA BASICA JOHN KENNEDY','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1705','ESCUELA PRESIDENTE SALVADOR ALLENDE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1707','ESCUELA MINISTRO ZENTENO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1708','ESCUELA ENRIQUE CARDENAS RIVERA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1709','ESCUELA PATRICIO LYNCH Z.','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1710','CENTRO DE EDUCACION INTEGRADA DE ADULTOS','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1712','ESCUELA VILLA MONTE','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1714','ESCUELA SANTA MARIA DE AGUA SANTA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1716','ESCUELA VILLA INDEPENDENCIA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1717','ESCUELA CARDENAL JOSE MARIA CARO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1718','ESCUELA EDUARDO LEZANA PINCHEIRA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1720','ESCUELA MARCELA PAZ','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1721','ESCUELA BASICA REPUBLICA DEL LIBANO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1722','ESCUELA BASICA DR ALDO FRANCIA BOIDO','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1724','ESCUELA PRESIDENTE EDUARDO FREI MONTALVA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1728','ESCUELA BASICA LUISA NIETO DE HAMEL','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1732','ESCUELA VIOLETA PARRA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('1734','COLEGIO RUBEN CASTRO-DIURNO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1735','LICEO PARROQUIAL SAN ANTONIO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1738','LICEO NUESTRA SRA.DE LA PAZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1739','ESC. DE TRIPULANTES Y PORTUARIA DE VALPARAISO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('1741','LICEO SANTA TERESA DE LOS ANDES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1742','COLEGIO SAN AGUSTIN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1743','COL.PARROQUIAL SANTA MARIA GORETTI','Valparaíso','CONCÓN','Part. Subvencionado'),
('1746','INST. DESARR. PARA NINOS CON S.DOWN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1747','LICEO JOSE CORTES BROWN','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1748','COLEGIO ESPANOL MARIA REINA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1749','COLEGIO EXCMO. CARDENAL RAUL SILVA HENRIQUEZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1750','COL. INMACULADA DE LOURDES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1751','ESCUELA PARTICULAR HUGO ERRAZURIZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1752','ESCUELA PARTICULAR SANTA FILOMENA','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1755','COLEGIO ANA MARIA JANER','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1756','COLEGIO CLAUDIO MATTE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('1757','COLEGIO ACONCAGUA','Valparaíso','QUILPUÉ','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
