-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 22 de 31 | filas 8401-8800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('17830','CENTRO PSICOPEDAGÓGICO DE ESTIMULACIÓN TEMPRANA CADI','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17832','ESCUELA ESPECIAL DE TRASTORNOS DE LA COMUNICACIÓN ABRA PALABRA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17833','COLEGIO ETCHEGOYEN TALCAHUANO','Biobío','TALCAHUANO','Part. Subvencionado'),
('17834','COLEGIO SAN FERNANDO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17835','JARDIN INFANTIL ANIBAL ESQUIVEL','Biobío','CORONEL','Part. Subvencionado'),
('17836','ESCUELA DE PÁRVULOS SAN FRANCISCO','Biobío','TALCAHUANO','Corp. Municipal'),
('17837','ESCUELA DE PARVULOS EL ARENAL','Biobío','TALCAHUANO','Corp. Municipal'),
('17838','COLEGIO TECNOLOGICO DARIO SALAS','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('17840','ESCUELA BASICA NAHUELBUTA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17843','COLEGIO AURORA DE CHILE CHIGUAYANTE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17846','CENTRO EDUCACION INTEGRAL DE ADULTOS','Biobío','YUMBEL','Corp. Municipal'),
('17847','INSTITUTO EDUCACIÓN DE ADULTOS RUBÉN CAMPOS LÓPEZ','Biobío','LAJA','Corp. Municipal'),
('17848','YIRE LICEO POLITECNICO DE COIHUECO','Ñuble','COIHUECO','Part. Subvencionado'),
('17850','COLEGIO BICENTENARIO PADRE MANUEL D`ALZON','Biobío','LOTA','Part. Subvencionado'),
('17852','ESCUELA ESPECIAL DE LENGUAJE Y JARDÍN INFANTIL LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17854','COLEGIO VILLA NONGUEN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17855','COLEGIO INMACULADA CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17857','LICEO OBISPO SAN MIGUEL','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('17858','COLEGIO MIXTO INMACULADA CONCEPCION','Biobío','TALCAHUANO','Part. Subvencionado'),
('17859','COLEGIO ALMONDALE','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17860','COLEGIO SAN LUIS','Biobío','TALCAHUANO','Part. Subvencionado'),
('17862','JARDIN INFANTIL MICKY MOUSE','Biobío','TALCAHUANO','Part. Subvencionado'),
('17863','JARDIN INFANTIL ADVENTISTA DE CHILLAN','Ñuble','CHILLÁN','Part. Subvencionado'),
('17865','JARDIN INFANTIL BOTECITO DE PAPEL','Biobío','PENCO','Part. Subvencionado'),
('17868','JARDIN INFANTIL MONTESSORI','Biobío','CONCEPCIÓN','Part. Pagado'),
('17869','PEQUEÑA LULU','Biobío','CHIGUAYANTE','Part. Pagado'),
('17870','JARDÍN INFANTIL RUCA-AYUTUN','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('17871','JARDIN INFANTIL TIMONEL LA ALEGRIA DE APRENDE','Biobío','CORONEL','Part. Subvencionado'),
('17872','ESCUELA DE LENGUAJE AMANECER','Biobío','TOMÉ','Part. Subvencionado'),
('17874','ESCUELA EDELMIRA VERGARA QUIÑONES','Biobío','ARAUCO','Corp. Municipal'),
('17875','COLEGIO SAN JOAQUIN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17876','AMERICAN JUNIOR COLLEGE','Biobío','CORONEL','Part. Subvencionado'),
('17877','COLEGIO PADRE ALBERTO HURTADO LOS ANGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17878','ESCUELA ESPECIAL TRASTORNO DE LA COMUNICACIÓN SAINT BERTY','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17879','CENTRO EDUCACIÓN INTEGRAL DE ADULTOS JANEQUEO - CONCEPCIÓN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17880','CENTRO DE EDUCACIÓN DE ADULTOS ADELAILA MORENO','Biobío','TUCAPEL','Corp. Municipal'),
('17881','CENTRO EDUCACIÓN INTEGRADO ADULTOS FERMÍN FIERRO LUENGO','Biobío','CURANILAHUE','Corp. Municipal'),
('17882','ESCUELA ESPECIAL TRASTORNOS DE LA COMUNICACIÓN AYLEM','Biobío','LAJA','Part. Subvencionado'),
('17883','COLEGIO SAN TERESA DE LOS ANDES - LOS ANGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17884','ESCUELA ESP.TRAST.LENGUAJE Y J.INFANTIL TITIRIMUNDI','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17885','CENTRO EDUCACIONAL BICENTENARIO ALTOS DE TOMÉ','Biobío','TOMÉ','Corp. Municipal'),
('17886','ESC.ESP.DE TRASTORNO DE LA COMUNICACION DINAB','Ñuble','SAN CARLOS','Part. Subvencionado'),
('17888','ESCUELA ESPECIAL SOL DE LOS ANGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17889','JARDIN INFANTIL RINCÓN DE LOS NIÑOS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17892','LICEO POLIVALENTE MARTA COLVIN ANDRADE','Ñuble','CHILLÁN','Corp. Municipal'),
('17893','COLEGIO THE WESSEX SCHOOL CHILLÁN','Ñuble','CHILLÁN','Part. Pagado'),
('17894','CENTRO DE ESTIMULACION TEMPRANA ELIM','Ñuble','SAN CARLOS','Part. Subvencionado'),
('17895','COLEGIO SAN FERNANDO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17897','ESCUELA GLORIAS NAVALES','Ñuble','NINHUE','Corp. Municipal'),
('17899','ESCUELA ESPECIAL CERES','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17900','COLEGIO METODISTA CONCEPCION','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17901','ESCUELA DE LEGUANJE EL FARO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17902','COLEGIO TERESA DE LOS ANDES','Ñuble','BULNES','Part. Subvencionado'),
('17903','SEBASTIAN SCHOOL','Ñuble','CHILLÁN','Part. Subvencionado'),
('17907','COLEGIO CREACIÓN CHILLÁN','Ñuble','CHILLÁN','Part. Subvencionado'),
('17908','COLEGIO BICENTENARIO PADRE ALBERTO HURTADO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17910','ESCUELA DE LENGUAJE ARCO IRIS','Biobío','HUALPÉN','Part. Subvencionado'),
('17911','ESCUELA ESPECIAL DE TRASTORNO DE LA COMUNICACIÓN SAN RODRIC','Biobío','LOTA','Part. Subvencionado'),
('17912','COLEGIO CREACIÓN CONCEPCIÓN','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('17914','ESCUELA ESPECIAL DE LENGUAJE TIEMPO NUEVO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17915','COLEGIO POLIVALENTE DOMINGO PARRA CORVALAN','Biobío','CORONEL','Part. Subvencionado'),
('17916','ESCUELA DAFNE ELVIRA ZAPATA ROZAS','Ñuble','PEMUCO','Corp. Municipal'),
('17917','JARDÍN INFANTIL PINTITAS','Ñuble','CHILLÁN','Part. Subvencionado'),
('17918','COLEGIO SAINT GEORGE SCHOOL','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('17920','COLEGIO HISPANO AMERICANO RIO VIEJO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17924','ESCUELA NACIMIENTO DE NUESTRO SEÑOR','Biobío','NACIMIENTO','Corp. Municipal'),
('17925','ESCUELA ESPECIAL DE LENGUAJE Y JARDÍN INFANTIL TUTUMPI','Biobío','CORONEL','Part. Subvencionado'),
('17926','COLEGIO 20 DE AGOSTO','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('17927','JARDIN INFANTIL CASCANUECES','Ñuble','CHILLÁN','Part. Pagado'),
('17928','JARDIN INFANTIL MI MUNDO','Ñuble','CHILLÁN','Part. Subvencionado'),
('17930','ESCUELA EL LLANO','Ñuble','QUIRIHUE','Corp. Municipal'),
('18001','CENTRO DE ESTIMULACION TEMPRANA EGO SUM','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18002','ESCUELA JOSE FRANCISCO PINO MEDINA','Ñuble','COELEMU','Corp. Municipal'),
('18003','ESCUELA DE LENGUAJE SAN NICOLAS','Biobío','PENCO','Part. Subvencionado'),
('18004','LICEO BICENTENARIO TÉCNICO PROFESIONAL ALONSO DE ERCILLA Y ZÚÑIGA','Biobío','CAÑETE','Corp. Municipal'),
('18006','ESCUELA ELISE MOTTART','Ñuble','EL CARMEN','Corp. Municipal'),
('18007','COLEGIO CARMELA ROMERO DE ESPINOSA','Biobío','CONCEPCIÓN','Part. Pagado'),
('18008','ESCUELA ESPECIAL AMPALU','Biobío','NACIMIENTO','Part. Subvencionado'),
('18009','CENTRO INTEGRAL ADULTOS PAUL PERCIVAL HARRIS','Biobío','ARAUCO','Corp. Municipal'),
('18010','COLEGIO SAN FERNANDO CHILLÁN VIEJO','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('18011','ESC. ESPEC. DE LENGUAJE SENDEROS DE SAN PEDRO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18012','ESCUELA MARTA COLVIN ANDRADE','Ñuble','COIHUECO','Servicio Local'),
('18014','ESCUELA BASICA LOS CONQUISTADORES','Biobío','PENCO','Corp. Municipal'),
('18015','ESCUELA BASICA FORJADORES DE CHILE','Biobío','PENCO','Corp. Municipal'),
('18016','ESCUELA BASICA PUEBLO SECO','Ñuble','SAN IGNACIO','Corp. Municipal'),
('18017','LICEO TÉCNICO PROFESIONAL VIOLETA PARRA SANDOVAL','Ñuble','SAN CARLOS','Servicio Local'),
('18020','ESCUELA DE LENGUAJE ALTOS DE CHIGUAYANTE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18021','ESCUELA DIEGO PORTALES PALAZUELOS','Biobío','YUMBEL','Corp. Municipal'),
('18023','CENTRO EDUCACIÓN INTEGRAL ADULTOS PADRE CARLOS PUENTES FIGUEROA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18024','ESCUELA ESPECIAL DE DISCAPACIDAD AUDITIVA Y TRASTORNOS GRAVES DE LA COMUNICACIÓN HÁBLAME DE AMOR','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18025','ESCUELA DE LENGUAJE MAR AZUL','Biobío','TALCAHUANO','Part. Subvencionado'),
('18026','ESCUELA DE LENGUAJE SAN SEBASTIAN','Biobío','YUMBEL','Part. Subvencionado'),
('18027','ESCUELA DE LENGUAJE TIMONEL','Biobío','CORONEL','Part. Subvencionado'),
('18028','COLEGIO CIUDAD EDUCATIVA','Ñuble','CHILLÁN','Part. Subvencionado'),
('18029','ESCUELA DE LENGUAJE SANTA MARIETTA','Biobío','TALCAHUANO','Part. Subvencionado'),
('18030','ESCUELA DE LENGUAJE CICEL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18031','ESCUELA DE LENGUAJE FLORIDA','Biobío','FLORIDA','Part. Subvencionado'),
('18032','CENTRO DE CAPACITACIÓN LABORAL EDUCACIÓN ESPECIAL PAULO FREIRE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18034','COLEGIO SOUTHERN COLLEGE','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18035','COLEGIO SAN AGUSTIN','Ñuble','QUIRIHUE','Part. Subvencionado'),
('18037','LICEO RALCO','Biobío','ALTO BIOBÍO','Corp. Municipal'),
('18038','ESCUELA DIFERENCIAL RAYITO DE SOL','Biobío','CORONEL','Part. Subvencionado'),
('18039','JARDÍN INFANTIL Y ESCUELA ESPECIAL DE LENGUAJE MAISON DE L´ENFANCE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18040','ESCUELA DE LENGUAJE Y JARDÍN INFANTIL PORVENIR','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18042','COLEGIO WENGA CORONEL','Biobío','CORONEL','Part. Subvencionado'),
('18043','ESCUELA DE LENGUAJE LOMAS COLORADAS','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18044','ESCUELA DE LENGUAJE Y JARDÍN INFANTIL TITIRIMUNDI','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18045','CENTRO DE CAPACITACIÓN LABORAL BERNARDO O`HIGGINS','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('18047','ESCUELA DIFERENCIAL BAO BAB','Biobío','HUALPÉN','Part. Subvencionado'),
('18049','COLEGIO ADVENTISTA DE CONCEPCION','Biobío','TALCAHUANO','Part. Subvencionado'),
('18050','COLEGIO LA FUENTE','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18051','ESCUELA BASICA DIFERENCIAL ARCO IRIS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18052','ESCUELA DE LENGUAJE CHILEDUCA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18054','CENTRO DE NIVELACIÓN Y DE CAPACITACIÓN PARA ADULTOS MADRE MARIA M Y S','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18055','COLEGIO MOZART SCHULE','Biobío','CONCEPCIÓN','Part. Pagado'),
('18061','ESCUELA DE LENGUAJE BULNES','Ñuble','BULNES','Part. Subvencionado'),
('18062','ESCUELA DE LENGUAJE INALAF','Biobío','TALCAHUANO','Part. Subvencionado'),
('18063','ESCUELA DE LENGUAJE BELEN','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18064','ESCUELA DE LENGUAJE VALENTINA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18065','ESCUELA NUEVA REPUBLICA','Biobío','HUALQUI','Servicio Local'),
('18066','COLEGIO AURORA DE CHILE SUR','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18069','CENTRO INTEGRAL DE EDUCACIÓN HIGH SCOPE LIMITADA','Biobío','HUALPÉN','Part. Subvencionado'),
('18073','JARDIN INFANTIL JUAN BAUTISTA','Biobío','ARAUCO','Part. Subvencionado'),
('18074','ESCUELA DE LENGUAJE SANTA JUANA','Biobío','SANTA JUANA','Part. Subvencionado'),
('18075','COLEGIO JAHVE NISI','Biobío','SANTA JUANA','Part. Subvencionado'),
('18076','JARDIN INFANTIL KARAMELO','Biobío','MULCHÉN','Part. Subvencionado'),
('18077','CENTRO DE EXPLORACIÓN CAPACITACIÓN LABORAL SAN RAFAEL','Ñuble','CHILLÁN','Part. Subvencionado'),
('18078','ESCUELA DE LENGUAJE EL VALLE','Ñuble','QUILLÓN','Part. Subvencionado'),
('18079','ESCUELA DE LENGUAJE ASERRIN ASERRAN','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18080','LICEO POLITECNICO CARAMPANGUE','Biobío','ARAUCO','Corp. Municipal'),
('18081','ESCUELA DE LENGUAJE EDUCERE','Biobío','HUALQUI','Part. Subvencionado'),
('18082','ESCUELA ADULTOS INTECAP','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18085','ESCUELA DE LENGUAJE MY DISNEY','Ñuble','COELEMU','Part. Subvencionado'),
('18087','DINABEC COLLEGE','Ñuble','SAN CARLOS','Part. Subvencionado'),
('18088','CENTRO DE FORMACION LABORAL SAN ANDRES','Biobío','CORONEL','Part. Subvencionado'),
('18089','ESCUELA DE LENGUAJE BAMBI','Biobío','CAÑETE','Corp. Municipal'),
('18090','COLEGIO SAN LORENZO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18091','ESCUELA ESPECIAL LOS NARANJOS','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('18092','ESCUELA DE LENGUAJE LARAQUETE','Biobío','ARAUCO','Part. Subvencionado'),
('18093','COLEGIO EL VALLE DE HUALQUI','Biobío','HUALQUI','Part. Subvencionado'),
('18094','CHRISTIAN COLLEGE','Biobío','HUALQUI','Part. Subvencionado'),
('18095','ESCUELA DE LENGUAJE SAN PABLO','Biobío','LEBU','Part. Subvencionado'),
('18096','ESCUELA DE LENGUAJE ALBORADA','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('18097','COLEGIO ALMONDALE LOMAS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18099','LICEO TOMAS LAGO','Ñuble','CHILLÁN VIEJO','Corp. Municipal'),
('18100','CENTRO DE FORMACIÓN LABORAL Y EDUCACIÓN DE ADULTOS EDUCERE','Biobío','HUALQUI','Part. Subvencionado'),
('18101','ESCUELA DE LENGUAJE ATRAPA PALABRAS','Biobío','MULCHÉN','Part. Subvencionado'),
('18102','COLEGIO PAULO FREIRE','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18104','ESCUELA ESPECIAL DIFERENCIAL CENTRO DE RECURSOS PERSEVERA','Ñuble','CHILLÁN','Part. Subvencionado'),
('18105','ESCUELA DE LENGUAJE GIRASOL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18106','ESCUELA ESPECIAL DEL MAR','Biobío','TALCAHUANO','Part. Subvencionado'),
('18107','ESCUELA ESPECIAL DE LENGUAJE SEMILLITA','Biobío','HUALPÉN','Part. Subvencionado'),
('18108','ESCUELA ESPECIAL DE LENGUAJE QUIRIHUE','Ñuble','QUIRIHUE','Part. Subvencionado'),
('18109','ESCUELA ESPECIAL DIFERENCIAL SOL NACIENTE','Biobío','CORONEL','Part. Subvencionado'),
('18110','JARDIN INFANTIL PAPELUCHO','Ñuble','CHILLÁN','Part. Subvencionado'),
('18111','COMPLEJO EDUCACIONAL GLORIA MENDEZ BRIONES','Biobío','PENCO','Part. Subvencionado'),
('18112','COLEGIO BICENTENARIO INES ENRIQUEZ FRODDEN','Biobío','FLORIDA','Servicio Local'),
('18113','ESCUELA ESPECIAL LOS GIRASOLES','Biobío','NEGRETE','Part. Subvencionado'),
('18114','COLEGIO A-LAFKEN','Biobío','PENCO','Part. Subvencionado'),
('18116','JARDIN INFANTIL SNOOPY','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18119','ESCUELA ESPECIAL DE LENGUAJE MATILDA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18121','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS TESOROS','Biobío','HUALPÉN','Part. Subvencionado'),
('18122','ESCUELA ESPECIAL DE LENGUAJE CIDNEE','Biobío','CORONEL','Part. Subvencionado'),
('18123','COLEGIO Y ESCUELA DE LENGUAJE CENTRO EDUCACIONAL PEUMAYEN','Biobío','CABRERO','Part. Subvencionado'),
('18124','COLEGIO SANTA TERESITA','Ñuble','COELEMU','Part. Subvencionado'),
('18126','COLEGIO PORVENIR SCHOOL','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18127','CENTRO EDUCACIONAL ALBORADA','Biobío','PENCO','Part. Subvencionado'),
('18128','COLEGIO SANTO TOMÁS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18130','ESCUELA ESPECIAL DE LENGUAJE AMANECER','Biobío','TALCAHUANO','Part. Subvencionado'),
('18131','ESCUELA ESPECIAL DE LENGUAJE ENTRE PALABRAS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18132','ESCUELA ESPECIAL DIFERENCIAL LUIS ESPINOZA PIERRETTI','Biobío','TALCAHUANO','Part. Subvencionado'),
('18133','ESC ESP DIF CENTRO ATENCION TEMPRANA Y BASICO ESPECIAL PASO A PASITO','Ñuble','CHILLÁN','Part. Subvencionado'),
('18138','JARDIN INFANTIL CANTACUENTOS','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18139','ESCUELA DE LENGUAJE RAYEN-ANTU','Biobío','CURANILAHUE','Corp. Municipal'),
('18140','JARDÍN INFANTIL EBEN-EZER','Ñuble','CHILLÁN','Part. Subvencionado'),
('18142','CENTRO ESTIMULACIÓN TEMPRANA PRINCESITA MISIN','Biobío','NACIMIENTO','Part. Subvencionado'),
('18143','ESCUELA DIFERENCIAL ESTRELLITA DE BELÉN','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18144','ESCUELA ESPECIAL DE LENGUAJE PADRE ALBERTO HURTADO','Biobío','CURANILAHUE','Part. Subvencionado'),
('18146','CENTRO DIFERENCIAL ESTIMULACIÓN TEMPRANA MANANTIAL','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18147','COLEGIO EDUCA BIOBÍO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18149','COLEGIO RUCALHUE','Biobío','HUALPÉN','Part. Subvencionado'),
('18150','ESCUELA DIFERENCIAL ASPAUT CHIGUAYANTE','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18152','INSTITUTO DE ATENCION A LA DIVERSIDAD INAD','Biobío','LEBU','Part. Subvencionado'),
('18153','CENTRO PSICOPEDAGOGICO EMMANUEL','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18154','ESCUELA ESPECIAL DE LENGUAJE TIMONEL CORONEL','Biobío','CORONEL','Part. Subvencionado'),
('18155','ESCUELA ESPECIAL DE LENGUAJE ARAUCO','Biobío','ARAUCO','Corp. Municipal'),
('18156','JARDÍN INFANTIL Y ESCUELA ESPECIAL DE LENGUAJE AGUA DE PEUMO','Ñuble','PEMUCO','Part. Subvencionado'),
('18157','ESCUELA ESPECIAL DE LENGUAJE RAYEN','Biobío','SAN ROSENDO','Part. Subvencionado'),
('18158','COLEGIO LICAN RAY','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18159','ESCUELA DE LENGUAJE ALMENDRA','Ñuble','QUILLÓN','Part. Subvencionado'),
('18160','ESCUELA ESPECIAL DE LENGUAJE CAMPANITA','Biobío','TOMÉ','Part. Subvencionado'),
('18162','ESCUELA ESPECIAL DE LENGUAJE ANTUKUYEN','Biobío','NEGRETE','Part. Subvencionado'),
('18163','COLEGIO PRESTON SCHOOL','Biobío','HUALPÉN','Part. Pagado'),
('18164','ESCUELA ESPECIAL DE LENGUAJE VILLA HERMOSA','Biobío','HUALPÉN','Part. Subvencionado'),
('18166','CENTRO CAPACITACIÓN LABORAL MIRANDO EL FUTURO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18167','ESCUELA ESPECIAL DE LENGUAJE ARAUCARIA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18168','ESCUELA ESPECIAL DE LENGUAJE BUEN RETIRO','Biobío','CORONEL','Part. Subvencionado'),
('18169','ESCUELA ESPECIAL ANTU','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18170','COLEGIO MONTE ÁGUILA COLLEGE','Biobío','CABRERO','Part. Subvencionado'),
('18172','COLEGIO AMANECER TALCAHUANO','Biobío','TALCAHUANO','Part. Subvencionado'),
('18173','ESCUELA ESPECIAL DE LENGUAJE LAS PALMERITAS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18175','CENTRO FORMACIÓN LABORAL LIWENKO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18176','ESCUELA ESPECIAL DE LENGUAJE NUEVO FUTURO','Biobío','PENCO','Part. Subvencionado'),
('18178','ESCUELA ESPECIAL DE LENGUAJE JARDÍN DE PALABRAS','Biobío','PENCO','Part. Subvencionado'),
('18181','INSTITUTO HUMANIDADES MONSEÑOR JOSE MANUEL SANTO ASCARZA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18183','COLEGIO PER SÉ','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18184','COLEGIO BORDERIO','Biobío','MULCHÉN','Part. Subvencionado'),
('18185','JARDIN INFANTIL LOS PEQUEÑOS ARTESANOS','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18186','JARDIN INFANTIL LOS PECECITOS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18187','ESCUELA ESPECIAL DE LENGUAJE BOSQUE MIO','Biobío','CABRERO','Part. Subvencionado'),
('18188','ESCUELA DE LENGUAJE LLACOLEN','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18189','ESCUELA DE LENGUAJE AMULEN','Biobío','SANTA JUANA','Part. Subvencionado'),
('18190','ESCUELA ESPECIAL DE LENGUAJE ALCAZAR','Biobío','PENCO','Part. Subvencionado'),
('18191','ESCUELA ESPECIAL DE LENGUAJE ABRAPALABRA','Ñuble','COIHUECO','Part. Subvencionado'),
('18192','ESCUELA ESPECIAL DE LENGUAJE HUEPIL','Biobío','TUCAPEL','Part. Subvencionado'),
('18193','ESCUELA ESPECIAL DE LENGUAJE KETRAWUE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18194','ESCUELA ESPECIAL DE LENGUAJE PALABRITAS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18195','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑOS SUEÑOS','Ñuble','COIHUECO','Part. Subvencionado'),
('18197','ESCUELA ESPECIAL DE LENGUAJE LLAIPÉN','Ñuble','QUIRIHUE','Part. Subvencionado'),
('18199','COLEGIO QUILLÓN','Ñuble','QUILLÓN','Part. Subvencionado'),
('18200','ESCUELA ESPECIAL DIFERENCIAL ANGELITOS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18202','ESCUELA ESPECIAL DE LENGUAJE ALONKURA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18203','ESCUELA ESPECIAL DE LENGUAJE KIMALU','Biobío','PENCO','Part. Subvencionado'),
('18204','JARDIN INFANTIL ZAPATITO JUGUETON','Ñuble','CHILLÁN','Part. Subvencionado'),
('18205','ESCUELA ESPECIAL DE LENGUAJE BOSQUE MAGICO','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18206','ESCUELA ESPECIAL DE LENGUAJE AMAPOLA','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18207','ESCUELA ESPECIAL DE LENGUAJE PINTO Y APRENDO','Ñuble','PINTO','Part. Subvencionado'),
('18208','ESCUELA ESPECIAL DE LENGUAJE ALTO DEL LAJA','Biobío','LAJA','Part. Subvencionado'),
('18210','ESCUELA ESPECIAL DE LENGUAJE SAN FRANCISCO DE ASIS','Biobío','TALCAHUANO','Part. Subvencionado'),
('18211','ESCUELA ESPECIAL DE LENGUAJE MIS DULCES PALABRAS','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18213','ESCUELA ESPECIAL DE LENGUAJE ADONAY','Biobío','MULCHÉN','Part. Subvencionado'),
('18214','JARDIN INFANTIL Y ESCUELA DE LENGUAJE PRIMEROS PASOS','Ñuble','CHILLÁN','Part. Subvencionado'),
('18216','COLEGIO AMANECER','Ñuble','BULNES','Part. Subvencionado'),
('18218','COLEGIO NUEVOS HORIZONTES','Biobío','SAN PEDRO DE LA PAZ','Servicio Local'),
('18219','ESCUELA ESPECIAL DE LENGUAJE FLOR DE JAZMIN','Ñuble','COELEMU','Part. Subvencionado'),
('18220','COLEGIO BICENTENARIO NUEVA ESPERANZA DE YUNGAY','Ñuble','YUNGAY','Part. Subvencionado'),
('18222','ESCUELA ESPECIAL DE LENGUAJE PASITOS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18223','COLEGIO EL FARO','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18224','ESCUELA ESPECIAL DE LENGUAJE GOLDEN HOUSE','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18225','ESCUELA ESPECIAL DE LENGUAJE CANTO DE LUNA','Ñuble','SAN CARLOS','Part. Subvencionado'),
('18226','ESCUELA ESPECIAL DE LENGUAJE PALABRAS MÁGICAS','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18227','ESCUELA ESPECIAL DE LENGUAJE ALTO TUCAPEL','Biobío','CAÑETE','Part. Subvencionado'),
('18228','CENTRO DE LENGUAJE INTECAP','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18230','ESCUELA ESPECIAL DE LENGUAJE EL TRENCITO','Biobío','YUMBEL','Part. Subvencionado'),
('18231','ESCUELA ESPECIAL DE LENGUAJE CUMBRES DE SAN IGNACIO','Ñuble','SAN IGNACIO','Part. Subvencionado'),
('18233','ESCUELA ESPECIAL DE LENGUAJE ARBOLIRIS','Biobío','CORONEL','Part. Subvencionado'),
('18234','COLEGIO ALTAZOR','Biobío','ANTUCO','Part. Subvencionado'),
('18235','ESCUELA DE LENGUAJE ALTUE','Biobío','TALCAHUANO','Part. Subvencionado'),
('18236','ESCUELA ESPECIAL DIFERENCIAL Y DE LENGUAJE MAISON DE L`ENFANCE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18237','COLEGIO AMANECER SAN CARLOS','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18238','ESCUELA DE LENGUAJE ALBORADA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('18239','ESCUELA ESPECIAL DE LENGUAJE MANQUIMAVIDA','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('18240','JARDIN INFANTIL JUGANDO APRENDO','Biobío','HUALPÉN','Part. Subvencionado'),
('18241','CENTRO DE EDUCACIÓN INTEGRAL DE ADULTOS NAHUELQUÍN','Biobío','TALCAHUANO','Part. Subvencionado'),
('18243','COLEGIO INGLÉS PALABRAS DE VIDA','Ñuble','COIHUECO','Part. Subvencionado'),
('18244','ESCUELA DIFERENCIAL CENTRO DE ESTUDIO E INCLUSION LABORAL BIOCOR','Biobío','CORONEL','Part. Subvencionado'),
('18245','ESCUELA ESPECIAL DE LENGUAJE SENDERO MÁGICO','Ñuble','COELEMU','Part. Subvencionado'),
('18247','COLEGIO SAN NICOLÁS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('18248','ESCUELA EL RENOVAL','Biobío','CORONEL','Part. Subvencionado'),
('18249','COLEGIO INSTITUTO CRISTIANO GRACIA Y PAZ','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18250','JARDÍN INFANTIL Y ESCUELA ESPECIAL ARCOIRIS','Biobío','HUALQUI','Part. Subvencionado'),
('18251','COLEGIO ALTURAS DE CHILLÁN','Ñuble','CHILLÁN','Part. Subvencionado'),
('18252','ESCUELA ESPECIAL DE LENGUAJE MI ANGEL','Ñuble','EL CARMEN','Part. Subvencionado'),
('18253','ESCUELA ESPECIAL DE LENGUAJE JUAN PABLO II','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('18254','ESCUELA ESPECIAL DE LENGUAJE SANTA CATALINA','Biobío','TALCAHUANO','Part. Subvencionado'),
('18255','ESCUELA ESPECIAL DE LENGUAJE EFRAIN AEDO','Biobío','CORONEL','Part. Subvencionado'),
('19630','ESCUELA ESPECIAL DE LENGUAJE FAROLITO DORADO','Biobío','CORONEL','Part. Subvencionado'),
('19902','ESCUELA ANEXA DE PELEHUITO','La Araucanía','LOS SAUCES','Corp. Municipal'),
('19906','LICEO BICENTENARIO  POLITECNICO EMA ESPINOZA CORREA','La Araucanía','LAUTARO','Corp. Municipal'),
('19907','ESCUELA ESPECIAL CLARET','La Araucanía','TEMUCO','Part. Subvencionado'),
('19908','GREEN HOUSE SCHOOL','La Araucanía','TEMUCO','Part. Pagado'),
('19910','ESCUELA PARTICULAR SAN LORENZO','La Araucanía','CHOLCHOL','Part. Subvencionado'),
('19911','ESCUELA PARTICULAR BOLLILCO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('19912','ESC. BASICA CRUZ DEL SUR','La Araucanía','VILCÚN','Corp. Municipal'),
('19913','LICEO BICENTENARIO LOS SAUCES','La Araucanía','LOS SAUCES','Corp. Municipal'),
('19914','ESC.ESP.RET.MENTAL FEYENTUN','La Araucanía','VILCÚN','Corp. Municipal'),
('19918','ESCUELA ESPECIAL ERICO HORNUNG','La Araucanía','COLLIPULLI','Corp. Municipal'),
('19919','ESCUELA PARTICULAR APOCALIPSIS','La Araucanía','CARAHUE','Part. Subvencionado'),
('19921','INSTITUTO CAMILO HENRIQUEZ','La Araucanía','VILLARRICA','Part. Subvencionado'),
('19922','ESCUELA PARTICULAR ANTUMALAL','La Araucanía','LAUTARO','Part. Subvencionado'),
('19923','ESCUELA NRO 15 AMI','La Araucanía','TEMUCO','Part. Subvencionado'),
('19925','LICEO PARTICULAR COMERCIAL CARAHUE','La Araucanía','CARAHUE','Part. Subvencionado'),
('19926','COLEGIO DE DESARROLLO INTEGRAL PILARCITA','La Araucanía','TEMUCO','Part. Subvencionado'),
('19927','ESCUELA BASICA VOLCAN LLAIMA','La Araucanía','MELIPEUCO','Corp. Municipal'),
('19928','ESCUELA PARTICULAR SAN IGNACIO','La Araucanía','CARAHUE','Part. Subvencionado'),
('19930','ESC. PART. BASICA COMUN BOLIL','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('19931','ESCUELA ESPECIAL DAME LA MANO','La Araucanía','GALVARINO','Corp. Municipal'),
('19934','ESCUELA PARTICULAR EL DESPERTAR','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('19945','ESCUELA ESPECIAL TULIO MORA ALARCON','La Araucanía','PURÉN','Corp. Municipal'),
('19947','ESCUELA LAURA VICUNA','La Araucanía','VILLARRICA','Part. Subvencionado'),
('19949','ESCUELA PARTICULAR SANTA OLGA','La Araucanía','CARAHUE','Part. Subvencionado'),
('19950','ESCUELA PARTICULAR SAN ANDRES','La Araucanía','CURACAUTÍN','Part. Subvencionado'),
('19952','COLEGIO ANGOL','La Araucanía','ANGOL','Part. Subvencionado'),
('19953','ESCUELA BILINGUE AMUL KEWUN','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('19954','COLEGIO ESPECIAL DE TRASTORNOS DE LA COMUNICACION ORAL Nº 34, DOCKSTA','La Araucanía','CARAHUE','Part. Subvencionado'),
('19956','ESCUELA BASICA MAHUIDA','La Araucanía','LOS SAUCES','Corp. Municipal'),
('19958','ESCUELA PARTICULAR QUINQUEN','La Araucanía','LONQUIMAY','Part. Subvencionado'),
('19959','COLEGIO JUAN XXIII','La Araucanía','TEMUCO','Part. Subvencionado'),
('19960','COLEGIO ANTUMALEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('19962','SOUTHERN OXFORD SCHOOL','La Araucanía','VILLARRICA','Part. Pagado'),
('19964','ESC. ESPECIAL PART. ALENKURA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('19965','ESCUELA PARTICULAR TERESA DE LOS ANDES','La Araucanía','LOS SAUCES','Part. Subvencionado'),
('19968','COLEGIO ADVENTISTA DE PITRUFQUEN','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('19969','CENTRO EDUCACIONAL ESPECIAL INCLUSIVO SAN CRISTOBAL','La Araucanía','TEMUCO','Part. Subvencionado'),
('19972','MOZART SCHOOL','La Araucanía','ANGOL','Part. Subvencionado'),
('19973','ESCUELA ESPECIAL HABLAARTE','La Araucanía','TEMUCO','Part. Subvencionado'),
('19974','COMPLEJO EDUCACIONAL LA FRONTERA','La Araucanía','TEMUCO','Part. Subvencionado'),
('19981','COLEGIO NUEVA CONCEPCION','La Araucanía','TEMUCO','Part. Subvencionado'),
('19983','COLEGIO EMPRENDER TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('19984','COLEGIO ESPECIAL DE LENGUAJE HOLANDA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('19985','JARDIN INFANTIL JEAN PIAGET','La Araucanía','VICTORIA','Part. Pagado'),
('19990','JARDIN INFANTIL Y SALA CUNA PARVUS','La Araucanía','TEMUCO','Part. Pagado'),
('19992','JARDIN INFANTIL LOS PEQUES','La Araucanía','TEMUCO','Part. Pagado'),
('19993','C.E.I.A. ANTONIO ACEVEDO HERNANDEZ','La Araucanía','ANGOL','Corp. Municipal'),
('19996','ESCUELA NUEVA MENETUE','La Araucanía','VILLARRICA','Part. Subvencionado'),
('19999','ESCUELA PARTICULAR GALLETUE','La Araucanía','LONQUIMAY','Part. Subvencionado'),
('20001','C.E.I.A. ALERTA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20002','ESCUELA DE LA COMUNICACION ICALMA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20008','COLEGIO EL LABRADOR','La Araucanía','VICTORIA','Part. Subvencionado'),
('20010','ESCUELA ENRIQUE TENORIO FUENTES','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20012','CENTRO DE EDUC. ADULTOS PAULO FREIRE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20015','ESC.PART.SAN FRANCISCO DE COIHUE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('20016','COLEGIO DE APLICACION','La Araucanía','TEMUCO','Part. Subvencionado'),
('20018','ESCUELA SAN JUAN DE DIOS','La Araucanía','GALVARINO','Part. Subvencionado'),
('20019','SUN FLOWER SCHOOL','La Araucanía','TEMUCO','Part. Subvencionado'),
('20024','ESCUELA PARTICULAR HUENTE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('20025','ESCUELA ARTISTICA ARMANDO DUFEY BLANC','La Araucanía','TEMUCO','Corp. Municipal'),
('20026','ESCUELA MAPU- LAFKEN','La Araucanía','CARAHUE','Part. Subvencionado'),
('20027','ESCUELA HUERTOS MINEROS','La Araucanía','CARAHUE','Part. Subvencionado'),
('20029','ESCUELA SANTA VICTORIA','La Araucanía','GALVARINO','Part. Subvencionado'),
('20030','ESC.ESPEC.ESDELENG TRAST.DE LA COMUNIC..','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20033','COLEGIO CUMBRES DEL BUDI','La Araucanía','SAAVEDRA','Part. Subvencionado'),
('20037','LICEO DEL DESARROLLO FORMACIÓN TP','La Araucanía','TEMUCO','Part. Subvencionado'),
('20041','ESCUELA PARTICULAR CLAUDIO ARRAU','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20042','ESC. PART. LUCILA GODOY ALCAYAGA','La Araucanía','ANGOL','Part. Subvencionado'),
('20043','CENTRO DE EDUCACION DE ADULTOS LEFXARV','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20044','CTRO.EDUC.ADULTOS T.P. EL SEMBRADOR','La Araucanía','TEMUCO','Part. Subvencionado'),
('20046','ESCUELA PART. MISS CLARA BRINCEFIELD','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20047','CENTRO DE ESTUDIOS DE LAS COMUNICACIONES PARA EL TRABAJO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20048','COLEGIO SCOLE CREARE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20052','COMPLEJO EDUCACIONAL VICTORIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('20053','LICEO TECNICO PROFESIONAL HUALPIN','La Araucanía','TEODORO SCHMIDT','Servicio Local'),
('20058','ESCUELA ESPECIAL LAS LILAS DE TRAIGUEN','La Araucanía','TRAIGUÉN','Corp. Municipal'),
('20063','CENTRO DE EDUC.I.ADUL.MIGUEL DE CERVANTES','La Araucanía','TEMUCO','Part. Subvencionado'),
('20064','COLEGIO BICENTENARIO DE LA ARAUCANIA','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20065','JARDIN INFANTIL RAYITO DE SOL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20066','CENTRO DE ESTUDIOS Y CAPACITACION LIMITADA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20067','ESCUELA FRANCISCO QUEREBAN','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20068','ESCUELA PARTICULAR SAINT GEORGE','La Araucanía','ANGOL','Part. Subvencionado'),
('20071','ESCUELA PARTICULAR LA DEHESA','La Araucanía','CUNCO','Part. Subvencionado'),
('20073','CENTRO EDUC.INTEGRAL ADULTOS ACROPOLIS','La Araucanía','CUNCO','Part. Subvencionado'),
('20074','CAMBRIDGE COLLEGE PRIMAVERA','La Araucanía','VILCÚN','Part. Subvencionado'),
('20078','LICEO FUTURO CARLOS LEAL SANHUEZA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20080','ESCUELA PARTICULAR JUVENCIO VALLE','La Araucanía','TEODORO SCHMIDT','Part. Subvencionado'),
('20082','ESCUELA PART.NUESTRA SENORA DEL ROSARIO','La Araucanía','ANGOL','Part. Subvencionado'),
('20084','ESCUELA PARTICULAR CHIHUIMPILLI','La Araucanía','FREIRE','Part. Subvencionado'),
('20085','COLEGIO GOLDEN SCHOOL','La Araucanía','TEMUCO','Part. Subvencionado'),
('20087','ESCUELA ARCO IRIS','La Araucanía','LUMACO','Part. Subvencionado'),
('20088','ESCUELA POETISA GABRIELA MISTRAL','La Araucanía','CARAHUE','Part. Subvencionado'),
('20089','C.E.I.A VILCUN','La Araucanía','VILCÚN','Part. Subvencionado'),
('20090','COLEGIO LEONARDO DA VINCI SCHOOL','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('20091','COLEGIO PUMAHUE','La Araucanía','TEMUCO','Part. Pagado'),
('20092','JARDIN INFANTIL BICHITOS','La Araucanía','TEMUCO','Part. Pagado'),
('20095','COLEGIO CAMILO HENRIQUEZ DE PEDREGOSO','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20096','COLEGIO BETANIA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20097','ESCUELA ESPECIAL ALFONSO RECART','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20099','ESCUELA ALIWEN DE LLAMUCO','La Araucanía','VILCÚN','Part. Subvencionado'),
('20100','COLEGIO CONGREGACIÓN OLIVOS','La Araucanía','TEMUCO','Part. Subvencionado'),
('20102','ESCUELA ESPECIAL HOSPITALARIA TEMUCO','La Araucanía','TEMUCO','Part. Subvencionado'),
('20103','LICEO MUNICIPAL LUMACO','La Araucanía','LUMACO','Corp. Municipal'),
('20106','JARDIN INFANTIL MI MUNDO','La Araucanía','TRAIGUÉN','Part. Pagado'),
('20108','COLEGIO LIDIA GONZALEZ BARRIGA','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('20113','ESCUELA BASICA PART VISTA HERMOSA','La Araucanía','PERQUENCO','Part. Subvencionado'),
('20114','LICEO ADULTOS AMERICO VESPUCIO RBD 20114-6','La Araucanía','TEMUCO','Part. Subvencionado'),
('20117','ESCUELA LOS ALAMOS','La Araucanía','GALVARINO','Part. Subvencionado'),
('20119','ESCUELA SANTA TERESITA DE IMPERIAL','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20120','COLEGIO JOSE GIORDANO','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20121','ESCUELA MUNICIPAL LOS ARRAYANES','La Araucanía','PUCÓN','Corp. Municipal'),
('20122','ESCUELA TRANI-TRANI','La Araucanía','TEMUCO','Part. Subvencionado'),
('20127','LICEO TECN. PROF. FORESTAL PEHUEN','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20129','ESCUELA GRACIA Y PAZ','La Araucanía','TEMUCO','Part. Subvencionado'),
('20131','COLEGIO DE ADULTOS SOL DE AMERICA','La Araucanía','TEMUCO','Part. Subvencionado'),
('20133','ESCUELA BASICA NINOS FELICES','La Araucanía','VILCÚN','Part. Subvencionado'),
('20137','COLEGIO INNOV-ARTE','La Araucanía','TEMUCO','Part. Subvencionado'),
('20139','LICEO TECNOLOGICO MONTEMARIA','La Araucanía','PUCÓN','Part. Subvencionado'),
('20140','ESCUELA PART. APRENDIENDO A VIVIR','La Araucanía','TEMUCO','Part. Subvencionado'),
('20141','ESCUELA PARTICULAR EMANUEL','La Araucanía','VICTORIA','Part. Subvencionado'),
('20144','ESCUELA PARTICULAR EL MIRADOR','La Araucanía','CARAHUE','Part. Subvencionado'),
('20145','ESCUELA GOLDEN HOUSE','La Araucanía','CARAHUE','Part. Subvencionado'),
('20151','LICEO PARTICULAR DE ADULTOS HOREB','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('20152','AYIÑLEO (LA LUZ Y EL AMOR QUE NUNCA SE EXTINGUE)','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('20153','COLEGIO PUCÓN','La Araucanía','PUCÓN','Part. Subvencionado'),
('20154','ESCUELA BASICA ANTU RAYEN','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('20155','ESCUELA ESP. DE LENGUAJE ANTUMAPU','La Araucanía','TEMUCO','Part. Subvencionado'),
('20156','JARDIN INFANTIL PEQUENAS SEMILLAS','La Araucanía','TEMUCO','Part. Subvencionado'),
('20158','COLEGIO ALTAS CUMBRES','La Araucanía','VILLARRICA','Part. Subvencionado'),
('20159','LICEO PARTICULAR JAN COMENIUS','La Araucanía','TEMUCO','Part. Subvencionado'),
('20161','ESCUELA PART. SUBVENCIONADA AMANCAY','La Araucanía','LAUTARO','Part. Subvencionado'),
('20162','COLEGIO REINO DE SUECIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('20164','LICEO AGRICOLA SAN SEBASTIAN','La Araucanía','PERQUENCO','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
