-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 20 de 31 | filas 7601-8000
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('14871','COLEGIO ALIMAPU','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14872','ESCUELA DE LENGUAJE ANTU AINIL','Valparaíso','LIMACHE','Part. Subvencionado'),
('14873','COLEGIO BAUTISTA JESUS MI REFUGIO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14874','CENTRO DE ESTUDIOS FRANCISCO BILBAO','Valparaíso','CASABLANCA','Part. Subvencionado'),
('14876','ESC. ESP. DE LENGUAJE JARDIN DEL MAR','Valparaíso','EL QUISCO','Part. Subvencionado'),
('14877','LICEO SAN ESTEBAN','Valparaíso','SAN ESTEBAN','Corp. Municipal'),
('14878','ESCUELA DE PARVULOS EBENEZERITO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14879','LICEO PART, MIXTO SAN FELIPE','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14880','ESC. ESP. DE LENG. Y JARDIN INF. LOS ROBLES DE QUILLOTA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14881','LICEO ALDEA EDUCATIVA RAPA NUI','Valparaíso','ISLA DE PASCUA','Corp. Municipal'),
('14882','ESC.ESPECIAL DE LENGUAJE OROLONCO','Valparaíso','PUTAENDO','Part. Subvencionado'),
('14883','ESCUELA DE LENGUAJE ALIWEN','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14885','COLEGIO LEONARDO DA VINCI','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14887','ESCUELA ESPECIAL SOL Y LUNA','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14890','ESCUELA ESPECIAL CICED','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14893','ESCUELA DE PARVULOS ANDALUE','Valparaíso','CALERA','Part. Pagado'),
('14894','ESCUELA ESP. DE LENGUAJE MILLANTU','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14896','COLEGIO SAN HERNALDO','Valparaíso','PUCHUNCAVÍ','Part. Subvencionado'),
('14897','ESC. ESPECIAL DE LENGUAJE ALBERTO HURTADO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14898','ESCUELA DE PARVULOS EMILITA','Valparaíso','SAN ANTONIO','Part. Pagado'),
('14901','COLEGIO SIMON BOLIVAR','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14902','COLEGIO FUNDADORES DE LA CALERA','Valparaíso','CALERA','Part. Pagado'),
('14903','ESC.ESP.DE LENG.NIÑO DIVINO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14904','ESCUELA DE PARVULOS CASCANUECES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14907','ESCUELA ESPECIAL DE LENGUAJE ANTU','Valparaíso','LA CRUZ','Part. Subvencionado'),
('14909','ESCUELA ESPECIAL DE LENGUAJE PAIHUEN-MAPU','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('14910','CENTRO DE ESTUDIOS SAN IGNACIO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14912','COLEGIO SAN ANTONIO DE VILLA ALEMANA','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14913','COLEGIO GALILEO','Valparaíso','QUILLOTA','Part. Subvencionado'),
('14915','ESCUELA DE PARVULOS ALIANZA ARTYLEN','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14916','ESCUELA DE PARVULOS PARAISO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14917','SCIENCE´S COLLEGE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14918','ESC. PARVULOS ANTUKAMEL','Valparaíso','CABILDO','Part. Subvencionado'),
('14922','COLEGIO LAS ACACIAS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14923','COLEGIO WINTERHILL VIÑA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14924','ESC.ESP. DE LENGUAJE ACUARELA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14926','ESCUELA ESPECIAL DE LENGUAJE AÛKEN','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14927','ESCUELA ESPECIAL DE LENGUAJE DEL SOL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14928','ESCUELA ESP.DE LENGUAJE TIERRA MADRE','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('14929','ESCUELA ESPECIAL DE LENGUAJE KUMELEN','Valparaíso','CALERA','Part. Subvencionado'),
('14930','ESCUELA ESPECIAL DE LENGUAJE MANANTIAL','Valparaíso','CALERA','Part. Subvencionado'),
('14931','ESCUELA ESP.DE LENGUAJE VOCES DEL VALLE','Valparaíso','CALLE LARGA','Part. Subvencionado'),
('14932','ESCUELA ESP.DE LENGUAJE CAICURA EPU','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14933','ESC. ESP. DE LENG. CUMBRES DE ACONCAGUA','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14934','ESC. ESPECIAL LENGUAJE MI PEQUEÑO MUNDO','Valparaíso','LLAILLAY','Part. Subvencionado'),
('14935','ESCUELA ESPECIAL DE LENGUAJE CARACOLITO','Valparaíso','CALERA','Part. Subvencionado'),
('14937','ESCUELA ESPECIAL DE LENGUAJE ANTARES','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14938','ESCUELA ESPECIAL DE LENGUAJE AITUE','Valparaíso','CALERA','Part. Subvencionado'),
('14941','ESCUELA ESPECIAL DE LENGUAJE CARIÑOSITOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14944','ESCUELA ESPECIAL DE LENGUAJE TOMASITO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('14945','ESC. ESP. DE LENGUAJE CUMBRES DE ACONCAGUA','Valparaíso','LOS ANDES','Part. Subvencionado'),
('14946','LICEO TEC. PROFESIONAL DE ADULTOS DE LIMACHE','Valparaíso','LIMACHE','Part. Subvencionado'),
('14947','ESC.ESP.DE TRASTORNOS DE LENGUAJE NAHUEL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('14949','ESCUELA ESPECIAL DE LENGUAJE CURIMON','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('14950','JARDIN INFANTIL Y ESC. ESPECIAL DE LENG. SEMILLITA','Valparaíso','CARTAGENA','Part. Subvencionado'),
('14951','ESCUELA DE PARVULOS SERPENTINA','Valparaíso','LA LIGUA','Part. Subvencionado'),
('14952','COLEGIO ALTOMONTE','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('14953','COLEGIO PEUMAYÉN','Valparaíso','CARTAGENA','Part. Subvencionado'),
('14954','ESCUELA ESPECIAL DE LENGUAJE NUBECITAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('14955','ESCUELA ESPECIAL DE LENGUAJE MI RESOL','Valparaíso','QUILLOTA','Part. Subvencionado'),
('15501','COLEGIO PARTICULAR LUCILA GODOY ALCAYAGA','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('15502','INSTITUTO MONSENOR LECAROS','O''Higgins','COLTAUCO','Part. Subvencionado'),
('15503','ESCUELA DUENDE MELODIA','O''Higgins','RANCAGUA','Municipal'),
('15510','COLEGIO QUIMAHUE','O''Higgins','RANCAGUA','Part. Pagado'),
('15515','COLEGIO PARTICULAR SUBV. CHILDREN SCHOOL','O''Higgins','GRANEROS','Part. Subvencionado'),
('15518','JARDIN INFANTIL TOPO GIGIO','O''Higgins','SAN FERNANDO','Part. Pagado'),
('15521','COLEGIO INGLES SAINT JOHN','O''Higgins','RANCAGUA','Part. Pagado'),
('15522','CHARLY SCHOOL','O''Higgins','PICHILEMU','Part. Subvencionado'),
('15524','COLEGIO SANTA CRUZ DE UNCO','O''Higgins','SANTA CRUZ','Part. Pagado'),
('15526','ESCUELA MUNICIPAL AMERICA','O''Higgins','MARCHIHUE','Corp. Municipal'),
('15531','JARDIN INFANTIL MUNDO FELIZ','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15534','COLEGIO SAN IGNACIO','O''Higgins','MACHALÍ','Part. Pagado'),
('15535','ESCUELA SANTA TERESA DE AVILA','O''Higgins','RENGO','Corp. Municipal'),
('15544','COLEGIO CRIPTOCARYA ALBA','O''Higgins','PEUMO','Part. Subvencionado'),
('15546','JARDIN INFANTIL MI GRANJA','O''Higgins','SAN FERNANDO','Part. Pagado'),
('15551','ESCUELA ESPECIAL CRECER','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15554','EL PEQUENO MOZART','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15557','ESCUELA ESPECIAL FRAY AVE MARIA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15561','JARDIN INFANTIL PASCUALITA','O''Higgins','RANCAGUA','Part. Pagado'),
('15564','COLEGIO LA CRUZ','O''Higgins','MACHALÍ','Part. Pagado'),
('15569','ESCUELA PUERTECILLO','O''Higgins','NAVIDAD','Corp. Municipal'),
('15570','ESCUELA BASICA GALVARINO VALENZUELA MORAGA','O''Higgins','LOLOL','Corp. Municipal'),
('15571','COLEGIO PARTICULAR LA PRIMAVERA','O''Higgins','QUINTA DE TILCOCO','Part. Subvencionado'),
('15574','LICEO MUNICIPAL DE ADULTOS SANTA CRUZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('15576','COLEGIO ARRAYANES','O''Higgins','SAN FERNANDO','Part. Pagado'),
('15579','COLEGIO PARTICULAR ALMA MATER','O''Higgins','RENGO','Part. Subvencionado'),
('15582','COLEGIO SAN MIGUEL ARCANGEL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15583','LICEO TECNICO PROFESIONAL EL TAMBO','O''Higgins','SAN VICENTE','Municipal'),
('15585','COLEGIO CRISTIANO RESURRECCION','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15586','COLEGIO TIA MONICA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15588','ROSARIO COLLEGE','O''Higgins','RENGO','Part. Subvencionado'),
('15589','COLEGIO ALCALDE PEDRO URBINA','O''Higgins','PEUMO','Part. Subvencionado'),
('15593','COLEGIO AMERICANO','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15594','COLEG.TERESIANO JUANITA FERNANDEZ SOLAR','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('15595','JARDIN INFANTIL ARDILLITA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15596','INSTITUTO SAN VICENTE DE TAGUA TAGUA','O''Higgins','SAN VICENTE','Municipal'),
('15597','COLEGIO PROVIDENCIA JARDIN INFANTIL','O''Higgins','RANCAGUA','Part. Pagado'),
('15598','JARDIN INFANTIL COLORIN COLORADO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15600','ALBERTO HURTADO CRUCHAGA','O''Higgins','DOÑIHUE','Part. Subvencionado'),
('15601','COLEGIO ANTILEN','O''Higgins','RENGO','Part. Subvencionado'),
('15605','COLEGIO HUMANISTA INTEGRADO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15607','CENTRO TRAST. Y TRAT. LENG. CHOIN RAYEN','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15608','ESCUELA PEDRO MORALES BARRERA','O''Higgins','SAN FERNANDO','Servicio Local'),
('15609','JARDIN INFANTIL EL TRIGAL','O''Higgins','RENGO','Part. Pagado'),
('15610','COLEGIO PARTIC, SAN JOSE DE LA MONTANA','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15614','ESCUELA EL NARANJAL','O''Higgins','RENGO','Corp. Municipal'),
('15621','COLEGIO PARTICULAR EL REAL','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15622','COLEGIO PARTICULAR LOMAS BLANCAS','O''Higgins','NANCAGUA','Part. Subvencionado'),
('15624','COLEGIO MISTRAL','O''Higgins','LAS CABRAS','Part. Subvencionado'),
('15627','COLEGIO SAN FRANCISCO','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15628','JARDIN INFANTIL SAN FRANCISCO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15629','ESCUELA ESPECIAL DE LENGUAJE RAICES DE RANCAGUA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15631','TRINITY COLLEGE','O''Higgins','MACHALÍ','Part. Pagado'),
('15632','COLEGIO SAN ANGELO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15633','BRITISH COLLEGE L.T.D.','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15641','CENTRO EDUCATIVO INTEGRAL LAS ENCINAS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15643','INSTITUTO CRISTIANO EDUMASTER COLLEGE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15644','COLEGIO AUDICION Y LENG. SAN GASPAR','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15646','INSTITUTO SANTA TERESA DE LOS ANDES','O''Higgins','GRANEROS','Part. Subvencionado'),
('15650','COLEGIO NAZARETH','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15653','CENTTRO TRAST.LENGUAJE NUESTRA ESPERAN','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('15656','CENTRO TRAST.LENGUAJE LOS BRUJITOS','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15657','COLEGIO NEHUEN','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15660','CENTRO REHAB. DEL LENGUAJE ORAL CERLO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15661','COLEGIO DIVINA ESPERANZA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15662','INSTITUTO SAN LORENZO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15663','ESCUELA DEL LENGUAJE SANTA MARIA','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('15664','COLEGIO MANQUEMAVIDA','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('15665','LICEO INTEGRADO DE ADULTOS','O''Higgins','GRANEROS','Corp. Municipal'),
('15669','JARDIN INFANTIL DIVINA PROVIDENCIA DE JESUS','O''Higgins','SAN FERNANDO','Part. Pagado'),
('15672','C.DE TRANS.DE LA COMUNIC. STA.TERESA DE JESUS','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15673','ESC. ESP. EL ROBLE, CENTRO DE ATENCION A NECES. EDUC. ESP.','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15676','COLEGIO HISPANO CHILENO EL PILAR','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15677','JARDIN INFANTIL GIRASOLES INTERACTIVOS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15679','JARDIN INFANTIL AVENTURAS MAGICAS','O''Higgins','GRANEROS','Part. Pagado'),
('15681','CENTRO EDUCATIVO INTEGRAL MARIA MAGDALENA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15682','COLEGIO MAGISTER','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15683','COLEGIO EVELYN S SCHOOL','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('15684','INSTITUTO HANS CHRISTIAN ANDERSEN','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15687','ESCUELA MUNICIPAL DE LENGUAJE SANTA CRUZ','O''Higgins','SANTA CRUZ','Corp. Municipal'),
('15690','COLEGIO LOS CIPRESES','O''Higgins','DOÑIHUE','Part. Subvencionado'),
('15691','ECUELA DE LENGUAJE LOS PALTOS','O''Higgins','PEUMO','Part. Subvencionado'),
('15694','JARDIN INFANTIL GENTE CHICA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15695','JARDIN INFANTIL MELODY','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15696','JARDIN INFANTIL TIA MONICA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15698','ESCUELA DE LENGUAJE SAN IGNACIO','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15700','COLEGIO LA REPUBLICA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15705','COLEGIO SANTA TERESA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15707','COLEGIO RANCAGUA','O''Higgins','RANCAGUA','Part. Pagado'),
('15708','ESCUELA ESPECIAL DE NERQUIHUE','O''Higgins','LOLOL','Corp. Municipal'),
('15712','CENTRO TRAST. DEL LENGUAJE ORAL ALBORADA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15713','COLEGIO DE LENGUAJE RAILEF','O''Higgins','PICHILEMU','Part. Subvencionado'),
('15714','ESCUELA DE TRASTORNOS DE LA COMUNICACION LA CRUZ','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15715','ESCUELA DE LENGUAJE CHARLES DARWIN','O''Higgins','CHÉPICA','Part. Subvencionado'),
('15716','ESCUELA ESPECIAL DE LENGUAJE RUCALHUE','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15717','ESCUELA ESPECIAL DE LENGUAJE ALCALA','O''Higgins','NANCAGUA','Part. Subvencionado'),
('15719','COLEGIO FRAY ANDRES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15720','LICEO MUNICIPAL ZOILA ROSA CARRENO','O''Higgins','MALLOA','Corp. Municipal'),
('15722','LICEO PARTICULAR CARDENAL RAUL SILVA HENRIQUE','O''Higgins','NANCAGUA','Part. Subvencionado'),
('15723','CENTRO EDUCACIONAL INTEGRAL DE ADULTOS LOS ROBLES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15724','ESCUELA FERNANDA AEDO FAUNDEZ','O''Higgins','RENGO','Corp. Municipal'),
('15726','COLEGIO SAN SEBASTIAN SCHOOL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15728','COLEGIO MUNICIPAL HUALLILEN','O''Higgins','COINCO','Corp. Municipal'),
('15729','ESCUELA DE LENGUAJE MANANTIAL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15731','COLEGIO ESPANA','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15732','COLEGIO CRISTIANO ADONAY','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15734','ESCUELA ESPECIAL DE LENGUAJE SAN BENITO','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15736','ESCUELA TRAST. DE LA COMUNIC. SANTA ROSA DE PELEQUEN','O''Higgins','MALLOA','Part. Subvencionado'),
('15738','ESCUELA TRAST. DE LA COMUNIC. NUESTRA SRA. DEL PILAR','O''Higgins','RENGO','Part. Subvencionado'),
('15739','COLEGIO CHIMBARONGO','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15740','ESCUELA DE LENGUAJE SAN ANDRES','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15741','ESCUELA DE LENGUAJE SANTA MARIA DE LA COMUNA','O''Higgins','PLACILLA','Part. Subvencionado'),
('15742','ESCUELA DE ESTIMUL. DE LENGUAJE CHARLES DARWIN','O''Higgins','REQUÍNOA','Part. Subvencionado'),
('15744','COLEGIO ALMENAR','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15745','COLEGIO VALLE DE COLCHAGUA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15746','SAINT MORITZ COLLEGE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15747','COLEGIO DE EDUCACION ESPECIAL MOSTAZAL','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('15748','ESCUELA ESPECIAL MARIA ALICIA PONCE','O''Higgins','MOSTAZAL','Corp. Municipal'),
('15750','COLEGIO LAS AMERICAS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15751','ESCUELA DE LENGUAJE CHARLES DARWIN','O''Higgins','OLIVAR','Part. Subvencionado'),
('15753','COLEGIO BENJAMIN VICUÑA MACKENNA','O''Higgins','RANCAGUA','Municipal'),
('15754','CENTRO DE RECURSOS EDUCATIVO INTEGRARTE','O''Higgins','CHÉPICA','Corp. Municipal'),
('15755','COLEGIO SAN NICOLAS','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15756','CENTRO EDUC. INT. DE ADULTOS SEMPER','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15757','COLEGIO PART. SUBV. SAN ESTEBAN','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15758','COLEGIO CHRISTIAN COLLEGE','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15759','LICEO MACHALI','O''Higgins','MACHALÍ','Corp. Municipal'),
('15760','ESC. ESP. DE LENGUAJE JUNTITOS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15761','ESCUELA ESPECIAL MADRE MARIA MAZZARELLO','O''Higgins','QUINTA DE TILCOCO','Part. Subvencionado'),
('15762','COLEGIO MARÍA ESCOBILLANA GUZMÁN','O''Higgins','GRANEROS','Corp. Municipal'),
('15763','COLEGIO ANTUHUE','O''Higgins','GRANEROS','Corp. Municipal'),
('15764','ELENA GAETE DARBEAUX','O''Higgins','PICHIDEGUA','Part. Subvencionado'),
('15765','CHARLES DARWIN','O''Higgins','LAS CABRAS','Part. Subvencionado'),
('15767','COLEGIO DIEGO PORTALES','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15768','COLEGIO SANTA FILOMENA','O''Higgins','RANCAGUA','Municipal'),
('15769','LICEO TÉCNICO SANTA CRUZ DE TRIANA','O''Higgins','RANCAGUA','Municipal'),
('15770','ESCUELA DIVINO MAESTRO','O''Higgins','PICHILEMU','Corp. Municipal'),
('15774','ESCUELA AGRICOLA DON GREGORIO','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15775','LICEO TECNICO PROFESIONAL SANTA ROSA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15776','COLEGIO AVE FENIX','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15777','COLEGIO JUAN LUIS VIVES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15778','CENTRO EDUC. ACUARELA TE ACOGE','O''Higgins','NANCAGUA','Part. Subvencionado'),
('15779','COLEGIO HERMANO DE ASIS','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15780','ESCUELA ESPECIAL DE PICHIDEGUA','O''Higgins','PICHIDEGUA','Corp. Municipal'),
('15781','LICEO MUNICIPAL DE CODEGUA','O''Higgins','CODEGUA','Corp. Municipal'),
('15782','CENTRO EDUCATIVO ESPECIAL CREEMOS','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15784','ESCUELA ESPECIAL DE LENGUAJE CODEGUA','O''Higgins','CODEGUA','Part. Subvencionado'),
('15785','ESCUELA ESPECIAL DE LENGUAJE NUESTRA SRA. DEL ROSARIO','O''Higgins','RENGO','Part. Subvencionado'),
('15786','JARDIN INFANTIL MIS TESORITOS PUFFI','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15787','COMPLEJO EDUCACIONAL LAS ARAUCARIAS','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15788','ESCUELA ESP. DE LENG. GIORDANO BRUNO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15789','ESCUELA ESPECIAL DE LENGUAJE RAICES','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15790','ESCUELA ESPECIAL AYUDANDO A CRECER','O''Higgins','CHIMBARONGO','Servicio Local'),
('15791','ESCUELA ESPECIAL DIFERENCIAL SAN ANDRES','O''Higgins','PICHILEMU','Part. Subvencionado'),
('15792','COLEGIO REAL DE CAREN','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15793','COLEGIO INTERAMERICANO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15795','JARDIN INFANTIL PEQUITAS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15796','ESC. ESP.DE LENGUAJE SAN FRANCISCO DE ASIS','O''Higgins','GRANEROS','Part. Subvencionado'),
('15798','ESCUELA ESPECIAL DE LENGUAJE SAN FRANCISCO DE','O''Higgins','MALLOA','Part. Subvencionado'),
('15799','COLEGIO DE LENGUAJE PADRE PIO','O''Higgins','SANTA CRUZ','Part. Subvencionado'),
('15800','ESC. ESP. DE LENGUAJE EL SEMBRADOR','O''Higgins','DOÑIHUE','Part. Subvencionado'),
('15801','JARDIN INFANTIL INMACULADA CONCEPCION','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15803','JARDIN INFANTIL TABANCURA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15804','ESCUELA ESPECIAL SAN VALENTIN','O''Higgins','GRANEROS','Part. Subvencionado'),
('15805','ESCUELA ESPECIAL NUEVO AMANECER','O''Higgins','GRANEROS','Part. Subvencionado'),
('15806','JARDIN INFANTIL SEMILLITA CANELO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15807','COLEGIO ALERCE','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15808','LICEO MIRELLA CATALAN URZUA','O''Higgins','PAREDONES','Corp. Municipal'),
('15809','OLIVAR COLLEGE','O''Higgins','OLIVAR','Part. Subvencionado'),
('15811','COLEGIO ANGOSTURA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15812','COLEGIO BASICO VIOLETA PARRA SANDOVAL','O''Higgins','PERALILLO','Corp. Municipal'),
('15814','JARDIN INFANTIL MI CASITA EN EL BOSQUE','O''Higgins','RANCAGUA','Part. Pagado'),
('15815','ESCUELA DE LENGUAJE RAYITO DE SOL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15817','COLEGIO NAHUELCURA','O''Higgins','MACHALÍ','Part. Subvencionado'),
('15818','ESCUELA ESPECIAL DE LENGUAJE ALTAZOR','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15819','COLEGIO DE LENGUAJE PADRE PIO PERALILLO','O''Higgins','PERALILLO','Part. Subvencionado'),
('15820','COLEGIO ALEMAN SAN MIGUEL','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15821','ESCUELA DE LENGUAJE PUCARA','O''Higgins','LAS CABRAS','Part. Subvencionado'),
('15822','ESCUELA DE LENGUAJE EL ARCA DE CRISTOBAL','O''Higgins','RENGO','Part. Subvencionado'),
('15823','ESCUELA DE LENGUAJE HAKUNA MATATA','O''Higgins','PERALILLO','Part. Subvencionado'),
('15824','ESC ESP. DE LENGUAJE NUESTRA SRA DE LOURDES','O''Higgins','DOÑIHUE','Part. Subvencionado'),
('15825','ESCUELA DE LENGUAJE SAN JOSE E.I.R.L.','O''Higgins','NANCAGUA','Part. Subvencionado'),
('15826','ESCUELA ESPECIAL DE LENGUAJE SAN EXPEDITO','O''Higgins','COLTAUCO','Part. Subvencionado'),
('15827','ESCUELA ESPECIAL DE LENGUAJE LOS ALERCES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15828','COLEGIO SAN NICOLAS DE BARI','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15829','ESCUELA ESPECIAL DE LENGUAJE ABRAPALABRA','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15830','COLEGIO DE ADULTOS MOSTAZAL','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('15831','ESCUELA ESPECIAL HIRAM','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15832','COLEGIO BOSQUES DE CHILE','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15834','ESCUELA ESP.DE LENGUAJE ENCANTADOS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15835','ESC.ESP.DE LENGUAJE EL TREN DE CRISTOBAL','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15836','ESCUELA ESP.DE LENGUAJE COMUNICARTE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15838','ESCUELA ESP. DE LENGUAJE TREMUN','O''Higgins','PICHIDEGUA','Part. Subvencionado'),
('15839','ESC. ESP. DE LENGUAJE SEMILLITA DE LA PUNTA','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('15840','COLEGIO TECNOLÓGICO PULMAHUE','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15841','ESC.ESP. DE LENGUAJE AYELEN','O''Higgins','RENGO','Part. Subvencionado'),
('15842','JARDIN INFANTIL SEMILLITA DE SABIDURIA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15843','LICEO INDUSTRIAL ESTEBAN LEYTON SOTO','O''Higgins','RENGO','Corp. Municipal'),
('15844','JARDIN INFANTIL PEQUEÑOS GIGANTES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15845','ESCUELA ESPECIAL DE LENGUAJE SAN JOSE','O''Higgins','LOLOL','Part. Subvencionado'),
('15846','ESCUELA ESPECIAL DE LENGUAJE REMOLINOS','O''Higgins','MARCHIHUE','Part. Subvencionado'),
('15848','INSTITUTO FERMIN VIVACETA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('15851','ESCUELA ESPECIAL DE LENGUAJE SAN GABRIEL','O''Higgins','SAN VICENTE','Part. Subvencionado'),
('15852','ESCUELA ESPECIAL ANGELES','O''Higgins','COLTAUCO','Part. Subvencionado'),
('15853','ESCUELA ESPECIAL DE LENGUAJE CARRUSEL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15854','INSTITUTO DE EDUCACION DE ADULTO SAN ANDRES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('15855','COLEGIO SEBASTIAN`S COLLEGE','O''Higgins','GRANEROS','Part. Subvencionado'),
('15856','ESCUELA ESPECIAL DE LENGUAJE NEWEN','O''Higgins','PAREDONES','Part. Subvencionado'),
('15857','COLEGIO UMBRALES','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('15858','ESCUELA ESPECIAL SAN EXPEDITO DE RENGO','O''Higgins','RENGO','Part. Subvencionado'),
('15859','COLEGIO PARTICULAR SUBVENCIONADO NANCAGUA SCHOOL','O''Higgins','NANCAGUA','Part. Subvencionado'),
('16406','ESC. DIFERENCIAL GUSTAVO RAMIREZ MORENO','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('16410','COLEGIO ABATE MOLINA','Maule','LONGAVÍ','Part. Subvencionado'),
('16415','COLEGIO RAUQUEN','Maule','CURICÓ','Part. Subvencionado'),
('16417','COLEGIO BICENTENARIO POLITECNICO SAN JOSE DE CURICO','Maule','CURICÓ','Part. Subvencionado'),
('16424','LICEO BICENTENARIO DE MOLINA MARIA DEL TRÁNSITO DE LA CRUZ','Maule','MOLINA','Corp. Municipal'),
('16427','COLEGIO ESMERALDA','Maule','TALCA','Part. Subvencionado'),
('16428','ESC. MONSENOR MANUEL LARRAIN ERRAZURIZ','Maule','HUALAÑÉ','Corp. Municipal'),
('16429','ESCUELA DIFERENCIAL LAS ILUSIONES','Maule','CURICÓ','Part. Subvencionado'),
('16431','COLEGIO  ORCHARD COLLEGE','Maule','CURICÓ','Part. Pagado'),
('16432','LICEO AGRIC.PADRE ALBERTO HURTADO','Maule','MOLINA','Part. Subvencionado'),
('16434','CENTRO EDUCACIONAL LUIS RUTTEN','Maule','TALCA','Part. Subvencionado'),
('16441','LICEO BICENTENARIO DE EXCELENCIA SANTA MARTA','Maule','TALCA','Part. Subvencionado'),
('16443','CENTRO INTEGRAL EDUCACION TALCA','Maule','TALCA','Part. Subvencionado'),
('16444','COLEGIO EDUARDO MARTIN ABEJON','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('16446','COLEGIO JUAN PIAMARTA','Maule','TALCA','Part. Subvencionado'),
('16448','INSTITUTO SANTA MARTA','Maule','CURICÓ','Part. Subvencionado'),
('16449','COLEGIO SANTA FE','Maule','CURICÓ','Part. Pagado'),
('16452','LICEO POLITECNICO DE CURICO','Maule','CURICÓ','Corp. Municipal'),
('16453','COLEGIO ALBORADA','Maule','LINARES','Part. Pagado'),
('16454','ESCUELA LAS DUNAS DE CHANCO','Maule','CHANCO','Servicio Local'),
('16455','ESCUELA DE PARVULOS SEMILLITA','Maule','LONGAVÍ','Corp. Municipal'),
('16456','INSTITUTO CUMBRES DE MAULE','Maule','PARRAL','Part. Subvencionado'),
('16457','CENTRO EDUCACIONAL APUMANQUE','Maule','CURICÓ','Part. Subvencionado'),
('16458','COL.CORPORACION EDUC.LA ARAUCANA','Maule','CURICÓ','Part. Pagado'),
('16459','INSTITUTO TECNICO SUPERIOR CONSTITUCION','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('16460','ESCUELA PADRE ALBERTO HURTADO','Maule','CURICÓ','Corp. Municipal'),
('16461','COLEGIO LYON´S SCHOOL','Maule','TALCA','Part. Subvencionado'),
('16462','LICEO MONSEÑOR CARLOS GONZÁLEZ CRUCHAGA','Maule','TALCA','Part. Subvencionado'),
('16467','LICEO PABLO NERUDA DE TALCA','Maule','TALCA','Part. Subvencionado'),
('16468','ESCUELA NESTOR DEL CAMPO ARZOLA','Maule','COLBÚN','Corp. Municipal'),
('16469','COLEGIO PABLO NERUDA','Maule','PARRAL','Corp. Municipal'),
('16470','COLEGIO CONCEPCION TALCA','Maule','TALCA','Part. Pagado'),
('16472','ESC.ESPECIAL TRASTORNOS DE LA COMUNICACI','Maule','LINARES','Part. Subvencionado'),
('16476','COLEGIO BOSQUES DE GAIA','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('16477','COLEGIO AQUELARRE','Maule','TENO','Part. Subvencionado'),
('16479','ESCUELA TALLER LABORAL UNPADE','Maule','TALCA','Part. Subvencionado'),
('16484','COLEGIO MANSO DE VELASCO','Maule','CAUQUENES','Part. Subvencionado'),
('16485','COLEGIO GARDEN COLLEGE','Maule','CAUQUENES','Part. Subvencionado'),
('16488','COLEGIO ADVENTISTA MARANATA','Maule','TALCA','Part. Subvencionado'),
('16489','COLEGIO BALTAZAR','Maule','TALCA','Part. Subvencionado'),
('16490','CENTRO DE LENGUAJE MARCELA PAZ','Maule','TALCA','Part. Subvencionado'),
('16491','COLEGIO ALBERT EINSTEIN','Maule','CURICÓ','Part. Subvencionado'),
('16492','INSTITUTO VALENTIN LETELIER','Maule','LINARES','Part. Subvencionado'),
('16494','COLEGIO CRISTIANO DE CURICO','Maule','CURICÓ','Part. Subvencionado'),
('16497','COLEGIO ANDES DE TALCA','Maule','TALCA','Part. Pagado'),
('16501','JARDIN INFANTIL CAMPANITA','Maule','TALCA','Part. Pagado'),
('16502','COLEGIO CORDILLERA','Maule','MOLINA','Part. Subvencionado'),
('16504','CENTRO EDUCACIONAL BUBI','Maule','TENO','Part. Subvencionado'),
('16506','ESCUELA CHACARILLAS','Maule','CONSTITUCIÓN','Servicio Local'),
('16507','JUAN SALVADOR COLLEGE','Maule','SAN JAVIER','Part. Subvencionado'),
('16508','COLEGIO HISPANOCHILENO EL PILAR','Maule','CURICÓ','Part. Subvencionado'),
('16509','COLEGIO CENTRO EDUCACIONAL VYGOTSKY','Maule','CURICÓ','Part. Subvencionado'),
('16510','ESCUELA ENRIQUE WEISS','Maule','LINARES','Part. Subvencionado'),
('16512','COLEGIO DIEGO THOMPSON','Maule','CURICÓ','Part. Subvencionado'),
('16513','CENTRO EDUCACIONAL ADONAY','Maule','CURICÓ','Part. Subvencionado'),
('16518','COLEGIO PARTICULAR SEBASTIAN','Maule','LINARES','Part. Subvencionado'),
('16520','COLEGIO KAIROS','Maule','CURICÓ','Part. Subvencionado'),
('16521','ESC.ESPECIAL DE TRASTORNO DE LA COMUNICACION','Maule','TALCA','Part. Subvencionado'),
('16523','ESC.TRASTORNOS DE LENGUAJE HANS CHRISTIAN AND','Maule','CURICÓ','Part. Subvencionado'),
('16526','COLEGIO LOS ALERCES','Maule','TALCA','Part. Subvencionado'),
('16530','ESC.ESPECIAL TRASTORNOS DE LA COMUNIC. MIS SO','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('16533','CENTRO DE LENGUAJE Y PSICOPEDAGOGIA DALUZ','Maule','TALCA','Part. Subvencionado'),
('16535','COLEGIO SAN MARCOS','Maule','CURICÓ','Part. Subvencionado'),
('16536','JARDIN INFANTIL MIS PRIMEROS PASOS','Maule','MOLINA','Part. Subvencionado'),
('16537','ESCUELA DE LENGUAJE CEL','Maule','CURICÓ','Part. Subvencionado'),
('16541','CENTRO EDUCATIVO PEUMAYEN','Maule','CURICÓ','Part. Subvencionado'),
('16542','ESCUELA DE LENGUAJE MAZAPAN','Maule','CURICÓ','Part. Subvencionado'),
('16543','ESCUELA PARVULOS ALDEA DE LOS NINOS','Maule','TALCA','Part. Subvencionado'),
('16544','ESCUELA DE LENGUAJE PAUL HARRIS','Maule','TENO','Part. Subvencionado'),
('16548','MI JARDIN Y YO','Maule','TALCA','Part. Subvencionado'),
('16549','COLEGIO PALENCIA SC.','Maule','CURICÓ','Part. Subvencionado'),
('16550','COLEGIO SAN JORGE','Maule','TALCA','Part. Pagado'),
('16551','LICEO BICENTENARIO POLIVALENTE DE RAUCO','Maule','RAUCO','Corp. Municipal'),
('16552','ESCUELA LENGUAJE BELEN','Maule','TALCA','Part. Subvencionado'),
('16553','ESCUELA DE LENGUAJE MANANTIAL','Maule','TALCA','Part. Subvencionado'),
('16554','ESCUELA DE LENGUAJE CEL','Maule','MOLINA','Part. Subvencionado'),
('16556','COLEGIO CORDILLERA','Maule','LINARES','Part. Subvencionado'),
('16557','CENTRO DE LENGUAJE CAUQUENES','Maule','CAUQUENES','Part. Subvencionado'),
('16558','CENTRO EDUCACIONAL TERRANOVA','Maule','TALCA','Part. Subvencionado'),
('16560','CENTRO DE LENGUAJE SAN JAVIER','Maule','SAN JAVIER','Part. Subvencionado'),
('16561','CENTRO LENGUAJE EL CANELO','Maule','LINARES','Part. Subvencionado'),
('16563','ESCUELA DE LENGUAJE CEDEL','Maule','PARRAL','Part. Subvencionado'),
('16564','LICEO BICENTENARIO TP SIMON BOLIVAR','Maule','CURICÓ','Part. Subvencionado'),
('16565','ESCUELA DE LENGUAJE PRINCIPITO','Maule','MOLINA','Part. Subvencionado'),
('16566','COLEGIO ESPECIAL DE MARIA','Maule','CURICÓ','Part. Subvencionado'),
('16568','ESCUELA DE LENGUAJE SAN NICOLAS','Maule','LINARES','Part. Subvencionado'),
('16569','COLEGIO LOS HEROES','Maule','CURICÓ','Part. Subvencionado'),
('16570','ESCUELA DE LENGUAJE RAYENCO','Maule','ROMERAL','Part. Subvencionado'),
('16572','ESCUELA ESPECIAL HIERBAS BUENAS','Maule','LINARES','Part. Subvencionado'),
('16574','EMA ESCAJADIO GARCIA','Maule','TALCA','Part. Subvencionado'),
('16575','CENTRO DE LENGUAJE CEDEL','Maule','TALCA','Part. Subvencionado'),
('16577','ESCUELA DE LENGUAJE LAS NIEVES','Maule','VILLA ALEGRE','Part. Subvencionado'),
('16580','ESC. PASO INTERNACIONAL PEHUENCHE','Maule','SAN CLEMENTE','Corp. Municipal'),
('16582','TECNOLOGICO NUEVO HORIZONTE','Maule','CURICÓ','Part. Subvencionado'),
('16583','ESCUELA DE ADMINISTRACION Y COMERCIO','Maule','CURICÓ','Part. Subvencionado'),
('16584','ESCUELA DE LENGUAJE GIRASOL','Maule','HUALAÑÉ','Part. Subvencionado'),
('16585','CENTRO EDUCACIONAL IRIS','Maule','TALCA','Part. Subvencionado'),
('16586','ESCUELA DE LENGUAJE RAYITO DE SOL','Maule','RAUCO','Part. Subvencionado'),
('16587','LICEO POLIVALENTE SAGRADA FAMILIA','Maule','SAGRADA FAMILIA','Corp. Municipal'),
('16588','COLEGIO SAN ALFONSO DE EL BOLDO','Maule','CURICÓ','Part. Subvencionado'),
('16589','COLEGIO EL QUILLAY','Maule','CURICÓ','Part. Subvencionado'),
('16590','ESC.ESP.DE TRAST.DEL LENGUAJE SAN VALENTIN','Maule','TALCA','Part. Subvencionado'),
('16591','ESCUELA DE LENGUAJE ARRAYAN','Maule','TALCA','Part. Subvencionado'),
('16592','ESCUELA LENGUAJE SAN CLEMENTE','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16594','COLEGIO EL SEMBRADOR','Maule','CURICÓ','Part. Subvencionado'),
('16595','ESCUELA DE LENGUAJE ANTUPIREN','Maule','LONGAVÍ','Part. Subvencionado'),
('16597','ESCUELA DE LENGUAJE ZARCILLO','Maule','TALCA','Part. Subvencionado'),
('16598','ESCUELA DE LENGUAJE VERBUM','Maule','CURICÓ','Part. Subvencionado'),
('16599','ESCUELA LENGUAJE PROSPERIDAD','Maule','TALCA','Part. Subvencionado'),
('16600','COLEGIO ALTA CUMBRE','Maule','CURICÓ','Part. Subvencionado'),
('16601','ESCUELA ESPECIAL DE LENGUAJE ALTAMIRA','Maule','LINARES','Part. Subvencionado'),
('16602','CENTRO LENGUAJE DALUZ 2','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16603','ESC. LENGUAJE ARCOIRIS','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16604','INSTITUTO LATINOAMERICANO-EUROPEO DE','Maule','TALCA','Part. Subvencionado'),
('16606','ESCUELA DE PARVULOS SAN AGUSTIN','Maule','TALCA','Part. Subvencionado'),
('16607','ESCUELA DE LENGUAJE ALBORADA','Maule','CURICÓ','Part. Subvencionado'),
('16608','COLEGIO ANTILHUE','Maule','MOLINA','Part. Subvencionado'),
('16610','ESCUELA DE LENGUAJE EDUCAR','Maule','SAGRADA FAMILIA','Part. Subvencionado'),
('16613','ESCUELA DE LENGUAJE BELEN','Maule','PARRAL','Part. Subvencionado'),
('16615','ESC.DE LENGUAJE Y JARDIN INFANTIL ECOLOGICO','Maule','CONSTITUCIÓN','Part. Subvencionado'),
('16616','ESCUELA DE TRANSTORNOS DE LENGUAJE EMMANUEL','Maule','CURICÓ','Part. Subvencionado'),
('16617','SALA CUNA Y JARDIN INFANTIL MICKEY MOUSE','Maule','SAN CLEMENTE','Part. Subvencionado'),
('16619','ESCUELA DE LENGUAJE BAMBI','Maule','CUREPTO','Part. Subvencionado'),
('16621','JARDIN INFANTIL TIRAMISU','Maule','TALCA','Part. Pagado'),
('16622','ESCUELA DE LENGUAJE GARDEN SCHOOL','Maule','TALCA','Part. Subvencionado'),
('16623','ESCUELA DE LENGUAJE RAIGUEN','Maule','TALCA','Part. Subvencionado'),
('16624','COLEGIO ANTARES','Maule','PELARCO','Part. Subvencionado'),
('16625','COLEGIO PABLO DE ROKHA','Maule','SAN JAVIER','Part. Subvencionado'),
('16627','COLEGIO SAN IGNACIO DE TALCA','Maule','TALCA','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
