-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 14 de 31 | filas 5201-5600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('8718','ESCUELA PARTICULAR DANES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('8720','ESCUELA PARTICULAR ESPECIAL ALOA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('8721','ESCUELA PARTICULAR ESPECIAL CEDIN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8724','COLEGIO SAINT JOSEPH C. THOMAS SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('8725','ESCUELA PARTICULAR ESPECIAL STA.JULIANA','Metropolitana','RECOLETA','Part. Subvencionado'),
('8726','ESCUELA PARTICULAR THOMAS JEFFERSON','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8728','COLEGIO GEORGE WASHINGTON','Metropolitana','INDEPENDENCIA','Part. Subvencionado'),
('8739','ESCUELA PARTICULAR DIVINA MARIA','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8740','COLEGIO MARIA LUISA VILLALON','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8748','COLEGIO INSTITUTO ALONSO DE ERCILLA','Metropolitana','SANTIAGO','Part. Pagado'),
('8750','COLEGIO ACADEMIA DE HUMANIDADES','Metropolitana','RECOLETA','Part. Pagado'),
('8754','COLEGIO HISPANO AMERICANO','Metropolitana','SANTIAGO','Part. Pagado'),
('8755','COLEGIO SAINT ROSE SCHOOL','Metropolitana','SANTIAGO','Part. Pagado'),
('8756','COLEGIO EXCELSIOR','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8757','COLEGIO DE LOS SAGRADOS CORAZONES ALAMEDA','Metropolitana','SANTIAGO','Part. Pagado'),
('8759','COLEGIO SANTA CECILIA','Metropolitana','SANTIAGO','Part. Pagado'),
('8761','COLEGIO INSTITUTO DE HUMANIDADES LUIS CAMPINO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8762','COLEGIO SANTA ELENA CARMELITAS MISIONERAS TERESIANA','Metropolitana','SANTIAGO','Part. Pagado'),
('8769','COLEGIO SANTA MARIA CERVELLON','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('8780','ESCUELA MANUEL MONTT','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8791','COLEGIO FILIPENSE','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8793','ESCUELA BASICA N°823 SPENDIX','Metropolitana','ÑUÑOA','Part. Pagado'),
('8800','ESCUELA PART MARY AND GEORGE S SCHOOL','Metropolitana','RECOLETA','Part. Subvencionado'),
('8809','ESCUELA DE PARVULOS N°1146 HEYDDIE','Metropolitana','SANTIAGO','Part. Pagado'),
('8811','LICEO PROFESIONAL ABDON CIFUENTES','Metropolitana','SANTIAGO','Part. Subvencionado'),
('8812','LICEO INDUSTRIAL DE LA CONSTRUCCION VICTOR BEZANILLA SALINAS','Metropolitana','SANTIAGO','Adm. Delegada'),
('8813','LICEO BICENTENARIO TÉCNICO PROFESIONAL IGNACIO DOMEYKO','Metropolitana','RECOLETA','Adm. Delegada'),
('8814','LICEO INDUSTRIAL A-22 DE SANTIAGO','Metropolitana','SANTIAGO','Adm. Delegada'),
('8815','COLEGIO SAN FRANCISCO DEL ALBA','Metropolitana','LAS CONDES','Municipal'),
('8818','LICEO ALEXANDER FLEMING DE LAS CONDES','Metropolitana','LAS CONDES','Part. Subvencionado'),
('8819','LICEO RAFAEL SOTOMAYOR','Metropolitana','LAS CONDES','Part. Subvencionado'),
('8821','LICEO MUNICIPALIZADO AMANDA LABARCA','Metropolitana','VITACURA','Corp. Municipal'),
('8822','LICEO JUAN PABLO II DE LAS CONDES','Metropolitana','LAS CONDES','Municipal'),
('8825','COLEGIO ANTARTICA CHILENA','Metropolitana','VITACURA','Corp. Municipal'),
('8827','COLEGIO NTRA. SRA. DEL ROSARIO LAS CONDES','Metropolitana','LAS CONDES','Part. Subvencionado'),
('8828','LICEO BICENTENARIO SIMON BOLIVAR','Metropolitana','LAS CONDES','Municipal'),
('8832','ESC. DE EDUC. DIFERENCIAL PAUL HARRIS','Metropolitana','LAS CONDES','Municipal'),
('8833','LICEO BICENTENARIO DE EXCELENCIA MARIA LUISA BOMBAL','Metropolitana','VITACURA','Part. Subvencionado'),
('8835','LICEO BICENTENARIO SANTA MARIA DE LAS CONDES','Metropolitana','LAS CONDES','Municipal'),
('8837','ESCUELA DIFERENCIAL F N°254 MADRE TIERRA LO BARNECHEA','Metropolitana','LO BARNECHEA','Corp. Municipal'),
('8839','INSTITUTO FERMIN VIVACETA','Metropolitana','LO BARNECHEA','Corp. Municipal'),
('8840','ESCUELA DE FARELLONES','Metropolitana','LO BARNECHEA','Corp. Municipal'),
('8841','COLEGIO PARROQUIAL SANTA ROSA DE LO BARNECHEA','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('8845','COLEGIO SAN JUAN DE KRONSTADT','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('8846','COLEGIO INMACULADA CONCEPCION','Metropolitana','VITACURA','Part. Pagado'),
('8849','COLEGIO LA VIRGEN DE POMPEYA','Metropolitana','LAS CONDES','Part. Subvencionado'),
('8854','INSTITUTO PRESIDENTE ERRAZURIZ','Metropolitana','LAS CONDES','Part. Subvencionado'),
('8860','COLEGIO ANGLO AMERICAN INTERNATIONAL SCHOOL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8861','COLEGIO JOHN ANDREWS ADVENTIST ACADEMY','Metropolitana','LA REINA','Part. Pagado'),
('8862','COLEGIO TABANCURA','Metropolitana','VITACURA','Part. Pagado'),
('8863','COLEGIO SCUOLA ITALIANA VITTORIO MONTIGLIO','Metropolitana','LAS CONDES','Part. Pagado'),
('8867','COLEGIO SAN FRANCISCO DE ASIS','Metropolitana','LAS CONDES','Part. Pagado'),
('8868','COLEGIO LA GIROUETTE','Metropolitana','LAS CONDES','Part. Pagado'),
('8869','COLEGIO THE NEWLAND SCHOOL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8870','COLEGIO COMPANIA DE MARIA APOQUINDO','Metropolitana','LAS CONDES','Part. Pagado'),
('8871','COLEGIO LOS ANDES DE VITACURA','Metropolitana','VITACURA','Part. Pagado'),
('8872','COLEGIO WENLOCK SCHOOL','Metropolitana','LAS CONDES','Part. Pagado'),
('8873','COLEGIO VILLA MARIA ACADEMY','Metropolitana','LAS CONDES','Part. Pagado'),
('8877','COLEGIO DE LOS SAGRADOS CORAZONES','Metropolitana','VITACURA','Part. Pagado'),
('8878','COLEGIO DEL SAGRADO CORAZON DE APOQUINDO','Metropolitana','LAS CONDES','Part. Pagado'),
('8880','COLEGIO NIDO DE AGUILAS','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8883','COLEGIO CONCORDIA','Metropolitana','LAS CONDES','Part. Pagado'),
('8885','COLEGIO REDLAND SCHOOL','Metropolitana','LAS CONDES','Part. Pagado'),
('8888','COLEGIO DEL VERBO DIVINO','Metropolitana','LAS CONDES','Part. Pagado'),
('8892','COLEGIO SAN JUAN EVANGELISTA','Metropolitana','LAS CONDES','Part. Pagado'),
('8893','COLEGIO INTERNACIONAL SEK CHILE','Metropolitana','LAS CONDES','Part. Pagado'),
('8894','COLEGIO LA MAISONNETTE','Metropolitana','VITACURA','Part. Pagado'),
('8895','COLEGIO DALCAHUE','Metropolitana','LAS CONDES','Part. Pagado'),
('8900','COLEGIO SEMINARIO PONTIFICIO MENOR','Metropolitana','LAS CONDES','Part. Pagado'),
('8902','COLEGIO CORDILLERA DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('8903','COLEGIO LINCOLN INTERNATIONAL ACADEMY','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8904','COLEGIO SANTA URSULA','Metropolitana','VITACURA','Part. Pagado'),
('8905','COLEGIO EL CARMEN TERESIANO I','Metropolitana','VITACURA','Part. Pagado'),
('8906','COLEGIO SAINT GEORGE S COLLEGE','Metropolitana','VITACURA','Part. Pagado'),
('8909','COLEGIO BRADFORD SCHOOL','Metropolitana','VITACURA','Part. Pagado'),
('8911','COLEGIO ARABE','Metropolitana','LAS CONDES','Part. Pagado'),
('8912','ESCUELA DE PARVULOS N°1138 MY MELODY KINDERGARTEN SCHOOL','Metropolitana','LAS CONDES','Part. Pagado'),
('8914','COLEGIO WILLIAM KILPATRICK','Metropolitana','LAS CONDES','Part. Pagado'),
('8917','COLEGIO CRAIGHOUSE','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8919','COLEGIO SAN PEDRO NOLASCO','Metropolitana','VITACURA','Part. Pagado'),
('8921','COLEGIO BRITISH HIGH','Metropolitana','LAS CONDES','Part. Pagado'),
('8923','LYCÉE ANTOINE DE SAINT-EXUPÉRY','Metropolitana','VITACURA','Part. Pagado'),
('8925','LICEO POLIVALENTE ARTURO ALESSANDRI P.','Metropolitana','PROVIDENCIA','Municipal'),
('8926','LICEO Nº7 DE PROVIDENCIA LUISA SAAVEDRA','Metropolitana','PROVIDENCIA','Municipal'),
('8927','LICEO CARMELA CARVAJAL DE PRAT','Metropolitana','PROVIDENCIA','Municipal'),
('8928','LICEO JOSE VICTORINO LASTARRIA','Metropolitana','PROVIDENCIA','Municipal'),
('8930','LICEO B 42 TAJAMAR','Metropolitana','PROVIDENCIA','Municipal'),
('8931','ESCUELA BASICA EL VERGEL','Metropolitana','PROVIDENCIA','Municipal'),
('8933','ESCUELA DE PROVIDENCIA','Metropolitana','PROVIDENCIA','Municipal'),
('8934','ESCUELA ABELARDO ITURRIAGA JAMETT','Metropolitana','PROVIDENCIA','Municipal'),
('8936','ESCUELA BASICA Y ESPECIAL MC-KAY','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('8938','COLEGIO POLIV. PROF. GUILLERMO GONZALEZ HEIN','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('8942','ESCUELA PARTICULAR TERESIANA DE SAN JOSE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('8944','COLEGIO PARTICULAR REGINA PACIS','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('8945','ESCUELA Y LICEO PAULINA VON MALLINCKRODT','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('8950','COLEGIO COMPANIA DE MARIA-SEMINARIO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8953','COLEGIO HUELEN','Metropolitana','VITACURA','Part. Pagado'),
('8954','COLEGIO MARIA INMACULADA','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('8956','COLEGIO LATINOAMERICANO DE INTEGRACION','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8959','COLEGIO CAMBRIDGE LARRAIN','Metropolitana','LA REINA','Part. Pagado'),
('8966','COLEGIO SAINT GABRIEL´S SCHOOL LOCAL SEDE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8967','ESCUELA DE PARVULOS N°1198 HOUSE GARDEN','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8969','COLEGIO THE ANGEL´S SCHOOL','Metropolitana','ÑUÑOA','Part. Pagado'),
('8972','COLEGIO SAN BENITO','Metropolitana','VITACURA','Part. Pagado'),
('8974','COLEGIO CAMPVS COLLEGE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8978','COLEGIO DUNALASTAIR','Metropolitana','LAS CONDES','Part. Pagado'),
('8979','COLEGIO ALEMAN DE SANTIAGO','Metropolitana','LAS CONDES','Part. Pagado'),
('8981','COLEGIO DE LOS SAGRADOS CORAZONES PROVIDENCIA','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8984','COLEGIO TREWHELA´S ENGLISH SCHOOL','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8988','COLEGIO MARIANO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8991','COLEGIO PADRE HURTADO Y JUANITA DE LOS ANDES','Metropolitana','LAS CONDES','Part. Pagado'),
('8992','COLEGIO ALEMAN SANKT THOMAS MORUS','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8995','COLEGIO SANTIAGO COLLEGE','Metropolitana','LO BARNECHEA','Part. Pagado'),
('8996','COLEGIO SAN IGNACIO EL BOSQUE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('8997','WEXFORD COLLEGE N 2','Metropolitana','PROVIDENCIA','Part. Subvencionado'),
('8998','COLEGIO CAMBRIDGE COLLEGE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('9003','COLEGIO THE ENGLISH INSTITUTE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('9004','COLEGIO UNIVERSITARIO INGLES','Metropolitana','PROVIDENCIA','Part. Pagado'),
('9006','COMPLEJO EDUCACIONAL LA REINA','Metropolitana','LA REINA','Municipal'),
('9007','LICEO EUGENIO MARÍA DE HOSTOS','Metropolitana','LA REINA','Municipal'),
('9008','COLEGIO MUNICIPALIZADO CONFEDERAC SUIZA','Metropolitana','LA REINA','Municipal'),
('9010','ESCUELA D-231 ESPECIAL DE DESARROLLO','Metropolitana','LA REINA','Municipal'),
('9011','COLEGIO SAN CONSTANTINO','Metropolitana','LA REINA','Municipal'),
('9012','ESCUELA BASICA YANGTSE EX E-229','Metropolitana','LA REINA','Municipal'),
('9013','ESCUELA PALESTINA','Metropolitana','LA REINA','Municipal'),
('9017','ESCUELA PARTICULAR SAN LEONARDO MURIALDO','Metropolitana','LA REINA','Part. Subvencionado'),
('9020','COLEGIO SANTA CATALINA LABOURÉ','Metropolitana','LA REINA','Part. Subvencionado'),
('9025','ESCUELA HERMANAS DEL NINO JESUS','Metropolitana','LA REINA','Part. Subvencionado'),
('9026','ESCUELA ESPECIAL CTI.LOS COPIHUES   N.3','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9032','ESCUELA PARTICULAR ANTINIL','Metropolitana','LA REINA','Part. Subvencionado'),
('9033','COLEGIO STA MARIA REINA','Metropolitana','LA REINA','Part. Subvencionado'),
('9035','COLEGIO EL CARMEN TERESIANO','Metropolitana','LA REINA','Part. Pagado'),
('9036','COLEGIO JOSÉ ARRIETA','Metropolitana','LA REINA','Part. Subvencionado'),
('9038','COLEGIO SAN LUIS DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('9039','COLEGIO RUBEN DARIO','Metropolitana','LA REINA','Part. Pagado'),
('9042','COLEGIO DE LA SALLE','Metropolitana','LA REINA','Part. Pagado'),
('9043','ESCUELA DE PARVULOS N°750 CHISPITAS','Metropolitana','LA REINA','Part. Pagado'),
('9046','COLEGIO THE GRANGE SCHOOL','Metropolitana','LA REINA','Part. Pagado'),
('9051','COLEGIO ANDREE ENGLISH SCHOOL','Metropolitana','LA REINA','Part. Pagado'),
('9052','ESCUELA DE PARVULOS LOS TROMPITOS','Metropolitana','LA REINA','Part. Pagado'),
('9053','COLEGIO TERESIANO ENRIQUE DE OSSO','Metropolitana','LA REINA','Part. Pagado'),
('9054','COLEGIO SAINT JOHN´S VILLA ACADEMY','Metropolitana','LA REINA','Part. Pagado'),
('9056','ESCUELA BASICA N° 733 PEQUENO MOZART','Metropolitana','LA REINA','Part. Pagado'),
('9058','INSTITUTO SUPERIOR DE COMERCIO DIEGO PORT','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9060','LICEO POLITECNICO PEDRO DE VALDIVIA','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9061','LICEO POLITECNICO A N° 60 PRESIDENTE MANUEL MONTT','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9063','LICEO INDUSTRIAL BICENTENARIO CHILENO ALEMAN','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9064','LICEO TECNICO B NÕ 58 JOSE MARIA NARBONA','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9065','LICEO COMERCIAL GABRIEL GONZALEZ VIDELA','Metropolitana','ÑUÑOA','Adm. Delegada'),
('9069','LICEO POLIVALENTE MERCEDES MARIN DEL SOLAR','Metropolitana','MACUL','Part. Subvencionado'),
('9070','ESCUELA BENJAMIN CLARO VELASCO','Metropolitana','ÑUÑOA','Municipal'),
('9071','LICEO AUGUSTO D HALMAR','Metropolitana','ÑUÑOA','Municipal'),
('9072','LICEO VILLA MACUL ACADEMIA EX LICEO JUANA DE IBARBOUROU A 48','Metropolitana','MACUL','Servicio Local'),
('9073','LICEO BICENTENARIO CARMELA SILVA DONOSO','Metropolitana','ÑUÑOA','Municipal'),
('9074','LICEO JOSE TORIBIO MEDINA','Metropolitana','ÑUÑOA','Municipal'),
('9075','LICEO BICENTENARIO JOAQUIN EDWARDS BELLO','Metropolitana','MACUL','Servicio Local'),
('9077','COMPLEJO EDUC.MUN. BRIGIDA  WALKER.','Metropolitana','ÑUÑOA','Municipal'),
('9078','LICEO LENKA FRANULIC','Metropolitana','ÑUÑOA','Municipal'),
('9082','COL TEC PROFESIONAL REPUBLICA ARGENTINA','Metropolitana','ÑUÑOA','Municipal'),
('9083','ESCUELA DIFERENCIAL MUNICIPAL AMAPOLAS','Metropolitana','ÑUÑOA','Municipal'),
('9084','ESC.PRESIDENTE EDUARDO FREI MONTALVA','Metropolitana','ÑUÑOA','Municipal'),
('9085','ESCUELA JOSE BERNARDO SUAREZ','Metropolitana','MACUL','Servicio Local'),
('9086','ESCUELA AURORA DE CHILE','Metropolitana','ÑUÑOA','Municipal'),
('9087','CENTRO EDUC. VALLE HERMOSO','Metropolitana','PEÑALOLÉN','Municipal'),
('9088','LICEO ANTONIO HERMIDA FABRES','Metropolitana','PEÑALOLÉN','Municipal'),
('9089','ESCUELA BÁSICA JOSÉ TORIBIO MEDINA','Metropolitana','ÑUÑOA','Municipal'),
('9090','ESCUELA BAS. CENTRO EDUCACIONAL MILLANTU','Metropolitana','MACUL','Servicio Local'),
('9091','ESCUELA REPUBLICA DE FRANCIA','Metropolitana','ÑUÑOA','Municipal'),
('9097','ESCUELA REPUBLICA DE COSTA RICA','Metropolitana','ÑUÑOA','Municipal'),
('9098','LICEO JUAN BAUTISTA PASTEN','Metropolitana','PEÑALOLÉN','Municipal'),
('9100','LICEO REPUBLICA DE SIRIA','Metropolitana','ÑUÑOA','Municipal'),
('9102','ESCUELA GUILLERMO ZANARTU IRIGOYEN','Metropolitana','ÑUÑOA','Municipal'),
('9103','ESCUELA UNION NACIONAL ARABE','Metropolitana','PEÑALOLÉN','Municipal'),
('9104','ESCUELA VILLA MACUL','Metropolitana','MACUL','Servicio Local'),
('9105','CENTRO EDUCACIONAL EDUARDO DE LA BARRA','Metropolitana','PEÑALOLÉN','Municipal'),
('9106','CENTRO EDUCACION MARIANO EGANA','Metropolitana','PEÑALOLÉN','Municipal'),
('9107','CENTRO EDUCACIONAL INTEGRAL DE ADULTOS ERASMO ESCALA ARRIAGADA (CEIA))','Metropolitana','PEÑALOLÉN','Municipal'),
('9110','ESCUELA CARLOS FERNANDEZ PENA','Metropolitana','PEÑALOLÉN','Municipal'),
('9111','ESCUELA LUIS  ARRIETA CANAS','Metropolitana','PEÑALOLÉN','Municipal'),
('9116','LICEO MUNICIPALIZADO MANUEL ROJAS','Metropolitana','MACUL','Servicio Local'),
('9117','COLEGIO BICENTENARIO MATILDE HUICI NAVAS','Metropolitana','PEÑALOLÉN','Municipal'),
('9121','ESCUELA TOBALABA','Metropolitana','PEÑALOLÉN','Municipal'),
('9122','ESCUELA JULIO MONTT SALAMANCA','Metropolitana','MACUL','Servicio Local'),
('9125','COLEGIO JULIO BARRENECHEA','Metropolitana','MACUL','Servicio Local'),
('9127','COLEGIO LIKANKURA DE PEÑALOLÉN','Metropolitana','PEÑALOLÉN','Municipal'),
('9128','ESCUELA DE ED.DIFERENCIAL HELLEN KELLER','Metropolitana','ÑUÑOA','Municipal'),
('9131','ESCUELA JUAN MOYA MORALES','Metropolitana','ÑUÑOA','Municipal'),
('9135','COLEGIO APOSTOL SAN PEDRO','Metropolitana','ÑUÑOA','Part. Pagado'),
('9137','ESCUELA PARTICULAR ESPECIAL CEINTRALE','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9140','ESCUELA PARTICULAR SANTA VICTORIA','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9142','ESCUELA BASICA PARTICULAR LOS HUSARES','Metropolitana','MACUL','Part. Subvencionado'),
('9144','ESCUELA BASICA MARTINEZ DE ROZAS','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9147','COLEGIO PARTICULAR N 1 DE NUNOA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9150','ESCUELA PARTICULAR REGINA MUNDI','Metropolitana','MACUL','Part. Subvencionado'),
('9151','COLEGIO SANTA MARGARITA DE ESCOCIA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9153','CENTRO DE CAPACITACIÓN LABORAL PARA DEFICIENTES MENTALES','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9156','ESCUELA BAS. RENACIMIENTO N_ 1','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9158','COLEGIO PARTICULAR SAN FERNANDO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9162','ESCUELA PARTICULAR NUESTRA SRA.DEL PILAR','Metropolitana','MACUL','Part. Subvencionado'),
('9164','LICEO POLITEC.PARTICULAR CARMEN ARRIARAN','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9165','ESCUELA BAS. N_ 850 SANTA SOFIA','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9168','COLEGIO LIBERTADOR SIMON BOLIVAR','Metropolitana','MACUL','Part. Subvencionado'),
('9171','ESCUELA SAN JOSE OBRERO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9172','COLEGIO POLIV. ROCKET COLLEGE','Metropolitana','MACUL','Part. Subvencionado'),
('9175','ESCUELA BASICA COLEGIO SANTA MARTA DE PENALOL','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9177','LICEO COMERCIAL PARTICULAR ÑUÑOA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9179','COLEGIO SANTA MARTA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9182','COLEGIO POLIVALENTE YORK','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9183','ESC.PARA SORDOS DR. OTTE GABLER','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9184','COLEGIO PRECIOSA SANGRE','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9185','LICEO SALESIANO CAMILO ORTUZAR MONTT','Metropolitana','MACUL','Part. Subvencionado'),
('9187','ESC. PART. MARTA BRUNET','Metropolitana','MACUL','Part. Subvencionado'),
('9190','ESCUELA PARTICULAR COLEGIO CEDI','Metropolitana','MACUL','Part. Pagado'),
('9194','CENTRO EDUC PROFES GMO GONZALEZ HEINRICH','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9197','ESCUELA PARTICULAR WELCOME SCHOOL','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9200','COLEGIO PARTICULAR JORGE PRIETO LETELIER','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9201','ESCUELA PARTICULAR SANTIAGO DE CHILE','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9205','ESCUELA PARTICULAR THE NEW SCHOOL','Metropolitana','MACUL','Part. Subvencionado'),
('9206','COLEGIO PARTICULAR NUMERO DOS DE NUÑOA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9208','COMPLEJO EDUCACIONAL ESPERANZA','Metropolitana','MACUL','Part. Subvencionado'),
('9209','ESCUELA PARTICULAR SAN JUAN BAUTISTA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('9212','ESCUELA PARTICULAR INST.P.DE VALDIVIA','Metropolitana','MACUL','Part. Subvencionado'),
('9213','COLEGIO, CENTRO EDUC.AMERICO VESPUCIO','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('9216','COLEGIO SUIZO DE SANTIAGO','Metropolitana','ÑUÑOA','Part. Pagado'),
('9217','COLEGIO AKROS','Metropolitana','ÑUÑOA','Part. Pagado'),
('9218','ESCUELA DE PARAVULOS N°1126 CEDI','Metropolitana','MACUL','Part. Pagado'),
('9221','COLEGIO ALTAMIRA','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('9228','INSTITUTO PABLO NERUDA','Metropolitana','ÑUÑOA','Part. Pagado'),
('9230','COLEGIO ISABEL LA CATOLICA','Metropolitana','ÑUÑOA','Part. Pagado'),
('9231','ESCUELA DE PARVULOS N°1224 RENASCENCE','Metropolitana','ÑUÑOA','Part. Pagado'),
('9237','INSTITUTO HEBREO DR CHAIM WEIZMANN-ORT','Metropolitana','LO BARNECHEA','Part. Pagado'),
('9239','COLEGIO FRANCISCO DE MIRANDA','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('9240','ESCUELA ESPECIAL N°649 MIGUEL ARCANGEL','Metropolitana','ÑUÑOA','Part. Pagado'),
('9244','FUNDACIÓN EDUCACIONAL COLEGIO NOTRE DAME','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('9246','COLEGIO SAN AGUSTIN','Metropolitana','ÑUÑOA','Part. Pagado'),
('9249','COLEGIO SAINT GASPAR COLLEGE','Metropolitana','ÑUÑOA','Part. Pagado'),
('9250','COLEGIO CALASANZ','Metropolitana','ÑUÑOA','Part. Pagado'),
('9259','COLEGIO MANQUECURA ÑUÑOA','Metropolitana','ÑUÑOA','Part. Pagado'),
('9262','ESCUELA DE PARVULOS N°1211 JARDIN INFANTIL MUSICAL DON OSITO','Metropolitana','ÑUÑOA','Part. Pagado'),
('9267','LICEO EXPERIMENTAL MANUEL DE SALAS','Metropolitana','ÑUÑOA','Part. Pagado'),
('9268','ESCUELA BÁSICA Nº520 FLORENCE NIGHTINGALE','Metropolitana','MACUL','Part. Pagado'),
('9270','COLEGIO VICTOR DOMINGO SILVA','Metropolitana','ÑUÑOA','Part. Pagado'),
('9271','COLEGIO THE KENT SCHOOL','Metropolitana','PROVIDENCIA','Part. Pagado'),
('9276','COLEGIO UNIVERSITARIO EL SALVADOR','Metropolitana','ÑUÑOA','Part. Pagado'),
('9277','COLEGIO SAN MARCOS','Metropolitana','MACUL','Part. Pagado'),
('9278','COLEGIO INSTITUTO SANTA MARIA','Metropolitana','ÑUÑOA','Part. Pagado'),
('9281','LICEO BICENTENARIO DE EXCELENCIA BENJAMIN VICUNA MACKENNA','Metropolitana','LA FLORIDA','Municipal'),
('9282','ESCUELA GUARDIAMARINA ERNESTO RIQUELME','Metropolitana','LA FLORIDA','Municipal'),
('9283','ESCUELA BELLAVISTA','Metropolitana','LA FLORIDA','Municipal'),
('9284','ESCUELA ELSA SANTIBANEZ','Metropolitana','LA FLORIDA','Municipal'),
('9285','ESCUELA MARCELA PAZ','Metropolitana','LA FLORIDA','Municipal'),
('9288','LICEO NUEVO AMANECER','Metropolitana','LA FLORIDA','Municipal'),
('9289','ESCUELA LAS ARAUCARIAS','Metropolitana','LA FLORIDA','Municipal'),
('9290','ESCUELA SOTERO DEL RIO','Metropolitana','LA FLORIDA','Municipal'),
('9292','COMPLEJO EDUC. MUNICIPAL CARDEN.A.SAMORE','Metropolitana','LA FLORIDA','Municipal'),
('9293','LICEO POLIVALENTE LOS ALMENDROS','Metropolitana','LA FLORIDA','Municipal'),
('9294','LICEO ANDRES BELLO','Metropolitana','LA FLORIDA','Municipal'),
('9296','ESCUELA LAS LILAS','Metropolitana','LA FLORIDA','Municipal'),
('9298','LICEO INDIRA GANDHI','Metropolitana','LA FLORIDA','Municipal'),
('9299','ESCUELA SANTA IRENE','Metropolitana','LA FLORIDA','Municipal'),
('9302','ESCUELA LO CANAS','Metropolitana','LA FLORIDA','Municipal'),
('9304','ESCUELA LOS CEREZOS','Metropolitana','LA FLORIDA','Municipal'),
('9306','ESCUELA LOS QUILLAYES','Metropolitana','LA FLORIDA','Municipal'),
('9307','ESCUELA  OSCAR CASTRO','Metropolitana','LA FLORIDA','Municipal'),
('9308','ESCUELA PARTICULAR UNIDAD DIVINA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9311','COLEGIO PARTICULAR ISLA WELLINGTON','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9312','CHILEAN EAGLES COLLEGE LAS VIZCACHAS','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('9317','INSTITUTO LA SALLE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9318','COLEGIO MAURICIO RUGENDAS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9324','ESCUELA PARTICULAR MSR.DIEGO ROSALES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9328','COLEGIO POLIV. SAN SEBASTIAN DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9331','COLEGIO PARTICULAR THE GARDEN SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9332','COLEGIO SANTA PATRICIA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9333','ESCUELA BÁSICA N°993 ANTONIO BORQUEZ SOLAR','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9334','COLEGIO PORTALES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9335','ESCUELA PARTICULAR LOS COPIHUES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9337','ESCUELA PARTICULAR LORD TOMAS COCHRANE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9339','ESCUELA Y COLEGIO POLITECNICO LOS HEROES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9340','COLEGIO SANTA MARIA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9341','ESCUELA PART. JOHN PAUL SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9342','ESCUELA PARTICULAR LAURA ELGUETA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9345','ESCUELA PARTICULAR LOS CASTANOS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9347','CENTRO EDUCACIONAL LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9348','ESCUELA PARTICULAR ESPECIAL NUEVO RUMBO','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9356','COLEGIO PARTICULAR SAN FRANCISCO DE ASIS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9358','ESC. PART. SAINT GERMAINE SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9362','COLEGIO PARTICULAR LA CONCEPCION','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9363','ESC. PART. RAFAEL SOTOMAYOR B.','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9366','ESCUELA BASICA PARTICULAR PAICAVI  NUM 1','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9368','ESCUELA PARTICULAR PAPA JUAN PABLO II','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9369','ESCUELA PARTICULAR ROSARIO CONCHA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9373','BERNADETTE COLLEGE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9375','CENTRO EDUCACIONAL LONDON','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9376','ESCUELA ESPECIAL INST.VICUNA MACKENNA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9377','COLEGIO POLIV. VICENTE VALDES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9385','COLEGIO LE MONDE','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9393','ESCUELA DE PARVULOS N°1136 THE RED GARDEN','Metropolitana','LA FLORIDA','Part. Pagado'),
('9396','COLEGIO SANTA CECILIA DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Pagado'),
('9405','LICEO BETSABE HORMAZABAL DE ALARCON','Metropolitana','SAN MIGUEL','Servicio Local'),
('9406','LICEO ANDRES BELLO','Metropolitana','SAN MIGUEL','Servicio Local'),
('9407','ESCUELA DE LA INDUSTRIA GRAFICA HECTOR GO','Metropolitana','SAN MIGUEL','Adm. Delegada'),
('9408','LICEO BICENTENARIO POLITECNICO SAN JOAQUIN','Metropolitana','SAN JOAQUÍN','Adm. Delegada'),
('9409','LICEO COMERCIAL INSTITUTO SUPERIOR DE COMERCIO DE CHILE (EX A99)','Metropolitana','SAN MIGUEL','Adm. Delegada'),
('9410','ESCUELA  CONSOLIDADA DAVILA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9411','CENTRO EDUCACIONAL HORACIO ARAVENA A.','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9413','ESCUELA GENERAL BASICA SANTA FE','Metropolitana','SAN MIGUEL','Servicio Local'),
('9414','COLEGIO CIUDAD DE FRANKFORT','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9415','ESCUELA TERRITORIO ANTARTICO','Metropolitana','SAN MIGUEL','Servicio Local'),
('9416','ESCUELA POETAS DE CHILE','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9418','ESCUELA LA VICTORIA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9419','LICEO MUNICIPAL ENRIQUE BACKAUSSE','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9421','LICEO MUNICIPAL SAN JOAQUIN','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9422','ESCUELA CENTRO EDUC. REP. MEXICANA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9424','ESCUELA BASICA FRAY CAMILO HENRIQUEZ','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9426','ESCUELA LLANO SUBERCASEAUX','Metropolitana','SAN MIGUEL','Servicio Local'),
('9428','ESCUELA BASICA RICARDO E. LATCHMAN','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9429','ESCUELA POETA VICTOR DOMINGO SILVA','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9430','CENTRO EDUC. PROVINCIA DE ÑUBLE','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9431','ESCUELA VILLA SAN MIGUEL','Metropolitana','SAN MIGUEL','Servicio Local'),
('9433','ESCUELA PABLO NERUDA','Metropolitana','SAN MIGUEL','Servicio Local'),
('9437','ESC. BAS. Y ESP. SU SANTIDAD JUAN XXIII','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9443','ESCUELA BAS. LOS HEROES DE YUNGAY','Metropolitana','LA GRANJA','Servicio Local'),
('9444','ESCUELA ESPECIAL LOS CEDROS DEL LIBANO','Metropolitana','SAN MIGUEL','Servicio Local'),
('9446','ESCUELA DE PARVULOS RAYITO DE LUZ','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9457','ESCUELA BÁSICA POETA NERUDA (EX-483)','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('9458','ESCUELA BOROA','Metropolitana','PEDRO AGUIRRE CERDA','Servicio Local'),
('9460','INST. REG. EDUC ADULTOS SAN MIGUEL','Metropolitana','SAN MIGUEL','Servicio Local'),
('9461','ESC. ESP. DE ADULTOS HUGO MORALES BIZAMA','Metropolitana','SAN MIGUEL','Servicio Local'),
('9467','COLEGIO LA CASTRINA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9472','LICEO POLITECNICO SAN LUIS','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9473','ESCUELA BAS.PART.N 23 COLEGIO SANTA ANA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9484','COLEGIO SANTA ROSA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9485','ESCUELA PARTICULAR HANSEL Y GRETEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9486','COLEGIO ESPIRITU SANTO DEL VERBO DIVINO','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9487','ESCUELA INDUSTRIAL PART. LAUTARO','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9489','LICEO COMERCIAL JAVIERA Y J L CARRERA N1','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9490','ESCUELA PARTICULAR LUCILA GODOY','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9499','ESCUELA HOGAR DE CIEGOS SANTA LUCIA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('9500','COLEGIO PART. NUESTRA SRA DEL HUERTO','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9502','COLEGIO POLIV.ADVENTISTA SANTIAGO SUR','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9503','ESCUELA PARTICULAR PIO DOCE','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9504','ESCUELA PARTICULAR Y COLEGIO CHILE','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9505','ESCUELA PARTICULAR JOSE A.ALFONSO','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9506','ESC.BAS.PROFESORA AIDA RAMOS DIAZ','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9507','ESCUELA PARTICULAR LAURA VICUNA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9508','COLEGIO PARTICULAR POBL. ALESSANDRI','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9509','COLEGIO SUBERCASEAUX COLLEGE','Metropolitana','SAN MIGUEL','Part. Pagado'),
('9510','COLEGIO PART. ANTONIO ACEVEDO HERNANDEZ','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9511','ESCUELA PARTICULAR GRAN AVENIDA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9512','ESCUELA BASICA PARTIC JACQUELINE KENNEDY','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9518','COLEGIO PARTICULAR PADRE FIDEL ABARCA','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9519','COLEGIO BICENTENARIO SANTO CURA DE ARS','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9520','PRINCESS MARGARET COLLEGE','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9527','ESCUELA PARTICULAR ECOLE NOEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9528','ESCUELA PARTICULAR LA RAIZ Y LA ESPIGA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9531','ESCUELA PARTICULAR MIGUEL DAVILA','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9533','ESCUELA BASICA PARTICULAR RAINBOW SCHOOL','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9534','COLEGIO SAN DAMIAN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('9536','ESCUELA PART.CENTRO EDUC.SANTA MONICA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9539','ESC. BAS. N°221 SANTA CATALINA DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9540','ESCUELA PARTICULAR SAN CARLOS','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9543','ESCUELA PARTICULAR EL GRECO','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9544','ESCUELA PARTICULAR AMIGOS','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9547','ESCUELA BAS. PART. QUEEN & FLOWER COLLEGE','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9551','ESCUELA PARTICULAR LA RONDA DE SN.MIGUEL','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9553','COLEGIO KING´S SCHOOL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9556','ESCUELA PARTICULAR MARQUEZ DE OVANDO','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9558','ESCUELA PARTICULAR ROCIO DE LOS ANGELES','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('9564','COLEGIO PARROQUIAL SAN MIGUEL','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9570','INSTITUTO MIGUEL LEON PRADO','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('9572','ESCUELA PARTICULAR JAVIERA CARRERA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('9574','ESCUELA BASICA PARTICULAR CAMINITO','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('9579','LICEO INDUSTRIAL DE SAN MIGUEL AGUSTIN ED','Metropolitana','SAN JOAQUÍN','Adm. Delegada'),
('9581','LICEO TECNICO A-100 DE SAN MIGUEL','Metropolitana','SAN MIGUEL','Adm. Delegada'),
('9582','LICEO BICENTENARIO FRANCISCO FRIAS VALENZUELA','Metropolitana','LA GRANJA','Servicio Local'),
('9583','CENTRO EDUCACIONAL MUN.MARIANO LATORRE','Metropolitana','LA PINTANA','Servicio Local'),
('9584','LICEO COMERCIAL VATE VICENTE HUIDOBRO','Metropolitana','SAN RAMÓN','Adm. Delegada'),
('9585','LICEO DOCTOR ALEJANDRO DEL RIO','Metropolitana','LA GRANJA','Servicio Local'),
('9586','LICEO MUNICIPALIZADO ARAUCANIA','Metropolitana','SAN RAMÓN','Servicio Local'),
('9587','LICEO MALAQUIAS CONCHA','Metropolitana','LA GRANJA','Servicio Local'),
('9588','ESCUELA BAS. TECNO SUR','Metropolitana','LA GRANJA','Servicio Local'),
('9590','ESCUELA BELGICA','Metropolitana','LA GRANJA','Servicio Local'),
('9591','LICEO N523','Metropolitana','LA PINTANA','Servicio Local'),
('9592','ESCUELA BASICA SENDERO DEL SABER','Metropolitana','SAN RAMÓN','Servicio Local'),
('9593','ESCUELA BASICA EDUCADORES DE CHILE','Metropolitana','SAN RAMÓN','Servicio Local'),
('9595','ESCUELA CAPITAN AVALOS','Metropolitana','LA PINTANA','Servicio Local'),
('9597','ESCUELA PABLO DE ROKHA','Metropolitana','LA PINTANA','Servicio Local'),
('9598','ESCUELA MUNICIPAL VIOLETA PARRA','Metropolitana','LA PINTANA','Servicio Local'),
('9599','LICEO MUNICIPAL PURKUYEN','Metropolitana','SAN RAMÓN','Servicio Local'),
('9600','ESCUELA NANIHUE','Metropolitana','SAN RAMÓN','Servicio Local'),
('9601','CENTRO EDUCACIONAL MUNICIPAL SAN RAMON','Metropolitana','SAN RAMÓN','Servicio Local'),
('9602','COLEGIO NERUDA','Metropolitana','LA PINTANA','Servicio Local'),
('9604','LICEO MUNICIPALIZADO CENT.ED. LA PINTANA','Metropolitana','LA PINTANA','Servicio Local'),
('9605','COLEGIO MUNICIPAL PROCERES DE CHILE','Metropolitana','LA GRANJA','Servicio Local'),
('9606','ESCUELA BAS. LA ARAUCANIA','Metropolitana','LA GRANJA','Servicio Local'),
('9607','ESCUELA DIFERENCIAL SANTA TERESITA DE LOS AND','Metropolitana','LA GRANJA','Servicio Local'),
('9608','CENTRO EDUCACIONAL MIRADOR','Metropolitana','SAN RAMÓN','Servicio Local'),
('9609','ESCUELA BAS. SANITAS','Metropolitana','LA GRANJA','Servicio Local'),
('9610','ESCUELA BAS. POETA OSCAR CASTRO ZUNIGA','Metropolitana','LA GRANJA','Servicio Local'),
('9611','ESCUELA BASICA TUPAHUE','Metropolitana','SAN RAMÓN','Servicio Local')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
