-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 29 de 31 | filas 11201-11600
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('40093','ESCUELA DE LENGUAJE KOALA','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('40095','ESCUELA RAYEN PAINE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('40099','LICEO TECNICO PROFESIONAL PAPUDO','Valparaíso','PAPUDO','Corp. Municipal'),
('40101','COLEGIO NUESTRA ESPERANZA','O''Higgins','MOSTAZAL','Part. Subvencionado'),
('40102','LICEO TECNOLOGICO COÑARIPE','Los Ríos','PANGUIPULLI','Part. Subvencionado'),
('40105','JARDIN INFANTIL MUNDO PEQUEÑO','O''Higgins','RANCAGUA','Part. Pagado'),
('40106','ESC. ESPECIAL DE LENGUAJE EDUCERE','La Araucanía','PITRUFQUÉN','Part. Subvencionado'),
('40107','ESC. ESP. DE LENGUAJE TORNASOL','La Araucanía','RENAICO','Part. Subvencionado'),
('40109','JARDIN INFANTIL LOS ENANITOS','Valparaíso','VALPARAÍSO','Part. Pagado'),
('40110','COLEGIO SAINT MATTHEW','La Araucanía','VILLARRICA','Part. Subvencionado'),
('40111','JARDIN INFANTIL MAGIC GARDEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('40113','ESC.ESP. DE LENGUAJE RAYITO DE SOL','Los Ríos','MARIQUINA','Part. Subvencionado'),
('40114','LICEO ORIENTE','O''Higgins','RENGO','Corp. Municipal'),
('40115','CENTRO EDUCACIONAL PAULO FREIRE','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('40116','ESCUELA PARTICULAR MARTÍN TEJEDA GUZMAN','Los Ríos','MARIQUINA','Part. Subvencionado'),
('40119','ESCUELA ESP. DE LENGUAJE AMANCAY','La Araucanía','TEMUCO','Part. Subvencionado'),
('40121','ESCUELA ESPECIAL DE LENGUAJE HUASCO EDUCA','Atacama','HUASCO','Part. Subvencionado'),
('40122','ESC.ESP.DE LENG. MI PEQUEÑO RINCON','Valparaíso','RINCONADA','Part. Subvencionado'),
('40123','ESCUELA ESPECIAL DE LENGUAJE GABRIELA MISTRAL','Valparaíso','PANQUEHUE','Part. Subvencionado'),
('40124','ESC. ESP. LENG. JOSE GRIMALDI ACOTTO','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('40125','COLEGIO PUMAHUE','Valparaíso','VALPARAÍSO','Part. Pagado'),
('40126','COLEGIO RAUL SILVA HENRIQUEZ','Coquimbo','OVALLE','Corp. Municipal'),
('40127','ESCUELA ESPECIAL DE LENGUAJE ARCO IRIS','Valparaíso','CATEMU','Part. Subvencionado'),
('40130','ESCUELA ESPECIAL DE LENGUAJE ILWEN','La Araucanía','TEMUCO','Part. Subvencionado'),
('40132','JARDIN INFANTIL SNOOPY','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40133','ESCUELA F-187','O''Higgins','RENGO','Corp. Municipal'),
('40136','ESCUELA ESP.DE LENGUAJE AMANCAY','O''Higgins','REQUÍNOA','Part. Subvencionado'),
('40137','COLEGIO SINAI','Aysén','AYSÉN','Part. Subvencionado'),
('40138','ESCUELA DE LENGUAJE DIDASKALOS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40140','ESC. ESP. DE LENGUAJE LOS GIRASOLES LTDA.','Coquimbo','LA SERENA','Part. Subvencionado'),
('40141','ESCUELA ESPECIAL DE LENGUAJE SANTA ANA','Coquimbo','LA SERENA','Part. Subvencionado'),
('40142','ESC. ESP. DE LENGUAJE MI CASTILLO','Coquimbo','LA SERENA','Part. Subvencionado'),
('40143','ESCUELA ESPECIAL Y DE LENGUAJE CUMBRE DE PALABRAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40144','JARDIN INFANTIL CURIE','Coquimbo','LA SERENA','Part. Subvencionado'),
('40145','ESCUELA ESPECIAL GERMINA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40146','COLEGIO SAN RAMON','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40149','ESC.LENGUAJE SAN SEBASTIAN DE MAFIL','Los Ríos','MÁFIL','Part. Subvencionado'),
('40150','ESC. ESPECIAL DE LENGUAJE MI SILABARIO','Los Ríos','MARIQUINA','Part. Subvencionado'),
('40152','ESCUELA ESPECIAL MI SOL','Los Ríos','FUTRONO','Part. Subvencionado'),
('40153','JARDIN INFANTIL ESTRELLITA DE BELEN','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40154','ESCUELA DE LENGUAJE NUEVO INTI','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40155','COLEGIO DIEGO VELÁZQUEZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40156','JARDIN INFANTIL WILLKA','Tarapacá','IQUIQUE','Part. Pagado'),
('40157','ESC ESP TRAST DE LA COMUN ARUSIÑA LAS TARKAS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40158','ESCUELA ESPECIAL DE LENGUAJE FANTASIA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40159','ESC ESP DE LENG RAMONA HENRIQUEZ ORTEGA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40160','CTRO.EDUCACION INTEGRADA DE ADULTOS SAN FRANC','Valparaíso','LIMACHE','Part. Subvencionado'),
('40163','ESCUELA ESPECIAL DE LENGUAJE CASTILLO DE PALA','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40167','ESC.ESP.DE LENGUAJE MAS SOL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40168','ESC.ESP.LENG LOS BENJAMINES','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40170','ESCUELA ESPECIAL DE LENGUAJE COMPAÑIA DE JESU','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40171','ENGLISH COLLEGE SAGRADO CORAZON DE MARIA','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40172','ESCUELA ESP. DE LENGUAJE ILLAWARA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40173','ESCUELA ESPECIAL DE LENGUAJE VICTORIA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40174','COLEGIO EDUCACION ESPECIAL CUMBRES','Coquimbo','LA SERENA','Part. Subvencionado'),
('40176','COLEGIO SAN MATIAS','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('40177','COLEGIO IRQIILLARIY','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40178','ESC. ESPECIAL LENGUAJE ABRACADABRA','La Araucanía','COLLIPULLI','Part. Subvencionado'),
('40181','JARDIN INFANTIL Y SALA CUNA DEL ANGEL','Tarapacá','IQUIQUE','Part. Pagado'),
('40184','COLEGIO ESTACIÓN','Atacama','COPIAPÓ','Part. Subvencionado'),
('40185','JARDIN INFANTIL LONDON INTERNATIONAL ACADEMY','Valparaíso','CALERA','Part. Pagado'),
('40186','COLEGIO DE ADULTOS GALILEO','Coquimbo','OVALLE','Part. Subvencionado'),
('40187','PARVULARIO HAPPY CHILDREN','Valparaíso','CALERA','Part. Subvencionado'),
('40189','COLEGIO CABO ALTO','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40190','ESCUELA ESPECIAL DE LENGUAJE LOS COLORES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40191','JARDIN INFANTIL MONTESSORI SAN ANDRES','O''Higgins','SANTA CRUZ','Part. Pagado'),
('40192','ESCUELA ESPECIAL DE LENGUAJE PLAYLAND','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40193','ESCUELA ESPECIAL DE LENGUAJE FLOR DEL VALLE','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40194','COLEGIO DOMINGO SANTA MARIA','Coquimbo','LA SERENA','Part. Subvencionado'),
('40195','ESC. ESP. DE LENG. SAN JOSE DE MONT','Coquimbo','MONTE PATRIA','Part. Subvencionado'),
('40197','ESC ESPECIAL DE LENGUAJE KUNAMASTA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40202','COLEGIO MONTESSORI MILLANTÚ','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('40203','COLEGIO HERIBERTO BALDINO ACUÑA CASTILLO','Los Ríos','PAILLACO','Part. Subvencionado'),
('40205','ESCUELA ESPECIAL COANIL','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40206','CENT.DE EDUC.INTEG.DE ADULT.PUELMAPU','Coquimbo','LA SERENA','Part. Subvencionado'),
('40207','ESCUELA ESPECIAL PAX TERRA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40208','COLEGIO TECNICO PROFESIONAL ALTUE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40209','ESCUELA ESPECIAL DE LENGUAJE ELEFANTE MELODIA','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('40210','ESC ESP DE LENGUAJE NIDOS DEL SABER','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40212','ESCUELA ESPECIAL DE LENGUAJE CHISPITAS ALEGRE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40213','ESCUELA DE PARVULOS ARCA DE NOE','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40216','ESCUELA ESPECIAL DE LENGUAJE MONTSERRAT EDUCA','Valparaíso','CATEMU','Part. Subvencionado'),
('40217','ESCUELA ESPECIAL CLUB DE LEONES CRUZ DEL SUR','Magallanes','PORVENIR','Part. Subvencionado'),
('40218','CENTRO DE RETOS MULTIPLES EDUCAR Y CRECER','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40219','COLEGIO SAGRADA FAMILIA','O''Higgins','COLTAUCO','Part. Subvencionado'),
('40225','ESC. ESP. LENG. SEMILLITAS DE AMOR','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40230','COLEGIO TECNOLOGICO DON BOSCO DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40231','COLEGIO CORDILLERA','Coquimbo','LA SERENA','Part. Subvencionado'),
('40233','ESCUELA ESPECIAL DE LENGUAJE KAILIN','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40234','JARDIN INFANTIL EBEN EZER EIRL','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40235','ESCUELA DE TRASTORNOS DEL LENGUAJE TIA SANDRA','O''Higgins','DOÑIHUE','Part. Subvencionado'),
('40236','COLEGIO DE LENGUAJE PADRE PIO SAN FERNANDO','O''Higgins','SAN FERNANDO','Part. Subvencionado'),
('40237','ESCUELA ESPECIAL DE LENGUAJE ANTUPIREN','O''Higgins','RENGO','Part. Subvencionado'),
('40240','ESCUELA ESPECIAL DE LENGUAJE ARCOIRIS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40241','COLEGIO SAN JOSE','O''Higgins','MACHALÍ','Part. Subvencionado'),
('40242','COLEGIO BICENTENARIO','Valparaíso','CABILDO','Corp. Municipal'),
('40243','ESCUELA ESPECIAL DE LENGUAJE LA TRINIDAD','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40244','ESCUELA ESPECIAL DE LENGUAJE ILLIMANI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40245','ESCUELA ESPECIAL DE LENGUAJE AMAPOLAS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40248','COLEGIO LOS FRESNOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40251','LICEO SAN JUAN XXIII','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40252','LICEO JOSÉ CORTÉS BROWN-RECREO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40253','ESCUELA AUDIMED LOS AROMOS','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40254','JARDIN INFANTIL Y SALA CUNA EL SOLDADITO','Tarapacá','IQUIQUE','Part. Pagado'),
('40255','ESCUELA ESPEC.DE LENGUAJE CASABLANCA','Valparaíso','CASABLANCA','Part. Subvencionado'),
('40256','COLEGIO TECNICO NACIONES UNIDAS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40257','COLEGIO PILLANLIKAN','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40259','ESCUELA ESPECIAL DE LENGUAJE ALONKEN','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40260','INSTITUTO IBERO CHILE','Valparaíso','CASABLANCA','Part. Pagado'),
('40261','ESCUELA ESPECIAL DE LENGUAJE KEWEN','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40262','ESCUELA ESPECIAL DE LENGUAJE ULTIMA ESPERANZA','Magallanes','NATALES','Part. Subvencionado'),
('40264','JARDIN INFANTIL PARTICULAR ROTATIN','Atacama','VALLENAR','Part. Pagado'),
('40265','CENTRO EDUCATIVO RENACER-ESCUELA ESPECIAL Y TALLER LABORAL','Los Lagos','OSORNO','Part. Subvencionado'),
('40266','ESCUELA ESPECIAL DE LENGUAJE ENTRETEPALABRAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40267','ESC.ESP.LENG.Y J.INF.CASTILLO DE SONRISAS','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40270','ESCUELA DE LENGUAJE YATIÑA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40271','ESCUELA ESPECIAL DE LENGUAJE CUNCUNITA AMARILLA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40272','ESCUELA ESPECIAL DE LENGUAJE SANTA INES','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40273','ESCUELA ESPECIAL DE LENGUAJE TIERRA DE ANGELE','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40274','JARDIN INFANTIL Y SALA CUNA LOS ALEVINES','Atacama','CALDERA','Part. Pagado'),
('40275','ESCUELA ESPECIAL DE LENGUAJE MATICES','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40276','ESCUELA ESPECIAL DE LENGUAJE LANKUYEN','Los Lagos','MAULLIN','Part. Subvencionado'),
('40278','SCUOLA ITALIANA VILLA ALEMANA','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('40281','CENTRO DE EDUCACION ESPECIAL BELLAVISTA','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40282','COMUNIDAD DE APRENDIZAJE VINCULOS CASTRO','Los Lagos','CASTRO','Part. Subvencionado'),
('40283','ESCUELA ESPECIAL DE LENGUAJE INANTUE','Los Lagos','QUINCHAO','Part. Subvencionado'),
('40284','COLEGIO ANDALUE','Los Lagos','OSORNO','Part. Subvencionado'),
('40285','COLEGIO PARTICULAR DA VINCI SCHOOL','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40287','ESCUELA ESPECIAL DE LENGUAJE LOURDES','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40288','COLEGIO SAN FRANCISCO DE ASIS DE OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('40289','INSTITUTO BICENTENARIO J.MIGUEL CARRERA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('40291','ESCUELA ESPECIAL DE LENGUAJE Y COLEGIO BASICO ELUM KIMU','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('40293','ESCUELA ESPECIAL DE LENGUAJE SAN JOAQUIN','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40295','COLEGIO MAHATMA GANDHI','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40296','RAICES DE QUELLON','Los Lagos','QUELLÓN','Part. Subvencionado'),
('40298','COLEGIO BERNARDO O´HIGGINS','Coquimbo','LA SERENA','Part. Subvencionado'),
('40299','COLEGIO ROBLES','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40300','ESCUELA ESPECIAL DE LENGUAJE ANTIYAL LAS COMP','Coquimbo','LA SERENA','Part. Subvencionado'),
('40301','LICEO POLITECNICO DE QUELLON','Los Lagos','QUELLÓN','Servicio Local'),
('40302','ESCUELA ESPECIAL DE LENGUAJE EL ARBOL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40303','ESCUELA ESPECIAL DE LENGUAJE CHOCOLATITO','Coquimbo','PUNITAQUI','Part. Subvencionado'),
('40305','COLEGIO JUAN PABLO II','Valparaíso','NOGALES','Part. Subvencionado'),
('40307','ESCUELA ESPECIAL DE LENGUAJE PEQUEÑO ARCOIRIS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40308','COMUNIDAD DE ACCION EDUCATIVA VINCULOS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40309','ESCUELITA ESPECIAL DE LENGUAJE MAMIÑA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40310','COLEGIO PUCARA','O''Higgins','GRANEROS','Part. Subvencionado'),
('40311','COLEGIO CAUPOLICAN','Magallanes','PORVENIR','Part. Subvencionado'),
('40312','COLEGIO ESPECIAL SAN LORENZO','Atacama','DIEGO DE ALMAGRO','Part. Subvencionado'),
('40315','ESCUELA ESPECIAL DE LENGUAJE VALLE DE NANCAGU','O''Higgins','NANCAGUA','Part. Subvencionado'),
('40316','COLEGIO PULMAHUE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40317','ESCUELA ESPECIAL LENGUAJE AMAUTA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40318','ESCUELA ESPECIAL CORPADIS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40319','COLEGIO PART. SUB. CUMBRES DEL CHOAPA','Coquimbo','SALAMANCA','Part. Subvencionado'),
('40320','COLEGIO ACADEMIA TARAPACA ORELLA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40321','COLEGIO DE ADULTOS BRILLA EL SOL DE LA SERENA','Coquimbo','LA SERENA','Part. Subvencionado'),
('40322','ESC. ESP. DE TRAST. DEL LENGUAJE CORDILLERA P','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40324','ESC. ESP. DE TRAST. ESPEC. DE LENGUAJE ALTUE','Coquimbo','SALAMANCA','Part. Subvencionado'),
('40325','COLEGIO MASTTAY','Coquimbo','MONTE PATRIA','Corp. Municipal'),
('40328','ESCUELA DIEGO RIVERA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40329','COLEGIO ROBERTO BRAVO','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40331','COLEGIO SAN FRANCISCO DE VALLE HERMOSO','Valparaíso','LA LIGUA','Part. Subvencionado'),
('40333','ESC. ESPEC. DE LENGUAJE LLANQUIRAY','Coquimbo','OVALLE','Part. Subvencionado'),
('40334','AULA HOSPITALARIA AYUUKELEN EPU','Coquimbo','OVALLE','Part. Subvencionado'),
('40335','AULA HOSPITALARIA AYUUKELEN','Coquimbo','LA SERENA','Part. Subvencionado'),
('40337','JARDIN INFANTIL SAINT FRANCIS','O''Higgins','RANCAGUA','Part. Pagado'),
('40338','ACONCAGUA EDUCA','Valparaíso','SANTA MARÍA','Part. Subvencionado'),
('40340','LICEO BICENTENARIO DE ALTO DEL CARMEN','Atacama','ALTO DEL CARMEN','Servicio Local'),
('40341','ESCUELA ESPECIAL DE LENGUAJE SEMILLITAS','O''Higgins','RANCAGUA','Part. Subvencionado'),
('40342','ESCUELA ESPEC. DE LENGUAJE REY CARLOS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40343','COLEGIO CREACION LA ARAUCANA PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40350','JARDIN INFANTIL BARQUILLO','Coquimbo','LA SERENA','Part. Pagado'),
('40351','COLEGIO BOSQUEMAR','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40352','LICEO TEC.PROFESIONAL PEDRO AGUIRRE CERDA','Valparaíso','CALLE LARGA','Corp. Municipal'),
('40353','ESCUELA ESPECIAL DE LENGUAJE SAN ENRIQUE','O''Higgins','CHIMBARONGO','Part. Subvencionado'),
('40354','MONTESSORI','Coquimbo','LA SERENA','Part. Pagado'),
('40359','ESCUELA ESPECIAL DE LENGUAJE SANTA CRUZ','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('40360','ESCUELA ESPECIAL MI MUNDO','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('40362','JARDIN INFANTIL REMOLINO','Valparaíso','LOS ANDES','Part. Subvencionado'),
('40365','ESCUELA ESPECIAL DE LENGUAJE ANTIHUAL','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40366','ESCUELA ESPECIAL DE LENGUAJE PALABRITAS','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40367','ESCUELA ESPECIAL DE LENGUAJE ARREBOL','Valparaíso','LA LIGUA','Part. Subvencionado'),
('40368','ESC ESP DE LENG SENDERO DEL SABER','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40369','ESCUELA AMANECER','Los Lagos','CHONCHI','Servicio Local'),
('40370','COLEGIO PUKALAN DE ALGARROBO','Valparaíso','ALGARROBO','Part. Subvencionado'),
('40371','COLEGIO SAN CARLOS DE LAS CABRAS','O''Higgins','LAS CABRAS','Part. Subvencionado'),
('40372','ESCUELA ESPECIAL DE LENJUAJE BAMBOO','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40374','COLEGIO ESPECIAL ESTRELLA DE LUZ','Valparaíso','LIMACHE','Part. Subvencionado'),
('40377','ESC ESP DE LENGUAJE GOTITAS DE ROCIO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40378','ESC.ESPEC.DE LENGUAJE EDUCATEL PLACERES','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40379','ESC.ESPEC.DE LENGUAJE PEQUEÑOS REYES','Valparaíso','CALERA','Part. Subvencionado'),
('40380','ESCUELA ESPECIAL DE LENGUAJE BETEL','Los Lagos','OSORNO','Part. Subvencionado'),
('40381','COLEGIO ACONCAGUA EDUCA','Valparaíso','PUTAENDO','Part. Subvencionado'),
('40382','ESCUELA ESPECIAL DE LENGUAJE ARTELIN','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40383','ESCUELA BASICA MIL PAISAJES-QUEMCHI','Los Lagos','QUEMCHI','Servicio Local'),
('40384','ESCUELA ESPECIAL DE LENGUAJE MATEITO´S','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40385','ESCUELA ESPECIAL DE LENGUAJE SOL Y LUNA','Valparaíso','NOGALES','Part. Subvencionado'),
('40386','ESC.ESPEC.DE LENGUAJE EXPLORA AMANCAY','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40387','JARDIN INFANTIL Y SALACUNA MI PEQUEÑO GENIO','Arica y Parinacota','ARICA','Part. Pagado'),
('40388','ESCUELA ESPECIAL DE LENGUAJE MATISSE','Los Lagos','PUYEHUE','Part. Subvencionado'),
('40390','ESCUELA HOSPITALARIA ALIANZA','Los Lagos','OSORNO','Part. Subvencionado'),
('40391','ESCUELA ESPECIAL DE LENGUAJE VICENTE HUIDOBRO','Coquimbo','OVALLE','Part. Subvencionado'),
('40393','SCUOLA ITALIANA ARTURO DELL´ ORO VIÑA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('40394','ESC.ESP.TRAST.DE LA COMUNICACIÓN HIRONDELLE','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('40395','COLEGIO JOHN WALL HOLCOMB','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40397','ESCUELA ESPECIAL DE LENGUAJE EDUCA INFANCIA','Coquimbo','OVALLE','Part. Subvencionado'),
('40398','ESCUELA ESPECIAL DE LENGUAJE MATICES','Coquimbo','OVALLE','Part. Subvencionado'),
('40399','COLEGIO NAZARET','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40400','CENTRO DE EDUCACION INTEGRAL DE ADULTOS SANTA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('40401','ESC ESP DE LENGUAJE EL DESPERTAR','Arica y Parinacota','ARICA','Part. Subvencionado'),
('40403','GREEN PARK SCHOOL','Los Lagos','OSORNO','Part. Subvencionado'),
('40405','ESCUELA DE LENGUAJE HAPPY DAY','Coquimbo','LA SERENA','Part. Subvencionado'),
('40406','COLEGIO MADRE ISABEL LARRAÑAGA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40407','CENTRO DE ESTUDIOS BORDEMAR','Valparaíso','CALERA','Part. Subvencionado'),
('40409','COLEGIO INTERCULTURAL LEONARDO DA VINCI','Valparaíso','CASABLANCA','Part. Subvencionado'),
('40410','ESCUELA ESPECIAL EL OLIVILLO','Atacama','VALLENAR','Part. Subvencionado'),
('40412','ESC. ESP. DE LENGUAJE PEQUEÑO PARLANCHIN','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40413','ESC.ESP.DE LENGUAJE Y J.INFANTIL CARITAS','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('40414','CENTRO EDUC.DE INTEGRAC.DE ADULTOS NEWEN','Valparaíso','CARTAGENA','Part. Subvencionado'),
('40415','ESCUELA ESPECIAL DE LENGUAJE DE COLORES','Atacama','COPIAPÓ','Part. Subvencionado'),
('40416','JARDIN INFANTIL MATIAS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40417','ESCUELA DE LENGUAJE ANGELUZ','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40418','RICHMOND SCHOOL OSORNO','Los Lagos','OSORNO','Part. Subvencionado'),
('40419','ESCUELA ESPECIAL DE LENGUAJE ARCA DE NOÉ','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40420','ESCUELA DE LENGUAJE NUBE Y SOL','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40422','COLEGIO NIRVANA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('40423','COLEGIO SAN JUAN','Los Lagos','ANCUD','Part. Subvencionado'),
('40424','CENTRO EDUCACIONAL RAICES DE MI TIERRA','Los Lagos','DALCAHUE','Part. Subvencionado'),
('40427','CENTRO DE INTERVENCION DE NECESIDADES EDUCATIVAS ESPECIALES DE PURRANQUE','Los Lagos','PURRANQUE','Part. Subvencionado'),
('40428','ESCUELA ESPECIAL LENGUAJE ARBOLITO DEL SABER','Los Lagos','FRESIA','Part. Subvencionado'),
('40429','LICEO TECNICO PROFESIONAL DE ADULTOS','Tarapacá','IQUIQUE','Servicio Local'),
('40430','JARDIN INFANTIL ALEXANDER FLEMING','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40432','JARDÍN INFANTIL AKANKE','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40433','ESCUELA ESPECIAL ALMENAR','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('40434','JARDIN INFANTIL AVANT GARDE','Valparaíso','QUILPUÉ','Part. Pagado'),
('40435','INSTITUTO DE ESTUDIOS IBERO CHILE','Valparaíso','QUILPUÉ','Part. Pagado'),
('40436','COLEGIO BETHEL','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('40438','JARDIN INFANTIL Y SALA CUNA REINO DE PAPEL','Los Lagos','PUERTO MONTT','Part. Pagado'),
('40444','ESCUELA ESPECIAL DE LENGUAJE SEMILLITAS DE ALERCE','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40445','ESCUELA ESPECIAL DE LENGUAJE VAINILLA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40447','CENTRO DE EDUCACION INTEGRADA DE ADULTOS AEK','Los Lagos','CALBUCO','Part. Subvencionado'),
('40451','ESCUELA ESPECIAL DE LENGUAJE CUNCUNITA','Los Lagos','PUERTO MONTT','Part. Subvencionado'),
('40452','ESCUELA ESPECIAL DE LENGUAJE PAIHUEN','Los Lagos','OSORNO','Part. Subvencionado'),
('40453','ESCUELA ESPECIAL DE LENGUAJE MANQUEHUE','Los Lagos','CALBUCO','Part. Subvencionado'),
('40457','LICEO TECNICO PROFESIONAL PABLO NERUDA','Los Lagos','CASTRO','Part. Subvencionado'),
('40458','ESCUELA DE LENGUAJE MOMENTOS PRECIOSOS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('40459','CENTRO EDUCACIONAL ALBORADA','Los Lagos','ANCUD','Part. Subvencionado'),
('41004','SALA CUNA Y JARDIN INFANTIL SMILE GARDEN','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41005','JARDIN INFANTIL Y SALA CUNA BIG HOUSE','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41006','SALA CUNA Y JARDIN INFANTIL CAPULLITOS','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('41009','COLEGIO COSTA CORDILLERA','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('41015','SALA CUNA Y JARDÍN INFANTIL SÚPER KIDS','Metropolitana','MELIPILLA','Part. Pagado'),
('41016','SALA CUNA Y JARDIN INFANTIL CHILDREN`S WORLD','Coquimbo','LA SERENA','Part. Pagado'),
('41017','ESCUELA ESPECIAL DE LENGUAJE SANTINO','Coquimbo','LA SERENA','Part. Subvencionado'),
('41018','COLEGIO CONQUISTADORES COQUIMBO','Coquimbo','COQUIMBO','Part. Pagado'),
('41024','ESCUELA ESPECIAL DE LENGUAJE CUMBRES DE HUEPIL','Biobío','TUCAPEL','Part. Subvencionado'),
('41045','JARDIN INFANTIL Y SALA CUNA DUENDECITOS','Metropolitana','LAS CONDES','Part. Pagado'),
('41057','SALA CUNA ENTREPEQUES','Los Lagos','QUEMCHI','Part. Pagado'),
('41058','SALA CUNA Y JARDÍN INFANTIL ALERCE','Metropolitana','LA FLORIDA','Part. Pagado'),
('41062','SALA CUNA Y JARDIN INFANTIL PACHAKUTI','Tarapacá','IQUIQUE','Part. Pagado'),
('41063','AULA HOSPITALARIA DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('41069','SALA CUNA Y JARDÍN INFANTIL TARUCA','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41077','JARDÍN INFANTIL Y SALA CUNA QUICO','Metropolitana','QUINTA NORMAL','Part. Pagado'),
('41079','SALA CUNA Y JARDÍN INFANTIL PEQUEÑO DUMBITO','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41080','JARDÍN INFANTIL LOS EXPLORADORES','Metropolitana','LAS CONDES','Part. Pagado'),
('41081','CENTRO VITAMINA MUJICA','O''Higgins','RANCAGUA','Part. Pagado'),
('41099','COLEGIO DE JÓVENES Y ADULTOS OSSANDÓN','Coquimbo','COQUIMBO','Part. Subvencionado'),
('41109','ESCUELA INTERNACIONAL DE LIDERES CORONEL SANTIAGO BUERAS Y AVARIA','Metropolitana','MAIPÚ','Part. Pagado'),
('41117','LYCÉE FRÉDÉRIC MISTRAL','Coquimbo','LA SERENA','Part. Pagado'),
('41124','COLEGIO PARTICULAR SUBVENCIONADO EDUARDO GALEANO','Maule','TALCA','Part. Subvencionado'),
('41127','ESCUELA DE LENGUAJE AMANCAY','Maule','TALCA','Part. Subvencionado'),
('41129','COLEGIO TALHUEN','Maule','MAULE','Part. Subvencionado'),
('41130','SALA CUNA Y JARDÍN INFANTIL CELESTE','Metropolitana','LA CISTERNA','Part. Pagado'),
('41132','SALA CUNA Y JARDIN INFANTIL RAYÜN','Coquimbo','COQUIMBO','Part. Subvencionado'),
('41135','COLEGIO INSTITUTO DE CIENCIAS Y TECNOLOGÍA TALAGANTE','Metropolitana','TALAGANTE','Part. Subvencionado'),
('41142','JARDÍN INFANTIL MONTT','Metropolitana','RECOLETA','Part. Pagado'),
('41143','SALA CUNA Y JARDÍN INFANTIL LAS CAMPANITAS','Metropolitana','QUILICURA','Part. Pagado'),
('41149','SALA CUNA Y JARDIN INFANTIL AMANCAY','Los Lagos','PUERTO MONTT','Part. Pagado'),
('41152','CENTRO VITAMINA CONCHA Y TORO','Metropolitana','PUENTE ALTO','Part. Pagado'),
('41153','CENTRO VITAMINA AHUMADA','Metropolitana','SANTIAGO','Part. Pagado'),
('41155','CENTRO VITAMINA LA CONCEPCION','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41156','CENTRO VITAMINA CIUDAD SATELITE','Metropolitana','MAIPÚ','Part. Pagado'),
('41157','CENTRO VITAMINA SANTA AMALIA','Metropolitana','LA FLORIDA','Part. Pagado'),
('41158','JARDÍN INFANTIL ANTILCO MONTESSORI','Metropolitana','SAN MIGUEL','Part. Pagado'),
('41161','SALA CUNA Y JARDÍN INFANTIL OLITAS DE MAR','Metropolitana','QUINTA NORMAL','Part. Pagado'),
('41162','CENTRO VITAMINA NUEVA COSTANERA','Metropolitana','VITACURA','Part. Pagado'),
('41163','CENTRO VITAMINA AMUNATEGUI','Metropolitana','SANTIAGO','Part. Pagado'),
('41164','VITAMINA JOHN JACKSON','Metropolitana','LA REINA','Part. Pagado'),
('41165','CENTRO VITAMINA SAZIE','Metropolitana','SANTIAGO','Part. Pagado'),
('41167','CENTRO VITAMINA FLOR DE AZUCENAS','Metropolitana','LAS CONDES','Part. Pagado'),
('41169','CENTRO VITAMINA PASEO BULNES','Metropolitana','SANTIAGO','Part. Pagado'),
('41170','CENTRO VITAMINA ALSACIA','Metropolitana','LAS CONDES','Part. Pagado'),
('41172','SALA CUNA Y JARDÍN INFANTIL TOMMY`S GARDEN','Metropolitana','MAIPÚ','Part. Pagado'),
('41173','CEIA LIBRE SER MISTRALIANO','Coquimbo','PAIGUANO','Part. Subvencionado'),
('41175','JARDÍN INFANTIL Y SALA CUNA COLIBRÍ','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41179','ESCUELA ESPECIAL DE LENGUAJE IWOKA','Coquimbo','OVALLE','Part. Subvencionado'),
('41194','JARDÍN INFANTIL Y SALA CUNA VALLE ENCANTADO','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('41195','SALA CUNA Y JARDÍN INFANTIL AYLLÚ KIDS','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41198','ESCUELA DE PARVULOS Nº2493 JARDÍN INFANTIL LEHIBOU','Metropolitana','COLINA','Part. Pagado'),
('41208','CORPORACION EDUCACIONAL JAYDIE LIMITADA','Antofagasta','ANTOFAGASTA','Part. Pagado'),
('41228','SALA CUNA Y JARDÍN INFANTIL FANTASIA MUSICAL','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41239','JARDIN INFANTIL PEQUEÑOS EXPLORADORES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('41240','JARDÍN INFANTIL Y SALA CUNA MI INFANCIA','Metropolitana','ÑUÑOA','Part. Pagado'),
('41241','SALA CUNA Y JARDÍN INFANTIL GREEN GARDEN','Metropolitana','PUDAHUEL','Part. Pagado'),
('41245','SALA CUNA LARA PINTA EL SOL','Metropolitana','LAMPA','Part. Pagado'),
('41251','SALA CUNA Y JARDIN INFANTIL HANSEL Y GRETEL','Los Ríos','VALDIVIA','Part. Pagado'),
('41254','JARDIN INFANTIL SUEÑO AZUL Y SUS PEQUEÑITOS','Coquimbo','LA SERENA','Part. Pagado'),
('41257','JARDÍN INFANTIL TOPOLINO','Metropolitana','ÑUÑOA','Part. Pagado'),
('41261','SALA CUNA Y JARDÍN INFANTIL LOS DUENDECITOS','Metropolitana','LO BARNECHEA','Part. Pagado'),
('41262','JARDÍN INFANTIL Y SALA CUNA ESPIGUITA','Los Lagos','OSORNO','Part. Pagado'),
('41264','COLEGIO EL ROBLE','Metropolitana','ÑUÑOA','Part. Pagado'),
('41272','SALA CUNA PASO A PASO','Metropolitana','PAINE','Part. Pagado'),
('41273','JARDIN INFANTIL PUMANQUE','Metropolitana','LAS CONDES','Part. Pagado'),
('41274','ESCUELA CARCEL CARLOS ALVEAL MUÑOZ','La Araucanía','COLLIPULLI','Corp. Municipal'),
('41276','JARDIN INFANTIL Y SALA CUNA POLILLITA DEL DESIERTO','Tarapacá','IQUIQUE','Part. Pagado'),
('41280','ESCUELA ESPECIAL DIFERENCIAL E INSTITUTO DE ESTIMULACIÓN TEMPRANA SAN MARCELINO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('41281','JARDIN INFANTIL Y SALA CUNA MI MUNDO CREATIVO','Valparaíso','CASABLANCA','Part. Pagado'),
('41282','SALA CUNA Y JARDIN INFANTIL DIENTECITO DE LECHE','Los Lagos','PUERTO MONTT','Part. Pagado'),
('41284','SALA CUNA Y JARDÍN INFANTIL DIENTECITO DE LECHE','Los Lagos','PUERTO VARAS','Part. Pagado'),
('41285','JARDIN INFANTIL ARCOIRIS DEL HOSPITAL REGIONAL','O''Higgins','RANCAGUA','Part. Pagado'),
('41291','SALA CUNA Y JARDÍN INFANTIL ENTRENIÑOS','Metropolitana','CERRILLOS','Part. Pagado'),
('41293','JARDIN INFANTIL PULGARCITO 2','Metropolitana','LA GRANJA','Part. Pagado'),
('41295','ESCUELA DEL CARIÑO IX','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('41296','CENTRO VITAMINA QUILICURA','Metropolitana','QUILICURA','Part. Pagado'),
('41298','JARDIN INFANTIL PALOMITAS DE MAIZ','Metropolitana','PUDAHUEL','Part. Pagado'),
('41301','JARDIN INFANTIL BURBUJITAS','Metropolitana','LO PRADO','Part. Pagado'),
('41303','JARDIN INFANTIL Y SALA CUNA MY GARDEN','Metropolitana','LO PRADO','Part. Pagado'),
('41306','JARDÍN INFANTIL Y SALA CUNA ALEXANDRIA','Los Lagos','OSORNO','Part. Pagado'),
('41307','JARDIN INFANTIL SANTA MONICA','Metropolitana','MELIPILLA','Part. Pagado'),
('41308','JARDIN INFANTIL ARBOL DE LOS SUEÑOS','Metropolitana','PADRE HURTADO','Part. Pagado'),
('41311','SALA CUNA Y JARDIN INFANTIL HUELLAS','Metropolitana','LAS CONDES','Part. Pagado'),
('41312','JARDÍN INFANTIL Y SALA CUNA PIN Y PON','Maule','CURICÓ','Part. Subvencionado'),
('41313','SALA CUNA Y JARDÍN INFANTIL MY LITTLE STAR','Metropolitana','LAS CONDES','Part. Pagado'),
('41317','JARDIN INFANTIL TREE HOUSE','La Araucanía','TEMUCO','Part. Pagado'),
('41331','JARDÍN INFANTIL SÍMOLI','Metropolitana','LAS CONDES','Part. Pagado'),
('41335','SALA CUNA Y JARDÍN INFANTIL KID`S PLACE','Metropolitana','SAN MIGUEL','Part. Pagado'),
('41338','JARDIN INFANTIL Y SALA CUNA VITAMINA PLAZA DE VIÑA','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('41339','SALA CUNA Y JARDIN INFANTIL KINETIN','Los Ríos','VALDIVIA','Part. Pagado'),
('41342','SALA CUNA Y JARDÍN INFANTIL ECO HOUSE GARDEN','Tarapacá','IQUIQUE','Part. Pagado'),
('41344','JARDIN INFANTIL Y SALA CUNA LA CASA DE LOS NIÑOS','Metropolitana','RECOLETA','Part. Pagado'),
('41346','JARDIN INFANTIL Y SALA CUNA RAYITO DE LUZ','Los Lagos','OSORNO','Part. Pagado'),
('41348','JARDÍN INFANTIL SONRISAS DE PUERTO MONTT','Los Lagos','PUERTO MONTT','Part. Pagado'),
('41349','AULA HOSPITALARIA HOSPITAL RANCAGUA','O''Higgins','RANCAGUA','Part. Subvencionado'),
('41352','SALA CUNA NENITOS','Metropolitana','SANTIAGO','Part. Pagado'),
('41355','JARDIN INFANTIL Y SALA CUNA PINTA PAPELES','Metropolitana','LAS CONDES','Part. Pagado'),
('41356','JARDIN INFANTIL BALOO','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('41357','COLEGIO CAMPOS DEL RANCO','Los Ríos','LA UNIÓN','Part. Pagado'),
('41358','SALA CUNA Y JARDÍN INFANTIL HAPPY PLACE','Magallanes','PUNTA ARENAS','Part. Pagado'),
('41359','JARDIN INFANTIL MIS PEQUEÑOS PENSANTES','Coquimbo','LA SERENA','Part. Pagado'),
('41360','SALA CUNA Y JARDÍN INFANTIL AILIN CREACIONES','Metropolitana','MACUL','Part. Pagado'),
('41366','JARDIN INFANTIL SUNNY KIDS','Metropolitana','LAS CONDES','Part. Pagado'),
('41367','SALA CUNA Y JARDÍN INFANTIL AMANCAY','Metropolitana','ÑUÑOA','Part. Pagado'),
('41374','COLEGIO DE ADULTOS RENACER','O''Higgins','PICHIDEGUA','Part. Subvencionado'),
('41375','CENTRO DE EDUCACIÓN DE ADULTOS (C.E.I.A.),`INSTITUTO POPULAR AYSÉN`','Aysén','COYHAIQUE','Part. Subvencionado'),
('41377','JARDÍN INFANTIL PEQUEÑOS COLONOS','Magallanes','CABO DE HORNOS','Part. Pagado'),
('41379','SALA CUNA Y JARDIN INFANTIL SOL Y LUNA','Arica y Parinacota','ARICA','Part. Pagado'),
('41382','JARDIN INFANTIL Y SALA CUNA SAN FRANCISCO DE ASIS','Tarapacá','IQUIQUE','Part. Pagado'),
('41383','SALA CUNA Y JARDIN INFANTIL PASITOS','Valparaíso','VALPARAÍSO','Part. Pagado'),
('41386','JARDÍN INFANTIL CREARE','La Araucanía','TEMUCO','Part. Pagado'),
('41396','SALA CUNA Y JARDIN INFANTIL HUMPTY DUMPTY','Metropolitana','LAS CONDES','Part. Pagado'),
('41401','CENTRO VITAMINA DOS ORIENTE','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('41404','JARDIN INFANTIL Y SALA CUNA MANUTARA','Tarapacá','IQUIQUE','Part. Pagado'),
('41407','JARDIN INFANTIL Y SALA CUNA PEÑABLANCA','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('41416','SALA CUNA Y JARDÍN INFANTIL REPOLLITOS','Metropolitana','ÑUÑOA','Part. Pagado'),
('41417','ESCUELA HOSPITALARIA DE ANGOL','La Araucanía','ANGOL','Part. Subvencionado'),
('41418','ESCUELA HOSPITALARIA DE VICTORIA','La Araucanía','VICTORIA','Part. Subvencionado'),
('41424','SALA CUNA Y JARDÍN INFANTIL MANITOS MÁGICAS','Biobío','CONCEPCIÓN','Part. Pagado'),
('41432','JARDIN  INFANTIL Y SALA CUNA EL LIMONERO','Valparaíso','RINCONADA','Part. Pagado'),
('41433','JARDIN INFANTIL Y SALA CUNA TERRA LUZ','Valparaíso','ALGARROBO','Part. Pagado'),
('41435','SALA CUNA Y JARDÍN INFANTIL NUESTROS NIÑOS','Metropolitana','MACUL','Part. Pagado'),
('41439','COLEGIO PATAGONIA PUERTO VARAS','Los Lagos','PUERTO VARAS','Part. Pagado'),
('41442','SALA CUNA Y JARDIN INFANTIL CHARLIE BROWN ALVARES','Valparaíso','VALPARAÍSO','Part. Pagado'),
('41443','SALA CUNA Y JARDÍN INFANTIL PUENTE MAGICO','Metropolitana','LAS CONDES','Part. Pagado'),
('41444','ESCUELA ESPECIAL DE LENGUAJE NOTITAS MÁGICAS','Coquimbo','OVALLE','Part. Subvencionado'),
('41448','JARDIN INFANTIL CRECER','O''Higgins','RANCAGUA','Part. Pagado'),
('41451','SALA CUNA Y JARDÍN INFANTIL GIRASOL','Magallanes','PUNTA ARENAS','Part. Pagado'),
('41452','SALA CUNA OVEJITAS PATAGÓNICAS','Magallanes','NATALES','Part. Pagado'),
('41453','JARDÍN INFANTIL Y SALA CUNA TURRÓN','Magallanes','PUNTA ARENAS','Part. Pagado'),
('41454','THE SHEPHERD BILINGUAL SCHOOL','Magallanes','PUNTA ARENAS','Part. Pagado'),
('41456','SALA CUNA Y JARDIN INFANTIL LITTLE BEE COLLEGE','Metropolitana','SAN MIGUEL','Part. Pagado'),
('41458','CENTRO VITAMINA SUECIA','Metropolitana','ÑUÑOA','Part. Pagado'),
('41460','CENTRO VITAMINA PLAZA PUENTE ALTO','Metropolitana','PUENTE ALTO','Part. Pagado'),
('41461','SALA CUNA Y JARDÍN INFANTIL LA CASA DEL ÁRBOL','Magallanes','PUNTA ARENAS','Part. Pagado'),
('41465','SALA CUNA Y JARDIN INFANTIL APAPACHO','Valparaíso','LOS ANDES','Part. Pagado'),
('41472','ESCUELA ESPECIAL DE LENGUAJE EL TRENCITO DE DORA','Los Lagos','SAN PABLO','Part. Subvencionado'),
('41473','JARDIN INFANTIL Y SALA CUNA FROEN','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('41479','JARDIN INFANTIL GIRASOL','Valparaíso','VALPARAÍSO','Part. Pagado'),
('41480','SALA CUNA LIMONADA','Maule','TALCA','Part. Pagado'),
('41484','CENTRO VITAMINA PEÑALOLEN','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('41485','CENTRO VITAMINA SANTA MARTA HUECHURABA','Metropolitana','HUECHURABA','Part. Pagado'),
('41486','CENTRO VITAMINA  PAJARITOS','Metropolitana','MAIPÚ','Part. Pagado'),
('41487','SALA CUNA Y JARDÍN INFANTIL DULCE AVENTURA','Metropolitana','MAIPÚ','Part. Pagado'),
('41488','ESCUELA ESPECIAL SEMILLITAS DEL VALLE','Metropolitana','LAMPA','Part. Subvencionado'),
('41495','JARDIN INFANTIL Y SALA CUNA NATGIO','Valparaíso','QUILPUÉ','Part. Pagado'),
('41497','JARDIN INFANTIL Y SALA CUNA KIPU','Metropolitana','PROVIDENCIA','Part. Pagado'),
('41498','BARQUITO DE PAPEL SPA','Los Lagos','OSORNO','Part. Pagado'),
('41503','ESCUELA ESPECIAL DE LENGUAJE EL UNIVERSO EN LA NUEZ','Coquimbo','COQUIMBO','Part. Subvencionado'),
('41504','ESCUELA ESPECIAL DE LENGUAJE  ARCOÍRIS DE PALABRAS','Coquimbo','COQUIMBO','Part. Subvencionado'),
('41505','JARDIN INFANTIL RUCALEM','Tarapacá','IQUIQUE','Part. Pagado'),
('41506','SALA CUNA UMBRAL','Metropolitana','LA GRANJA','Part. Pagado'),
('41510','COLEGIO EVERGREEN DE LA LIGUA','Valparaíso','LA LIGUA','Part. Pagado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
