-- Import colegios 2025 en partes (SQL Editor friendly)
-- Parte 17 de 31 | filas 6401-6800
begin;
insert into public.colegios (rbd, nombre, region, comuna, tipo)
values
('11035','COLEGIO AMBROSIO O HIGGINS','Atacama','VALLENAR','Part. Pagado'),
('11036','ESCUELA JOSÉ JOAQUÍN VALLEJOS','Atacama','CALDERA','Servicio Local'),
('11038','LICEO GENERAL RAMÓN FREIRE','Atacama','FREIRINA','Servicio Local'),
('11103','COLEGIO LOS CARRERA SPA','Coquimbo','COQUIMBO','Part. Pagado'),
('11105','LICEO BICENTENARIO DE EXCELENCIA COLEGIO PARTICULAR MIGUEL DE CERVANTES','Coquimbo','COQUIMBO','Part. Subvencionado'),
('11106','COLEGIO PARTICULAR SANTA MARIA','Coquimbo','OVALLE','Part. Subvencionado'),
('11107','COLEGIO PART.SANTA TERESA DE JESUS','Coquimbo','OVALLE','Part. Pagado'),
('11110','LICEO JORGE IRIBARREN CHARLIN DE HURTADO','Coquimbo','RÍO HURTADO','Corp. Municipal'),
('11111','LICEO ALBERTO GALLARDO LORCA','Coquimbo','PUNITAQUI','Corp. Municipal'),
('11113','BASICA COMUN DELIA ANDRADE DE TELLO','Coquimbo','OVALLE','Corp. Municipal'),
('11114','COLEGIO NUEVO MUNDO','Coquimbo','LA SERENA','Part. Subvencionado'),
('11116','JARDIN INFANTIL LAS ABEJITAS','Coquimbo','LA SERENA','Part. Pagado'),
('11117','JARDIN INFANTIL EL SOLDADITO','Coquimbo','LA SERENA','Part. Pagado'),
('11120','JARDIN INFANTIL CARRUSEL','Coquimbo','COQUIMBO','Part. Pagado'),
('11122','JARDIN INFANTIL DEL HOSPITAL DE COQUIMBO','Coquimbo','COQUIMBO','Part. Pagado'),
('11127','JARDIN INFANTIL TOÑITO','Coquimbo','OVALLE','Part. Pagado'),
('11130','COLEGIO SAN IGNACIO DE LOYOLA','Coquimbo','ILLAPEL','Part. Subvencionado'),
('11133','COLEGIO PARTICULAR SAN GABRIEL','Coquimbo','COQUIMBO','Part. Subvencionado'),
('11136','COLEGIO SAN ALBERTO HURTADO CRUCHAGA','Coquimbo','OVALLE','Corp. Municipal'),
('11138','JARDIN INFANTIL PILLIN','Coquimbo','LA SERENA','Part. Pagado'),
('11139','LICEO FERNANDO BINVIGNAT MARIN','Coquimbo','COQUIMBO','Servicio Local'),
('11144','ESCUELA DIEGO DE ALMEYDA','Coquimbo','COQUIMBO','Part. Subvencionado'),
('11145','COLEGIO PARTICULAR CALASANZ','Coquimbo','COQUIMBO','Part. Subvencionado'),
('11147','COLEGIO MANANTIAL','Coquimbo','ILLAPEL','Part. Subvencionado'),
('11153','ESCUELA LA PARRITA','Coquimbo','CANELA','Corp. Municipal'),
('11155','LICEO JORGE ALESSANDRI RODRIGUEZ','Coquimbo','LA SERENA','Servicio Local'),
('11156','CENTRO DE DETENCION PREVENTIVA','Coquimbo','ILLAPEL','Corp. Municipal'),
('11157','COLEGIO LIBERTADOR SIMON BOLIVAR','Coquimbo','LA SERENA','Part. Subvencionado'),
('11176','COLEGIO CHAMPAGNAT','Valparaíso','VILLA ALEMANA','Part. Pagado'),
('11177','COLEGIO PARROQUIAL SAN NICOLAS','Valparaíso','HIJUELAS','Part. Subvencionado'),
('11178','CENTRO EDUCACIONAL CENINES','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('11180','ESC. DE PARVULOS LA PEQUEÑA POLITA','Valparaíso','QUILLOTA','Part. Subvencionado'),
('11188','JARDIN INFANTIL BURBUJAS','Valparaíso','VALPARAÍSO','Part. Pagado'),
('11191','ESCUELA PEDRO NOLASCO MOLINA','Valparaíso','SAN FELIPE','Corp. Municipal'),
('11196','CTRO.REC.ATENC.DIVERS.CRAD PAUL PERCY HARRIS','Valparaíso','CABILDO','Corp. Municipal'),
('11199','COLEGIO LUIS CRUZ MARTINEZ','Valparaíso','LA LIGUA','Corp. Municipal'),
('11200','ESCUELA PADRE ALBERTO HURTADO','Valparaíso','SANTO DOMINGO','Corp. Municipal'),
('11201','BRITISH SCHOOL SAN ANTONIO','Valparaíso','SAN ANTONIO','Part. Subvencionado'),
('11203','COLEGIO PARTICULAR CLAUDIO GAY','Valparaíso','LOS ANDES','Part. Subvencionado'),
('11205','CENTRO EDUC.ESPECIAL ANN SULLIVAN','Valparaíso','QUINTERO','Part. Subvencionado'),
('11206','ESCUELA MUNICIPAL LAS PUERTAS','Valparaíso','CABILDO','Corp. Municipal'),
('11209','COLEGIO GALILEO GALILEI','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('11217','COLEGIO SAINT THOMAS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('11220','COLEGIO LUIS GALDAMEZ','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('11221','JARDIN INFANTIL PILLIN HOSP  SALVADOR','Valparaíso','VALPARAÍSO','Part. Pagado'),
('11223','COLEGIO ITALIANO','Valparaíso','LIMACHE','Part. Subvencionado'),
('11224','COLEGIO PARTICULAR BECARB','Valparaíso','CALERA','Part. Subvencionado'),
('11230','COLEGIO DE ADULTOS PROFESOR MANUEL GUERRERO CEBALLOS','Valparaíso','QUILLOTA','Corp. Municipal'),
('11231','ESCUELA DE ADULTOS','Valparaíso','LIMACHE','Corp. Municipal'),
('11234','ESCUELA JOSÉ DOMINGO SAAVEDRA','Valparaíso','SAN ANTONIO','Corp. Municipal'),
('11237','COLEGIO ALEMAN DE SAN FELIPE','Valparaíso','PANQUEHUE','Part. Pagado'),
('11238','ESCUELA DE PARVULOS LOS ALMENDROS','Valparaíso','SAN FELIPE','Part. Pagado'),
('11240','ESCUELA SAN GABRIEL DE LA RIVERA','Valparaíso','CALERA','Part. Subvencionado'),
('11242','COLEGIO EL COBRE DE LOS ANDES','O''Higgins','RANCAGUA','Part. Subvencionado'),
('11244','COLEGIO MUNDO INFANTIL','O''Higgins','RANCAGUA','Part. Pagado'),
('11245','COL.EDUC. ESPECIAL DR. ALBERT SCHWEITZER','O''Higgins','REQUÍNOA','Corp. Municipal'),
('11246','LICEO ELISA ESCOBEDO LA PAZ','O''Higgins','RENGO','Corp. Municipal'),
('11248','ESC. ADRIANA ARANGUIZ CERDA','O''Higgins','SAN VICENTE','Municipal'),
('11256','COLEGIO PARTICULAR SUBV.DON BOSCO','O''Higgins','RANCAGUA','Part. Subvencionado'),
('11257','ESCUELA MUNICIPAL DE COLHUE','O''Higgins','PUMANQUE','Corp. Municipal'),
('11261','ESCUELA DIGNA CAMILO','O''Higgins','PICHILEMU','Corp. Municipal'),
('11263','CENTRO PARVULARIO DE CHIMBARONGO','O''Higgins','CHIMBARONGO','Servicio Local'),
('11265','COLEGIO ENA BELLEMANS MONTTI','O''Higgins','RANCAGUA','Part. Subvencionado'),
('11277','ESCUELA GABRIELA MISTRAL','O''Higgins','MOSTAZAL','Corp. Municipal'),
('11279','ESCUELA ANGEL MARIA','O''Higgins','CHÉPICA','Corp. Municipal'),
('11283','ESCUELA CARDONAL PANILONCO','O''Higgins','PICHILEMU','Corp. Municipal'),
('11284','CENTRO DE EDUCACION DE ADULTOS','O''Higgins','RANCAGUA','Municipal'),
('11286','LICEO HERIBERTO SOTO SOTO','O''Higgins','SAN FERNANDO','Servicio Local'),
('11287','LICEO BERTA ZAMORANO LIZANA','O''Higgins','COLTAUCO','Corp. Municipal'),
('11291','VILLA MARIA COLLEGE','O''Higgins','MACHALÍ','Part. Pagado'),
('11318','ESCUELA DIFERENCIAL SANTA ADRIANA','Maule','PARRAL','Part. Subvencionado'),
('11323','ESCUELA REINO DE DINAMARCA','Maule','MOLINA','Corp. Municipal'),
('11330','ESCUELA DIFERENCIAL SAN CLEMENTE','Maule','SAN CLEMENTE','Corp. Municipal'),
('11333','ESCUELA OSVALDO HIRIART CORVALAN','Maule','PENCAHUE','Corp. Municipal'),
('11334','ESCUELA HUAPI ALTO','Maule','LINARES','Corp. Municipal'),
('11336','COLEGIO PARTICULAR NOBEL SCHOOL','Maule','PARRAL','Part. Subvencionado'),
('11337','CENTRO DE EDUCACION INTEGRADA DE ADULTOS','Maule','SAN JAVIER','Corp. Municipal'),
('11338','ESCUELA DIFERENCIAL ESPERANZA','Maule','MOLINA','Corp. Municipal'),
('11339','ESCUELA SAN ANTONIO','Maule','TALCA','Part. Subvencionado'),
('11342','ESCUELA CARLOS TRUPP WANNER','Maule','TALCA','Corp. Municipal'),
('11343','COLEGIO NUEVA HOLANDA','Maule','TALCA','Part. Subvencionado'),
('11344','INSTITUTO JAVIERA CARRERA DE LINARES','Maule','LINARES','Part. Subvencionado'),
('11347','ESCUELA DE PARVULOS SAN CLEMENTE','Maule','SAN CLEMENTE','Corp. Municipal'),
('11348','COLEGIO DE MARIA','Maule','TALCA','Part. Subvencionado'),
('11350','ESCUELA ESPECIAL BELLAVISTA','Maule','TENO','Part. Subvencionado'),
('11352','ESCUELA EL GUINDO','Maule','TENO','Corp. Municipal'),
('11394','ESCUELA GABRIELA MISTRAL','Biobío','TOMÉ','Corp. Municipal'),
('11395','ESCUELA BASICA LLOICURA','Biobío','TOMÉ','Corp. Municipal'),
('11397','COLEGIO ADVENTISTA','Biobío','LOTA','Part. Subvencionado'),
('11398','ESCUELA MAULE','Biobío','CORONEL','Servicio Local'),
('11399','ESCUELA SAN ERNESTO','Biobío','CONTULMO','Corp. Municipal'),
('11400','LICEO TRAPAQUEANTE','Biobío','TIRÚA','Corp. Municipal'),
('11401','ESCUELA ESPECIAL CONSTITUCION','Ñuble','CHILLÁN','Part. Subvencionado'),
('11404','ESCUELA SAN LUIS','Ñuble','YUNGAY','Corp. Municipal'),
('11405','ESCUELA FERNANDO BAQUEDANO','Ñuble','YUNGAY','Corp. Municipal'),
('11406','ESCUELA BÁSICA Y TECNOLÓGICA DIFERENCIAL LAURA VICUÑA','Ñuble','BULNES','Corp. Municipal'),
('11407','ESCUELA BASICA LOS OLIVOS','Ñuble','RANQUIL','Corp. Municipal'),
('11408','ESCUELA PARTICULAR SANTA PILAR','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('11414','ESCUELA MIGUEL DE CERVANTES','Biobío','CHIGUAYANTE','Part. Subvencionado'),
('11415','THE AUKLAND SCHOOL','Biobío','CONCEPCIÓN','Part. Pagado'),
('11417','ESCUELA ADULTOS LAS AMERICAS','Biobío','TALCAHUANO','Corp. Municipal'),
('11418','ESCUELA LOS QUIQUES','Biobío','SANTA JUANA','Servicio Local'),
('11419','ESCUELA COLICO BAJO','Biobío','SANTA JUANA','Corp. Municipal'),
('11420','COLEGIO METODISTA LAGUNILLAS','Biobío','CORONEL','Part. Subvencionado'),
('11425','ESCUELA CIFUENTES BAJO','Biobío','CURANILAHUE','Corp. Municipal'),
('11429','COLEGIO ALIWEN','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('11430','COLEGIO TERESIANO PADRE ENRIQUE','Biobío','NACIMIENTO','Part. Subvencionado'),
('11431','ESCUELA DIFERENCIAL MARIA MONTESSORI','Biobío','HUALPÉN','Part. Subvencionado'),
('11462','ESCUELA COLONIA RAYEN-LAFQUEN','La Araucanía','VILLARRICA','Corp. Municipal'),
('11465','COLEGIO LATINOAMERICANO','La Araucanía','TEMUCO','Part. Subvencionado'),
('11467','ESCUELA PARTICULAR VILCUN','La Araucanía','VILCÚN','Part. Subvencionado'),
('11471','ESCUELA PARTICULAR FOLILCO','La Araucanía','FREIRE','Part. Subvencionado'),
('11472','ESCUELA ARAUCARIAS','La Araucanía','LONCOCHE','Corp. Municipal'),
('11498','COMPLEJO EDUCACIONAL PRINCIPE DE GALES','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('11501','COLEGIO RAKIDUAM','La Araucanía','VILLARRICA','Part. Subvencionado'),
('11509','ESCUELA BASICA SAN SEBASTIAN DE MAQUEHUE','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('11520','ESCUELA ESPECIAL AYELEN','La Araucanía','LAUTARO','Corp. Municipal'),
('11522','ESCUELAS BASICA RENICO GRANDE','La Araucanía','LUMACO','Corp. Municipal'),
('11526','ESCUELA PARTICULAR HUALAPULLI','La Araucanía','VILLARRICA','Part. Subvencionado'),
('11527','LICEO POLITECNICO METODISTA LA GRANJA','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('11528','ESCUELA PARTICULAR SANTA ELENA','La Araucanía','NUEVA IMPERIAL','Part. Subvencionado'),
('11529','ESCUELA ESPECIAL LOS CANELOS','La Araucanía','ANGOL','Part. Subvencionado'),
('11530','ESCUELA ESPEC.RETARDO MENTAL AMMILLAN','La Araucanía','PITRUFQUÉN','Corp. Municipal'),
('11532','ESCUELA PARTICULAR LUIS ISRAEL','La Araucanía','PADRE LAS CASAS','Part. Subvencionado'),
('11539','ESCUELA RURAL DOMINGO FAUSTINO SARMIENTO','Los Lagos','CURACO DE VÉLEZ','Servicio Local'),
('11540','ESCUELA PARTICULAR ALEPUE','Los Ríos','MARIQUINA','Part. Subvencionado'),
('11542','ESCUELA PARTICULAR MELIQUINA','Los Ríos','MARIQUINA','Part. Subvencionado'),
('11543','ESCUELA PARTICULAR TRIPAYANTE','Los Ríos','MARIQUINA','Part. Subvencionado'),
('11544','ESCUELA PARTICULAR MISIONAL PELCHUQUIN','Los Ríos','MARIQUINA','Part. Subvencionado'),
('11547','ESCUELA PARTICULAR NOLGUEHUE','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('11548','ESCUELA CLAUDIO MATTE','Los Lagos','FRUTILLAR','Servicio Local'),
('11553','ESCUELA RURAL NALHUITAD','Los Lagos','CHONCHI','Servicio Local'),
('11554','ESCUELA DE ADULTOS DE RIO BUENO','Los Ríos','RÍO BUENO','Corp. Municipal'),
('11576','ESCUELA PARTICULAR N.290 LOS RADALES','Los Lagos','FRUTILLAR','Part. Subvencionado'),
('11577','ESCUELA ESPECIAL TALLER LABORAL MATICES','Los Lagos','OSORNO','Part. Subvencionado'),
('11578','ESCUELA PARTICULAR N.300 YUSTE','Los Lagos','ANCUD','Part. Subvencionado'),
('11582','ESCUELA PARTICULAR FOLLECO ALTO','Los Ríos','LA UNIÓN','Part. Subvencionado'),
('11590','ESCUELA RURAL SAN PEDRO','Los Lagos','DALCAHUE','Servicio Local'),
('11591','INSTITUTO TECNICO PROFESIONAL LLIFEN','Los Ríos','FUTRONO','Corp. Municipal'),
('11593','ESCUELA RURAL MARIA ENRIQUETA CHIGUAY CAIPILLAN','Los Lagos','QUELLÓN','Servicio Local'),
('11594','COLEGIO ANTILLANCA','Los Lagos','OSORNO','Part. Subvencionado'),
('11608','LICEO TECNICO PROFESIONAL JUAN PABLO II','Aysén','COYHAIQUE','Part. Subvencionado'),
('11609','ESCUELA MUNICIPAL MELIMOYU','Aysén','CISNES','Servicio Local'),
('11612','ESCUELA BASICA RIBERA SUR','Aysén','AYSÉN','Servicio Local'),
('11674','ESCUELA PARTICULAR CANICU','Biobío','ALTO BIOBÍO','Part. Subvencionado'),
('11675','ESCUELA ESPECIAL DE LENGUAJE CAMPANELLA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('11676','ESCUELA BASICA LA HUERTA','Biobío','SANTA JUANA','Servicio Local'),
('11677','ESCUELA ANDRES ALCAZAR','Biobío','LAJA','Corp. Municipal'),
('11678','LICEO ADVENTISTA','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('11680','COLEGIO CHARLES DARWIN','Magallanes','PUNTA ARENAS','Part. Subvencionado'),
('11681','COLEGIO MIGUEL DE CERVANTES','Magallanes','PUNTA ARENAS','Part. Pagado'),
('11685','SOCIEDAD EDUCACIONAL  LA ARAUCANA','Magallanes','PUNTA ARENAS','Part. Pagado'),
('11687','ESCUELA REPUBLICA ARGENTINA','Magallanes','PUNTA ARENAS','Servicio Local'),
('11704','ESCUELA PUERTA DE LA CORDILLERA','Ñuble','PINTO','Servicio Local'),
('11705','COLEGIO LOS EDUCADORES','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('11706','LICEO PARTICULAR LOS ANDES','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('11707','COLEGIO PARTICULAR NIÑO JESÚS','Biobío','LOTA','Part. Subvencionado'),
('11708','COLEGIO PARQUE CENTRAL','Biobío','HUALPÉN','Part. Subvencionado'),
('11709','COLEGIO ALERCE','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('11710','JARDIN INFANTIL EMANUEL','Biobío','CORONEL','Part. Subvencionado'),
('11711','ESCUELA LUIS MARTÍNEZ GONZÁLEZ','Biobío','TUCAPEL','Corp. Municipal'),
('11712','ESCUELA PARTICULAR GASPAR CABRALES','Biobío','LOS ÁLAMOS','Part. Subvencionado'),
('11714','ESCUELA CHACUIVI','Biobío','TIRÚA','Corp. Municipal'),
('11715','COLEGIO PARTICULAR ALBERTO BLEST GANA','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('11716','COLEGIO MARÍA INMACULADA DE LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('11718','ESCUELA PARTICULAR JUAN PABLO SEGUNDO','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('11719','ESCUELA PARTICULAR BIOBÍO DE LOS ÁNGELES','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('11739','ESCUELA PART.TRAPA TRAPA BUTALELBUM','Biobío','ALTO BIOBÍO','Part. Subvencionado'),
('11741','COLEGIO SAN ANDRÉS','Biobío','CONCEPCIÓN','Part. Subvencionado'),
('11743','COLEGIO BASICO LOS LOBOS','Biobío','TALCAHUANO','Corp. Municipal'),
('11744','ESCUELA CHILLAN VIEJO','Ñuble','CHILLÁN VIEJO','Part. Subvencionado'),
('11746','ESCUELA PARTICULAR LOS CONFINES','Biobío','CURANILAHUE','Part. Subvencionado'),
('11755','COLEGIO DE ADULTOS INSTITUTO LUISA CARDIJIN','Metropolitana','SANTIAGO','Part. Pagado'),
('11761','ESCUELA PARTICULAR SAN FELIPE NERI','Metropolitana','RECOLETA','Part. Subvencionado'),
('11766','COLEGIO INSTITUTO ARTÍSTICO DE ESTUDIOS SECUNDARIOS DE LA UNIVERSIDAD DE CHILE','Metropolitana','SANTIAGO','Part. Pagado'),
('11768','ESCUELA ESPECIAL PART RAYITO DE LUZ','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('11776','COLEGIO THE MAYFLOWER SCHOOL','Metropolitana','LO BARNECHEA','Part. Pagado'),
('11783','ESCUELA BASICA N°1238 GIORDANO BRUNO','Metropolitana','PEÑALOLÉN','Part. Pagado'),
('11788','ESCUELA ESPECIAL PARTICULAR LO HERMIDA','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('11789','ESCUELA BASICA PART.BROTHERS SCHOOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11791','ESC ESPECIAL NUESTRA SENORA DE LOURDES','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11792','LICEO PARTIC.ALBERTO MAGNO LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11793','ESC BASICA PARTICULAR SAN VALENTIN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11794','ESCUELA ESPECIAL PARTICULAR VARESCA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11795','COLEGIO SAN CARLOS DE LA FLORIDA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11797','ESC PARTICULAR MANUEL VICUNA LARRAIN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11800','ESCUELA ESPECIAL PARTICULAR LAS ROSAS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('11804','ESCUELA ESPECIAL NUEVA ALBORADA','Metropolitana','LA PINTANA','Part. Subvencionado'),
('11805','COLEGIO POLIVALENTE INGLES','Metropolitana','LA PINTANA','Part. Subvencionado'),
('11806','ESCUELA BASICA PARTICULAR ARMI','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('11809','ESC.PAR.MAURICE AND NATALY SCHOOL','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('11811','LICEO SANTA MARIA EUFRASIA','Metropolitana','SAN JOAQUÍN','Servicio Local'),
('11812','COLEGIO TOMAS MORO','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('11813','ESCUELA PARTICULAR ALVAREZ DE TOLEDO','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('11814','COLEGIO PESTALOZZI','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('11818','COMPLEJO EDUC.PARTICULAR DE LAS ACACIAS','Metropolitana','EL BOSQUE','Part. Subvencionado'),
('11828','ESCUELA ESPECIAL PARTICULAR SOR TERESA','Metropolitana','CERRILLOS','Part. Subvencionado'),
('11830','ESCUELA BASICA  1287 SAN MARCOS APOSTOL','Metropolitana','MAIPÚ','Part. Subvencionado'),
('11831','LICEO INDUSTRIAL BENJAMIN FRANKLIN','Metropolitana','QUINTA NORMAL','Municipal'),
('11835','ESCUELA PARTICULAR ROYAL SCHOOL','Metropolitana','LO PRADO','Part. Subvencionado'),
('11837','ESCUELA SAINT MARY SCHOOL','Metropolitana','COLINA','Part. Subvencionado'),
('11838','ESCUELA PART. STA. CLARISA DE COLINA','Metropolitana','COLINA','Part. Subvencionado'),
('11843','MASTER COLLEGE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('11845','ESCUELA PARTICULAR BELGICA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('11851','COLEGIO JOSE MANUEL BALMACEDA','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('11853','ESCUELA BAS. PARTICULAR MILLARAY','Metropolitana','PEÑAFLOR','Part. Subvencionado'),
('11854','ESCUELA BASICA PARTICULAR BRASILIA','Metropolitana','PADRE HURTADO','Part. Subvencionado'),
('11862','ESCUELA DE PARVULOS TRIBILIN','Metropolitana','ESTACIÓN CENTRAL','Part. Subvencionado'),
('11865','ESCUELA DE PARVULOS CONEJIN','Metropolitana','EL BOSQUE','Part. Pagado'),
('11867','COLEGIO UNIVERSAL SAN FRANCISCO','Metropolitana','TALAGANTE','Part. Subvencionado'),
('11870','ESC.BAS. PART. COLEGIO HAYDN DE SAN JOAQUIN','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('11871','COLEGIO PEDRO DE VALDIVIA','Metropolitana','PROVIDENCIA','Part. Pagado'),
('11878','ESCUELA ESPECIAL ARNOLD GESELL','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('11883','LICEO MUNICIPAL POLIVALENTE MARIA PINTO','Metropolitana','MARÍA PINTO','Municipal'),
('11886','ESCUELA BASICA EL CARMELO','Metropolitana','CURACAVÍ','Part. Subvencionado'),
('11906','ESCUELA BAS. LOS CARRERA','Metropolitana','SAN MIGUEL','Part. Subvencionado'),
('11909','ESCUELA PARTICULAR N°333 EL ANGEL','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('11914','ESCUELA BASICA Nº128 SAN RAMON','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('11915','ESCUELA DE PARVULOS N° 242 LOS CHIQUITITOS','Metropolitana','LO ESPEJO','Part. Pagado'),
('11918','FROILAN YAÑEZ DE LA BARRA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('11921','COLEGIO INFOCAP','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('11926','ESCUELA BASICA PARTICULAR ROQUER','Metropolitana','RENCA','Part. Subvencionado'),
('11928','ESCUELA ANTILLANCA','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('11931','CENTRO EDUC.PART.ORDEN DE SAN JORGE','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('11932','ESCUELA ESPECIAL JULIO BERNALDO QUIROS','Metropolitana','PAINE','Part. Subvencionado'),
('11936','COLEGIO JACQUES COUSTEAU','Metropolitana','MAIPÚ','Part. Subvencionado'),
('11942','COLEGIO ABERSAN','Metropolitana','COLINA','Part. Subvencionado'),
('11949','COLEGIO CRISOL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11950','COLEGIO MONTEVERDE','Metropolitana','PEÑALOLÉN','Part. Subvencionado'),
('11952','ESCUELA BELEN O¦HIGGINS','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('11956','ESCUELA BASICA  N°1226 PEPITA','Metropolitana','LA FLORIDA','Part. Pagado'),
('11959','ESCUELA DE PARVULOS N° 1300 ALVARO COVARRUBIAS A.','Metropolitana','INDEPENDENCIA','Part. Pagado'),
('11962','COLEGIO  PEDRO DE VALDIVIA-AGUSTINAS','Metropolitana','SANTIAGO','Part. Pagado'),
('11965','CENTRO EDUCACIONAL SAN LORENZO','Metropolitana','RECOLETA','Part. Subvencionado'),
('11966','COLEGIO PUCARA DE LOS ANDES','Metropolitana','LAS CONDES','Part. Pagado'),
('11968','COLEGIO CUMBRES','Metropolitana','LAS CONDES','Part. Pagado'),
('11971','COLEGIO SANTO DOMINGO_PADRES DOMINICOS','Metropolitana','LA REINA','Part. Pagado'),
('11977','SAINT CHRISTIAN COLLEGE','Metropolitana','LA GRANJA','Part. Subvencionado'),
('11979','COLEGIO MIGUEL ANGEL','Metropolitana','LA PINTANA','Part. Subvencionado'),
('11980','ESCUELA ESPECIAL PARTICULAR CECLA','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('11993','ESCUELA BASICA JUAN PABLO DUARTE','Metropolitana','PROVIDENCIA','Municipal'),
('11994','LICEO POLIVALENTE BAHIA DARWIN','Metropolitana','LA GRANJA','Part. Subvencionado'),
('11997','ESCUELA JOSE IBAÑEZ','Metropolitana','LA CISTERNA','Part. Subvencionado'),
('11998','ESCUELA BASICA PARTICULAR HUEÑECITO','Metropolitana','LA PINTANA','Part. Subvencionado'),
('12001','COLEGIO PARTICULAR EVANGÉLICO BETANIA','Ñuble','CHILLÁN','Part. Subvencionado'),
('12002','ESCUELA PARTICULAR TOQUI CAUPOLICAN','Biobío','CAÑETE','Part. Subvencionado'),
('12004','LICEO POLITECNICO CURANILAHUE','Biobío','CURANILAHUE','Part. Subvencionado'),
('12005','COLEGIO DON ORIONE','Biobío','LOS ÁNGELES','Part. Subvencionado'),
('12006','LICEO AGRICOLA SAN CARLOS','Ñuble','SAN CARLOS','Servicio Local'),
('12008','ESCUELA PARTICULAR AMERICO VESPUCIO','Biobío','CORONEL','Part. Subvencionado'),
('12013','JARDIN INFANTIL TIRITA DE PAPEL','Biobío','CONCEPCIÓN','Part. Pagado'),
('12014','ESCUELA DE PARVULOS Y ESC.ESP.LENG.DIVINO MAESTRO','Ñuble','CHILLÁN','Part. Subvencionado'),
('12015','COLEGIO CONCEPCION','Biobío','LOS ÁNGELES','Part. Pagado'),
('12018','ESCUELA EL RODEO','Ñuble','PINTO','Servicio Local'),
('12020','ESCUELA BASICA ENRIQUE ZANARTU PRIETO','Biobío','CABRERO','Corp. Municipal'),
('12022','ESCUELA BASICA CHACAYAL SUR','Biobío','LOS ÁNGELES','Corp. Municipal'),
('12023','COLEGIO BASICO SAN VICENTE','Biobío','TALCAHUANO','Corp. Municipal'),
('12024','THE WESSEX SCHOOL','Biobío','CONCEPCIÓN','Part. Pagado'),
('12025','COLEGIO ITAHUE DE CHIGUAYANTE','Biobío','CHIGUAYANTE','Part. Pagado'),
('12027','COLEGIO BICENTENARIO DE EXCELENCIA EL ÁRBOL DE LA VIDA','Ñuble','SAN CARLOS','Part. Subvencionado'),
('12031','COLEGIO SAN DIEGO DE ALCALÁ','Biobío','TUCAPEL','Part. Subvencionado'),
('12032','COLEGIO CHOLGUAN','Ñuble','YUNGAY','Part. Subvencionado'),
('12033','LICEO BICENTENARIO DE EXCELENCIA INDUSTRIAL METODISTA DE CORONEL','Biobío','CORONEL','Part. Subvencionado'),
('12035','JARDIN INFANTIL BARQUITO DE PAPEL','Biobío','TALCAHUANO','Part. Subvencionado'),
('12036','COLEGIO PINARES','Biobío','CHIGUAYANTE','Part. Pagado'),
('12037','LICEO POLIVALENTE HERMANAS MAESTRAS DE LA SANTA CRUZ','Biobío','LAJA','Part. Subvencionado'),
('12042','CENTRO EDUCACIÓN ADULTOS MANANTIAL DE AGUA VIVA','Biobío','LAJA','Part. Subvencionado'),
('12046','COLEGIO LORENZO MONDANELLI','Ñuble','COIHUECO','Part. Subvencionado'),
('12050','COLEGIO POLIVALENTE DARIO SALAS','Ñuble','CHILLÁN','Part. Subvencionado'),
('12051','ESCUELA ESPECIAL DE LA SOLIDARIDAD','Biobío','MULCHÉN','Corp. Municipal'),
('12052','CENTRO DE CAPACITACION LABORAL APANDI','Biobío','LOTA','Part. Subvencionado'),
('12055','COLEGIO TÉCNICO PROFESIONAL AMANCAY','Biobío','CONCEPCIÓN','Part. Pagado'),
('12058','ESCUELA BASICA LOS LIBERTADORES','Biobío','HUALQUI','Servicio Local'),
('12059','COLEGIO AGRÍCOLA LOS MAYOS','Biobío','SANTA BÁRBARA','Part. Subvencionado'),
('12062','LICEO MAURICIO HOCHSCHILD','Biobío','SAN PEDRO DE LA PAZ','Part. Subvencionado'),
('12063','THE THOMAS JEFFERSON SCHOOL','Biobío','TALCAHUANO','Part. Pagado'),
('12064','ESCUELA BASICA EL PIURE','Biobío','ARAUCO','Corp. Municipal'),
('12065','ESCUELA BASICA MELA','Ñuble','TREHUACO','Corp. Municipal'),
('12076','ESCUELA PARTICULAR SAN GUILLERMO','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('12077','COLEGIO SAN MIGUEL DE LOS ANDES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('12079','HERNAN MERINO CORREA','Metropolitana','SAN BERNARDO','Servicio Local'),
('12083','COLEGIO LO ERRAZURIZ','Metropolitana','MAIPÚ','Part. Subvencionado'),
('12085','COLEGIO CRISTIANO EMMANUEL','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('12086','COLEGIO COYANCURA','Metropolitana','LAS CONDES','Part. Pagado'),
('12087','COLEGIO BRITISH ROYAL SCHOOL','Metropolitana','LA REINA','Part. Pagado'),
('12090','COLEGIO TERRANOVA','Metropolitana','LA REINA','Part. Pagado'),
('12092','ESCUELA ESPECIAL ANADIME','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('12094','COLEGIO SAN ESTEBAN DIÁCONO','Metropolitana','VITACURA','Part. Pagado'),
('12095','ESC BAS PART COLEGIO CHILLAN','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('12097','ESCUELA ESPECIAL N°1327 ANAKENA','Metropolitana','LA FLORIDA','Part. Subvencionado'),
('12102','ESC. DE PARVULOS ALBERTO WIDMER N_ 2','Metropolitana','MAIPÚ','Part. Subvencionado'),
('12103','ESCUELA ESPECIAL DE EDUCACION','Metropolitana','LO ESPEJO','Servicio Local'),
('12105','ESCUELA BASICA Nº1343 `CEDEL INTEGRACION`','Metropolitana','LA PINTANA','Part. Subvencionado'),
('12108','ESCUELA PARTIC.DE PARVULOS MI PRINCESITA','Metropolitana','SAN JOAQUÍN','Part. Subvencionado'),
('12111','COLEGIO POLIV. PDTE. JOSE MANUEL BALMACEDA','Metropolitana','SAN BERNARDO','Part. Subvencionado'),
('12113','ESCUELA BASICA LO VELASQUEZ','Metropolitana','RENCA','Municipal'),
('12115','CENTRO EDUCACIONAL FEDERICO GARCIA LORCA','Metropolitana','RENCA','Part. Subvencionado'),
('12117','COMPLEJO EDUCACIONAL J. MIGUEL CARRERA','Metropolitana','QUILICURA','Servicio Local'),
('12118','ESCUELA CENTRO BIBLICO LA FORESTA','Metropolitana','MELIPILLA','Part. Subvencionado'),
('12119','ESCUELA DIFERENCIAL INTEGRACION','Metropolitana','MELIPILLA','Part. Subvencionado'),
('12121','ESCUELA MARIA DE LA PAZ','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('12122','ESCUELA EDUCADORA GABRIELA MISTRAL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('12126','ESCUELA BÁSICA Y ESPECIAL N°352 LAUTRARU','Metropolitana','LA PINTANA','Part. Subvencionado'),
('12130','ESCUELA MARIA TERESA SCHOOL NUM 2','Metropolitana','SANTIAGO','Part. Subvencionado'),
('12133','COLEGIO FRANCISCO ENCINA','Metropolitana','ÑUÑOA','Part. Pagado'),
('12136','ESCUELA ESPECIAL PART SANTIAGO SUR','Metropolitana','PEDRO AGUIRRE CERDA','Part. Subvencionado'),
('12143','ESCUELA ESPECIAL PARTICULAR GALVARINO','Metropolitana','SAN RAMÓN','Part. Subvencionado'),
('12146','CENTRO DE EDUCACIÓN INTEGRADA DE ADULTOS VALPARAÍSO','Valparaíso','VALPARAÍSO','Servicio Local'),
('12151','COLEGIO HISPANO AMERICANO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12157','ESCUELA ESPECIAL DE DESARROLLO','Valparaíso','QUILPUÉ','Municipal'),
('12171','ESCUELA BASICA HUMBERTO VILCHEZ ALZAMORA','Valparaíso','VIÑA DEL MAR','Servicio Local'),
('12175','ESCUELA PARTICULAR MARIANO LATORRE','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('12177','COLEGIO ANDRES BELLO','Valparaíso','CABILDO','Part. Subvencionado'),
('12182','ESCUELA PARTICULAR N.303 LUIS CRUZ MARTINEZ','Los Lagos','OSORNO','Part. Subvencionado'),
('12183','COLEGIO SAINT THOMAS COLLEGE','Los Lagos','OSORNO','Part. Subvencionado'),
('12185','COLEGIO BICENTENARIO HELVECIA','Los Ríos','VALDIVIA','Part. Subvencionado'),
('12188','ESCUELA CERRO ALEGRE','Los Ríos','RÍO BUENO','Part. Subvencionado'),
('12191','ESCUELA PARTICULAR N.308 EL MIRADOR','Los Lagos','LOS MUERMOS','Part. Subvencionado'),
('12192','INSTITUTO DEL MAR BICENTENARIO CAPITAN WILLIAMS','Los Lagos','CHONCHI','Part. Subvencionado'),
('12193','ESCUELA PARTICULAR N.310 RELDEHUE','Los Lagos','CHAITÉN','Part. Subvencionado'),
('12217','CENTRO POLITECNICO PARTICULAR DE NUNOA','Metropolitana','ÑUÑOA','Part. Subvencionado'),
('12221','ESCUELA ESPECIAL PARTICULAR REINA MARIA','Metropolitana','CONCHALÍ','Part. Subvencionado'),
('12225','COLEGIO BICENTENARIO SAN ESTEBAN MARTIR','Metropolitana','LO BARNECHEA','Part. Subvencionado'),
('12226','ESCUELA BASICA N°1355 IRARRAZAVAL','Metropolitana','ÑUÑOA','Part. Pagado'),
('12237','ESC.PART.COLEGIO LOS HALCONES','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('12241','COLEGIO CORAZON DE JESUS','Metropolitana','QUINTA NORMAL','Part. Subvencionado'),
('12242','COLEGIO PUDAHUEL','Metropolitana','PUDAHUEL','Part. Subvencionado'),
('12243','ESCUELA Nº 1365 R.P. GUSTAVO LE PAIGE','Metropolitana','RENCA','Municipal'),
('12244','COLEGIO EL SEMBRADOR','Metropolitana','PUENTE ALTO','Part. Subvencionado'),
('12249','ESCUELA ESPECIAL PONTIFICE JUAN PABLO II','Metropolitana','PEÑALOLÉN','Municipal'),
('12251','COLEGIO BATALLA DE LA CONCEPCION','Metropolitana','EL BOSQUE','Servicio Local'),
('12255','COLEGIO ALCAZAR','Metropolitana','MAIPÚ','Servicio Local'),
('12258','COLEGIO EMMANUEL MOUNIER','Metropolitana','PEÑAFLOR','Part. Pagado'),
('12260','COLEGIO SAN FRANCISCO DE ASIS DE BELEN','Metropolitana','SANTIAGO','Part. Subvencionado'),
('12265','COLEGIO THE SOUTHERN CROSS SCHOOL','Metropolitana','LAS CONDES','Part. Pagado'),
('12266','COLEGIO CIUDADELA MONTESSORI DE LAS CONDES','Metropolitana','LAS CONDES','Part. Pagado'),
('12268','COLEGIO MAYA SCHOOL','Metropolitana','ÑUÑOA','Part. Pagado'),
('12269','COLEGIO INSTITUTO SAN CARLOS','Metropolitana','LA PINTANA','Part. Subvencionado'),
('12273','ESC.MUNIC.DE PARVULOS HERNAN DEL SOL','Metropolitana','RENCA','Municipal'),
('12294','INSTITUTO CIEC','Valparaíso','VIÑA DEL MAR','Part. Pagado'),
('12295','COLEGIO SAN IGNACIO DE LA SSALLE','Valparaíso','QUILLOTA','Part. Pagado'),
('12299','ESCUELA BASICA ANEXO PICHILEMU','Valparaíso','LA LIGUA','Corp. Municipal'),
('12301','COLEGIO ESPAÑOL DE VIÑA DEL MAR','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12302','COLEGIO SAINT JULIAN COLLEGE','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12305','COLEGIO ALEXANDER FLEMING','Valparaíso','VILLA ALEMANA','Part. Subvencionado'),
('12309','COLEGIO PIRAMIDE','Valparaíso','SAN FELIPE','Part. Subvencionado'),
('12310','ESCUELA ESPECIAL DE LENGUAJE SAN ROQUE','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('12311','CTRO ESTUDIOS CAPACITACION PARA SORDOS','Valparaíso','VALPARAÍSO','Part. Subvencionado'),
('12312','COLEGIO REBECA FERNANDEZ','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12314','ESCUELA ATENAS','Valparaíso','OLMUÉ','Corp. Municipal'),
('12323','CENTRO EDUCACIONAL CRISOL','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12328','ALIANZA ALEMANA EL BELLOTO','Valparaíso','QUILPUÉ','Part. Subvencionado'),
('12330','COLEGIO CRISTIANO EBEN-EZER ANEXO','Valparaíso','VIÑA DEL MAR','Part. Subvencionado'),
('12332','LICEO POLITECNICO DE CON CON','Valparaíso','CONCÓN','Servicio Local'),
('12336','LICEO BICENTENARIO TECNICO PROFESIONAL DE MINERIA','Valparaíso','CABILDO','Corp. Municipal'),
('12366','ESCUELA ESPECIAL ARCO IRIS','La Araucanía','CARAHUE','Servicio Local'),
('12368','LICEO BICENTENARIO DE EXCELENCIA POLITÉCNICO SANTA CRUZ','La Araucanía','CUNCO','Part. Subvencionado'),
('12501','ESCUELA JORGE ALESSANDRI RODRIGUEZ','Arica y Parinacota','ARICA','Servicio Local'),
('12502','COLEGIO  ANDINO','Arica y Parinacota','ARICA','Part. Pagado'),
('12504','COLEGIO LITTLE COLLEGE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12505','COLEGIO PADRE LUIS GALLARDO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12509','LICEO PDTE. ANIBAL PINTO GARMENDIA.','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12510','JARDIN INFANTIL PAPELUCHO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12511','JARDIN INFANTIL NOCTILUCAS','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12512','JARDIN INFANTIL SAN NICOLAS','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12515','COLEGIO NUSTA KORI','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12518','COLEGIO DIOCESANO OBISPO LABBE','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12519','JARDIN INFANTIL CAPERUZO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12523','JARDIN INFANTIL EMMANUELITO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12534','LICEO COLEGIO METODISTA ROBERT JOHNSON','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12536','ESCUELA CRISOLVI','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12537','JARDIN INFANTIL CASCANUECES','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12538','ESCUELA CHIPANA','Tarapacá','IQUIQUE','Servicio Local'),
('12539','COLEGIO SAN JUAN DE LA BLACHERE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12542','ESCUELA CALETA SAN MARCOS','Tarapacá','IQUIQUE','Servicio Local'),
('12545','JARDIN INFANTIL EL LLAMITO','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12547','COLEGIO SAUCACHE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12549','C.T. C.Y LENGUAJE HISPANO AMERICANO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12550','OASIS EN EL DESIERTO','Tarapacá','POZO ALMONTE','Municipal'),
('12551','LIC.PADRE ALBERTO HURTADO CRUCHAGA','Tarapacá','PICA','Corp. Municipal'),
('12552','ESCUELA HUAVIÑA','Tarapacá','HUARA','Corp. Municipal'),
('12553','J. I. ANATIRI','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12554','ESCUELA DE SOGA','Tarapacá','HUARA','Corp. Municipal'),
('12555','JARDIN INFANTIL AYMARA AYRAMPITO','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12556','JARDIN INFANTIL PECECITO DORADO','Tarapacá','IQUIQUE','Part. Pagado'),
('12557','C.TRAST. DE LA COMUNIC. AMANECER','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12562','ESCUELA LAONZANA','Tarapacá','HUARA','Corp. Municipal'),
('12566','COLEGIO METODISTA WILLIAM TAYLOR','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12567','COLEGIO SAN ANTONIO DE MATILLA','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12568','JARDIN INFANTIL MANDALA GARDEN','Tarapacá','IQUIQUE','Part. Pagado'),
('12569','JARDIN INFANTIL BETHEL DE ARICA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12570','COLEGIO ALTA CORDILLERA','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12573','COLEGIO MARIA REINA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12579','ESCUELA LATINOAMERICANA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12584','JARDIN INFANTIL ECOSEMILLITA','Tarapacá','IQUIQUE','Part. Pagado'),
('12585','J.  I.  MI RINCON','Tarapacá','IQUIQUE','Part. Pagado'),
('12587','COLEGIO ARICA COLLEGE','Arica y Parinacota','ARICA','Part. Subvencionado'),
('12588','COLEGIO REINA DEL DESIERTO','Tarapacá','ALTO HOSPICIO','Part. Subvencionado'),
('12590','COLEGIO HISPANO ITALIANA','Tarapacá','IQUIQUE','Part. Subvencionado'),
('12591','LICEO SAMCA ARUMANTI','Tarapacá','IQUIQUE','Part. Subvencionado')
on conflict (rbd) do update set
  nombre = excluded.nombre,
  region = excluded.region,
  comuna = excluded.comuna,
  tipo = excluded.tipo;
commit;
